### ISSUE TITLE
Not able to read QR code from image 

### ISSUE THREAD

**Issue by Bhaskar971** [zxing/zxing#1000]
Hi All,

I have below image with a QR code in it. However, it is not recognized.  
![5_1_](https://user-images.githubusercontent.com/33713967/39278881-efdff664-4938-11e8-8d43-42351247892f.png)

The online reader is also not able to detect it. 
https://zxing.org/w/decode

Could you please advise.

**Comment by srowen** [comment]
The image actually has a lot of white noise, if you look carefully. It's a little too much. A simple low pass filter (blur) makes it decode, so you may want to preprocess your images this way too.

For example the attached decodes as "OAMQ0000212758_1_1"

<img width="191" alt="small" src="https://user-images.githubusercontent.com/822522/39279757-9ec8c40e-48c0-11e8-91d0-83566fd83277.png">
