### ISSUE TITLE
How to determine the decoder.decode() variables

### ISSUE THREAD

**Issue by PGMacDesign** [zxing/zxing#1002]
Hello all, as per the guidelines, I asked this question about a month ago [(here)](https://groups.google.com/forum/#!topic/zxing/U6Xm1-uqpa4) but I have yet to hear a response so I wanted to repost it here. 

I am working with and relatively new to PDF417 images and am trying to decode them. I am utilizing the com.google.zxing.pdf417.decoder.decode() method [(link) ](https://github.com/zxing/zxing/blob/04595508b63c3bde614b59dac361b50bfadb8757/core/src/main/java/com/google/zxing/pdf417/decoder/PDF417ScanningDecoder.java) and I see that the last 2 required parameters are: "int minCodewordWidth" and "int maxCodewordWidth".
Aside from the fact that I do not know how to obtain those, there is also a todo note up top that reads, "TODO don't pass in minCodewordWidth and maxCodewordWidth, pass in barcode columns for start and stop pattern columns".

At the time of this call, I have the bitmap image of the actual pdf417, the base64 String version of it, the BinaryBitmap, the ResultPoint array, and the PDF417DetectorResult(s). 

My question is, with the information I have, **how do I determine the required variables that are needed for this function**?

Thanks for the help, all!

**Comment by srowen** [comment]
Although it's public, this isn't the API you're meant to call. I think it's public mostly for legacy reasons (this code was copied from another project).  You should be using `PDF417Reader`.

**Comment by PGMacDesign** [comment]
@srowen Thanks! This did indeed do the trick.
