### ISSUE TITLE
StringUtils guessEncoding cannot diferentiate SJIS from UTF-8

### ISSUE THREAD

**Issue by Valarini** [zxing/zxing#1004]
When passing a byte array representing a text encoded in SJIS, the guessEncoding method from StringUtils misses, categorizing the text as UTF-8 encoded.

**Comment by srowen** [comment]
There is no way to disambiguate every byte sequence, because some byte sequences are a valid encoding of a string in SJIS and UTF-8. You don't provide any example or detail here.
