### ISSUE TITLE
Is it possible to decode the QR code image after shooting it with the camera?

### ISSUE THREAD

**Issue by AhnSungHyeon** [zxing/zxing#1011]
We are currently developing an application that uses the Zxing Library to scan QR codes.

The problem here is the time to recognize the QR code according to the camera performance of the smartphone scanning the QR code.

So the way I want to solve is to crop the QR code part of the image shot by the camera and then decode the QR code.

I looked for related materials and found the following material
https://stackoverflow.com/questions/32120988/qr-code-decoding-images-using-zxing-android
I tried but failed.

I can not find the cause of why I failed.

Below is the code I created.
I checked the error log.

-------------------------------------------------------------------------------------------------------------------
    public void QRCodeImage_to_Decode(Bitmap bitmap){

        Bitmap generatedQRCode = bitmap;
        Log.e("QRCodeImage_to_Decode","generatedQRCode : "+generatedQRCode);
        int width = generatedQRCode.getWidth();
        Log.e("QRCodeImage_to_Decode","width : "+width);
        int height = generatedQRCode.getHeight();
        Log.e("QRCodeImage_to_Decode","height : "+height);
        int[] pixels = new int[width * height];
        Log.e("QRCodeImage_to_Decode","pixels : "+pixels.length);
  

        RGBLuminanceSource source = new RGBLuminanceSource(width, height, pixels);
        Log.e("QRCodeImage_to_Decode","source : "+source);

        BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(source));
        Log.e("QRCodeImage_to_Decode","binaryBitmap : "+binaryBitmap);

        Reader reader = new MultiFormatReader();
        Log.e("QRCodeImage_to_Decode","reader : "+reader);
        Result result = null;
        Log.e("QRCodeImage_to_Decode","result#1 : "+result);
        try {
            result = reader.decode(binaryBitmap);

            Log.e("QRCodeImage_to_Decode","result#2 : "+result);
        } catch (NotFoundException e) {
            e.printStackTrace();
        } catch (ChecksumException e) {
            e.printStackTrace();
        }  catch (com.google.zxing.FormatException e) {
            e.printStackTrace();
        }
        //String text =  result.toString();
        String text =  result.getText();
        Toast.makeText(this,text,Toast.LENGTH_SHORT).show();
        Log.e("QRCodeImage_to_Decode","text : "+text);
-------------------------------------------------------------------------------------------------------------------
05-18 22:29:48.797 29910-29910/? E/QRCodeImage_to_Decode: generatedQRCode : android.graphics.Bitmap@872b97b
05-18 22:29:48.798 29910-29910/? E/QRCodeImage_to_Decode: width : 2291
05-18 22:29:48.798 29910-29910/? E/QRCodeImage_to_Decode: height : 2289
05-18 22:29:48.798 29910-29910/? E/QRCodeImage_to_Decode: pixels : 5244099
05-18 22:29:49.857 29910-29910/? E/QRCodeImage_to_Decode: source : ###################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
                                                          #######################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
05-18 22:29:51.975 29910-29910/? E/QRCodeImage_to_Decode: binaryBitmap : X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X
05-18 22:29:51.983 29910-29910/? E/QRCodeImage_to_Decode: reader : com.google.zxing.MultiFormatReader@d7ea398
05-18 22:29:51.983 29910-29910/? E/QRCodeImage_to_Decode: result#1 : null
05-18 22:29:52.781 29910-29910/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.cameranostest, PID: 29910
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.zxing.Result.getText()' on a null object reference
                                                       at com.example.cameranostest.Main2Activity.QRCodeImage_to_Decode(Main2Activity.java:336)
                                                       at com.example.cameranostest.Main2Activity.onCropImageComplete(Main2Activity.java:169)
                                                       at com.theartofdev.edmodo.cropper.CropImageView.onImageCroppingAsyncComplete(CropImageView.java:1180)
                                                       at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.onPostExecute(BitmapCroppingWorkerTask.java:245)
                                                       at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.onPostExecute(BitmapCroppingWorkerTask.java:23)
                                                       at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                       at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by srowen** [comment]
Sure, you can crop the image in your application code (see YUVPlanarLuminanceSource's constructor) to efficiently examine just part of the image. In my experience, even a large image decodes in milliseconds on a modern phone. I doubt you need this. But it's up to your code. You show an error in your app.
