### ISSUE TITLE
Don't see QR code, recognizable by cell phone application.

### ISSUE THREAD

**Issue by mordechaiguterman** [zxing/zxing#1014]
I have good QR code (image available by link)
https://www.dropbox.com/s/tx258i3snwgfgbd/bb5f5973-6662-46a8-b876-7b2bdbc972c8.png?dl=0

But it did not recognized both by zxing dll and zxing online tool.

Android application recognize it. 

What may be wrong with image?

**Comment by srowen** [comment]
I think it's the noise. Try a more original image and don't binarize it. Or apply a light blue.

**Comment by mordechaiguterman** [comment]
I have pdf that printed and scanned again.
I'm converting this pdf to png files with Ghostscript
sDevice = png16m;
-dTextAlphaBits=4;
-dGraphicsAlphaBits=4;

After that I am just taking part of image with QR code and trying to decode it.

There are no additional image transformation.

What should I do for stable recognition process?

**Comment by mordechaiguterman** [comment]
Also what do you mean by 'apply a light blur.'?

**Comment by srowen** [comment]
Whatever you are doing seems to dither to monochrome along the way. I wouldn't do that. Blur means apply a low pass filter, gaussian blur
