### ISSUE TITLE
scans EAN-13 codes starting with "0", gets UPC-A results without "0" in beginning

### ISSUE THREAD

**Issue by Saba-21** [zxing/zxing#1016]
barcode: https://user-images.githubusercontent.com/25323083/40483766-295ff230-5f6a-11e8-9a47-e7fb480d85a1.png
result: http://prntscr.com/jm0q26

**Comment by Saba-21** [comment]
source:[](https://user-images.githubusercontent.com/25323083/40483766-295ff230-5f6a-11e8-9a47-e7fb480d85a1.png)
result: [](http://prntscr.com/jm0q26)

**Comment by srowen** [comment]
The result is correct. UPC A is identical to EAN 13 beginning with 0.

**Comment by Saba-21** [comment]
@srowen thanks for response))
