### ISSUE TITLE
Does not meet the GS1 standard

### ISSUE THREAD

**Issue by MarkLogZhu** [zxing/zxing#1018]
Generate Data Matrix in the project, but it does not seem to meet the GS1 standard. I want to know how I can operate it to meet the standard。

  public Bitmap getDataMatrix(string inputData, int barcodeWidth, int barcodeHeight) {
           
            DatamatrixEncodingOptions options = new DatamatrixEncodingOptions() {
                Width = barcodeWidth,//宽度
                Height = barcodeHeight,//高度                
                Margin = 0,
                PureBarcode = true,

                SymbolShape = SymbolShapeHint.FORCE_SQUARE
            };
 
            options.Hints.Add(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
      
            BarcodeWriter writer = new BarcodeWriter() {
                Format = BarcodeFormat.DATA_MATRIX,
                Options = options
            };
            var img = writer.Write(inputData);

            return img;
            //return PictureUtils.Instance.zoomImage(PictureUtils.Instance.cutImageWhitePart(img, 1), barcodeWidth, barcodeHeight);

        }

**Comment by srowen** [comment]
You haven't provided any detail on the problem and this is code for a different project.
