### ISSUE TITLE
Rotated QR code can't be detected

### ISSUE THREAD

**Issue by skamenialo** [zxing/zxing#1022]
I've tested some distorted QR codes. Rotated and leaned symbol this way is detected really rare. On the other hand, if it is rotated 180 degrees, then can be detected.
![5](https://user-images.githubusercontent.com/9460632/41183769-a7db55c8-6b7c-11e8-9cad-166e16f90fc8.jpg)

**Comment by srowen** [comment]
It's actually not even skewed; it's compressed along a diagonal. This makes the QR code invalid. There is also a maximum skew that decoders are meant to tolerate. If this were actually a skewed image of a QR code I think it would be OK as the suggested skew isn't that severe. But, this image is no longer valid.

**Comment by skamenialo** [comment]
I don't agree.  This code was at first skewed (detected), next rotated 45 degrees (detected), and later 180 degrees (not detected). 
Hah. Changing code position and size of whole image have affect on detecting image.
Could you explain this? 
![5](https://user-images.githubusercontent.com/9460632/41185547-ae8dd708-6b89-11e8-9b1f-fe4707d0a423.jpg)

**Comment by srowen** [comment]
OK. I'm saying it's probably out of bounds of what _should_ be detectable. Skew isn't so bad, but significant. I also point out it's not really the result of an actual skew of a square, and that has a little bit of an implication in the math that assumes this to be so.

I think it can still be detected by good luck in similar situations, but not all of them. And that's what you find. There's not a bug here, because this image isn't the sort that definitely should decode.

**Comment by srowen** [comment]
There are a bunch of heuristics that help find the finder patterns quickly. They assume the image is a photo. The heuristics actually perform worst on images that are not from photos, but constructed synthetically like this one. It's just much easier to find white-black regions that look valid like finder patterns. So you may find that images that are near tolerances decode fine when they're "real" images, but happen to fail seemingly randomly when decoded from the original image. I think that's what happens here. 

It's not a bug insofar as 'fixing' that would probably mean compromising the speed or accuracy of these heuristics on real images, and that's the real use case.

I'm always open to changes that improve performance on the test set, but any individual "this doesn't scan" report is typically not a bug.

**Comment by skamenialo** [comment]
You are right. The most important is fast detecting a symbol. And nobody tries to detect it that way in "production".
Okay, so I have to modify this solution in my project. Thank you for your explanations.

**Comment by Willowlululu** [comment]
> There are a bunch of heuristics that help find the finder patterns quickly. They assume the image is a photo. The heuristics actually perform worst on images that are not from photos, but constructed synthetically like this one. It's just much easier to find white-black regions that look valid like finder patterns. So you may find that images that are near tolerances decode fine when they're "real" images, but happen to fail seemingly randomly when decoded from the original image. I think that's what happens here.
> 
> It's not a bug insofar as 'fixing' that would probably mean compromising the speed or accuracy of these heuristics on real images, and that's the real use case.
> 
> I'm always open to changes that improve performance on the test set, but any individual "this doesn't scan" report is typically not a bug.

Hello, I am using zxing to detect barcode .But I found that zxing performs not well about rotated 1D Barcodes. When I rotate the barcode from horizon to 30 degree it just detected failed. As I didn't found related documents about the rotation degree tolerance, I just hope that I could get help from u here. 
Looking forward to your reply, Thanks
