### ISSUE TITLE
Barcode found in normal Text

### ISSUE THREAD

**Issue by stephanprantl** [zxing/zxing#1031]
Hi,

I'm using the ZXing-Library (latest Version 3.3.3 from Maven-Repository) for a Desktop-Application which retrieves Data/Images from a desk scanner. The Images are at least in resolution of 240dpi and converted/saved to tiff.

Sometimes ZXing reacts quite curious when reading these images. Sometimes there is no Barcode where is one. Sometimes it reads an incorrect number and in the example-picture attached it reads a barcode from a normal line of text.

I converted and attached the original File as JPEG (same issue):
![orig](https://user-images.githubusercontent.com/20207286/41596155-b57815c2-73c9-11e8-8ff5-91c4f098d01b.jpg)

Also your Online-Decoder reads a Barcode from the Textline:
![zxing_barcode_from_text_onlineresult](https://user-images.githubusercontent.com/20207286/41596249-f93095aa-73c9-11e8-85ac-b040c200390c.PNG)

Code which is used and results in the incorrect Barcode:

    public static void main( String[] args ) throws IOException, NotFoundException
    {
        String filePath = args[0];
        BufferedImage image = ImageIO.read( new File( filePath ) );

        Map<DecodeHintType, Object> decodeHints = new EnumMap<>( DecodeHintType.class );
        decodeHints.put( DecodeHintType.TRY_HARDER, Boolean.TRUE );
        decodeHints.put( DecodeHintType.PURE_BARCODE, Boolean.FALSE );
        decodeHints.put( DecodeHintType.POSSIBLE_FORMATS, Arrays.asList( BarcodeFormat.EAN_13 ) );

        LuminanceSource source = new BufferedImageLuminanceSource( image );
        BinaryBitmap bitmap = new BinaryBitmap( new HybridBinarizer( source ) );

        GenericMultipleBarcodeReader reader = new GenericMultipleBarcodeReader( new MultiFormatReader() );
        Result[] results = reader.decodeMultiple( bitmap, decodeHints );
        for( Result result : results )
        {
            System.out.println( result.getText() );
        }
    }

**Comment by srowen** [comment]
Eventually you will find a black white pattern that looks close enough to a barcode in cross section that it succeeds. This is most common in images that are not photos and when using try-harder. It isn't going to bother to cross check additional lines. It is optimised for photos.
