### ISSUE TITLE
env.ANDROID_HOME problem with gradle and SpringBoot NOT SOLVED YET

### ISSUE THREAD

**Issue by dionren** [zxing/zxing#1037]
Previous 2 threads are closed, but the problem remain.

zxing 3.3.0 works fine, but 3.3.1 or later version, the problem occur.

NO relation with gradle versions, NO relation with SpringBoot versions.

> Task :ms-cv3:compileJava
Errors occurred while build effective model from C:\Users\dionr\.gradle\caches\modules-2\files-2.1\com.google.zxing\core\3.3.1\d1e7c4667f9dcdda30d09f3df7d1b44f65c44336\core-3.3.1.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is ${env.ANDROID_HOME}/platforms/android-22/android.jar in com.google.zxing:core:3.3.1
Errors occurred while build effective model from C:\Users\dionr\.gradle\caches\modules-2\files-2.1\com.google.zxing\javase\3.3.1\357121cdf3f89f63ddfaad18170612dcad0db947\javase-3.3.1.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is ${env.ANDROID_HOME}/platforms/android-22/android.jar in com.google.zxing:javase:3.3.1

**Comment by srowen** [comment]
Looks like ANDROID_HOME is not set.

**Comment by dionren** [comment]
It's not rational to set ANDROID_HOME in a java project.

**Comment by srowen** [comment]
I am not even sure what this means?

**Comment by flashing** [comment]
> I am not even sure what this means?

I am fighting with this problem now. With gradle and springboot 2.0.6, 
compile "com.google.zxing:javase:3.3.3"
under Windows system, I've got this (but it's totally ok under MacOS mojave):
Errors occurred while build effective model from C:\Users\ken\.gradle\caches\modules-2\files-2.1\com.google.zxing\javase\3.3.3\dd6a981a04a79aa686515a11cd09d049e202a32\javase-3.3.3.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.google.and
roid:android:jar must specify an absolute path but is /${env.ANDROID_HOME}/platforms/android-22/android.jar in com.google.zxing:javase:3.3.3
Errors occurred while build effective model from C:\Users\ken\.gradle\caches\modules-2\files-2.1\com.google.zxing\core\3.3.3\3fc07a37b124d3f9e134854b4c7bf7dc120bcae7\core-3.3.3.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is /${env.ANDROID_HOME}/platforms/android-22/android.jar in com.google.zxing:core:3.3.3
Hibernate JPA 2 Static-Metamodel Generator 5.2.17.Final

**Comment by srowen** [comment]
I think you're specifying a Windows-style path. I think a Linux-style path is required even when you're on Windows (it'll get translated). See https://github.com/zxing/zxing/issues/904 . You can disable the Android stuff if you don't need it (it is not enabled by default but see issue) or just modify the POM

**Comment by flashing** [comment]
> I think you're specifying a Windows-style path. I think a Linux-style path is required even when you're on Windows (it'll get translated). See #904 . You can disable the Android stuff if you don't need it (it is not enabled by default but see issue) or just modify the POM

I read that thread (issues-904)again and make sure there is no Windows-style path in my build.gradle file.
It's wired that version 3.3.0 is OK.

**Comment by srowen** [comment]
ANDROID_HOME is set? I think this is a gradle vs maven pom thing

**Comment by flashing** [comment]
> ANDROID_HOME is set? I think this is a gradle vs maven pom thing

The thing is I am not an android developer, and just want use zxing to generate qrcode image for apps to scan for payment. I use artifact javase(or core is the same error output) and got this error, am I doing something wrong or what?
I am now doing some test to confirm what cause this, gradle, gradle's setting file, spring boot or something else and I will post my result here.
But still, with all due respect, since zxing is the most popular qr code component(and now is the only choice?) and we trust google, this error really should not exist for such a long time...

**Comment by srowen** [comment]
Please see the other issue. This is a gradle problem. The Android profile is _not_ active unless you enable it with ANDROID_HOME. This can't be fixed in this project, which is correctly declaring its pom file.

**Comment by flashing** [comment]
> Please see the other issue. This is a gradle problem. The Android profile is _not_ active unless you enable it with ANDROID_HOME. This can't be fixed in this project, which is correctly declaring its pom file.

It's now pretty sure that this warning is caused by spring-boot's gradle plugin, as that issue said.
I dig this because version 3.3.0 works fine really makes me confusing.
I don't think this is a gradle problem because a simple gradle java application without springboot works fine, but all versions including springboot 1.5.x,2.0.x,2.1.x, will output this warning message during gradle's building process.
I am working for a project's coming deadline and really don't have more time to find out the truth behind... since I only use ZXing to generate simpile code image, I will return back to version 3.3.0. But I will really appreciate if anyone can fix this...

**Comment by suiaing** [comment]
Is there any solution or workaround ?

**Comment by ahmad3ttallah** [comment]
any updates on that issue?

**Comment by srowen** [comment]
Folks: this is a gradle issue. This project is built with Maven, not gradle. If it's not reading Maven profile activations as intended, you can manually delete the profiles.

**Comment by lrxw** [comment]
How can I fix that for my project if I use gradle? I don't understand either why android specific things are put into the core component.

**Comment by srowen** [comment]
Just chop out references to the Android modules from the parent pom.xml file.
They are _not_ in the core module. Are y'all even reading the build?

**Comment by rivancic** [comment]
I Agree with @lrxw Android specific configuration / logic should be in zxing android dependency.

**Comment by srowen** [comment]
Folks: the Android build stuff is in the android modules. The top level POM has common config to do things like even activate the Android modules.
