### ISSUE TITLE
Inverse Datamatrix not scanning (white on brown)

### ISSUE THREAD

**Issue by havardo** [zxing/zxing#1038]
The enclosed barcodes works fine with Zebra/Motorola scanners. However, the "official" ZXing Android app does not manage these unfortunatly (Datamatrix and inverse are both enabled). 

Is this a bug or are inverse datamatrix not supported?
![inversedm1](https://user-images.githubusercontent.com/5795624/42123991-59a79d52-7c53-11e8-8dfc-9bec2f88ef94.jpg)
![inversedm2](https://user-images.githubusercontent.com/5795624/42123992-59be533a-7c53-11e8-9458-ebe4646da498.jpg)

**Comment by havardo** [comment]
Duplicate of #194

**Comment by srowen** [comment]
The library doesn't look for inverted codes but it's trivial to invert the image and then scan it. This is what the app tries if set to do so. But the inverse happens in the camera and that doesn't work all the time. Check you turned on inverse scanning.
