### ISSUE TITLE
Adding ECI information when not necessary breaks some old readers

### ISSUE THREAD

**Issue by Canos** [zxing/zxing#1042]
In a former version of the Encoder.java class we can find this code.

## Previous versions
```
// Append ECI segment if applicable
    if (mode == Mode.BYTE && (hasEncodingHint || !DEFAULT_BYTE_MODE_ENCODING.equals(encoding))) {
      CharacterSetECI eci = CharacterSetECI.getCharacterSetECIByName(encoding);
      if (eci != null) {
        appendECI(eci, headerBits);
      }
    }
```

## Current version
```
// Append ECI segment if applicable
    if (mode == Mode.BYTE && hasEncodingHint) {
      CharacterSetECI eci = CharacterSetECI.getCharacterSetECIByName(encoding);
      if (eci != null) {
        appendECI(eci, headerBits);
      }
    }
```

The OR condition has been remove in newer versions.
I would like to humbly ask if it would be possible to have a stronger options like this one

## Proposal
`if (mode == Mode.BYTE && hasEncodingHint && !DEFAULT_BYTE_MODE_ENCODING.equals(encoding)) {`

The reason is that some old gun readers aren't prepared to read the ECI information and the read will fail if we add this ECI information (DATALOGIC QD2430 is a current example), some frameworks like jasper reports new versions are sending the Character encoding as hint ALWAYS, (i've warned them if so) but I hope it would be a stronger solution if you also check this.

Thanks for your awesome work.

**Comment by srowen** [comment]
The clause that was removed should be redundant and the behavior identical to before. If a hint is set the ECI segment is always there. So, at least this wasn't the issue. 

Yeah, best to not set the hint if it isn't desired. I see your problem though. Really you are proposing setting the segment if and only if it's not the default encoding. 

The only issue with this, I suppose, is that you can no longer force the ECI segment to appear. I'm comparing that behavior change to the value of working around the third party tool here; not sure which is more important. 

What about generating the barcodes directly? You can call the online encoder by URL to generate the image, so ought to be pretty integrateable into reports.

**Comment by Canos** [comment]
> What about generating the barcodes directly? You can call the online encoder by URL to generate the image, so ought to be pretty integrateable into reports.

That's a great idea but since QR building is a critical issue in a ticketing company, we discarded the online generated option. 

I managed to override the propperly class in jasper reports and I could remove the hint then, so i fixed the problem. Thanks
