### ISSUE TITLE
Data Matrix  - using zxing.dll Interop VB Script  (Margin Issue)

### ISSUE THREAD

**Issue by ClassicDude** [zxing/zxing#1043]
I just want to point out regarding data matrix - there is issue with 'margin' size for the output image.

here is the code I've used:

  qrCodeOptions.Height = 35
  qrCodeOptions.Width = 35
  qrCodeOptions.Margin = 0
  qrCodeOptions.PureBarcode = True
  qrCodeOptions.DefaultEncodation = ZXing.Datamatrix.Encoder.Encodation.ASCII
  qrCodeOptions.SymbolShape = ZXing.Datamatrix.Encoder.SymbolShapeHint.FORCE_SQUARE

As you can see below images:

This is original image size: 

![datamatrix_4a7-c30-024-805](https://user-images.githubusercontent.com/41024771/42995244-44b8f5fc-8c08-11e8-83c3-0fc19717a187.png)

This isn't right size - margin become bigger and data matrix become much smaller why?

![datamatrix_3ae-d0d-e41-fb5](https://user-images.githubusercontent.com/41024771/42995243-44a080c6-8c08-11e8-99e1-94f7afba4f0c.png)

for your information: both data come in random alphanumeric as 15 char max

**Comment by srowen** [comment]
This is actually code from another project.
