### ISSUE TITLE
Crash when scanning a VCard QR code on Android

### ISSUE THREAD

**Issue by SopaXorzTaker** [zxing/zxing#1045]
Hello, I'm using the official ZXing app from Google Play (version 4.7.7) on Android 7.1.2 (My phone is a Xiaomi Redmi 5A, MIUI 9.5.10.0 Global Stable).

I've randomly stumbled upon this QR code (attached) and decided to scan it out of curiosity.
But, for some reason, when I attempt to scan it, the application crashes.

![qrcrash](https://user-images.githubusercontent.com/6389052/43067635-94afb414-8e70-11e8-9743-e20f246e9145.png)

Perhaps it has something to do with the VCard parsing code?
The built-in camera application (which also integrates a QR reader) can read and parse that symbol successfully.

**Comment by SopaXorzTaker** [comment]
Note: the on-line reader at zxing.org can also understand that image without a problem, but it doesn't parse the VCard data, so that might be the case.

**Comment by srowen** [comment]
I can't reproduce with the latest app. I suspect it was simply a bug that was fixed along the way. You'd have to post a stack trace otherwise.

**Comment by SopaXorzTaker** [comment]
Here's the relevant log I obtained via adb.

`
07-23 18:06:20.859 11607 11607 D AndroidRuntime: Shutting down VM
07-23 18:06:20.860 11607 11607 E AndroidRuntime: FATAL EXCEPTION: main
07-23 18:06:20.860 11607 11607 E AndroidRuntime: Process: com.google.zxing.client.android, PID: 11607
07-23 18:06:20.860 11607 11607 E AndroidRuntime: java.lang.IllegalArgumentException: Expected scheme-specific part at index 4: tel:
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at java.net.URI.create(URI.java:854)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at com.google.zxing.client.result.VCardResultParser.matchVCardPrefixedField(VCardResultParser.java:199)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at com.google.zxing.client.result.VCardResultParser.parse(VCardResultParser.java:3068)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at com.google.zxing.client.result.ResultParser.parseResult(ResultParser.java:90)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at com.google.zxing.client.android.CaptureActivityHandler.handleMessage(CaptureActivityHandler.java:2062)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6221)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 4: tel:
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at java.net.URI$Parser.fail(URI.java:2856)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at java.net.URI$Parser.failExpecting(URI.java:2862)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at java.net.URI$Parser.parse(URI.java:3065)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at java.net.URI.<init>(URI.java:590)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	at java.net.URI.create(URI.java:852)
07-23 18:06:20.860 11607 11607 E AndroidRuntime: 	... 10 more
`

**Comment by srowen** [comment]
Yeah that's already fixed in `master`; if it's not already in the current app it'll be in the next release.

**Comment by SopaXorzTaker** [comment]
Okay, thanks!
