### ISSUE TITLE
 Improper Output Neutralization for Logs (CWE ID 117) (CRLF Injection)

### ISSUE THREAD

**Issue by Dharmaraj-Rupakheti** [zxing/zxing#1051]
**### Bug Reports**

We are using Zxing library (com.google.zxing:core: 3.3.3) on our project. And We did Vera Code (Ref: https://www.veracode.com ) Scan to find out the flaws and fix them. And We got the Improper Output Neutralization for Logs (CWE ID 117) (CRLF Injection) flaws on DecodeHintManager.java (Line Number: 227). It is producing by writing untrusted data into a log file allows an attacker to forge log entries or inject malicious content into log files.

**Current Code, which produce this flaw**
Log.w(TAG, "Ignoring hint " + hintType + " because it is not assignable from " + hintData);

**Recommendations**
Avoid directly embedding user input in log files when possible. Sanitize untrusted data used to construct log entries by using a safe logging mechanism such as the OWASP ESAPI Logger, which will automatically remove unexpected carriage returns and line feeds and can be configured to use HTML entity encoding for non-alphanumeric data. Only write custom blacklisting code when absolutely necessary. Always validate untrusted input to ensure that it conforms to the expected format, using centralized data validation routines when possible.  (Taking reference from Vera Code Scan Report Recommendation). 

Can you guys please help to fix this issue ? I know, we can use the temporary Mitigation action (https://help.veracode.com/reader/DGHxSJy3Gn3gtuSIN2jkRQ/~p4MSKOS8F8X8h0KwFTKoQ) But I think, this is not good idea to avoid the issue instead of fix, if possible. Thanks!

**Comment by srowen** [comment]
Yeah, that's a fair point. I don't see a way that it's a security issue in this case, because neither the user nor app uses the log output. It might confuse a developer though. I think I will remove a number of log statements that could have external input because they aren't that useful anyway.

The web app may also need review like this too.

**Comment by Dharmaraj-Rupakheti** [comment]
Cool. Sounds Good. Thanks so much @srowen for quick fix.
