### ISSUE TITLE
Project with a drone

### ISSUE THREAD

**Issue by il421** [zxing/zxing#1054]
Hello,
I have a project. I need to scan 1 D and 2 D barcodes by using DJI Phantom 4 drone camera feed, via an Android app. Now I am getting the picture through DJI SDK (using TextureView). I do want to implement your library. I have some questions:
1. Is it possible?
2. Can I scan form the video stream?
3. Can I scan and recognize a few barcodes in one frame in the same time?
4. Can I scan from various rotations of barcodes?

Thank you for your help in advance. 
PS If you can give me some tips about the implementing.

**Comment by srowen** [comment]
If it's an Android app, sure you should be able to integrate scanning. Yes, the app in this project scans from a video stream. You can potentially read multiple barcodes at once but it is unlikely to work from a stream. Rotations work, depending on the format.

This should generally go to the mailing list: https://groups.google.com/forum/#!forum/zxing
