### ISSUE TITLE
Orientation problem

### ISSUE THREAD

**Issue by Nanetto** [zxing/zxing#1059]
Hi,
I'm on xiaomi redmi note 5 android 8.1.0 version. The phone is in automatic rotation.
The screen when capturing barcode is always orizzontal. Help screen and setting screen are ok.
I tried thiking and unthiking the "no automatic rotation" box, closing and restarting the app but nothing change. Similar apps works fine
![screenshot_barcode_scanner_20180829](https://user-images.githubusercontent.com/42812965/44801782-441fc680-abba-11e8-8777-673c4c79e436.jpg)
Thanks

**Comment by srowen** [comment]
The app is landscape-only, and is EOL, so auto rotation isn't going to be added.

**Comment by beta-tester** [comment]
i have the same annoying orientation issue.
i would like to use the App in portrait mode.

@srowen , does EOL mean "end of live"?
so the android Barcode Scanner app in the Google Play store is also EOL?

i like your Barcode Scanner app so much. so useful, so minimal, no ads, no tracking,

**Comment by srowen** [comment]
Yes, sorry, it cannot be updated anymore

**Comment by beta-tester** [comment]
so i should not use ie as template for my own app in the future?
is `android-core` and `android-integration` also EOL?

is [journeyapps/zxing-android-embedded](https://github.com/journeyapps/zxing-android-embedded) then a better solution to start creating a barcode scanner app for android?

**Comment by srowen** [comment]
Nothing in the project is going to be updated, but you can reuse parts as you like. The core is still quite usable, just the app, no. I have generally discouraged people from copying the app entirely anyway

**Comment by beta-tester** [comment]
with **nothing** you mean the whole **zxing** project, not only the android part?

**Comment by srowen** [comment]
The whole project is in maintenance mode, maybe minor improvements and fixes to the core, but nothing for the app. I would not expect any particular changes

**Comment by beta-tester** [comment]
ok, thank you.for all the work.

PS.: i just found another project from you, [Barcode Scanner Plus](https://github.com/srowen/zxing-bsplus), that is oriented in portrait mode, but its `core` seems to be outdated, even the "Plus" suggest an advanced and newer app.

PPS.: i am wondering, was the landscape orientation chosen to have more pixel for a 1D barcode scan? then it makes sense.

please forgive all my stupid questions

**Comment by srowen** [comment]
Right, it was a for-pay app with more advanced features. Most were back-ported to the OSS app. But both are long since not updated. It's possible to implement for sure, just didn't get around to back-porting that part and I can't update the app anymore either
