### ISSUE TITLE
Source code encoding

### ISSUE THREAD

**Issue by Acolyte** [zxing/zxing#1060]
There are quite a few files in the source that have incorrect encoding that, when being compiled, produce errors during javadoc generation stage.
![ipdj8w7](https://user-images.githubusercontent.com/994225/44851628-041c1a80-ac72-11e8-9267-dc913cfa6b48.png)

**Comment by srowen** [comment]
They should all be UTF-8. Something on your end is assuming the encoding is ASCII, which is wrong. Are you sure your tools haven't maybe modified the encoding, or you've changed your tool set to assume ASCII?

I think we can explicitly tell the javadoc plugin to assume UTF-8, but I suspect you can also adjust it on your end.

**Comment by srowen** [comment]
Try again from master, after https://github.com/zxing/zxing/commit/a010db7fe20287a4b79382688001be7d3bc2fc27
