### ISSUE TITLE
Update wiki content: https://github.com/zxing/zxing/wiki/Barcode-Contents

### ISSUE THREAD

**Issue by skyzyx** [zxing/zxing#1061]
Some of this information is outdated, and incorrect as of iOS 11. I would be happy to update some of it, but it appears that the wiki editing is set to contributor-only.

**Comment by srowen** [comment]
Sure, I just turned on editing for everyone temporarily. Go ahead.

**Comment by srowen** [comment]
@skyzyx are you OK on edits now?
