### ISSUE TITLE
Barcode with small size not getting detected on 5mp-omnivision-ovs5640-camera-module-board with Inforce 6401 Development Kit. 

### ISSUE THREAD

**Issue by Gmrevo** [zxing/zxing#1064]
The application detects the same barcodes on the mobile phone but when we are checking the application with our custom device, It's unable to detect. It detects bar code of large size correctly. 
Can anyone suggest a solution and an approach to overcome the issue?

**Comment by srowen** [comment]
The usual explanation is lack of autofocus or problems in the driver or different min focus distance. I don't think there is a software solution if so. This library is EOL.
