### ISSUE TITLE
Nothing happens after clicking

### ISSUE THREAD

**Issue by PawelCyrklaf** [zxing/zxing#1065]
Hi :)
I am trying to do a barcode scanner in Xamarin using ZXing based on this page: github.com/Redth/ZXing.Net.Mobile

I've been fighting this since yesterday and I have no idea what might be wrong, the videos are working and in my case I have no chance :(

I use vs 2017 Community and packages:

-  ZXing.Net.Mobile.Forms - 2.4.1
-  ZXing.Net.Mobile - 2.4.1
- Xamarin.Forms - 3.1.0.697729

My project to download if someone would like to see the whole code: [http://cyrklaf.eu/skaner.rar](http://cyrklaf.eu/skaner.rar)
I'm missing ideas, like a simple thing, and the problems themselves

My code:
```
scanPage = new ZXingScannerPage ();
             scanPage.OnScanResult + = (result) =>
             {
                 scanPage.IsScanning = false;
                 Device.BeginInvokeOnMainThread (() =>
                 {
                     Navigation.PopAsync ();
                     DisplayAlert ("Scanned Barcode", result.Text, "OK");
                 });
             };
             await Navigation.PushAsync (scanPage);
```

**Comment by srowen** [comment]
This is about a separate project.
