### ISSUE TITLE
Zxing to support -> Restrictions on non-SDK interfaces on Android Pie

### ISSUE THREAD

**Issue by KevinLeigh** [zxing/zxing#1066]
As of Android Pie, there is restrictions for using non-SDK interfaces. Please see documentation here -> https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces

Will Zxing be updated to fully support Restrictions on non-SDK?

**Comment by srowen** [comment]
The app isn't going to updated further at all; it's EOL except for occasional bug fix releases, and now we can't upload the app anymore after November. That said I don't think there are any uses of class by reflection in the app.
