### ISSUE TITLE
Support for QR Code Model 1

### ISSUE THREAD

**Issue by george-hopkins** [zxing/zxing#1067]
In a project I recently worked on, we needed to scan some old QR codes (Model 1) as specified in ISO 18004:2000 Annex M. Due to the existing code base here, the implementation was rather straight forward.
Is there any interest in including it? (So far, only #156 and some old posts on the mailing list mention it.) If so, I would clean up my patchset and prepare a pull-request.

**Comment by george-hopkins** [comment]
Alright, I completely understand your hesitation. Unfortunately the patch didn't turn as nice as I'd like to be. If anyone needs support for model 1, please feel free to check out [`qrmodel1` on my fork](https://github.com/george-hopkins/zxing/tree/qrmodel1).

**Comment by Rsathishkumar87** [comment]
![qr1nirmal](https://user-images.githubusercontent.com/44689465/64249332-0c67ff00-cf31-11e9-9c21-bd225eff193e.jpg)
this qr code not decoded

**Comment by kuangguo** [comment]
> 好吧，我完全理解你的犹豫。不幸的是，补丁并没有像我想要的那样好。如果有人需要模型 1 的支持，请随时查看[`qrmodel1`我的叉子](https://github.com/george-hopkins/zxing/tree/qrmodel1)。



> ![qr1nirmal](https://user-images.githubusercontent.com/44689465/64249332-0c67ff00-cf31-11e9-9c21-bd225eff193e.jpg) qr model1 code not decoded

Have you solved it？
