### ISSUE TITLE
EAN 128 not found...!

### ISSUE THREAD

**Issue by v4l3r10** [zxing/zxing#107]
Hi!
i'm trying do decode this EAN128 barcode but not work with zxing
https://dl.dropboxusercontent.com/u/6140898/Temp/ean128.jpg

result with bcTester:
https://dl.dropboxusercontent.com/u/6140898/Temp/bcTester.jpg

**Comment by ZineddineHarakat** [comment]
How can i display EAN 128 barcode separator during scan please ?
