### ISSUE TITLE
Scans only in landscape mode, may show a black screen.

### ISSUE THREAD

**Issue by CoolMind** [zxing/zxing#1071]
Using library v. 3.3.0 it can only recognize a QR in landscape mode. Also if start an app when a screen is turned off, then turn it on, it shows black screen with text views, but no camera preview.

Why didn't you make a portrait oreintation?

**Comment by srowen** [comment]
Don't know, this sounds like an issue with your app. QR codes can be scanned in any orientation.
Portrait mode was implemented in the "plus" version. This app is discontinued.

**Comment by CoolMind** [comment]
Sorry, maybe I made something wrong, but I also noticed this situation in android sample of the library.

**Comment by stefan222** [comment]
@CoolMind Have you found a solution?

**Comment by CoolMind** [comment]
@stefan222, yes, I turned to https://github.com/dm77/barcodescanner. Sorry. :)
