### ISSUE TITLE
Datamatrix (144x144) cannot be decoded

### ISSUE THREAD

**Issue by bommo1** [zxing/zxing#1077]
The following datamatrix code cannot be decoded. There must be something special about it as only half of the open source and commercial libraries I've tried manage to read it ([this one](https://online-barcode-reader.inliteresearch.com/) for example does). Any hint would be appreciated.

![37153710-efe509fa-22dd-11e8-94bb-bf42e5bfbaf0](https://user-images.githubusercontent.com/32093209/46076584-40b63580-c18e-11e8-8b14-fa009233b124.png)

**Comment by srowen** [comment]
It's either some slight problem from the image distortion here (see bottom and right edge), something the library doesn't support, or a bug. Unless you have a PR to consider though I'd have to close this. This project is dormant now.
