### ISSUE TITLE
Barcodes at a small angle are not regognized

### ISSUE THREAD

**Issue by ochakov** [zxing/zxing#1079]
Here is a sample barcode that is not recognized. Rotating the image will make zxing recognizing the barcode.

![2645015](https://user-images.githubusercontent.com/5604370/46434031-6d36f800-c720-11e8-9935-7fbe3d4863b5.jpg)

**Comment by srowen** [comment]
Yes, it is too rotated and there is no horizontal line that crosses the whole barcode. This is not how this barcode was designed to be read
