### ISSUE TITLE
Unable to Scan QR-Code

### ISSUE THREAD

**Issue by Trust-Coder** [zxing/zxing#1084]
I just implemented this library for my client and its working fine, but having a trouble while scanning a QR-Code. 

![qr code](https://user-images.githubusercontent.com/35214797/46791052-b955ee00-cd59-11e8-8c21-f01235cc7054.jpg)

The code is scanned fine on other apps which have used this library but don't know why it doesn't work on my app. My App scans all other QR-Codes but gives issue on this type only. Attaching my apk below, please give me some suggestions.
[app-debug.zip](https://github.com/zxing/zxing/files/2468013/app-debug.zip)

**Comment by Trust-Coder** [comment]
**SCAN FRAGMENT CODE**

`package com.trustcoder.TILBBC.fragments;

import android.os.Bundle;
import android.os.Handler;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.Toast;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.Result;
import com.trustcoder.TILBBC.R;
import com.trustcoder.TILBBC.interfaces.ScanFragmentCallbackListener;
import com.trustcoder.TILBBC.models.LinkedData;

import java.util.ArrayList;
import java.util.List;

import me.dm7.barcodescanner.zxing.ZXingScannerView;

public class ScanFragment extends Fragment implements ZXingScannerView.ResultHandler, View.OnClickListener {
    private static final long SPLASH_DISPLAY_LENGTH = 1000;

    private Handler handler;
    private Runnable runnable;

    enum SCAN_STATE{A,B,C,D,E,F}          // (A.C + B.D) . E

    private SCAN_STATE state = SCAN_STATE.A;

    private ImageView imageBarcode;
    private ImageView imageBeacon;
    private ImageView imageLinkSign;

    private ImageView imageBarcodeSelected;
    private ImageView imageBeaconSelected;

    private ImageView imageBarcodeScanned;
    private ImageView imageBeaconScanned;
    private ImageView imageLinkSignScanned;


    private static final String FLASH_STATE = "FLASH_STATE";
    private static final String AUTO_FOCUS_STATE = "AUTO_FOCUS_STATE";
    private static final String SELECTED_FORMATS = "SELECTED_FORMATS";
    private static final String CAMERA_ID = "CAMERA_ID";
    private ZXingScannerView mScannerView;
    private boolean mFlash;
    private boolean mAutoFocus;
    private ArrayList<Integer> mSelectedIndices;
    private int mCameraId = -1;

    private ScanFragmentCallbackListener callBackListener = null;

    private LinkedData linkedData = new LinkedData();

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_scan, null);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        initUI(view); //Initialize UI
        processState();

        mScannerView = view.findViewById(R.id.scanner_view);
        if(savedInstanceState != null) {
            mFlash = savedInstanceState.getBoolean(FLASH_STATE, false);
            mAutoFocus = savedInstanceState.getBoolean(AUTO_FOCUS_STATE, true);
            mSelectedIndices = savedInstanceState.getIntegerArrayList(SELECTED_FORMATS);
            mCameraId = savedInstanceState.getInt(CAMERA_ID, -1);
        } else {
            mFlash = false;
            mAutoFocus = true;
            mSelectedIndices = null;
            mCameraId = -1;
        }
        setupFormats();

        if(savedInstanceState != null)
        {
            String sState = savedInstanceState.getString("state");
            linkedData.setBarcode(savedInstanceState.getString("barcode"));
            linkedData.setBeacon(savedInstanceState.getString("beacon"));

            if (sState != null) {
                switch (sState.charAt(0))
                {
                    case 'A':
                        state = SCAN_STATE.A;
                        break;
                    case 'B':
                        state = SCAN_STATE.B;
                        break;
                    case 'C':
                        state = SCAN_STATE.C;
                        break;
                    case 'D':
                        state = SCAN_STATE.D;
                        break;
                    case 'E':
                        state = SCAN_STATE.E;
                        break;
                    case 'F':
                        state = SCAN_STATE.D;
                        break;
                }
            }

            processState();
        }
        else
        {
            imageLinkSignScanned.setVisibility(View.INVISIBLE);
            imageLinkSign.setVisibility(View.VISIBLE);
        }



        handler = new Handler();
        runnable = new Runnable() {
            @Override
            public void run() {
                mScannerView.resumeCameraPreview(ScanFragment.this);
            }
        };
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        if (getActivity() instanceof ScanFragmentCallbackListener)
            callBackListener = (ScanFragmentCallbackListener) getActivity();
    }

    @Override
    public void onResume() {
        super.onResume();
        mScannerView.setResultHandler(this);
        mScannerView.startCamera(mCameraId);
        mScannerView.setFlash(mFlash);
        mScannerView.setAutoFocus(mAutoFocus);
    }

    @Override
    public void onPause() {
        mScannerView.stopCamera();
        super.onPause();
    }

    @Override
    public void onSaveInstanceState(@NonNull Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putString("state", state.toString());
        outState.putString("barcode", linkedData.getBarcode());
        outState.putString("beacon", linkedData.getBeacon());
    }

    @Override
    public void onViewStateRestored(@Nullable Bundle savedInstanceState) {
        super.onViewStateRestored(savedInstanceState);
    }

    @Override
    public void onClick(View v) {
        switch (v.getId())
        {
            case R.id.ic_barcode:
                if(state == SCAN_STATE.C)
                {
                    state = SCAN_STATE.B;
                    processState();
                }
                break;

            case R.id.ic_beacon:
                if(state == SCAN_STATE.B)
                {
                    state = SCAN_STATE.C;
                    processState();
                }
                break;

            case R.id.ic_link_sign:
            case R.id.ic_link_sign_scanned:
                if(state == SCAN_STATE.F)
                {

                    state = SCAN_STATE.A;
                    processState();
                    mScannerView.resumeCameraPreview(this);

                    //TODO: Save the code to database
                    passDataToActivity(linkedData.getBarcode(), linkedData.getBeacon());
                    linkedData = new LinkedData();
                }
                break;

        }
    }



    /**
     * <p>It initialize the UI</p>
     */
    private void initUI(View view) {

        imageBarcode = view.findViewById(R.id.ic_barcode);
        imageBeacon = view.findViewById(R.id.ic_beacon);
        imageLinkSign = view.findViewById(R.id.ic_link_sign);

        imageBarcodeSelected = view.findViewById(R.id.ic_barcode_selected);
        imageBeaconSelected = view.findViewById(R.id.ic_beacon_selected);

        imageBarcodeScanned = view.findViewById(R.id.ic_barcode_scanned);
        imageBeaconScanned = view.findViewById(R.id.ic_beacon_scanned);
        imageLinkSignScanned = view.findViewById(R.id.ic_link_sign_scanned);

        imageBarcode.setOnClickListener(this);
        imageBeacon.setOnClickListener(this);
        imageLinkSign.setOnClickListener(this);

        imageLinkSignScanned.setOnClickListener(this);

    }

    public void setupFormats() {
        List<BarcodeFormat> formats = new ArrayList<>();

        if(mSelectedIndices == null || mSelectedIndices.isEmpty()) {
            mSelectedIndices = new ArrayList<>();
            for(int i = 0; i < ZXingScannerView.ALL_FORMATS.size(); i++) {
                mSelectedIndices.add(i);
            }
        }

        for(int index : mSelectedIndices) {
                formats.add(ZXingScannerView.ALL_FORMATS.get(index));
        }
        if(mScannerView != null) {
            mScannerView.setFormats(formats);
        }
    }



    /**
     * <p>It is used to process QR Code linkedData</p>
     *
     * @param result
     */
    private void processQr(String result) {

        switch (state){
            case B:
                Toast.makeText(getContext(), "BarCode: " + result, Toast.LENGTH_SHORT).show();
                state = SCAN_STATE.D;
                linkedData.setBarcode(result);
                processState();
                handler.postDelayed(runnable, SPLASH_DISPLAY_LENGTH);
                break;
            case C:
                Toast.makeText(getContext(), "Beacon: " + result, Toast.LENGTH_SHORT).show();
                state = SCAN_STATE.E;
                linkedData.setBeacon(result);
                processState();
                handler.postDelayed(runnable, SPLASH_DISPLAY_LENGTH);
                break;
            case D:
                Toast.makeText(getContext(), "Beacon: " + result, Toast.LENGTH_SHORT).show();
                state = SCAN_STATE.F;
                linkedData.setBeacon(result);
                processState();
                break;
            case E:
                Toast.makeText(getContext(), "BarCode: " + result, Toast.LENGTH_SHORT).show();
                state = SCAN_STATE.F;
                linkedData.setBarcode(result);
                processState();
                break;
            case F:
                Toast.makeText(getContext(), "Extra: " + result, Toast.LENGTH_SHORT).show();
                processState();
                break;
        }

    }

    private void processState()
    {
        switch (state){
            case A:
                imageBarcode.setVisibility(View.GONE);
                imageBarcodeSelected.setVisibility(View.VISIBLE);
                imageBarcodeScanned.setVisibility(View.GONE);

                imageBeacon.setVisibility(View.VISIBLE);
                imageBeaconSelected.setVisibility(View.GONE);
                imageBeaconScanned.setVisibility(View.GONE);

                imageLinkSign.setVisibility(View.VISIBLE);
                imageLinkSignScanned.setVisibility(View.GONE);

                state = SCAN_STATE.B;

                break;
            case B:

                imageBarcode.setVisibility(View.GONE);
                imageBarcodeSelected.setVisibility(View.VISIBLE);

                imageBeacon.setVisibility(View.VISIBLE);
                imageBeaconSelected.setVisibility(View.GONE);

                break;
            case C:
                imageBarcode.setVisibility(View.VISIBLE);
                imageBarcodeSelected.setVisibility(View.GONE);

                imageBeacon.setVisibility(View.GONE);
                imageBeaconSelected.setVisibility(View.VISIBLE);

                break;
            case D:
                imageBarcodeSelected.setVisibility(View.GONE);
                imageBarcodeScanned.setVisibility(View.VISIBLE);

                imageBeacon.setVisibility(View.GONE);
                imageBeaconSelected.setVisibility(View.VISIBLE);

                break;
            case E:
                imageBarcode.setVisibility(View.GONE);
                imageBarcodeSelected.setVisibility(View.VISIBLE);

                imageBeaconSelected.setVisibility(View.GONE);
                imageBeaconScanned.setVisibility(View.VISIBLE);

                break;
            case F:
                imageBarcodeSelected.setVisibility(View.GONE);
                imageBarcodeScanned.setVisibility(View.VISIBLE);

                imageBeaconSelected.setVisibility(View.GONE);
                imageBeaconScanned.setVisibility(View.VISIBLE);

                imageLinkSign.setVisibility(View.GONE);
                imageLinkSignScanned.setVisibility(View.VISIBLE);

                break;
            default:
                // Must be some error....
                break;
        }
    }

    @Override
    public void handleResult(final Result result) {

        getActivity().runOnUiThread(new Runnable() {
            @Override
            public void run() {

                processQr(result.getText());
            }
        });
    }

    void passDataToActivity(String barcode, String beacon)
    {
        if(callBackListener != null)
            callBackListener.onDataScanned(new LinkedData(barcode, beacon));
    }


}
`

**Comment by srowen** [comment]
It looks too light. Sorry can't help with your app here.

**Comment by tr00per** [comment]
> It looks too light. Sorry can't help with your app here.

In other words: have you tried "image thresholding", @Trust-Coder?

**Comment by Trust-Coder** [comment]
No, I have no idea about it. Please guide me.

**Comment by tr00per** [comment]
Just google the phrase as quoted and start with Wikipedia. 2nd page deep there's an example implementation.

Basics are simple - convert to grayscale, pick a number (your threshold), divide to black and white by the threshold. You will get a simplified version of the image. See the articles for illustrations ;)

Experiment with the number for best results. The algorithm implementation on Wikipedia is for automating threshold picking.

**Comment by Trust-Coder** [comment]
Do I supposed to add this in library? Because I'm scanning it directly.
Image attached above was a sample for sharing here.
