### ISSUE TITLE
Unable to scan some Codabar

### ISSUE THREAD

**Issue by skylook** [zxing/zxing#109]
![codabar-1-1](https://cloud.githubusercontent.com/assets/3205308/2577082/e16fedb2-b979-11e3-9caf-0d5c4bde0cd1.jpg)

The attachment is a normal codabar which is not able to be scaned by zxing but may successfully scaned by some other Apps.
I donot find the reason yet.

**Comment by gxh-apologize** [comment]
@srowen How can I get  "Aabc123bcd456A" if it's Codabar ?

**Comment by srowen** [comment]
That string can't be encoded in Codabar, as far as I know

**Comment by oehhar** [comment]
Ghx, Sean,
thanks for the great discussion.

Codabar is a very special code.

The character set is 0 to 9 with start/stop ABCD.

If the code starts and stops with the same character it is complete.
If it stops with a different character, there is a continuation code to scan.
The data should be concatenated.

And you can see all the "zero" bar patterns in the picture, so the content is "000123000456".

Best regards,
Harald
