### ISSUE TITLE
Aztec problem with correct read

### ISSUE THREAD

**Issue by GruszkaMarcin** [zxing/zxing#1093]
### Bug Reports
Hi, I have a problem reading the aztec code, zxing can hardly scan the aztex code below for example
![pobrane](https://user-images.githubusercontent.com/20757754/47299208-02d7f000-d61a-11e8-8a90-318382cd48ed.gif)

**Comment by srowen** [comment]
I'm only accepting pull requests now. This is a large code and may be difficult to scan. But it easily decodes: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F20757754%2F47299208-02d7f000-d61a-11e8-8a90-318382cd48ed.gif
