### ISSUE TITLE
ByQuadrantReader NullPointerException

### ISSUE THREAD

**Issue by psManu** [zxing/zxing#1095]
`LuminanceSource source = new BufferedImageLuminanceSource(bufferredImage);`
`BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));`
`ByQuadrantReader byQuadrantReader = new ByQuadrantReader(reader);`
`GenericMultipleBarcodeReader multiReader = new GenericMultipleBarcodeReader(byQuadrantReader);`
`Result[] results = multiReader.decodeMultiple(bitmap);`

Here on decodeMultiple(bitmap) a NullPointerException is thrown.
Its from Line num 110 in  [https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/multi/ByQuadrantReader.java](url) .

Downloaded source code and updated it to do a simple Null check before going in. It seems to work.

**Comment by srowen** [comment]
Please open pull requests, not issues. There is no way to reproduce this here, and the link above doesn't work.
