### ISSUE TITLE
Methods with invalid locals information

### ISSUE THREAD

**Issue by syslogic** [zxing/zxing#1097]
since using `D8`, these warnings became appearent:
 ```
AGPBI: {"kind":"warning","text":"Stripped invalid locals information from 1 method.","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Methods with invalid locals information:\n  int com.google.zxing.aztec.detector.Detector.getColor(com.google.zxing.aztec.detector.Detector$Point, com.google.zxing.aztec.detector.Detector$Point)\n  Attempt to define local of type int as errRatio","sources":[{"file":"/home/martin/.gradle/caches/modules-2/files-2.1/com.google.zxing/core/3.3.3/b640badcc97f18867c4dfd249ef8d20ec0204c07/core-3.3.3.jar"}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Stripped invalid locals information from 2 methods.","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Methods with invalid locals information:\n  boolean com.google.zxing.qrcode.detector.FinderPatternFinder.foundPatternCross(int[])\n  Attempt to define local of type int as moduleSize\n  boolean com.google.zxing.qrcode.detector.FinderPatternFinder.foundPatternDiagonal(int[])\n  Attempt to define local of type int as moduleSize","sources":[{"file":"/home/martin/.gradle/caches/modules-2/files-2.1/com.google.zxing/core/3.3.3/b640badcc97f18867c4dfd249ef8d20ec0204c07/core-3.3.3.jar"}],"tool":"D8"}
```

**Comment by srowen** [comment]
I'm not sure what that is, but this is a function of the compiler or proguard optimization. Disable optimization if it's on. But it's not a project issue.

**Comment by syslogic** [comment]
[D8](https://android-developers.googleblog.com/2018/04/android-studio-switching-to-d8-dexer.html) is the current dexer, while searching GitHub for "Methods with invalid locals information" turns up quite a few results. the [source code](https://github.com/inferjay/r8/blob/master/src/main/java/com/android/tools/r8/utils/InternalOptions.java) might explain it better. it's a dex compiler optimization - while I build against tons of libraries, where only zxing throws these complains - and those 3 locals most likely could be improved.

**Comment by srowen** [comment]
These are clearly D8 bugs though, right?  It's complaining about...
```
float d = distance(p1, p2);
...
int error = 0;
...
float errRatio = error / d;
```
Its type is `float`, and the expression at the right is `float` too.
Same pattern in the other instance.

I am able to build and run the app with the Android SDK command line tools right now.

**Comment by srowen** [comment]
I should say that if there is a simple change to an equivalent implementation that doesn't trip over this, that's fine, open a PR.

**Comment by evgeniybondarenko-whaleapp** [comment]
Hi, we have this problem too. How to fix it?
