### ISSUE TITLE
How to add data to the bottom of the barcode？ 

### ISSUE THREAD

**Issue by chenshun00** [zxing/zxing#1099]
like this .

![image](https://user-images.githubusercontent.com/26037282/47695559-8eb2d300-dc3d-11e8-9d41-1377702880ab.png)

**Comment by srowen** [comment]
This library doesn't do that, you'll have to edit the image elsewhere.

**Comment by Champomix** [comment]
Is someone may share a snippet of code to do it, i am interested in

**Comment by Champomix** [comment]
Here my solution to do this with datamatrix.
Maybe the same with barcode.

Calling like this : 

`
Map<EncodeHintType, Object> hintMap = new EnumMap<>(EncodeHintType.class);
        hintMap.put(EncodeHintType.DATA_MATRIX_SHAPE, SymbolShapeHint.FORCE_SQUARE);

        final DataMatrixWriter barcode = new DataMatrixWriter();
        BitMatrix matrix = barcode.encode(preencoded, BarcodeFormat.DATA_MATRIX, PREFEREDSIZE, PREFEREDSIZE, hintMap);

        MatrixToImageConfig matrixToImageConfig = new MatrixToImageConfig(Colors.BLACK.getArgb(),
                Colors.WHITE.getArgb());
        BufferedImage datamatrixImage = MatrixToImageWriter.toBufferedImage(matrix, matrixToImageConfig);
BufferedImage originalImage = drawTextOnImage("2D-DOC", datamatrixImage, datamatrixImage.getHeight() / 5);
`
Here the code :

`
protected FontMetrics feetFontSizeToRegion(String text, Font font, Graphics2D g2d, int regionWidth,
            int regionHeight) {

        LOGGER.debug("text={};regionWidth={};regionHeight={}", text, regionWidth, regionHeight);

        // Get the fonts metrics
        FontMetrics fm = g2d.getFontMetrics(font);

        // Calculate the scaling requirements
        float xScale = (float) ((double) regionWidth / fm.stringWidth(text));
        float yScale = (float) ((double) regionHeight / fm.getHeight());

        // Determine which access to scale on...
        float scale = 0f;
        if (xScale > yScale) {
            scale = yScale;
        } else {
            scale = xScale;
        }

        LOGGER.debug("xScale={};yScale={};scale={}", xScale, yScale, scale);

        // Create a new font using the scaling facter
        g2d.setFont(font.deriveFont(AffineTransform.getScaleInstance(scale, scale)));
        // Make it pretty
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Get the "scaled" metrics
        fm = g2d.getFontMetrics();

        return fm;
    }

    protected BufferedImage drawTextOnImage(String text, BufferedImage image, int space) throws IOException {

        boolean doDebug = false;

        LOGGER.debug("{} {} {}", image.getWidth(), image.getHeight(), space);

        BufferedImage bi = new BufferedImage(image.getWidth(), image.getHeight() + space, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON));
        g2d.addRenderingHints(
                new RenderingHints(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON));

        Font font = new Font("Verdana", Font.PLAIN, space);
        g2d.drawImage(image, 0, 0, null);

        final int w = bi.getWidth();
        final int h = space;

        FontMetrics fm = feetFontSizeToRegion(text, font, g2d, w, h);
        final Rectangle2D stringBounds = fm.getStringBounds(text, g2d);

        final double x = (w - stringBounds.getWidth()) / 2d;
        final double y = (bi.getHeight() - space) + (h - stringBounds.getHeight()) / 2d;

        if (doDebug) {
            g2d.setColor(Color.RED);
        } else {
            g2d.setColor(Color.WHITE);
        }
        g2d.fillRect(0, image.getHeight(), (int) w, (int) h);

        // center text at bottom of image in the new space
        g2d.setColor(Color.BLACK);
        g2d.drawString(text, (int) x, (int) (y + fm.getAscent()));

        if (doDebug) {
            g2d.setColor(Color.BLUE);
            final Shape borderRectTight = new Rectangle2D.Double(x, y, stringBounds.getWidth(),
                    stringBounds.getHeight());
            g2d.setStroke(new BasicStroke(1f));
            g2d.draw(borderRectTight);
        }

        g2d.dispose();

        return bi;
    }
`
