### ISSUE TITLE
Can we generate EMV compliant qr code using zxing?

### ISSUE THREAD

**Issue by humayuntanwar** [zxing/zxing#1100]
The emv has its own structure of string. Which is encoded using byte mode.
I m new to this library sorry if this is not the appropriate way to look for solution

**Comment by srowen** [comment]
I don't know what that is, but if it's just a format for the string contents, you can send whatever string you like to be encoded, yes. You have to construct the string.

**Comment by NattoCB** [comment]
Hi @srowen I guess this is what humayuntanwar talked about:

<img width="961" alt="image" src="https://github.com/user-attachments/assets/b32c6b58-8fc1-405b-80e7-e4f489e09d2e" />
<img width="730" alt="image" src="https://github.com/user-attachments/assets/893340b1-62d9-4e6f-b497-b486e5468dc4" />

EMVCo Specification is a global payment specification and it forces (it said **shall** means must) to encode every QRC from the rawText in Byte Mode, and all other modes are not allowed. So, if a QRC wants to be EMV compliant, there is necessary to add a feature to let developer to manually choose the generating mode of the QRC.

Currently seems like zxing will automatically determine the encoding mode and there doesn't have a parameter to make it customizable.

https://github.com/zxing/zxing/blob/2dfb2054af1e1872ac5354e6d8218931fb88e021/core/src/main/java/com/google/zxing/qrcode/encoder/Encoder.java#L251
