### ISSUE TITLE
Oreo icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [zxing/zxing#1105]
Icon is still not adaptive. Whay have you closed #996?

Please don't close  this bug until it's not fixed.

Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by srowen** [comment]
I am not working on this project any more. I am not taking requests. Open a pull request if you like, but, we also cannot submit updates to this app in the App Store anymore

**Comment by c-e-p-x-u-o** [comment]
> we also cannot submit updates to this app in the App Store anymore

I don't understand. The app on Google Play links to https://github.com/zxing/zxing/

**Comment by srowen** [comment]
The app targets an older Android version, and can no longer be updated on Play.

**Comment by c-e-p-x-u-o** [comment]
> I am not working on this project any more. I am not taking requests.

The last update was 4 days ago. You may do nothing, but please do not close this issue.

**Comment by c-e-p-x-u-o** [comment]
> The app targets an older Android version, and can no longer be updated on Play.

Google Play says it's updates 2018-09-09
F-Droid says it's updates 2018-09-20

**Comment by c-e-p-x-u-o** [comment]
Any my adndroid versions is 8.1.0

**Comment by srowen** [comment]
... and the restriction is effective as of November 1. https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by c-e-p-x-u-o** [comment]
OK. Let's leave GPlay and talk about F-Droid. It doesn't have this restriction.

**Comment by AlfredoRamos** [comment]
@srowen Is there a reason that the `targetSdkVersion` can't be changed? Because I've read the article you linked, and it seems that it does not affect the minimum Android version required to run.

It's a genuine question since I haven't done anything for Android, I don't know the implications of changing the target SDK version.

I've been using this application since a long time and I'm a little sad about the current state of it.

**Comment by srowen** [comment]
Yeah it's the permissions model. It would have to be rewritten to handle requesting permissions. It gets enforced when you target 20 or above I think. Happy to find out if this isn't the case.
