### ISSUE TITLE
qrcode model and version

### ISSUE THREAD

**Issue by zhivko** [zxing/zxing#1107]
What to put inside **EncodeHintType QR_VERSION** to get

Model 2
Version 4
ECC level L

I have code now like this:
`
Hashtable<EncodeHintType, String> hintMap = new Hashtable<EncodeHintType, String>();
hintMap.put(EncodeHintType.CHARACTER_SET, "UTF-8");
hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L.toString());
hintMap.put(EncodeHintType.QR_VERSION, "4");
`

where or how do I set model?

http://www.qrcode.com/en/about/error_correction.html
http://www.qrcode.com/en/codes/model12.html
http://www.qrcode.com/en/about/version.html

**Comment by srowen** [comment]
That's right, as the javadoc says it's "4" as a string or int. Questions should really go to https://groups.google.com/forum/#!forum/zxing
