### ISSUE TITLE
Cannot decode zxing encoded qrcode

### ISSUE THREAD

**Issue by chossette** [zxing/zxing#1109]
Hello !

### Bug Reports
Two QR code pngs are attached. One is prefixed with ok_ and the other one fail_. They are a crop of the original frame (to reduce issue caused by content).
Both have been generated in the same process with zxing are refer to different frame of a content.

We cannot manage to read it using ZXing or online tool: https://zxing.org/w/decode.jspx.

![fail_chunk_1542209021600000000_350x350rgb](https://user-images.githubusercontent.com/15772228/48630044-7a9bff00-e9bb-11e8-94c8-10039f506ac9.png)
![Uploading ok_chunk_1542208793080000000_350x350rgb.png…]()

I may have probably missed something ??
Using my android phone I can decode both QR code using QR droid

Tx by advance,

**Comment by srowen** [comment]
White space around the image. It is added automatically by the encoder here. This wasn't generated with zxing. The code isn't valid I'm afraid.

**Comment by chossette** [comment]
This was generated using zxing.

I am going to check the code, and get back to you on Monday.

Indeed, if I add a bigger white border, the code readable by zxing.

 

I am going to check what we have done wrong with zxing.

 

Tx for your feedback !

 

De : Sean Owen [mailto:notifications@github.com] 
Envoyé : vendredi 16 novembre 2018 16:52
À : zxing/zxing <zxing@noreply.github.com>
Cc : chossette <nicolas.bernard@charlescros.org>; Author <author@noreply.github.com>
Objet : Re: [zxing/zxing] Cannot decode zxing encoded qrcode (#1109)

 

White space around the image. It is added automatically by the encoder here. This wasn't generated with zxing. The code isn't valid I'm afraid.
