### ISSUE TITLE
Add support for Android portrait mode

### ISSUE THREAD

**Issue by donv** [zxing/zxing#111]

**Comment by WACMemphis** [comment]
+1

**Comment by fbreda** [comment]
+1

2015-02-10 15:06 GMT-02:00 WACMemphis <notifications@github.com>:

**Comment by srowen** [comment]
Hi all, +1 won't do anything, there's nobody taking feature requests, but I'll work with someone who wants to implement this to merge it with my implementation to make something best of both worlds.

**Comment by chepe263** [comment]
I was reading the help in the application. When my deviced changed orientation to landscape, the help went white. Is this the same issue?

**Comment by edy1** [comment]
+1

**Comment by mifa** [comment]
+1

**Comment by srowen** [comment]
@edy1 @mifa did you read my comment? +1 is just spam unless you are going to contribute code.

**Comment by dimitrovskif** [comment]
The method described [here](http://stackoverflow.com/questions/16252791/zxing-camera-in-portrait-mode-on-android) doesn't work on ZXing 3.2 because the viewport is a little bit stretched.

Any fix?

(I have a 5 day deadline to finish QR scanning, and our app is portrait - I am basically f*cked)

**Comment by dimitrovskif** [comment]
I think this problem can be solved by using some code from [https://github.com/dlazaro66/QRCodeReaderView](this project)

It's a lightweight library for `zxing-core` which works in portrait mode. I compared scanning QR codes, there are only two differences: 

* QRCodeReaderView has higher autofocus interval (easily modifiable)

* QRCodeReaderView does not crop a specific zone, it scans the whole camera frame (easily modifiable)

**Comment by skzinzuwadia** [comment]
Hi,
https://github.com/dlazaro66/QRCodeReaderView
it did not support code 128

**Comment by schildbach** [comment]
Does QRCodeReaderView work *only* in portrait orientation? Unfortunately, then it would not solve my problem. My app works both in portrait and landscape, and the goal is using the scanner should not switch orientations.

**Comment by semieye** [comment]
Hi guys,
try this project: https://github.com/dm77/barcodescanner
it works both in portrait and landscape.

**Comment by SudarAbisheck** [comment]
Checkout this project too !! 
https://github.com/SudarAbisheck/ZXing-Orient
It supports both portrait and Landscape mode too..

**Comment by KrasnayaPloshchad** [comment]
The current version of Barcode Scanner can handle the initial orientation of camera when the app is opened, but cannot rotating it correctly when rotate the device in 180°, and the interface have no protait mode when rotate the device in 90°.

**Comment by KrasnayaPloshchad** [comment]
I think [Open Camera](https://sourceforge.net/projects/opencamera/) also set an good example.

**Comment by liyzay** [comment]
@srowen I think I might find a way to support portrait mode.
Here is my steps:
1.I cloned the latest code from version 4.7.6
2.Removing "android:screenOrientation="sensorLandscape"" in [https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml#L60](url)
2.Removing lines from 172 to 176 in [https://github.com/zxing/zxing/blob/master/android/src/com/google/zxing/client/android/CaptureActivity.java#L172](url) to support both landscape and portrait
3.Changing portrait preview size by changing code in [https://github.com/zxing/zxing/blob/master/android-core/src/main/java/com/google/zxing/client/android/camera/CameraConfigurationUtils.java#L276](url)
like this:

		double screenAspectRatio = (double) screenResolution.x / (double) screenResolution.y;
		//Consider portrait
		boolean isScreenPortrait = screenResolution.x < screenResolution.y;

		// Remove sizes that are unsuitable
		Iterator<Camera.Size> it = supportedPreviewSizes.iterator();
		while (it.hasNext()) {
			Camera.Size supportedPreviewSize = it.next();
			int realWidth = supportedPreviewSize.width;
			int realHeight = supportedPreviewSize.height;
			if (realWidth * realHeight < MIN_PREVIEW_PIXELS) {
				it.remove();
				continue;
			}

			boolean isCandidatePortrait = realWidth < realHeight;
			int maybeFlippedWidth = isScreenPortrait != isCandidatePortrait ? realHeight : realWidth;
			int maybeFlippedHeight = isScreenPortrait != isCandidatePortrait ? realWidth : realHeight;
			double aspectRatio = (double) maybeFlippedWidth / (double) maybeFlippedHeight;
			double distortion = Math.abs(aspectRatio - screenAspectRatio);
			if (distortion > MAX_ASPECT_DISTORTION) {
				it.remove();
				continue;
			}

			if (maybeFlippedWidth == screenResolution.x && maybeFlippedHeight == screenResolution.y) {
				Point exactPoint = new Point(realWidth, realHeight);
				Log.i(TAG, "Found preview size exactly matching screen size: " + exactPoint);
				return exactPoint;
			}
		}

4.Putting the "framingRectInPreview" rect center in the camera resolution screen by changing code in [https://github.com/zxing/zxing/blob/master/android/src/com/google/zxing/client/android/camera/CameraManager.java#L253](url) like this:

> 
		if (framingRectInPreview == null) {
			Rect framingRect = getFramingRect();
			if (framingRect == null) {
				return null;
			}
			Point cameraResolution = configManager.getCameraResolution();
			Point screenResolution = configManager.getScreenResolution();
			if (cameraResolution == null || screenResolution == null) {
				// Called early, before init even finished
				return null;
			}
			//Create a new rect which is same size as framingRect
			//And put the it center in the camera resolution screen
			Rect centerInCameraRect = new Rect() ;
			centerInCameraRect.left = (cameraResolution.x-framingRect.width())/2;
			centerInCameraRect.right = centerInCameraRect.left + framingRect.width() ;
			centerInCameraRect.top = (cameraResolution.y-framingRect.height())/2;
			centerInCameraRect.bottom = centerInCameraRect.top+framingRect.height() ;
			framingRectInPreview = centerInCameraRect ;
		}
		return framingRectInPreview;


I test those code with my phone and it works fine.

**Comment by srowen** [comment]
That sounds like a lot of the necessary change, though there needs to be some UI change too right? it doesn't really work on smaller screens in portrait otherwise.

**Comment by BS987** [comment]
@liyzay I tried your suggested code change on 4.7.7 version, screen is rotated fine and preview rectangle is also good. But it does not scan anything in portrait mode. Can you please suggest me what is wrong ? Did you checked it by scanning anything ?

**Comment by GuoJinyu** [comment]
@srowen 
I think the most important point to support for Android portrait mode is rotating the YUV preview frame data array, because the preview frame you get is only relative to the camera's orientation (always landscape at nearly all of Android phones) which has no relation to the screen's orientation.
So this is my steps to support portrait mode in version 4.7.7:
1. Changing to "android:screenOrientation="landscape"" in [AndroidManifest.xml](https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml#L47)(because [this issue](https://github.com/zxing/zxing/issues/576))
2. Changing lines from 172 to 176 in [CaptureActivity.java](https://github.com/zxing/zxing/blob/master/android/src/com/google/zxing/client/android/CaptureActivity.java#L172)  to support both landscape and portrait
```java    
if (prefs.getBoolean(PreferencesActivity.KEY_DISABLE_AUTO_ORIENTATION, true)) {
      setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
} 
````
3. Changing lines from 327 to 329 in [CameraConfigurationUtils.java](https://github.com/zxing/zxing/blob/master/android-core/src/main/java/com/google/zxing/client/android/camera/CameraConfigurationUtils.java#L327) to get proper aspectRatio in accordence with screen orientation
```java
    boolean isScreenPortrait = screenResolution.x < screenResolution.y;
    int maybeFlippedWidth = isScreenPortrait ? realHeight : realWidth;
    int maybeFlippedHeight = isScreenPortrait ? realWidth : realHeight;
```
4. Changing  lines from 266 to 269 in [CameraManager.java](https://github.com/zxing/zxing/blob/master/android/src/com/google/zxing/client/android/camera/CameraManager.java#L266) to get precise preview rectangle for camera.
```java
      if(screenResolution.x < screenResolution.y){
         // portrait
    	 rect.left = rect.left * cameraResolution.y / screenResolution.x;
         rect.right = rect.right * cameraResolution.y / screenResolution.x;
         rect.top = rect.top * cameraResolution.x / screenResolution.y;
         rect.bottom = rect.bottom * cameraResolution.x / screenResolution.y;
      } else {
         // landscape
         rect.left = rect.left * cameraResolution.x / screenResolution.x;
         rect.right = rect.right * cameraResolution.x / screenResolution.x;
         rect.top = rect.top * cameraResolution.y / screenResolution.y;
         rect.bottom = rect.bottom * cameraResolution.y / screenResolution.y;
      }
```
5. Changing  lines from 47 to 48 in[PreviewCallback.java](https://github.com/zxing/zxing/blob/master/android/src/com/google/zxing/client/android/camera/PreviewCallback.java#L47) to send proper width and height of preview frame
```java
      Point screenResolution = configManager.getScreenResolution();
      Message message;
      if (screenResolution.x < screenResolution.y){
        // portrait      
    	message = thePreviewHandler.obtainMessage(previewMessage, cameraResolution.y,
                cameraResolution.x, data);
      } else {
    	// landscape
    	message = thePreviewHandler.obtainMessage(previewMessage, cameraResolution.x,
    	        cameraResolution.y, data);
      }
```
6. Adding lines between 76 and 77 in[PreviewCallback.java](https://github.com/zxing/zxing/blob/master/android/src/com/google/zxing/client/android/DecodeHandler.java#L76) to rotate data when portrait
```java
    long start = System.currentTimeMillis();
    if (width < height) {
      // portrait
      byte[] rotatedData = new byte[data.length];
      for (int x = 0; x < width; x++) {
          for (int y = 0; y < height; y++)
              rotatedData[y * width + width - x - 1] = data[y + x * height];
      }
      data = rotatedData;
    }
    Result rawResult = null;
```

Above-mentioned code modify has been tested on both 1D and 2D code and works good in my two Android phones with back camera.

BTW , I publish an Android scanner library by simplifying this Android project [SimpleZXing](https://github.com/GuoJinyu/SimpleZXing)

**Comment by ChinaBabyFace** [comment]
@BS987 Hi！I meet same problem like you.But QR-code can scan

**Comment by ChinaBabyFace** [comment]
@GuoJinyu 完美

**Comment by GuoJinyu** [comment]
@srowen sorry for my careless, I just modify my comment above and it can work properly.

**Comment by SteveRapp** [comment]
Honestly, just losing the text that shows up on the "bottom" (AKA sideways on the left side of the screen) would be enough of a fix for my (and probably most people's) purposes. It just makes the app look ridiculous and sloppily designed that the entire thing is portrait up until you open the QR reader and it insists on being landscape. Without the text, you wouldn't be able to tell it's gone into landscape. The instructions given by the text are beyond obvious anyway. It could just go away with no real impact on user experience.

**Comment by praveenshharma** [comment]
@GuoJinyu  Perfect Solution

**Comment by GuoJinyu** [comment]
@praveenshharma as for frame size, you can just add code like this in [CameraManager](https://github.com/zxing/zxing/blob/master/android/src/com/google/zxing/client/android/camera/CameraManager.java#L224)
```java
            int width = findDesiredDimensionInRange(screenResolution.x, MIN_FRAME_WIDTH, MAX_FRAME_WIDTH);
            int height = findDesiredDimensionInRange(screenResolution.y, MIN_FRAME_HEIGHT, MAX_FRAME_HEIGHT);
            if (width < height) {
                height = width;
            }
```

**Comment by srowen** [comment]
I'm going to at long last declare that this won't happen in this project. However, I'm going to soon open source the 'plus' app anyway, which has this functionality.

**Comment by juqiu** [comment]
Just need to change lines  in CameraManager.java to get precise preview rectangle can support  portrait mode:
  
          if (screenResolution.y > screenResolution.x) { // portrait mode
                rect.left = framingRect.top * cameraResolution.x/ screenResolution.y;
                rect.top = (screenResolution.x-framingRect.right) * cameraResolution.y / screenResolution.x;
                rect.right = framingRect.bottom * cameraResolution.x / screenResolution.y;
                rect.bottom = (screenResolution.x-framingRect.left) * cameraResolution.y / screenResolution.x;
            } else {
                rect.left = rect.left * cameraResolution.x / screenResolution.x;
                rect.right = rect.right * cameraResolution.x / screenResolution.x;
                rect.top = rect.top * cameraResolution.y / screenResolution.y;
                rect.bottom = rect.bottom * cameraResolution.y / screenResolution.y;
            }

**Comment by biwoodfengs** [comment]
Thanks @juqiu , My apps work in portrait mode, I found that it only decodes the center_horizontal parts of screen, then  I make scan rectangle top of screen, the decode area has a right shifts.  juqiu's resolution make me ajust the decode area in portrait mode works properly.

**Comment by maverick74** [comment]
@srowen where can we get updated about the opensourcing of the "plus" version, when it happens???

I ask this because i try to use opensource apps everywhere i can, so i'm interested in this!

Thanks :)

**Comment by srowen** [comment]
https://play.google.com/store/apps/details?id=com.srowen.bs.android

**Comment by maverick74** [comment]
@srowen I was hopping you would have a blog or something that would have more "up-to-date" news :)

Will keep an eye on PlayStore, then!

Happy Holidays

Thanks

**Comment by agbaraka** [comment]
As of **zxing library:2.2.0** 

**AndroidManifest.xml**

```
<activity
    android:name="com.journeyapps.barcodescanner.CaptureActivity"
    android:screenOrientation="fullSensor"
    tools:replace="screenOrientation" />
```
**Set additional property at call to scanner :**

```
IntentIntegrator integrator = new IntentIntegrator(this);
//set orientation locked to false
integrator.setOrientationLocked(false);
```

**Comment by yangyiRunning** [comment]
@GuoJinyu  

在DecodeHandler类中的`rotatedData[y * width + width - x - 1] = data[y + x * height];`这一行，会报错`java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 1375816 free bytes and 1343KB until OOM`， 有什么解决的办法么？
