### ISSUE TITLE
Multiple camera instances problem -  "Android camera encountered a problem.."

### ISSUE THREAD

**Issue by DarioNevistic** [zxing/zxing#1110]
Opening multiple camera instances will result with Android camera problem on android 7.1.1 - Samsung J5 device.
`Sorry, the Android camera encountered a problem. You may need to restart the device.`

If mentioned problem occurs, user needs to restart device to continue with normal camera work (also native camera not working).

**Note**: Zxing Scanner app is opening as external app from my own application, it is not integrated.

Steps to reproduce:
- open `example` custom app - and choose scan using zxing scanner (zxing scanner app is opened external)
- minimize `example` app
- open Zxing Scanner app directly

**Note2** if error not occurs at first time, try to mix these steps few times, I am able to produce it every time.

Device: Samsung J5 (same bug on multiple devices)
Android: 7.1.1

**Comment by srowen** [comment]
I'm not sure what to make of that. The app just opens one camera and does so correctly. This sounds like a problem with the device driver, or that the other app maybe isn't closing the camera.
