### ISSUE TITLE
How to design a mask to make QRcode's distribution even and beautiful

### ISSUE THREAD

**Issue by HUANGskysky** [zxing/zxing#1116]
## Questions

We know that QRcode's data are placed in a format of zigzag after we have placed the basic patterns,Type information and Version information. But now if I  adapted a new way to place the data,for example, homocentric squares. I found the mask in your design is not suitable for me now. So I want to ask your motivation to design mask before. I get little knowledge about this. 
Looking forward to your reply！

**Comment by AntonioNelson98** [comment]
Yes I do
