### ISSUE TITLE
Support 8-color HCC2D code?

### ISSUE THREAD

**Issue by evandrix** [zxing/zxing#1117]
- 8-color, i.e. https://en.m.wikipedia.org/wiki/List_of_monochrome_and_RGB_palettes#3-bit_RGB
- e.g. 
![](https://i.ibb.co/d5WSkxz/QR3C.png)
- writeup https://github.com/shiltemann/CTF-writeups-public/blob/master/Hackvent_2015/writeup.md#dec-17-santas-quick-response

**Comment by srowen** [comment]
I'm afraid this is in maintenance mode, so I wouldn't add more support for new formats. If you had a nice clean implementation of a decoder in a pull request, maybe.

**Comment by HUANGskysky** [comment]
Recently I also do some research about Colored QR code,maybe we can discuss about this.

**Comment by evandrix** [comment]
- using the notes from:
> https://github.com/shiltemann/CTF-writeups-public/blob/master/Hackvent_2015/writeup.md#dec-17-santas-quick-response

![qr3c](https://user-images.githubusercontent.com/169669/49701333-1ec53e80-fc26-11e8-82be-839c772d1575.png)
...becomes the following when split into its R,G,B components:
![qr3c-0](https://user-images.githubusercontent.com/169669/49701330-1e2ca800-fc26-11e8-92c4-19247d82f7e0.png)
![qr3c-1](https://user-images.githubusercontent.com/169669/49701331-1e2ca800-fc26-11e8-80aa-d9380864e176.png)
![qr3c-2](https://user-images.githubusercontent.com/169669/49701332-1ec53e80-fc26-11e8-8181-c614acbc8b80.png)

- my [solution](https://github.com/zxing/zxing/files/2660895/qr3c.py.txt) for the challenge task this year

**Comment by HUANGskysky** [comment]
Maybe you can look at this project, https://github.com/ouyangzhibo/HiQ-Robust-and-Fast-Decoding-of-High-Capacity-Color-QR-Codes

**Comment by evandrix** [comment]
:+1:

**Comment by evandrix** [comment]
on the topic of 2D color barcodes, there is also this other thing:
- https://jabcode.org/scan
- repo https://github.com/jabcode/jabcode
- vid https://www.youtube.com/watch?v=KXmj8HOyRnY
