### ISSUE TITLE
errorCorrectionLevel = Integer.parseInt(hints.get(EncodeHintType.ERROR_CORRECTION).toString());

### ISSUE THREAD

**Issue by uquba** [zxing/zxing#1120]
PDF417Writer.class AztecWriter.class errorCorrectionLevel = Integer.parseInt(hints.get(EncodeHintType.ERROR_CORRECTION).toString()); is error
should be errorCorrectionLevel =ErrorCorrectionLevel.valueOf(hints.get(EncodeHintType.ERROR_CORRECTION).toString()).getBits();

**Comment by srowen** [comment]
No, that's for QR code EC levels. Check the docs of `EncodeHintType.ERROR_CORRECTION`
