### ISSUE TITLE
duplicate class on android

### ISSUE THREAD

**Issue by dpapini** [zxing/zxing#1122]
hi, thank you for you great job. i 'wold like to use your library for my project, but when i run my application i receive the error "duplicate class android.support.v4"

this is my gradle dependencies

    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0-alpha1'

can you help me 

thank you

**Comment by srowen** [comment]
This has nothing to do with this library.
