### ISSUE TITLE
Fails to get camera on Winmate E430

### ISSUE THREAD

**Issue by asgerjensen** [zxing/zxing#1124]
After upgrading from an older device to the Winmate E430 series of android PDAs, I can no longer scan using the Barcode Scanner app. 

I'm using the IntentIntegrator approach from my app.

When Barcode Scanner opens, it says something to the effect that the camera is failing / not available.

I noticed when I  opened the built-in camera app, it says "Waiting for WDC to release", before the camera becomes active. So it seems the devices built-in scanner (which is a seperate hardware scanner), has a lock on the camera subsystem somehow. 

Attaching a debugger, makes me think that WDC is a Winmate application that interfaces with their hardware scanner. 

I might be able to grab the camera myself, before handing over control to Barcode Scanner, but the timings in doing this seems ...iffy, as the WDC application apparently retakes control on its own, when other camera apps have properly released their locks.

I am using version 4.7.6 of BarCode scanner, and the Winmate device is apparently Android 4.2.

**Comment by srowen** [comment]
Yeah, I think that is unfortunately something to do with the device and its driver. All the app does is open the camera and its reporting that the driver failed to open it for some reason.
