### ISSUE TITLE
[C#] Decode fail

### ISSUE THREAD

**Issue by JJHL** [zxing/zxing#1127]
Hi,
I am using zxing dll.

sometimes, My program could not decode a image.
our image size is (500,500) and I retry to decode by resizing the image.

please check my code and Image.
How can I do?

![test](https://user-images.githubusercontent.com/46519088/51095382-a8ed5d80-17f7-11e9-88ef-9084593b455c.jpg)

Blow my code 
-----------------------------------------------------------------------------------------------

                source = Image.FromFile(imagePath);
                if (count == 0)
                {
                    img = new Bitmap(source);
                }
                else
                {
                    img = new Bitmap(source, new Size(500 - (count * 50), 500 - (count * 50)));
                }
reader = new BarcodeReader();
                reader.AutoRotate = true;
                reader.TryInverted = true;
                reader.Options.TryHarder = true;
                reader.Options.PossibleFormats = new List<BarcodeFormat>();
                reader.Options.PossibleFormats.Add(BarcodeFormat.QR_CODE);
                Result decodeResult = reader.Decode(img);

---------------------------------------------------------------------------------------------------

**Comment by srowen** [comment]
You're asking about a different project. 
I think the problem is the barcode is a little warped and there is noise. Still I'd expect it to decode. It reads fine off the screen.

**Comment by JJHL** [comment]
Hi, Thank you for reply.

but, My smartphone app 'zxing scanner' decodes very well.

we are wondering if there is a difference between jar file and C#dll.
