### ISSUE TITLE
This two-dimensional code can't be scanned, and ChecksumException is reported as an error.

### ISSUE THREAD

**Issue by zongchuansheng** [zxing/zxing#1128]
![20190123170008](https://user-images.githubusercontent.com/46957120/51595077-d7261800-1f30-11e9-9e94-ad8f7e461c40.png)
This two-dimensional code can't be scanned,This code is partially obscured,and ChecksumException is reported as an error.

**Comment by QingfengLee** [comment]
There are some occlusion on the finder pattern,  it may results in the inaccurate location. Indirectly, there may be errors in the final sampling results. In addition, the distortion of the two-dimensional code may lead to inaccurate sampling results.  All of these may lead to the report of ChecksumException.

**Comment by zongchuansheng** [comment]
I have noticed that.But I found that other applications can scan this.
I wonder if I can modify a piece of code to solve this problem. Where should I start?
