### ISSUE TITLE
Plugin unable to scan PDF417 driving license

### ISSUE THREAD

**Issue by gilbertngandu** [zxing/zxing#1129]
### Expected Behaviour
Drivers license scan should return the data
### Actual Behaviour
Unable to scan PDF417. The plugin works well with vehicle license disk but it struggling with more dense PDF417 like the driving license in the picture below. Plugin such as https://github.com/manateeworks/phonegap-manateeworks-v3 are able to read the content of the image below:
https://user-images.githubusercontent.com/968412/37446065-e0878f0a-2823-11e8-9542-9af11132852c.png
### Reproduce Scenario (including but not limited to)
Try scanning the following image 
https://user-images.githubusercontent.com/968412/37446065-e0878f0a-2823-11e8-9542-9af11132852c.png
#### Steps to Reproduce
Try scanning the following image 
https://user-images.githubusercontent.com/968412/37446065-e0878f0a-2823-11e8-9542-9af11132852c.png
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

#### Sample Code that illustrates the problem
this.barcodeScanner.scan({formats: "PDF_417", showTorchButton:true}).then(barcodeData => { });

**Comment by srowen** [comment]
This is reported against the wrong project

**Comment by gilbertngandu** [comment]
Hi Sean,
Please have a look at the initial project where I reported the issue
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/760#issuecomment-456734089
They referred me to your project.

**Comment by zkrige** [comment]
I'm not sure why this is closed. ZXING is unable to read this PDF417 barcode. Is there any way I can help in getting axing reading this barcode?

**Comment by srowen** [comment]
Well, one reason is above: 1) wrong project. 2) this project is not maintained. 3) this project does read the barcode. Did you try it at zxing.org

**Comment by zkrige** [comment]
Thank you for the prompt response @srowen. I really appreciate it

I'll open a new issue for the barcode that is unable to scan
