### ISSUE TITLE
README says The Barcode Scanner app can no longer be published but reason not clear

### ISSUE THREAD

**Issue by whcrg** [zxing/zxing#1132]
Sorry for slightly misusing issues for a question type stuff, but this IS also an issue with the readme.

Why "The Barcode Scanner app can no longer be published, so it's unlikely any changes will be accepted for it."? Maybe there should be one sentence explanation or link to somewhere etc?

I am developing a webapp that needs zxing:// url functionality and I am concerned will this app be there in future. I have used hours for googling if barcode scanners are forbidden in play store or something but I find no explanation. Also searched https://groups.google.com/forum/#!forum/zxing with no results.

**Comment by srowen** [comment]
It isn't gone just can't be updated as it targets API 19
