### ISSUE TITLE
Zxing android AZTEC quality

### ISSUE THREAD

**Issue by kotekGit** [zxing/zxing#1134]
I am using this plugin in Ionic/Cordova project and it is working perfectly in iOS application (recognise AZTEC code, but on android it have problem. It recognise simple AZTEC code, but when trying with more complicated it can not recognise).

Sample AZTEC to recognise:
https://ibb.co/qpkR2Dr

Can anyone help?

**Comment by wosiu** [comment]
@srowen @kotekGit was the issue resolved?
