### ISSUE TITLE
Not able to read QR code from image

### ISSUE THREAD

**Issue by 810152690** [zxing/zxing#1138]
Hi All,

I have below image with a QR code in it. However, it is not recognized.

![image](https://user-images.githubusercontent.com/1946356/53312619-b581cd00-38f0-11e9-9d6e-4446c5c65f54.png)

however, using iphone's camera can recognized it.

Is there something to do to fix this?

**Comment by srowen** [comment]
Nope, just try a different image. These aren't bugs per se and as you read in the text you removed, this project only accepts pull requests.

**Comment by 810152690** [comment]
Thank for your reply.
I remove text, but zxing can't recognized it. By the way, i using iOS code.
![image](https://user-images.githubusercontent.com/1946356/53314541-d00c7400-38f9-11e9-8da1-1e5dcbf9190a.png)
what can I do to resolve it?

**Comment by 810152690** [comment]
what do mean "this project only accepts pull requests".

**Comment by srowen** [comment]
You read this text when you opened the issue:

```
(Please remove this text once you've read and understood it.)

## Contributing

The project is in maintenance mode, meaning, changes are driven by contributed patches.
There is otherwise no active development or roadmap for this project. It is "DIY".

Only proposed changes in the form of a pull request are likely to be acted on, but,
these will be acted on promptly.
...
```

**Comment by tadd** [comment]
@srowen
FYI: Issues can be disabled
https://help.github.com/en/articles/disabling-issues

and PR will be still available.
https://help.github.com/en/articles/creating-an-issue
> Pull requests can't be turned off and are always available.

**Comment by srowen** [comment]
Yeah, I hadn't gone that far unless someone had a simple, legitimate issue to report that wasn't immediately solvable, but think I'll do that now.

**Comment by 810152690** [comment]
> Nope, just try a different image. These aren't bugs per se and as you read in the text you removed, this project only accepts pull requests.

Hi, i don't know the reason why can't recognized it. Must I try new image?

**Comment by tadd** [comment]
@srowen I read "EDIT" part now.  Thank you for consideration.

I just hope that you do not get tired.  Thanks for your great work.
