### ISSUE TITLE
unable to read QR code

### ISSUE THREAD

**Issue by 810152690** [zxing/zxing#1140]
Hi, i have image that unable to read QR.
![image](https://user-images.githubusercontent.com/1946356/53402415-abdd8f80-39ec-11e9-86ea-7910bde66aa1.png)

I found
```
- (ZXDetectorResult *)detect:(ZXDecodeHints *)hints error:(NSError **)error {
  self.resultPointCallback = hints == nil ? nil : hints.resultPointCallback;

  ZXQRCodeFinderPatternFinder *finder = [[ZXQRCodeFinderPatternFinder alloc] initWithImage:self.image resultPointCallback:self.resultPointCallback];
  ZXQRCodeFinderPatternInfo *info = [finder find:hints error:error];
  if (!info) {
    return nil;
  }

  return [self processFinderPatternInfo:info error:error];
}
```
info always is nil. So i can't read QRCode from image.
I don't know the reason.

**Comment by srowen** [comment]
This is about a different library.

**Comment by 810152690** [comment]
> This is about a different library.

what do you mean "different library"?

**Comment by srowen** [comment]
This code you are calling is not in this github repository. Look at what you are importing

**Comment by 810152690** [comment]
> This code you are calling is not in this github repository. Look at what you are importing

sorry to trouble you.

**Comment by reybenigay-lab** [comment]
My issue jack track cammins engine low power

**Comment by nadeemsaab245-dotcom** [comment]
> Hi, i have image that unable to read QR. ![image](https://user-images.githubusercontent.com/1946356/53402415-abdd8f80-39ec-11e9-86ea-7910bde66aa1.png)
> 
> I found
> 
> ```
> - (ZXDetectorResult *)detect:(ZXDecodeHints *)hints error:(NSError **)error {
>   self.resultPointCallback = hints == nil ? nil : hints.resultPointCallback;
> 
>   ZXQRCodeFinderPatternFinder *finder = [[ZXQRCodeFinderPatternFinder alloc] initWithImage:self.image resultPointCallback:self.resultPointCallback];
>   ZXQRCodeFinderPatternInfo *info = [finder find:hints error:error];
>   if (!info) {
>     return nil;
>   }
> 
>   return [self processFinderPatternInfo:info error:error];
> }
> ```
> 
> info always is nil. So i can't read QRCode from image. I don't know the reason.

1140

**Comment by nadeemsaab245-dotcom** [comment]
> Hi, i have image that unable to read QR. ![image](https://user-images.githubusercontent.com/1946356/53402415-abdd8f80-39ec-11e9-86ea-7910bde66aa1.png)
> 
> I found
> 
> ```
> - (ZXDetectorResult *)detect:(ZXDecodeHints *)hints error:(NSError **)error {
>   self.resultPointCallback = hints == nil ? nil : hints.resultPointCallback;
> 
>   ZXQRCodeFinderPatternFinder *finder = [[ZXQRCodeFinderPatternFinder alloc] initWithImage:self.image resultPointCallback:self.resultPointCallback];
>   ZXQRCodeFinderPatternInfo *info = [finder find:hints error:error];
>   if (!info) {
>     return nil;
>   }
> 
>   return [self processFinderPatternInfo:info error:error];
> }
> ```
> 
> info always is nil. So i can't read QRCode from image. I don't know the reason.

#- (ZXDetectorResult *)detect:(ZXDecodeHints *)hints error:(NSError **)error {
  self.resultPointCallback = hints == nil ? nil : hints.resultPointCallback;

  ZXQRCodeFinderPatternFinder *finder = [[ZXQRCodeFinderPatternFinder alloc] initWithImage:self.image resultPointCallback:self.resultPointCallback];
  ZXQRCodeFinderPatternInfo *info = [finder find:hints error:error];
  if (!info) {
    return nil;
  }

  return [self processFinderPatternInfo:info error:error];
}
