### ISSUE TITLE
Unable to scan big QR-Code

### ISSUE THREAD

**Issue by No1e** [zxing/zxing#1141]
Dear ZXing Support,

Could you enhance your library to support scanning of bigger QR Codes

Here is an example:
![qr code](https://user-images.githubusercontent.com/25526781/53473345-76778700-3a6a-11e9-9ee4-2b72e19d691a.PNG)

Kind regards,
Novak

**Comment by axxel** [comment]
Since this project is unlikely to change anything substantial with its QRCode decoder, I'd like to point out that https://github.com/zxing-cpp/zxing-cpp/ can read this easily.

**Comment by casonwheeler-png** [comment]
how can I post it
