### ISSUE TITLE
Wiki "Barcode Contents" page's Wi-Fi section displays escaping information incorrectly

### ISSUE THREAD

**Issue by h4l** [zxing/zxing#1143]
The wiki isn't editable, but the section on [escaping values in Wi-Fi codes][wifi-config] is wrong due to incorrect markdown escaping. It's currently (notice the missing backslashes in the double quotes):

[wifi-config]: https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11

> Order of fields does not matter. Special characters "\", ";", "," and ":" should be escaped with a backslash ("\") as in MECARD encoding. For example, if an SSID was literally `"foo;bar\baz"` (with double quotes part of the SSID name itself) then it would be encoded like: `WIFI:S:\"foo\;bar\\baz\";;`

Should read:
> Order of fields does not matter. Special characters "\\", ";", "," and ":" should be escaped with a backslash ("\\") as in MECARD encoding. For example, if an SSID was literally `"foo;bar\baz"` (with double quotes part of the SSID name itself) then it would be encoded like: `WIFI:S:\"foo\;bar\\baz\";;`

IMO this is easier to read though:
> Order of fields does not matter. Special characters `\`, `;`, `,` and `:` should be escaped with a backslash (`\`) as in MECARD encoding. For example, if an SSID was literally `"foo;bar\baz"` (with double quotes part of the SSID name itself) then it would be encoded like: `WIFI:S:\"foo\;bar\\baz\";;`

**Comment by srowen** [comment]
Good catch, done.

**Comment by black-snake** [comment]
Just found out the hard qay that another character needs to be escaped as well: `/` must be escaped by a backslash so that `/` becomes `\/`.

**Comment by srowen** [comment]
@black-snake can you give an example? I just tried a WIFI: URI with a forward slash and it appeared to work fine without escaping.

**Comment by black-snake** [comment]
Hi,

sorry for the late reply.

So I have a WPA2-Key that contains the literal `/` and I tried the following data for the QR code and the connection with my Apple iPhone (latest OS version 12) failed to connect. After some trial and error I escaped the literal `/` so that is becomes `\/` and finally it worked.

## example
key: `abc123/` *(don't worry, this is not my real WPA2 key)*

- doesn't work

        WIFI:T:WPA;S:My_WiFi_SSID;P:abc123/;;

- does work

        WIFI:T:WPA;S:My_WiFi_SSID;P:abc123\/;;

**Comment by srowen** [comment]
Hm, when I try your first string, the passwords is parsed as "abc123/" as desired. I think something else is going on?

**Comment by black-snake** [comment]
@srowen Sorry, you're right! The escaping `\` is not needed in front of `/`. Strange enough, it works **with** and **without** escaping on my phone now... At first, it didn't but that was probably due to another issue. Sorry for the confusion.
