### ISSUE TITLE
Bug in QRcode/Detector/ FinderPattern[] selectBestPatterns()

### ISSUE THREAD

**Issue by Quatrus** [zxing/zxing#1144]
### Bug Reports

624      for (int i = 0; i < possibleCenters.size() && possibleCenters.size() > 3; i++) {
625        FinderPattern pattern = possibleCenters.get(i);
626        if (Math.abs(pattern.getEstimatedModuleSize() - average) > limit) {
627          possibleCenters.remove(i);
628          i--;
629        }
630      }
I am pretty sure that line 626 is wrong. As written it removes the GOOD patterns.
So it should be 
 if (Math.abs(pattern.getEstimatedModuleSize() - average) < limit) {

**Comment by srowen** [comment]
No, it's checking whether the module size in the candidate is too different from the average. The check is correct. You can verify by trying your change; lots of tests fail.

**Comment by Quatrus** [comment]
Yes, sorry, I was too fast with the conclusions. The point is that I have a big set of test images and on some of them this test is wrong. I work with the C++ version and modified the code the following way
```  if (startSize > 3) {
    // But we can only afford to do so if we have at least 4 possibilities to choose from
    int   total = 0;      //<-----new
    float totalModuleSize = 0.0f;
    float average,stdDev,square = 0.0f;
    for (std::size_t i = 0; i < startSize; i++) {
      float size = possibleCenters_[i]->getEstimatedModuleSize();
      if (size != 1.0f)
      {
        totalModuleSize += size;
        square += size * size;
        total++;   //<-----new
      }
    }
    if(total)     //<-----new
    {
       average = totalModuleSize / total;   //<-----new
       stdDev = (float)std::sqrt(square / total - average * average); //<-----new
    }
    else
    {
       average = 1; //<-----new
       stdDev  = 0; //<-----new
    }

    sort(possibleCenters_.begin(), possibleCenters_.end(), FurthestFromAverageComparator(average));
    
    float limit = max(0.2f * average, stdDev);

    for (std::size_t i = 0; i < possibleCenters_.size() && possibleCenters_.size() > 3; i++) {
      if (abs(possibleCenters_[i]->getEstimatedModuleSize() - average) > limit) {
        possibleCenters_.erase(possibleCenters_.begin()+i);
        i--;
      }
    }
  }
```
Now it works MUCH better (for me ;) )

What I did was to exclude the possible centers with suspicious  module size of 1 from the  _average_ and from the _limit_

**Comment by Quatrus** [comment]
![image](https://user-images.githubusercontent.com/48251280/53818693-c671b480-3f68-11e9-9c5d-cba570440a21.png)
I am trying to upload a demo image.
In my setup this image failed to be decoded using the Hybrid Binarizer and then was decoded using the GlobalHistogram

**Comment by srowen** [comment]
You can open a pull request with a similar change here. The question is whether it makes more images fail than succeed.

**Comment by Quatrus** [comment]
I use about 1200 images in my regression test and for the time being I do not see images to fail becuase of the change. Unfortunately there are images where selectBestPattern still fails.
For example, on the image below using after the HybridBinarizer there are 72 candidates. Sorting them using FurthestFromAverageComparator set the good ones on the top but further filters discard them. 
Then the image is successfully decoded using the GlobalHistogramBinarizer but I would like to improve the selection somehow instead of using the backup solution

![image](https://user-images.githubusercontent.com/48251280/53823273-b90cf800-3f71-11e9-8e38-a29f49598077.png)
