### ISSUE TITLE
ITF barcodes from some Brazilian companies cannot be decoded by zxing v3.3.2+

### ISSUE THREAD

**Issue by gziolle** [zxing/zxing#1148]
Since v3.3.2 update, some ITF barcodes from Brazilian companies cannot be decoded by zxing.
These barcodes are decoded by ZXing v3.3.0
I tested the releases with an app I made and with Barcode Scanner, and in both cases zxing v3.3.2+ cannot decode the barcodes.

I attached an sample for reference and testing purposes.
![barcode-original](https://user-images.githubusercontent.com/1500586/54603659-a7bcf480-4a23-11e9-96e7-7df0a61086c5.png)

**Comment by srowen** [comment]
I'm not sure what would have changed, but I'm not accepting reports like this. If you can identify a change that improves scanning on this one without harming other cases, open a PR.
