### ISSUE TITLE
Scanning only works when barcode is alligned on redline

### ISSUE THREAD

**Issue by prpadhi** [zxing/zxing#1150]
Hi,
We are developing an application using zxing library. We are facing one issue where we are able to scan properly only when the redline is on or over the barcode. As per the requirement we want to scan the barcode regardless of the position in camera. Means once barcode is displayed in viewer application should read the barcode. 
Is there any option which is readily available in ZXing library or any work arounds available?
Please suggest if solution is available or we cannot achieve this using ZXing.

Regards
Priya Ranjan

**Comment by srowen** [comment]
It's really that it only looks in the rectangular reticle. That is by design, to prompt users to hold the camera far enough away. You can modify the app to look at the whole image. The library itself always looks at the whole image it's given.
