### ISSUE TITLE
Want to enable beep on successful scan

### ISSUE THREAD

**Issue by prpadhi** [zxing/zxing#1151]
Hi,
We have a requirement where we want to set a beep sound on every successful scan.
Is it possible to achieve this with latest ZXing.Net.Mobile(2.4.1) library?

Regards
Priya Ranjan

**Comment by srowen** [comment]
The app in this project has done that for 10 years. You're talking about a separate project here, actually.

**Comment by prpadhi** [comment]
Hi srowen,

I am new to this library and i am not clear with your reply. 
Is this feature available in ZXing.Net.Mobile(2.4.1) library or we need to refer some other library. 
If this feature is already available can you please suggest how to achieve it?

Thanks
Priya ranjan

**Comment by srowen** [comment]
Zxing.net is a different library
