### ISSUE TITLE
[Q] Custom barcode zebra format

### ISSUE THREAD

**Issue by kashkashio** [zxing/zxing#1152]
Hello
I wonder if it's possible to create a custom barcode that will be unique to me?
can i create another format of my own using predefined symbols and spaces and line widths ?

let say i want to set that
e.g:
| || | ||| | = 1
|| || | | ||| = 2

and to be able to use zxing to read this custom barcode?

Thanks a lot

**Comment by srowen** [comment]
You can implement support for whatever you like, extending this library, but no the library doesn't do that for you.
