### ISSUE TITLE
Split packages between javase and core JARs prevent use as Automatic Module

### ISSUE THREAD

**Issue by msgilligan** [zxing/zxing#1153]
Both the `javase` and `core` JARs have classes in the package `com.google.zxing`. This prevents usage as an "Automatic Module" under the Java Platform Module System (Java 9+)

This results in errors like the following:
```
error: the unnamed module reads package com.google.zxing from both javase and core
error: module com.google.common reads package com.google.zxing from both core and javase
```

There are at least two solutions
1. Refactor the modules to avoid split packages (this is probably a breaking change)
2. Combine the two jars into a single jar for JavaSE.

**Comment by srowen** [comment]
Yeah, would love to all else equal, but it's a breaking change, so I don't think it's worth doing. It doesn't declare anything as exported or not like all pre-Java-9 JARs, so everything remains available from both JARs as intended.

**Comment by schildbach** [comment]
Combining JARs could be done via the build system and then uploaded as an additional artifact.

**Comment by msgilligan** [comment]
For those interested, we resolved the issue in **bitcoinj** by removing the `com.google.zxing:javase:3.3.3` dependency and replacing it with `com.google.zxing:core:3.3.3`. It turns out we were better off converting the `BitMatrix` directly to a JavaFX `Image` than using the `javase` module as we had been doing.

The resolving PR is here: https://github.com/bitcoinj/bitcoinj/pull/1776
