### ISSUE TITLE
Add Automatic-Module-Name attribute to core jar (minimal Java Module support)

### ISSUE THREAD

**Issue by msgilligan** [zxing/zxing#1154]
The `core` JAR should work as an automatic Java Module as long as it is not used in conjunction with the `javase` JAR (which causes a split package problem see PR #1153).

Unfortunately, the Java module system defaults to using the filename (in this case `core`) as the module name and this is very confusing to see in code as many libraries have a `core` module.

I suppose it should be `com.google.zxing`. I don't think it makes sense to do this for any of the other modules, but maybe I'm unaware of a use case.

If this sounds OK to the maintainers, I'll submit a pull request.

**Comment by msgilligan** [comment]
And I have verified that the `core` jar does run as an Automatic Module in a module JavaFX 11 app! (at least basic QR generation is working)

**Comment by srowen** [comment]
What does this entail? We can't change things like the maven artifact name or package of existing classes, but if it's strictly a new setting that can't break anything , could be fine

**Comment by msgilligan** [comment]
It's adding one-line entry to the `MANIFEST.MF` file in the JAR:

```
Automatic-Module-Name: com.google.zxing
```

Artifact names and existing packages don't have to change. There is a restriction on "split packages" which would prevent us from doing the same to the other JARs. But since there will be problems under the module system for those JARs anyways, this is:

1.  The best we can do
2. A useful improvement for Java 9+

Shall I prepare a PR?

**Comment by msgilligan** [comment]
This blog post provides helpful background information:
http://branchandbound.net/blog/java/2017/12/automatic-module-name/

**Comment by srowen** [comment]
That makes sense to me, as long as it wouldn't trigger any automated export/import restrictions from the JAR when used on Java 9+. This will be the only module we can really name.

**Comment by msgilligan** [comment]
This won't change export/import behavior -- On Java 9+ it will still have the same rules for "Automatic Modules" as before. The only difference is the the module name will be `com.google.zxing` rather than the filename which is the uninformative and possibly conflicting `core`.

**Comment by msgilligan** [comment]
@srowen PR submitted #1155

**Comment by msgilligan** [comment]
PR #1155 is merged.

**Comment by msgilligan** [comment]
I went ahead and submitted PR #1162 which makes the `javase` module work as an automatic module. I know it will be rejected (at least as is) but thought I'd submit if for completeness. (And because I did it so I could use it in a project via https://jitpack.io)
