### ISSUE TITLE
IndexOutOfBounds when encoding a PDF417

### ISSUE THREAD

**Issue by Doophie** [zxing/zxing#1163]
I'm trying to encode a PDF417 and whenever I set the `PDF417_COMPACTION` to `Compaction.TEXT` I get this crash: 

```
    java.lang.ArrayIndexOutOfBoundsException: length=128; index=8226
        at com.google.zxing.pdf417.encoder.PDF417HighLevelEncoder.isMixed(PDF417HighLevelEncoder.java:456)
        at com.google.zxing.pdf417.encoder.PDF417HighLevelEncoder.encodeText(PDF417HighLevelEncoder.java:298)
        at com.google.zxing.pdf417.encoder.PDF417HighLevelEncoder.encodeHighLevel(PDF417HighLevelEncoder.java:185)
        at com.google.zxing.pdf417.encoder.PDF417.generateBarcodeLogic(PDF417.java:649)
        at com.google.zxing.pdf417.PDF417Writer.bitMatrixFromEncoder(PDF417Writer.java:107)
        at com.google.zxing.pdf417.PDF417Writer.encode(PDF417Writer.java:87)
        at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
```

Here is the code for how I am trying to create the barcode: 

```
        var hints: MutableMap<EncodeHintType, Any>?
        
        hints = EnumMap<EncodeHintType, Any>(EncodeHintType::class.java)
        
        hints[EncodeHintType.CHARACTER_SET] = "UTF-8" 
        hints[EncodeHintType.ERROR_CORRECTION] = 6
        hints[EncodeHintType.PDF417_COMPACTION] = Compaction.TEXT
        
        val writer = MultiFormatWriter()
        val result: BitMatrix
        try {
            result = writer.encode(contents, format, img_width, img_height, hints)
        } catch (iae: WriterException) {
            // Unsupported format
            return null
        }
```

Is this a bug or am i doing something wrong?

**Comment by srowen** [comment]
I suspect it's a bug, and I unfortunately have no idea what. I think there are a few latent bugs in the PDF417 parts. If you figure it out, feel free to open a PR. What language is this BTW?

**Comment by Doophie** [comment]
will do, the language is kotlin

**Comment by Doophie** [comment]
@srowen After looking into it a bit more, my data contained a • character and it was checking that character that it crashed and got the index out of bounds. If i have time later i'll see if i can fix the crash.

**Comment by hidethatbug** [comment]
> I suspect it's a bug, and I unfortunately have no idea what. I think there are a few latent bugs in the PDF417 parts. If you figure it out, feel free to open a PR. What language is this BTW?

i use java ,i work for android

**Comment by Doophie** [comment]
@hidethatbug did you by chance try using the  • character in what your contents?

**Comment by sanjaykumarm** [comment]
@srowen Do you know why PDF417 barcode is not scanned by app ? Just search PDF417 barcode like (https://www.google.com/search?q=PDF417+barcode&pws=0&gl=us&sxsrf=ACYBGNSdD_T7SKV1VFqCbhHS3vzXm_N4gQ:1570773894952&tbm=isch&source=iu&ictx=1&fir=kKc5tueauiP1qM%253A%252CQDBZhqzL1ExgMM%252C%252Fm%252F02v3gn&vet=1&usg=AI4_-kS4PwRJB9k7qOjj5BkX0-_iIHfYbg&sa=X&ved=2ahUKEwjVtJ_gxJPlAhVv6nMBHROaBo4Q_B0wG3oECAkQAw#imgrc=kKc5tueauiP1qM:&vet=1) and scan it, most of all barcodes are not detected by the app.

**Comment by khavnu** [comment]
What is your img_width, img_height?
This is my soluttion, you need to use realWidth = bitMatrix.getWidth()....:
       
BitMatrix bitMatrix = new MultiFormatWriter().encode(mContent, barcodeFormat, mWidth, mHeight, hintsMap);

            int realWidth = bitMatrix.getWidth();
            int realHeight = bitMatrix.getHeight();

            int[] pixels = new int[realWidth * realHeight];
            for (int i = 0; i < realHeight; i++) {
                for (int j = 0; j < realWidth; j++) {
                    if (bitMatrix.get(j, i)) {
                        pixels[i * realWidth + j] = 0x00000000;
                    } else {
                        pixels[i * realWidth + j] = 0xffffffff;
                    }
                }
            }
            Bitmap bitmap = Bitmap.createBitmap(pixels, 0, realWidth, realWidth, realHeight, Bitmap.Config.RGB_565);

**Comment by wvieed** [comment]
G

**Comment by srowen** [comment]
Likely fixed by https://github.com/zxing/zxing/pull/1514
