### ISSUE TITLE
Can't read datamatrix

### ISSUE THREAD

**Issue by sikemullivan** [zxing/zxing#1172]
Hi,

I have a pretty simple datamatrix that can't be read by Zxing. I've used a few other sites, and there is no issue. 

`var reader = new BarcodeReader();
reader.Options.TryHarder = true;
reader.Options.PossibleFormats = new List<ZXing.BarcodeFormat>() { ZXing.BarcodeFormat.DATA_MATRIX };

var text = reader.Decode(image)?.Text;`

![2019_05_29_15_13_23-x1-y0-75e84d tif barcode x0 y0](https://user-images.githubusercontent.com/23320600/58610860-a9e8ce00-8272-11e9-8946-ae53aa90cdf3.jpg)

**Comment by srowen** [comment]
Yeah, in this particular image it mis-detects where the barcode is. It's just an unfortunate consequence of how the heuristics work. It will read fine if you read it off the screen, or a small variation of the image, so it's just detection.

You're actually not using this project here anyway, but think the answer is the same for the port. There's no more work on this project, so unless someone has a clean improvement to the heuristic, it's just one of those images that won't decode.

**Comment by axxel** [comment]
Just in case this might help: if using c++ or WebAssembly is an option for you, have a look at the recent c++-port https://github.com/nu-book/zxing-cpp. It contains a complete reimplementation of the datamatrix detector code and is able to decode your image just fine. (online demo: https://nu-book.github.io/zxing-cpp/demo_reader.html)

**Comment by sikemullivan** [comment]
I'm using .NET Core. I can post this to the ported repo and see what they say.
