### ISSUE TITLE
Cannot scan this picture that has not good quality

### ISSUE THREAD

**Issue by yukangkangyu** [zxing/zxing#1175]
![picture](https://user-images.githubusercontent.com/22390894/59024306-410de100-8884-11e9-9f47-b53c2a3fc60c.png)

**Comment by yukangkangyu** [comment]
How can I fix it

**Comment by makiuchi-d** [comment]
It is better to adjust the contrast.
![a](https://user-images.githubusercontent.com/1674313/59033384-90afd500-88a3-11e9-9621-3788d3344d22.png)

**Comment by srowen** [comment]
The barcode scans fine. The image contrast is a bit too low.
