### ISSUE TITLE
Error before Android 24 version

### ISSUE THREAD

**Issue by Tamem-Maaz** [zxing/zxing#1177]
I am running this library in hand terminal device that has android 22 version.
The issue about sort list inside class **FinderPatternFinder** and function **selectBestPatterns**

    int startSize = possibleCenters.size();
    if (startSize < 3) {
      // Couldn't find enough finder patterns
      throw NotFoundException.getNotFoundInstance();
    }

    possibleCenters.sort(moduleComparator);

    double distortion = Double.MAX_VALUE;
    double[] squares = new double[3];
    FinderPattern[] bestPatterns = new FinderPattern[3];

This sort way did not support it in android 22
`possibleCenters.sort(moduleComparator);`

I think it must change to
`Collections.sort(possibleCenters, moduleComparator);`

**Comment by srowen** [comment]
No, the core library requires Java 8, which requires API 24.  Require API 24 or stick to version 3.3.3..
