### ISSUE TITLE
Some QR Codes are not scanning by zxing but working fine in some other apps

### ISSUE THREAD

**Issue by usmanrana07** [zxing/zxing#1182]
There are some QR codes that are not recognizing by zxing android library but working fine with many other apps at playstore. I saw a sample [https://github.com/EdwardvanRaak/MaterialBarcodeScanner](url) as well which is using google vision library and is recognizing same image very quickly. Is there some limitation in zxing? Before moving to any other option i want to be sure about that as zxing has very good rating that other libs.

Attached a sample QR image:
[https://drive.google.com/open?id=1Rv09Opx7seWXdSPH7xMKGbU9V8UhXlWI](url)

**Comment by srowen** [comment]
Yep, that's just how it is. Some barcodes will scan and some won't. There is no more work on this library. That link doesn't open BTW.

**Comment by usmanrana07** [comment]
updated the url

**Comment by srowen** [comment]
That barcode is simply too light.

**Comment by usmanrana07** [comment]
but same is working very well with above mentioned sample which is using google vision library.

**Comment by srowen** [comment]
I'm sure it's a better scanning library and you should use it. But technically this is an invalid barcode as the contrast separation is far too small.

**Comment by usmanrana07** [comment]
Can we add that support in zxing to make it scan this kind of qr codes as well? Because many of the major apps are using this kind of QR codes and it has become an essential part. Thanks
