### ISSUE TITLE
Redmi 5 plus  getConfigForPhoneId subId is invalid

### ISSUE THREAD

**Issue by wanwanlyss** [zxing/zxing#1183]
Demo can't run in Redmi 5 plus，Log is  getConfigForPhoneId subId is invalid，isCarrierConfigEnabled bundle is null，what is the reason？

**Comment by srowen** [comment]
There's no demo, and those errors sound like phone logs, not app

**Comment by wanwanlyss** [comment]
Thanks,  There is no bug after updating the phone system.
