### ISSUE TITLE
I unable to import some QR image

### ISSUE THREAD

**Issue by NeerajSinghUnnao** [zxing/zxing#1185]
I unable to import some QR image example image bellow:
![BDO201907010214](https://user-images.githubusercontent.com/5018099/60647894-6595b280-9e5c-11e9-8513-0212ff08ee5e.png)

**Comment by NeerajSinghUnnao** [comment]
What is this only close ticket you don't have any idea what is wrong with this qr image?

**Comment by srowen** [comment]
You didn't read the text you deleted to open this.
