### ISSUE TITLE
Inverted DataMatrix

### ISSUE THREAD

**Issue by kuleshovdv** [zxing/zxing#1187]
Hi!
How you think does possible to ZXing reading barcode like this [https://wiki.lineris.ru/_detail/marka/tobacco/mark_code.jpg](https://wiki.lineris.ru/_detail/marka/tobacco/mark_code.jpg)
This is inverted DataMatrix.
Invert scan option doesn't work with this barcode.

**Comment by srowen** [comment]
You just have to invert the image then pass to the library

**Comment by kuleshovdv** [comment]
It was first that I try. Dont't work.
