### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by dharmeshajudiya48** [zxing/zxing#1190]
##Issue 
I use zxing in my production and when I try PDF_417 and AZTEC, it thorws NumberFormatExcpetion for ErrorCorrectionLevel.M, I checked internally writer file for both BarCodeFormat, it try to convert ErrorCorrectionLevel.M to Integer 

##Code
`/*
   * This method return barcode based on parameter type and qrCodeRepresentation
   */
  public static ByteArrayOutputStream createBarcode(String qrCodeRepresentation, String type)
  {
    try 
    {
      final int size = 160;
      int width = 420;
      int height = 60;
      BarcodeFormat barcodeFormat = getBarcodeFormat(type);

      final Hashtable<EncodeHintType, ErrorCorrectionLevel> hintMap = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();
      hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.M);

      // Check barcode format and create BitMatrix for barcode 
      // Not passing hintMap to AZTEC and PDF_417, because internally it convert ErrorCorrectionLevel.M and it throws NumberFormatException
      // It is zxing error so just cover up our code to not pass EncodeHintType.ERROR_CORRECTION
      final BitMatrix byteMatrix = is2DBarcodeType(barcodeFormat) 
                                     ? (barcodeFormat.equals(BarcodeFormat.AZTEC )|| barcodeFormat.equals(BarcodeFormat.PDF_417))
                                         ? new MultiFormatWriter().encode(qrCodeRepresentation, barcodeFormat, size, size) 
                                         : new MultiFormatWriter().encode(qrCodeRepresentation, barcodeFormat, size, size, hintMap)
                                     : new MultiFormatWriter().encode(qrCodeRepresentation, barcodeFormat, height, width, hintMap);

      final int crunchifyWidth = byteMatrix.getWidth();
      final BufferedImage image = new BufferedImage(crunchifyWidth, crunchifyWidth, BufferedImage.TYPE_INT_RGB);
      image.createGraphics();

      final Graphics2D graphics = (Graphics2D) image.getGraphics();
      graphics.setColor(Color.WHITE);
      graphics.fillRect(0, 0, crunchifyWidth, crunchifyWidth);
      graphics.setColor(Color.BLACK);

      for (int i = 0; i < crunchifyWidth; i++) {
          for (int j = 0; j < crunchifyWidth; j++) {
              if (byteMatrix.get(i, j)) {
                  graphics.fillRect(i, j, 1, 1);
              }
          }
      }
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      ImageIO.write(image, "png", baos);
      InputStream is = new ByteArrayInputStream(baos.toByteArray());
      return baos;
    } 
    catch (final WriterException e) 
    {
        e.printStackTrace();
    }
    catch (IOException e)
    {
      e.printStackTrace();
    }
    return null;
  }
  
  
  /*
   * This method return BarcodeFormat based on barcodeType parameter
   * If it not match it return default CODE_39 BarcodeForamt
   */
  public static BarcodeFormat getBarcodeFormat(String barcodeType)
  {
    if(barcodeType == null || barcodeType.isEmpty())
      barcodeType = "CODE_39";
    
    switch (barcodeType.toUpperCase())
    {
      case "EAN_8" :
        return BarcodeFormat.EAN_8;
      case "UPC_E" :
        return BarcodeFormat.UPC_E;
      case "EAN_13" :
        return BarcodeFormat.EAN_13;
      case "UPC_A" : 
        return BarcodeFormat.UPC_A;
      case "QR_CODE" :
        return BarcodeFormat.QR_CODE;
      case "CODE_39" : 
        return BarcodeFormat.CODE_39;
      case "CODE_93" : 
        return BarcodeFormat.CODE_93;
      case "CODE_128" : 
        return BarcodeFormat.CODE_128;
      case "ITF" : 
        return BarcodeFormat.ITF;
      case "PDF_417" : 
        return BarcodeFormat.PDF_417;
      case "CODABAR" :
        return BarcodeFormat.CODABAR;
      case "DATA_MATRIX" :
        return BarcodeFormat.DATA_MATRIX;
      case "AZTEC" : 
        return BarcodeFormat.AZTEC;
      default:
        return BarcodeFormat.CODE_39;
      
    }
  }
  
  /*
   * This method return true if BarcodeFroamt it 2D format
   */
  public static boolean is2DBarcodeType(BarcodeFormat barcodeFormat) 
  {
    return barcodeFormat.equals(BarcodeFormat.DATA_MATRIX) || 
           barcodeFormat.equals(BarcodeFormat.QR_CODE) ||
           barcodeFormat.equals(BarcodeFormat.PDF_417) ||
           barcodeFormat.equals(BarcodeFormat.MAXICODE) ||
           barcodeFormat.equals(BarcodeFormat.AZTEC);
  }`

##Solution 

I also check QA_CODE writer and seems it use string as it is, so we can use same for PDF_417 and 
AZTEC, for workaroun I didn't pass ERROR_CORRECTION hints

**Comment by srowen** [comment]
I'm not sure what you're reporting, but it seems like an error in your code
