### ISSUE TITLE
Distinguise between WEP, WPA-PSK, WPA-EAP, WPA2-PSK and WPA2-EAP

### ISSUE THREAD

**Issue by Meteor0id** [zxing/zxing#1194]
Currently a WPA2 PSK CCMP network is simply indicated by T:WPA;

I noticed the implementation on Android isn't working. Oddly, WPA2-EAP has been added, but WPA2 is not a valid type, nor is WPA2-PSK.

The current type indicators are therefore ambiguous.

Whether CCMP and TIKP need to be part of the type name, I am not certain (T:WPA-PSK-TKIP; and T:WPA-PSK-CCMP;). But lets at least prevent implementation issues by amending ambiguous type indicators.

**Comment by srowen** [comment]
What change are you suggesting? does parsing need to change, or how the parsed values translate into Android API calls, or?
