### ISSUE TITLE
Reset ck

### ISSUE THREAD

**Issue by Swuzzlebubble** [zxing/zxing#1195]
Cannot clear or reset the share option.
So if you select an option which does not work but had selected remember choice, you are stuck.

**Comment by Punkroku** [comment]
I am not sure I understood. I wasnt asking for a feature request but I
am looking for talented coders.

openInvent.club/forum

**Comment by Swuzzlebubble** [comment]
I loaded up a list of barcodes via the scanner app

Then I selected ‘share to device’ and ‘remember my choice’

However ‘share’ didn’t work – I should have chosen email

There was no way to unselect ‘share to device’.

So I had to rescan the items with another app.
