### ISSUE TITLE
Url with * in it misbehaves

### ISSUE THREAD

**Issue by jeffallen** [zxing/zxing#1196]
Some car charging stations have qr codes on them with URLs in them like this: http://m.intercharge.eu/qr?evseid=CH*CCC*E50081

The result view shows the whole url, but the clickable part stops at the first *. This might be because the * should be % escaped, but the fact is there are thousands of qr codes out there in this format, so if they were clickable it would be helpful.

I will look into how to fix this when I can.

**Comment by srowen** [comment]
I was going say, is a `*` safe to use without encoding in an HTTP URL? but it is.
The linkification is done by Android:
https://developer.android.com/reference/android/widget/TextView.html#attr_android:autoLink
I'm not sure why it doesn't link the whole thing. It's set to create links from 'web' URLs which seems correct here. I'm not sure if it's possible to fix from the app.
