### ISSUE TITLE
Nearly impossible to scan on Samsung S5 mini

### ISSUE THREAD

**Issue by NicoWeio** [zxing/zxing#1197]
Scanning barcodes on the Samsung Galaxy S5 mini is nearly impossible, as it fails to recognize anything, even though the camera gets a razer-sharp image with good contrast. The yellow dots, which should indicate the start of a 2D-barcode appear somewhat randomly, but never on the actual start of a barcode.

Strange things can be seen when I do get a scan result, which might hint at what the problem is:

![Screenshot_2019-08-11-18-33-24](https://user-images.githubusercontent.com/12870528/62836907-e66c7900-bc68-11e9-9d5d-d605cf193428.png)

**Comment by srowen** [comment]
That suggests the preview data is incorrect. This is typically some kind of camera driver issue. You might be able to dig out more from the logs, but I don't think there's much the app can do about it. Try restarting the phone too.
