### ISSUE TITLE
Junk character are displayed in scan result

### ISSUE THREAD

**Issue by deepak160988** [zxing/zxing#1198]
Hi Guys,
I'm using 'me.dm7.barcodescanner:zxing:1.9.13' library in my android project.
When I scan in normal angle it is giving me correct input.
but in case if i tilt(45 degree) and scan the bar code, it is displaying some junk character.

I created a barcode for "body", i tilted the scanner to 45 degree and when i scanned barcode of "body" it displays a junk character 04328100. 

Kindly let me know is there any solution to solve this problem??
Thanks in advance

Thanks and Regards,
Deepak

**Comment by srowen** [comment]
This is a different library, so I don't think this is the right place.
However I'm pretty sure it's a false read of an EAN-8 code, which can happen at times though rarely. You can turn off scanning for those barcodes probably.

**Comment by deepak160988** [comment]
oh ya.. sorry. But anyway thanks for the suggestion :-)
