### ISSUE TITLE
3.4.0 version open proguardFiles compilation failed

### ISSUE THREAD

**Issue by kamike** [zxing/zxing#1199]
I use the 3.2.0 version and everything works fine.When I use the 3.4.0 version and open proguardFiles generating apk，it's build error.My proguard-rules.pro Already added
-keep class com.google.zxing.** {*;}
-dontwarn com.google.zxing.**

android studio=3.4.1
java_sdk=1.8
compile_sdk_version = 26
support_version = 26.2.0
min_sdk_version = 19
target_sdk_version = 26

How should I solve the problem

**Comment by srowen** [comment]
It builds OK for me, and you provided no information about the error.

**Comment by kamike** [comment]
I found that the class com.github.jaiimageio* is reporting an build error.I added the following code to the proguard-rules file.It’s build  successfully.

-keep class com.github.jaiimageio.** {*;}
-dontwarn com.github.jaiimageio.**

**Comment by srowen** [comment]
JAI is not included in any artifact that should be optimized with proguard. You may have modified the build. It is only used on the core and android artifacts. JAI is used by javase.
