### ISSUE TITLE
Wrong EAN13 code detected - am I doing something wrong?

### ISSUE THREAD

**Issue by ttsiodras** [zxing/zxing#120]
![why](https://cloud.githubusercontent.com/assets/181293/2775177/b3bd1e44-cac2-11e3-8200-766268c572f4.png)

The above-attached image is wrongly detected - I used:

```
wget https://github.com/zxing/zxing/archive/master.zip
unzip master.zip
cd zxing-master/
mvn compile
cd javase/target/classes/
java -cp .:../../../core/target/classes com/google/zxing/client/j2se/CommandLineRunner why.png --try_harder  --pure_barcode
```

...which prints a wrong number (compare to that in the image):

```
Raw result:
000642109420
Parsed result:
000642109420
Found 2 result points.
  Point 0: (78.5,64.0)
  Point 1: (335.5,64.0)
```

Am I doing something wrong, or is this kind of errors something to be expected when trying to detect barcodes?

P.S. In case it helps, the barcode was generated inside a Jasper Report, with the Barbeque library, and the document was then scanned back.

**Comment by Jendorski** [comment]
I am also facing this issue, hopefully using Code 128 will help ensure the barcodes return the right numbers, with this format.
