### ISSUE TITLE
【android】tips I need to install Google play

### ISSUE THREAD

**Issue by cxyhegithub** [zxing/zxing#1203]
I can normal installation zxing, but when I start the zxing tips I need to install Google play, how do I solve (I don't want to have such a prompt)? thanks
Can you give me some information to solve this problem
（Chinese mobile phone brand vivo）
![63648060-b6d76980-c75c-11e9-9698-5ecf297131cf](https://user-images.githubusercontent.com/26237184/63661613-e6828200-c7ed-11e9-9a99-f0c04e9ed6cd.png)

**Comment by srowen** [comment]
I'm not sure what you are asking, but this app is only distributed by the project on Play. Debugging anything else is up to you and not supported

**Comment by cxyhegithub** [comment]
I downloaded the source code from github and ran it on my phone. I could install the app normally, but when I opened the app, it prompted me to install Google play first. But my users in China, we don't really need Google play @srowen

**Comment by IrishVampyre** [comment]
Downloadbit rom Amazon prime here maybe ?


"HOW TO INSTALL YOUR GOOGLE PLAY ON KINDLE FIRE: Easy Ways To Install Google Play And Get Your Favorite Apps And Games On Kindle Fire In 5 Minutes." by TOM M. LEON
http://amzn.eu/33lhFbz



Sent from myMail for iOS


Monday, 26 August 2019, 03:43 +0100 from notifications@github.com <notifications@github.com>:

Closed #1203<https://github.com/zxing/zxing/issues/1203>.
