### ISSUE TITLE
Not able to write more than 80 character barcode

### ISSUE THREAD

**Issue by sonisudarshan0** [zxing/zxing#1205]
While creating barcode i have found that barcode is not generating for more than 80 characters below is my code and attached error details

![image](https://user-images.githubusercontent.com/50704950/64023944-f506cb80-cb56-11e9-8463-08c1accec8aa.png)

error:

![image](https://user-images.githubusercontent.com/50704950/64024061-36977680-cb57-11e9-8b5e-bb9482e4ba9c.png)

**Comment by srowen** [comment]
You are writing about zxing.net here, a different project. That said you should verify whether GS1 has this max limit; the error may be correct.
