### ISSUE TITLE
PDF 417 encoding windows 1251 

### ISSUE THREAD

**Issue by sonfiree** [zxing/zxing#1206]
How to set encoding?

```
 Traceback (most recent call last):
  File "C:/Users/user/test.py", line 14, in <module>
    barcode = reader.decode("Screenshot_121.png")
  File "C:\Anaconda3\lib\site-packages\zxing\__init__.py", line 41, in decode
    return BarCode.parse(stdout)
  File "C:\Anaconda3\lib\site-packages\zxing\__init__.py", line 81, in parse
    raw = raw[:-1].decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 8: invalid start byte
```

**Comment by sonfiree** [comment]
windows 1251 `|????????|?????|?????????|`

**Comment by srowen** [comment]
This is ultimately a question about a python wrapper package that isn't part of this library. https://github.com/dlenski/python-zxing

**Comment by sonfiree** [comment]
Everything is fine with zxing, this is a problem in python-zxing

**Comment by sonfiree** [comment]
> This is ultimately a question about a python wrapper package that isn't part of this library. https://github.com/dlenski/python-zxing

Everything is fine with zxing, this is a problem in python-zxing
