### ISSUE TITLE
Problem with generating barcode image from text

### ISSUE THREAD

**Issue by NiccoloZaza** [zxing/zxing#1210]
Hello. My problem is that zxing works on most of the barcodes but the ones with character '¿'. I don't know what to do. It scans it without problem but can't create image out of it. So for example, it does not work on barcodes like this ";1513515¿". here is my code

```
    private void generateBarcode(String barcodeText, BarcodeFormat format) {
        try {
            Map<EncodeHintType, Object> hints = new EnumMap<>(EncodeHintType.class);
            hints.put(EncodeHintType.CHARACTER_SET, "UNICODE");
            MultiFormatWriter multiFormatWriter = new MultiFormatWriter();
            BitMatrix bitMatrix = multiFormatWriter.encode(barcodeText, format, 300, 80, hints);
            BarcodeEncoder barcodeEncoder = new BarcodeEncoder();
            Bitmap bitmap = barcodeEncoder.createBitmap(bitMatrix);
            imgViewBarcode.setImageBitmap(bitmap);
        } catch (WriterException e) {
            e.printStackTrace();
        }
    }
```

I have tried this code without hints, with UTF-8, UTF-16 and UTF-32 but no luck.

It crashes on 
`BitMatrix bitMatrix = multiFormatWriter.encode(barcodeText, format, 300, 80, hints);`
and throws this exception

>  Caused by: java.lang.IllegalArgumentException: Bad character in input: ¿

**Comment by srowen** [comment]
There is no charset "UNICODE"; you need something like "UTF-8". These are the standard names in the JVM.

**Comment by NiccoloZaza** [comment]
> There is no charset "UNICODE"; you need something like "UTF-8". These are the standard names in the JVM.

How can you reply that when i clearly said that i have already tried every other charset but it does not work

**Comment by srowen** [comment]
That's not how I read it; best to show a valid code snippet that reproduces it, not one with an obvious problem, right?

More of the stack trace would be useful, because, I have a better guess: you also didn't show the format you are encoding, and few formats can encode even non-digit input.

Reconsider how you are approaching asking for help here.

**Comment by NiccoloZaza** [comment]
Well, i am using code128 format. Even though it can scan a barcode with "¿" character, it can't generate image from it afterwards. And the problem is with unicode character because code128 works on ascii characters so if you do have any easy solution i would appreciate it(because i have already fixed it with complex code which i don't like)

**Comment by srowen** [comment]
OK, that's the issue Code 128 sort of supports Latin-1 (not Unicode): https://en.wikipedia.org/wiki/Code_128 This isn't currently implemented in the library though.  If you want to try implementing it and it works, open a pull request.
