### ISSUE TITLE
Issue in Barcode reading from Android gallery.

### ISSUE THREAD

**Issue by imspatni** [zxing/zxing#1211]
**Scenario:** We are working on a use case to read barcode from Android gallery. Barcode image we using contains some additional component, e.g. service Logo, Name info. Please note, we are generating QR Code via Zxing lib only.

**Issue:**

1. If name-info contain character like `testPC` then QR does not get read,

1. while if I make name (all in small) `testpc` then it work without any issue.

**What alternatively have been tried**

1. Cropped image with QR image only, it's readable. But not an easy solution to auto detect barcode and given for scanning.

1.  If I flip the image to 180-degree then it read barcode without any issue.

1. For validation purpose alternatively I'm using [online Zxing decoder](https://zxing.org/w/decode.jspx).

**What is expectation**

1. It should not make any trouble irrespective of screen content.

1. Does Zxing provide any standard configuration while generating barcode image with other screen element. Any configuration about element placement !!

**Comment by srowen** [comment]
I don't know, you didn't provide a QR code. It's definitely possible some images aren't recognized and that's not a bug per se. The online decoder is willing to spend more cycles flipping and altering the barcode, whereas it doesn't on a phone.

**Comment by imspatni** [comment]
@srowen here is image for reference. As earlier mentioned it is random and because of combination of other element on screen it is getting failed.

![sample_fail](https://user-images.githubusercontent.com/31846361/65330151-9d003980-dbd7-11e9-8187-de58ef87da3f.png)

Any suggestion around this ?

**Comment by srowen** [comment]
I think it's simply a misread. It's actually easier to find the wrong corner points in an image like this. It reads fine if you scan it off the screen, for example. There's nothing to do except try variations of the image, if you must read this exact image.

**Comment by imspatni** [comment]
sorry but not getting this.

1. How to find wrong corner ? Do you mean there is an issue with Bar-code image generation !
2. When you say variation, does that mean by generating new BARCODE ? Or I'm reading it wrong. Please correct.
