### ISSUE TITLE
Outputs incorrect barcode

### ISSUE THREAD

**Issue by dirtygardner** [zxing/zxing#1212]
BarCodeScanner_4.7.8

Actual-barcode=0000000990066
Output-barcode=000000990066

**Comment by srowen** [comment]
There isn't nearly enough info to help here anyway, but I'm guessing you are including the check digit in expected output. It's not part of the input.

**Comment by dirtygardner** [comment]
What other info is needed?
Scanned other barcodes and for every case Actual-barcode=Output-barcode

**Comment by srowen** [comment]
Well, what format? what is your input to what?

**Comment by dirtygardner** [comment]
UPC→number

**Comment by srowen** [comment]
UPC barcodes are 12 digits, not 13. The 13th digit is a check digit. It's checked if you supply it, and it's correctly encoded, but not considered part of the barcode. https://en.wikipedia.org/wiki/Universal_Product_Code

**Comment by dirtygardner** [comment]
So why is 0 omitted and 6 is not omitted?

**Comment by srowen** [comment]
You'd really have to show a barcode!

**Comment by dirtygardner** [comment]
Good idea, will take photos next time.
