### ISSUE TITLE
It looks blurry rarely on some android devices

### ISSUE THREAD

**Issue by CarlosEco** [zxing/zxing#1213]
Hi, i´m using ZXingScannerView and screen looks blurry only in some huawei devices like you can see in this image:

> https://s50.photobucket.com/user/CarlosEco/media/IMG_20190927_123724_zps4q8dlvmb.jpg.html

The library import is: 
` implementation 'com.journeyapps:zxing-android-embedded:3.6.0'`

The tag that i´m using on my xml is: 
`<me.dm7.barcodescanner.zxing.ZXingScannerView
            android:layout_width="match_parent"
            android:layout_height="match_parent" />`

**Comment by srowen** [comment]
You're asking about your code, and a different library. This isn't the place.
