### ISSUE TITLE
Migrate LGTM.com installation from OAuth to GitHub App

### ISSUE THREAD

**Issue by LGTM-badger** [zxing/zxing#1217]
Hi There,

This project is still using an old implementation of LGTM's automated code review, which has now been disabled. To continue using automated code review, and receive checks on your Pull Requests, please [install the GitHub App](https://github.com/apps/lgtm-com/installations/new) on this repository.

Thanks,
The LGTM Team

**Comment by srowen** [comment]
OK, I installed the app and removed the webhook. Let me know if I need to do anything else.
