### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by iBrady** [zxing/zxing#1218]
Links on the documentation site are not working anymore. Where do I find the documentation?

**Comment by srowen** [comment]
The links at https://zxing.github.io/zxing/ aren't generated by the plugin - weird technical reasons I can't resolve. There is a previous issue about it. But everything else is there. The only meaningful documentation is the javadoc: https://zxing.github.io/zxing/apidocs/index.html

(It would have been better to say anything about the links you're looking for!)

**Comment by iBrady** [comment]
Thanks for the useful information! I won't waste my time looking for the other documentation 👍
