### ISSUE TITLE
Image Rotation support is not available for Android SDK.

### ISSUE THREAD

**Issue by imspatni** [zxing/zxing#1220]
I'm currently using zxing version library `com.google.zxing:core:3.3.2`. While debugging for  on non-scanned image scenario I learn about `DecodeHintType.TRY_HARDER`. What it do, it simply tell zxing SDK to rotate and try scanning one last time in case it failed to scan image earlier.

Here is the code snippet I'm using: 

```
LuminanceSource source = new RGBLuminanceSource(width, height, pixels);
        BinaryBitmap bBitmap = new BinaryBitmap(new HybridBinarizer(source));
        MultiFormatReader reader = new MultiFormatReader();
        try {
            HashMap<DecodeHintType, Object> decodeHints = new HashMap();
            decodeHints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
            Result result = reader.decode(bBitmap, decodeHints);
            qrImageReaderCallBack.onSuccessQrCodeDataFromImage(result.getText());
        } catch (NotFoundException e) {
            qrImageReaderCallBack.onFailedQrCodeDataFromImage();
        }
```
But since `LuminanceResource.isRotateSupported()` always return false and neither `RGBLuminanceSource` class override it, `OneDReader` class check `tryHarder && image.isRotateSupported()` check simply get discarded.

In cross verification I checked with other domain library e.g. iOS and Java which actually having other Luminance class implementation support which support image rotation.

- iOS platform  : ZXCGImageLuminanceSource
- JAVA platform: BufferedImageLuminanceSource 

Checked with other Luminance class implementation which are:
- InvertedLuminanceSource: Use to inverts the luminance, black to white and vice versa. 
- PlanarYUVLuminanceSource: Use for camera scanning.

does not serve the same purpose.

**So Questions here are**:

1.  Does Android library having any other Luminance class support to achieve the same ?
2. Can BufferedImageLuminanceSource from Java library be used for Android client ?

**Comment by srowen** [comment]
It doesn't support rotation, yes. You could implement it and contribute that. In Java it's more usual to read it as a BufferedImage and use BufferedImageLuminanceSource, which does.
