### ISSUE TITLE
用zxing生成的二维码，过段时间集体扫码失效，显示‘发生未知错误，请重试’

### ISSUE THREAD

**Issue by JohnsonChan** [zxing/zxing#1227]
这边用zxing生成二维码作为个人推广码或名片，使用了一段时间发现产品用户集体反馈，二维码扫不了了。
显示‘发生未知错误，请重试’
zxing生成的二维码，同一个二维码扫码能识别出url，过段时间就不行了。是为什么呢？。这个二维码包含的内容是联网获取的？

**Comment by srowen** [comment]
(I translated your message, but if you're able, English would be better.)
The app does nothing to the text you give it except encode it. You didn't give details about the problem, but it sounds like something else goes wrong after following your link. For example if you link to a site and then the site has an error or doesn't exist, of course, it won't work, but the app itself has nothing to do with it.
