### ISSUE TITLE
core 3.4.0 , the QR code is recognized successfully but report such an error

### ISSUE THREAD

**Issue by 1015156849** [zxing/zxing#1229]
**Error :**
No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

**System:**
Android 6.0

**Class Name :**
` com.google.zxing.qrcode.detector.FinderPatternFinder`

**Method Name:**
`selectBestPatterns`

Please Replace 
           `possibleCenters.sort(moduleComparator);`
to
           `Collections.sort(possibleCenters,moduleComparator);`

**Comment by srowen** [comment]
3.4 needs Java 8. You are using Java 7. Use the last 3.3.x version instead.
