### ISSUE TITLE
Change the scan to portrait. The preview is stretched

### ISSUE THREAD

**Issue by lxfwelldone** [zxing/zxing#1230]
In your demo，Here are the changes I made！
After you run the app, the content is stretched.
There are other places that need to be modified？
Thank you very much ！
1、android:screenOrientation="portrait"

2、the method "getFramingRectInPreview" in CameraManager.java 
//      rect.left = rect.left * cameraResolution.x / screenResolution.x;
//      rect.right = rect.right * cameraResolution.x / screenResolution.x;
//      rect.top = rect.top * cameraResolution.y / screenResolution.y;
//      rect.bottom = rect.bottom * cameraResolution.y / screenResolution.y;
      rect.left = rect.left * cameraResolution.y / screenResolution.x;
      rect.right = rect.right * cameraResolution.y / screenResolution.x;
      rect.top = rect.top * cameraResolution.x / screenResolution.y;
      rect.bottom = rect.bottom * cameraResolution.x / screenResolution.y;

3、the method “decode” in DecodeHandler.java 

    byte[] rotatedData = new byte[data.length];
    for (int y = 0; y < height; y++) {
      for (int x = 0; x < width; x++)
        rotatedData[x * height + height - y - 1] = data[x + y * width];
    }
    int tmp = width; // Here we are swapping, that's the difference to #11
    width = height;
    height = tmp;

    data = rotatedData;

**Comment by lxfwelldone** [comment]
i got it

**Comment by zhangchaojiong** [comment]
@lxfwelldone  how to  solve it ?

**Comment by zhangchaojiong** [comment]
I CERATE A CenterCropSurfaceView like that: 
call ```CenterCropSurfaceView.setPreViewSize(bestPreviewSize)```,  after  ``` cameraManager.openDriver(surfaceHolder);```

the ```bestPreviewSize``` value in ```CameraConfigurationManager.class``` that you need to change to public

```
public class CenterCropSurfaceView extends SurfaceView {
    private double retY = 0f;
    private double retX = 0f;
    private double translationX = 0f;
    private double translationY = 0f;

    public CenterCropSurfaceView(Context context) {
        super(context);
    }

    public CenterCropSurfaceView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public CenterCropSurfaceView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    public CenterCropSurfaceView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }
    
    public void setPreViewSize(Point point) {
        if (point == null || point.x <= 0 || point.y <= 0) return;

        double cameraAspectRatio;
        if (point.x < point.y) {
            cameraAspectRatio = (double) point.y / (double) point.x;
        } else {
            cameraAspectRatio = (double) point.x / (double) point.y;
        }

        //当前 surfaceView 的宽高
        int curX = getMeasuredWidth();
        int curY = getMeasuredHeight();

        if (curX < curY) {
            double curAspectRatio = curY / (double) curX;
            if (cameraAspectRatio > curAspectRatio) {
                //需要拉大curY
                retY = cameraAspectRatio * curX;
                translationY = (retY - curY) / 2;
            } else {
                //需要拉大curX
                retX = curY / cameraAspectRatio;
                translationX = (retX - curX) / 2;
            }
        } else {
            double curAspectRatio = curX / (double) curY;
            if (cameraAspectRatio > curAspectRatio) {
                //需要拉大curX
                retX = curY * cameraAspectRatio;
                translationX = (retX - curX) / 2;
            } else {
                //需要拉大curY
                retY = curX / cameraAspectRatio;
                translationY = (retY - curY) / 2;
            }
        }
        requestLayout();
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        if (retX > 0 && retY > 0) {
            setMeasuredDimension((int) retX, (int) retY);
        } else {
            super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        }
    }

    @Override
    public void layout(int l, int t, int r, int b) {
        l = l - (int) translationX;
        t = t - (int) translationY;
        r = r + (int) translationX;
        b = b + (int) translationY;
        super.layout(l, t, r, b);
    }
}
```
