### ISSUE TITLE
android version compatible：ArrayList#sort()

### ISSUE THREAD

**Issue by zhtoo** [zxing/zxing#1232]
ArrayList#sort() is used at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616) .but ArrayList#sort() was added in API level 24 and runtimes below API level 24 don't have that method. when the device below API level 24 will throw NoSuchMethodError.

Set a flag here to remind Android developers to pay attention to this problem when using com.google.zxing:core:3.4.0 

Solution：1、using com.google.zxing:core:3.3.0;
2、import  core  and Modify _possibleCenters.sort(moduleComparator);_  to  _Collections.sort(possibleCenters, moduleComparator);_

**Comment by srowen** [comment]
This is already covered many times, and isn't a place to add notes.
