### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by IfeanyiEkperi** [zxing/zxing#1234]
I'll love to contribute to this project by offering a logo redesign for the project that meets all required standard while still following same theme of the already in use logo.

Logos have no minimalistic and this project deserves something minimal and sleek too.

Hope to be given the chance to rebrand this project.

Yours in service.
Ifeanyi Ekperi

**Comment by srowen** [comment]
Thank you but I think the logo is fine and recognizable now after 10 years or so. This is in maintenance mode anyway.
