### ISSUE TITLE
java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

### ISSUE THREAD

**Issue by wukongGit** [zxing/zxing#1235]
java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
11-21 20:37:38.500 26202-26304/net.lubanstudio.android.in W/System.err:     at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
11-21 20:37:38.500 26202-26304/net.lubanstudio.android.in W/System.err:     at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
11-21 20:37:38.500 26202-26304/net.lubanstudio.android.in W/System.err:     at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
11-21 20:37:38.500 26202-26304/net.lubanstudio.android.in W/System.err:     at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
11-21 20:37:38.500 26202-26304/net.lubanstudio.android.in W/System.err:     at net.lubanstudio.android.mvp.main.MainPresenter.scanningImage(MainPresenter.java:387)
11-21 20:37:38.500 26202-26304/net.lubanstudio.android.in W/System.err:     at net.lubanstudio.android.mvp.main.MainPresenter$4.run(MainPresenter.java:322)
11-21 20:37:38.500 26202-26304/net.lubanstudio.android.in W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-21 20:37:38.500 26202-26304/net.lubanstudio.android.in W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-21 20:37:38.500 26202-26304/net.lubanstudio.android.in W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by srowen** [comment]
Answered many times already. Please search first.
