### ISSUE TITLE
Dual QR code scan results are not consistent 

### ISSUE THREAD

**Issue by calsoftgaurav** [zxing/zxing#1236]
Hi Team,
I'm trying to Scan dual QR code /Data Matrix through zxing. But the Intent data to onActivityResult() is in contestant . As i understand( please correct if wrong) , zxing scanner capture image once, any QR/DM is detected and passed Intent data to decode by parseActivityResult(). But  the result may not found all QR/DM ( if nor clear) that was in focus. 
**What i want?**
I want to write a validation, the zxing scanner will capture image **only if** two QRs/DMs are detected before converting to Intent data for  onActivityResult() .

Below are my code:
Issue line in code:
//>>>>>>>>>>>>>>>>>>>  length should be TWO in my case
//>>>>>>>>>>issue is results are not consistent some time I get 1 or 2  
=======================
import com.google.zxing.Result;
import com.google.zxing.ResultPoint;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.multi.GenericMultipleBarcodeReader;
import com.google.zxing.multi.MultipleBarcodeReader;
import com.google.zxing.multi.qrcode.QRCodeMultiReader;

public class MainActivity extends AppCompatActivity {

    private Button buttonScan;

    //qr code scanner object
    private IntentIntegrator qrScan;
	
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        requestCameraPermission();

        buttonScan = (Button) findViewById(R.id.buttonScan);

        CameraSettings settings = new CameraSettings();
        settings.setAutoFocusEnabled(false);
        settings.setScanInverted(true);

        //attaching onclick listenerprojectionAvcivity
        buttonScan.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

        qrScan = new IntentIntegrator(MainActivity.this);
        qrScan.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);

        qrScan.setPrompt(" Dual Scanner  ");
        qrScan.setOrientationLocked(true);
        qrScan.setBarcodeImageEnabled(true);
        qrScan.setBeepEnabled(true);

        qrScan.initiateScan();    // Scanner initiated         

            }
        });

    }

    //Getting the scan results
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        IntentResult result = qrScan.parseActivityResult(requestCode, resultCode, data);
		int[] data2 = new int[bMap.getWidth() * bMap.getHeight()];
        bMap.getPixels(data2, 0, bMap.getWidth(), 0, 0, bMap.getWidth(), bMap.getHeight());
        RGBLuminanceSource rgbLuminanceSource = new RGBLuminanceSource(bMap.getWidth(), bMap.getHeight(), data2);

        LuminanceSource source = rgbLuminanceSource;
        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
        Hashtable<DecodeHintType, Object> hints = new Hashtable<DecodeHintType, Object>();
        hints.put(DecodeHintType.TRY_HARDER, true);

            if(imageType.equals("QR_CODE")) {
                QRCodeMultiReader qrCodedetector =new QRCodeMultiReader();
                Result[] qrResult = qrCodedetector.decodeMultiple(bitmap, hints);

                    System.out.println(" QR Scanned Result: ::::: " + qrResult.toString());
                    System.out.println(" Number of QR detected ::::::::::" + qrResult.length); //>>>>>>>>>>>>>>>>>>>  length should be TWO in my case
					//>>>>>>>>>>issue is results are not consistent some time I get 1 or 2  or some time none ( Say 2 QRs in scanner view)

            }
            if(imageType.equals("DATA_MATRIX")) {
                MultiFormatReader tmpBarcodeReader = new MultiFormatReader();
                MultipleBarcodeReader bcReader = new GenericMultipleBarcodeReader(tmpBarcodeReader);
                Result[] dmResult  = bcReader.decodeMultiple(bitmap,hints);
                // setting results.

                    System.out.println(" DM Scanned Result: ::::: " + dmResult.toString());
                    System.out.println(" Number of DM detected ::::::::::" + dmResult.length);  //>>>>>>>>>>>>>>>>>>>  length should be TWO in my case
					//>>>>>>>>>>issue is results are not consistent some time I get 1 or 2  or some time none ( Say 2 QRs in scanner view)
            }

}

**Comment by mgouker** [comment]
Is it possible the qr codes have matching data? I'm not sure about the java code, but the objective-c library definitely eliminates duplicates.

**Comment by calsoftgaurav** [comment]
> Is it possible the qr codes have matching data? I'm not sure about the java code, but the objective-c library definitely eliminates duplicates.

This is not about matching/duplicate data. More about how zxing detect vs decode multi QR codes ?

**Comment by srowen** [comment]
MultipleBarcodeReader tries to find multiple barcodes, but isn't guaranteed to find them all. This isn't a bug per se.

**Comment by calsoftgaurav** [comment]
> MultipleBarcodeReader tries to find multiple barcodes, but isn't guaranteed to find them all. This isn't a bug per se.

Hi srowen,
Is there any code in  zxing scanner OR  method to override , where i can instruct scanner to capture image only if two QRs/DMs  detected  by zxing scanner? 
thanks in advance.
