### ISSUE TITLE
The library scanned the incorrect barcode results when scan the product type as UPC-E

### ISSUE THREAD

**Issue by mahendran92** [zxing/zxing#1242]
The actual barcode is 04963406 - Type UPC E. 

In rare case, it gives the incorrect result as 04904144 (or) 11904102 (UPC - E)

![serwerqwerqwerqwer](https://user-images.githubusercontent.com/13418532/70436409-38a29700-1aaf-11ea-9d71-7aebc9b09ad2.jpg)

Is there any chance to validate these incorrect scanned results?

Thanks

**Comment by srowen** [comment]
As ever:
- Please see the text you deleted to open this PR
- Only scan for the format you want if it's a problem. This is just a phantom misread of a UPC code
