### ISSUE TITLE
Veracode Issue DecodeHintManager.java

### ISSUE THREAD

**Issue by robimoltewhp** [zxing/zxing#1243]
Hello,

I am using Veracode Tool for code static analysis
https://www.veracode.com
and I am facing one security issue on your component

The issue says:

DecodeHintManager.java: 227

Description: This call to android.util.Log.w() could result in a log forging attack. Writing untrusted data into a log file allows an attacker to forge log entries or inject malicious content into log files. Corrupted log files can be used to cover an attacker's tracks or as a delivery mechanism for an attack on a log viewing or processing utility. For example, if a web administrator uses a browser-based utility to review logs, a cross-site scripting attack might be possible. The second argument to w() contains tainted data. The tainted data originated from an earlier call to com.journeyapps.barcodescanner.CaptureActivity.getIntent.
Remediation: Avoid directly embedding user input in log files when possible. Sanitize untrusted data used to construct log entries by using a safe logging mechanism such as the OWASP ESAPI Logger, which will automatically remove unexpected carriage returns and line feeds and can be configured to use HTML entity encoding for non-alphanumeric data. Alternatively, some of the XSS escaping functions from the OWASP Java Encoder project will also sanitize CRLF sequences. Only write custom blacklisting code when absolutely necessary. Always validate untrusted input to ensure that it conforms to the expected format, using centralized data validation routines when possible.

**Comment by srowen** [comment]
This warning is spurious because the log message contains no external input at all. You can ignore it.
