### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by Sathishdisys** [zxing/zxing#1247]
### Issue Description
The program can potentially fail to release a system resource
Resource leaks have at least two common causes:
- Error conditions and other exceptional circumstances.
- Confusion over which part of the program is responsible for releasing the resource.

### Recommendation 
. Never rely on finalize() to reclaim resources. In order for an object's finalize() method to be invoked, the garbage collector must determine that the object is eligible for garbage collection. Because the garbage collector is not required to run unless the JVM is low on memory, there is no guarantee that an object's finalize() method will be invoked in an expedient fashion. When the garbage collector finally does run, it may cause a large number of resources to be reclaimed in a short period of time, which can lead to "bursty" performance and lower overall system throughput. This effect becomes more pronounced as the load on the system increases.

### Issue File

 iskan-android​ /zxing-android-embedded​/build​ /intermediates​/intermediate-jars​ /debug​/classes​.jar​/com​ /journeyapps​/barcodescanner​ /CaptureManager​.java:360

**Comment by srowen** [comment]
You are reporting this against code in a different project. Also, generic static analysis results aren't helpful.
