### ISSUE TITLE
Digits are read out of order on ITF Barcode with 44 digits

### ISSUE THREAD

**Issue by rinaldosilva** [zxing/zxing#1250]
![Imagem](https://user-images.githubusercontent.com/7175358/72005571-a962dd80-322c-11ea-8999-4ce440cc46ba.jpg)

When I scan this barcode zxing brings the following code:
23798811900000091982373160002441859800075630
but the correct I think should be:
23792373126000244185998000756308881190000009198
as shown in the image above.
How can I solve this issue?

**Comment by srowen** [comment]
If you're correct, I think it's a simple misread. That's probably an ITF barcode which doesn't have a checksum. There's not much you can do except perhaps apply business logic to reject obviously wrong reads and try again with a slightly modified image or something

**Comment by rinaldosilva** [comment]
Thanks man! you are correct about this, I will apply ckeckmum.
