### ISSUE TITLE
WifiResultParser overloads H: for "hidden", "phase 2 method"

### ISSUE THREAD

**Issue by srowen** [zxing/zxing#1254]
(Reported by Albert Sanz via email.)

In https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/client/result/WifiResultParser.java#L60 , we see that `H:` is used as the prefix for 'hidden', but, also used for 'phase 2 method'. This can't be right.

This was ultimately because of my own error in reviewing a change 2 years ago:
https://github.com/zxing/zxing/pull/865#discussion_r147551490

Instead I think we can use the originally proposed `PH2:` for phase 2 method.

In order to try to retain compatibility, the code can interpret `H:` as 'hidden' if it is 'true' or 'false', or if `PH2:` was set separately. Otherwise, interpret it as phase 2 method. This shouldn't break any existing usage.

**Comment by srowen** [comment]
Resolved in https://github.com/zxing/zxing/commit/2e2b5ba757b6cbc2fdeaaa0ed6dcdd794abb5b2e

**Comment by TheZ3ro** [comment]
This changes aren't available in the last version of the "Barcode Scanner"/ZXing app on the PlayStore.
Latest release is from Sept 9, 2018.

It would be nice to upload a recent version of the app with this feature.
Thanks

**Comment by srowen** [comment]
I'm not allowed to update the app on Play anymore (API target is too old) but I can produce a new version of the .apk and upload it here, for side-loading.

**Comment by gurkburk76** [comment]
> I'm not allowed to update the app on Play anymore (API target is too old) but I can produce a new version of the .apk and upload it here, for side-loading.

That would be nice, will it work with android 12? :)
