### ISSUE TITLE
IsBlank return true if user tap on signature pad.

### ISSUE THREAD

**Issue by ErBhautik** [zxing/zxing#1255]
Is there any way to validate the signature for the minimum size. If the user taps on signature pad IsBlank set to true even for single dot.

I have tried to validate signature based on Image size(byte[] length) but it is very on a different devices.

**Comment by srowen** [comment]
Wrong project? Does not sound like anything from code here.

**Comment by ErBhautik** [comment]
I think IsBlank property is available in zxing package
