### ISSUE TITLE
How to use IntentIntegrator to get a proper IntentResult? [question]

### ISSUE THREAD

**Issue by c0dd3vi11** [zxing/zxing#1259]
I have loaded application from https://f-droid.org/en/packages/com.google.zxing.client.android/ and now is trying to write an app to use "Barcode Scanner". I added code to Main Activity:

```
private fun doScan() {
    integrator = IntentIntegrator(this)
    dialog = integrator?.initiateScan()
}
```

Also I added `onActivityResult`:
```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    super.onActivityResult(requestCode, resultCode, data)

    val scanResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, intent)
    if (scanResult != null) {
        AlertDialog.Builder(this).setMessage("Result: [$scanResult]").show()
    }
}
```

But all fields in `scanResult` contain "zeros". What I did wrong? Or something is wrong with the build on f-droid?
```
Format: null
Contents: null
Raw bytes: (0 bytes)
Orientation: null
EC level: null
```

p.s. I also tried to build the app from a source code to discover the problem by myself but failed (#1257).

**Comment by srowen** [comment]
Don't know, this should be all you need to know:
https://github.com/zxing/zxing/blob/master/android-integration/src/main/java/com/google/zxing/integration/android/IntentIntegrator.java

Are you sure it called the Barcode Scanner app and not something else? did you get a successful scan?

**Comment by c0dd3vi11** [comment]
Yes, after I call `integrator?.initiateScan()` it goes to f-droid's app, makes a recognition and goes back:
![photo_2020-01-31 21 38 12](https://user-images.githubusercontent.com/60510579/73565228-2838e800-4472-11ea-8b9f-2bb07825c08b.jpeg)

**Comment by srowen** [comment]
I don't think it's an issue necessarily, but anything from f-droid is unofficial.
This works fine for me with the latest version. Download "ZXing Test" and use it to invoke a scan by intent.

**Comment by c0dd3vi11** [comment]
Okay, I got it.

Could you describe what means "ZXing Test"? I don't see it in https://github.com/zxing/zxing/releases section.

**Comment by srowen** [comment]
Search in the Play Store, it's easier.

**Comment by c0dd3vi11** [comment]
Roger that ;)

**Comment by c0dd3vi11** [comment]
Incredable! Did "ZXing Test" use the same method to open "Barcode Scanner" as I'm trying to use?

p.s. It works well!

**Comment by srowen** [comment]
Yes. It's not published anymore but this was the last version: https://github.com/zxing/zxing/blob/zxing-3.3.0/androidtest/src/com/google/zxing/client/androidtest/ZXingTestActivity.java

**Comment by c0dd3vi11** [comment]
Thank you a lot! I try to figure up what happened...

**Comment by c0dd3vi11** [comment]
I found the a bug! >_<

I copied the code from https://zxing.github.io/zxing/apidocs/com/google/zxing/integration/android/IntentIntegrator.html, but there was an example written in Java. After I made a copy in Kotlin Android Studios' snippet for `onActivityResult` I didn't notice that instead of intent they use varname `data`! You can see my mistake in the first message in the second code example.

So! Now everything work like a charm! ^_^ Than you for giving me advices, @srowen !

**Comment by henry-leu** [comment]
How do I use the IntentIntegrator class for non-android? I'm using it in my Java class for testing purpose. Not on Android.

**Comment by srowen** [comment]
It is for Android, would not help outside of Android
