### ISSUE TITLE
Support for WPA-Enterprise?

### ISSUE THREAD

**Issue by ISharkI** [zxing/zxing#126]
Hello

We just stumbled upon the problem that we want to grand our members (4k+) access to our distributed wifi network which uses 802.1X for authentication.
Currently the scanner supports only "open","WEP", "WPA" and "WPA2".

According to my current understanding of the code (if I missed something please tell me) there are only the files 

core/src/main/java/com/google/zxing/client/result/WifiResultParser.java
core/src/main/java/com/google/zxing/client/result/WifiParsedResult.java

which generate the config and is parsed to the Android manager later. According to the Android documentation the WifiConfiguration accepts "public WifiEnterpriseConfig enterpriseConfig" with all neccessary sub-options like "public int getPhase2Method ()" etc. However testing in our network (with it's current configuration) using an QR-Code was not successful. 

Am I wrong? If yes I would like to know where my mistake is.
If you need further information in order to reproduce the issue don't hesitate to contact me.

Greetings
Michael

**Comment by denysvitali** [comment]
Sorry for the necro-bump, but it looks like 802.11x is still not supported. Is there any plan to do it?

**Comment by srowen** [comment]
I'd be OK with requiring Android 4.3+ at this point. So if you want to revive this and propose a PR @denysvitali I'd look at it.
