### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by emtammaru** [zxing/zxing#1262]
After running some endurance tests against an endpoint to decode pdf417 barcode images, I found a small but steady memory leak.  I created a very simple cli application which demonstrates and reproduces the memory leak here: https://github.com/emtammaru/zxing-issue.  

Note, I have not done a deep investigation into where the memory leak is coming from exactly, but I am using a `BufferedImageLuminanceSource` with a `HybridBinarizer` to decode images with the `PDF417Reader`.  I looked and did not find any other open issues regarding memory leaks, so I am posting this for visibility.  

Just to negate link rot, here is the code from the sample application that reproduces the memory leak:

Using zxing core and javase version 3.4.0

```
package main;

import org.joda.time.LocalTime;

import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.io.IOException;

import javax.imageio.ImageIO;

import com.google.zxing.BinaryBitmap;
import com.google.zxing.ChecksumException;
import com.google.zxing.FormatException;
import com.google.zxing.LuminanceSource;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.pdf417.PDF417Reader;

import java.io.BufferedInputStream;
import java.io.FileInputStream;

public class Main {
	public static void main(String[] args) throws IOException, NotFoundException, FormatException, ChecksumException {
		LocalTime currentTime = new LocalTime();
		System.out.println("The current local time is: " + currentTime);
		PDF417Reader reader = new PDF417Reader();
		while (true) {
			try (InputStream barCodeInputStream = new BufferedInputStream(new FileInputStream("./barcode.gif"))) {
				BufferedImage barCodeBufferedImage = ImageIO.read(barCodeInputStream);
				LuminanceSource source = new BufferedImageLuminanceSource(barCodeBufferedImage);
				BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

				Result result = reader.decode(bitmap);
				// System.out.println(result.getText());
			}
		}
	}
}
```

**Comment by srowen** [comment]
Two possibilities:

It's not a memory leak :) What are you seeing that suggests it? just wondering about the methodology. It's normal for the heap to grow a bit, but wouldn't expect much long-term growth from this if you are (for example) triggering GC and then evaluating.

It's a memory leak in native code that ImageIO uses. In the online app at zxing.org I've seen _some_ memory leak that causes it to run out of memory after a month or so. From heap dumps it seemed like off-heap memory must be the issue, like, the heap had plenty of room so no GC happened, but those objects held on to significant off-heap memory and it ran the process out of memory. I stuck in some regular System.gc() calls and it seemed OK, so maybe the theory is right.

You might test by having it call System.gc() every 10000 iterations or something and see if that changes things.

**Comment by srowen** [comment]
For more context, you can see some stuff I added over time trying to really ensure the image resources were totally freed:

https://github.com/zxing/zxing/blob/master/zxingorg/src/main/java/com/google/zxing/web/DecodeServlet.java#L220
https://github.com/zxing/zxing/blob/master/zxingorg/src/main/java/com/google/zxing/web/DecodeServlet.java#L153

I don't think it's a leak in the core library here, so not sure what can be done here. It simply doesn't hold on to much of any state itself.

**Comment by emtammaru** [comment]
Thanks for the quick reply @srowen.  I am going to run some more tests today with System.gc() calls and look at reconfiguring the heap size settings to see if this might be a symptom of the garbage collector after all.  

Question though regarding the second possibility:


> It's a memory leak in native code that ImageIO uses. In the online app at zxing.org I've seen some memory leak that causes it to run out of memory after a month or so. From heap dumps it seemed like off-heap memory must be the issue, like, the heap had plenty of room so no GC happened, but those objects held on to significant off-heap memory and it ran the process out of memory. I stuck in some regular System.gc() calls and it seemed OK, so maybe the theory is right.

This sounds very similar to what I was originally seeing during my endurance testing -- i.e. the memory would grow very slowly but steadily, and over about a week's time the memory would approach 500 MB.  However, the max heap size setting is 2 GB, so maybe the garbage collector just never even ran in that 1 week timespan?  

Also, when you say it seemed OK after adding some System.gc() calls, can you be more specific?  Does the memory follow a normal-ish sinusoidal pattern where it grows slowly over time and falls back down after the programmatic System.gc() calls?  

Thanks again for your thoughtful responses, really appreciate it.

**Comment by srowen** [comment]
See the second source link above - I just had it run gc() a couple times an hour (not expensive at all in that case). Hacky but seemed to help. You could do it much less frequently. 

I didn't track the memory usage over time but recall it just stayed pretty flat, but then again, memory allocation is minimal to begin with in that app. It's just handling a few QPS.

The other source link, using BufferedImage.flush(), might have helped too. I forget.

**Comment by emtammaru** [comment]
After further review and memory profiling, it appears the issue I'm seeing is actually an issue with docker & openjdk, not zxing.  See here: https://github.com/moby/moby/issues/15020

**Comment by srowen** [comment]
Maybe, I mean, the JVM process may well use more memory than the heap size because of off-heap allocation (not so much here but in general). Certainly in earlier versions of Java a lot of class metadata was off heap. Native buffers for I/O, etc don't count. I also know that the JVM won't shrink its OS memory usage even after GC unless you let it with Xms < Xmx. Even then I think it's kind of stingy about doing so. This might be of interest: http://openjdk.java.net/jeps/351
