### ISSUE TITLE
Bug with last version

### ISSUE THREAD

**Issue by pb402385** [zxing/zxing#1267]
I encountered un bug with last version on IOS iPhone,

unable to instantiate new ZXing.BrowserBarcodeReader();

So i change my code from:
<script type="text/javascript" src="https://unpkg.com/@zxing/library@latest"></script>
to:
<script type="text/javascript" src="https://unpkg.com/@zxing/library@0.15.0/umd/index.min.js"></script>

and everything is OK now, i put a message for you to know there is potentially problems with last version on IOS iPhone

Best regards.

**Comment by srowen** [comment]
That code isn't part of this project.
