### ISSUE TITLE
Unable to scan code 39 Barcode.

### ISSUE THREAD

**Issue by smoro88** [zxing/zxing#1268]
I updated the solution like mentioned to V3 PreReleese to validate and it still cannot scan this image attached.

![barcode (3)](https://user-images.githubusercontent.com/29660459/76673108-9e079780-6578-11ea-8eda-1734e5fe034f.gif)

**Comment by smoro88** [comment]
Has this been closed because a fix has been applied to the trunck?

**Comment by srowen** [comment]
No. Read the text you deleted to even open this issue.
