### ISSUE TITLE
Standard Code39 barcode not recognized

### ISSUE THREAD

**Issue by kellywahl** [zxing/zxing#1270]
![46923fde-86e7-4c50-bdac-d98e2a44e739](https://user-images.githubusercontent.com/7792895/77570265-63c8bf00-6ec3-11ea-9c4d-4f61729464c2.jpg)

Please help me understand why this barcode doesn't scan in either the API or your online test (https://zxing.org/w/decode.jspx) . I have tried scanning it with a handheld scanner and it appears ok

**Comment by srowen** [comment]
Hard to say; it's usually the slight distortion from aliasing the very narrow bars here that throws it off.
