### ISSUE TITLE
Code128 image width

### ISSUE THREAD

**Issue by kinguru** [zxing/zxing#1273]
I need to create a code128 with max-width restriction, as I need it then to be printed in 2" paper.
How I could achieve it?
My code is:

var barcodeWriter = new BarcodeWriter
            {
                Format = BarcodeFormat.CODE_128,
                Options = new Code128EncodingOptions { Width = width, Height = height, PureBarcode = true, Margin = 0 }
            };
            var result = barcodeWriter.Write(Guid.Newid());

**Comment by srowen** [comment]
There isn't a way to restrict its max size. It will render as an image that's as small as possible and still fits the bars (i.e. single-width bars are one pixel). You can simply scale the image however you like when you print or render it onto another image.

**Comment by kinguru** [comment]
Thank you
