### ISSUE TITLE
QR code unexpected marins

### ISSUE THREAD

**Issue by kinguru** [zxing/zxing#1274]
Hi, I'm creating a simple QR code from GUID
The code is:
var barcodeWriter = new BarcodeWriter();
barcodeWriter.Format = BarcodeFormat.QR_CODE;
barcodeWriter.Options = new QrCodeEncodingOptions { Width = size.Width, Height = size.Height, PureBarcode = true, Margin = 0 };
var result = barcodeWriter.Write(jobGUID.ToString());

In case QR code size > 86px it generates withour maring. If 86 or less it adds 10-12 pixels margins.
I'm confused trying to position generated QR code :) Why it adds margin if i set margin=0?

**Comment by srowen** [comment]
That looks like code from another library.
But margin is required to generate a valid QR code. I think you are talking about the quiet zone. I doubt you can suppress that in the other library; not this one.

**Comment by kinguru** [comment]
you catch me :) it is from zxing.net,
but i believe it was ported from zxing java :)

**Comment by duronggang** [comment]
https://blog.csdn.net/ruanjiandu/article/details/109243323
