### ISSUE TITLE
ISO 8859-1: 7F is not defined

### ISSUE THREAD

**Issue by SebastianGoebel** [zxing/zxing#1279]
Hi, I have a short question. 

At this point: 
https://github.com/zxing/zxing/blob/54d0a37832b51e15b257f7363bc1bf9725b07445/core/src/main/java/com/google/zxing/common/StringUtils.java#L118

is checked whether it is not ISO88591. According to Wikipedia, 7F is not part of ISO88591:
https://en.wikipedia.org/wiki/ISO/IEC_8859-1

Doesn't the condition have to be: if (value >= 0x7F && value <0xA0)?

**Comment by srowen** [comment]
I agree, though it looks like this char is sometimes interpreted as DEL. It will still be parseable as ISO-8859-1 in the JVM with this code point (looks like it's ignored). The purpose here is really to roughly distinguish UTF8, Shift_JIS, etc. 

Does this difference cause a problem in the wild?

**Comment by SebastianGoebel** [comment]
Thank you for your prompt reply!

> Does this difference cause a problem in the wild?

No, I just noticed it by accident and I was wondering whether it has deeper meaning (ANSI confusion etc.).

**Comment by srowen** [comment]
It may be better changed, but all else equal I think I'd leave the long-standing behavior as-is. (A "normal" QR code wouldn't be encoding 7f anyway). Anyone can comment/reopen if there's a reason to believe that's not true.
