### ISSUE TITLE
Bug Report; XAMARIN Shell.Android: Scanner does not scan if navigated to without main thread.

### ISSUE THREAD

**Issue by Dr-Primary** [zxing/zxing#1287]
Recreation:
I have a button that activates the following code:

private async void importButton_Clicked(object sender, EventArgs e)
        {
            var method = await Shell.Current.DisplayActionSheet("Import Method Selection", "Cancel", null, new string[2] { "QR Code", "Browse Files" });
            if(method.Equals("QR Code"))
            {
                await Shell.Current.GoToAsync("scannerPage"); 
            }

My scanner page content looks like this:

    <ContentPage.Content>
        <Grid VerticalOptions="FillAndExpand"
              HorizontalOptions="FillAndExpand">
            <zxing:ZXingScannerView x:Name="scanView"
                                        OnScanResult="scanView_OnScanResult"
                                        IsScanning="True"
                                        VerticalOptions="FillAndExpand"
                                        HorizontalOptions="FillAndExpand"/>
            <zxing:ZXingDefaultOverlay TopText="Align the barcode within the frame"/>
        </Grid>
    </ContentPage.Content>

It seems like if there is any kind of awaited code before the navigation the scanner will not register any QR codes.
Right now if I change the navigation line to this:

Device.BeginInvokeOnMainThread(async() => await Shell.Current.GoToAsync("scannerPage"));

the scanner will work just fine.  Maybe this is a shell issue but I figured I'd post here in case someone runs into the same problem.

**Comment by srowen** [comment]
Wrong project.
