### ISSUE TITLE
Request to update wiki "Barcode Contents"

### ISSUE THREAD

**Issue by Kxuan** [zxing/zxing#1288]
Please update the wiki [Barcode Contents](https://github.com/zxing/zxing/wiki/Barcode-Contents).

There is too many difference between the current code and the documentation.

The [Wi-Fi Network config (Android, iOS 11+)](https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11) only shows T, S, P, H.

But the code recognizes other parameters like PH2. And the "H" has the different definition in the code.

**Comment by srowen** [comment]
Can you open a PR with the changes? or paste the ones you'd suggest here?

**Comment by srowen** [comment]
OK while I was at it, I updated for the new WPA2-EAP fields
