### ISSUE TITLE
Wifi network config guidance is inconsistent on escaping

### ISSUE THREAD

**Issue by chris-morgan** [zxing/zxing#1292]
https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11:

> Special characters `\`, `;`, `,` and `:` should be escaped with a backslash (`\`) as in MECARD encoding. For example, if an SSID was literally `"foo;bar\baz"` (with double quotes part of the SSID name itself) then it would be encoded like: `WIFI:S:\"foo\;bar\\baz\";;`

`"` wasn’t in the list of things that need escaping, yet it is escaped in the example.

**Comment by srowen** [comment]
Yes I think quotes don't actually need to be escaped. I added a test case and it works without them. Double quote doesn't have special meaning in MECARD or here. I'll update.
