### ISSUE TITLE
Build issue Mac - maven install fails

### ISSUE THREAD

**Issue by saholmes** [zxing/zxing#1293]
Hi, 

Trying to build and followed instructions for maven build

Get error:  
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project core: MavenReportException: Error while generating Javadoc: 

Java SDK 8 is installed
Maven is latest version
Mac OS 10.15.5

**Comment by srowen** [comment]
There's no error reported here. I have the same setup and it builds fine.

**Comment by srowen** [comment]
Reopening because I can reproduce this on Travis if javadoc is enabled, for JDK 11+
https://travis-ci.org/github/zxing/zxing/jobs/695517286

**Comment by srowen** [comment]
Looks like `<source>` is needed to make it work on Java 11+, so I added that. It appears to work now.
