### ISSUE TITLE
QR code detection issue with non-ASCII characters

### ISSUE THREAD

**Issue by adeshpandey** [zxing/zxing#1297]
Does not detect correctly QR codes with non-ASCII characters. In my case it is pre-pending 2.5 bytes and appending 10.5 bytes.

**Comment by srowen** [comment]
Without any detail or example, can't help. QR codes do not formally support encoding like UTF-8 at all, actually. It can be guessed in some cases.

**Comment by adeshpandey** [comment]
Hi @srowen 
My QR Code is: https://imgur.com/AqUySJ8 and i have verified the detection as follows- https://imgur.com/a/NgnVDEi
You can see that expected has 2.5 bytes less in the beginning and 10.5 at the end

**Comment by srowen** [comment]
Yes, that's the result, but I am not clear what you are expecting to see and why.

**Comment by adeshpandey** [comment]
Since I have generated the QR code from my end and wanted to verify if it is detected successfully or not but I noticed that it's detected with some extra bytes and my system could not verify.

**Comment by srowen** [comment]
What bytes do you think are extra? the ec 11 bytes are padding required by a QR code.
how did you encode it?

**Comment by adeshpandey** [comment]
Hi @srowen 
In the end except e of first ec 11 all the extra and in the beginning 46 0 is extra
