### ISSUE TITLE
Design Issue While generating UPC-A barcode using Zxing.

### ISSUE THREAD

**Issue by katalsupriya** [zxing/zxing#1298]
I have created UPC-A barcode using Zxing in C#.
![image](https://user-images.githubusercontent.com/43651982/85999528-dcdb3380-ba29-11ea-9116-fbe26752dc92.png)

Here is the UPC-A barcode generated online
![image](https://user-images.githubusercontent.com/43651982/85999569-f11f3080-ba29-11ea-9e59-b53dd398ade3.png)

Why my Zxing UPC-A barcode footer layer is different?

**Comment by srowen** [comment]
The C# port is a different project, so I'm not sure if it's different, but this project doesn't generate the digits at all, just the barcode. Something else is adding digits.

**Comment by katalsupriya** [comment]
I did not get it

**Comment by micjahn** [comment]
Only the C# port of zxing (https://github.com/micjahn/ZXing.Net) generates a footer. The original java version doesn't. But the C# implementation is very simple. It doesn't divide the content into different parts.
