### ISSUE TITLE
The QRcode decode wrongly

### ISSUE THREAD

**Issue by syafiqahLiyana** [zxing/zxing#1302]
I'm using zxing version 3.3.0 but when I try using it they decode the wrong value

here the example:-
Actually value:-
282343535464646428

but after scan QRcode, the value became:-

**23435354646464**

Does anyone know why?

**Comment by srowen** [comment]
I don't know, you didn't provide a QR code.

**Comment by syafiqahLiyana** [comment]
Sorry forgot to share the qrcode 

The current value decode:- 
**68854127096888**

![image](https://user-images.githubusercontent.com/40551935/86991203-130a7700-c1d1-11ea-8a1c-16c6b639fcf9.png)
![qr1](https://user-images.githubusercontent.com/40551935/86991240-29b0ce00-c1d1-11ea-8c5e-ea88e194d2be.jpeg)

**Comment by srowen** [comment]
I lifted both barcodes, and they both scan as `286885412709688891` That has to be the right value. Where are you getting your expected value, and how did you scan for this? which barcode is it finding?

**Comment by syafiqahLiyana** [comment]
Oh, seems like the device driver might not compatible with the zxing. thanks for your helps
