### ISSUE TITLE
Veracode Found Security Flaws.

### ISSUE THREAD

**Issue by patelchetan79** [zxing/zxing#1303]
After creating the Android APK file, we scan the apk file in Veracode. Veracode found the below flaws in the code.

Improper Output Neutralization for Logs

com\google\zxing\client\android\encode\EncodeActivity.java Line 151, 159
com\google\zxing\client\android\HttpHelper.java Line 207
com\google\zxing\client\android\HelpActivity.java Line 43
com\google\zxing\client\android\encode\QRCodeEncoder.java Line 215

Thanks
Chetan

**Comment by srowen** [comment]
I don't think any of those are actually security issues, but it wouldn't hurt to remove the logging in QRCodeEncoder, EncodeActivity. It just doesn't do much. The others seem invalid.
Please check for false positives before reporting.

**Comment by srowen** [comment]
https://github.com/zxing/zxing/commit/07fdff4df7647e558c5e4c421b0b5bc05617df2d
