### ISSUE TITLE
QR ECC level bug

### ISSUE THREAD

**Issue by Martin12350** [zxing/zxing#1304]
Setting error correction level for QR code with function forBits has first bit reversed.
So with numbers (0, 1, 2, 3) instead (L, M, Q, H) is (M, L, H, Q).
Not big deal, but good to know.
```
BarcodeWriter writer = new BarcodeWriter();
writer.Options = new QrCodeEncodingOptions()
{
    Width = 100, 
    Height = 100, 
    ErrorCorrection = ErrorCorrectionLevel.forBits(codeQR.eccLevel)   //FIX: codeQR.eccLevel^1
};
writer.Format = BarcodeFormat.QR_CODE;
Bitmap QRcode = writer.Write(code);
```

**Comment by srowen** [comment]
(PS you are using a port of this project's code, not this project.)
No, the code is correct. L is 01, M is 00, Q is 11, H is 10. I checked the QR code spec again.
If that were wrong none of this would have worked for 10 years.

**Comment by Martin12350** [comment]
Would you mind send me URL of QR specification?
Because everywhere I see this:
![obrazek](https://user-images.githubusercontent.com/47942899/90684971-57297680-e269-11ea-8804-834d0b428608.png)

And if i got it correctly then L=00, etc. I also tried different generators with this result.
I apologize for the problems. And thanks for answer.

**Comment by srowen** [comment]
It's not publicly available (for pay from the standards org)
L is the lowest EC level, but it does not follow that it is encoded by 00. It is encoded by 01 for whatever reason.

**Comment by pzygielo** [comment]
@Martin12350 - note - per [wikipedia](https://en.wikipedia.org/wiki/QR_code#/media/File:QR_Character_Placement.svg): _dark is 0 on even rows and 1 on odd rows_ 

> And if i got it correctly then L=00,

So `L = [dark, dark]`<sup>`T`</sup> is not `00` I guess.

**Comment by srowen** [comment]
I believe that is indeed (part of) the special region where things like EC level are recorded. However, that picture is incorrect. The two EC level bits are not literally two modules you can read off. It's a sequence of bits plus a bunch of EC bits that are placed across a few locations in the QR code. Because of the EC (of the EC info itself, ironically), those bits you see aren't anything like the original.
