### ISSUE TITLE
Camera Scanning only once, does action then stops reading in Xamarin.Forms

### ISSUE THREAD

**Issue by israaydin** [zxing/zxing#1309]
Hello,

I've used ZXing in Xamarin.forms in my app which reads the Qr, and opens a browser and goes to the link, i followed the guideline and checked several people's implementations and my app is successfully reading the Qr and going to the site comes from Qr. the issue happens when i try to come back to the app ( via either pressing back or home and closing the browser) and read another Qr code, the app doesnt work. i m using the scanView.IsScanning=true after reading once. tried creating button and changing IsScanning, or working with OnResume function, nothing changed. only thing worked for me is, creating the main page over and over again when onResume called (which is basically reloading/relaunching the app from scratch). i m in need of some guidance. thanks in advance

ps: i m fairly new to app programing and i dont know if it is a bug or i m doing something wrong and missing some key points in my coding or train of thoughts. maybe i should try to restart ZXingScannerView or camera somehow but i dont know how to do/approach this.

these are the changes i ve made to the examples or guidelines the rest includes permissions and initializing in main activity

mainpage.xaml.cs
```
public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }
        public void scanView_OnScanResult(ZXing.Result result)
        {
            if (result.Text != null && result.Text.Contains("ramakbilisim"))
            {
                Browser.OpenAsync(result.Text, BrowserLaunchMode.SystemPreferred);
            }
        }
        protected override void OnAppearing()
        {
            base.OnAppearing();
            scanView.IsScanning = true;
        }
        protected override void OnDisappearing()
        {
            base.OnDisappearing();
            scanView.IsScanning = false;
        }
    }
```

mainpage.xaml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:zxing="clr-namespace:ZXing.Net.Mobile.Forms;assembly=ZXing.Net.Mobile.Forms"
             mc:Ignorable="d"
             x:Class="RamakDenemeQr.MainPage">

    <StackLayout Padding="0,0,0,10">
        <Frame BackgroundColor="#2196F3" Padding="24" CornerRadius="0">
            <Label Text="Ramak Deneme Qr" HorizontalTextAlignment="Center" TextColor="White" FontSize="36"/>
        </Frame>
        
        <zxing:ZXingScannerView
            x:Name="scanView"
            OnScanResult="scanView_OnScanResult"
            IsScanning="False"
            WidthRequest="300"
            HeightRequest="400"
            VerticalOptions="CenterAndExpand"
            HorizontalOptions="CenterAndExpand"
            />
    </StackLayout>
    
</ContentPage>

**Comment by srowen** [comment]
That's actually code from a different project, not this one.

**Comment by israaydin** [comment]
these codes are my implementations of ZXing on Xamarin.forms based on github guidelines and other sources. which in result i created an app that uses ZXing for Qr Reading. can you elaborate what you mean in your comment

**Comment by srowen** [comment]
The Xamarin-related port is not this project, it's a different one. The code you are using is not here.
