### ISSUE TITLE
The estimated position of Alignment Pattenrns Point is inaccurate

### ISSUE THREAD

**Issue by liupd1996** [zxing/zxing#1314]
Hello,
I encountered the absence of Alignment Pattenrns point, so I tried to create a new Point to replace it, but after debugging, I found that the predicted points were quite different from the actual ones, so the TWO-DIMENSIONAL code could not be identified,but I have seen that your calculation method should be correct, and I don't know what causes it. Could you please help me with this problem. Thank you very much!

--------
This code is located in Detector. Java
int estAlignmentX = (int) (topLeft.getX() + correctionToTopLeft * (bottomRightX - topLeft.getX()));
int estAlignmentY = (int) (topLeft.getY() + correctionToTopLeft * (bottomRightY - topLeft.getY()));

**Comment by srowen** [comment]
It's entirely possible it finds the wrong point, sure. That's just how it is.
Without any more detail, can't say more.

**Comment by liupd1996** [comment]
I found in the code that if you didn't find the correction point, you would replace it with the Position Detection Patterns point in the lower right corner, and then perform a perspective transform. From my understanding, a square will always be a parallelogram from any Angle, so I think the point you assumed in the lower right corner should be accurate, but it hasn't been decoded. I don't quite understand the reason why the decoding is not successful, is it because the image acquired by the camera is curved?Can you help me out? Thank you very much!

Could there be a better way to handle missing correctors?

**Comment by axxel** [comment]
> From my understanding, a square will always be a parallelogram from any Angle

That is not correct. It can also be a trapezoid.

> is it because the image acquired by the camera is curved?

Could you post a sample image?

> Could there be a better way to handle missing correctors?

I believe so and implemented one in my QRDetector rewrite in the (new) c++ port of this project: https://github.com/nu-book/zxing-cpp/commit/c401b48029464a5ee9bd0c7e4def69caddcbead0. I'd be curious if your input can be successfully detected by my new code.

**Comment by liupd1996** [comment]
Yep.A square may be irregular when viewed from different angles.

I uploaded two pictures, the first one I covered the correction symbol, which could not be recognized by Zxing Android,  the estimation point was incorrect, which led to the perspective transform problem, so it could not be recognized.
The second qr code is curved. 

Thank you for the project. I will try it.
![1111](https://user-images.githubusercontent.com/70434675/93305731-7e0ba600-f831-11ea-96be-241c73ecd19f.png)
![2222](https://user-images.githubusercontent.com/70434675/93305740-8237c380-f831-11ea-98ff-b3a11043f34e.png)

**Comment by liupd1996** [comment]
![33333333](https://user-images.githubusercontent.com/70434675/93307545-ad231700-f833-11ea-95c2-2ae8e234ac0f.png)

**Comment by axxel** [comment]
The first one works with my approach, the second one does not. Such a curved image would need a different approach in the GridSamper to have a chance of working at all.

**Comment by liupd1996** [comment]
Could you tell me how you implemented it? It is troublesome for Java to call c++ interface, and I'd like to implement it directly in Zxing Android if it's simple.Could you tell me a few key file locations in your project and I'll learn about them.
Thanks!

**Comment by axxel** [comment]
We actually have an android wrapper available but, yes, it is still cumbersome to get it to work on android. That said, it is way less work than to port my rewrite back to Java. If you still want to give it a go, the link above is what need to start looking into that.

Do you mind if I include your first sample in our black-box-testing set of images?

**Comment by liupd1996** [comment]
You are free to use it

**Comment by srowen** [comment]
They aren't even trapezoids :) Can be skewed by perspective. Or indeed on a curved surface even.

Curvature is not possible to detect just from finding alignment patterns, though a little won't break the detection.

The point of the alignment pattern is to detect perspective skew, so, yeah you need it. Otherwise it guesses based on the other points assuming no perspective distortion, as if there is only shear.

I'm sure there are more complex heuristics to try to find the barcode boundaries, like edge detection. They are often not worth it in the camera phone scanning use case because you always have a next image to try that's slightly different.

But, when do you not have an alignment point? it is required by the QR code spec, for all but the smallest possible barcode.

**Comment by axxel** [comment]
> They aren't even trapezoids :)

Some are, but yes, a whole range of convex quadruples are possible. By the way, the convex insight was what allowed me to get rid of the [exception catching based bounds checking](https://github.com/zxing/zxing/blob/6fe3a775a0759bdb8d0a4c5138594e46098c263a/core/src/main/java/com/google/zxing/common/DefaultGridSampler.java#L75-L82) in the `GridSampler` (see https://github.com/nu-book/zxing-cpp/commit/88d5c5952ed39f630013165b8f234d0ed5562b2e).

> Curvature is not possible to detect just from finding alignment patterns

Well if you had more than 1 alignment pattern (higher version number) you could in fact do something about curvature. (have not done that, yet).

> I'm sure there are more complex heuristics to try to find the barcode boundaries

What I ended up doing is fitting a line to the correct edge of the 1-module square part of the finder patterns and then intersect the lines from the bottom left and the top right finder pattern to estimate the position of the bottom right alignment pattern. That also works for skewed version 1 symbols that have no alignment pattern.

> But, when do you not have an alignment point? 

It could be corrupted like [here](https://github.com/zxing/zxing/blob/master/core/src/test/resources/blackbox/qrcode-2/25.png). But I would indeed be interested what the OPs use case for this is.

**Comment by liupd1996** [comment]
I am a little confused about your code. I am curious about how you get the edge of two finder patterns. I want to use the 8-neighborhood pixel method, could you please tell me your method.Thanks. @axxel

**Comment by axxel** [comment]
As I said: it is going to be work to port that back to Java. Regarding the algorithm itself: if you know enough about C++ and Java, you don't need to understand the algorithm at all. If you have a specific question I might have time to answer that but "please tell me your method" is nothing I'm willing to act on. Plus: I do believe your time is better spent on incorporating our Android wrapper. You'll get a substantial speed improvement and improvements to other decoders as well.
