### ISSUE TITLE
It's hard to scan a QR code when it fills the screen

### ISSUE THREAD

**Issue by liupd1996** [zxing/zxing#1315]
Hi:
This is the first time I've used the library, and I found a problem.When the QR code is full of the screen, it is difficult to scan the results, and it is quickly recognized when the distance is relatively long.Can you tell me the specific reasons? Is there any way to optimize it?
I really appreciate someone answering my question!

**Comment by srowen** [comment]
If you're using the mobile app, it's probably because it can't auto focus so close. It's also not scanning the whole screen, just the reticle, for this reason.

**Comment by liupd1996** [comment]
What you said should be right, I tried to enlarge the QR code, the lens is away, this time full of scan box it is available.
