### ISSUE TITLE
Rotated Data Matrix code can't be decode  How we decode Rotated Data Matrix code using pylibdmtx library?

### ISSUE THREAD

**Issue by fatana1** [zxing/zxing#1317]
Here  i Have decode image without rotation  i got the result successfully but when i rotated it there is not any result any one help me please 

import numpy as np
import cv2
from pylibdmtx import pylibdmtx

if __name__ == '__main__':

    image = cv2.imread('new.jpg', cv2.IMREAD_UNCHANGED);

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    ret,thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

    msg = pylibdmtx.decode(thresh)
    print(msg)

Result of running code

[Decoded(data=b'09903010917072337', rect=Rect(left=1, top=7, width=128, height=122))]

here is the Rotated image
<img width="133" alt="RoDm" src="https://user-images.githubusercontent.com/62222034/93839697-649aac00-fcc0-11ea-844c-3e545841f204.png">

**Comment by srowen** [comment]
This looks unrelated to the code in this project.
