### ISSUE TITLE
Reading cross scanned barcode

### ISSUE THREAD

**Issue by Antonino09** [zxing/zxing#1318]
![barcode](https://user-images.githubusercontent.com/44637836/94813978-0163f480-03f9-11eb-9939-f9d75bda6e4e.jpg)
I'm having some troubles in recognizing cross scanned barcode (45°) , so with misaligned barcodes the reader fails.
How can i solve this problem ?
Please help me.

**Comment by srowen** [comment]
That one seems to scan:
https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F44637836%2F94813978-0163f480-03f9-11eb-9939-f9d75bda6e4e.jpg

If it's rotated much more though, then no horizontal line passes through the whole barcode. 
You can try TRY_HARDER mode, as well as try various rotations of the image in your app if it fails to scan.
