### ISSUE TITLE
QR - WiFi (doubt)

### ISSUE THREAD

**Issue by Azogue99** [zxing/zxing#1319]
Hi, I'm trying to generate a QR with the WiFi configuration.

`WIFI:S:eduroam;T:WPA3-Enterprise;E:TTLS;PH2:PAP;I:[username];P:[password];A:[anon];;`

It's an eduroam WiFi, so it has a security level WPA3-Enterprise. My question is: Do you know if QR supports this security and if it does, whats the name to introduce in the parameter **T**??

The best database i could find on my research whas this github post, and i'd like to know where did this info came from.

![2](https://user-images.githubusercontent.com/72257457/94919669-2322b180-04b5-11eb-9e6a-207a4ec31c45.PNG)

**Comment by srowen** [comment]
No, though, you can write whatever you want into a QR code and you could make up the encoding you suggest for WPA-3. What matters is what a scanner client will do with it, and this one does not support WPA-3 anyway though.

**Comment by Azogue99** [comment]
How can i do that?
Im new to github :P

**Comment by srowen** [comment]
You would open a pull request with changes to the code. It's not particularly hard to return a new special value from WPA-3 from the parser, but adding support to actually configure a wifi network of that type in Android app might be harder.

**Comment by ThomasCr** [comment]
Have a look at https://github.com/zxing/zxing/discussions/1491
