### ISSUE TITLE
How we detect multiple Data Matrix code from a single images  ? Please any one help me to solve this 

### ISSUE THREAD

**Issue by fatana1** [zxing/zxing#1320]
Here is the code actually i have done the decode process but stack on detection

from pylibdmtx.pylibdmtx import decode
import cv2
import numpy as np

def dataMat(image, bgr):
    gray_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    data = decode(gray_img)
    print(data)
    for decodedObject in data:
        points = decodedObject.rect

        pts = np.array(points, np.int32)
        pts = pts.reshape((-1, 1, 2))
        #cv2.polylines(image, [pts], True, (0, 255, 0), 3)

        #cv2.putText(frame, decodedObject.data.decode("utf-8") , (30, 30), cv2.FONT_HERSHEY_SIMPLEX, 1,bgr, 2)

        print("Barcode: {} ".format(decodedObject.data.decode("utf-8")))

bgr = (8, 70, 208)

frame  = cv2.imread('4Dm.jpg')
code = dataMat(frame, bgr)
print(code)
cv2.imshow('Data Matrix reader', frame)
code = cv2.waitKey(0)

Result of decode
Barcode: JEAN BOSCO
电气工程专业
FUJIAN UNIVERSITY OF TECHNOLOGY
+8613023816076-CHINA  

Here is the image i used 

![4Dm](https://user-images.githubusercontent.com/62222034/95152016-acd8c480-07be-11eb-85c1-4eeac2d21462.jpg)

**Comment by srowen** [comment]
- This is not the `pylibdmtx` project
- That is one DataMatrix barcode
- This project's code correctly decodes it as-is

**Comment by sajukalhoro23-glitch** [comment]
Sajukalhoro
