### ISSUE TITLE
Waiting because no window has focus but there is a focused application that may eventually add a window when it finishes starting up.

### ISSUE THREAD

**Issue by hellobyhello** [zxing/zxing#1323]
0-15 11:18:16.462 645-659/? E/ActivityManager: ANR in **packageName** (packageName/ActivityCalss)
    PID: 6253
    Reason: Input dispatching timed out (Waiting because no window has focus but there is a focused application that may eventually add a window when it finishes starting up.)
    Load: 0.6 / 0.44 / 0.38
    CPU usage from 57239ms to 0ms ago:
      3.1% 258/surfaceflinger: 0.2% user + 2.8% kernel / faults: 6 minor 1 major
      1.5% 645/system_server: 0.6% user + 0.9% kernel / faults: 2036 minor 234 major
      0.8% 255/adbd: 0% user + 0.7% kernel / faults: 1358 minor
      0.4% 32/kswapd0
    : 0% user + 0.4% kernel
      0.2% 114/logd: 0% user + 0.1% kernel / faults: 8 minor
      0% 260/local_gps: 0% user + 0% kernel
      0% 722/com.android.systemui: 0% user + 0% kernel / faults: 209 minor 32 major
      0% 3/ksoftirqd/0: 0% user + 0% kernel
      0% 15/ksoftirqd/1: 0% user + 0% kernel
      0% 99/jbd2/sdb3-8: 0% user + 0% kernel
      0% 257/servicemanager: 0% user + 0% kernel / faults: 2 major
      0% 259/vinput: 0% user + 0% kernel
      0% 277/zygote: 0% user + 0% kernel / faults: 2434 minor 1 major
      0% 1320/sdcard: 0% user + 0% kernel / faults: 1 minor 1 major
      0% 1362/com.android.defcontainer: 0% user + 0% kernel / faults: 217 minor 2 major
     +0% 6238/logcat: 0% user + 0% kernel
     +0% 6253/com.hd123.cpos.develop: 0% user + 0% kernel
    8.9% TOTAL: 2.6% user + 4.6% kernel + 1% iowait + 0.2% irq + 0.2% softirq
    CPU usage from 1865ms to 2367ms later:
      5.8% 258/surfaceflinger: 1.9% user + 3.8% kernel
        3.8% 258/surfaceflinger: 1.9% user + 1.9% kernel
        1.9% 858/Binder_5: 0% user + 1.9% kernel
      1.9% 114/logd: 0% user + 1.9% kernel
      1.9% 255/adbd: 0% user + 1.9% kernel / faults: 13 minor
      1.9% 645/system_server: 1.9% user + 0% kernel
        1.9% 675/SensorService: 1.9% user + 0% kernel
      1.9% 6238/logcat: 1.9% user + 0% kernel
    7.2% TOTAL: 2% user + 4.1% kernel + 1% irq

*****************************************************************
This is my gradle version configuration：

I encountered this problem.
#Thu Sep 10 11:12:00 CST 2020
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

implementation
'com.google.zxing:core:3.4.0'
***************************************************************

When set the gradle version to gradle-4.10.2-all.zip, it's can work, why is this?

**Comment by srowen** [comment]
Not sure, you have your own project and app here it seems, not the one from this project.
