### ISSUE TITLE
FNC1 problem

### ISSUE THREAD

**Issue by eyagarci** [zxing/zxing#1324]
how can I decode fnc1 caracters using zxing?

I activate "ASSUME_GS1" option but I have this result: ]C190MPT00034110R20060043

Does anyone have an idea?

**Comment by oehhar** [comment]
The "]C1" tells you, that a leading FNC1 was present.
The included "GS" tells you, that a FNC1 was present between341 and 10R

Best regards,
Harald

**Comment by srowen** [comment]
FNC1 will be translated as ASCII char 29, unless it's the leading char, in which case it's "]C1". You are decoding them here correctly.

**Comment by eyagarci** [comment]
@srowen can we explain me how can I extract information from this id?
I think that I should have a result like (90)MPT000341(10)R20060043 because I need save each fnc1 character with its value.

**Comment by oehhar** [comment]
Please read the GS1 Genspec. It contains all information what is in the code and what is in the interpretation. The following info is from the Genspec:

- The code starts with an FNC1 character.
- The "()" are only in the interpretation.
- Before each AI (the number in () in the interpretation), there might be an FNC1 or GS.
- If the AI before is variable length, there must be an FNC1 or GS.
- The first FNC1 is transmitted by changing the Symbology ID. In case of Code128, the change is from ]C0 to ]C1
- any consecutive FNC1 contained in the code is transmitted as GS
- GS is the "group separator" with ASCII-Value 29. It is shown in your string as a question mark.

Thus, the received string "]C190MPT000341�10R20060043" is 100% correct and should be, what you expect.

Hope this helps,
Harald

**Comment by eyagarci** [comment]
thnx @oehhar
