### ISSUE TITLE
Aztec decoder does not handle FNC1 or ECI sequences

### ISSUE THREAD

**Issue by dlenski** [zxing/zxing#1327]
In Aztec's `PUNCT` mode, [the sequence `00000` encodes a `FLG(n)` code](https://en.wikipedia.org/wiki/Aztec_Code#Character_set) which can be used to insert either `FNC1` or [an ECI indication](https://en.wikipedia.org/wiki/Extended_Channel_Interpretation).

ZXing's Aztec decoder simply ignores the 5 bits which introduce this sequence:

https://github.com/zxing/zxing/blob/b1c85db64e0ef13e7d8a4c9de32bd94c76eea5d8/core/src/main/java/com/google/zxing/aztec/decoder/Decoder.java#L62-L65

… which causes it to not only ignore the FNC1 or ECI indicator, but also to completely lose synchronization due to the {3,7,11,15,19,23,27} bits which follow `FLG(n)` and indicate the value of `n` (3 bits) and/or the ECI code (4/8/…/24 bits).

I think it should be relatively straightforward to adopt the ECI handling from QR and PDF417 codes and add them to the Aztec decoder (and encoder), so that non-Latin1 characters can be reliably encoded in Aztec.

**Comment by srowen** [comment]
I don't know Aztec well at all but take your word for it. Yes I'd take a pull request on this if you have time and motivation. It does sound straightforward

**Comment by srowen** [comment]
Resolved by https://github.com/zxing/zxing/pull/1328
