### ISSUE TITLE
Aztec decoding (ZXing still can't correctly decode big aztec codes.) 

### ISSUE THREAD

**Issue by ghost** [zxing/zxing#133]

**Comment by sosite** [comment]
I compare Android apps - Barcode Scanner with ZXing vs NeoReader app. Barcode Scanner doesn't recognize big aztec code when NeoReader doesn't have a problem with that [sample image](https://cloud.githubusercontent.com/assets/2025949/7269283/d6a07df0-e8d2-11e4-936e-0ac21ae8bdf5.jpg).

Maybe it did't know a correct size where looking for a data?

**Comment by sosite** [comment]
![aztec-test](https://cloud.githubusercontent.com/assets/2025949/15851448/176bc89e-2c9d-11e6-9d49-273a661182e9.png)

In Poland in car card we use large aztec code. Unfortunately they can't be decoded by zxing.

**Comment by sebastianwarmuz** [comment]
any luck on that one?

**Comment by mokry** [comment]
Same problem. Have anybody fixed problem?

**Comment by buddingspacer** [comment]
Same problem, Is this fixed?
