### ISSUE TITLE
get separator with zxing

### ISSUE THREAD

**Issue by eyagarci** [zxing/zxing#1332]
How can I decode FNC2,FNC3,FNC4, SHIFT B, CODE B et CODE C separators using zxing library ?

**Comment by srowen** [comment]
Not sure what you mean, like which format. The formats are read correctly. Many of those things aren't characters in the output but affect how the parsing proceeds.

**Comment by eyagarci** [comment]
I want to know if I can decode the separators like fnc2, fnc3 ... to be able to extract the information encoded with the zxing library. For the example of fnc1 I used the option ASSUME_GS1 to save the information. I want to do the same for the other separators.
