### ISSUE TITLE
ScanError event is not calling while scan any invalid QR Code

### ISSUE THREAD

**Issue by amirSohel007** [zxing/zxing#1338]
I am using scanError event for handling the case of error, If my QR code is invalid or not work in that case i need to catch the error so for that I used this 'scanError' but it is not working,
or just wanted to know when this method trigger

**Comment by srowen** [comment]
You're talking about a different project.

**Comment by amirSohel007** [comment]
@srowen isn't zxing library ?

**Comment by srowen** [comment]
There is no ScanError anything in this project. You are probably looking at a port.
