### ISSUE TITLE
Android: Problems interacting with ZXing App with Android 11

### ISSUE THREAD

**Issue by ehambuch** [zxing/zxing#1341]
Changing the targetSdk to 30 (Android 11) I encountered some issues with my app that uses "android integration". Starting my app in the Android emulator, it got stuck in an endless loop of requesting for installation of the _ZXing Barcode Scanner_ app.

According to my research that is because of a new privacy feature called "_Package Visibility_" in Android 11.  I've added the following to my AndroidManifest which seem to help:

```
    <queries>
        <package android:name="com.google.zxing.client.android" />
    </queries>
```

**Comment by ehambuch** [comment]
Note: this is probably not an issue to the zxing software itself, but may help anyone integrating zxing with the latest Android versions.

**Comment by srowen** [comment]
Yeah, not surprised if this is the case. 
If there is any change on the app end, unfortunately it can't be published anymore.
But you're saying the calling app just needs this? if so I can put it in the wiki.

**Comment by ehambuch** [comment]
Yes, would be helpful to add this to the Wiki. The reason is explained [here](https://developer.android.com/about/versions/11/privacy/package-visibility). 
Is there any reason why the Barcode Scanner app won't be updated anymore? According to Google Play it hasn't been updated since 2018. I know that it is a pain to keep an Android app up to date...

**Comment by srowen** [comment]
You can't upload new app versions if they target 19 or less, and updating to 19+ would require rewriting the permissions code. If someone would do it, cool. Otherwise, it's just in maintenance mode

**Comment by srowen** [comment]
Added a note in https://github.com/zxing/zxing/wiki/Scanning-Via-Intent#package-visibility-and-android-11
