### ISSUE TITLE
The image you uploaded could not be decoded

### ISSUE THREAD

**Issue by aimilin6688** [zxing/zxing#1343]
The image you uploaded could not be decoded, or was too large. Go "Back" in your browser and try another image.
![2](https://user-images.githubusercontent.com/3804814/103477731-7b42ba00-4dfc-11eb-818e-39bc7a24adf2.png)
![微信图片_20210103184645](https://user-images.githubusercontent.com/3804814/103477735-8990d600-4dfc-11eb-82a4-8a299105de99.jpg)

[https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F3804814%2F103477735-8990d600-4dfc-11eb-82a4-8a299105de99.jpg](https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F3804814%2F103477735-8990d600-4dfc-11eb-82a4-8a299105de99.jpg)

**Comment by srowen** [comment]
The decoder won't let you upload huge images. Try running locally or crop just the barcode part of the image and upload that.

**Comment by aimilin6688** [comment]
I tried to crop the picture to only the QR code, and the result could be recognized.Thank you very much
