### ISSUE TITLE
Scanner: QR code not recognized

### ISSUE THREAD

**Issue by Albirew** [zxing/zxing#1344]
Tried to read following QR code with either zxing.org and SecScanQR Android app that uses this lib. May be related to borderless cells or color.
![00000](https://user-images.githubusercontent.com/2805161/104047488-013a7880-51e2-11eb-9ff5-ddb4abc1b75d.jpg)

**Comment by srowen** [comment]
That is a pretty invalid QR code. It's inverted, for one, and while you can
scan it if you set it to scan for inverted codes, the luminance difference
between red and black is probably not sufficient.
