### ISSUE TITLE
 Android 6.0 ArrayList.sort()

### ISSUE THREAD

**Issue by todo-fixme** [zxing/zxing#1351]
### Bug Reports

https://stackoverflow.com/questions/38951218/java-lang-nosuchmethoderror-no-interface-method-sortljava-util-comparator-ex/38951385

Android 6.0.1,level 23 
XiaoMi/MIUI

java.lang.NoSuchMethodError
1 com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:624)
2 com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
3 com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)

**Comment by srowen** [comment]
Not a bug. The newest version needs Java 8, and Android 6 doesn't support it.
