### ISSUE TITLE
How to add back button in barcode scanning page in iOS ?

### ISSUE THREAD

**Issue by gayugokhale** [zxing/zxing#1352]
Hello,

I am using Zxing nuget package in xamarin.forms app.

I am not able to go back without scanning QR/Barcode in iOS devices and simulators.In android it is possible using device back button. I tried adding scanning page in navigation stack so that Back button would show on this page as well. But it's not showing. Is there any way to implement this?

Thanks

**Comment by srowen** [comment]
That's a different package, and a question of how you write your app, rather than the scanning code.
