### ISSUE TITLE
Google Play store listing has adware

### ISSUE THREAD

**Issue by Rondom** [zxing/zxing#1353]
I know that this project is in maintenance mode, but I am opening this issue to alert people about the fact that the Play Store listing is shipping adware these days (shady websites popping up in Chrome). See recent ratings in the play store listing:
https://github.com/zxing/zxing

I am not sure if anyone still has access to the Play Store listing. Or maybe someone still has contacts to the original authors from Google, to get this fixed quickly. For now, I think it would be wise to remove the Play store link from the README.

**Comment by srowen** [comment]
I have access, and I am original author, but, this is false.
Please read https://github.com/zxing/zxing/issues/1345
