### ISSUE TITLE
Fix yourselves

### ISSUE THREAD

**Issue by feathered-arch** [zxing/zxing#1354]
It would be great if you asshats could leave out the adware notification bullshit. 

Because I'm fairly certain your asses are about to be handed back to you by Google for what is either deliberate, or is the result of your incompetence allowing your app to become compromised.

**Comment by srowen** [comment]
https://github.com/zxing/zxing/issues/1345#issuecomment-769319520

Your comments aren't welcome here, not just because they're wrong, but because of language.

**Comment by ronnie8743** [comment]
Didn't know i had an app someone made it to do tucked shit to me I don't
know how to make an app
