### ISSUE TITLE
ERROR: APK path is not specified for module "android"

### ISSUE THREAD

**Issue by herou** [zxing/zxing#1356]
I pulled the repo and I am facing this issue:

![image](https://user-images.githubusercontent.com/13895430/107125530-d1e35e00-68aa-11eb-978f-d3e7ecc26417.png)

**Comment by srowen** [comment]
Not sure, it's not related to this project per se. It builds correctly and opens for me in IJ fine.

**Comment by herou** [comment]
@srowen What do you mean is not related to this project? Why did you close the issue ??

**Comment by srowen** [comment]
Because the build in this project works fine, and works fine for me. I am sure it is something specific to whatever you are doing with the build, so, not something anyone can help you with with this level of info.
