### ISSUE TITLE
iQR

### ISSUE THREAD

**Issue by gallettube** [zxing/zxing#1357]
Add the capability to read iQRs on the SDK

**Comment by srowen** [comment]
What is that? But you would have to open a pull request.

**Comment by lamualfa** [comment]
> What is that? But you would have to open a pull request.

The next version of QR Code created by the original QR Code creator.

https://www.qrcode.com/en/codes/iqr.html

![image](https://github.com/user-attachments/assets/204ee52f-55e0-4714-8600-de8f1619e435)
![image](https://github.com/user-attachments/assets/19123b38-20a1-4582-b9e1-3107e0109439)
