### ISSUE TITLE
Chinese Characters QR code decode Wrong

### ISSUE THREAD

**Issue by shengye102** [zxing/zxing#1359]
Using zxing core 3.4.1.jar   decode  QR code ,  origin QRCode  content is "调压柜_3253" ,but zxing analyse content contains Error Character ? look for next image showing 
![1613728844(1)](https://user-images.githubusercontent.com/12425247/108489499-94d09000-72dc-11eb-8cd0-c5f6a3b1dfb4.jpg)

I'm confused abount this problem，Can anyone help me?Thank you very much

**Comment by srowen** [comment]
Not without seeing a QR code, or the actual output of the decoder in bytes.
