### ISSUE TITLE
Chinese Characters QR code decode Wrong

### ISSUE THREAD

**Issue by shengye102** [zxing/zxing#1360]
I  am so sorry, yesterday I can‘t  explain my question, so  I describle my question  agin,
Using zxing core 3.4.1.jar decode QR code , origin QRCode content is "调压柜_3253" ,but zxing analyse content contains Error Character ? look for next image showing
![1613728844(1)](https://user-images.githubusercontent.com/12425247/108576280-f4b84c80-7357-11eb-851a-77915b10e3e4.jpg)

my origin QRcode image is generated by online website, content is  调压柜_3253 , next  is  my qrcode image.
![调压柜_3253](https://user-images.githubusercontent.com/12425247/108576284-f97d0080-7357-11eb-8826-cfc83afea2d1.png)

I'm confused abount this problem,  I find a link about you said ,This QRCode Image is not ECI segment ,  what is it? and  what should I do?
Thank you very much

**Comment by srowen** [comment]
This decodes fine. I think the problem is however you are displaying the result.
https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F12425247%2F108576284-f97d0080-7357-11eb-8826-cfc83afea2d1.png

**Comment by shengye102** [comment]
It is wrong answer, look this link, this HTML  content contains a  special  characters  .why?

![1613782601(1)](https://user-images.githubusercontent.com/12425247/108576970-6db8a380-735a-11eb-8af6-da60ed19c4f9.jpg)

 I generate this by this https://cli.im/  website  
![1613782807(1)](https://user-images.githubusercontent.com/12425247/108576911-406bf580-735a-11eb-9c7b-9b7af15000d8.jpg)

**Comment by srowen** [comment]
That looks like a byte-order marker from unicode or a non-breaking space, U+FEFF. It's a non-printing char, but, it is in the QR code, so the result is correct.

**Comment by shengye102** [comment]
Do you mean it is a problem of generating a QR code image? I think Maybe it can be removed when decoding? Is this ok,you think?  becauce some qrcode image is generate by client, I can't control it .  
by the way, I want to ask you ,you said U+FEFF ,what is it?

**Comment by srowen** [comment]
OK I see what is going on. The bytes are encoding characters with UTF-16, not UTF-8. U+FEFF is the BOM for UTF-16, not UTF-8. That isn't supported here right now. That's an unusual encoding, as opposed to UTF-8 or maybe Big5. It ends up parsing OK anyway except that the BOM is treated as a character. The "right" thing to do is encode the QR code with an ECI segment specifying the supported encoding - or just use UTF-8. It's a valid feature request to support UTF-16 but I don't have time to do so myself.

**Comment by shengye102** [comment]
I roughly understand what you mean，thank you answer my question，now ，should I modify root decode code,but I don't konw how to do it? perhaps，Maybe you can tell me that I should focus on looking at the code in that place, I want to see

**Comment by shengye102** [comment]
hello, I think about it agin,accroding to your describle,I think a solved answer, use Pattern  expression ,  this can reach my goal ,next my add cod segment ,
![1613792999(1)](https://user-images.githubusercontent.com/12425247/108583039-fabb2700-7371-11eb-8269-1bfa1f45ea8a.jpg)
Maybe is ok?

**Comment by srowen** [comment]
I looked into it a little more and the problem is a bit different.
There is a UTF-8 byte order mark in the QR code bytes, so it is interpreted correctly as UTF-8. However the first real character in the UTF-8 text is U+FEFF, which is the UTF-16 byte order mark, just as a non-printing character. That's wrong. The code that generated this QR code mistakenly took UTF-16 bytes, with BOM, and encoded as a UTF-8 string.

So yes it is a problem with the QR code, and yes you can just ignore non-printing chars in your application.

I can add code that would guess UTF-16 encoding correctly, but, this isn't actually UTF-16-encoded.

**Comment by shengye102** [comment]
sorry,yesterday was  a rest day，I haven't reply you immediately,
Ok,you dont't need modify code about it, in fact ,as you said,the QR code image is Wrong, I also find this problem, use this website
(https://zxing.appspot.com/generator or https://ddsm.com/) generated the QR image is right ,  so  I decide to ignore no-printing chars in my code as you said. Thank you very much reply me
