### ISSUE TITLE
Mr Anthony Humphreys 

### ISSUE THREAD

**Issue by anthonyh2017** [zxing/zxing#1361]
Hello I’ve changed phones and deleted everything on my other phone and now I don’t have a way of setting it back up, can you please help, thank you

**Comment by anthonyh2017** [comment]
Why have you closed It, before you have sorted it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by srowen** [comment]
This is completely unrelated to this project or app.

**Comment by anthonyh2017** [comment]
No it’s not, how come when I try to login i need a QR Code or a setup code

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anthonyh2017** [comment]
Explain why you’re Authenticator App would say that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by srowen** [comment]
The Authenticator app is from Google. I am not Google. You are very much in the wrong place; stop asking here.
