### ISSUE TITLE
 FNC1 character decoding

### ISSUE THREAD

**Issue by dehnhard** [zxing/zxing#1373]
I noticed different FNC1 character treatments in the various zxing readers and want to open a discussion about it, targeting a community concensus (or maintainer decision) about a more standardized treatment.

### FNC1 treatment for GS1

Essentially this is: "A FNC1 character in the first position indicates a GS1 barcode and is replaced with the Smybology identifier, while any subsequent FNC1 character is replaced with a GS character."
Actually for some symbologies there is also a significance for FNC1 (or even FNC2) characters in subsequent positions, I'll consider these to be subcases of the same topic.

The GS1 Specifications[1] and Guidelines[2] mainly describes data processing wich takes place after the scanning, but mentions that the scanner "should be programmed to" process according to GS1 rules and "ideally"[3] "... passes the decoded data using the Symbology Identifier ...". 
It sounds more like a recommandation and like acknowledging the fact that there might be other use cases for the function characters.

According to [4] there seems to be an EU legislation mandating GS1 decoding for GS1 barcodes, also proposing it mandatory for non GS1 codes ("subject to confirmation").

### Implementation now

- ZXing does not prepend a symbology identifier to the content with the odd exception of Code128 and exactly only when decoding a leading FNC1 character and having the hint "ASSUME_GS1" set.
- Regarding converting FNC1 to GS:
  - Code128 does this if and only if the hint "ASSUME_GS1" is set.
  - The readers of the 1D barcodes EAN, UPC, ITF and RSS don't do any FNC1 conversion.
      - There is a class "AppIdDecoder" in the RSS folder which does something with FNC1, but I frankly have no clue what it does and when and where it is used.
  - PDF417 doesn't do any FNC1 conversion, but it is also not listed as a carrier in the GS1 specification.
  - QRCode converts FNC1 characters to GS if the first or the second character is FNC1.
  - Aztec converts FNC1 to GS, although it is not listed as a carrier in the GS1 specification.
  - Maxicode doesn't do any FNC1 conversion, but it is also not listed as a carrier in the GS1 specification.
  - Datamatrix converts FNC1 characters to GS.

It's obvious that the decoding could be harmonized, but I think it's not as bad as it may seem. It's a more of a sign that this is a living open source project that had contributions from different sources.

### Questions

1. Should ZXing recommend or require readers to do FNC1 conversion?
    - A minor breaking change for those apps that are treating the FNC1 themselves (some of them presumably workarounds for the missing conversion).
2. Should ZXing go further and also prepend the symbology identifier by default?
    - A major breaking change, as now all apps will receive 2-3 more characters in the content!
    - But also full compliance to GS1 and Symbology standards.
3. If (1) but not (2): What to do with a FNC1 character in the first position (which should have been replaced by the SI)? Keep, strip or convert to GS?

### My personal recommendation

I don't see any indication that the FNC1 is used by anyone for something else than what is decribed here, but several indications that it is in demand and even expected. E.g. the major 2D barcodes, including the recently reimplemented Aztec reader are all implementing it. So I think it would be good to require and implement the FNC1 to <GS> conversion in all readers.

I'm also leaning towards the "prepend the symbology identifier to the content" thing, but I am not the maintainer and won't have the hassle to communicate that change.

As a further note: I don't recommend making parts or all of this optional (as in a hint or option when scanning). I'd even get rid of the ASSUME_GS1 hint, which seems to be a half-hearted implementation of a "GS1 switch". Such a switch makes sense for an industrial scanning appliance, but I imagine most developers who are using ZXing let alone their end users wouldn't even know what that option means - they'll just want to scan that 'damned barcode' and get the result.

### References
[1] https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf
[2] https://www.gs1.org/docs/barcodes/GS1_DataMatrix_Guideline.pdf
[3] https://www.gs1.org/standards/gs1-datamatrix-guideline/25#3-Reading-and-decoding-GS1-DataMatrix+3-2-Scanners-for-GS1-DataMatrix
[4] https://www.gs1.org/sites/default/files/eu2018-574requireddatacapturespecifications.pdf

**Comment by srowen** [comment]
The role of the library is just to read and return what's in the barcode, so, up to apps what to do with it.

FNC1 is kind of ambiguous - is it part of the contents as ASCII 29, another formatted string, or just metadata? Depends. I think it should be consistent but I hesitate to change the output. So maybe responding to ASSUME_GS1 in more formats gives readers the option of returning that data?

Right, it's not on by default, it's there when a certain behavior is required.

**Comment by dehnhard** [comment]
Sorry, but I can't see pushing ASSUME_GS1 being less disruptive nor helping unifiing the implementation.

What exactly is the desired certain behavior?

I remember trying to use the hint once, ending up not using it not seeing any documentation or positive effect on using it.

Putting the analysis above into numbers, as of now:
- 1 reader adapts it's behavior to ASSUME_GS1, resulting in converting FNC1 if and only if GS1 is detected and the hint is set.
- 6 readers don't convert FNC1, ignoring ASSUME_GS1.
- 3 readers (including the most used types DataMatrix and QRCode) always convert FNC1 for GS1 and non-GS1 codes, also ignoring ASSUME_GS1.

**Comment by dehnhard** [comment]
Note: I just updated my initial post, because all mentions of `<GS>` in clear text did vanish, presumably conflicting with some markdown rules. It should be clearer now.

**Comment by srowen** [comment]
I think the overall issue is that the current default behavior is widely expected. IIRC there is another use case for treating FNC1 differently in 1 reader, hence some flag for selecting that. If you're suggesting the same alternate behavior, it makes sense to reuse the flag (whose name may not be the most accurate). Is that the idea?

I don't know enough about FNC1 to evaluate the right answer.

**Comment by dehnhard** [comment]
I'd call it similar to that alternate behavior and I think it describes on a technical level what those people need who expect a leading symbology identifier and GS characters in the content.

Sounds like you would be open to an implementation which adds a hint (atm i'd call it 'SYMBOLOGY') that turns zxing into a mode which does just that in a consistent way? I think about implementing that - provided I get it funded.

In the meantime I'd like to keep this issue open, in case somebody wants to add to the discussion.

**Comment by srowen** [comment]
I'm not sure, I don't know enough to really evaluate this. I think we do not want to change any default encoding behavior. The default should already be consistent.

I think returning metadata as metadata is also a good fine thing as in your other PR. 

I'd be more cautious about changing the returned contents string, but, there is already apparently one exceptional case here involving FNC1 that might need to generalize - not sure. It appears specific to GS1 and don't know how much GS1 applies to other formats. But again that sounds like an exception rather than rule.

**Comment by dehnhard** [comment]
I see some inconsistency regarding FNC1 to GS conversion. Arguably library consumer can easily work around it by doing the same conversion themselves.

Symbology in metadata is ok, but it also leads to an edge case in the result (see question 3 in my initial post).

**Comment by dehnhard** [comment]
Here is an interesting related article with an industrial background: https://www.packagingdigest.com/coding/gs1-datamatrix-fnc1-versus-gs-variable-length-field-separator-character

I let the rest speak for itself, just pointing out one claim of the article, which was new to me: The function characters have been invented for Code 128 to "define instructions for the bar code reading device" and have been adopted by other barcodes.

**Comment by srowen** [comment]
OK, I'm open to a PR to work on 3) if there's a clear improvement there. 
Right yeah it seems like this was 'primarily' used in Code 128 so that may be why the GS1 flag is there.
If there's a logically separate use of FNC1 in other barcodes that could be treated separately for that reason.
I don't know enough to know what the change should be.

**Comment by dehnhard** [comment]
I don't know enough either to propose something which is valid for all barcodes and I won't propose a content change for a partial solution. So I settle with a comment for the SYMBOLOGY hint for 3): https://github.com/zxing/zxing/pull/1376
