### ISSUE TITLE
Unable to scan QR Code

### ISSUE THREAD

**Issue by AlfredAfutu** [zxing/zxing#1378]
I am unable to scan the QR code attached. 

It looked like an inverted code so i tried setting the SCAN_TYPE to 1 but to no avail.

The content of the code is in the format `URL:https://domain_name/alphanumeric_characters`

I would be glad if i can be put on the right direction to solve the issue. 

Thanks in advance
<img width="128" alt="Screenshot 2021-04-08 at 16 47 12" src="https://user-images.githubusercontent.com/5557324/114055538-28601f00-9891-11eb-981d-2f579834bedd.png">

**Comment by srowen** [comment]
You would have to invert the image to scan it (there is a hint you can send in the next version that will make it try that automatically). This isn't technically valid by itself. I'm not sure what SCAN_TYPE is - are you sure you aren't using another library?

**Comment by AlfredAfutu** [comment]
Is this next version going to be released sometime soon?

**Comment by AlfredAfutu** [comment]
Also is the QR code actually inverted?

**Comment by srowen** [comment]
Maybe in a few months - no hard schedule. But it's easy enough to invert the image as the caller.
It's definitely inverted. It's meant to be dark-on-light

**Comment by AlfredAfutu** [comment]
I see this PR was recently merged which looks like the solution you mentioned. Is that correct?

**Comment by srowen** [comment]
Yes, but, you can already just invert the input.

**Comment by AlfredAfutu** [comment]
How can i do this?
