### ISSUE TITLE
Can't decode from CommandLineRunner but ok with online decoder

### ISSUE THREAD

**Issue by ChenjieXu** [zxing/zxing#1380]
### Bug Reports
When I decode this picture using java -jar target/javase-3.4.2-jar-with-dependencies.jar, no barcode found. But it can be decoded on online decoder. Is there anything that I missed? Here is my sample.
![test_new_pyzxing_version](https://user-images.githubusercontent.com/31937673/114302882-b6d8d880-9afd-11eb-98a3-b5cf2fa011b7.jpg)

**Comment by srowen** [comment]
Try specifying TRY_HARDER mode or different binarizers. The online decoder tries everything.

**Comment by ChenjieXu** [comment]
It can be successfully detected by specifying TRY_HARDER mode. Thank you.
