### ISSUE TITLE
read only pdf417 barcode

### ISSUE THREAD

**Issue by amdawadi22** [zxing/zxing#1381]
I have driver's license and there is more then one barcode on card. but, I want to read only pdf417 barcode via video streaming in pure JavaScript. many time video streaming is not focusing pdf417 barcode properly and it's take too much time to read this barcode. can u help if we get only pdf417 barcode from the video streaming and decode this barcode.

**Comment by srowen** [comment]
Does the port that you're using supoprt the "POSSIBLE_FORMATS" hint? you can use that to only look for one type of barcode.

**Comment by amdawadi22** [comment]
I can't understand what you say but this is my very simple code here. this is working but some time it's take too much time to decode pdf417 barcode when more then one barcode on the card. if any changes require in this. please, tell me.


<script type="text/javascript">
        window.addEventListener('load', function () {
            let selectedDeviceId;
            const codeReader = new ZXing.BrowserPDF417Reader();
            codeReader.listVideoInputDevices()
                .then((videoInputDevices) => {
                    const sourceSelect = document.getElementById('sourceSelect')
                    selectedDeviceId = videoInputDevices[0].deviceId
                    if (videoInputDevices.length >= 1) {
                        videoInputDevices.forEach((element) => {
                            const sourceOption = document.createElement('option')
                            sourceOption.text = element.label
                            sourceOption.value = element.deviceId
                            sourceSelect.appendChild(sourceOption)
                        })
                        sourceSelect.onchange = () => {
                            selectedDeviceId = sourceSelect.value;
                        };
                        const sourceSelectPanel = document.getElementById('sourceSelectPanel')
                        sourceSelectPanel.style.display = 'block'
                    }
                    document.getElementById('startButton').addEventListener('click', () => {
                        $("#video").attr('class', '');
                        codeReader.decodeFromVideoDevice(selectedDeviceId, 'video', (result, err) => {
                            if (result) {
                                document.getElementById('result').textContent = result.text
                                 }
                            if (err && !(err instanceof ZXing.NotFoundException)) {
                                 debugger;
                                 console.error(err)
                            }
                        })
                        console.log(`Started continous decode from camera with id ${selectedDeviceId}`)
                    })
                    document.getElementById('resetButton').addEventListener('click', () => {
                        codeReader.reset()
                        document.getElementById('result').textContent = '';
                        document.getElementById('captureImage').innerHTML = '';
                        console.log('Reset.')
                    })
                })
                .catch((err) => {
                    console.error(err)
                })
        })
    </script>

**Comment by amdawadi22** [comment]
<script type="text/javascript">
        window.addEventListener('load', function () {
            let selectedDeviceId;
            const codeReader = new ZXing.BrowserPDF417Reader();
            codeReader.listVideoInputDevices()
                .then((videoInputDevices) => {
                    const sourceSelect = document.getElementById('sourceSelect')
                    selectedDeviceId = videoInputDevices[0].deviceId
                    if (videoInputDevices.length >= 1) {
                        videoInputDevices.forEach((element) => {
                            const sourceOption = document.createElement('option')
                            sourceOption.text = element.label
                            sourceOption.value = element.deviceId
                            sourceSelect.appendChild(sourceOption)
                        })
                        sourceSelect.onchange = () => {
                            selectedDeviceId = sourceSelect.value;
                        };
                        const sourceSelectPanel = document.getElementById('sourceSelectPanel')
                        sourceSelectPanel.style.display = 'block'
                    }
                    document.getElementById('startButton').addEventListener('click', () => {
                        $("#video").attr('class', '');
                        codeReader.decodeFromVideoDevice(selectedDeviceId, 'video', (result, err) => {
                            if (result) {
                                document.getElementById('result').textContent = result.text
                                 }
                            if (err && !(err instanceof ZXing.NotFoundException)) {
                                 debugger;
                                 console.error(err)
                            }
                        })
                        console.log(`Started continous decode from camera with id ${selectedDeviceId}`)
                    })
                    document.getElementById('resetButton').addEventListener('click', () => {
                        codeReader.reset()
                        document.getElementById('result').textContent = '';
                        document.getElementById('captureImage').innerHTML = '';
                        console.log('Reset.')
                    })
                })
                .catch((err) => {
                    console.error(err)
                })
        })
    </script>

**Comment by srowen** [comment]
This is a different project code base I can't speak for. But in this project you can specify decode hints, like what format to scan for.

**Comment by amdawadi22** [comment]
I added hints also but till not give proper result for all cards. can you suggest me if any other changes require? 
### added hints in my code
const hints = new Map();
            const formats = [ZXing.BarcodeFormat.PDF_417];
            const CHARSET = 'utf-8';
            hints.set(ZXing.DecodeHintType.POSSIBLE_FORMATS, formats);
            hints.set(ZXing.DecodeHintType.CHARACTER_SET, CHARSET);
            hints.set(ZXing.DecodeHintType.TRY_HARDER, true);
            hints.set(ZXing.DecodeHintType.PURE_BARCODE, true);
           const codeReader = new ZXing.BrowserMultiFormatReader(hints);
