### ISSUE TITLE
Scan and Decode only pdf417 barcode

### ISSUE THREAD

**Issue by amdawadi22** [zxing/zxing#1382]
I have driver's license and there is more then one different type of barcode on card. but, I want to scan and decode only pdf417 barcode via video streaming in pure JavaScript. I added hints also to scan and decode only pdf417 barcode but it's not working properly for all card. 

### added hints in my code
```
const hints = new Map();
const formats = [ZXing.BarcodeFormat.PDF_417];
const CHARSET = 'utf-8';
hints.set(ZXing.DecodeHintType.POSSIBLE_FORMATS, formats);
hints.set(ZXing.DecodeHintType.CHARACTER_SET, CHARSET);
hints.set(ZXing.DecodeHintType.TRY_HARDER, true);
hints.set(ZXing.DecodeHintType.PURE_BARCODE, true);
const codeReader = new ZXing.BrowserMultiFormatReader(hints);
```

 I attached two card. the first one decode properly but in second card I didn't get any result.

please suggest me. what i need to change or tell me if any problem with Zxing.js 

![card2](https://user-images.githubusercontent.com/82382253/114972720-aa0d0980-9e9c-11eb-8c42-d9a223baf867.jpg)

![card1](https://user-images.githubusercontent.com/82382253/114972864-ec364b00-9e9c-11eb-8e52-569485e47b6c.jpg)

**Comment by srowen** [comment]
It looks reasonable, so may simply not decode.
But you are not using code from this project, rather a fork or port, it seems.

**Comment by amdawadi22** [comment]
this is not satisfied answer.
you told me to give decode hints. I also added but why it's not working for all card.

**Comment by srowen** [comment]
"Satisfied" or not, that's all the answer I can offer. I do not support _this_ project, let alone another one, and you should be starting with whatever project you're using. It may simply not decode. No more issues please.
