### ISSUE TITLE
OnNewIntent to scan NFC not being called from android 10 onwards

### ISSUE THREAD

**Issue by PhongDinh12** [zxing/zxing#1384]
I use onNewIntent to listen to NFC, when the camera is turned on, the onNewIntent function is not called when I swipe the NFC tag. When I turn off the camera, I swipe the NFC tag to the onNewIntent function to receive it normally. I am thinking that the function is overwritten or removed the service when the camera is turned on. If anyone has encountered this error please help me to debug. I sincerely thank !

**Comment by srowen** [comment]
Not sure, seems like you are talking about your own application? I think the intent handling is the same but maybe you are handling them differently when scanning for a barcode?

**Comment by PhongDinh12** [comment]
I want to swipe the NFC tag while the camera is open. But it is faulty from andorid 10, and under android 10, I still work normally

**Comment by srowen** [comment]
I don't know - you are talking about your own app, not this one, as far as I can tell.
