### ISSUE TITLE
Aztec code with large content is not getting scanned in Android.

### ISSUE THREAD

**Issue by naveenmatt** [zxing/zxing#1385]
### Bug Reports

The Aztec code that is generated with large content is not getting scanned in android. 
Any idea, whether the Aztec code fixes queued up for 3.4.2 has the related fixes in?
3.4.2 -> https://github.com/zxing/zxing/milestone/13?closed=1

![image](https://user-images.githubusercontent.com/5009945/116925444-0cd90180-ac0e-11eb-9fec-7fa02c6c6c6b.png)

**Comment by srowen** [comment]
3.4.2 is not released. I don't know if any fixes there are relevant. I could not get this to decode in the online decoder, which will try lots of things. Do you know already of a specific fix that might be relevant?

**Comment by srowen** [comment]
Huh OK it decodes to this with `master`: 

```
Aztec Code was developed in 1995 by Andrew Longacre and Rob Hussey at Welch Allyn, which later became a division of Honeywell known as Hand Held Products. Since that time, Aztec has been placed in the public.
domain and standardized according to ISO/IEC 2477 domain and standardized according to ISO/IEC 24778
Each row in an Aztec Code symbol contains a fixed mber of black or white square modules, typically with black representing a bit value of 1 and
```

If that's correct then I think it is probably due to some fix. I can work on a release of 3.4.2 if that's useful.

**Comment by naveenmatt** [comment]
Thanks @srowen . That would really help.

**Comment by srowen** [comment]
I am going to close this as solved by some other recent changes, but yes I understand releasing 3.4.2 soon would help.
