### ISSUE TITLE
Doesn't read a specific QR code from file image (Android)

### ISSUE THREAD

**Issue by aljosta** [zxing/zxing#1386]
The issue happen only with picture attached, cannot read QR from gallery with this image that content a QR code, the zxing return this exception "Method threw 'com.google.zxing.NotFoundException' exception" when I execute ```multiFormatReader.decodeWithState(binaryBitmap)``` in my code. With other pictures read correctly.

I have tried from zxing test web site https://zxing.org/w/decode.jspx, but I get the same result (No barcode was found in this image). The same happen when I trying from the app Barcode Scanner+(Plus) (No barcode was found in this image).

But when I try to read this qr code with camera, it's read correctly.

Could they help me to know why happen this issue with zxing for this specific QR code?
 
![QR_NoSeDejaLeer_1](https://user-images.githubusercontent.com/51809633/116924707-dc995f00-ac1d-11eb-8a0e-ac018edbcd37.jpeg)

**Comment by srowen** [comment]
I debugged it, and it does correctly identify the QR code. However, the QR code is a bit corrupted. You can see how the module sizes aren't quite correct and uniform, even at the corners. It is just enough to make the library reject this image. Unfortunately, the rendering of this QR code is slightly wrong enough to make it invalid.

**Comment by aljosta** [comment]
Thanks for your response, it's very helpful for me. Also I want to ask you about another QR Code in image attached, I had to re size it to be able read it as a file image. Could I make reading without re size the image? Could it miss me anything in the code for zxing be able to read this qr code?

This is the implementation without re size where it doesn't read:
```
 private void decodeFromFile(int resultCode, Intent intent) throws FileNotFoundException, NumberFormatException {
        if(resultCode == Activity.RESULT_OK && intent != null) {

            Uri selectedImageUri = intent.getData();
            Bitmap imageBitmap;

            InputStream imageStream = mManager.getActivity().getContentResolver().openInputStream(selectedImageUri);
            imageBitmap = BitmapFactory.decodeStream(imageStream);

            int width = imageBitmap.getWidth();
            int height = imageBitmap.getHeight();

            int[] pixels = new int[width * height];
            imageBitmap.getPixels(pixels, 0, width, 0, 0, width, height);

            Map<DecodeHintType, Object> hints = new Hashtable<>();
            hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);

            List<BarcodeFormat> codeFormatsToHint = new ArrayList<>();
            codeFormatsToHint.add(BarcodeFormat.QR_CODE);
            hints.put(DecodeHintType.POSSIBLE_FORMATS, codeFormatsToHint);

            MultiFormatReader multiFormatReader = new MultiFormatReader();
            multiFormatReader.setHints(hints);

            RGBLuminanceSource source = new RGBLuminanceSource(width, height, pixels);

            Result rawResult;

            BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(source));

            try {
                rawResult = multiFormatReader.decodeWithState(binaryBitmap);
                mOutputParameters.set(Outputs.OUTPUT_TEXT_DECODED.position(), rawResult.getText());
                mListener.notifyCallSuccessful(mOutputParameters);
            } catch (ReaderException re) {
                mListener.notifyCallError(Constants.ErrorCode.DECODING_FILE_ERROR.getCode());
            } finally {
                multiFormatReader.reset();
            }
        } else {
            mListener.notifyCallError(Constants.ErrorCode.GENERIC_ERROR.getCode());
        }
    }
```

![QR_NoSeDejaLeer_2](https://user-images.githubusercontent.com/51809633/117012283-67c53400-acb4-11eb-8fb6-95b15ccbf32d.jpeg)

**Comment by srowen** [comment]
This seems to decode fine. I sent it to zxing.org You do not have to resize.

**Comment by aljosta** [comment]
Thanks for all your help. But I have another question about the first image I sent you. Why does the image can't be read as an image file but it can be read from camera? what are the differences between read from camera and read from file for the zxing library?

**Comment by srowen** [comment]
The image itself is a bit corrupted. Strangely enough, when you take a picture of the picture with a camera, it may gloss over some of those issues and then still work. If that's true, you can try things like applying small perturbations of the image (blur in particular) to see if a small change happens to work. It's very close, just barely invalid, so, maybe worth trying.
