### ISSUE TITLE
Support for row/pixel stride in PlanarYUVLuminanceSource

### ISSUE THREAD

**Issue by alexbakker** [zxing/zxing#1387]
We're using CameraX in combination with ZXing in our Android app to scan QR codes. Previously, we were naively passing the YUV data given by CameraX in the image analysis callback to ZXing immediately. As a consequence, if the data contained padding, ZXing would see a corrupt image and would be unable to detect the QR code. We've now fixed the issue by stripping the padding before passing the data to ZXing. See: https://github.com/alexbakker/Aegis/commit/36cffa1b9a4cb648292dee8e31403563b992a60f.

Would it make sense to add support for row stride and pixel stride in PlanarYUVLuminanceSource? Maybe through a separate constructor (though it's already quite large) or a static helper function that strips the padding? I can work on a patch if this is something you think belongs in ZXing.

**Comment by srowen** [comment]
Yes I think that's fine. You can open a PR.

**Comment by Valodim** [comment]
If only the row stride diverges from the image width, this can also be fixed by setting the dataWidth parameter accordingly. @alexbakker have you seen `pixelWidth != 1` in the wild?

**Comment by alexbakker** [comment]
> If only the row stride diverges from the image width, this can also be fixed by setting the dataWidth parameter accordingly. 

You're right.

> @alexbakker have you seen pixelWidth != 1 in the wild?

I haven't. I just double checked [the documentation](https://developer.android.com/reference/androidx/camera/core/ImageAnalysis.Analyzer#analyze(androidx.camera.core.ImageProxy)) and it turns out I was trying to take too many formats into account. Apparently CameraX only produces images in the ``YUV_420_888`` format. So there's our confirmation that ``pixelStride`` will always be ``1``.
