### ISSUE TITLE
Barcode image is not showing the actual code in footer note

### ISSUE THREAD

**Issue by sarkar-ritam** [zxing/zxing#1389]
![image](https://user-images.githubusercontent.com/62100923/117426313-63617b00-af41-11eb-8905-11a76f3e560b.png)

## Contributing

The project is in maintenance mode, meaning, changes are driven by contributed patches.
There is otherwise no active development or roadmap for this project. It is "DIY".

Only proposed changes in the form of a pull request are likely to be acted on, but,
these will be acted on promptly.

### Feature Requests

Refer the attached image, This is the generated image by Zxing library in java base code. I want to show the actual UPC code as footer note, by default its not showing.
dependencies used

com.google.zxing
core
3.3.0

com.google.zxing
javase
3.3.0

**Comment by srowen** [comment]
For this, I'd say, I'd look at a pull request maybe, but, I think the purpose of this library is just to make the barcode. You can add whatever you like by hand or programmatically to the image.
