### ISSUE TITLE
Unable to overlap Edittext on top of ZXingScannerView

### ISSUE THREAD

**Issue by madhurihr1592** [zxing/zxing#1394]
I have an activity where parent is Framelayout, inside I have a ZXingScannerView also a EditText. When Keyboard is opened even after typing it is not displaying in edittext. 

As a workaround I aadded a nestedscrollview as parent for framelayout, after adding this edittext is taking input but once unable to delete the entered charater, In UI it is not updating. 

May be when the keyboard is open it is making the view hang. Have anyone faced similar issue ?

**Comment by srowen** [comment]
Sorry, don't know, that's an Android question in general, not directly related to this project
