### ISSUE TITLE
Can't read QR Code image while website/other app can

### ISSUE THREAD

**Issue by gmamessier-accor** [zxing/zxing#1395]
I'm using a Zxing library based on yours (I use the one from journeyapps) to scan a QR Code from an image. It works pretty well but I have found some images that I can't decode though the web site https://zxing.org/w/decode.jspx or another app using ZXing can decode it. So I'm wondering what I do wrong or what am I missing ...

If someone have a clue that would be great.

This image: https://ibb.co/xHDR39P
The other app decode it
the website can't decode
the app Barcode Scanner+ can't decode
my app can't decode

This image: https://ibb.co/zfMN0K3 (cropped from the first one)
The other app decode it
the website decode it
the app Barcode Scanner+ can't decode
my app can't decode

This image: https://ibb.co/z75n3wm (cropped from the second one)
The other app decode it
the website decode it
the app Barcode Scanner+ decode it
my app can decode

Here is the code I use to decode image. I tried with TRY_HARDER hint, with multiple binarizer and even rotating it..

```
fun scanQRImage(bMap: Bitmap, context: Context, angle: Float = 0f): IntentResult? {
        val intArray = IntArray(bMap.width * bMap.height)
        //copy pixel data from the Bitmap into the 'intArray' array
        bMap.getPixels(intArray, 0, bMap.width, 0, 0, bMap.width, bMap.height)
        val source: LuminanceSource = RGBLuminanceSource(bMap.width, bMap.height, intArray)
        val hints: MutableMap<DecodeHintType, Any> = Hashtable()
        hints[DecodeHintType.TRY_HARDER] = java.lang.Boolean.TRUE
        val bitmap = BinaryBitmap(HybridBinarizer(source))
        val reader: Reader = MultiFormatReader()
        return try {
            val result: Result = reader.decode(bitmap, hints)
            generateResultIntent(BarcodeResult(result, null), context, false)
        } catch (e: Exception) {
            val newAngle = angle + 90
            if (newAngle < 400)
                scanQRImage(rotateBitmap(bMap, angle), context, newAngle)
            else
                null
        }
    }
```

**Comment by srowen** [comment]
I don't accept issue reports like this - you'd have to propose a change after debugging why it doesn't read.

**Comment by gmamessier** [comment]
If anyone else have this issue, I may have found something. Try to rotate your image degre by degre, sometimes few degres made a difference in my scans
