### ISSUE TITLE
Code 39 VIN barcodes not being recognized 

### ISSUE THREAD

**Issue by roadhero** [zxing/zxing#1399]
While some of the vehicle identification number barcodes are recognized, the other ones are not (although, having a strict standard). They can be recognized with some other tools though. A good example is below:

![20210614_105045](https://user-images.githubusercontent.com/21088825/122761650-25c47180-d2a5-11eb-8295-b4813891f85c.jpg)

**Comment by petrykDima** [comment]
I have the same issue and couldn't fix it =(

**Comment by srowen** [comment]
For this image, it looks like the bars are too thin, and the exposure makes them even narrower in the image. Can you get a closer clearer photo? might work, but this one is probably just a little hard to scan
