### ISSUE TITLE
QR code detection failed

### ISSUE THREAD

**Issue by TyrionChou** [zxing/zxing#1401]
hi there, why this image detection failed? this picture  is quiet clear!
![1152](https://user-images.githubusercontent.com/25079938/123098672-f60f9800-d463-11eb-8cc2-dd877e21531a.jpg)

**Comment by srowen** [comment]
It works fine: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F25079938%2F123098672-f60f9800-d463-11eb-8cc2-dd877e21531a.jpg

**Comment by TyrionChou** [comment]
changing parameter --multi to --pure_barcode can solve this well
