### ISSUE TITLE
arm64-v8a，release，return error points result

### ISSUE THREAD

**Issue by liang55** [zxing/zxing#1403]
### Bug Reports
Use zxing in the formal environment, cpu architecture arm64-v8a. After scanning the QR code several times, wrong coordinate data will be obtained.

1.implementation 'com.google.zxing:core:3.4.1'
2.arm64-v8a,release apk
3.
`
public static Result decodeImage(Bitmap bitmap) {
        if (bitmap == null) return null;
        Matrix matrix = new Matrix();
        matrix.postScale(1, 2);
        Bitmap resizeBmp = Bitmap.createBitmap(bitmap,0,0,bitmap.getWidth(),
                bitmap.getHeight(),matrix,true);
        bitmap=resizeBmp;
        int width = bitmap.getWidth();
        int height = bitmap.getHeight();
        int[] pixels = new int[width * height];
        bitmap.getPixels(pixels, 0, width, 0, 0, width, height);
        RGBLuminanceSource source = new RGBLuminanceSource(width,height,pixels);
        BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(source));
        try {
            Map<DecodeHintType, Object> hints = new EnumMap<>(DecodeHintType.class);
            hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
            hints.put(DecodeHintType.CHARACTER_SET,"utf-8");
            return  new MultiFormatReader().decode(binaryBitmap,hints);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
` 
![71ff7937-30b3-4261-95a1-69d92c2a81dd](https://user-images.githubusercontent.com/9209995/123246893-e2723900-d518-11eb-94d0-44b0b37ea5ae.jpg)
4.return error points result, [[235962256,80],[603,80]]

**Comment by liang55** [comment]
What I tested was to recognize this image three times, and it would return the wrong points data.

**Comment by srowen** [comment]
Unless you have a change to propose that would overall increase detection, no single mis-detection is considered a bug

**Comment by liang55** [comment]
> Unless you have a change to propose that would overall increase detection, no single mis-detection is considered a bug

thanks for the reply. You can try it. In the release version of the arm64-v8a system, when the barcode is recognized multiple times, a very large error coordinate data will appear. For example [[235962256,80],[603,80]].
