### ISSUE TITLE
Cant decode QRcode, not found exception

### ISSUE THREAD

**Issue by lintangtimur** [zxing/zxing#1404]
```java

    public static Result readQRCode(String filePath, String charset, Map hintMap)
            throws FileNotFoundException, IOException, NotFoundException {
        BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(
                new BufferedImageLuminanceSource(
                        ImageIO.read(new FileInputStream(filePath)))));
        Result qrCodeResult = new MultiFormatReader().decode(binaryBitmap, hintMap);

        return qrCodeResult;
    }
```
![error](https://user-images.githubusercontent.com/16686825/123364575-dfba2700-d59e-11eb-8129-aac6c246692c.jpg)

**Comment by srowen** [comment]
This has no quiet zone of white pixels around it. It is invalid.

**Comment by lintangtimur** [comment]
all of my qr created by generator, below is same generator
![R1PR01012100000001515](https://user-images.githubusercontent.com/16686825/123378222-a7264780-d5b6-11eb-8b7f-b3922fc6d284.jpg)

But success to decode
