### ISSUE TITLE
Not decode qrcode

### ISSUE THREAD

**Issue by chen-laodi** [zxing/zxing#1407]
![c76135bc-332e-487b-991e-b8f4fe10d905](https://user-images.githubusercontent.com/40551848/124685124-3579c200-df03-11eb-995c-2b84ccd22648.jpg)
Can someone tell me why it can't decode

**Comment by srowen** [comment]
I think it's just too corrupted - look at the bar widths, and shape of the finder pattern at the bottom left for example. Not even nearly square or even.

**Comment by chen-laodi** [comment]
> 我认为它太损坏了 - 例如，查看左下角的条宽和取景器图案的形状。甚至不接近正方形或什至。

![c76135bc-332e-487b-991e-b8f4fe10d905](https://user-images.githubusercontent.com/40551848/124710732-be0e5780-df2f-11eb-992a-bfa093d4de69.jpg)
The high-definition positioning is redrawn, but it still cannot be decoded

**Comment by srowen** [comment]
That's better but I still see significant distortions. Look at the space to the right of the top left finder pattern. It's far too thin.
