### ISSUE TITLE
oss-fuzz integration of zxing

### ISSUE THREAD

**Issue by 0roman** [zxing/zxing#1409]
Hi all,

I prepared the integration (https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/21430bdfc29e5055fc539a50100db5a867197473) of zxing into google oss-fuzz. This will enable continuous fuzzing of this project, which will be conducted by google. Bugs that will be found by fuzzing will be reported to you. 

The integration makes only sense if someone will deal with the bug reports submitted by oss-fuzz. Are you interested in the integration? If yes, I would submit a pull request and I would provide your contact information for bug reports. Is there any email I can use for that?

For the Fuzzing of Java applications Jazzer is used. [Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) is a coverage-guided, in-process fuzzer for the JVM platform developed by Code Intelligence. It is based on libFuzzer and brings many of its instrumentation-powered mutation features to the JVM. 
Jazzer has already found a lot of critical bugs in JVM applications.

If there are any questions regarding fuzzing or the oss-fuzz integration, it would be a pleasure for me to help.

**Comment by srowen** [comment]
Is there any way to see some of the issues it might detect in a first trial run? 
I'm the only point of contact and could try to fix fairly simple issues it finds; yeah I think this could be valuable, to run at least once in a while. Is it possible to run it manually or in the existing build or does it need to happen via an external service?

**Comment by 0roman** [comment]
@srowen that sounds good. It is not necessary that only you should fix all issues found with fuzzing. It would be enough if you could create tickets here. After my integration in oss-fuzz you will be notified per mail when findings will be triggered with detailed reports. 

Interesting issues would be for example out of memories or ininite loops, see https://github.com/CodeIntelligenceTesting/jazzer#findings for different findings found with jazzer. 

An issue which was detected after seconds in zxing was an ArrayIndexOutOfBoundsException. See the following snippet of a fuzz test:

```
#1637	REDUCE cov: 1305 ft: 1832 corp: 68/359b lim: 6 exec/s: 1637 rss: 210Mb L: 6/6 MS: 5 CopyPart-ChangeBinInt-ChangeByte-CopyPart-CopyPart-
#1640	NEW    cov: 1305 ft: 1839 corp: 69/365b lim: 6 exec/s: 1640 rss: 211Mb L: 6/6 MS: 3 InsertByte-CopyPart-ChangeByte-
#1701	NEW    cov: 1305 ft: 1840 corp: 70/371b lim: 6 exec/s: 1701 rss: 212Mb L: 6/6 MS: 1 ChangeBit-
#1756	NEW    cov: 1305 ft: 1842 corp: 71/377b lim: 6 exec/s: 1756 rss: 213Mb L: 6/6 MS: 5 EraseBytes-ChangeBit-ChangeBinInt-ChangeByte-CrossOver-
#1788	NEW    cov: 1341 ft: 1930 corp: 72/383b lim: 6 exec/s: 1788 rss: 213Mb L: 6/6 MS: 2 CopyPart-ChangeBinInt-
#1814	NEW    cov: 1390 ft: 2039 corp: 73/388b lim: 6 exec/s: 1814 rss: 214Mb L: 5/6 MS: 1 ChangeByte-
#1884	NEW    cov: 1390 ft: 2040 corp: 74/392b lim: 6 exec/s: 1884 rss: 215Mb L: 4/6 MS: 5 CopyPart-ChangeByte-EraseBytes-CopyPart-InsertByte-
#1920	NEW    cov: 1390 ft: 2043 corp: 75/398b lim: 6 exec/s: 1920 rss: 216Mb L: 6/6 MS: 1 ChangeBinInt-

== Java Exception: java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 3
	at com.google.zxing.common.BitMatrix.get(BitMatrix.java:162)
	at com.google.zxing.aztec.detector.Detector.getColor(Detector.java:471)
	at com.google.zxing.aztec.detector.Detector.isWhiteOrBlackRectangle(Detector.java:433)
	at com.google.zxing.aztec.detector.Detector.getBullsEyeCorners(Detector.java:256)
	at com.google.zxing.aztec.detector.Detector.detect(Detector.java:76)
	at com.google.zxing.aztec.AztecReader.decode(AztecReader.java:65)
	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
	at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:57)
	at MultiFormatDecodeFuzzer.fuzzerTestOneInput(MultiFormatDecodeFuzzer.java:48)

```
Is this enough for you?

**Comment by srowen** [comment]
Yeah that kind of thing is usually enough to figure out where should have a better check and catch an exception

**Comment by 0roman** [comment]
You will also get an input in the report which will trigger the finding. If you agree I would use srowen@gmail.com as primary contact for bug reports found with oss-fuzz and submit a pull request to oss-fuzz?

**Comment by srowen** [comment]
Yeah sounds fine to set up

**Comment by srowen** [comment]
I think I fixed the error above. It's hard to say as it's hard to know what input causes it, which could lead to a test, but I'm pretty certain of it anyway.

**Comment by srowen** [comment]
Just closing on this side --
