### ISSUE TITLE
Postal Code BarCode

### ISSUE THREAD

**Issue by sarathkumar-optisol** [zxing/zxing#1413]
Unable to read Postal Code Barcode using Zxing.
Is there is a chance to implementation Postal Code Barcode in future?

For Reference:
https://www.dynamsoft.com/Barcode-Types/Australian-Post.aspx

**Comment by oehhar** [comment]
Dear sarathkumar,
thank you for the valueable proposition. The project is in maintenance mode. There are no active developers.
But if you may contribute this change, it may be accepted in the main repository.

Best regards,
Harald
