### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by bpenh68** [zxing/zxing#1414]
I have download the ZXing 3.3.3 source code.

when i use : mvn install

some failure occured.

what should i do?

 --- maven-jar-plugin:3.1.0:jar (default-jar) @ core ---
[INFO] Building jar: /Users/pengbin/studyflutter/zxing-zxing-3.3.3/core/target/core-3.3.3.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:3.0.0:jar (attach-javadocs) @ core ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ZXing 3.3.3:
[INFO] 
[INFO] ZXing .............................................. SUCCESS [  5.977 s]
[INFO] ZXing Core ......................................... FAILURE [01:27 min]
[INFO] ZXing Java SE extensions ........................... SKIPPED
[INFO] ZXing zxing.org web app ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:33 min
[INFO] Finished at: 2021-08-01T19:12:08+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar (attach-javadocs) on project core: Execution attach-javadocs of goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar failed: Cannot invoke "org.apache.commons.lang3.JavaVersion.atLeast(org.apache.commons.lang3.JavaVersion)" because "org.apache.commons.lang3.SystemUtils.JAVA_SPECIFICATION_VERSION_AS_ENUM" is null -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :core

### Bug Reports

Bug reports must have enough detail to understand and reproduce the problem. Inadequate
bug reports will be closed with a request for more information.

Bug reports without an associated pull request are not likely to be addressed, but will be
left open for some time to see if anyone can contribute a solution. However, bug reports
with a pull request are likely to be merged promptly.

**Comment by bpenh68** [comment]
3.4.0 is same case.

------------------------------------------------------------------------
[INFO] Reactor Summary for ZXing 3.4.0:
[INFO] 
[INFO] ZXing .............................................. SUCCESS [ 32.528 s]
[INFO] ZXing Core ......................................... FAILURE [ 41.067 s]
[INFO] ZXing Java SE extensions ........................... SKIPPED
[INFO] ZXing zxing.org web app ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 min
[INFO] Finished at: 2021-08-01T19:22:03+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:4.2.0:bnd-process (default) on project core: bnd error: null: ConcurrentModificationException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :core
pengbin@192 zxing-zxing-3.4.0 %

**Comment by bpenh68** [comment]
but 3.4-2.1 is ok.

[INFO] Installing /Users/pengbin/studyflutter/zxing-zxing-3.4-2.1/zxingorg/target/zxingorg-3.4.1-sources.jar to /Users/pengbin/.m2/repository/com/google/zxing/zxingorg/3.4.1/zxingorg-3.4.1-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ZXing 3.4.1:
[INFO] 
[INFO] ZXing .............................................. SUCCESS [ 24.229 s]
[INFO] ZXing Core ......................................... SUCCESS [02:16 min]
[INFO] ZXing Java SE extensions ........................... SUCCESS [  9.020 s]
[INFO] ZXing zxing.org web app ............................ SUCCESS [ 17.560 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:07 min
[INFO] Finished at: 2021-08-01T19:30:02+08:00
[INFO] ------------------------------------------------------------------------

**Comment by bpenh68** [comment]
but in android/ , error occured

pengbin@192 android % mvn package android:apk
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.google.zxing:android:4.7.9: Could not find artifact com.google.zxing:zxing-parent:pom:3.4.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 40, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.google.zxing:android:4.7.9 (/Users/pengbin/studyflutter/zxing-zxing-3.4-2.1/android/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.google.zxing:android:4.7.9: Could not find artifact com.google.zxing:zxing-parent:pom:3.4.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 40, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
pengbin@192 android %

**Comment by srowen** [comment]
Builds fine for me. See the wiki page for how to build
