### ISSUE TITLE
Is there any restriction or constraint when detect QRCode in bitmap?

### ISSUE THREAD

**Issue by kim-ninh** [zxing/zxing#1416]
I have two images with the following resolution: 720x1480 and 1080x2160 (both of them are the screenshot on my phone which contain a QRcode inside it). 
The first one is not able to detect in original resolution but when resized, it is detected normally.
The second one is detected even in original resolution but it can't when resized.
I wonder if there is any constraint when detecting QRCode in bitmap (image resolution for example)

Thanks

**Comment by srowen** [comment]
There is no constraint. However some high res images are harder to detect because the noise is high resolution too. Sometimes small changes to the image work, and sometimes down sampling actually helps as it's a mild noise filter

**Comment by kim-ninh** [comment]
Thanks for your reply, Sean!
