### ISSUE TITLE
Can't select macro camera

### ISSUE THREAD

**Issue by compunited** [zxing/zxing#1424]
Almost all new smartphone have multiple cameras.
It would be good to force/use the macro camera. Unfortunately there is no property to use the macro camera

**Comment by srowen** [comment]
As the message says - maintenance mode, no feature requests.
I'd look at a clean pull request to add this, but, I can't release new versions of the app anyway.
I don't know if a macro camera helps - focus matters most, and people tend to be close to the code not far.
