### ISSUE TITLE
Xamarin Forms using shell seems to be threading issue ?

### ISSUE THREAD

**Issue by stephenhauck** [zxing/zxing#1431]
I am running 3.1.0-beta2 and am not sure this is where we should be posting ?
I have a Xamarin Forms app using the shell navigation system .. 
when I am one form deep it seems that everything works fine... 
If I open a couple of pages and try to scan it hangs and complains about 
"{Android.Util.AndroidRuntimeException: Only the original thread that created a view hierarchy can touch its views."
I have not tried this on iOS yet ..

I navigate to the scanning view like so 
```
var route = $"{nameof(ScanBarcodeView)}?_viewTitle=Scan Serial Number";
await Shell.Current.GoToAsync(route);
```

I have tried to invoke it on the main thread like so with no change in behavior ..
`Device.BeginInvokeOnMainThread(async () => await Shell.Current.GoToAsync($"{nameof(ScanBarcodeView)}?_viewTitle=Scan AssetNumber"));`

Any suggestions ?

**Comment by srowen** [comment]
That would be a different project, sorry. I don't think that's related to anything here.
