### ISSUE TITLE
Unable to detect QR code in Program, but a scanner app is able to detect this. 

### ISSUE THREAD

**Issue by sanjeebsarkar** [zxing/zxing#1435]
Hi , 
Thank you so much for this library and it works on almost all of the cases of QR code detection except for a few, and it would be really great if you can tell me the reason. 
I am attaching a screenshot of the QR code, below :

![image](https://user-images.githubusercontent.com/58333434/133977016-91a2785c-dd7d-4da7-ac56-1e82e610021d.png)

I am using the below code for QR detection : 

`

      private static final Map<DecodeHintType,Object> HINTS;
	  private static final Map<DecodeHintType,Object> HINTS_PURE;
	 
	  static {
		    HINTS = new EnumMap<>(DecodeHintType.class);
		    HINTS.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
		    HINTS.put(DecodeHintType.POSSIBLE_FORMATS, EnumSet.allOf(BarcodeFormat.class));
		    HINTS_PURE = new EnumMap<>(HINTS);
		    HINTS_PURE.put(DecodeHintType.PURE_BARCODE, Boolean.TRUE);
		  }
	
	public static void processImage(BufferedImage image,String pdfName) throws IOException, ReaderException {

		LuminanceSource source = new BufferedImageLuminanceSource(image);
		BinaryBitmap bitmap = new BinaryBitmap(new GlobalHistogramBinarizer(source));
		Collection<Result> results = new ArrayList<>(1);
		System.out.print(pdfName+" ");
		try {

			MultiFormatReader reader = new MultiFormatReader();
			ReaderException savedException = null;
			try {
				// Look for multiple barcodes
				MultipleBarcodeReader multiReader = new GenericMultipleBarcodeReader(reader);
				Result[] theResults = multiReader.decodeMultiple(bitmap, HINTS);
				if (theResults != null) {
					results.addAll(Arrays.asList(theResults));
				}
			} catch (ReaderException re) {
				savedException = re;
			}

			if (results.isEmpty()) {
				try {
					// Look for pure barcode
					Result theResult = reader.decode(bitmap, HINTS_PURE);
					if (theResult != null) {
						results.add(theResult);
					}
				} catch (ReaderException re) {
					savedException = re;
				}
			}

			if (results.isEmpty()) {
				try {
					// Look for normal barcode in photo
					Result theResult = reader.decode(bitmap, HINTS);
					if (theResult != null) {
						results.add(theResult);
					}
				} catch (ReaderException re) {
					savedException = re;
				}
			}

			if (results.isEmpty()) {
				try {
					// Try again with other binarizer
					BinaryBitmap hybridBitmap = new BinaryBitmap(new HybridBinarizer(source));
					Result theResult = reader.decode(hybridBitmap, HINTS);
					if (theResult != null) {
						results.add(theResult);
					}
				} catch (ReaderException re) {
					savedException = re;
				}
			}

			if (results.isEmpty()) {
				try {
					throw savedException == null ? NotFoundException.getNotFoundInstance() : savedException;
				} catch (FormatException | ChecksumException e) {
					throw e;
				} catch (ReaderException e) { // Including NotFoundException
					throw e;
				}
				
			}
			System.out.println("Printing all the results in collection object");
			for(Result r : results) {

				String data = r.getText();
				
			}
		}
		catch (RuntimeException re) {
			// Call out unexpected errors in the log clearly
			log.log(Level.WARNING, "Unexpected exception from library", re);
			throw re;
		}
		System.out.println();
	}
`

Can you please help me out with this? 
Thank you.

**Comment by sanjeebsarkar** [comment]
Sorry, I forgot to mention, the QR code is a part of a PDF file. The PDF is converted to image. and then that image is scanned for reading the QR code. Now this is working for most of the PDF file except for this and couple of others more. So I just selected 1 QR code and raised this issue. If u need the other QR codes also, please let me know I will paste the QR data. If you need the entire PDF page where this QR is residing, let me know that also.

**Comment by srowen** [comment]
In the app it's actually getting many slightly different views of this image. Some may not decode, some might. You can try further generating slight variations on the image (slight blur, rotation, etc) to try even harder. 

One main problem with this QR code is lack of quiet zone around it. It needs to have white space around the border, so the generated QR code here is technically wrong. If you can fix the PDFs that's the best solution. But this is pretty minor. It's really the complexity of the code, which also indicates this isn't a great use of QR codes. Beyond version 10 or so gets harder to read.

**Comment by sanjeebsarkar** [comment]
Hi,
Thank for the info, I will try to rotate the image and see if that will work or not.
