### ISSUE TITLE
Removed cpp version can't decode this QR but current java version can

### ISSUE THREAD

**Issue by kim-ninh** [zxing/zxing#1439]
Hi, I've using the removed cpp version of this repository. Actually, it is from the fork [glassechidna/zxing-cpp](https://github.com/glassechidna/zxing-cpp). The following QR code can not decode on cpp version but it works fine on java. After digging the source, I figure out this exception is throw: ReedSolomonException("Error locator degree does not match number of roots."). 

The only stack trace I have is something like this
![image](https://user-images.githubusercontent.com/28674990/134457257-a3e0e3f6-6f7f-4e9c-bce9-f19c835d230f.png)

I know the cpp version is removed from the current repo but my app is in production. Can you give me some idea how to fix this?

Thanks

Here is QRCode:

![qr_fail6](https://user-images.githubusercontent.com/28674990/134457501-84af669f-58b7-46d1-b11c-badb088bcec5.png)

**Comment by jiaeck** [comment]
This port to c++ works for this qr code
https://github.com/nu-book/zxing-cpp

It requires a C++17 compliant compiler

**Comment by srowen** [comment]
OK, but it'd be better to report vs any active fork

**Comment by kim-ninh** [comment]
For anyone facing this problem, try to read the mirrored code. https://github.com/zxing/zxing/blob/be2c5bdd883f9f42e794e4b0e7e1b30f436fc0a7/core/src/main/java/com/google/zxing/qrcode/decoder/Decoder.java#L91-L127

**Comment by srowen** [comment]
Ah, if the QR code is flipped over, then it's not valid. That's why the library doesn't try it
