### ISSUE TITLE
Compiling 3.0.1 for Java 6

### ISSUE THREAD

**Issue by aedenj** [zxing/zxing#144]
Excuse my ignorance I'm not well versed in the Java ecosystem. I've attempted to follow the instructions to build core and javase using, for example, 

`mvn -DskipTests packages`

but I get the error: 

```
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.879 s
[INFO] Finished at: 2014-05-12T18:48:40-08:00
[INFO] Final Memory: 11M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project core: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /Users/aeden/projects/zxing/zxing-zxing-3.0.0/core/src/main/java/com/google/zxing/aztec/AztecReader.java:78: <identifier> expected
[ERROR] } catch (NotFoundException | FormatException e) {
[ERROR] ^
[ERROR] /Users/aeden/projects/zxing/zxing-zxing-3.0.0/core/src/main/java/com/google/zxing/aztec/AztecReader.java:78: '{' expected
[ERROR] } catch (NotFoundException | FormatException e) {
[ERROR] ^
```

Advice?

**Comment by thotypous** [comment]
@tboemker Please take a look at https://github.com/thotypous/zxing/tree/zxing-2.3.0-java6 and https://github.com/thotypous/zxing/releases/tag/zxing-2.3.0-java6. I hope this is useful for you.

**Comment by mhcuervo** [comment]
We faced the same problem some weeks ago and back-ported some modules of version 3.2.0. (https://github.com/Solvoj/zxing/tree/master-Java6). Back-ported version of "core" and "javase" are currently in maven central. Group ID: "com.solvoj.zxing-java6" . Artifact Ids "core-java6" and "javase-java6" respectively.

        <dependency>
            <groupId>com.solvoj.zxing-java6</groupId>
            <artifactId>core-java6</artifactId>
            <version>3.2.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.solvoj.zxing-java6</groupId>
            <artifactId>javase-java6</artifactId>
            <version>3.2.0</version>
        </dependency>
