### ISSUE TITLE
micro PDF417 decoding issue

### ISSUE THREAD

**Issue by jiaeck** [zxing/zxing#1440]
Hi,
does current zxing decode **micro** PDF417 format?
It is able to do so according to: http://fileformats.archiveteam.org/wiki/MicroPDF417
However I have not managed to decode micro PDF417 using zxing.

Any hint is appreciated!
Thanks
Jia

**Comment by srowen** [comment]
Hm, I'm not sure actually, but "WYSIWYG" - if it works it works, if not it doesn't
