### ISSUE TITLE
Issue with GS1-128 barcode

### ISSUE THREAD

**Issue by HunSpeedi** [zxing/zxing#1457]
Description of the bug:

When I process a GS1 DataMatrix like this one:
https://barcode.tec-it.com/en/GS1DataMatrix?data=0105000456013482172012001000001%5CF210000000003
I get the following result: \u001d0105000456013482172012001000001\u001d210000000003
The \F (FNC1) terminator is recognized and the \u001d character is added between values.

However when I do the following with a GS1-128 barcode like this one:
https://barcode.tec-it.com/en/EANUCC128?data=010500045611225310COV0109%5CF17220901%20
I get the following result: 010500045611225310COV010917220901
And the \F (FNC1) terminator is not recognized and the values are concatenated.

Expected behavior:
The plugin should recognize the group separator in a case of a GS1-128 barcode as well.

**Comment by srowen** [comment]
I won't have time to try to debug this, but if you can do so and open a PR with a fix, I'd look at it. I don't know whether the behavior is correct or not

**Comment by axxel** [comment]
zxing-cpp has the same behavior and I had quick look at the code. There is a `DecodingHint` called [ASSUME_GS1](https://github.com/zxing/zxing/blob/6c034f977505b058c7cf764b3d9b1abd068a725e/core/src/main/java/com/google/zxing/DecodeHintType.java#L76) that changes the behavior.

Maybe setting that hint is all you need. Our project does replace the first \FNC1 with the symbology identifier "]C1", though. I have not checked what zxing does.

**Comment by Mohama123** [comment]
No

در تاریخ سه‌شنبه ۹ نوامبر ۲۰۲۱،‏ ۱۶:۰۲ Sean Owen ***@***.***>
نوشت:
