### ISSUE TITLE
Fatal Exception: java.lang.VerifyError Verifier rejected class com.google.zxing.pdf417.decoder.DetectionResultRowIndicatorColumn

### ISSUE THREAD

**Issue by duyhv12** [zxing/zxing#1461]
Hi I am facing with this issue. 
please help me how to resolve this issue.

sorry if my english not well.

Fatal Exception: java.lang.VerifyError
Verifier rejected class com.google.zxing.pdf417.decoder.DetectionResultRowIndicatorColumn: com.google.zxing.pdf417.decoder.BarcodeMetadata com.google.zxing.pdf417.decoder.DetectionResultRowIndicatorColumn.getBarcodeMetadata() failed to verify: com.google.zxing.pdf417.decoder.BarcodeMetadata com.google.zxing.pdf417.decoder.DetectionResultRowIndicatorColumn.getBarcodeMetadata(): [0xB4] Rejecting invocation, expected 5 argument registers, method signature has 1 (declaration of 'com.google.zxing.pdf417.decoder.DetectionResultRowIndicatorColumn' appears in base.apk!classes2.dex)

version: android 8
Gradle using lib:
com.google.zxing:core:3.3.0
implementation ('com.journeyapps:zxing-android-embedded:4.1.0')  { transitive = false }

thanks

**Comment by srowen** [comment]
You didn't say anything about how this arises. But you are also using a different projects artifacts here
