### ISSUE TITLE
Issue with documentation site.

### ISSUE THREAD

**Issue by endcycles** [zxing/zxing#1463]
I just tried to visit the documentation for the repo to learn more and I am getting 404 error request on every single sub-page from https://zxing.github.io/zxing/

https://zxing.github.io/zxing/core/index.html
https://zxing.github.io/zxing/javase/index.html
https://zxing.github.io/zxing/zxingorg/index.html
https://zxing.github.io/zxing/zxing.appspot.com/index.html

**Comment by srowen** [comment]
Yeah, I'm sorry, I don't know how to get the maven site plugin to generate those. I can't suppress them either. 
There would be no useful info in those subpages anyway - it's really the javadoc that is of any interest. If you know how to fix it open a PR

**Comment by Mohama123** [comment]
Yes you?

در تاریخ جمعه ۲۶ نوامبر ۲۰۲۱،‏ ۲۲:۴۲ Sean Owen ***@***.***>
نوشت:
