### ISSUE TITLE
broken links in documentation

### ISSUE THREAD

**Issue by beta-tester** [zxing/zxing#1466]
hi, there are broken links in `docs/index.html` and where the README.md points to in "[Documentation Site](https://zxing.github.io/zxing/)"
when i click the links on the Documentation Site:
[ZXing Core](https://zxing.github.io/zxing/core/index.html),
[ZXing Java SE extensions](https://zxing.github.io/zxing/javase/index.html),
[ZXing zxing.org web app](https://zxing.github.io/zxing/zxingorg/index.html),
[ZXing Appspot-based encoder](https://zxing.github.io/zxing/zxing.appspot.com/index.html)

or the same local links of the docs folder:
ZXing Core (`./core/index.html`),
ZXing Java SE extensions (`./javase/index.html`),
ZXing zxing.org web app (`./zxingorg/index.html`),
ZXing Appspot-based encoder (`./zxing.appspot.com/index.html`),

![Screenshot from 2021-12-09 17-27-47](https://user-images.githubusercontent.com/4750719/145439457-7c998ef2-cb7c-45a7-a695-c555309f2d7c.png)

i get an **404 - File not found** error.

**Comment by srowen** [comment]
Yeah, see previous issues - I can't figure out how to get the site plugin to generate these. If you can fix it, be my guest. They don't have much useful info anyway; it's the javadoc that matters, really.

**Comment by beta-tester** [comment]
oops, duplicate of #1463,
i did not searched for that issue in closed issues section, because for me it does not looks like a fixed issue.
