### ISSUE TITLE
Unwanted EAN-13 borders since 3.3.1

### ISSUE THREAD

**Issue by knyttl** [zxing/zxing#1470]
### Bug Reports

Since 3.3.1 EAN-13 contains unwanted borders:

<img width="358" alt="Screenshot 2021-12-13 at 9 04 58" src="https://user-images.githubusercontent.com/401107/145774596-6aa7103c-e02c-4476-93d1-5b7c0452d5c2.png">

[HTML source](https://gist.github.com/knyttl/8e8ac13574b05cecb033a30307798c22)

Is this desired? Can this be removed somehow?

**Comment by srowen** [comment]
.. how are you generating this?

**Comment by knyttl** [comment]
```kotlin
class BarCode(text: String) {
    val BASE64_IMAGE_PREFIX = "data:image/png;base64,"

    val writer = EAN13Writer()

    fun toBase64(size: Int? = null) = BASE64_IMAGE_PREFIX + IOUtils.encodeBase64(getImage(size))

    fun stream() = ByteArrayOutputStream().also { writeToStream(it) }

    private fun writeToStream(stream: OutputStream) {
        val config = MatrixToImageConfig(MatrixToImageConfig.BLACK, MatrixToImageConfig.WHITE)
        MatrixToImageWriter.writeToStream(createMatrix(), IMAGE_TYPE, stream, config)
    }

    private fun createMatrix() = writer.encode(text, type, width, height, hints)
}

BarCode("5185247597751").toBase64()
```

**Comment by srowen** [comment]
I think this is on purpose. The barcode requires a minimum quiet zone at the left and right:
https://github.com/zxing/zxing/commit/24681e8488d9a73652ecba9a14b8bc2434ebaade

**Comment by knyttl** [comment]
But shouldn't this be configurable? This does not make much sense when you print it on a white blank background where the paper is essentially whole quiet zone :/

**Comment by srowen** [comment]
I think the library's stance is to generate a barcode that is valid in itself, so you can't configure it to generate something invalid. If printing on white, the white background won't matter. If it's a matter of size and placement, you can deal with that accordingly in your app (or just modify the image programmatically)

**Comment by knyttl** [comment]
but what about setting some `defaultMargin=3mm` to default which could be adjusted? this would require "hacking" of something like `margin: -3mm 0 -3mm 0` in css, which is really ugly especially as it is not clear how big the margin really is.

**Comment by srowen** [comment]
Try passing the MARGIN encoder hint with value 0?

**Comment by knyttl** [comment]
Ok, that helped. Thanks.
