### ISSUE TITLE
Cannot read white qr-codes

### ISSUE THREAD

**Issue by Bommel24** [zxing/zxing#1471]
Cannot read qr codes in this style:

![image](https://user-images.githubusercontent.com/35267552/145828535-9aedb931-152f-4805-b496-0de803a2cf74.png)
(https://google.de)

I use this journeyapps/zxing-android-embedded and i also tried it online at https://zxing.org/w/decode.jspx 
If I invert the image it works.
It seems that the qr code has to be darker than it's background?

**Comment by srowen** [comment]
You have to invert it, yes. QR codes are not white-on-black, technically

**Comment by pzygielo** [comment]
Works for me with option "white on black" set.

**Comment by TokenYc** [comment]
BinaryBitmap invertBitmap = new BinaryBitmap(new GlobalHistogramBinarizer(source.invert()));
if fail，invert it
