### ISSUE TITLE
App barcode reader doesn't work at Samsung S5 mini 

### ISSUE THREAD

**Issue by PSLLSP** [zxing/zxing#1472]
This issue is about ZXing Application for Google  Android

https://play.google.com/store/apps/details?id=com.google.zxing.client.android

I used this application on **Samsung S4 mini** for long time, it works well and I like it. My S4 mini has Android v 4.4.4

I upgraded to **Samsung S5 mini**, I upgraded Android from version 4.4.2 to version 6.0.1. I see that zxing app scanner doesn't work on S5 mini :-( I see barcode in the camera but it is not recognized and decoded. Tested with QR code and CODE-128.

I have found similar report in the zxing forum, S5 mini cannot read barcode.

https://groups.google.com/g/zxing/c/eiT4So8w2ok

S4 mini and S5 mini, both phones run the same version of app, v 4.7.8

I tried your test app

https://play.google.com/store/apps/details?id=com.google.zxing.client.androidtest

It works fine on S4 mini but it crashes on **S5 mini** when I try to get **camera parameters**.

**Comment by srowen** [comment]
Sorry, this app hasn't been supported for years, and I can't update it anymore anyway
