### ISSUE TITLE
NotFoundException hides stack trace

### ISSUE THREAD

**Issue by TWiStErRob** [zxing/zxing#1478]
Bug report: `ReaderException.isStackTrace` is a hand tool to actually get stacks during development/tests. All we need to do is either define that property or reflectively set the boolean.

This works fine for `ChecksumException` and `FormatException`, but `NotFoundException` doesn't use `isStackTrace`, so it actually never has a stack trace. There's no way to know where the error came from.

**Comment by srowen** [comment]
You just want NotFoundException to show stack traces in unit tests? yeah that seems reasonable, not sure why I didn't do that originally. Maybe just that it's so 'routine' that rarely is of interest even in testing.

**Comment by srowen** [comment]
Done in https://github.com/zxing/zxing/commit/491006ac3bbc046f5850f7f40c936e0e81f85274

**Comment by TWiStErRob** [comment]
Stack trace highlights a code path where the failure is, without it we're getting "well, something failed, good luck!", rather than "a using b using c failed to process d", which has a bit more info to start investigation. I couldn't find out (there was literally no way) where to put the breakpoint to investigate the issue more, because of this, luckily I guessed right and found it, but it was quite a surprise. Those Singleton exceptions are a bit strange, never seen anything like this in my 16 years of Java. Thanks for the quick fix. Looking forward to updating the lib.

**Comment by srowen** [comment]
Right, I get that. You can break on the exception in an IDE, but this one gets thrown a lot. It is fine to turn it on in tests.

The motivation for the singletons was to avoid computing the stack trace at runtime, as it's not cheap and exceptions are thrown frequently -- the normal thing that happens is that reader X can't see a barcode in frame Y of a video, happening 100s of times per second. Exception-as-flow-control is actually a good idea for perf here, strangely, as the frequent flow control result is to break from deeply nested code, and it beats thunking a return value in every single location everywhere, code-wise and even perf-wise.

Now the JVM actually does suppress stack traces in many cases automatically for the same reason! but this wasn't true in J2ME in 2007. So this kinda manually forces the behavior for perf reasons.

**Comment by TWiStErRob** [comment]
Ah, it makes sense. From a library design perspective this should be a first class API then. `surefire` is quite a random historical Java library. Many of us use Gradle and JUnit 4, JUnit 5 or TestNG. Android Instrumentation tests use JUnit 3 or 4 too.

For now I just put this into my `AndroidJUnitRunner` initialization to prevent us future headaches:
```kotlin
        // We want stack traces in all our exceptions, otherwise when it fails we have no clue what happened.
        com.google.zxing.ReaderException::class.java
            .getDeclaredField("isStackTrace")
            .apply { isAccessible = true }
            .set(null, true)
```
The disclaimer is that this app is rendering and scanning barcode images rarely, not handling streams of images / videos.

**Comment by TWiStErRob** [comment]
Btw, any idea on the timeline of 3.5.0? I see the milestone is done, but I guess you're just using that to keep track, not as a planner.

**Comment by srowen** [comment]
Maybe, it's not intended to be enabled in general, except for possible debugging. You can set the env variable manually, or I can add support for other standard ones if you know what they are, or I could add a custom new one, but might not make much difference. Just System.setProperty? no need for reflection.

**Comment by srowen** [comment]
Oh, maybe it checks too early to set the system property programmatically. You can set in your invocation of the test harness with -D too, but this could work fine too. I could expose a static for-testing-only method to set it

**Comment by srowen** [comment]
Yeah, releases are probably once a year at best, but it's overdue, so was going to cut one once another contributor's recent changes are all in. Soonish.

**Comment by TWiStErRob** [comment]
Yeah, but that's quite random, a property that's unrelated to anything. I chose reflection, because if something changes it'll break and would need to adjust it, similar to public API changes. If the property handling changes, there would be no sign of it not working any more.

**Comment by srowen** [comment]
It's meant to auto-trigger when run in a testing harness; not random. I'm suggesting it was never intended to be enabled by anything but unit test harnesses, but, could have it look for signs of other harnesses. Or if you really have a use case for enabling it explicitly, can add a method to do that, but seems easier where possible to just turn it on in the presence of your test framework if it's detectable

**Comment by TWiStErRob** [comment]
The use case is Android Instrumentation tests using ZXing to verify barcodes in UI tests. If they fail to verify we get a stack trace on CI, which might not be reproducible locally, so we need the most information available. One of the main information sources is the stack trace for UI tests, and they're very long and complex going through 2 thread boundaries. I raised this issue because we got errors, but couldn't find the root cause without some serious hacking around and debugging, which would've been much easier if had the traces.

JUnit and AndroidTest would be two frameworks you could detect, not sure how though (maybe Class.forName?). If I were you I would just open up the API and let the user opt-in, rather than maintaining an all-detecting magic constant in `ReaderException`.

**Comment by srowen** [comment]
Yeah I'll just add a method you can call explicitly, as that's probably tidier than a system property (and that exists just to autodetect an existing test harnesses)
