### ISSUE TITLE
CameraConfigurationUtils not defined in CameraConfigurationManager

### ISSUE THREAD

**Issue by bustedware** [zxing/zxing#148]
CameraConfigurationUtils.java appears to be missing from project and I can't find it anywhere in src after redownloading to make sure. Has this somehow gone missing?

**Comment by mertemin** [comment]
Add CameraConfigurationUtils.java that is under android-core/src/main/java/com/google/zxing/client/android/camera/ to your build path (or simply copy it and paste it to your-app-name/app/src/main/java/com/google/zxing/client/android/camera/).
