### ISSUE TITLE
C++ Zxing library cannot read qr code generated by qrencode correctly throw: Zxing ::ChecksumException  

### ISSUE THREAD

**Issue by twisezz** [zxing/zxing#1487]
I am using the C++ zxing library and want to read the qr code generated using the qrencode library.  But the width and height of the image can only be retrieved each time, but the data can not be correctly read, and throws:  Zxing ::ChecksumException, the two-dimensional code found on the network is not this problem, and I will qrencode generated two-dimensional code on Zxing Decoder Online can also be correctly read.  I found some Java and android solutions here, but since I haven't been using C++ long enough, I can't convert the solution to C++ mode.  So I hope to get some C++ solutions here, thank you!  

`int main() 
{

	string image_name = "C:\\Users\\Public\\Documents\\aa.jpg";
	Mat matSrc = imread(image_name, 1);
	if (!matSrc.data) {
		fprintf(stderr, "read image error: %s", image_name.c_str());
		return -1;
	}

	cv::Mat matGray;
	cv::cvtColor(matSrc, matGray, CV_BGR2GRAY);

	Ref<LuminanceSource> source = MatSource::create(matGray);
	int width = source->getWidth();
	int height = source->getHeight();
	fprintf(stderr, "image width: %d, height: %d\n", width, height);

	Ref<Reader> reader;
	reader.reset(new qrcode::QRCodeReader);

	Ref<Binarizer> binarizer(new GlobalHistogramBinarizer(source));
	Ref<BinaryBitmap> bitmap(new BinaryBitmap(binarizer));
	DecodeHints d;
	d.setTryHarder(true);
	DecodeHints shints = d.getTryHarder();
	Ref<Result> result(reader->decode(bitmap, zxing::DecodeHints::QR_CODE_HINT));
	string qrdata = result->getText()->getText();
	cout << qrdata << endl;
}`

#https://github.com/zxing/zxing/issues/995
my QRcode：
![aa](https://user-images.githubusercontent.com/98145904/150480254-9caf0fc4-c23e-4646-8aa9-6e1470319365.jpg)

**Comment by axxel** [comment]
The "original" c++ port of ZXing has long been deprecated and removed from the repository. I suggest you have a look at https://github.com/nu-book/zxing-cpp, which is the most up-to-date and active c++ port of ZXing at the moment and it decodes your sample just fine.
