### ISSUE TITLE
Barcode scanner has invalid signature 

### ISSUE THREAD

**Issue by needsomehelpplease** [zxing/zxing#1488]
When i try to use this app to scan a barcode  through another app called SAP authenticator i wil not work. It works alone, buy not with the SAP app. How to fix this?
![Screenshot_20220121-143908_Authenticator](https://user-images.githubusercontent.com/96019091/150536996-c9c2eff1-17dd-4113-9788-e85b64de99de.jpg)

**Comment by srowen** [comment]
I don't know, the app is officially available through Play, and is signed correctly with my developer key. You may have some copy of the app built by someone else, or other requirement for this app due to other software. Not related to the project.

**Comment by needsomehelpplease** [comment]
Isee,thanks for your time
