### ISSUE TITLE
FR: Extending raw data display with raw error correction codes

### ISSUE THREAD

**Issue by Sturwandan** [zxing/zxing#1489]
I need an android application, which can read 2D barcodes and not only provide the decoded data (there are plenty of apps which do that), but also provide the raw data including data bytes and error correction bytes. Unfortunately, raw data provided by Barcode Scanner only includes data bytes and not error connection bytes.

I think it should be pretty trivial extension, so I would like to risk leaving a feature request without a PR, because I know very little of android programming if anything at all.

Also, if there is already an open source app which can show raw data read from a barcode, including error correction bytes, I would be grateful for a suggestion.

**Comment by srowen** [comment]
The EC bytes are not really 'separate' from the data bytes, so not exposed in the results provided by the library. You are welcome to hack the code to do whatever you want of course, but no I don't see value in exposing this in general.
