### ISSUE TITLE
'Barcode Scanner' application has invalid signature. Please reinstall it from a verified store.

### ISSUE THREAD

**Issue by Boskizus31** [zxing/zxing#1497]
When using "Authenticator" app from SAP, we are getting the following message:
«_Install Barcode Scanner?

This application requires Barcode Scanner. Would you like to install it?_»

After downloading "Barcode Scanner" app from Play Store and setting it up, and accessing "Authenticator" app once again, the following error message is obtained:
«_Cannot scan a QR code

'Barcode Scanner' application has invalid signature. Please reinstall it from a verified store._»

With this being said, we are kinda stuck in here as we are not being able to move forward while using "Authenticator" app.

Moreover, accessing directly "Barcode Scanner" app we immediately receive the message below:
«_Barcode Scanner

This app was built for an older version of Android and may not work properly. Try checking for updates or contact the developer._»

On the message we also have at the bottom 2 buttons: "Check for update" & "OK". When clicking on the 1st one we are redirected to "Barcode Scanner" Google Play page, in which we notice the app is up to date and it was last updated on 9 Sept 2018.

FYI my Android version is 12.

Any help or guidance is appreciated here. Thank you in advance.

Best regards,

**Comment by Boskizus31** [comment]
Hello @srowen,

Please note I am using Google Play Store and not another store.

I have downloaded both apps from there.

Therefore, please return back once possible considering the feedback above.

Thank you.

Best regards,

**Comment by srowen** [comment]
I can't reproduce that, works fine for me. The app has not changed in years, and have not heard any reports of this. Something else in your system is the problem - something side-loading or modifying sigs or something

**Comment by oehhar** [comment]
Boskizius31, please read carefully the error message you got.
This app is for an older version of Android.
That is true.
If this is the SAP criteria, the App is out as expected.
zxing will not change this, sorry.

Take care,
Harald
