### ISSUE TITLE
Cannot detect QR code printed on wood surface

### ISSUE THREAD

**Issue by kim-ninh** [zxing/zxing#1499]
Hi, I try to scan these QR codes in **Barcode Scanner+** and https://zxing.org/ but had no success. Any suggestion for this type of QRCode? Thanks.

![1](https://user-images.githubusercontent.com/28674990/152804573-e6443c9c-3300-48e1-aab1-01e392902530.jpg)
Case 1

![2](https://user-images.githubusercontent.com/28674990/152804581-4a36637a-2962-4ac0-aa0f-f5e7b8f4c217.jpg)
Case 2

![3](https://user-images.githubusercontent.com/28674990/152804585-c920c2df-bf72-4519-be8a-5489672359a4.jpg)
Case 3

**Comment by srowen** [comment]
I think the problem is not enough dark/light contrast in those QR codes. The last one is technically not valid (missing enough white space around border) and others are slightly distorted in other ways for artistic purposes, but that make it harder to read. Not a bug
