### ISSUE TITLE
QR Decoder and guessing encoding of Byte Mode

### ISSUE THREAD

**Issue by pictview** [zxing/zxing#1500]
The attached image contains 8859-1 string "ééécéé jj", but actually the CJK string "鳬馗鳬 jj" is decoded.
When I check decodeByteSegment() in DecodedBitStreamParser.java, I see the following comment:
     // The spec isn't clear on this mode; see
      // section 6.4.5: t does not say which encoding to assuming
      // upon decoding. I have seen ISO-8859-1 used as well as
      // Shift_JIS -- without anything like an ECI designator to
      // give a hint.
And then StringUtils.guessCharset() is called. This function prefers ShiftJIS over 8859-1.
I believe the interpretation of the specification is wrong:
* 5.1: byte data (default: ISO/IEC 8859-1; or other sets as otherwise defined (see 6.3.4));
* 6.3.1: The default interpretation for QR Code 2005 is ECI 000003 representing the ISO/IEC 8859-1 character set.
* 6.3.4: In closed-system national or application-specific implementations of QR Code 2005, an alternative 8-bit
character set, for example as defined in an appropriate part of ISO/IEC 8859, may be specified for Byte mode.
When an alternative character set is specified, however, the parties intending to read the QR Code 2005
symbols require to be notified of the applicable character set in the application specification or by bilateral
agreement.
* Section 6.4.5 "Byte mode" talks about the Byte encoding, but not about its interpretation at all.

So, for this generic tool, I believe 8859-1 should be either assumed or preferred.

<img width="314" alt="QR_Latin1" src="https://user-images.githubusercontent.com/87663700/153178042-f60b5bee-e09b-4adf-9d3d-ce20e828abbf.png">

**Comment by srowen** [comment]
You are definitely correct that the default interpretation of byte segments is ISO-8859-1, and other interpretations should be signaled with an ECI segment. In practice, oh boy, there are so many QR codes in Japan that just put Shift_JIS in it, and plenty that just put in UTF-8. Hence guessing is necessary in practice, I found. There's no way to get this 100% correct as some byte sequences will also look like valid Shift_JIS.

If you have a change to the heuristic it uses that would make this work and almost surely not break existing guesses (at least tests pass) I'd take a look. If you're encoding these, you can also use UTF-8 and an ECI segment, UTF-8 with a BOM, or an ECI specifying ISO-8859-1 and it should work out.
