### ISSUE TITLE
A new release soon?

### ISSUE THREAD

**Issue by Altonss** [zxing/zxing#1513]
Hello,
First of all, thanks for this great project!
I know it's in maintainance mode only, but do you know when you will release the next version containing the latest merged pull requests?
Thanks for your answers :)

**Comment by srowen** [comment]
@AlexGeller1 any more changes coming soon in the pipe? if not I think we're pretty good to cut a release soon

**Comment by AlexGeller1** [comment]
>any more changes coming soon in the pipe?
I have a fix for #1163 (It is just a guard against input characters > 255 as the algorithm isn't prepared to handle those). I would quickly make a PR for that. Besides that I would like to see PR #1498 merged, if possible. It is 100% backward compatible if I remember correctly.

**Comment by srowen** [comment]
I think I'd like to go ahead with a release; we're at a relatively stable point

**Comment by Altonss** [comment]
Thanks a lot for the new release!
