### ISSUE TITLE
Hello, are there plans to generate the DataMatrix with a forced C40 encoding ?

### ISSUE THREAD

**Issue by Alung90** [zxing/zxing#1519]
Hello, are there plans to generate the DataMatrix with a forced C40 encoding ?
Why not add a parameter that allows you to choose the exclusive encoding type in the DataMatrixWriter and encodeHighLevel class ?
Thanks

_Originally posted by @glassglass in https://github.com/zxing/zxing/discussions/1462_

**Comment by AlexGeller1** [comment]
The latest release has the option to force C40 encoding (see https://zxing.github.io/zxing/apidocs/com/google/zxing/EncodeHintType.html#FORCE_C40)
