### ISSUE TITLE
[Android] Sometimes zxing detect floor, table or nothing as a Barcode

### ISSUE THREAD

**Issue by voliothonh** [zxing/zxing#1528]
If I keep the Android camera facing a table, floor, sheet of paper, or whatever, for about 20 - 40 seconds it will get 1 result as a 1D BarCode.
The results are different every time, not the same
I've never seen it misrepresent as a 2D code
I've searched a lot of issues on github and stackoverflow but haven't seen anyone reporting the same error.
Hope you can reproduce this bug and fix it soon. 

**Many thanks for awesome library.**

**Comment by AndrewDavydenko** [comment]
have the same issue! thanks!

**Comment by srowen** [comment]
This has come up a bunch of times. With enough input frames, something will look enough like a simple barcode that it will scan. The main problem is that some possible formats do not have a checksum and it's easy to get a false positive. You're still welcome to improve heuristic change, but 99.9% of the time it hurts scanning actual barcodes, because 99.9% of the time you're not pointed at the floor.

**Comment by axxel** [comment]
Maybe I can offer an 'easy' way out: I suggest you have a look at https://github.com/nu-book, which is the most recent c++ port of ZXing. It comes with an android wrapper including a kotlin demo app. Inside the demo app, there is even a "Java" button to witch between the c++ and the java version of the project for easy comparison. The point is, I've re-implemented most part of the 1D barcode detection and made it substantially faster and more reliable in terms of false-positive detection. No guarantee, though, that you get 0 false positives with your input but certainly a lot less.

**Comment by voliothonh** [comment]
> Maybe I can offer an 'easy' way out: I suggest you have a look at https://github.com/nu-book, which is the most recent c++ port of ZXing. It comes with an android wrapper including a kotlin demo app. Inside the demo app, there is even a "Java" button to witch between the c++ and the java version of the project for easy comparison. The point is, I've re-implemented most part of the 1D barcode detection and made it substantially faster and more reliable in terms of false-positive detection. No guarantee, though, that you get 0 false positives with your input but certainly a lot less.

Thank for suggestion.
I tried it, and it seems to run pretty fast.
But it still seems to be missing a few features such as: detecting multiple codes on 1 bitmap (yes on py, android doesn't).

**Comment by axxel** [comment]
> But it still seems to be missing a few features such as: detecting multiple codes on 1 bitmap (yes on py, android doesn't).

Correct. This could be fixed relatively easy, though. If you care to get involved, please open a new issue and we can continue the discussion there.

**Comment by zaheerrasheed** [comment]
facing same issuer
