### ISSUE TITLE
Unable to scan this QRCode

### ISSUE THREAD

**Issue by kim-ninh** [zxing/zxing#1530]
I'm unable to scan this QRCode by using Barcode Scanner app or zxing.org. Could anyone tell me what is a problem with this code?
Thanks.

![0f946d31587d9823c16c](https://user-images.githubusercontent.com/28674990/169640346-50e67ab3-b1d3-4415-9a35-2841a118082c.png)

**Comment by axxel** [comment]
I've run it through zxing-cpp and that fails as well with a checksum error, even though the sampling works perfectly. I noticed that the error correction level is `Low`. It might be that the 'A08' overlay with this EC-level is simply too much for the error recovery to work. Meaning this symbol is simply unreadable and always was.

**Comment by kim-ninh** [comment]
> I've run it through zxing-cpp and that fails as well with a checksum error, even though the sampling works perfectly. I noticed that the error correction level is `Low`. It might be that the 'A08' overlay with this EC-level is simply too much for the error recovery to work. Meaning this symbol is simply unreadable and always was.

Did you mean the QRCode itself is corrupted somehow? I see this message "Error locator degree does not match number of roots" from the exception and have no idea what is going wrong :((((

**Comment by axxel** [comment]
Yes this QRCode symbol is corrupted. All symbols with something printed "over them" like the white circle with the text `A08` here are technically corrupted. But if the error correction level is high enough such that the remainder of the symbol contains enough valid information for the missing part to be reconstructed, then the symbol can still be decoded. Here too much data missing for such a `low` EC-Level.

My interpretation: the creators of this symbol did not know what they were doing.

**Comment by kim-ninh** [comment]
I still have a question. So if this QRCode symbol is actually corrupted, we should never ever be able to scan it right?.  When I try slowly moving the camera far away from the image. At the moment, the app is still able to scan it (but with a lot of effort).  So my question is why I am still able to scan it when moving far away from the image? 

https://user-images.githubusercontent.com/28674990/169653089-163cb27d-de2f-4415-b9cf-4650232d8222.mp4

**Comment by srowen** [comment]
My guess is that it is corrupted, but with a little luck it reads/misreads parts in just a way that it happens to work. Error correction depends on how much was read correctly

**Comment by axxel** [comment]
In support of @srowen:

![#1530-grid](https://user-images.githubusercontent.com/1038346/169653667-b60c69a5-585c-4018-8b22-c3144fd54bf2.png)

The blue dots are the precise location where the image is sampled. You can see that some which are on white because of the overlay come very close to some black pixels. If you move the camera, the precise location of the sampling grid varies slightly and you might end up with maybe just 1 bit that gets sampled black instead of white and that might already be sufficient.

**Comment by kim-ninh** [comment]
In my understanding, the overall process is like this: detect 3 finder patterns and the alignment pattern. After that, we have the location of 4 points and then map those points into a square using PerspectiveTransform. So when I move the camera, the points after mapping varies which leads to the sampling grid varying too, right? So we can have a little luck that on the sampling grid, some part in the text "A08" is black pixels which is actually the correct value, and Error Correction is now able to recover the whole wrong value part. Correct me if I misunderstood.

**Comment by kim-ninh** [comment]
Well, when I try to remove the text "A08" and leave the overlay just a white background, I expected I couldn't scan it but the result is the same. Can we somehow modify the image so that we could never be able to scan it?

![phothin_02](https://user-images.githubusercontent.com/28674990/169678004-c7f06202-2231-488d-9cfa-c1198df14b93.jpg)


https://user-images.githubusercontent.com/28674990/169678011-1380eb68-7349-41fb-b2fa-59047da38743.mp4

**Comment by axxel** [comment]
> Can we somehow modify the image so that we could never be able to scan it?

Absolutely: simply make the white circle even larger or paint over some untouched white modules with black. I guess only very few additional corrupted modules will completely break the symbol.
