### ISSUE TITLE
Replace hostname "zxing.org" with "chart.apis.google.com" for generator's QR codes to load

### ISSUE THREAD

**Issue by seb1100xx** [zxing/zxing#1537]
With generator, the QR codes won't load from "zxing.org" hostname, but it works with "chart.apis.google.com"

https://github.com/zxing/zxing/blob/99e9b34f5afc21fdaeead283d5ed0bc1314cbec1/zxing.appspot.com/src/main/java/com/google/zxing/web/generator/client/Generator.java#L201

**Comment by srowen** [comment]
Oh, it will work, just the server keeps crashing. I'll restary
