### ISSUE TITLE
Code128 ResultPoints return incorrect values

### ISSUE THREAD

**Issue by kkondratov** [zxing/zxing#1540]
Currently the Code128Reader reader is providing a Result information with incorrect coordinates at where the code starts and ends.

Taking the following barcode as an example:
<img width="285" alt="foobar" src="https://user-images.githubusercontent.com/4076121/176904913-ae7b1818-0b2d-44ba-bcc0-f402ce9d0f23.png">

I'm getting the following results: 
```
{
    "text": "foobar\n",
    "rawBytes": "aEZPT0JBUmVKQWo=",
    "numBits": 88,
    "resultPoints": [
    {
        "x": 59,
        "y": 122
    },
    {
        "x": 499,
        "y": 122
    }],
    "resultMetadata": {
        "SYMBOLOGY_IDENTIFIER": "]C0"
    },
    "timestamp": 1656682389903,
    "barcodeFormat": "CODE_128"
}
```

Now the result point 1 is [59,122], which is in de middle of the Code128 start pattern, not the start of the actual data nor the start of the barcode.

Looking at decodeRow method Code128Reader, the startPatternInfo is found first and the code is decoded. This is all correct, however at the end where the result is constructed the left and right (which are the points returned in the result) are calculated based on the startPatternInfo. 

In this case left is calculated as `(startPatternInfo[1] + startPatternInfo[0]) / 2.0f;` here the `startPatternInfo[0]` has the actual position (albeit 1 pixel off in the example) of the barcode left coordinate. 
Right is calculated as `lastStart + lastPatternSize / 2.0f` which is also incorrect, since it results in the middle of the CODE_STOP of the Code128. 

The fix for the left is straightforward, either use startPatternInfo[0] or "calculate it" based on startPatternInfo[1] and startPatternInfo[2] (`startPatternInfo[2] - startPatternInfo[1]`) which results in the same value as `startPatternInfo[0]`;

From debugging info the startPatternInfo has the following values:

```
startPatternInfo[0] = 37
startPatternInfo[1] = 84
startPatternInfo[2] = 101
```

The fix for right requires more investigation.

**Comment by srowen** [comment]
Do you have a change to propose, that doesn't break any of the existing tests and makes this pass?
Nobody is otherwise working on this.

**Comment by srowen** [comment]
It's looking for a line across the image that looks like a 1D barcode. It finds the start and end of the start/stop pattern. What it returns as metadata is the midpoint, I believe; it's there more for a UI. Is that all you're asking, what the result points "mean" in this case? I think it's on purpose, or at least, no more or less logical than anything else I could think of such that the semantics are kinda consistent with other barcodes.

**Comment by kkondratov** [comment]
@srowen I think you misunderstood my question. When the Result object is returned for 1D barcodes. What is expected as ResulPoint values?
Are these:
1. Outer boundaries, most left point and most right point of the barcode (start/stop code included)
2. Inner boundaries, left point is the start of the data excluding the start code, right is the end of the data excluding the stop code

I don't know exactly what other codes return yet, haven't tested/read the code. Hence the question :)

**Comment by srowen** [comment]
They are points along a line that cuts across the barcode. The points are the midpoint of the start/stop of the start code, and end code symbol. You got that much from the code, yes. What are you trying to do?

**Comment by kkondratov** [comment]
@srowen I’m in need of the outer boundaries of the barcode. Because I need to reconstruct the actual bounding box of the barcode. Basically we need to scan an image, extract the code, and provide a printer with specific barcode printing instructions. This due to the quality of the original image we’re getting and the printer that can not print high enough quality barcode from the original image.

Could you explain why its the midpoint of the start/stop of the start code, and end code symbol, and not outer edges of the barcode?

Looking at PDF417 (one other barcode we’re using), the result points contain the outer boundaries of the box and inner boundaries of the data of the qr code.

**Comment by srowen** [comment]
Ah the 1D readers do not look for a bounding box. They just look for a line across that registers as a barcode. 

The 2D readers do. You'd have to use the library at a lower level, but you can emulate what they do. See the "Detector" implementations as used in the 2D decoders like QR code.

If you just need an equivalent barcode, you could consider regenerating the barcode given the contents. But if you need the original image, mapped to a rectangle, you'd have to detect it, yeah.

Why are the returned result points what they are? What constitutes an 'important' point on the image depends on the use case, I guess. Many points are detected, but many seem pretty implementation and format specific. For example - the start and end of the start pattern are detected, but, does the caller care? the use case I had in mind was UI feedback. Here is where in the image the barcode we found starts and ends. You can see this in the Barcode Scanner library - it determines what line or box is drawn.

Why aren't there corner points for code 128? sure, not unreasonable, as the "1D" barcode is in fact rendered as a 2D rectangle. But it isn't detected or read this way and so it isn't computed to return. Just the start/end of where it was found.

PDF417 is truly "2D"; you need to find the whole rectangle, not just a line cutting across it. So it does and reports those corners.

Lower level use cases need to hack a little deeper into the code to get more info out.

**Comment by kkondratov** [comment]
@srowen Thank you for a detailed explanation :)

> Ah the 1D readers do not look for a bounding box. They just look for a line across that registers as a barcode.

That is definitely reasonable and I assumed that’s the case, its not necessary to know the bounding box for detection, thus why provide that info.

> The 2D readers do. You'd have to use the library at a lower level, but you can emulate what they do. See the "Detector" implementations as used in the 2D decoders like QR code.

Yes, thank you, I’ve spotted that indeed , which is useful for our scenarios.

> Why are the returned result points what they are? What constitutes an 'important' point on the image depends on the use case, I guess. Many points are detected, but many seem pretty implementation and format specific. For example - the start and end of the start pattern are detected, but, does the caller care? the use case I had in mind was UI feedback. Here is where in the image the barcode we found starts and ends. You can see this in the Barcode Scanner library - it determines what line or box is drawn.

I definitely agree with the fact that it is very implementation specific, and indeed does the caller care or not. I guess I need to dig into the BarcodeScanner library why its the center of the start/end code.

> Why aren't there corner points for code 128? sure, not unreasonable, as the "1D" barcode is in fact rendered as a 2D rectangle. But it isn't detected or read this way and so it isn't computed to return. Just the start/end of where it was found.

I totally understand why the 2D rectangle is not returned (that’s something we have to detect ourselves). 

Why the coordinates are the mid points of start and end points is what confuses me. Based on those coordinates alone I’d have to detect the actual start point, and the actual endpoint. I guess that comes back to the BarcodeScanner library where those points are used in UI as you’ve explained (I’ll have a look to get a better grasp).
Hence the initial issue, I’d expect to have gotten the outer boundaries of the 1D line (begin of the start code, end of end code).

I’d like to create a PR to include those two points in the result as well if that’s okay with you? That will save processing and figuring that data on our end, and if its already present during detection then its easier to get that info. Either in the ResultPoints or add it as Metadata (to not affect any existing tests, I’d need to investigate what the best approach is here).

**Comment by srowen** [comment]
I don't think there's a strong reason for the midpoint vs the outside. It's the 'center' of the start code. It didn't make as much sense to return 2 points to me. By analogy, I think you get the centers of the finder patterns in QR codes? maybe misremembering.

Why do you want the outer boundary if you already detect it separately?
I'm not sure there's a compelling reason to change the behavior in the library. I'd go for it if the behavior hadn't existed for so long. I just hesitate to change any behavior because this is in mainteance mode.

**Comment by kkondratov** [comment]
Regarding the PD417 results there are 8 points returned, the bounding box and the codewoord area.

```
PDF417DetectorResult detectorResult = Detector.detect(image, hints, multiple);
    for (ResultPoint[] points : detectorResult.getPoints()) {
DecoderResult decoderResult = PDF417ScanningDecoder.decode(detectorResult.getBits(), points[4], points[5], points[6], points[7], getMinCodewordWidth(points), getMaxCodewordWidth(points));
      Result result = new Result(decoderResult.getText(), decoderResult.getRawBytes(), points, BarcodeFormat.PDF_417);
…..
```

> Why do you want the outer boundary if you already detect it separately?

We don’t detect it yet, we were thinking of using the provided information by this amazing library to figure out and calculate the actual bounding box. Seeing that 2D bounding box is provided, there is no need for that.
For 1D it would be useful to have the outer boundaries as well, then the bounding box is easy. If we had the inner box (not the center of start code) then its also easy to figure out. However since its the center of the start code and center of end code its a tad bit more difficult (especially because the end code doesn’t have the same length as startcode, otherwise it would’ve been easier to calculate).

The easiest way for me to go at the moment is shadow the class and add that information from the calculated results during code detection. 

Seeing its nowhere documented and unclear why the result points are center of the start code and center of end code for Code128 it hard to understand without your explanation. That’s why I was proposing to add it as a PR.

If you say that it’s not a bug, then I need to figure out a different approach :)

**Comment by kkondratov** [comment]
Just to add to the previous comment, from your explanation it is clear why these points exist now (because there is a caller that uses them to draw things in the UI).

From a usage/library design point of view I would’ve gone with a different approach, because the core library is very useful outside of the UI library as well. Hence I would’ve provided more information (not just mid points of start and end codes), and based on the type of code, determine if I need the 1D data or 2D data extracting it from the result points. And UI should figure out if it wants to draw a line through the 90% of the code or 100% or what it needs.

Either way I’m closing this issue because as you’ve said the library is in maintenance mode and adding this behaviour is going to change behaviour of dependencies. I’m going to figure out a different approach.

Once again thank you for your help and explanation!

**Comment by axxel** [comment]
Just name one alternative that might work a bit better for your application: https://github.com/nu-book/zxing-cpp

During reimplementation of all the 1D codes, I opted for returning 'everything except the quite zone' as the position of any barcode, that mostly means 'from the first black pixel to the last black pixel'. Generally, you still have the limitation that you don't get the full bounding box. But if you used the `ReadBarcodes` (multi-barcode version) function and your symbols are properly detectable and horizontally aligned you do in fact get pretty much exactly that:
![out](https://user-images.githubusercontent.com/1038346/176977487-051910bb-1ef2-4d4e-af28-90baed7692c6.png)
.

**Comment by srowen** [comment]
I can look at returning some other metadata that's like 'all points the implementation happened to find, in some impl specific order' maybe. And leave the current return value as is as a sort of 'key human readable locations' Adding a bit of extra existing info to the return seems OK

**Comment by kkondratov** [comment]
@axxel  thank you i'll have a look at that implementation :) the advantage we have is that our barcodes are always perfectly aligned. We're not scanning from the "real world" but get a perfectly aligned label so the problem space is a lot easier.

@srowen That would be great, but i'll leave it up to you. As you've said the library is in maintenance mode and only bug fixes are included.

**Comment by axxel** [comment]
In that case, you should get near perfect results and if you don't, please let me know and I'll see what can be done about it.

**Comment by kkondratov** [comment]
@axxel ah i see in the `ODReader` you return a `Results` object that merges "multiple" OneD results to determine the bounding box based on the found data.
