### ISSUE TITLE
Maxicode incorrect char mapped to Set A index 0 (CR vs LF)

### ISSUE THREAD

**Issue by gredler** [zxing/zxing#1543]
It appears to me that although the specification for Maxicode specifies that character "CR" (carriage return, ASCII 13) maps to Set A index 0, the set table at `com.google.zxing.maxicode.decoder.DecodedBitStreamParser.SETS` instead maps "LF" (line feed, ASCII 10) to this position. Per the spec, the only way that "LF" should be encodable is via Set E index 10.

Because of this defect, some symbols which encode "\r" are decoding to "\n" instead.

![image](https://user-images.githubusercontent.com/178883/179650919-88863bf8-fd93-45fc-b9c9-f9c00c430741.png)

**Comment by srowen** [comment]
I think you're right, looks like a typo. If you want to open a PR, go for it, or I can do it tomorrow.

**Comment by gredler** [comment]
Will do, thanks for the quick review.
