### ISSUE TITLE
How to get original bytes from QR code.

### ISSUE THREAD

**Issue by SurajBahadur** [zxing/zxing#1546]
I'm using [LVGL](https://docs.lvgl.io/master/libs/qrcode.html) library to generate the Qr code.

```
uint8_t test[150];
uint8_t testSize = 140;

for (unint8_t i = 0; i< testSize; i++)
{
   test[u] = i;
}

lv_qrcode_update(qr,test,testSize); //for generating qr code
```
<img width="250" alt="lgvl" src="https://user-images.githubusercontent.com/19315803/180049342-4ef73e72-04af-4aee-841f-780bdef0403d.png">

After scanning the QR code, it gives me result i.e
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{|}~�

but in actual is should return numbering from 0 to 140. 
Secondly, if I query for raw bytes then it gives

`[64, 11, 0, 0, 16, 32, 48, 64, 80, 96, 112, -128, -112, -96, -80, -64, -48, -32, -15, 1, 17, 33, 49, 65, 81, 97, 113, -127, -111, -95, -79, -63, -47, -31, -14, 2, 18, 34, 50, 66, 82, 98, 114, -126, -110, -94, -78, -62, -46, -30, -13, 3, 19, 35, 51, 67, 83, 99, 115, -125, -109, -93, -77, -61, -45, -29, -12, 4, 20, 36, 52, 68, 84, 100, 116, -124, -108, -92, -76, -60, -44, -28, -11, 5, 21, 37, 53, 69, 85, 101, 117, -123, -107, -91, -75, -59, -43, -27, -10, 6, +116 more]
`

Is there any way to get the original byte?

**Comment by srowen** [comment]
You are asking about a different port of this library.
In this library, yes you get the raw bytes as extra result metadata.
Note that you are trying to interpret the bytes as numbers, when the QR code by nature encodes text (so the result is correct). However you can do what you like.

**Comment by SurajBahadur** [comment]
@srowen Thank you for your quick reply and I agree with you. Is there any other way apart from this library to get original value that passed while generating the QR i.e 0 to 140.

**Comment by axxel** [comment]
> Is there any other way apart from this library to get original value that passed while generating the QR i.e 0 to 140.

You could use the most recent c++-port https://github.com/nu-book/zxing-cpp. I just recently put a lot of effort in improving the 'binary' data use-case (see https://github.com/nu-book/zxing-cpp/issues/334 for an elaborate discussion about the topic). You would want to access the `Result::bytes()` member to retrieve what you are looking for. I tested your code and believe it is scanned just as you would expect.
