### ISSUE TITLE
Inconsistent QR Code decoding

### ISSUE THREAD

**Issue by DieterDeRo** [zxing/zxing#1553]
On my project we use ZXing for integration testing. About one in 5 tests fail due to ZXing running into a NotFoundException of ChecksumException. All QR codes are of the same format. I will add 3 of them into this message. One of them passes the scan, one causes a ChecksumException and another causes a NotFoundException.

We send these screenshots using the following code:

```
public String decodeQRCode(final BufferedImage bufferedImage) {
    final LuminanceSource source = new BufferedImageLuminanceSource(bufferedImage);
    final BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
    try {
      final Map<DecodeHintType, Object> hints = Map.of(
          DecodeHintType.TRY_HARDER, true
      );
      return new QRCodeMultiReader().decode(bitmap, hints).getText();
    } catch (final NotFoundException | FormatException | ChecksumException e) {
      throw new RuntimeException("QR code not found", e);
    }
  }
```
checksumexception:
![checksumexception1](https://user-images.githubusercontent.com/108527350/185068447-6cfafa73-f5f4-45f4-bf81-e97587e73507.png)
notfoundexception:
![notfoundexception1](https://user-images.githubusercontent.com/108527350/185068455-e2418b4d-30ac-4965-adb8-481c16f18531.png)
success:
![testpassed1](https://user-images.githubusercontent.com/108527350/185068456-e3b6fc48-f7ce-4c0e-b29f-eff202fcd173.png)

**Comment by srowen** [comment]
These all seem to decode fine in the online decoder: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F108527350%2F185068455-e2418b4d-30ac-4965-adb8-481c16f18531.png

I don't look at 'this won't decode' issues in general. compare the online decoder source with what you're doing. Maybe you want a different binarizer, or maybe the 'pure barcode' mode is succeeding here
