### ISSUE TITLE
QR Code Scans on zxing.org, but not in BrowserQRCodeReader

### ISSUE THREAD

**Issue by wisefool769** [zxing/zxing#1556]
The following QR code scans in the zxing.org webapp, but it throws a CheckSumException when using BrowserQRCodeReader. I have tried using DecodeHintType.TRY_HARDER to no avail. This is a Solana Pay URI as specified here: https://github.com/solana-labs/solana-pay/blob/master/SPEC.md . 

Do you have any recommendations for me?

<img width="541" alt="localhost_3000_qr" src="https://user-images.githubusercontent.com/3916546/186522718-44af280a-eb2d-42da-803b-2abe53c777e4.png">

**Comment by srowen** [comment]
You can look at the source code in the project, find DecodeServlet. It tries different binarizers, pure barcode mode, etc. Maybe one of those works.
