### ISSUE TITLE
Unable to decode DM code which consists of points

### ISSUE THREAD

**Issue by MioChiu** [zxing/zxing#1565]
I find it difficult to decode these kinds of twoD code composed of points. What can I do to make it easier?
Thanks.
![image](https://user-images.githubusercontent.com/42037320/197970250-01f0bdc1-64f1-4147-b959-589a1a869987.png)

**Comment by srowen** [comment]
Hard to decode. It's inverted, so you need to enable inverted scanning in the app or try inverting the image. The dots are disconnected which is problematic too. No one answer here
