### ISSUE TITLE
The library is hanging when processing a triggering image

### ISSUE THREAD

**Issue by hauck-jvsh** [zxing/zxing#1567]
As said before in #1541, we integrate this library in another project (https://github.com/sepinf-inc/IPED/) to detect images with QRCodes. Another image with approximately 2Mb triggers an unexpected behavior, the library is running for hours without finishing.  The triggering file is attached. The thread dump below shows that the process is locked inside the zxing library.

>  java.lang.Thread.State: RUNNABLE
	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:637)
	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
	at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:64)
	at iped.engine.task.QRCodeTask.process(QRCodeTask.java:143)

I take a small look in the code and seems to be a method with a cubic complexity in relation to the number of possible centers. Maybe this number should have an upper bound?

[triggeringImage.zip](https://github.com/zxing/zxing/files/9913238/triggeringImage.zip)

**Comment by srowen** [comment]
Yeah you have it right. I think there is an easy fix. Coming shortly. Are you in a position to build the library from source and try the fix?

**Comment by lfcnassif** [comment]
Just confirmed the fix, thank you @srowen!

**Comment by lfcnassif** [comment]
Out of curiosity, is there a time frame for 3.5.1?

**Comment by srowen** [comment]
Just when I have a reason to make a release. It's been 6 months and some reasonable fixes since the last one so I could do it in the next couple days.

**Comment by hauck-jvsh** [comment]
Wow, you were fast I was in a meeting and when I came out the problem was already fixed and tested.

**Comment by srowen** [comment]
3.5.1 should be released now. I needed to get out some other fixes, so good timing

**Comment by lfcnassif** [comment]
Great, thank you!
