### ISSUE TITLE
QR code generated with zxing 3.5.0 cannot be read by the same library.

### ISSUE THREAD

**Issue by abinassar** [zxing/zxing#1568]
Hello, I am currently developing a program in spring boot that generates QR codes with the zxing library in its version 3.5.0.

        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>core</artifactId>
            <version>3.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>3.5.0</version>
        </dependency>

The functions I use to generate and read the QR codes are the following:

    public void createQRCode(String qrCodeData, 
                        String filePath,
                        String charset, 
                        Map<EncodeHintType, ErrorCorrectionLevel> hintMap, 
                        int qrCodeheight, 
                        int qrCodewidth) throws WriterException, IOException {

        String QRCodeData = new String(qrCodeData.getBytes(charset), charset);

        BitMatrix matrix = new MultiFormatWriter().encode(QRCodeData,
                BarcodeFormat.QR_CODE,
                qrCodewidth,
                qrCodeheight,
                hintMap);

        Path QRCodePath = Paths.get(filePath);

        MatrixToImageWriter.writeToPath(matrix,
                filePath.substring(filePath.lastIndexOf('.') + 1),
                QRCodePath);

    }

    public String readQRCode(BufferedImage QRCodeImage, 
                             String charset, 
                             Map<DecodeHintType, Object> hintMap) throws FileNotFoundException, IOException, NotFoundException {

        BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(
            new BufferedImageLuminanceSource(QRCodeImage)));
        Result qrCodeResult = new MultiFormatReader().decode(binaryBitmap,
                hintMap);
        return qrCodeResult.getText();
    }

The implementation of the functions is done in the following way:

    String dataEncrypted = "kTKZdHd0nuF3Fp1HnefdrIvzZqyt5uuqgIJX4pWbmwuF0oqBHitd9xnEm6z/fWWhNj4br4gAxDYUnLW/JPB4PORVHVxaMMCE8yBDpS+AA/UJc6WblXniwm/Ii8z2l3LE"

    String charset = "UTF-8";
    Map<EncodeHintType, ErrorCorrectionLevel> hintMap = new HashMap<EncodeHintType, ErrorCorrectionLevel>();
    hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);

    QRCodeService.createQRCode(dataEncrypted, barcodeFileName, charset, hintMap, 500, 500);

To decrypt the function is:

    String charset = "UTF-8";
    BufferedImage envelopeImagePage;
    Map<DecodeHintType, Object> hintMap = new HashMap<DecodeHintType, Object>();
    hintMap.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
    hintMap.put(DecodeHintType.POSSIBLE_FORMATS, Arrays.asList(BarcodeFormat.QR_CODE));
    resultFromQRCode = QRCodeService.readQRCode(qrCodeImage, charset, hintMap);

The problem I have is that there are codes that I generate that later return the exception not found and they cannot read the QR code. An example of one of the QR codes that return this exception is the following:

![QRCode can not read](https://user-images.githubusercontent.com/55027987/199389516-aaa74e2c-30c5-43d7-b67f-bfb95b3e9f4e.png)

However, with a handheld scanner or cell phone camera scanner there is no problem in reading failed QR codes. This are my questions:

* Is the configuration I use to generate and read the QR codes correct?
* Is this a JAVA library bug?

I look forward to your response and advice on this matter. Thanks in advance.

**Comment by micha-sommer** [comment]
We are experiencing a similar problem which actually started with the release of version 3.5.1.

**Comment by srowen** [comment]
For the first post, it's entirely possible the generate QR code doesn't quite scan because it misreads the finder patterns, just possible on any image. It should be rare but not impossible. Use PURE_BARCODE mode if you know you are scanning generated images like the one in the post. not a bug but open to suggestions as pull requests.

**Comment by srowen** [comment]
To the second, 3.5.1 does have fixes to avoid doing a lot of work when there are lots of barely-detected finder patterns. It could make it not decode some images that decoded before, but also should be corner cases. Same, open to ideas, but as pull requests.
