### ISSUE TITLE
LuminanceSource.java / has final methods

### ISSUE THREAD

**Issue by tfonteyn** [zxing/zxing#1572]
https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/LuminanceSource.java

    public final String toString()

When decoding a barcode which (for whatever reason) throws an error, the toString of LuminanceSource will be called. 
On some Android devices this will then lead to a StackOverflowError because the StringBuilder in the toString will grow to large.

... and I cannot simply override the toString in a custom LuminanceSource.

Can the 'final' be removed from the toString() method please.

**Comment by srowen** [comment]
Hm how does the error arise?

**Comment by srowen** [comment]
Yes, there's nothing wrong with the toString, it seems. It will allocate a string the size of the barcode, and that may be the final allocation that runs OOM or something, but no issue there per se. I don't think removing 'final' helps you debug
