### ISSUE TITLE
 PlanarYUVLuminanceSource  is a final class and hence cannot be extended.

### ISSUE THREAD

**Issue by tfonteyn** [zxing/zxing#1573]
https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/PlanarYUVLuminanceSource.java

Can the 'final' from this class be removed please?

workaround I use for now is simply to copy the code from that class to a new custom one, but that is a bit silly IMHO.

**Comment by srowen** [comment]
Duplicate https://github.com/zxing/zxing/issues/1572
