### ISSUE TITLE
QR code scanner does not work on QR codes with a black background

### ISSUE THREAD

**Issue by hakhov** [zxing/zxing#1574]
[QR-Code auf schwarz.pdf](https://github.com/zxing/zxing/files/10066878/QR-Code.auf.schwarz.pdf)

**Comment by LucasFaiska** [comment]
I have a simmilar issue, why this one has been closed?

**Comment by hakhov** [comment]
Hello, this info help me
https://github.com/Redth/ZXing.Net.Maui/blob/main/ZXing.Net.MAUI/BarcodeScannerOptions.cs#L10
