### ISSUE TITLE
zxing-core 3.3.3 crashes on Android < 7.0 when decoding QR code 

### ISSUE THREAD

**Issue by nikkitagupta** [zxing/zxing#1575]
I'm using com.google.zxing:core:3.3.3 with in an Android app.
Everytime I scan a QR code with an Android device with Android < 7.0 (API 24) the app crashes with the following exception:

10-10 10:30:38.504 10128 12133 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(SourceFile:616)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at com.google.zxing.qrcode.detector.FinderPatternFinder.find(SourceFile:164)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at com.google.zxing.qrcode.detector.Detector.detect(SourceFile:81)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at com.google.zxing.qrcode.QRCodeReader.decode(SourceFile:77)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at com.google.zxing.MultiFormatReader.decodeInternal(SourceFile:173)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at com.google.zxing.MultiFormatReader.decodeWithState(SourceFile:87)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at com.airwatch.qrcode.DecodeHandler.getScanResult(Unknown Source)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at com.airwatch.qrcode.DecodeHandler.decode(Unknown Source)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at com.airwatch.qrcode.DecodeHandler.handleMessage(Unknown Source)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-10 10:30:38.504 10128 12133 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)

My app still provide support for Android 5.0 devices which is API 21 so I cannot change the target version to API 24 

As per the suggestion here modifying Android app to use zxing 3.3.x core library will fix the crash, but I am still seeing the same crash using zxing 3.3.3 .
https://github.com/zxing/zxing/issues/1170#issuecomment-494778246

Any help or suggestion is much appreciated .

**Comment by srowen** [comment]
You would have to stay on an older version of the library then

**Comment by Isigwe** [comment]
#1575 thank you

**Comment by nikkitagupta** [comment]
@srowen Thanks for the quick reply really appreciate it. So here is my another question since I didn't wanted to downgrade the zxing core lib version from 3.3.3 to 3.3.0, I choose to implement this using Desugaring as mentioned here
https://github.com/zxing/zxing/issues/1170#issuecomment-557446951

by simply adding coreLibraryDesugaringEnabled true in the build.gradle file like below

compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

dependencies {
      coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}
    
But I am still seeing the same crash again 

11-30 16:27:55.745 13679 20488 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(SourceFile:16)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(SourceFile:171)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.Detector.detect(SourceFile:5)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.google.zxing.qrcode.QRCodeReader.decode(SourceFile:6)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.google.zxing.MultiFormatReader.decodeInternal(SourceFile:13)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.google.zxing.MultiFormatReader.decodeWithState(SourceFile:9)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.airwatch.qrcode.DecodeHandler.getScanResult(SourceFile)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.airwatch.qrcode.DecodeHandler.decode(SourceFile)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.airwatch.qrcode.DecodeHandler.handleMessage(SourceFile)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

11-30 16:27:55.745 13679 20488 E AndroidRuntime: 	at com.airwatch.qrcode.d.run(SourceFile)

11-30 16:27:55.766  1273  2736 W ActivityManager:   Force finishing activity com.airwatch.androidagent/com.airwatch.qrcode.ui.QRCodeCaptureActivity

11-30 16:27:55.778   650 20523 E mm-camera: cpp_module_send_buf_divert_event:545] buffer event received with no divert config

11-30 16:27:55.830   650 20467 D mm-camera: mct: mct_pipeline_process_set:command=8000009

11-30 16:27:55.830   650 20467 D mm-camera: mct: mct_pipeline_process_set: STREAM-OFF on stream 0x40002 stream type=3

11-30 16:27:55.830   650 20467 I mm-camera: module_sensor_module_process_event:4707ide 40002 MCT_EVENT_CONTROL_STREAMOFF

11-30 16:27:55.831   650 20467 I mm-camera: module_sensor_stream_off:4500ide 40002 MCT_EVENT_CONTROL_STREAMOFF

11-30 16:27:55.831   650 20467 E mm-camera: iface_streamoff_to_thread: E, session id = 4, user stream id = 2

11-30 16:27:55.831   650 20454 E mm-camera: iface_streamoff: E, session_id 4 mct_stream_id = 2

11-30 16:27:55.831   650 20454 E mm-camera: iface_util_update_streamon_id: left stream on count 1, skip hw streamoff

11-30 16:27:55.831   650 20454 E mm-camera: iface_util_decide_hw_streams: num_user_streams 1 num_hw_streams 0

11-30 16:27:55.908   650 20454 E mm-camera: iface_streamoff: all bundled stream streamoff, clear hal bundled mask

11-30 16:27:55.908   650 20454 E mm-camera: iface_streamoff: X

**Comment by nikkitagupta** [comment]
Am I missing anything here or doing something wrong ? Or is it something like Desugaring doesn't always fix this issue and I might need to try some other solution to support my app in Android 6.0 devices

**Comment by srowen** [comment]
I don't think it's a matter of 'desugaring'. This is a difference in core JDK libraries across Java versions

**Comment by nikkitagupta** [comment]
then why do I see same error even after desugaring, ideally it should have fixed this error right ?

11-30 16:27:55.745 13679 20488 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

**Comment by srowen** [comment]
As in my last message - it isn't related to desugaring at all

**Comment by nikkitagupta** [comment]
Since I have to support Android 6.0 devices so I wanted to know which version of zxing lib I should downgrade to to avoid this error ?

**Comment by nikkitagupta** [comment]
Hi @srowen Even downgrading the zxing version doesn't solves my issue, when using zxing 3.3.0 version I am getting this error 

E  FATAL EXCEPTION: Thread-509
                                                                                                    Process: com.airwatch.androidagent, PID: 6064
                                                                                                    java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of ‘java.util.List’ appears in /system/framework/core-libart.jar)
                                                                                                    	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(SourceFile:16)
                                                                                                    	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(SourceFile:171)
                                                                                                    	at com.google.zxing.qrcode.detector.Detector.detect(SourceFile:5)
                                                                                                    	at com.google.zxing.qrcode.QRCodeReader.decode(SourceFile:6)
                                                                                                    	at com.google.zxing.MultiFormatReader.decodeInternal(SourceFile:13)
                                                                                                    	at com.google.zxing.MultiFormatReader.decodeWithState(SourceFile:9)
                                                                                                    	at com.airwatch.qrcode.DecodeHandler.getScanResult(SourceFile)
                                                                                                    	at com.airwatch.qrcode.DecodeHandler.decode(SourceFile)
                                                                                                    	at com.airwatch.qrcode.DecodeHandler.handleMessage(SourceFile)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:148)
                                                                                                    	at com.airwatch.qrcode.d.run(SourceFile)
