### ISSUE TITLE
why zxing can not decode this qrcode image?

### ISSUE THREAD

**Issue by jiaqiang000** [zxing/zxing#1585]
JavaSE: Exception is "com.google.zxing.NotFoundException"
Can any one help me?
![image](https://user-images.githubusercontent.com/43921091/209461404-b21b22e5-dade-4ae4-ba7e-58a719c58065.png)
The version is 3.4.1
```
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>3.3.1</version>
        </dependency>
```
and the java code is there.
```
        BufferedImageLuminanceSource source = new BufferedImageLuminanceSource(image);
        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
        Result result;
        Map<DecodeHintType,Object> hints = new LinkedHashMap<>();
        hints.put(DecodeHintType.CHARACTER_SET, "utf-8");
        hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
        result = new MultiFormatReader().decode(bitmap, hints);
        return result.getText();
```
The Exception info is :

com.google.zxing.NotFoundException
There is not anything other displayed...

But the following code can not be decoded out，It's really weird
![image](https://user-images.githubusercontent.com/43921091/209461543-a12634e6-f9aa-4c87-a285-71eb5fff6363.png)

**Comment by srowen** [comment]
It decodes fine: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F43921091%2F209461404-b21b22e5-dade-4ae4-ba7e-58a719c58065.png
