### ISSUE TITLE
Unable to scan barcode. Not recognized

### ISSUE THREAD

**Issue by diegoflassa** [zxing/zxing#1587]
I´m trying to scan the folowing barcode with the latest version available of the library, but it just does not recongnizes it!
The numbers below the barcode are the value that should be read!

![Barcode](https://user-images.githubusercontent.com/7230966/210279683-fca6d4cf-4082-497f-9f77-fed43d809fe2.png)

**Comment by srowen** [comment]
It looks like it's just too blurry

**Comment by diegoflassa** [comment]
> It looks like it's just too blurry

It might be, but, another app i tried was able to read it!
This one: 
https://play.google.com/store/apps/details?id=com.gamma.scan&hl=en&gl=US

**Comment by diegoflassa** [comment]
I tried with my app, thats uses the library, and this one (unable to read it too)
https://github.com/journeyapps/zxing-android-embedded.git

I was only able to read it with this one:
https://play.google.com/store/apps/details?id=com.gamma.scan&hl=en&gl=US

**Comment by diegoflassa** [comment]
Leave it closed! I was able to read it when using a better image!
Thanks for the tip!
