### ISSUE TITLE
barcode scanning

### ISSUE THREAD

**Issue by sepideh69** [zxing/zxing#1589]
hi 
I have a question . is this library just for scanning qr code? 
I need to scan barcode but as I tried I couldn't do that

**Comment by diegoflassa** [comment]
It can be used to scan both qr or barcode.
Have ou tried the example app?

**Comment by sepideh69** [comment]
tnx for replying

I follow this tutorial :
https://www.youtube.com/watch?v=asl1mFtkMkc

and here is the code :
https://github.com/philipplackner/QrCodeScannerCompose/tree/app/app/src/main/java/com/plcoding/qrcodescannercompose
