### ISSUE TITLE
项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?

### ISSUE THREAD

**Issue by gionlime** [zxing/zxing#1590]
项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?

**Comment by srowen** [comment]
No sorry no port that I know of

**Comment by axxel** [comment]
Maybe [this](https://pub.dev/packages/flutter_zxing) would be an option for you. It is a wrapper for [zxing-cpp](https://github.com/zxing-cpp/zxing-cpp).

**Comment by srowen** [comment]
Oh wow I didn't know about that, good call out
