### ISSUE TITLE
Generate QR code with ISO 18004 standard?

### ISSUE THREAD

**Issue by NirmalWi** [zxing/zxing#1592]
I want to generate the QR code with ISO 18004 standard. If I use Zxing maven dependency or library, is it follows that standard? (ISO 18004)

**Comment by srowen** [comment]
It already follows ISO 18004:2006; I don't know how much 18004:2015 is different, but my impression is that it is the same format.

**Comment by NirmalWi** [comment]
OK. Thank you very much for the information...
