### ISSUE TITLE
Exception with com.google.zxing.NotFoundException

### ISSUE THREAD

**Issue by NBarile** [zxing/zxing#1594]
Hi guys ! 

I try to detect barcode in a webcam flux with opencv, but I Java catch a NotFoundException error.

I try 3 different code, with video and only one image, and I have the same error...

I think it's the decode() method...

Someone can help me ?

Thanks !

**Comment by NBarile** [comment]
@srowen uh, why did u closed the post ? 

My problem still here ...

**Comment by srowen** [comment]
No detail at all, you completely ignored the instructions you deleted
