### ISSUE TITLE
PDF417 Argentinian Driver Licence

### ISSUE THREAD

**Issue by airiarte** [zxing/zxing#1598]
Hi, I´ve tested Zxing with online decoder and android. This code is not recognized by Zxing but it does with other barcode readers. Can you lead me to resolve this issue? Please help.
![1677270134818](https://user-images.githubusercontent.com/3331990/221295491-40463ec3-c430-4e10-8a87-e02c25776372.JPEG)

**Comment by srowen** [comment]
It's just too distorted - need a better picture, but the underlying barcode actually looks a bit messed up

**Comment by airiarte** [comment]
Thank you for the fast response. I´ll try to get a better picture of the card.

**Comment by airiarte** [comment]
Just to let you know, I agree the barcode is not in a perfect shape. What frustrates me is this good and expensive product https://demo.dynamsoft.com/barcode-reader/ it reads exactly the same picture that I've previously attached.

**Comment by srowen** [comment]
Sometimes, counterintuitively, a slightly blurrier image works. You can try a light blur or downsample of the image. It can even out noise that harms detection.
