### ISSUE TITLE
Bug for v3.5.1 zxing-core

### ISSUE THREAD

**Issue by oyzh1994** [zxing/zxing#1600]
### Bug Reports
in javafx project(jdk17&openjfx17)，code like it is **hold on** and not working next code. zxing-core version is 3.5.1.
_new MultiFormatWriter().encode(content, BarcodeFormat.QR_CODE, w, h, hints);_
and in zxing-core version is 3.4.1, code is run normally.
i think it is an bug. TAT.

以上代码在javafx工程中，使用3.5.1版本运行异常(一直卡住)，使用3.4.1版本运行正常。

**Comment by srowen** [comment]
No idea what you're asking here

**Comment by zooooooooy** [comment]
我也遇到同样的问题，查看日志后发现是zxing自带的stringutils的构造方法是私有的，所以该类无法被初始化导致的。暂时还没有解决方法。

**Comment by oyzh1994** [comment]
> 我也遇到同样的问题，查看日志后发现是zxing自带的stringutils的构造方法是私有的，所以该类无法被初始化导致的。暂时还没有解决方法。

我后面解决了，我对jdk进行过裁剪，不当的裁剪导致的此问题
