### ISSUE TITLE
QR Code Bitmap EncodeHintType.MARGIN not working on some URLs

### ISSUE THREAD

**Issue by sanogueralorenzo** [zxing/zxing#1601]
### Bug Reports

Hello everyone 👋 

Given the following utility method to generate QR codes

```
fun String.toQrCode(size: Int, blackColor: Int, whiteColor: Int): Bitmap {
    val hints = mapOf(EncodeHintType.MARGIN to 0)
    val bits = QRCodeWriter().encode(this, BarcodeFormat.QR_CODE, size, size, hints)
    return Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888).apply {
        for (x in 0 until size) {
            for (y in 0 until size) {
                setPixel(x, y, if (bits[x, y]) blackColor else whiteColor)
            }
        }
    }
}
```

I have noticed that depending on the URL the bitmap you get has a different size, not respecting the QR Code Writer size parameter

With the first URL `https://link.tonal.com/aaaa-a-aaaaa` this is the output:

<img width="68" alt="image" src="https://user-images.githubusercontent.com/5630683/222875578-0c5b22ff-2f03-499d-b60e-7c98a414d3af.png">

With the second URL `https://knowledge.tonal.com/s/article/How-to-Troubleshoot-Cables-Not-Retracting` this is the output:

<img width="68" alt="image" src="https://user-images.githubusercontent.com/5630683/222877636-760c7b65-b011-456b-b524-4fd877fbbdad.png">

I've tried in 3.4.1 and the latest 3.5.1 with the same result (as well as leaving the default margin instead of setting it to 0)

Is there anything I can do to enforce QRCode size? Adding padding + using crop to padding in the imageview is not reliable since it will make big QR codes have the proper margin but the smaller ones will be too small

**Comment by srowen** [comment]
Longer URLs require bigger QR codes to encode. That much seems entirely expected. You can't generate an image smaller than is necessary to display the code!
You are setting the margin to 0, is that what you're concerned about? you can set it >0.

**Comment by sanogueralorenzo** [comment]
Thanks for the reply @srowen 

I investigated a bit more and I was able to better reproduce the issue

It seems that there is a bug when you set Margin to 0 for shorter URLs since the bitmap returned has white space instead of scaling up since margin is 0

Short URL `https://link.tonal.com/aaaa-a-aaaaa` with margin 0

<img width="73" alt="image" src="https://user-images.githubusercontent.com/5630683/222932311-83af814c-2d84-4d6a-a6a3-2b520e4c4ba7.png">

Short URL `https://link.tonal.com/aaaa-a-aaaaa` with margin 1

<img width="69" alt="image" src="https://user-images.githubusercontent.com/5630683/222932373-3c690cb8-183a-4deb-bdea-e25587c9dfbd.png">

Long URL `https://knowledge.tonal.com/s/article/How-to-Troubleshoot-Cables-Not-Retracting` with margin 0

<img width="68" alt="image" src="https://user-images.githubusercontent.com/5630683/222932292-b9a68396-d67a-4478-930b-29e310234159.png">

Long URL `https://knowledge.tonal.com/s/article/How-to-Troubleshoot-Cables-Not-Retracting` with margin 1

<img width="70" alt="image" src="https://user-images.githubusercontent.com/5630683/222932271-d7066794-a3c0-48f4-8fdc-905279c2d152.png">

I don't think it is caused by short / long URLS but different URLs, trying with an abnormal long URL with margin 0 provides the following

<img width="71" alt="image" src="https://user-images.githubusercontent.com/5630683/222932472-6ba02734-8531-4794-893f-2ca3661fe9f7.png">

So overall the margin is not always respected

**Comment by sanogueralorenzo** [comment]
Re-opening for visibility, since I think this example explains better the issue

Below we have the following

- ImageView 74dp height and width
- ImageView padding 2dp + cropToPadding true
- ImageView background set to white with rounded colors
- QR Code generator with size of 74dp (converted to pixels), Margin set to 0 + when drawing the bitmap it draws the QR Code in black and red for the empty pixels

This produces the following:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/5630683/222957283-f60f7840-790e-47a4-af70-5545466e3cfc.png">

As you can see with the red border of the bitmap, the QR Code that is being generated is not matching the size and padding I provided. Instead it is creating a smaller QR Code and filling the borders of the bitmap with empty space, ignoring the Margin 0 set into the library. My expectation was that this bitmap would have 0 Margin regardless of how small or large the generated QR Code is (by scaling the bitmap up or down until it matches the passed size)

I was able to "fix" or reduce this Bitmap margin by:

- Make the size of the QR Code bitmap around 28dp bigger than the target ImageView (to avoid smaller QR Codes having extra bitmap padding)
- Adding padding 2dp + cropToPaddingTrue (to still have some padding around the QR Code)

**Comment by srowen** [comment]
So, I'm still confused, why do you want 0 margin? it's not valid without a quiet zone.
The generator has to generate an image where each module is an integer number of pixels on a side. It will make the image output bigger if needed to do so and accommodate the image. If the largest possible rendering of the QR code that fits in your supplied dimensions is smaller than desired, you get margin no matter what you set it to.
Otherwise, you would have a pretty distorted QR code, so no that is by design.
