### ISSUE TITLE
QR code generator Down

### ISSUE THREAD

**Issue by AHugie** [zxing/zxing#1609]
Hello, The QR code generator at [ http://zxing.appspot.com/generator/ ] appears to be down. 

Settings to reproduce:

Contents: URL
URL: any (all don't work)
Barcode size: any (all don't work)
Error Correction: any (all don't work)
Character Encoding: any (all don't work)

Thank you!

**Comment by srowen** [comment]
It does that and I restart. No need to report

**Comment by srowen** [comment]
I would not rely on it being up, but I can occasionally reset it. No need
to report, I get an alert eventually
