### ISSUE TITLE
Scanning a GS1 barcode multiple times, gives different results.

### ISSUE THREAD

**Issue by akrajanshukla** [zxing/zxing#1616]
Scan a GS1 barcode

(01)57251412207292(15)230124(10)Lot-110

If you can scan this barcode multiple times from a Xamarin Forms app, we see different results being returned by the ZXing scanner.

For example,
instead of 01 for the first two digits - sometimes it gives 00 and hence GS1 parsing fails.

**Comment by srowen** [comment]
I can't help debug, but maybe you just have misreads or are finding a different phantom barcode
