### ISSUE TITLE
Fairly innocuous QR codes that only work with PURE_BARCODE hint

### ISSUE THREAD

**Issue by dlenski** [zxing/zxing#1623]
There are some very straightforward QR code images that ZXing fails to decode except with the `PURE_BARCODE` hint.

2 such examples were recently reported in https://github.com/dlenski/python-zxing/issues/27 (`python-zxing` is a Python wrapper around ZXing's `CommandLineRunner`).

As far as I can tell, the effect of the `PURE_BARCODE`  hint on QR code decoding is entirely in https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/qrcode/QRCodeReader.java#L72-L80

```java
    if (hints != null && hints.containsKey(DecodeHintType.PURE_BARCODE)) {
      BitMatrix bits = extractPureBits(image.getBlackMatrix());
      decoderResult = decoder.decode(bits, hints);
      points = NO_POINTS;
    } else {
      DetectorResult detectorResult = new Detector(image.getBlackMatrix()).detect(hints);
      decoderResult = decoder.decode(detectorResult.getBits(), hints);
      points = detectorResult.getPoints();
    }
```

Without fully understanding why these images fail to decode _without_ the hint… would it be unreasonable to _retry_ with the  `PURE_BARCODE` hint, if detection/decoding fails without it?

Note that many other 2D decoders, including Aztec 2D code, simply ignore the `PURE_BARCODE` hint altogether.

**Comment by srowen** [comment]
You can do that, but, that's really up to the caller to decide to do. I don't think it would be useful to do in the default path, because it's designed to work with photos from a camera primarily, and testing if every failed frame is somehow just a plain synthetic image of a barcode would waste cycles

**Comment by dlenski** [comment]
> it's designed to work with photos from a camera primarily, and testing if every failed frame is somehow just a plain synthetic image of a barcode would waste cycles

Understood, yes, but…

> You can do that, but, that's really up to the caller to decide to do. I don't think it would be useful to do in the default path, because …

1. Does it make sense for the default path of the _command-line runner_ *not* to set `PURE_BARCODE` by default, but only as an option?
2. If the answer to (1) is "yes, it still makes sense for the command-line runner *not* to set `PURE_BARCODE`", then would it not make sense for the `TRY_HARDER` option to retry with `PURE_BARCODE`, effectively?

**Comment by srowen** [comment]
There should be flags for both on the CLI: https://github.com/youknowone/zxing/blob/master/javase/src/main/java/com/google/zxing/client/j2se/CommandLineRunner.java#L66
No I think those are separate ideas
