### ISSUE TITLE
Compact PDF417: spurious ChecksumException

### ISSUE THREAD

**Issue by gredler** [zxing/zxing#1641]
Similar to issue #1624, the example below causes an error because a barcode pattern is erroneously considered to match the PDF417 stop pattern (which doesn't exist on Compact PDF417 barcodes, and should not be found).

In pull request #1628 we reduced `MAX_INDIVIDUAL_VARIANCE` from `0.8` to `0.7`, which fixed the original sample. However, the sample below requires a further reduction from `0.7` to `0.64` in order to pass. I'm worried that continuing down this path could start to cause regressions decoding legitimate low-quality images.

We examined another alternative in pull request #1627 with a new `ASSUME_COMPACT_PDF_417` hint, but this requires explicit user action -- not horrible, but not ideal either.

Another option that is worth thinking about is adding a heuristic / sanity check for stop patterns that we think we have found which have a height very different from the corresponding start pattern. If the two heights are very different, we could assume that what we found was not in fact a stop pattern. I'll create a pull request with a sample implementation for this option, for discussion.

![13](https://github.com/zxing/zxing/assets/178883/e88175d5-9464-41bf-96fe-038def0e4268)

**Comment by srowen** [comment]
Does turning down the tolerance cause tests to fail? it could be the right move. The original value was probably pretty lax. If it does harm other decoding then yeah may need some other approach

**Comment by gredler** [comment]
No, as I recall the other tests were still passing at `0.64` as well. It just worries me to start changing magic numbers that seem to have worked so well for so many years by 25%. (Or possibly more whenever the next fuzz error crops up!)
