### ISSUE TITLE
QR Code whitespace problem

### ISSUE THREAD

**Issue by amormz** [zxing/zxing#1654]
Hi, I ran into a problem while creating a QR code.
Why do the generated images have large margins at the edges? I've set margin to 0.
thanks.

QR code sample:
<img width="332" alt="image" src="https://github.com/zxing/zxing/assets/53961687/35ccc5cc-160a-45d7-a948-2fc55f046c25">

width:200, height:200
hits:
```java
    hints.put(EncodeHintType.CHARACTER_SET, "utf-8");
    hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.M);// L、M、Q、H
    hints.put(EncodeHintType.MARGIN, 0);
```

**Comment by srowen** [comment]
They must have non-zero margin to be valid

**Comment by amormz** [comment]
> They must have non-zero margin to be valid

Thank you for your reply. I have set the margin to 0, but the above problem still occurs

**Comment by srowen** [comment]
What do you mean? Input, output?
