### ISSUE TITLE
PDF Barcode generation giving strange results

### ISSUE THREAD

**Issue by ashore8093** [zxing/zxing#166]
Platform: Android 4.0+
Zxing Version: 3.0.1
Barcode Format: PDF417

Since CP437 encoding isn't present on Android I've tried setting different encodings to render a PDF417 barcode but it is prepending extra characters that vary based on the encoding.

US-ASCII
Prepends with 'A'

ISO-8859-1
Prepends with 'AB'

UTF-8
Prepends with 'A\s'

UTF16 prepends stranger characters and actually loses a character from the original source.

Using the following to set the Character set
hints.put(EncodeHintType.CHARACTER_SET, "US-ASCII");

Is there anyway to prevent the rendered barcode from prefixing these characters?

**Comment by androidneha** [comment]
You can Try this

try {
            // Encode a String into bytes
            String inputString = "00oDL9CAU7408tue0920171130";
            byte[] input = inputString.getBytes("UTF-8");

            // Compress the bytes
            byte[] output = new byte[100];
            Deflater compresser = new Deflater();
            compresser.setInput(input);
            compresser.finish();
            int compressedDataLength = compresser.deflate(output);
            compresser.end();

            // Decompress the bytes
            Inflater decompresser = new Inflater();
            decompresser.setInput(output, 0, compressedDataLength);
            byte[] result = new byte[100];
            int resultLength = decompresser.inflate(result);
            decompresser.end();

            // Decode the bytes into a String
            String outputString = new String(result, 0, resultLength, "UTF-8");

            Log.e("outputString",outputString +" / "+output );
        } catch(java.io.UnsupportedEncodingException ex) {
            Log.e("outputString",ex.toString());
            // handle
        } catch (java.util.zip.DataFormatException ex) {
            Log.e("outputString",ex.toString());
            // handle
        }
