### ISSUE TITLE
Please put in encoders for the remaining barcode symbologies.

### ISSUE THREAD

**Issue by BenHut1** [zxing/zxing#1660]
I'm so glad that ZXing can decode some of the more exotic types of barcode such as Maxicode, but sadly it can't encode many of these. The ones it can encode are ones I already have encoders for. I'm looking for encoders for some of the more exotic barcodes such as Maxicode and RSS.

**Comment by srowen** [comment]
Sure, but, somebody would have to write those, and there is nobody working on this project. Feel free to open a PR with a clean implementation

**Comment by ramanpopli** [comment]
Is anyone working on it . As said by @srowen nobody is using this project . if its Ok to do Implementation for this feature , then I would like to contribute .

**Comment by BenHut1** [comment]
I don't think there's any rule saying not to contribute. I just think the
original authors, and most other contributors, have stopped working on it.

**Comment by pasin19** [comment]
``

**Comment by BenHut1** [comment]
> ``

What does .. mean?

**Comment by BenHut1** [comment]
> Is anyone working on it . As said by @srowen nobody is using this project . if its Ok to do Implementation for this feature , then I would like to contribute .

Nothing wrong with contributing, as I explained in a previous post. If you can add maxicode decoding, please do.
