### ISSUE TITLE
[BUG] Aztec fails to decode

### ISSUE THREAD

**Issue by JKamsker** [zxing/zxing#1662]
The aztec decoder does not work. I have only tried the web version which is build on top of the code in this repo. (https://zxing.org/w/decode.jspx)

## Additional Information

Images:
![grafik](https://github.com/micjahn/ZXing.Net/assets/11245306/6fa7805a-9a17-432e-a234-1af1768a0c85)
![signal-2023-06-30-114422](https://github.com/micjahn/ZXing.Net/assets/11245306/85d17a38-d930-4d92-b06f-9d5c084c8c10)

Aspose is able to read the information.
https://products.aspose.app/barcode/de/recognize/aztec#/recognized

It is trying to encode the binary data as UTF-8 string but it seems to be correct otherwise.

Related issue in the dotnet port: https://github.com/micjahn/ZXing.Net/issues/507

**Comment by srowen** [comment]
Sorry, I don't take reports like this, only proposed PRs

**Comment by axxel** [comment]
You might want to give https://github.com/zxing-cpp a try.

**Comment by JKamsker** [comment]
@axxel Thanks for pointing that out! [Their web version](https://zxing-cpp.github.io/zxing-cpp/zxing_viddemo.html) doesnt detect anything either with my provided samples.

**Comment by axxel** [comment]
The web-version is currently not up to date (see README). I just checked that at least the first image gets detected successfully with current HAED. You could open an issue telling me that the web-version is outdated but I know that already ;).

**Comment by axxel** [comment]
I stumbled over this again and just wanted to take the opportunity to mention that `zxing-cpp` v3.1 can now decode the second image as well.
