### ISSUE TITLE
build android apk fail with " 'dependencies.dependency.version' for com.google.android:android:jar is missing."

### ISSUE THREAD

**Issue by yokewang** [zxing/zxing#1664]
Hi, I followed "https://github.com/zxing/zxing/wiki/Getting-Started-Developing" to build an android apk in a docker container（mobiledevops/android-sdk-image）.
But got the below errors：
mobiledevops@95fecc375430:~/app/zxing-zxing-3.5.1/android$ ../../apache-maven-3.9.3/bin/mvn package android:apk
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] **'dependencies.dependency.version' for com.google.android:android:jar is missing.** @ line 34, column 17
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.google.zxing:android:4.7.9 (/home/mobiledevops/app/zxing-zxing-3.5.1/android/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.google.android:android:jar is missing. @ line 34, column 17
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

BTW：
From the root of the project, run mvn install to compile, test and assemble all modules. Add -DskipTests to skip unit tests. Note that Android-related modules and apps will not be built unless ANDROID_HOME is set.
Compiled .jar files are found in submodules after this. For example, the compiled core/ code is available at core/target/core-x.y.z.jar.
The core.jar is generated.
mobiledevops@95fecc375430:~/app/zxing-zxing-3.5.1/core/target$ ls -l core-3.5.1.jar
-rw-r--r-- 1 mobiledevops mobiledevops 606819 Jul  9 04:56 core-3.5.1.jar

**Comment by srowen** [comment]
Did you install the Android SDK and set ANDROID_HOME? any modifications?

**Comment by yokewang** [comment]
Yes, the mobiledevops/android-sdk-imag container set the correct ANDROID_HOME and Android SDK.

**Comment by srowen** [comment]
I think there's a problem with your setup or modifications. It's saying the android.home property isn't set, or there is no file at:

```
<!-- ANDROID_HOME must be absolute, but redundant leading / may help Gradle Spring Boot plugin -->
<systemPath>/${android.home}/platforms/android-${android.platform}/android.jar</systemPath>
```

**Comment by yokewang** [comment]
mobiledevops@39d5aa6de147:~/app$ set
ANDROID_HOME=/opt/android-sdk-linux
ANDROID_SDK_ROOT=/opt/android-sdk-linux
ANDROID_SDK_TOOLS_CHECKSUM=bd1aa17c7ef10066949c88dc6c9c8d536be27f992a1f3b5a584f9bd2ba5646a0
ANDROID_SDK_TOOLS_VERSION=9477386

mobiledevops@39d5aa6de147:~/app$ cd  /opt/android-sdk-linux/
mobiledevops@39d5aa6de147:/opt/android-sdk-linux$ ls
build-tools  cmdline-tools  emulator  extras  licenses  patcher  platform-tools  platforms  tools
mobiledevops@39d5aa6de147:/opt/android-sdk-linux$ cd platforms
mobiledevops@39d5aa6de147:/opt/android-sdk-linux/platforms$ ls
android-30  android-31  android-32  android-33

**Comment by srowen** [comment]
It's not clear what you're showing here, but, you at least do not have Android 22 installed. You need to debug your own setup. Please see messages above and trace what the build does. You can see the build works in GA, so it's your env at issue.

**Comment by marcelrv** [comment]
after stuggling a lot with the same erro here a hint that worked for me:

running with the ` mvn -P build-android install` I saw the exact path the build process was working.
In my case I had the path surrounded with quotes.  Removing the quotes fixed it for me. But more in general, this way it is more easy to detect what is goinf on. 

```
D:\Programming\git\zxing>mvn -P build-android -nsu -B -Pjacoco install  -DskipTests
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is /"C:\Users\marce\AppData\Local\Android\Sdk"/platforms/android-22/android.jar @ line 701, column 25
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.google.zxing:zxing-parent:3.5.4-SNAPSHOT (D:\Programming\git\zxing\pom.xml) has 1 error
[ERROR]     'dependencyManagement.dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is /"C:\Users\marce\AppData\Local\Android\Sdk"/platforms/android-22/android.jar @ line 701, column 25
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

D:\Programming\git\zxing>set ANDROID_HOME=C:\Users\marce\AppData\Local\Android\Sdk

D:\Programming\git\zxing>mvn -P build-android -nsu -B -Pjacoco install  -DskipTests
... now it worked
```
