### ISSUE TITLE
Uncertainty Around Licensing Terms

### ISSUE THREAD

**Issue by dvird** [zxing/zxing#1670]
Loving the work you've done here. I've been using your project and it's pretty awesome. Just wanted to bring up something that's been bugging me a bit - the license format.

Having a clear license is super important and makes it easy for everyone to know where they stand. I noticed that your license info is not so clear. Could you guys make it simpler to understand? Maybe in the readme file or somewhere else in the docs?

By the way, ever thought about monetizing your SDK/API with [Eartho](https://www.eartho.world/)? It helps with setting up license-based billing super easily. Might be something to check out.

Keep up the great work!

**Comment by srowen** [comment]
I assume this is spam bc of link and question
