### ISSUE TITLE
Code128 Barcode - Maximum Limit of content is 80 chars

### ISSUE THREAD

**Issue by himanshushukla254** [zxing/zxing#1672]
Hi Team, I was going through the code128 writer present in `com.google.zxing.oned` package and found that the max length of allowed content is set to 80.

Any reasons for setting this limit? I see code128 algo does not have any limits implicitly and other online platforms are also generating Code128 barcode with more than 80 chars.

Attached Screenshot from Code128Writer:

<img width="632" alt="image" src="https://github.com/zxing/zxing/assets/15158684/daeadfb5-0ffd-4394-9d94-dfc61f582605">

**Comment by srowen** [comment]
I'm not sure. Do you know if there is a max in any spec? If there's no evidence there is really a limit we could remove this, but there are practical upper limits for sure.

**Comment by himanshushukla254** [comment]
Not sure, There are different statements in many articles regarding the max-content length.
https://www.softmatic.com/barcode-code-128.html#128-max
https://stackoverflow.com/questions/24263237/what-is-the-maximum-length-of-a-code-128-barcode

Even this platform also supporting >80 chars
https://barcodeapi.org/index.html#128

**Comment by gredler** [comment]
For what it's worth, I had a look at my copy of the Code 128 spec (ISO/IEC 15417:2007) and don't see any formal maximum. I suspect this is more in the way of a sanity check (as far as my own experience goes, I don't think I've ever seen a Code 128 barcode longer than 50 characters or so in the wild).

**Comment by srowen** [comment]
I think it's fine to take out this limit, but, in practice you won't really be able to use longer barcodes well anyway

**Comment by himanshushukla254** [comment]
Yes, we can remove this forced check. This looks like a limitation in zxing as compared to other platforms.

**Comment by himanshushukla254** [comment]
The changes are already done for this. This will be available in the 3.5.3 release as per [#1675 ]. Hence, Closing this issue.
