### ISSUE TITLE
Random Scans in Low Light Conditions While Using zxing from Laptop Screen

### ISSUE THREAD

**Issue by sarkiroka** [zxing/zxing#1676]
Hello there,

I've been a big fan of zxing for quite some time, and I'm really thankful for this amazing package! However, I've stumbled upon a rather elusive issue that I thought should be brought to your attention.

**Issue:**
When I aim my camera towards my laptop screen in a dark room, zxing occasionally registers random scans. It's not immediate, but after holding my phone for a few seconds and with slight involuntary movements on my part, a scan is suddenly registered. I suspect it's due to a combination of factors like refresh rates, moire patterns, and perhaps even planetary alignment if we're being whimsical.

**Steps to Reproduce:**
Open the app and point the camera towards a laptop screen in a dark room.
Hold the phone with slight involuntary movements.
Notice that a scan may randomly be registered.
**Code Sample:**
Here's how I'm using the zxing package in my app:

```
    barcodeView = findViewById(R.id.barcodeView)
    barcodeView.setStatusText("")

    capture = CaptureManager(this, barcodeView)
    capture.initializeFromIntent(intent, savedInstanceState)
    capture.decode()

    barcodeView.decodeContinuous(object : BarcodeCallback {
        override fun barcodeResult(result: BarcodeResult) {
                var points="";
                result.resultPoints.forEach { point->
                    points+="[${point.x};${point.y}],"
                }
                Log.d("TAG", "barcodeResult: \n" +
                        "format: ${result.barcodeFormat} \n" +
                        "rawbytes: ${result.rawBytes}\n" +
                        "text: ${result.result.text}\n" +
                        "pointsSize: ${result.resultPoints.size}\n"+
                        "points: ${points}\n"+
                        "metadata: ${result.resultMetadata}"
                )
                handleResult(result.result.text)
            }
        override fun possibleResultPoints(resultPoints: List<ResultPoint>) {}
    })
```

**Dependency:**
```
    implementation("com.journeyapps:zxing-android-embedded:4.3.0")
```

**Recorded Log:**
```
barcodeResult: 
                                                                                                    format: UPC_E 
                                                                                                    rawbytes: null
                                                                                                    text: 11588160
                                                                                                    pointsSize: 2
                                                                                                    points: [755.5;351.0],[137.0;351.0],
                                                                                                    metadata: {ORIENTATION=180}
```

**Attachments:**
I have attached an image to give you an idea of what the camera sees around the time the random scan occurs.
[screenshot](https://pasteboard.co/NEdGwffytCuy.jpg)

**Note:**
I understand that active development for zxing might have ceased, but I genuinely love this package and it would mean the world to me if you could look into this issue. Thank you very much!

Best regards,
sarkiroka

**Comment by srowen** [comment]
I think you're saying the result is not correct - not the right barcode or there is no barcode at all in the image.

Yeah it's decoding many images per second and there's an increasing chance, especially in a noisy image, that it'll see a pattern of light and dark that's close enough to a barcode to register it. this happens most often with simple barcodes like UPC. It's a phantom scan.

You can of course limit the scan to the format you know you're looking for to avoid this - like a QR code.

If one were to start this library today and not in 2007, there are way smarter things that can be done with the 100x more computing power on phones that this is targeted at. For example, obviously CV models could easily tell you what region even looks like it's a barcode and then scan that.

This is just looking for light/dark patterns that seem to begin a barcode quite naively.
