### ISSUE TITLE
QR Scanner image is not working when try to get from gallery

### ISSUE THREAD

**Issue by Rameshmca13** [zxing/zxing#1687]
i have implemented zxing framework for the QR scanner and QR Reader image  from the gallery.

When we are try to scan - its working fine .

when we are try to scan in gallery and processing it we are getting the issue "**Error Domain=ZXErrorDomain Code=1002 "A barcode was not found in this image" UserInfo={NSLocalizedDescription=A barcode was not found in this image}**"

Please help me out the issue. I have attached one simple images also . 

![IMG_B62EE7F0FB83-1](https://github.com/zxing/zxing/assets/22642333/c07e171e-e42f-42f5-9926-1fc5116ee1b8)

**Comment by srowen** [comment]
Are you sure the QR code is not flipped over? it's at least rotated, which would be fine, but not mirrored. That much looks abnormal here.
Otherwise, not sure, I dont' investigate individual images that don't scan.
