### ISSUE TITLE
Sometime same Barcode return different result - Android

### ISSUE THREAD

**Issue by drcmehul** [zxing/zxing#1698]
I am using [https://barcode.tec-it.com/en/] for generate dummy barcode but whenever i scan from my mobile app in which i have integrated zxing library. it sometime returning different value in same barcode scan.

This scenario not happening always but accidentally sometime happening. anyone facing same issue and resolved any tactics ?

below barcode i am scanning.

![image](https://github.com/zxing/zxing/assets/134578127/44c1fc46-ee16-42c5-9edd-60a62f68d399)

Thanks.

**Comment by srowen** [comment]
Try turning off scanning for anything except Code 128. You didn't say, but I assume the false read is for a different format
