### ISSUE TITLE
 QR Scanner is not working when try to scan some QR code

### ISSUE THREAD

**Issue by AminDodiya** [zxing/zxing#1700]
i have implemented zxing framework for the QR scanner.

When we are try to scan - its not working some time

When we try to scan QR code but not getting URL from QR code.I getting blank string.I attached my code SS.

Please help me out the issue. I have attached one video.

https://github.com/zxing/zxing/assets/17842985/49146b
![Screenshot from 2023-10-06 10-55-53](https://github.com/zxing/zxing/assets/17842985/3ed07a14-e9ba-4464-ab98-10179248258e)
![Screenshot from 2023-10-06 10-56-09](https://github.com/zxing/zxing/assets/17842985/88fa097e-23b4-494b-918f-bfdad04708c5)
![Screenshot from 2023-10-06 10-56-18](https://github.com/zxing/zxing/assets/17842985/166fc528-a562-473e-aaa6-8b0aac3e059e)
![Screenshot from 2023-10-06 10-56-37](https://github.com/zxing/zxing/assets/17842985/9f538986-a493-4a86-a885-b3b3f3fa6d98)
e5-4a37-4bbe-b3bd-cc89187ca107

**Comment by srowen** [comment]
This is likely an issue with your code or the barcode, not the library. You'd have to narrow this down to a specific issue with a PR

**Comment by AminDodiya** [comment]
Can you give more details how can i solve this point
