### ISSUE TITLE
need to generate QR code with ECC-Q and version 2, because of the size of data encoding in QR code, it is generating with version3

### ISSUE THREAD

**Issue by kamalvamshi4** [zxing/zxing#1708]
we are using zxing to generate qr code in oracle 10g, length of the string encoding in qr code is restricting us to create qr code with ecc-Q and version-2, it is allowing version-3.

**Comment by srowen** [comment]
That means indeed you have too much data to store in that version with that much EC.

**Comment by kamalvamshi4** [comment]
we are trying to store the string of length 30 characters, the ask is , can we able to generate a QR code with below criteria

1) ECC-Q
2) version -2
3) string length - 30 characters(alphanumeric) , 

could you please confirm is it possible? do we need any customizations required to achieve this? appreciate your help

**Comment by srowen** [comment]
No, please see the QR code spec. Max characters would be 29 for alpha + Q. Just use M EC level and would fit

**Comment by kamalvamshi4** [comment]
requirement is to fit 30 characters in ECC-Q,  is there any other way to alter the code to make it fit in Q?

**Comment by srowen** [comment]
No, it is prohibited by the QR code specification. Limit is 29
