### ISSUE TITLE
Can JDK17 Build zxing 3.5.1 and Later?

### ISSUE THREAD

**Issue by ElisabethJing** [zxing/zxing#1713]
Can JDK17 Build zxing 3.5.1 and Later?

**Comment by Gary19751957** [comment]
What is this

**Comment by srowen** [comment]
Yes. You can see that in the CI CD builds here

**Comment by ElisabethJing** [comment]
Thank you.

**Comment by ElisabethJing** [comment]
> Yes. You can see that in the CI CD builds here

Thank you.
