### ISSUE TITLE
Decode barcode contain arabic letters problem

### ISSUE THREAD

**Issue by asattot** [zxing/zxing#1716]
Hello, thank you for this perfect project.

The problem is when i try to decode a barcode with type pdf417 that contain Arabic letters i got this result:
ÇÍãÏ#ÓÊæÊ#ãÍãÏ#ÑíãÇ #ÏãÔÞ 10-5-1995#

This line should be separated by (#) 
Firstname
Lastname
Fathername
Mothername
birth place and date
but this data should be visible in arabic letters like this:
احمد#ستوت#محمد#ريما#دمشق 10-5-1995#

This is my try on zxing.org:
https://zxing.org/w/decode?u=https%3A%2F%2Flh3.googleusercontent.com%2Fu%2F0%2Fdrive-viewer%2FAK7aPaDbkl8cItgLWrNYKB9zkAPcRm51WNG54PZUjtjocJNgY-GaEqh5KpgqVir2Ii3C71mSZVmw50pKmI-bq6Cga_zKLudC%3Dw1920-h913

And all the printed barcode in this way, i try more than once also same results.

By the way when i read this barcode in a barcode reader there is no problem and the data visible correctly but i need to decode via software.

Is this problem from the encoding barcode ?!

I hope i describe the problem very well, Thank you very much :)

**Comment by oehhar** [comment]
Hi asattot,
the right way to encode Arabic glyphs in Barcode is to use an appropriate ECI. You may try the open source Program zint, which does that correctly.
Unfortunately, 90% of the barcode readers out there including zxing is completly broken in this aspect. Consider to use zxing-cpp, which does it right.

Take care,
Harald

**Comment by oehhar** [comment]
You may also post the generated code as a graphic here. I may check it. And please post the contained data. I may create a code with ECI.

**Comment by asattot** [comment]
@srowen 
Thank you :)

**Comment by oehhar** [comment]
I am sorry, I was not able to scan the code. It must have a very high error level setting to be large like that. Or there is another issue, I don't know.

Sorry,
Harald
