### ISSUE TITLE
A possible PDF encoding bug

### ISSUE THREAD

**Issue by tohidemyname** [zxing/zxing#1721]
encodeNumeric(ECIInput,int,int,StringBuilder)@PDF417HighLevelEncoder has the following code:

private static void encodeNumeric(ECIInput input, int startpos, int count, StringBuilder sb) {
    int idx = 0;
    StringBuilder tmp = new StringBuilder(count / 3 + 1);
    BigInteger num900 = BigInteger.valueOf(900);
    BigInteger num0 = BigInteger.valueOf(0);
    while (idx < count) {
      tmp.setLength(0);
      int len = Math.min(44, count - idx);
      String part = "1" + input.subSequence(startpos + idx, startpos + idx + len);
      BigInteger bigint = new BigInteger(part);
      do {
        tmp.append((char) bigint.mod(num900).intValue());
        bigint = bigint.divide(num900);
      } while (!bigint.equals(num0));

      //Reverse temporary string
      for (int i = tmp.length() - 1; i >= 0; i--) {
        sb.append(tmp.charAt(i));
      }
      idx += len;
    }
  }
I notice that Zxing.net is ported from the above code, but they fixed a bug in their ported code:

- String part = '1' + msg.Substring(startpos + idx, startpos + idx + len);
 +  String part = '1' + msg.Substring(startpos + idx, len);

The patch is as follows:
https://github.com/micjahn/ZXing.Net/commit/75ef6554a0b318178729a93c12f6accfd8cd0c32

**Comment by srowen** [comment]
What's the bug?
The second arg to Java subString is end, not length, so I think those are the same logic, not a difference

**Comment by tohidemyname** [comment]
Look like a difference in APIs. This is not a bug. Sorry for not noticing the differnces.
