### ISSUE TITLE
Unable to scan this QR Code (which is not in good shape)

### ISSUE THREAD

**Issue by yong2khoo-lm** [zxing/zxing#1729]
Hi All,

First, thanks for the project. We mostly are able to scan the QR code if the condition is good.
However, if there are some imperfection like below, then it is not scannable. (tested with v3.5.1 and v3.5.2)
![image](https://github.com/zxing/zxing/assets/51041738/d04d37ae-cad6-4133-9122-2fe45ca4e828)
Content: `B(1)|45|5|410|0|17|17|0012002485`

However, it is worthy to mention that, this above QR code is scannable with a third-party app with ease.
Can anyone verify this?

Thanks.

**Comment by srowen** [comment]
Yes it's too distorted. This project is not maintained, there will be no updates to scanning.
