### ISSUE TITLE
Defining a Margin on Web API gives “Bad Request”

### ISSUE THREAD

**Issue by FrederikWolter** [zxing/zxing#1738]
# Bug Report
### Working Example
Calling the web API directly works as expected:
[https://zxing.org/w/chart?cht=qr&chs=230x230&chld=H&chl=123456]()

![chart](https://zxing.org/w/chart?cht=qr&chs=230x230&chld=H&chl=123456)

### Broken Example
Trying to change the margin (aka. _quiet zone_) of the resulting qr code, e.g. by adding **`|1`** to `chld` for one pixel, breaks the request.
[https://zxing.org/w/chart?cht=qr&chs=230x230&chld=H|1&chl=123456]() results in **Status 400** and not showing anything.

This is unexpected as this feature is seemingly implemented [here](https://github.com/zxing/zxing/blob/0b9959afb70b67771d09ad7488a5378c678f189f/zxingorg/src/main/java/com/google/zxing/web/ChartServlet.java#L171):
```java
String ldString = request.getParameter("chld");
if (ldString != null) {
    int pipeIndex = ldString.indexOf('|');
    if (pipeIndex < 0) {
        // Only an EC level
        ecLevel = ErrorCorrectionLevel.valueOf(ldString);
    } else {
        ecLevel = ErrorCorrectionLevel.valueOf(ldString.substring(0, pipeIndex));
        margin = Integer.parseInt(ldString.substring(pipeIndex + 1));
        Preconditions.checkArgument(margin > 0, "Bad margin");
    }
}
```
Furthermore, it not returning a “Bad margin” nor any other error message is confusing. 
Is this version of code running on the web server?

Thanks for your work and support in advance!
Frederik

**Comment by srowen** [comment]
You will need to url-encode the pipe character in URLs generally, I believe, and that's the same here. Use %7C and there is no error

**Comment by FrederikWolter** [comment]
Thanks for the solution and again all your work!

Although it's kind of unintuitive you have to do that, science the Google API accepts the request unsing the pipe char:
[https://chart.googleapis.com/chart?chs=230x230&cht=qr&chld=h|1&chl=123456789]()

![chart](https://chart.googleapis.com/chart?chs=230x230&cht=qr&chld=h|1&chl=123456789)

**Comment by srowen** [comment]
I imagine the old chart server code is technically wrong to allow this character without escaping, but general servlet engines enforce it. See for example.https://itecnote.com/tecnote/tomcat-how-to-make-apache-tomcat-8-0-41-to-allow-the-pipe-character-in-url-get-request/
