### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by kshitiz305** [zxing/zxing#1741]
<img width="382" alt="image" src="https://github.com/zxing/zxing/assets/38988779/c920f638-057c-4bbf-83d3-b0673b4a23c0">

The link seems to be broken and if you could suggest me to a new link that could be replaced.

### Questions

Questions should be asked on the mailing list:
https://groups.google.com/forum/#!forum/zxing

### Feature Requests

Feature requests are not accepted and will generally be closed.
Feature requests with a pull request may be accepted. When in doubt, discuss on the
mailing list first.

### Bug Reports

Bug reports must have enough detail to understand and reproduce the problem. Inadequate
bug reports will be closed with a request for more information.

Bug reports without an associated pull request are not likely to be addressed, but will be
left open for some time to see if anyone can contribute a solution. However, bug reports
with a pull request are likely to be merged promptly.

**Comment by srowen** [comment]
Looks like this isn't offered for OSS projects anymore and should be deleted
