### ISSUE TITLE
Issues in decoding PDF 417 format Barcodes

### ISSUE THREAD

**Issue by adiv5** [zxing/zxing#1742]
I am trying to use `zxing` to decode PDF417 images. However Im getting an error message as follows:

`ValueError: Unknown format code 'x' for object of type 'str'`

Error seems to be in the `__repr__` of the [BarCode Class](https://github.com/dlenski/python-zxing/blob/master/zxing/__init__.py)

Here is the File i'm using 
![](https://github.com/zxing/zxing/assets/22361618/85571d0b-e2ae-4a7d-9aac-aea482c7abcb)

Can I understand if there is any workaround for the same?

**Comment by srowen** [comment]
Wrong project. You can see you link to code in another repo

**Comment by adiv5** [comment]
My bad.

**Comment by axxel** [comment]
Maybe https://pypi.org/project/zxing-cpp/ can be solution for you.
