### ISSUE TITLE
Docs are broken, with core docs missing

### ISSUE THREAD

**Issue by dallasgutauckis** [zxing/zxing#1748]
The core docs (https://zxing.github.io/zxing/core/index.html) linked to from the main docs site (https://zxing.github.io/zxing/) are missing, and templating also seems to be broken:

<img width="1165" alt="image" src="https://github.com/zxing/zxing/assets/117083/fad9f3bc-e964-4935-8525-6735deb4e0d9">

**Comment by srowen** [comment]
Yep, been that way for years and I don't know how to get the site plugin to generate those correctly, sorry.
If you have a fix, open a PR
