### ISSUE TITLE
Discussion forum inaccessible

### ISSUE THREAD

**Issue by gredler** [zxing/zxing#1751]
The discussion forum linked from the README is currently showing the following message:

> Banned content warning
>
> zxing has been identified as containing spam, malware, or other malicious content.
> 
> For more information about content policies on Google Groups see our [Help Center article](https://support.google.com/groups/answer/141369?hl=en) on abuse and our [Terms of Service](https://policies.google.com/terms?hl=en).

**Comment by srowen** [comment]
Huh, no idea why. There was little activity anyway, and some spam (that I deleted) once in a while. Oh well, I'll remove the link
