### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by mid-kid** [zxing/zxing#1756]
I've been using this app for as long as I can remember, usually getting it from F-Droid, and it's installed and worked fine for all this time.

Unfortunately, as of android 14, it now refuses to install. I wonder if there's interest in resolving it or if I should look for something else.

**Comment by rafaelmoreno29** [comment]
I'm having the same problem. :(

**Comment by srowen** [comment]
There will be no updates, sorry. It will no longer work with later Android versions.

**Comment by mid-kid** [comment]
Shame, but understandable. Thanks for all the years of service!

**Comment by Shipon1880** [comment]
Give me plus
