### ISSUE TITLE
pdf417 encode error java.lang.ArrayIndexOutOfBoundsException when using CHARACTER_SET ISO-8859-15

### ISSUE THREAD

**Issue by cuongtranba** [zxing/zxing#1761]
Hello,

I encountered an error while attempting to create a PDF417 barcode with character set ISO-8859-15. Here's the relevant code snippet:
```java
String content = "€ 123,45";

Map<EncodeHintType, Object> hints = new HashMap<>();
hints.put(EncodeHintType.ERROR_CORRECTION, 4);
hints.put(EncodeHintType.PDF417_DIMENSIONS, new com.google.zxing.pdf417.encoder.Dimensions(7, 7, 1, 300));
hints.put(EncodeHintType.MARGIN, 0);
hints.put(EncodeHintType.CHARACTER_SET, "ISO-8859-15");
hints.put(EncodeHintType.PDF417_COMPACTION, com.google.zxing.pdf417.encoder.Compaction.TEXT);

MultiFormatWriter writer = new MultiFormatWriter();
BitMatrix bitMatrix = writer.encode(content, BarcodeFormat.PDF_417, 200, 100, hints);
```

The error message I received is as follows:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 8364 out of bounds for length 128
        at com.google.zxing.pdf417.encoder.PDF417HighLevelEncoder.isMixed(PDF417HighLevelEncoder.java:557)
        at com.google.zxing.pdf417.encoder.PDF417HighLevelEncoder.encodeText(PDF417HighLevelEncoder.java:325)
        at com.google.zxing.pdf417.encoder.PDF417HighLevelEncoder.encodeHighLevel(PDF417HighLevelEncoder.java:212)
        at com.google.zxing.pdf417.encoder.PDF417.generateBarcodeLogic(PDF417.java:659)
        at com.google.zxing.pdf417.PDF417Writer.bitMatrixFromEncoder(PDF417Writer.java:111)
        at com.google.zxing.pdf417.PDF417Writer.encode(PDF417Writer.java:90)
        at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
        at barcode.BarcodeGenerator.generate(BarcodeGenerator.java:48)
        at test.test.main(test.java:11)
```

thank you

**Comment by srowen** [comment]
Looks legitimate, but, I can't debug it. If you have a pull request, feel free to open it here

**Comment by ftiercelin** [comment]
@cuongtranba 
I have tried the following and it seems to work:
```java
		String content = "€ 123,45";
		Map<EncodeHintType, Object> hints = new HashMap<>();
		hints.put(EncodeHintType.ERROR_CORRECTION, 4);
		hints.put(EncodeHintType.PDF417_DIMENSIONS, new com.google.zxing.pdf417.encoder.Dimensions(7, 7, 1, 300));
		hints.put(EncodeHintType.MARGIN, 0);
		hints.put(EncodeHintType.PDF417_AUTO_ECI, true);

		MultiFormatWriter writer = new MultiFormatWriter();
		BitMatrix bitMatrix = writer.encode(content, BarcodeFormat.PDF_417, 200, 100, hints);
```
PDF417 was initially intended to use [CP437](https://en.wikipedia.org/wiki/Code_page_437) which only supports 255 characters, not including things like €. To use such character, I think you need to turn on the ECI.

**Comment by ftiercelin** [comment]
@srowen 
The test case for this one is not supposed to work as a TEXT PDF417 can't encode non standard characters like €.
But the exception currently thrown isn't explicit, although it references Unicode 8364 (€) : 
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 8364 out of bounds for length 128`

I suggest to detect the attempt to use characters outside of 0...255 with a more explicit exception:
`Writer Non-encodable character detected: € (Unicode: 8364). Consider specifying Compaction.AUTO instead of Compaction.TEXT` 
... in a fashion similar to other checks performed in PDF417HighLevelEncoder.encodeHighLevel

If you agree with this approach, I'll submit a PR.

Thanks

**Comment by srowen** [comment]
Yeah maybe test whether the text is encodable with the target charset first; I think that's fine.
Whatever follows how other formats handle this is best.
