### ISSUE TITLE
Don't decode QR_CODE.

### ISSUE THREAD

**Issue by kkkaktusss** [zxing/zxing#1774]
Hi, a i have a bit question. When I try to decode image, barcodereader can't find a QR_CODE format, but in "https://zxing.org" this type is recoginzed(attach a proof in picture). 
My code return EAN_8, UPC_E,  but not a QR_CODE.
`                var reader = new BarcodeReader() { AutoRotate = true};
                reader.Options.TryHarder = true;
                reader.Options.PossibleFormats = new BarcodeFormat[] { BarcodeFormat.QR_CODE, BarcodeFormat.EAN_8, BarcodeFormat.UPC_E };
                var result2 = reader.DecodeMultiple(imageMat);`

![2024-03-19_14-57-53](https://github.com/zxing/zxing/assets/66029262/6335adaa-0f8b-4dc0-a42f-c4fdb0beaf27)

![photo_2024-03-19_14-55-52](https://github.com/zxing/zxing/assets/66029262/14791de1-8cd1-4cea-96d2-a2a4fdbb7d01)

Can you help me?

**Comment by Rozhdestvensk1y** [comment]
try restart application

**Comment by srowen** [comment]
You're actually asking about a different project here, a port of this library.
