### ISSUE TITLE
Why zxing can not decode this qrcode image?

### ISSUE THREAD

**Issue by baigeta** [zxing/zxing#1786]
为什么不识别这个二维码呢？
Why zxing can not decode this qrcode image?
Thank you for your assist!!
![cropped20240307007764_78265 pdf png](https://github.com/zxing/zxing/assets/50309158/ab9ceef3-8729-45c3-9d44-c30a67dd9a0f)

The version is 3.4.1
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>3.5.3</version>
        </dependency>
The Exception info is :
com.google.zxing.NotFoundException

**Comment by srowen** [comment]
It's far too distorted. Look at the finder pattern shapes.
