### ISSUE TITLE
Letters in Croatian ćčšžšđ

### ISSUE THREAD

**Issue by dmilasin76** [zxing/zxing#1787]
I have a problem when scanning standard 2d barcodes in PDF_417 format. It reads them without problems, but I have barcodes of the same structure and composition, in which the Croatian letters čšđž are read, and when scanning some barcodes, some barcodes are read correctly and some are not, that is, where the letters čšđž are, it places signs.
When I try let's say this:
` decodedData = new String(scannedData.getBytes("ISO-8859-1"), "UTF-8");`
then read some barcodes that he did not read correctly. But then some that he was reading correctly before the change he doesn't read correctly :)

**Comment by srowen** [comment]
It sounds like the barcodes are using the wrong encoding, or not specifying a custom encoding in an ECI segment, or otherwise not being guessed correctly. The right move is to use UTF-8, or use an ECI segment. Otherwise, this is possible.
