### ISSUE TITLE
MultiFormatReader unable to decode simple data matrix code (C#)

### ISSUE THREAD

**Issue by ilsebilse149** [zxing/zxing#1795]
Hey there,

I have a small function that reads codes from images. While that works with most codes and code types, it somehow fails with an fairly "easy" example data matrix code:

![datamatrix](https://github.com/zxing/zxing/assets/74191307/7d81e0a6-1d86-4b80-8f8b-f8e5d1bc4e94)

This is my code. Im using Visual Studio 22 and installed ZXing.Net (Version 0.16.8) via NuGet: 
```csharp
public static string ReadCode(Mat image)
{
    MultiFormatReader reader = new MultiFormatReader();
    var lum = new MatLuminanceSource(image);
    BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(lum));

    var result = reader.decode(binaryBitmap, new Dictionary<DecodeHintType, object>() { { DecodeHintType.TRY_HARDER, true } });
    if (result == null) return "";
    return result.Text;     
}
```
What could be the cause for this issue? I tried reading the code with different Websites/ tools and they all are able to read the code. 

If you have further questions, im glad to answer them! 
Thanks in advance :)

**Comment by srowen** [comment]
Try "TRY_HARDER" mode, or restrict to Data Matrix when scanning, but, I think the problem is that tiny gap between the modules at the right side and bottom. That's not valid. Comically, blurring the image a bit should make it work too if that's the issue.
