### ISSUE TITLE
Zxing is not working with PDF417 for south african driving liecenses

### ISSUE THREAD

**Issue by pratikukheshe** [zxing/zxing#1803]
Currently, I am implementing the zxing(3.5.3) jar to read barcode from the images. In some of the cases, I am not getting the barcode in the image and in some cases result is not proper. I am expecting the 720 bytes in result but getting 1063 bytes. Here, is the sample code

`   

                try {
		BufferedImage image = ImageIO.read(file);
		LuminanceSource ls = new BufferedImageLuminanceSource(image);
		BinaryBitmap bmp = new BinaryBitmap(new HybridBinarizer(ls));

		GenericMultipleBarcodeReader reader = new GenericMultipleBarcodeReader(new MultiFormatReader());

		Map<DecodeHintType, Object> decodeHints = new EnumMap<>(DecodeHintType.class);
		decodeHints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
		decodeHints.put(DecodeHintType.POSSIBLE_FORMATS, EnumSet.of(BarcodeFormat.PDF_417));

		com.google.zxing.Result[] results1 = reader.decodeMultiple(bmp, decodeHints);
		int i = 0;
		for (com.google.zxing.Result result : results1) {
			System.out.println("Barcode " + ++i + ": " + result.getText());
			result.getResultPoints();
		//	parseData(decryptData(result.getResultPoints())) ;
		}
	} catch (Exception e) {
		System.err.println("Error: " + e.getMessage());
	}`

**Comment by srowen** [comment]
Sorry, can't help debug individual scans. Maybe you're looking at some base64-encoding of data rather than data

**Comment by pratikukheshe** [comment]
Thanks Srowen for your quick response.
Let me give some more background to you.
Currently, I am using zxing 3.5.3 APIs to read the data from African driving license barcode using below code. 

try {
	BufferedImage image = ImageIO.read(file);
	LuminanceSource ls = new BufferedImageLuminanceSource(image);
	BinaryBitmap bmp = new BinaryBitmap(new HybridBinarizer(ls));
	GenericMultipleBarcodeReader reader = new GenericMultipleBarcodeReader(new MultiFormatReader());
	Map<DecodeHintType, Object> decodeHints = new EnumMap<>(DecodeHintType.class);
	decodeHints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
	com.google.zxing.Result[] results1 = reader.decodeMultiple(bmp, decodeHints);
	for (com.google.zxing.Result result : results1) {
		System.out.println("Barcode " + ++i + ": " + result.getText());
		//here I am expecting 720 Bytes
		System.out.println("Barcode " + ++i + ": " + result.getText().getBytes());
	}
} catch (Exception e) {
	System.err.println("Error: " + e.getMessage());
}



Now as per this link - [(https://stackoverflow.com/questions/17549231/decode-south-african-za-drivers-license)]

this barcode contains the encrypted data which we need to decrypt and parse.

Using a commercial libraries I am getting the data which are 720 Bytes and I have written the logic to decrypt and parse that data.
Now my expectation is that zxing should also return the 720 Bytes at mentioned point as comment in code, so that I can decrypt and parse it but here it is returning 1033 Bytes and I am not able to parse it.

So, Is that something wrong from my end in code or is it the limitation of zxing?
