### ISSUE TITLE
How to get zxingorg 3.5.3-SNAPSHOT entity package

### ISSUE THREAD

**Issue by ElisabethJing** [zxing/zxing#1811]
zxing-3.5.3 depends on zxingorg 3.5.3-SNAPSHOT, which is not available at https://repo1.maven.org/maven2/com/google/zxing/zxingorg/. How can I obtain it?

**Comment by ElisabethJing** [comment]
Is zxingorg 3.5.3-SNAPSHOT an official release?

**Comment by srowen** [comment]
No, that's just a snapshot version. Oops, is there a dependency left at the snapshot version somewhere?

**Comment by ElisabethJing** [comment]
Is zxing-3.5.3 an official release? Doesn't zxing-3.5.3 force dependency on zxingorg?

**Comment by srowen** [comment]
Yes, 3.5.3 was the last release. I'm not sure what you're asking here, can you be more specific?

**Comment by ElisabethJing** [comment]
Is it possible to integrate only zxing-3.5.3 and not zxingorg in the project?

**Comment by srowen** [comment]
Yes. Depend on the modules you actually want
