### ISSUE TITLE
Any barcode with an @ gets misidentified as an email address, disabling custom/web search

### ISSUE THREAD

**Issue by Klaws--** [zxing/zxing#1818]
Steps to reproduce (1):

Create a barcode for XY@asdf
Scan the barcode

Result: the barcode is correctly scanned and decoded, with two buttons at the bottom of the screen: "Send email" and "Add contact".

Expected result: same, but with buttons for "Web search" and "Custom search" (if set up).

Test case 2:
Same, but with barcode for @asdf

While I don't mind that the application considers anything which has an "@" inside worthy to be offered the option for email-related functions, it prevents easy searching for email addresses on the web and also scanning of product codes with an "@". And no, I have no clue who had this funny idea, but in this case, the first part before the "@" is a company code and the second part is the item code (yes, *that* order exactly...).

Proposed fix:

In EmailAddressResultHandler.java, lines 32-33 are
```
    R.string.button_email,
    R.string.button_add_contact
```
and might be changed to:
```
    R.string.button_custom_product_search,
    R.string.button_web_search,
    R.string.button_email,
    R.string.button_add_contact
```

For further consideration: I am undecided whether it would be a good idea to have custom search and web search buttons for every scan result. I guess it doesn't make sense for a VCard (lots of data inside) but might be nice for telephone numbers.

Anyone, any opinion?

**Comment by srowen** [comment]
I don't mind tightening up the very lenient check here: https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/client/result/EmailDoCoMoResultParser.java#L60
Feel free to propose something that maybe looks for at least something like a domain after "@"

The app itself can't be updated, but I think a conservative change to that logic is not bad

**Comment by ANAGH1234** [comment]
see this code-private int[] determineDimensions(int sourceCodeWords, int errorCorrectionCodeWords) throws WriterException {
    float ratio = 0.0f;
    int[] dimension = null;

    int currentCols = minCols;
    for (int cols = minCols; cols <= maxCols; cols++) {
        currentCols = cols;
        int rows = calculateNumberOfRows(sourceCodeWords, errorCorrectionCodeWords, cols);

        if (rows < minRows) {
            break; // No need to check further as rows will only decrease
        }

        if (rows > maxRows) {
            continue; // Skip this column count as it exceeds max rows
        }

        float newRatio = ((float) (17 * cols + 69) * DEFAULT_MODULE_WIDTH) / (rows * HEIGHT);

        // Update if the new ratio is closer to the preferred ratio
        if (dimension == null || Math.abs(newRatio - PREFERRED_RATIO) < Math.abs(ratio - PREFERRED_RATIO)) {
            ratio = newRatio;
            dimension = new int[]{cols, rows};
        }
    }

    // Handle case when no suitable dimensions were found in the loop
    if (dimension == null) {
        int rows = calculateNumberOfRows(sourceCodeWords, errorCorrectionCodeWords, currentCols);
        if (rows >= minRows && rows <= maxRows) {
            dimension = new int[]{currentCols, rows};
        } else {
            throw new WriterException("Unable to fit message in columns");
        }
    }

    return dimension;
}
generatePDF417Image("0000000001000000022200000003330444400888888881010101010", 371, null);

**Comment by ftiercelin** [comment]
@srowen I think the email check using an alphanumeric REGEX doesn't account for email addresses like 建設省@gov.jp
Emails addresses with non alphanumeric characters, while very rare, are now allowed.

**Comment by srowen** [comment]
I agree; the tension is misidentifying other strings as emails with too lenient a check.
As I say feel free to open a PR with an argument for the change.

**Comment by ftiercelin** [comment]
> I agree; the tension is misidentifying other strings as emails with too lenient a check. As I say feel free to open a PR with an argument for the change.

don't I need privileges to create a branch and then a PR?
I tried creating one, but got a 403

**Comment by srowen** [comment]
As with most projects, no you do not create a branch in the project. You fork and open a PR from your fork.
