### ISSUE TITLE
BarCode Scanner device Orientation not changing in ipad and Tablet

### ISSUE THREAD

**Issue by Priyanka-art516** [zxing/zxing#1843]
Hi Team,
I am using a ZXing barcode scanner facing issues on my iPad and tablet where changing orientation from landscape to portrait or vice versa does not reflect with scanner orientation.
On other mobile devices it works fine. I have used MobileBarcodeScanningOptions and set AutoRotate as true.

<img width="581" alt="Screenshot 2024-08-20 173235" src="https://github.com/user-attachments/assets/32c0d03c-1372-4194-ae91-1c6f3dfec033">

Any leads appreciated

**Comment by srowen** [comment]
This is not related to the code in this project, but some port

**Comment by Priyanka-art516** [comment]
Is there any solution for this.
