### ISSUE TITLE
High CPU Usage Due to Invert Colors Function in QRCodeAnalyzer

### ISSUE THREAD

**Issue by uurcan** [zxing/zxing#1844]
I'm using the ZXing library for QR code detection in real-time using Android's CameraX API. To handle scenarios where QR codes are presented with inverted colors, I implemented an invertColors function in my code. However, this function significantly increases CPU usage, making the QR code detection process less efficient.

Problem:
The ZXing library currently does not natively support the detection of inverted QR codes. As a result, I have to implement custom solutions like color inversion, which leads to higher CPU consumption and impacts performance.

Code Example:
Below is a snippet of the code I'm using:

```
class QRCodeAnalyzer(
    private val onResult: (String) -> Unit
) : ImageAnalysis.Analyzer {

    //...

    private fun processImage(imageProxy: ImageProxy, data: ByteArray) {
        try {
            decodeQRCode(imageProxy, data)
        } catch (e: NotFoundException) {
            val invertedData = data.invertColors()
            try {
                decodeQRCode(imageProxy, invertedData)
            } catch (ex: Exception) {
                ex.printStackTrace()
            }
        }
    }

    private fun ByteArray.invertColors(): ByteArray {
        return map { (255 - (it.toInt() and 0xFF)).toByte() }.toByteArray()
    }

    //...
}
```

Impact:
The invertColors function, while necessary to handle inverted QR codes, consumes a significant amount of CPU resources. This inefficiency can lead to degraded performance, especially on lower-end devices or in applications requiring real-time processing.

**Comment by srowen** [comment]
First, inverted QR codes are not technically valid QR codes. But your app can scan for them this way, sure. It's up to you. It seems like you're saying your code is slow though, not the library.

But there is an impl of inverting an image here: https://github.com/zxing/zxing/blob/8944e607789b0847625f9962e90aab9901c731cd/core/src/main/java/com/google/zxing/InvertedLuminanceSource.java#L25

This at least only inverts what is read, and you can try to use it
