### ISSUE TITLE
Unable to scan QR codes with target logo

### ISSUE THREAD

**Issue by MHShetty** [zxing/zxing#1851]
The zxing library handles stylized QR codes very well, however trying to scan the following barcode doesn't lead to any results:

![qr-with-logo](https://github.com/user-attachments/assets/cfb14cac-cd06-428b-9674-165c8989ee22)

However, the following QR (after editing out the logo) gets scanned:

![qr-without-logo](https://github.com/user-attachments/assets/b0ef38a4-6694-4929-9180-2e7d05c8de0a)

Unsure what's causing this issue, but for confirmation, the QR with logo is scannable on the given link https://dnschecker.org/qr-code-scanner.php and the default scanner of iOS devices

**Comment by MHShetty** [comment]
?

**Comment by MHShetty** [comment]
@srowen Could you please mention the reason for closing the issue? It's really hard to know for sure at the moment

**Comment by srowen** [comment]
Please review the text you read and deleted when opening this issue. "Barcode doesn't scan" is not something that's accepted

**Comment by MHShetty** [comment]
Ah gotcha, thanks for the clarification and your valuable time!
