### ISSUE TITLE
The package product 'ZXingObjC' cannot be used as a dependency of this target because it uses unsafe build flags.

### ISSUE THREAD

**Issue by DLlzw** [zxing/zxing#1871]
The package product 'ZXingObjC' cannot be used as a dependency of this target because it uses unsafe build flags.
in xcode 15.2
<img width="484" alt="image" src="https://github.com/user-attachments/assets/abebec50-1462-4e06-9bb8-fb296eb463d8">

**Comment by srowen** [comment]
Wrong project
