### ISSUE TITLE
GS1 Datamatrix uses ]d1 and creates invalid Datamatrix-Code

### ISSUE THREAD

**Issue by recodyx** [zxing/zxing#1881]
[GS1 Decoding specification](https://www.gs1.org/standards/gs1-datamatrix-guideline/25#3-Reading-and-decoding-GS1-DataMatrix+3-3-Decoding)

Code for creating GS1 Datamatrix:

```
...

Map<EncodeHintType, Object> hints = new EnumMap<EncodeHintType, Object>(EncodeHintType.class);
hints.put(EncodeHintType.CHARACTER_SET, "UTF-8");
hints.put(EncodeHintType.MARGIN, 0);
hints.put(EncodeHintType.GS1_FORMAT, true);


BitMatrix bitMatrix = new MultiFormatWriter().encode(content, BarcodeFormat.DATA_MATRIX, width, height, hints);
...
```

Using Version 3.5.3
Java 17, Windows 10

![gs1](https://github.com/user-attachments/assets/62ad27e8-868a-47ee-b552-44850b6a53f9)

**Comment by ftiercelin** [comment]
Hi @recodyx , do you want to close this issue?

**Comment by jacky8466** [comment]
> ok sorry I fixed it. I have used the wrong SEPARATOR_CHAR. instead of char 29 I've used '\u001D' ...
> 
> I did not know that the separator determines the symbology identifier.

Can using zxing generate standard GS1 DM codes?Can you generate and parse GS1 DM code in practical use with zxing? Can you provide sample code? thank you
