### ISSUE TITLE
Negative scan doesn't work

### ISSUE THREAD

**Issue by castersju** [zxing/zxing#194]
Sorry for my english, I'm a french user ;-)

All is in title. Try to scan a white code with a black background. That doesn't work for me. 
Tried with a Google Nexus 5.
Version 4.7.0 of Barcode Scanner

I hope it will be fixed soon.

**Comment by wfred101** [comment]
The negative QR-Code is specified in ISO/IEC 18004. This should work as well as a negative data matrix (ISO/IEC 16022). Bar Codes are specified to use dark bars and light spaces only. In standardization negative bar codes don't exist.

**Comment by srowen** [comment]
White-on-black barcodes are an optional part of the QR code and DM specs. I don't think they are 'standard' for 1D symbologies. Hence there is a separate mode you enable to scan for them. However for reasons I don't understand the negative camera mode doesn't enable on some Android devices. This is really about support for camera color mode `negative`, not a question of the spec.

**Comment by wfred101** [comment]
Negative is for Data Matrix and QR-Code in the normative part of the
standard. That means mandatory.
Negative is not specified for any bar code. That means optional.


Am 08.03.2015 um 14:41 schrieb Sean Owen:

**Comment by srowen** [comment]
Read section 5.2 of ISO 18004, where it marks reflectance reversal as optional for QR codes. Section 4.2 of ISO 16022 also marks this as an "additional" feature, but then actually marks reflectance reversal alone as non-optional with every other additional feature as optional. I think that means DM should read white on black too.

In any event I'm afraid I am not going to change this about the app at this stage, but would accept a fix to at least get the invert-image setting working on devices where it's not.

**Comment by wfred101** [comment]
Chapter 5.2 of ISO/IEC 18004 is this
Reflectance reversal
Symbols are intended to be read when marked so that the image is either
dark on light or light on dark
(see Figures 1 and 2). The specifications in this International Standard
are based on dark images on a
light background, therefore in the case of symbols produced with
reflectance reversal references to dark
or light modules should be taken as references to light or dark modules
respectively.

Maybe its helps somebody who is still working at Zxing.

Am 09.03.2015 um 20:28 schrieb Sean Owen:

**Comment by srowen** [comment]
"The use of the following additional features is optional in QR Code 2005:"

**Comment by brysonthor** [comment]
How does one enable inverted scan?

**Comment by wfred101** [comment]
We have had a version which was able to scan inverted codes. For some
reasons it was not accepted here as far as I remember.

Am 10.09.2015 um 00:53 schrieb brysonthor:

**Comment by boschsi** [comment]
I have the same problem, I have tried with Barcode Scanner app also, but it doesn't work with nexus 5, it opens negative screen for a while then changes back to normal screen. I've tried with android 4.4.4 and 5.1.1

**Comment by naritakung** [comment]
firstprom007@gmail.com

**Comment by ngfx** [comment]
Hello Sean Owen @srowen , I got the same problem and I'd like to know whether this issue will be fixed in short term in your library. Thank you very much.

**Comment by tanelihuuskonen** [comment]
I don't really see the point of changing the mode of the camera to scan inverted barcodes. The following code worked fine on @castersju 's examples:

`bitmap = new BinaryBitmap(new HybridBinarizer(source.invert()));`
`result = multiFormatReader.decode(bitmap, hints);`

I'm working on a proper pull request.

**Comment by srowen** [comment]
The upside was that this would occur in hardware, or at least some native code somewhere in the driver, I presume. The visual effect was kind of cool too. But, as it has some problems working, I don't mind this changing to just flip the bits in the Java code. That operation is pretty fast.

**Comment by diegopaso** [comment]
The mode of the camera to scan inverted barcodes should not exist and it should be automatic as iPhone users or another apps.

A lot of Android users doesn´t know even that the option exists and they cannot read a lot of bidis that are in their common lives.

**Comment by Cafune** [comment]
We can all agree that that inverted barcodes are an optional part of the spec, but we can also agree that they're seeing more and more use and failure/refusal to support a feature while competitors do is silly.

**Comment by davidjonker** [comment]
Hello, I'm also facing same issue, Can you please tell me exact solution for invert QR Codes?

**Comment by L4rS6** [comment]
I'm interested in a solution as well. Thank you in advance!

**Comment by uniphonic** [comment]
I'm also interested in a solution for inverted barcodes. Has anyone come up with one?

**Comment by manijshrestha** [comment]
@uniphonic, @davidjonker , @L4rS6 yes there is a solution for this. I have put a PR request in barcodescanner lib here: https://github.com/dm77/barcodescanner/pull/265 Looks like maintainer hasn't been too active lately. Hopefully it will be merged soon.

**Comment by 774163977** [comment]
ZTE

**Comment by 774163977** [comment]
Thanks for your time today and tomorrow and will be back in the office in the afternoon

**Comment by 774163977** [comment]
Maraykm Yashab tomorrow you are invited to the ceremony in my house and who can attend will get me on the gift of two of my coming back

**Comment by Nfinished** [comment]
What is happening

**Comment by nevercast** [comment]
https://github.com/dm77/barcodescanner/pull/265 was merged. Is this issue ready to be closed?

**Comment by ao2** [comment]
FWIW I agree with @diegopaso from https://github.com/zxing/zxing/issues/194#issuecomment-256604107 that automatic detection of inverted codes would be the most user friendly.

And https://github.com/dm77/barcodescanner/pull/265 seems like an improvement.

I'd argue that having this in the library would be the most beneficial instead of letting each separate App duplicate the solution.

However there is the problem of the overhead introduced by processing the frame twice (original and inverted), has anyone measured the impact of this?

Maybe the automatic detection of inverted codes can be offered an an optional feature of the library, and user apps can opt-in by calling a method or by passing a parameter instead of open coding the solution.

Thanks,
   Antonio

**Comment by srowen** [comment]
All of this already exists, just not enabled by default. It might be reasonable to enable it now just because phone CPUs are much faster than 8 years ago

**Comment by ao2** [comment]
> All of this already exists, just not enabled by default. It might be reasonable to enable it now just because phone CPUs are much faster than 8 years ago

Do you mean that the library already has code to try and detect the inverted image each time?
Once enabled will the double processing be always active? Or can it be made optional for user code?

Thanks,
   Antonio

**Comment by srowen** [comment]
There is an option for it in the app. In user code, you'd have to flip the image but there is a method to do that. Maybe could be another decode hint to try both.

**Comment by ao2** [comment]
Yes, what i was referring to was **automatic** detection of inverted codes, and for that both the original and the inverted image have to be tried for each frame.

**Comment by rockstore** [comment]
execure me, when I make "disable_metering" disable, the invert_scan does not work, can you give me some help?

**Comment by srowen** [comment]
I'm not able to update the Android app on Play anymore, so these issues will not get fixed.

**Comment by andreygursky** [comment]
@srowen, luckily your app can be obtained not only in Google Playstore but also from F-Droid:
https://f-droid.org/en/packages/com.google.zxing.client.android/

And of course every user can build it from source. Thus fixing issues seems to me not to depend on the proprietary Google Playstore. Though it is (was) a nice to have way to distribute the prebuilt app.

**Comment by srowen** [comment]
That is right, but I haven't distributed it that way nor would it reach most users that way. The app and project are really EOL and just in maintenance mode so I think that is the last for the app.

**Comment by gvfbossa** [comment]
For the love of God.... Has someone made this thing work?
I need to read inverted colors QRCode but nothing seems to work....
I have tried to invert eh camera colors... wasn't able to....
I have tried to invert the image source... wasn't able to....
Please, someone, there is a solution to this?

**Comment by gvfbossa** [comment]
> I don't really see the point of changing the mode of the camera to scan inverted barcodes. The following code worked fine on @castersju 's examples:
> 
> `bitmap = new BinaryBitmap(new HybridBinarizer(source.invert()));`
> `result = multiFormatReader.decode(bitmap, hints);`
> 
> I'm working on a proper pull request.

Where on earth did you put that piece of code, so it worked? Please!

**Comment by manijshrestha** [comment]
@gvfbossa - this might help you - https://github.com/zxing/zxing/issues/194#issuecomment-284010397

**Comment by gvfbossa** [comment]
> @gvfbossa - this might help you - [#194 (comment)](https://github.com/zxing/zxing/issues/194#issuecomment-284010397)

Thank you very much. Can this module be used with Appcelerator Titanium? Or can it be incorporated by zxing ?

**Comment by manijshrestha** [comment]
@gvfbossa  - I have not used Titanium so can't confirm. zxing is now in maintenance mode. You can always fork the repo and make the necessary changes  if needed.
