### ISSUE TITLE
Add Support for Micro QR Code?

### ISSUE THREAD

**Issue by groucho23** [zxing/zxing#209]
It would be nice to be able scanning micro qr codes with the famous zxing library. are u planning to support it?

**Comment by KrasnayaPloshchad** [comment]
Micro QR was adopted as JIS X 0510 and it was released in November 2011.

**Comment by srowen** [comment]
Micro QR was standardized earlier in the main ISO spec, but, it's an optional element, and I have never seen it used. At this stage wouldn't consider a patch for it since the project is in maintenance mode only.

**Comment by leonardwoo** [comment]
Micro QRCode is already ISO/IEC 18004:2015 and ISO/IEC 23941:2022
