### ISSUE TITLE
QRCodeReader not decoding:com.google.zxing.NotFoundException

### ISSUE THREAD

**Issue by vivekratansinha** [zxing/zxing#216]
ZXing 3.1.1-SNAPSHOT

Encoded some UTF-8 text to QRCode.
QRCodeReader fails to decode with com.google.zxing.NotFoundException.

Enclosed is the QRCode in question.

![00023](https://cloud.githubusercontent.com/assets/8625707/4123968/cf4376a8-32d3-11e4-8e98-f9c088be721c.PNG)

**Comment by baichengzhou** [comment]
牛逼，解决我的问题了。

**Comment by baichengzhou** [comment]
我用zxing来解码的时候，普通的二维码能解析，但是中间带LOGO的解码的时候报错com.google.zxing.NotFoundException，虽然不是相同的问题，但是这个解决了我的问题。
hints.put(DecodeHintType.PURE_BARCODE, Boolean.TRUE);
完美！！！

**Comment by yoting** [comment]
hints.put(DecodeHintType.PURE_BARCODE, Boolean.TRUE);
是的加入这一句代码解决问题。。。。

**Comment by ysq1051838264** [comment]
hints.put(DecodeHintType.PURE_BARCODE, Boolean.TRUE);加上这，还是报这错误com.google.zxing.NotFoundException

**Comment by tanranran** [comment]
@ysq1051838264 
+1 

me too

zxing version 3.3.0

**Comment by Humilton** [comment]
试试 : hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
try : hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);

**Comment by dublinmiton** [comment]
Dublin Milton

**Comment by jinyu73** [comment]
js使用的话，怎么解决这种报错

**Comment by chengduHebiao** [comment]
but it didnt work for me ,so any other suggestion?

**Comment by baichengzhou** [comment]
I optimized zxing, the success rate is very high, you can test it
https://www.sojson.com/qr/deqr.html
https://www.sojson.com/qr/zxing.html

**Comment by chengduHebiao** [comment]
> I optimized zxing, the success rate is very high, you can test it
> https://www.sojson.com/qr/deqr.html
> https://www.sojson.com/qr/zxing.html

能给点建议和方向吗？

**Comment by jinyu73** [comment]
OK, let me have a look first




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"何彪"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 中午1:28
收件人:&nbsp;"zxing/zxing"<zxing@noreply.github.com&gt;;
抄送:&nbsp;"口含薄荷---心微凉"<1115741577@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题： &nbsp;回复：[zxing / zxing] QRCodeReader无法解码：com.google.zxing.NotFoundException（＃216）



 
我优化了zxing，成功率很高，可以对其进行测试
 https://www.sojson.com/qr/deqr.html 
 https://www.sojson.com/qr/zxing.html
  
能给点建议和方向吗？
  
— 
您收到此评论是因为您发表了评论。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by baichengzhou** [comment]
> > I optimized zxing, the success rate is very high, you can test it
> > https://www.sojson.com/qr/deqr.html
> > https://www.sojson.com/qr/zxing.html
> 
> 能给点建议和方向吗？

我就是把图片色差一直调整！直到出结果

**Comment by spkingr** [comment]
Encounter the same problem, solved with the correct colored QRcode image: white and black works fine, other colors produce exceptions.

之前红色出问题，改成黑白一切正常。
请问：BufferedImageLuminanceSource 类为什么没有在 3.4.1 jar 包里？

**Comment by MrHuang77** [comment]
> > > I optimized zxing, the success rate is very high, you can test it
> > > https://www.sojson.com/qr/deqr.html
> > > https://www.sojson.com/qr/zxing.html
> > 
> > 
> > 能给点建议和方向吗？
> 
> 我就是把图片色差一直调整！直到出结果
像下面的二維碼使用ZXing識別不出來，這個問題困惑了我好久
![test7](https://user-images.githubusercontent.com/34028182/195754555-678775bd-8d4e-440f-8f95-9dd2950e7c0d.jpg)

**Comment by AllenThmos** [comment]
> > > > I optimized zxing, the success rate is very high, you can test it
> > > > https://www.sojson.com/qr/deqr.html
> > > > https://www.sojson.com/qr/zxing.html
> > > 
> > > 
> > > 能给点建议和方向吗？
> > 
> > 
> > 我就是把图片色差一直调整！直到出结果
> > 像下面的二維碼使用ZXing識別不出來，這個問題困惑了我好久
> > ![test7](https://user-images.githubusercontent.com/34028182/195754555-678775bd-8d4e-440f-8f95-9dd2950e7c0d.jpg)

调色差的代码借我抄抄

**Comment by AllenThmos** [comment]
> 
现在解决了吗，调色差的代码借我抄抄
