### ISSUE TITLE
12+5 UPC support in Android

### ISSUE THREAD

**Issue by jharmn** [zxing/zxing#217]
Reasonable background here:
http://stackoverflow.com/questions/8544503/zxing-scanning-barcode-with-upc-5-supplemental

For older/80s books/comics, the 12+5 UPC is needed to convert to ISBN:
http://www.librarything.com/wiki/index.php/ISBN

However, I've yet to find any combination of IntentIntegrator or direct Intent call which will produce the full 17 character value.

**Comment by SimoneMSR** [comment]
Hello @srowen  and @jharmn ,
I have followed your corversation and succesfully obtained the EAN-5 extension of a EAN-13 bar code. But I cannot obtain this extension when I use UPC_A bar codes.
Looking at the `UPCAReader.java` file of the zxing library (ver 3.3.2), I see that the `decodeRow` method is overridden several times, and allways calls the `maybeReturnResult` method which **overwrite** the original result from the `EAN13Reader`, thus cancels the **extras** from the `Results` objects
I wonder why this is happening, and how I can workaround this. Should I change the zxing version?

**Comment by srowen** [comment]
EAN-5 is logically an extension to EAN-13, not UPC-A. Although those two latter formats are related, their readers are not. You should not be using UPCAReader here, IIRC.

**Comment by SimoneMSR** [comment]
I am forcing the scan to have an UPC-A format, as the codes I would like to read look like the following

![barcode](https://user-images.githubusercontent.com/10962296/40180277-b720c920-59e6-11e8-960d-89f7cb3d5ce7.jpg)

Which seems to be UPC-A

Why do not we use the following lines within UPCAReader `maybeReturnResult`?
```
  private static Result maybeReturnResult(Result result) throws FormatException {
    String text = result.getText();
    if (text.charAt(0) == '0') {
      Result retval = new Result(text.substring(1), null, result.getResultPoints(), BarcodeFormat.UPC_A);
      retval.putAllMetadata(result.getResultMetadata());
      return retval;
    } else {
      throw FormatException.getFormatInstance();
    }
  }

```
putAllMetadata seems logical, yet usefull to me!

**Comment by srowen** [comment]
I see, that's a good point. I'll make something similar to that change.
