### ISSUE TITLE
Feature request: GS1-128 parser/decoder

### ISSUE THREAD

**Issue by Praktifix** [zxing/zxing#227]
Hello,
the barcode scanner app is a great tool! Thank you very much. 
One additional feature would make it perfect for me. Namely this is a GS1-128 parser that decodes the content/data of the barcode. GS1-128 was formerly named EAN-128 or CCG-128. 
For instance from the barcode data "3103123456107890" it gives as result 
- Netweight: 123,456 kg
- Lot: 7890

Such a feature would be helpfull for testing/reading transportation labels in a lot of logistics purposes, especially for foods. Some time ago I found a good example implementation here: 
http://stackoverflow.com/questions/5685964/decoding-ean-128
Unfortunately I am not so familiar with programming java. It would be great if one of you guys will find it interessting and usefull, too.

Best regards,
Praktifix

**Comment by metinilhan** [comment]
That future would be awasome.

**Comment by Provoo** [comment]
Could you please let me know how we can implement this. Our company needs to tell the user if is code_128 or gs1-128
