### ISSUE TITLE
MECARD / vCard encoding should delimit fields

### ISSUE THREAD

**Issue by srowen** [zxing/zxing#23]
Address / city / state / postal code and so on are supposed to be separated in MECARD and vCard, by comma and semicolon, respectively. The code right now doesn't break this down beyond an address field though, so isn't able to format accordingly. 

Ideally the online encoder would have separate fields for address components. And, in Android, would retrieve address elements independently. However I am not sure Android breaks this out either, not via Intent.

Ported from https://code.google.com/p/zxing/issues/detail?id=1468

**Comment by rotdrop** [comment]
Hi, this still does not work, i.e. the individual address fields are still merged into the "street address" when importing into the contacts app on Android (SGS3 with Android 4.3). OTOH, when I download a vCard file and import it with the import functionality of the contacts app, "everything" seems to work correctly. Is there a known work-around, like storing the decoded data as a .vcf  _file_ on the sd-card? I know I can somehow export the history as CVS file etc. but there does not seem to be an obvious way to simply store the data in the file-system, for later import by other apps. Thanks,

Claus

**Comment by srowen** [comment]
That's not quite what this issue is about. You're talking about behavior of the Contacts app. This is about delimiting address elements, which may or may not change Contacts behavior. It's open because indeed it is not resolved. You are welcome to work on it.

**Comment by Ayyan551** [comment]
![Uploading IMG20240403001534.jpg…]()
