### ISSUE TITLE
 "Structured Append" in QR

### ISSUE THREAD

**Issue by mofosyne** [zxing/zxing#233]
Just noticed that QR has support for splitting a text (and hopefully binary file as well) into multiple QR codes that can be scanned sequentially to reconstruct the file.

This might be useful. How hard would it be to support this?

---

src: http://stackoverflow.com/questions/12905485/storing-a-bmp-image-in-a-qr-code

> The best source of information you can use is the norm about QR Codes (ISO 18004:2006); it's possible (but not necessarily easy) to find it for free on the web.
> 
> The relevant part (section 9) of this norm says:
> 
> > "Up to 16 QR Code symbols may be appended in a structured format. If a symbol is part of a Structured Append message, it is indicated by a header block in the first three symbol character positions. The Structured Append Mode Indicator 0011 is placed in the four most significant bit positions in the first symbol character. This is immediately followed by two Structured Append codewords, spread over the four least significant bits of the first symbol character, the second symbol character and the four most significant bits of the third symbol character. The first codeword is the symbol sequence indicator. The second codeword is the parity data and is identical in all symbols in the message, enabling it to be verified that all symbols read form part of the same Structured Append message. This header is immediately followed by the data codewords for the symbol commencing with the first Mode Indicator."

---

http://www.onbarcode.com/qr_code/structured_append/

> Structured AppendBasic principles 
> 
> Structured append cannot be used in Micro QR Code. 
> 
> One QR Code 2005 symbol can be divided into up to 16 symbols. On the contrary, it can be appended into a structured format. If a symbol is a part of the structured append message, it can be represented by a header block in the first two and a half character positions The four most significant bit positions of the first symbol character set the Structured Append mode indicator 0011. 
> 
> In Structured Append mode, two Structured Append codewords follows indicators, which are placed in the four least significant bits position of the first symbol character, the eight bit position of the second symbol character and the four most significant bit position of the third symbol character respectively. The first codeword is symbol sequence indicator, the second one is parity data, which is identical in all append message to enable all readable symbols are part of the same Structured Append message. This header is followed by the data symbols commencing with the indicator of the first mode. If adopted other ECI mode rather than ECI default mode, each header block consisting of ECI indicator and ECI designator should follow Structured Append header.

**Comment by mofosyne** [comment]
If anyone is looking for this information:

Metadata for structured append is exposed already in result.java from resultsmetadatatype.java in zxing-core

	  /**
	   * If the code format supports structured append and the current scanned code is part of one then the
	   * sequence number is given with it.
	   */
	  STRUCTURED_APPEND_SEQUENCE,

	  /**
	   * If the code format supports structured append and the current scanned code is part of one then the
	   * parity is given with it.
	   */
	  STRUCTURED_APPEND_PARITY,
	  

It was added by micjahn https://zxingnet.codeplex.com/discussions/364835 

------

Recall that only 16 QR can be chained together. So a value of STRUCTURED_APPEND_SEQUENCE=17 may indicate end of a sequence (still need to understand it a bit more)

**Comment by chrisbainbridge** [comment]
There is code to do this at http://programresource.net/en/2013/05/04/2202.html
