### ISSUE TITLE
Any Datamatrix 144x144 barcoode is not read

### ISSUE THREAD

**Issue by ychtioui** [zxing/zxing#261]
I integrated Zxing to read DataMatrix barcodes. I have a database of over 2000 images. all barcodes are read, but 144x144 barcodes.
I attached an image. The  image encodes a few digits in a 144x144 barcode.
has the datamatrix 144x144 reading fixed? is this a known issue?

this barcode has 10 datablocks. The reader decides that each datablocks has errors, and this is not the case. When I save and review the bitmatrix, it does match 100% the input image.

thanks
![barcode_144_144](https://cloud.githubusercontent.com/assets/9968625/5247116/a9bd99d0-793d-11e4-991d-b8ffeecb6057.jpg)

**Comment by terryburton** [comment]
This is industry knowledge I'm afraid, but Data Matrix 144x144 symbols have an interesting property that ZXing might not account for:

https://groups.google.com/forum/#!topic/postscriptbarcode/ylTP8DCCjZ8

Hope this helps.

**Comment by srowen** [comment]
@terryburton good to know. I had no understanding of the underlying issue.
