### ISSUE TITLE
DEFAULT_INTENT_RESULT_DURATION_MS not taken into account

### ISSUE THREAD

**Issue by Spear51** [zxing/zxing#266]
Hi,

I use zxing with cordoba for ticketing purpose and would like to reduce the delay after scanning to go back to the application. However the DEFAULT_INTENT_RESULT_DURATION_MS seems not taken into account when I set it to 1L. The message stays displayed during 2 seconds.

Could you try on your side ? 
Thanks
Theo

**Comment by binoculars88** [comment]
@srowen any chance you can help me with this one?
http://stackoverflow.com/questions/31996598/modify-class-in-jar-android-build-failed
