### ISSUE TITLE
datamatrix dimensions

### ISSUE THREAD

**Issue by andrejb-dev** [zxing/zxing#271]
When using com.google.zxing.datamatrix.DataMatrixWriter encode(String contents, BarcodeFormat format, int width, int height, Map<EncodeHintType,?> hints) and providing width and height, none of these parameters are pushed to the size of resulting BitMatrix, so it is really small even if dimensions are 400x400 for example.

**Comment by cyrilfr** [comment]
I'm using ZXing Java SE 3.3.1 from the central maven repo and I still have this issue. That's the workaround?
