### ISSUE TITLE
Ability to read QR codes saved in the phone

### ISSUE THREAD

**Issue by jithurjacob** [zxing/zxing#275]
I couldn't find a way to read a QR code saved on my phone.

Scenario : my friend just sent me a QR code to a URL on whatsapp but  Barcode scanner does not provide an option to read thoses saved in File System.

This would be a nice feature addition to this wonderful Android app I think.

**Comment by unhammer** [comment]
QR codes some times appear on web sites, in which case you have to find your laptop, type in the URL from your phone, and try to scan your laptop monitor (while swearing at the site creator), so a feature that let you "open image in barcode scanner" would probably be helpful for this use case as well :-)

**Comment by srowen** [comment]
Sure but in that case I would really hope the QR code is a hyperlink. It would seem silly not too indeed.

**Comment by TameOfGroans** [comment]
Can scanner run in background? This would be a non-pathetic use of camera+mirror.

**Comment by jithurjacob** [comment]
![download](https://cloud.githubusercontent.com/assets/7101452/6456171/23fe67e0-c184-11e4-9522-fdaec36d9c0a.png)

I have got this QR Code on my phone while browsing a site .How would I scan this using your app ? 

Hope it's clear

**Comment by alexanderadam** [comment]
It would be awesome if that would be implemented. Thank you.

**Comment by srowen** [comment]
I'm not going to back-port it at this point, but this was implemented in the + app:
https://play.google.com/store/apps/details?id=com.srowen.bs.android

I'd stil collaborate with someone who took a good stab at a PR on this, and merge the two implementations, but nobody has proposed anything.
