### ISSUE TITLE
Problem with new TLDs

### ISSUE THREAD

**Issue by treaki** [zxing/zxing#281]
Hi,

i have just created some barcode with an http link and now i am deeply sad that your scanner dosnt make this link "clickable" like other links. Please improve your url detection system so that the new tlds are supported as well. In attachment ill send some screenshuts with describe the problem.

thanks and keep up the good work

treaki

![screenshot_2015-01-04-19-35-22](https://cloud.githubusercontent.com/assets/1477872/5607183/ab346a5e-9450-11e4-90b2-ea0c6d785191.png)
![screenshot_2015-01-04-19-35-11](https://cloud.githubusercontent.com/assets/1477872/5607182/ab332090-9450-11e4-82fb-e2bbd239ffb2.png)

**Comment by srowen** [comment]
Android makes links clickable here, not the app. I don't think ovh is a TLD anyway.

**Comment by treaki** [comment]
no, this url is working. its the new tld of my provider ovh (see ovh.com) try it out if you want

how to report than this bug to android?
