### ISSUE TITLE
pdf417 decoding issue. ( big number )

### ISSUE THREAD

**Issue by maxx1958** [zxing/zxing#284]
pdf417 decoding issue. 

I tried decode blows value . but decoded values are incorrect 

-- input --
G13UE0022 123456789012345 123456789012345
-- output --
G13UE0022 123456789012345 ABcjw"eeyz
-------------------------------------------------------------------------------------------

**Comment by maxx1958** [comment]
"123456789012345 123456789012345" returen abnormal value.

I guess big number and big number make a bug.

**Comment by maxx1958** [comment]
![barcode-image](https://cloud.githubusercontent.com/assets/10458106/5686702/be5d6b76-9888-11e4-84f6-c7f8fcb5a878.jpg)

thank you very much~~ :)
I attached file. I made a image from the below site.
http://www.racoindustries.com/barcodegenerator/2d/pdf417.aspx

**Comment by srowen** [comment]
This appears to decode fine:

http://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F10458106%2F5686702%2Fbe5d6b76-9888-11e4-84f6-c7f8fcb5a878.jpg

Are you scanning with a mobile app?

**Comment by maxx1958** [comment]
Sorry. I used different source.

Zxingcpp. I will try to use your original source. Thank you very much.
