### ISSUE TITLE
pdf417 decoding issue.

### ISSUE THREAD

**Issue by maxx1958** [zxing/zxing#285]
pdf417 decoding issue.

I tried decode blows values . but decoded values are incorrect
(i used cpp tree 
https://github.com/zxing/zxing/tree/00f634024ceeee591f54e6984ea7dd666fab22ae/cpp )

if you don`t mind . can you make command tool(.exe) file (windows base) 
I need just decode pdf417 format such as default example prog. 

please help me. 

-- input --
G13UE0022 123456789012345 123456789012345
-- output --
G13UE0022 123456789012345 ABcjw"eeyz

and
"123456789012345 123456789012345" returen abnormal value.

I guess big number and big number make a bug.

below image is 123456789012345 123456789012345 
![barcode](https://cloud.githubusercontent.com/assets/10458106/5691492/94ed88a0-990c-11e4-96e8-ef05e3889d13.jpg)

**Comment by srowen** [comment]
This code is not supported and I have no ability to make windows binaries.
