### ISSUE TITLE
Some Time Fail to scan 1d type Barcode

### ISSUE THREAD

**Issue by maheshshahu** [zxing/zxing#286]
When we scan 1d type bar code it take more time to scan and some time it gives me wrong values.
Frequency of giving wrong values was 4/10.
How to resolve this?
Is this not support for 1d ?
What I do for scan 1 d type barcode?

**Comment by srowen** [comment]
This almost always means a false positive for UPC-E. Disable formats you're not interested in. It also may indicate the device is not focusing and therefore not scanning well. (This is not a place to ask questions -- use the discussion group. This is for proposing pull requests.)
