### ISSUE TITLE
Hide / Prevent settings from being displayed or changed

### ISSUE THREAD

**Issue by harish118** [zxing/zxing#289]
hi,

I am using the barcode plugin and I want to prevent the user from changing any settings on the scanner. Alternatively the settings can be locked / disabled or something?

Thanks,
M&M

**Comment by srowen** [comment]
There's no plugin in this project, so you may be talking about something else. No, it would not be good to lock down settings just because the app was invoked by Intent.

**Comment by harish118** [comment]
ok thanks...didn't want people to meddle with settings and then complain that a certain thing does not work as mentioned.

Thanks anyway
