### ISSUE TITLE
GS1 - code 128 barcodes, FNC1 character is suppressed.

### ISSUE THREAD

**Issue by smilog** [zxing/zxing#295]
We use this in ZXING in with our data collection applications for warehouse logistics.
Often we scan barcodes that conform to the GS1 standard, that contain multiple fields.
For variable length fields, a FNC1 character (ascii 29) is used as a terminator.
For 1D Code128 formated barcodes, the FNC1 character is suppressed.

**Comment by srowen** [comment]
What change are you suggesting? Can you make a pull request?

**Comment by smilog** [comment]
I am suggesting that all the data be passed when a code 128 barcode is scanned, including the non-printable characters such as Ascii 29. The behaviour is more correct when scanning a 2D Data Matrix barcode that is has multiple fields that conform to the GS1 standard.

**Comment by srowen** [comment]
Nonprintable characters are still part of the returned string. They are just not visible. I know that it is unspecified, however, what to do with FNC1 in some formats where the reader is not interpreting them as commands. I think DM suggests mapping to ASCII 29 and I did the same in other formats that do not specify. Is the suggestion to make Code 128 behave this way? There is an `ASSUME_GS1` hint for this that is probably what you need. Reopen if not.

**Comment by wfred101** [comment]
ISO standards demand the following behavior:
FNC1 at the first position - This is tranlated to the symbology identifier according ISO/IEC 15424. A Code 128 for example get ]C0 as identifier if there was no FNC1 at the first position. If there was one then the symbology identifier gets ]C1. There is no other translation of FNC1 if it is at the first position. In case the FNC1 is beeing use at another position (except second) as field separator then the ISO standards demand that the FNC1 character shall be translated to the GS character ASCII 29.

The Code 128 (ISO/IEC 15417) modifiers 
0 a normal Code 128 - no FNC characters at the first or second position
1 is a FNC1 at the first position. GS1 call then this Code 128 "GS1 128"
2 is a FNC1 charater at the secon position
4 is a concantenated symbol according to ISBT demands

**Comment by srowen** [comment]
Eh, yes I think that's what is happening here? what is the difference between what happens and what you expect?

**Comment by wfred101** [comment]
If its working like that then ignore the posting. Typically this
behaviour is working incorrect for most smartphone scanning apps. ;-)
Am 08.03.2015 um 14:43 schrieb Sean Owen:
