### ISSUE TITLE
issues while selecting image from gallery and find its content ? 

### ISSUE THREAD

**Issue by erumhannan** [zxing/zxing#298]
i m following this tutorial and have used this code to select image from gallery and want to find the correct code from barcode image 
https://nizaqatali.wordpress.com/2011/06/15/android-qr-code-reader/

LOGCAT:

01-27 11:41:06.794: I/Image File Path(3411): /storage/emulated/0/DCIM/Camera/0126151235b.jpg
01-27 11:41:06.814: D/AndroidRuntime(3411): Shutting down VM
01-27 11:41:06.814: W/dalvikvm(3411): threadid=1: thread exiting with uncaught exception (group=0x41861e48)
01-27 11:41:06.824: E/AndroidRuntime(3411): FATAL EXCEPTION: main
01-27 11:41:06.824: E/AndroidRuntime(3411): Process: com.example.scannerapplication, PID: 3411
01-27 11:41:06.824: E/AndroidRuntime(3411): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:11264 flg=0x1 }} to activity {com.example.scannerapplication/com.example.scannerapplication.ImageSelectionActivity}: java.lang.UnsupportedOperationException: This luminance source does not support cropping.
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3382)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3425)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at android.app.ActivityThread.access$1300(ActivityThread.java:139)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at android.os.Looper.loop(Looper.java:136)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at android.app.ActivityThread.main(ActivityThread.java:5105)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at dalvik.system.NativeStart.main(Native Method)
01-27 11:41:06.824: E/AndroidRuntime(3411): Caused by: java.lang.UnsupportedOperationException: This luminance source does not support cropping.
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at com.google.zxing.LuminanceSource.crop(LuminanceSource.java:94)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at com.google.zxing.BinaryBitmap.crop(BinaryBitmap.java:106)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at com.google.zxing.multi.GenericMultipleBarcodeReader.doDecodeMultiple(GenericMultipleBarcodeReader.java:127)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at com.google.zxing.multi.GenericMultipleBarcodeReader.decodeMultiple(GenericMultipleBarcodeReader.java:64)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at com.google.zxing.multi.GenericMultipleBarcodeReader.decodeMultiple(GenericMultipleBarcodeReader.java:57)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at com.example.scannerapplication.ImageSelectionActivity.onActivityResult(ImageSelectionActivity.java:106)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at android.app.Activity.dispatchActivityResult(Activity.java:5467)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3378)
01-27 11:41:06.824: E/AndroidRuntime(3411): 	... 11 more
01-27 11:41:13.604: I/Process(3411): Sending signal. PID: 3411 SIG: 9
01-27 11:46:54.254: I/ViewRootImpl(4238): ViewRoot's Touch Event : Touch Down
01-27 11:46:54.314: I/ViewRootImpl(4238): ViewRoot's Touch Event : Touch UP

**Comment by srowen** [comment]
This is not a question about this project
