### ISSUE TITLE
UIButton action event not working when it is placed over cameraview

### ISSUE THREAD

**Issue by CHandooNaani** [zxing/zxing#305]
I have integrated zxing barcode scanning to my application.everything is fine but, i have added a custom cancel button in OverlayView.m file provided by zxing.But, the event action is not performing. I donno what is the reason.It works fine for the IPhone but it is not working for the Ipad. Not only the button click its not recognizing the touch too from entire screen.

here is the code i'm using

- (id) initWithFrame:(CGRect)theFrame cancelEnabled:(BOOL)isCancelEnabled oneDMode:(BOOL)isOneDModeEnabled {
if( self == [super initWithFrame:theFrame] ) {

    self.oneDMode = isOneDModeEnabled;
    //CGFloat rectSize = self.frame.size.width - kPadding * 2;
    //CGFloat rectSize2 = self.frame.size.height - kPadding * 2;
    // it effects cropping
    // 1st param effect the border line of rect and second param effects left vertical of rect 3rd param effects width and 4th param effects the height..

    self.backgroundColor = [UIColor clearColor];
    //self.timer = [NSTimer scheduledTimerWithTimeInterval:1 target:self                                                     selector:@selector(mytimer)                                                    userInfo:Nil repeats:YES];

    // logo ..
    UILabel *logo = [[UILabel alloc] init];

    UIImageView *img = [[UIImageView alloc]
                        initWithImage:[UIImage imageNamed:@"Technolabs.PNG"]];
    [logo addSubview:img];
    [img release];
    logo.backgroundColor = [UIColor clearColor];

    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {
        cropRect = CGRectMake(kPadding * 4, kPadding * 4, self.frame.size.width - (kPadding*20) , self.frame.size.height - (kPadding * 6));

        [logo setFrame:CGRectMake(50, 425, 218, 53)];
    }
    else{
        cropRect = CGRectMake(kPadding * 2, kPadding * 3, self.frame.size.width - (kPadding*4) , self.frame.size.height - (kPadding * 6));
        [self.cancelButton setFrame:CGRectMake(260, 40, 50, 50)];
        [logo setFrame:CGRectMake(10, 225, 80, 203)];
    }

    [self addSubview:logo];

    if (isCancelEnabled) {
        //UIButton *butt = [UIButton buttonWithType:UIButtonTypeRoundedRect];

        cancelButton = [[UIButton alloc] init];
        //[cancelButton setTitle:@"Cancel" forState:UIControlStateNormal];
        if (oneDMode) {
            UIImage *img = [UIImage imageNamed:@"closebutton.png"];
            [cancelButton setImage:img forState:UIControlStateNormal];
            //[img release];
            //[cancelButton setTransform:CGAffineTransformMakeRotation(M_PI/2)];

        }
        [cancelButton setFrame:CGRectMake(660, 40, 50, 50)];
        cancelButton.backgroundColor = [UIColor clearColor];
        [cancelButton addTarget:self action:@selector(cancel:) forControlEvents:UIControlEventTouchUpInside];

        //[self addSubview:imageView];
    }

    cancelButton.userInteractionEnabled = YES;
    cancelButton.enabled = YES;

    [self addSubview:cancelButton];

    UIButton *cancel_Button = [[UIButton alloc] init];
    UIImage *img1 = [UIImage imageNamed:@"closes.png"];
    [cancel_Button setImage:img1 forState:UIControlStateNormal];
    cancel_Button.frame = CGRectMake(600.0, 40, 50, 50);
    cancel_Button.hidden = NO;
    cancel_Button.backgroundColor = [UIColor clearColor];
    [cancel_Button addTarget:self action:@selector(cancel:) forControlEvents:UIControlEventTouchUpOutside];
    //[self addSubview:cancel_Button];
}

return self;
}

Please can anyone help me to solve this issue.Thanks in advance i have tried all the possible i can to make it happen but the action is not happening and the method is not calling at all. I'm more happy if it recognizes just a touch.

**Comment by srowen** [comment]
This is asking about code not in the project now.

**Comment by CHandooNaani** [comment]
Hello srowen,

thanx for the reply.this code belongs zxing 2.2.and i have modified the overlay view to add my own custom button to cancel the barcode scanning but its not hapenning
