### ISSUE TITLE
com.google.zxing.NotFoundException

### ISSUE THREAD

**Issue by baruchhiz** [zxing/zxing#306]
Hello all,
I generate a barcode, but i didn't try to read it.
I used all the hints, barcode formats but still noffound is thrown.
![barcode5](https://cloud.githubusercontent.com/assets/10864292/6058916/b24f500e-ad34-11e4-8192-9a4a57706cea.jpg)

Thanks,
Baruch

**Comment by srowen** [comment]
It looks malformed. Look at the size of the narrowest bars which seems to vary by a factor of three. Maybe you scaled this image.

**Comment by baruchhiz** [comment]
Hi Sean,
Here's  barcode6 without any scaling (was cut from pdf), but still not working
![barcode6](https://cloud.githubusercontent.com/assets/10864292/6059145/f8376f5a-ad36-11e4-8ea8-8c74ebfd84ce.JPG)

Thanks,
Baruch

**Comment by srowen** [comment]
It still looks wrong, compared to other 1D encodings. At best, I can say maybe it's an unsupported format.

**Comment by marmar44** [comment]
On 5 Feb 2015 19:15, "Sean Owen" <notifications@github.com> wrote:
>
> It still looks wrong, compared to other 1D encodings. At best, I can say
maybe it's an unsupported format.
