### ISSUE TITLE
Some of barcodes cannot be identified

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [zxing/zxing#310]
I have downloaded the latest stable version of your Android app, but I found some barcodes cannot be identified by your app. they are:
https://en.wikipedia.org/wiki/File:MicroQR_Example.png
https://en.wikipedia.org/wiki/File:Qr-code-ver-40.png

From: https://en.wikipedia.org/wiki/QR_code

**Comment by srowen** [comment]
The first one is a Micro QR code, which is actually not a part of the main QR code standard. It is not supported and won't be. The second is a maximally dense QR code and will never be read at that size; past about version 20 it gets hard to read on a camera, although version 40 is actually read just fine by the library. This is a test case even.

**Comment by KrasnayaPloshchad** [comment]
Oh~

**Comment by KrasnayaPloshchad** [comment]
I found a photo including QR code taken from billboard, I can scanned the code directly with [QuickMark](http://quickmark.com.tw/En/basic/downloadMain.asp), but cannot scanned with your scanner.

https://en.m.wikipedia.org/wiki/File:Japan-qr-code-billboard.jpg

**Comment by srowen** [comment]
Scans fine for me. Please don't post on old issues. This isn't an issue even; at best, write to the mailing list. @KrasnayaPloshchad
