### ISSUE TITLE
Make IntentIntegrator REQUEST_CODE parametrizable

### ISSUE THREAD

**Issue by eMaringolo** [zxing/zxing#314]
The current implementation of ```initiateScan()``` uses a fixed request code when calling ```startActivityForResult(...)```, which could be bypassed by calling ```createIntent()``` and starting the intent activity externally. 

But ```parseActivityResult()``` cannot be bypassed, because REQUEST_CODE is hardwired in the code.

It would be desirable to have a version of ```initiateScan()``` and ```parseActivityResult()``` that receives the request code as argument.

**Comment by srowen** [comment]
I think that's fine, do you want to make a PR that adds a getter/setter for a request code, which defaults to the current value?

**Comment by renatosc** [comment]
I am in need of this. Already added a getter/setter. Can I make the PR?
