### ISSUE TITLE
After some time playing with zxing dalvik VM is aborted!

### ISSUE THREAD

**Issue by TMSantos** [zxing/zxing#318]
Hey I am facing this problem:

E/dalvikvm﹕ Unexpected opcode(281) with kInstrCanBranch set
E/dalvikvm﹕ VM aborting
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 20681 (Compiler)

This happens after playing with Zxing lib after some time.

Happens with different devices, any ideia what is this and how I can fix it?

Thank you

**Comment by srowen** [comment]
Sorry to say that is a bug in dalvik, as you see. It should never crash.

**Comment by TMSantos** [comment]
Hello srowen,

Thank you for your fast reply. 

Do you know if there is any possible way to catch it/avoid?

Hard to manage since is not a regular crash :/

**Comment by srowen** [comment]
No, it's a much lower level error. The app running in Dalvik can't trap this; the VM itself dies.

Now, one possibility is that the proguard optimization step is producing bytecode that is exotic but valid (or possibly even invalid) and dalvik is unhappy. Even though it should never crash, maybe building without proguard works around it.

**Comment by TMSantos** [comment]
Unfortunately happens in my debug build also and is not using ProGuard. :/

Thank you for your help! If I find anything I will communicate.

**Comment by TMSantos** [comment]
Just to add:

I am using Zxing in a fragment , which is inside an ViewPagerAdapter. Not sure if this can provide unexpected behaviours.
