### ISSUE TITLE
Preview brightness issue on Google Nexus 5 (maybe other devices)

### ISSUE THREAD

**Issue by mvpotter** [zxing/zxing#320]
I did not find the source of the issue, however due to changes in "setBestPreviewFPS" method (here https://github.com/zxing/zxing/commit/461d15a8908900772440ee2415f0afb5a17f08fc) camera preview is dark on Google Nexus 5 (5.0.1) device.

Example screenshots (same room and light conditions):

BS-4.6.4
![BS-4.6.4](https://dl.dropboxusercontent.com/u/1940399/BS-4.6.4.png)

BS-4.7.0
![BS-4.7.0](https://dl.dropboxusercontent.com/u/1940399/BS-4.7.0.png)

When I rollback the changes - issue dissapears

**Comment by srowen** [comment]
What that tends to mean is that the driver has a bug. The basic form is:

1. driver says it supports X, like some preview size
1. app sets X
1. driver fails, and all configuration is ignored

As you can see the change has nothing to do with brightness. 

However I am also not able to reproduce this on a Nexus 4, 5 or 6 on Android 4.x / 5.x. Try the various device bug workaround settings, and try different brightness settings, in the app's Settings.
