### ISSUE TITLE
QR code reading problem (Java SE) 

### ISSUE THREAD

**Issue by dimonrv** [zxing/zxing#321]
I am trying to read this QR code with the Zxing 2.0 and latest, without any success.
![43-b35c593a-5d00-4aeb-b976-dfefa909c7ec](https://cloud.githubusercontent.com/assets/11295572/6464442/4868480c-c1cb-11e4-8eb8-fadc21f19242.png)
com.google.zxing.FormatException

If I fill the square.

![43-b35c593a-5d00-4aeb-b976-dfefa909c7ec](https://cloud.githubusercontent.com/assets/11295572/6464606/7513b1f6-c1cc-11e4-827c-4226752ff4e5.png)

Decode succeeded.

What is the problem?

Thanks!

**Comment by srowen** [comment]
Yeah, it's a funny problem. That little region passes the heuristics for a finder pattern quite easily, so it keeps misreading. A little change can change it. Also try rotating the image a bit. It's a weakness of the heuristic that shows up in rare cases like this. I don't know of a good way to fix it without hurting performance for most codes though.

**Comment by dimonrv** [comment]
Thanks for your fast reply.
