### ISSUE TITLE
How do I set narrow/wide bar width

### ISSUE THREAD

**Issue by dittodhole** [zxing/zxing#322]
I have created a label via EPL/ZPL/Fingerprint, which give me an option for narrow/wide bar width (for eg CODE_128). I am porting this to a WPF application, to use a normal windows printer.

Is there any option for this width?

**Comment by dittodhole** [comment]
I did some investigations - this could be done, like:

- Create your own `IBarcodeRenderer`, where you can inject those widths
- Implement your own `Render` methods, where you do some stretching on the narrow(1) or wide(3) bars.

But is there any solution implemented in the framework itself?

**Comment by srowen** [comment]
I think you are talking about another project? These interfaces aren't in this one.

**Comment by dittodhole** [comment]
Thanks, my fault! (I intended to go for zxing.net)...
