### ISSUE TITLE
Data Matrix Rectangular Extension

### ISSUE THREAD

**Issue by dehnhard** [zxing/zxing#324]
I added the pull request https://github.com/zxing/zxing/pull/323 with my work on support for DMRE as described in http://www.aim-d.de/images/stories/pdfs/Arbeitskreise/Barcode/aim_spec_dmre_2014-09-22.pdf

It is functional enough for my needs, but I think it needs at least a good look from a maintainer before proper inclusion into zxing.

**Comment by srowen** [comment]
(Only closing this since it's pretty well encapsulated in the pull request itself)
