### ISSUE TITLE
Cannot scan barcode on tablet Ellipsis 7 using apk which is built from source code of Git

### ISSUE THREAD

**Issue by TuanTruong99** [zxing/zxing#325]
I downloaded the latest source code on Feb 27, 2015.  I built an apk and run it on the tablet Ellipsis 7 (http://www.verizonwireless.com/tablets/ellipsis-7/) .  It doesn't work.  But If I install the app Barcode Scanner on PlayStore, it work fine.  Are they built on different source code ?

**Comment by srowen** [comment]
"Doesn't work" doesn't help. No they are built from the same source. It is probably an issue with your env or device.

**Comment by TuanTruong99** [comment]
I can open the app to scan the barcode but it cannot scan successfully.  Please check the project that I build on :http://www.freeuploadsite.com/do.php?id=67450, tell me if something's wrong.
