### ISSUE TITLE
integrator immersive mode - is it possible?

### ISSUE THREAD

**Issue by Venzon** [zxing/zxing#327]
Hi

I am using custom capture layout with zxing integrator
Is there any way to set immersive view for such implementation? I would like to use same flags as I use for all activities:
```
View.SYSTEM_UI_FLAG_LAYOUT_STABLE
            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION // hide nav bar
            | View.SYSTEM_UI_FLAG_FULLSCREEN // hide status bar
            | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
```

```
public void scanBarcodeCustomLayout(View view) {
        IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setCaptureLayout(R.layout.custom_capture_layout);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE_TYPES);
        integrator.autoWide();
        integrator.setCameraId(1);
        integrator.setScanningRectangle(1600, 800);
        integrator.setResultDisplayDuration(0);
        integrator.initiateScan();
    }
```

regards

**Comment by srowen** [comment]
No, it needs the action bar if that's what you mean. But it's already full screen.

**Comment by Venzon** [comment]
@srowen thx for reply
So there is no way to use zxing barcode scanner without top and bottom menu?
Maybe with some other view implementation?

**Comment by srowen** [comment]
No, you would need to make your own app.

**Comment by Venzon** [comment]
@srowen last question
Do  you think that I can use some external app to force immersive mode for entire app?
For example https://play.google.com/store/apps/details?id=com.hamzahrmalik.immersiveforcer
Will it work with zxing? I would like to stay with this awesome lib
Thanks for your help

**Comment by Venzon** [comment]
full screen problem solved with https://github.com/dm77/barcodescanner
