### ISSUE TITLE
Error when trying to call for the BarcodeScanner.Scan()

### ISSUE THREAD

**Issue by empsortberg** [zxing/zxing#328]
I get the following error when I'm trying to call the .Scan():
Warning: Attempt to present <ZXing_Mobile_ZXingScannerViewController: 0x160d87d0> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x14f6a2f0> whose view is not in the window hierarchy!

Anyone got an idea whats wrong?
Cheers!

**Comment by srowen** [comment]
I think you're asking about another project; there's no such method here.

**Comment by empsortberg** [comment]
ZXing.Mobile.MobileBarcodeScanner().Scan()?

**Comment by srowen** [comment]
That is not part of this project. Maybe you are looking for https://github.com/Redth/ZXing.Net.Mobile ?
