### ISSUE TITLE
The camera is opened slowly on the android phone with authority management.(Android)

### ISSUE THREAD

**Issue by lien1992** [zxing/zxing#330]
When I start zxing android application on the phone with authority management, the authority tip pops up after nearly six seconds while other applications that use camera will pop up the authority tip immediately. By the way, as for the  phone with authority management,  the authority tip will pop up when the third-party application call the camera, the application can open camera only if the application is permitted. 
![authority_tip](https://cloud.githubusercontent.com/assets/2783554/6614808/cf182138-c8d8-11e4-853c-031f6ccbe4db.jpeg)

**Comment by srowen** [comment]
The app opens the camera immediately when it starts. I don't know how this system works, but it is up to this other third-party software when and how it shows this dialog.

**Comment by lien1992** [comment]
I have just tried other phones that installed with authority management application, the zxing android application also encounters the problem when I set the camera authority to asking me(three options: always allow, ask me, always disallow). Maybe you can have a try.

**Comment by srowen** [comment]
This is certainly a question about this third party tool you have installed, right? I have no idea what it is or does.

**Comment by lien1992** [comment]
I mean that it's not a question about the third-party tool, but the zxing android application, because it pops up authority tip quickly for other applications that use camera. I have tried to find out what causes that all the day, but no any progress. Thank you for your reply.

**Comment by srowen** [comment]
As I say, the camera is opened immediately on startup, of course. Look at the source
