### ISSUE TITLE
Not able to install ZXing.Net to my apache cordova app

### ISSUE THREAD

**Issue by pr4v33nv3rm4** [zxing/zxing#333]
Hi

I am new to apache cordova or WP app development for that mater. I am having a empty apache cordova app and trying to install XZing.net for barcode scanning functionality.

When i am using  PM> Install-Package ZXing.Net in package manager console , i am getting following exception.

PM> Install-Package ZXing.
NetInstalling 'ZXing.Net 0.14.0.1'.
Successfully installed 'ZXing.Net 0.14.0.1'.
Adding 'ZXing.Net 0.14.0.1' to BarcodePOC.Uninstalling 
'ZXing.Net 0.14.0.1'.Successfully 
uninstalled 'ZXing.Net 0.14.0.1'.
Install failed. Rolling back...Install-Package : Could not install package 'ZXing.Net 0.14.0.1'. You are trying to install this package into a project that targets 'MDD,Version=v8.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.At line:1 char:1+ Install-Package ZXing.Net+ ~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand PM> 

Can somebody please help to understand what i am missing here? thanks.

**Comment by srowen** [comment]
This is not the zxing.net project
