### ISSUE TITLE
displayFrameworkBugMessageAndExit

### ISSUE THREAD

**Issue by bestfriend21** [zxing/zxing#335]
Hello,
I am working on the app using Zxing framework.
When i use some devices, i got the following exception.

0java.lang.RuntimeException: Adding window failed
1	at android.view.ViewRootImpl.setView(ViewRootImpl.java:648)
2	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:261)
3	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:71)
4	at android.app.Dialog.show(Dialog.java:302)
5	at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
6	at com.google.zxing.client.android.CaptureActivity.displayFrameworkBugMessageAndExit(CaptureActivity.java:442)
7	at com.google.zxing.client.android.CaptureActivity.initCamera(CaptureActivity.java:432)
8	at com.google.zxing.client.android.CaptureActivity.surfaceCreated(CaptureActivity.java:370)
9	at android.view.SurfaceView.updateWindow(SurfaceView.java:662)
10	at android.view.SurfaceView.access$000(SurfaceView.java:90)
11	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:195)
12	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
13	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2231)
14	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1231)
15	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6272)
16	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
17	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
18	at android.view.Choreographer.doFrame(Choreographer.java:560)
19	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
20	at android.os.Handler.handleCallback(Handler.java:808)
21	at android.os.Handler.dispatchMessage(Handler.java:103)
22	at android.os.Looper.loop(Looper.java:193)
23	at android.app.ActivityThread.main(ActivityThread.java:5315)
24	at java.lang.reflect.Method.invokeNative(Native Method)
25	at java.lang.reflect.Method.invoke(Method.java:515)
26	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
27	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
28	at dalvik.system.NativeStart.main(Native Method)
29Caused by: android.os.TransactionTooLargeException
30	at android.os.BinderProxy.transact(Native Method)
31	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:683)
32	at android.view.ViewRootImpl.setView(ViewRootImpl.java:637)

Device name is "Xiaomi 2014501"
Can you please clarify what the problem is?
Thanks,

**Comment by srowen** [comment]
It's failing while trying to report a failure in the camera. Check the device logs. Ultimately it's a problem with the device.
