### ISSUE TITLE
support request: codabar for public libraries

### ISSUE THREAD

**Issue by stamas1111** [zxing/zxing#336]
Public libraries in the USA use a 14 digit codabar bar code for membership cards and for books.  Please add support for this to the library.  Thanks!   Reference info for this standard is readily available and easy to find.

**Comment by srowen** [comment]
Codabar is already supported, so please test it first.
Feature requests are not accepted, but you can propose a patch for things you want done.

**Comment by stamas1111** [comment]
Android app: Watch Membership uses this library but flags the following codabar enter as invalid: 23006003382595.  I have independently confirmed this membership code with built in check digit conforms to the published 14 digit codabar standard (used by USA public libraries).  Is this a zxing problem or a Watch Membership app problem?

**Comment by srowen** [comment]
I don't think Codabar has a check digit? http://en.wikipedia.org/wiki/Codabar#Check_digit Or at least standard Codabar doesn't. I remember this makes it a bit problematic.

**Comment by stamas1111** [comment]
The check digit is a numeric code implementation standard used by public libraries.  The barcode should only be a graphic translation of the 14 digits. If you can verify the digits -> codabar zxing code works with this 14 digit example, then I can notify the "Watch Membership" android app authors that the problem lies with their use of the zxing library.
