### ISSUE TITLE
Front camera focus

### ISSUE THREAD

**Issue by manuelmh** [zxing/zxing#337]
Hi everyone,

Changing and adding some code I managed to use both back and front camera in both portrait and landscape mode (I think I am not using the latest Zxing release). However, since the front camera does not have autofocus, it is very difficult to scan QRs with it. It scans some of them, depending on the QR, device, light, how close it is to the screen... I wonder if there is anything I can change in order to improve its performance: camera settings, pre-processing the QR data...

Thanks in advance

**Comment by srowen** [comment]
The lack of focus is a big obstacle, but yeah, the app can't do much about that I'm afraid.

**Comment by manuelmh** [comment]
Hi again,

We just started testing with 33x33 points QR, I think that gives space for 77 characters. Without any encoding or encryption, and both cameras can scan them with no problems and very fast.
