### ISSUE TITLE
(wish) save a series of scan to csv

### ISSUE THREAD

**Issue by andrearicci** [zxing/zxing#338]
As a cad user I'm evaluating the possibiliti to use qrcode to tag printed sheeets. I would like to be able to scan a series of qrcodes (the drawings) then download and check the results.
You have a "history" function. Can that be evolved to my needs?
That would be helpfull also to check and scan in/out goods from a warehouse.
Thank you

**Comment by srowen** [comment]
Good news, it's done this for a long time. Just choose to 'save' the history and it will export as CSV however you like.

**Comment by andrearicci** [comment]
using android barcode scanner <https://play.google.com/store/apps/details?id=com.google.zxing.client.android> I can't find the function (or the log)

**Comment by srowen** [comment]
History -> Share icon

**Comment by andrearicci** [comment]
great, thanks a lot
