### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by lawloretienne** [zxing/zxing#345]
What is the suggested way to set up Proguard rules for ZXing (the zxing core [http://mvnrepository.com/artifact/com.google.zxing/core/3.2.0]) ?

**Comment by srowen** [comment]
Have a look at how proguard is set up for the Maven plugin in https://github.com/zxing/zxing/blob/master/pom.xml

**Comment by lawloretienne** [comment]
Proguard rules are typically found in a proguard-rules.pro configuration file, but you have directed me to a pom.xml file.  Where exactly are the proguard rules there?

**Comment by srowen** [comment]
Yes, did you look at the Android app? https://github.com/zxing/zxing/tree/master/android
The core library itself is not optimized, but the whole thing is optimized together when it is built into an Android app.

**Comment by lawloretienne** [comment]
So ever since I enabled Proguard in my app, users have been complaining
about auto-focusing issues (they start trying to scan but it never focuses
enough to get a result)

Are these Proguard rules supposed to address the issues with auto-focusing?

Before I had Proguard enabled I didn't have users complaining about
auto-focusing.

On Mon, Mar 23, 2015 at 5:38 PM, Sean Owen <notifications@github.com> wrote:

> Yes, did you look at the Android app?
> https://github.com/zxing/zxing/tree/master/android
> The core library itself is not optimized, but the whole thing is optimized
> together when it is built into an Android app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zxing/zxing/issues/345#issuecomment-85261510>.
>



-- 
-Etienne Lawlor (Software Developer)

**Comment by srowen** [comment]
No Proguard would have nothing to do with autofocus; it's a byte-code optimizer. The file is the Android default with a small change to what optimization is allowed, etc. I can't speak to what your app does but make sure you aren't removing code you use by reflection or something.

**Comment by lawloretienne** [comment]
Line 27 of the proguard.cfg file
https://github.com/zxing/zxing/blob/master/android/proguard.cfg#L27

is causing this error to get thrown

java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder
       at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:620)
       at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:825)
       at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:817)
       at android.support.v7.internal.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:554)
       at android.support.v7.internal.app.ToolbarActionBar.setListMenuPresenter(ToolbarActionBar.java:558)
       at android.support.v7.app.ActionBarActivityDelegateBase.setSupportActionBar(ActionBarActivityDelegateBase.java:178)
       at android.support.v7.app.ActionBarActivity.setSupportActionBar(ActionBarActivity.java:92)

But if I comment it out then people are complaining about auto-focusing issues.

**Comment by srowen** [comment]
I can't help with your app but I doubt that is the problem. The line causes it to not remove classes at all.

**Comment by lawloretienne** [comment]
Does ZXing support a tap to focus feature?

**Comment by tvvbbb** [comment]
I also meet you issue,when I use zxing in 2015.You can slove it after scaned every time manually.
