### ISSUE TITLE
Wrong EAN code scanned on Android

### ISSUE THREAD

**Issue by slaha** [zxing/zxing#346]
Hi,

I try to implement scanning of barcodes of goods (EAN-13). But unfortunately there is a lot of wrongly read codes (at least on my Nexus 7 II tablet).
See screenshots there: http://jdem.cz/brxkr5 On the page there I also uploaded a PDF with some codes I use for testing.

Don't you know what can cause these misreads?

Thank you

**Comment by srowen** [comment]
Usually it is camera problems that mean you can't scan and eventually will see a phantom EAN8 code. Restrict to the format you want and check your auto focus
