### ISSUE TITLE
How to read the scanned history data?

### ISSUE THREAD

**Issue by Techno-Group** [zxing/zxing#350]
Dear Mr.&Mrs.,

We urgently need to read the scanned history data but can't read them successfully. For example, one history scanned data was saved as an URL https://l4e.us/62O/183610/CORTES-DIAZ/JAVIER/KING-SERVICE that is our customer's contact information but we can't read it now. Could you please help us out? 

Thank you very much!

Jason

**Comment by srowen** [comment]
Not clear what you mean. That is a valid URL as you can see. What's on the other end has nothing to do with barcodes.

**Comment by Techno-Group** [comment]
Hi,

The URL is not correct information because we scanned the badges of visitors to our booth. The infirmation of the URL is supposed to be the contact information of visitors but the saved history URL does not show them but linked us to another website. Would u please help to figure out what is going on?

Thanks/Jason


Sent from Jason Chiu's Galaxy SIII 

-------- 原始郵件 --------
自： Sean Owen <notifications@github.com> 
日期：  
至： zxing/zxing <zxing@noreply.github.com> 
副本： Techno-Group <jason@technoplas.com> 
主旨： Re: [zxing] How to read the scanned history data? (#350) 
 
Closed #350.

**Comment by srowen** [comment]
OK, but this has nothing to do with the barcode or this app. The barcode contained the exact URL above. The exact URL was saved in history, and exported correctly. In no sense does the app read or parse a random URL.
