### ISSUE TITLE
Android App: Automatic flashlight

### ISSUE THREAD

**Issue by abmmhasan** [zxing/zxing#354]
Problem appears when I try to scan some bar-code but there is no light or light is dim. You should add auto-flash if it is not enough light to scan bar-code.

**Comment by srowen** [comment]
Already implemented. Did you look in settings?

**Comment by abmmhasan** [comment]
well, I've set it to auto, but it not working when I was in dark! Which means it does not detecting auto flash. This thing needs improvement!

**Comment by srowen** [comment]
Works OK for me. It has to be pretty dark to trigger as otherwise the flash is not helpful and just generates glare.

**Comment by abmmhasan** [comment]
I've tried by placing finger on sensor of my phone! No result!

**Comment by srowen** [comment]
Works fine for me; walk into a dark bathroom and it comes on. EIther you didn't set to auto, or your device doesn't support an ambient light sensor.

**Comment by abmmhasan** [comment]
I have light sensor! Anyway may be some other bug then!
