### ISSUE TITLE
Add floating element feature for Android device

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [zxing/zxing#356]
Hi, 

Do you think of adding screen decoding feature for Android device? I found Android app [Calculator++](https://play.google.com/store/apps/details?id=org.solovyev.android.calculator) have a floating element which can make calculating on the screen, so I think you can add some floating elements to make a selection, decode and showing the result on the screen.

**Comment by srowen** [comment]
This is hard mostly because the app has to have the camera open. There isn't any further development work on this app, so no this would not happen.
