### ISSUE TITLE
Failing to receive Intent

### ISSUE THREAD

**Issue by ProdigiumKami** [zxing/zxing#358]
I am having trouble getting zxing to respond to my intent to scan a barcode, I am using your app to scan a barcode as described in you API but the app doesnt open :/ it insted crashes my app. After multiple tries, i decided to proceed with my development efforts by adding a catch block which sends an Intent to the store to download the app. The play store responds to the Intent, so I'm wondering what's wrong here. ive tried a bunch of stuff for months. I've screenhoted the code as posted on code project (who couldnt assist me)

![image](https://cloud.githubusercontent.com/assets/7430528/7202445/a897b428-e512-11e4-950c-7612d92e3ce9.png)

**Comment by srowen** [comment]
Not sure, but it's a function of your app's integration code and your local env. Have a look at the Intent wiki. This is a place for submitting pull requests.
