### ISSUE TITLE
Kindle Fire HDX camera orientation inverted

### ISSUE THREAD

**Issue by srowen** [zxing/zxing#36]
Install BarcodeScanner-4.5.1.apk from the downloads section on a Kindle Fire HDX
Notice that the UI is properly oriented in landscape mode but the camera preview is inverted (up-side-down)

The UI should be properly oriented in landscape mode (as it is) but the camera preview should also be right-side-up.

This issue occurs whether the Kindle's "Auto-Rotate" feature is enabled or disabled.

![device-2014-01-15-101638](https://f.cloud.github.com/assets/822522/1947259/d3ccbee4-8047-11e3-817a-8e33b5b6146b.png)

Ported from https://code.google.com/p/zxing/issues/detail?id=1833

**Comment by SyedWasiHaider** [comment]
This is still an issue.

**Comment by judax** [comment]
I am developing a camera handling library myself and I can confirm this is an issue on the Kindle Fire HDX 10. I also have the BarCodeScanner installed and the image is upside down. My library also has this problem. Not sure how can be resolved though. Very much appreciated if someone could provide some feedback on the issue. Tested on many other devices: Kindle Fire HD, Samsung Galaxy S3, Nexus 7, ... and none of these devices show this behaviour.

**Comment by arnauorriols** [comment]
This is indeed still happening, on every device I can try.
