### ISSUE TITLE
setTitle() for IntentIntegrator.shareText()

### ISSUE THREAD

**Issue by agrajaghh** [zxing/zxing#362]
Unfortunately it's not possible to set the title of the activity which shows the QR Code with `IntentIntegrator.shareText()`

So just the type will be displayed, e.g. "Text":

![screenshot_2015-04-24-00-18-54](https://cloud.githubusercontent.com/assets/5296073/7308769/87ba55ee-ea17-11e4-877b-2cde9d12fe52.png)

**Comment by srowen** [comment]
Sure, how about a pull request to add this option? as long as it doesn't remove existing methods, that's fine.
