### ISSUE TITLE
Online decoder displays wrong raw bytes for data for DATA_MATRIX

### ISSUE THREAD

**Issue by TorstenScheck** [zxing/zxing#365]
When using <http://zxing.org/w/decode.jspx> with the following image, I noticed that the raw bytes are are wrong, even though the raw text is correct.

![datamatrix](https://cloud.githubusercontent.com/assets/10532201/7406749/862abff2-ef08-11e4-9982-a80ef352abdb.jpg)

~~~
Raw bytes expected:
44 45 41 12 20 01 2d 82  1b a1 00 3e 25 f3 25 1d 
00 04 97 02 1e 47 11 00  00 06 ea 30 46 42 30 31 
39 32 38 34 35 32 33 54  49 34 

Raw bytes displayed:
45 46 42 13 21 e7 18 ae  70 5a 89 a5 99 6d e9 4d
14 a2 1b b4 dd dd 8f 4e  ad 32 c7 63 dc b8 64 f5
79 0f ad 3c d7 69 ff 92  28 df 6a ea 
~~~

**Comment by srowen** [comment]
I suspect the raw bytes are in fact correct if the text is, right? These are the encoded codewords themselves. Maybe you are expecting a different codeword encoding than what the encoder chose?

**Comment by TorstenScheck** [comment]
II expect an ASCII character set where e.g. a capital 'D' is 0x44, not 0x45.

Strangely, the text is correct, but the bytes are not.

This makes the online service unusable for anyone interested in the binary data.

~~~
Raw text

DEA� �-<82>�¡�>%ó%���<97>��G����ê0FB019284523TI4

Raw bytes

 45 46 42 13 21 e7 18 ae   70 5a 89 a5 99 6d e9 4d
 14 a2 1b b4 dd dd 8f 4e   ad 32 c7 63 dc b8 64 f5
 79 0f ad 3c d7 69 ff 92   28 df 6a ea

Barcode format  DATA_MATRIX
Parsed Result Type      TEXT
Parsed Result

DEA� �-<82>�¡�>%ó%���<97>��G����ê0FB019284523TI4
~~~

**Comment by srowen** [comment]
Why do you expect these codewords? There are many valid encodings for a string. That is, this barcode has the bytes it reports. This sounds like a question about controlling your encoder.

**Comment by TorstenScheck** [comment]
The image I gave as an example is a franking mark of the Deutsche Post. It uses a very simple ASCII encoding e.g. for the first three bytes: it's always Hex:444541 => ASCII: DEA.

See: <http://www.deutschepost.de/content/dam/mlm.nf/dpag/images/p/premiumadress/premiumadress_neu/mlfvm_8_premiumadress_1_0_18_en.pdf>

Maybe I've totally misunderstood the whole concept and you are right about those strange "encodings" for a "string" or "controlling your encoder". But then your concept is not usable, because people simply expect to see the byte values which match the encoded binary data.

But I still believe that there is just a nasty bug in the bytes printing loop.

**Comment by srowen** [comment]
Yeah what you see is the Data Matrix "encodation" of the string, which is not a simple ASCII or ISO-8859-1 representation. It has various modes to encode / compress strings. This starts in "ASCII encodation", which actually encodes most characters as ASCII + 1 values.

**Comment by TorstenScheck** [comment]
I see. Then my incident is no bug, but an improvement.

This service, for instance, prints the original binary data, as defined in the Deutsche Post specification: <http://online-barcode-reader.inliteresearch.com/default.aspx>

~~~
Barcode:        1 of 1  Type:   DataMatrix              Page 1 of 1
Length:         42      Rotation:       none
Module:         6.7pix  Rectangle:      {X=36,Y=43,Width=175,Height=174}
Barcode Text processing:
    Converted Character Set: ISO-8859-1
    Formatted: specialChar

Binary Data in barcode (Hex-ASCII display)

0000  44 45 41 12 20 01 2d 82  1b a1 00 3e 25 f3 25 1d  | DEA~ ~-~~~~>%~%~ |
0010  00 04 97 02 1e 47 11 00  00 06 ea 30 46 42 30 31  | ~~~~~G~~~~~0FB01 |
0020  39 32 38 34 35 32 33 54  49 34                    | 9284523TI4       |
~~~

**Comment by srowen** [comment]
To simplify, there are three representations of the same data:

1. The Data Matrix encodation, using things like C40 and byte mode, as an array of bytes
1. The string, as an array of characters
1. That same string, encoded according to something like ISO-8859-1

It's not valid to put 3 into the barcode itself; that is not how strings are encoded in a Data Matrix barcode. 1 is how they are encoded. 1 is what the tool shows you. However it still represents the same string in 2. You can encode the string according to 3, yourself, but that is not the purpose of the tool. It's showing you the actual content of the barcode, which is not the bytes in 3, but bytes in 1.

**Comment by vidyajejurkar** [comment]
@TorstenScheck : How did u decode this rawbytes into Hex-ASCIII ? I  also want to decode and get this Hex-ASCII.Can u please provide code?

**Comment by TorstenScheck** [comment]
@vidyajejurkar As mentioned above I used this online service:
http://online-barcode-reader.inliteresearch.com/default.aspx

**Comment by NikKpkt** [comment]
To follow up in case someone has the same question in the future. The decoded bytes can be accessed as follows:

    Result result = reader.Decode(dmc);
    if (result.ResultMetadata.ContainsKey(ResultMetadataType.BYTE_SEGMENTS))
    {
        var byteSegments = (List<byte[]>) result.ResultMetadata[ResultMetadataType.BYTE_SEGMENTS];

        if (byteSegments != null && byteSegments.Count > 0)
        {
            resultBytes = byteSegments[0];
        }
    }
