### ISSUE TITLE
activity.getPackageManager() null sometimes in findTargetAppPackage

### ISSUE THREAD

**Issue by xmarston** [zxing/zxing#366]
The issue I'm facing is that sometimes when I launch the IntentIntegrator the app crashes because a NullPointerException.

I find that the problem is because the activity sometimes is null. I'm launching this Intent from a Fragment, how can I avoid that the app crashes?

**Comment by srowen** [comment]
Yeah, you can't pass a `null` for the `Activity`. There are separate methods for using `Fragment`s in the same class.

**Comment by xmarston** [comment]
I think you don't understand me, probably because I didn't make my explanation very clear.

I always use the method that takes the Fragment as variable:

    IntentIntegrator scanIntegrator = new IntentIntegrator(fragment);

Where fragment is the actual fragment obviously but *sometimes*, not always, I'm receiving a **NullPointerException** in the line of the function findTargetAppPackage that I pointed out previously, this line:

    PackageManager pm = activity.getPackageManager();

**Comment by srowen** [comment]
What is null? activity or PackageManager?
