### ISSUE TITLE
how to set custom layout to zxing and scanning multiple times 

### ISSUE THREAD

**Issue by kailash09dabhi** [zxing/zxing#367]

**Comment by kailash09dabhi** [comment]
Please atleast clear my question.

**Comment by srowen** [comment]
There's not a clear question here, and this is not where you ask questions.

**Comment by kailash09dabhi** [comment]
Ok I got the solution though but I agreed I should not post question here. But Was frustrating to find info about this question i think please you guys should post info regarding this in wiki of this project.
And thanks for being responsive.Have a good day.!
