### ISSUE TITLE
receive barcodes in tasker

### ISSUE THREAD

**Issue by SneakyWhoami** [zxing/zxing#369]
Maybe this feature is perfectly functional and i just dont grok the documentation..? I hope its within the projects scope. Maybe its really a tasker "bug"?

I want to call zxing from a tasker task and then use the captured barcode from within tasker. I can call zxings scan intent from within tasker but i cant find a way to use the result.
It would be nice if zxing could produce a nice tasker/locale plugin or whatever to allow some fully automated use to be set up on device like that.

**Comment by srowen** [comment]
I don't know what a tasker task is, but have a look at the documentation for invoking via Intent: https://github.com/zxing/zxing/wiki This is for proposing patches, not asking questions. This kind of plugin would be too niche to implement in the main project.

**Comment by SneakyWhoami** [comment]
Alright, thought as much. Worth a shot though. Thanks and keep up the good
work

**Comment by M13Kd** [comment]
Have I earned anything so I can buy food??
