### ISSUE TITLE
poor performance using core in own app

### ISSUE THREAD

**Issue by daisylassie** [zxing/zxing#371]
hi,

we implemented your zxing/core source in our app and see that it takes 2-4 seconds to scan a 1d barcode from camera preview.

your zxing app does this in just milliseconds. do you have any tipps for us to do the scan faster.
in other words: does the decode function in your app the same work as in an "own" app.

the purpose of this question is, to get a hint if we have to investigate inside the zxing source or in the camera preview things which gives the info to the decoder.

best regards, reinhard

**Comment by srowen** [comment]
I don't think there's any magic, but indeed you have its entire source to browse and that's up to you. This is for proposing patches rather than questions.
