### ISSUE TITLE
GS1-Integration for Datamatrix

### ISSUE THREAD

**Issue by etalon** [zxing/zxing#373]
At the moment GS1 is only supported for Code128. There is also the possibility to print a GS1-String into a Datamatrix-Code. It would be nice if this would be integrated. 

http://www.gs1.org/docs/barcodes/GS1_DataMatrix_Guideline.pdf

Thanks a lot.

**Comment by srowen** [comment]
This is bring your own patch only at this point.

**Comment by PoliticallyIncorrectTalkin** [comment]
Thank you. I'm sorry to say I have been very sick after a heart attack I had. But am good now. Its why I have not been here till today. I'm very sorry to be delayed.
Regards
@PoliticallyIncorrectTalkin

**Comment by andreygursky** [comment]
Hi,
GS1 support for the datamatrix is missing, so why this issue is closed?

**Comment by oehhar** [comment]
Am 13.07.2016 um 23:44 schrieb andreygursky:
> Hi,
> GS1 support for the datamatrix is missing, so why this issue is closed?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zxing/zxing/issues/373#issuecomment-232495969>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/AL1sLZUW1euGwl51rGShLVYUBzE9S1YKks5qVVw2gaJpZM4ETkYx>.
> 

Maybee the section "Android" of
http://www.elmicron.de/P2P/info.html
may help you.
It decodes also an URL encoded in GS1 Codes.

- Harald

**Comment by andreygursky** [comment]
Harald, thanks for the patch. Pretty tiny. Now I have to figure out how to build zxing for Android with a one liner. Is the androidtest being packaged as an official .apk?

**Comment by oehhar** [comment]
Am 14.07.2016 um 21:08 schrieb andreygursky:
> Harald, thanks for the patch. Pretty tiny. Now I have to figure out how
> to build zxing for Android with a one liner. Is the androidtest being
> packaged as an official .apk?

On the web site, there is an apk.
Nevertheless, I would call it "public" but not "official".

The exposed functionality, to extract a contained URL from GS1 (and ASC
MH10.31 industrial structures) would be quite helpful for zxing.

Nevertheless, I am not the person to push this forward, lack of java
knowledge.

And there is another patch for zxing which is getting more important:
http://www.dmre.info/ containing a pull request.
This is now an ISO project and is on the way to an international standard.

Harald
