### ISSUE TITLE
Cancelling Before Scan Results in Black Camera on Next Scan

### ISSUE THREAD

**Issue by neoncube2** [zxing/zxing#376]
To reproduce, put the following code in a project, perhaps so that it runs when a button is clicked so that the code can easily be ran more than once.

```C#
MobileBarcodeScanner scanner = new MobileBarcodeScanner(Deployment.Current.Dispatcher);

//Tell our scanner to use the default overlay
scanner.UseCustomOverlay = false;

//We can customize the top and bottom text of our default overlay
scanner.TopText = "Hold camera up to barcode";
scanner.BottomText = "Camera will automatically scan barcode\r\n\r\nPress the 'Back' button to Cancel";

ZXing.Result scanResult = await scanner.Scan(scanningOptions);
```

While the camera is initializing (the TopText and BottomText are shown, but nothing from the camera is), hit the back button on the phone to cancel scanning. Then run the above code again to try to scan again. The TopText and BottomText are shown, but the camera never initializes. Getting out of the app and back in seems to fix the issue.

**Comment by srowen** [comment]
This looks like zxing.net which is a different project.

**Comment by neoncube2** [comment]
Ah, thanks. Sorry for the trouble.
