### ISSUE TITLE
Turning torch on has no effect

### ISSUE THREAD

**Issue by andyhammar** [zxing/zxing#377]
Trying this with Xamarin Forms, has no effect on either platform. (iOS, Droid, Wp).
(Lib works and we can scan codes).

iOS has a flash button, and that turns on the flash.

But doing: 
  scanner.Torch(true); 
or 
  scanner.ToggleTorch();
before starting to scan has no effect.

(On Droid, scanner.IsTorchOn=true after the call, but on Wp = false)

Am I using it wrong?
Thanks

**Comment by srowen** [comment]
This is code from a different project that you're talking about

**Comment by andyhammar** [comment]
Of course, sorry 'bout that. Thanks
