### ISSUE TITLE
Doesn't scan PDF417 barcode using Samsung tablet

### ISSUE THREAD

**Issue by Jimmymp1632** [zxing/zxing#378]
App is not able to scan PDF417 barcode (US Driving License) using Samsung tablet cameras (2015 Samsung Galaxy Tab S 10.5 with Auto Focus). However, the same app is able to scan pdf417 barcode using Samsung Galaxy Note 3 phone.

**Comment by srowen** [comment]
Yeah, drivers licenses are hard to scan because they're dense and sometimes smudged. It depends a lot on the camera. Unless you have a PR here I don't think there's a change that will come of this.

**Comment by Jimmymp1632** [comment]
but it works fine with Nexus tablet (5mp with auto focus) which has a worst camera then samsung tablet (8mp with auto focus). Any solutions you can think of ? I really need to implement this feature into our app.

Thank you
