### ISSUE TITLE
getRawBytes() on scanning Aztec Code returns NULL

### ISSUE THREAD

**Issue by BRAINBLENDr** [zxing/zxing#379]
getRawBytes() on scanning Aztec Code returns NULL

**Comment by BRAINBLENDr** [comment]
Why is this closed?

**Comment by srowen** [comment]
This doesn't even partly describe a problem, let alone a PR that fixes whatever this is.

**Comment by BRAINBLENDr** [comment]
Sorry, i'm trying to get the raw bytes from an Aztec code, currently the raw bytes method seems to return null.

What can I do to get the raw bytes?

I'm sorry that I'm not very good in explaining my issue, I hope this clarifies it some more.

**Comment by BRAINBLENDr** [comment]
(Here is the code that is failing)[https://github.com/BRAINBLENDr/AztecCollect/blob/master/app/src/main/java/com/brainblendr/azteccollect/MainActivity.java]

**Comment by BRAINBLENDr** [comment]
Is this something you can help me with?
