### ISSUE TITLE
Aztec Decoder broken, getRawBytes never populated

### ISSUE THREAD

**Issue by iSDP** [zxing/zxing#381]
I've found the issue why getRawBytes() is not populated, it can be found [here](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/aztec/decoder/Decoder.java#L79)

What needs to be done to pass the raw Bytes along?

**Comment by iSDP** [comment]
Fixed it myself, do you want the code?

**Comment by srowen** [comment]
Yeah, like turning the 'bits' into a `byte[]`? I think that was never implemented because the code came from a different place. The bytes may or may not be meaningful, but better to return something than nothing. If you have a PR for that, that's fine.

**Comment by iSDP** [comment]
I'll look into it

**Comment by iSDP** [comment]
Made a PR: https://github.com/zxing/zxing/pull/389

**Comment by alotaibiatm** [comment]
Tanks
