### ISSUE TITLE
Attempt to access a cursor after it has been closed

### ISSUE THREAD

**Issue by drewdrewcarlstedt** [zxing/zxing#385]
Test Name: Monkey Test 4____________	Version: _1__________

Severity (Fatal, Serious, Minor): _Minor____________

Type: (Coding Error, Design Issue, Suggestion, Documentation): _Coding Error__________

Summary: _Attempt to access a cursor after it has been closed_________________________

Able to be reproduced? (Yes/No): _Yes________

What is the problem and how can it be reproduced?
__See Monkey output file______________________________________________________
      __run Monkey with seed 1431413465180_________________________________________
___________________________________________________________________________

Suggestions (optional):
___________________________________________________________________________
___________________________________________________________________________
___________________________________________________________________________

Reported By: __Drew Carlstedt________________	Date: _5/13/2015_______

~~~~~~~~~~~~~~~~~~~~~ DEVELOPMENT TEAM ONLY ~~~~~~~~~~~~~~~~~~~~~

Functional Area: ____________________________	Assigned To: ____________________

Comments: ___________________________________________________________________________
___________________________________________________________________________

Status (Open/Closed): _____________________	Priority (1-5): __________________

Resolution (Pending, Fixed, Irreproducible, Reassigned, As Intended, Unfixable, Withdrawn, Requesting More Information, Disagree with Suggestion): ___________________________

Resolved By: _______________________	Date: ________________

Tested By: _________________________	Date: ________________

Fixed Version Number: ______________________

**Comment by drewdrewcarlstedt** [comment]
:Monkey: seed=1431413465180 count=1500

:AllowPackage: com.google.zxing.client.android

:IncludeCategory: android.intent.category.LAUNCHER

:IncludeCategory: android.intent.category.MONKEY

// Event percentages:

//   0: 15.0%

//   1: 10.0%

//   2: 2.0%

//   3: 15.0%

//   4: -0.0%

//   5: 25.0%

//   6: 15.0%

//   7: 2.0%

//   8: 2.0%

//   9: 1.0%

//   10: 13.0%

:Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.google.zxing.client.android/.CaptureActivity;end

    // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.google.zxing.client.android/.CaptureActivity } in package com.google.zxing.client.android

:Sending Touch (ACTION_DOWN): 0:(932.0,457.0)

// CRASH: com.google.zxing.client.android (pid 2727)

// Short Msg: android.database.StaleDataException

// Long Msg: android.database.StaleDataException: Attempted to access a cursor after it has been closed.

// Build Label: generic_x86/sdk_google_phone_x86/generic_x86:5.0.2/LSY66D/1797986:eng/test-keys

// Build Changelist: 1797986

// Build Time: 1426728420000

// android.database.StaleDataException: Attempted to access a cursor after it has been closed.

// 	at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:64)

// 	at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:70)

// 	at android.database.CursorWrapper.getCount(CursorWrapper.java:57)

// 	at com.google.zxing.client.android.share.BookmarkAdapter.getCount(BookmarkAdapter.java:49)

// 	at android.widget.ListView.layoutChildren(ListView.java:1561)

// 	at android.widget.AbsListView.onTouchModeChanged(AbsListView.java:3545)

// 	at android.view.ViewTreeObserver.dispatchOnTouchModeChanged(ViewTreeObserver.java:879)

// 	at android.view.ViewRootImpl.ensureTouchModeLocally(ViewRootImpl.java:3340)

// 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1753)

// 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)

// 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)

// 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)

// 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)

// 	at android.view.Choreographer.doFrame(Choreographer.java:550)

// 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)

// 	at android.os.Handler.handleCallback(Handler.java:739)

// 	at android.os.Handler.dispatchMessage(Handler.java:95)

// 	at android.os.Looper.loop(Looper.java:135)

// 	at android.app.ActivityThread.main(ActivityThread.java:5221)

// 	at java.lang.reflect.Method.invoke(Native Method)

// 	at java.lang.reflect.Method.invoke(Method.java:372)

// 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)

// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

// 

** Monkey aborted due to error.

Events injected: 2

:Sending rotation degree=0, persist=false

:Dropped: keys=0 pointers=0 trackballs=0 flips=0 rotations=0

## Network stats: elapsed time=2084ms (0ms mobile, 0ms wifi, 2084ms not connected)

** System appears to have crashed at event 2 of 1500 using seed 1431413465180

**Comment by srowen** [comment]
This sounds like something fixed a while ago
