### ISSUE TITLE
splitQuery ignore characters

### ISSUE THREAD

**Issue by drewdrewcarlstedt** [zxing/zxing#388]
Test Name: splitQuery Unit Test	Version: 1.0

Severity (Fatal, Serious, Minor): Minor

Type: (Coding Error, Design Issue, Suggestion, Documentation): Coding Error

Summary: Method should get rid of repeated specific characters, but it do not. 

Able to be reproduced? (Yes/No): Yes

What is the problem and how can it be reproduced?
The Javadoc for the method splitQuery, inside class DecodeHintManager, states that the method should ignore repeated specific characters, such as double ampersands, using only the first one. After unit tests, we find out that it although it ignores the repeated characters, the final result will be different as if you had only a single specific character.

Suggestions (optional):
___________________________________________________________________________
___________________________________________________________________________
___________________________________________________________________________

Reported By: Anderson             Date: 5/7/2015

~~~~~~~~~~~~~~~~~~~~~ DEVELOPMENT TEAM ONLY ~~~~~~~~~~~~~~~~~~~~~

Functional Area: ____________________________	Assigned To: ____________________

Comments: ___________________________________________________________________________
___________________________________________________________________________

Status (Open/Closed): _____________________	Priority (1-5): __________________

Resolution (Pending, Fixed, Irreproducible, Reassigned, As Intended, Unfixable, Withdrawn, Requesting More Information, Disagree with Suggestion): ___________________________

Resolved By: _______________________	Date: ________________

Tested By: _________________________	Date: ________________

Fixed Version Number: ______________________

**Comment by srowen** [comment]
This might be easy to fix but I need an example. There's nothing about a reproduction here.
