### ISSUE TITLE
Multibyte characters are not handled properly in PDF417 encoder 

### ISSUE THREAD

**Issue by strguntbr** [zxing/zxing#394]
Trying to encode the string "1%§s ?aG$" with PDF417 encoder (Charset UTF-8, Compaction Byte) throw a "Non-encodable character detected" exception.

The problem seems to be that § is encoded as "c2 a7" in unicode and thus for all characters after the § the index in the input-string does not match the index in the encoded byte array.

**Comment by srowen** [comment]
Hm yeah, I don't know a lot about this code path, but I can imagine the problem and your fix looks reasonable. Let me think about it a little more, but since tests pass and it doesn't seem to affect other behavior, can't hurt much to merge I think.
