### ISSUE TITLE
Android project displaying QR-code can not find zxing classes in the jar files

### ISSUE THREAD

**Issue by afarber** [zxing/zxing#398]
Good evening,

I am trying to create [a simple Android app](https://github.com/afarber/android-newbie/tree/master/QREncoder), which would display a QR-coded image.

So I have installed HomeBrew, ant and maven at my Mac OS Yosemite notebook and pointed the ANDROID_HOME environment variable to the location of Android SDK.

Then I have checked out latest zxing from GitHub and built it (seeming without any errors) with the command `mvn package` (and using javac version 1.8.0_45).

After that I have created a new Android project with blank Activity in Eclipse and copied the 3 jar files into its libs directory:

    android/libs/core-3.2.1-SNAPSHOT.jar
    android-core/target/android-core-3.2.1-SNAPSHOT.jar
    android/target/android-4.7.4.jar

Unfortunately, my simple code in [MainActivity.java](https://raw.githubusercontent.com/afarber/android-newbie/master/QREncoder/src/de/afarber/qrencoder/MainActivity.java) does not compile:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ImageView imageView = (ImageView) findViewById(R.id.qrCode);
        String qrData = "Data I want to encode in QR code";
        int qrCodeDimention = 500;
        QRCodeEncoder qrCodeEncoder = new QRCodeEncoder(qrData, 
            null,
            Contents.Type.TEXT, 
            BarcodeFormat.QR_CODE.toString(), 
            qrCodeDimention);

        try {
            Bitmap bitmap = qrCodeEncoder.encodeAsBitmap();
            imageView.setImageBitmap(bitmap);
        } catch (WriterException e) {
            e.printStackTrace();
        }
    }

The errors are (here [Eclipse-screenshot](http://i.stack.imgur.com/ycE15.png)):

    BarcodeFormat cannot be resolved
    Contents cannot be resolved to a variable
    QRCodeEncoder cannot be resolved to a type
    QRCodeEncoder cannot be resolved to a type
    WriterException cannot be resolved to a type

But at the same time I can see these (supposedly not found by Eclipse) classes by calling tar tool:

    # tar tvfz libs/core-3.2.1-SNAPSHOT.jar | grep -i WriterException
    -rwxrwxrwx  0 0 0 0 28 Mai 20:35 com/google/zxing/WriterException.class
    # tar tvfz libs/core-3.2.1-SNAPSHOT.jar | grep -i BarcodeFormat
     -rwxrwxrwx  0 0 0 0 28 Mai 20:35 com/google/zxing/BarcodeFormat.class
    # tar tvfz libs/android-4.7.4.jar | grep -i QRCodeEncoder
    -rwxrwxrwx  0 0 0 0 28 Mai 20:39 com/google/zxing/client/android/encode/QRCodeEncoder.class

What am I doint wrong please, why can't Eclipse find the classes?

Greetings from Germany
Alex

**Comment by srowen** [comment]
You should not include the `android-*` jar; it's not a library to be reused. But that is not your problem. This is something to do with your project setup in Eclipse and not this project.

**Comment by A024806** [comment]
喔哈日歷史殺人爾西下人私立西索三月利息瑞穗日下下運用zeal卻越來越發財雷森園雖啥名拉下三月司法林6Cpeacock有老人院子裡熱熱過癮

**Comment by A024806** [comment]
JA AF legal vs如此好H貨J消息月刊6ˉ卡滋卡滋Uˉ去U親戚喜歡自由卡滋卡滋呼吸器而有親戚齊齊而侵權狂咳Y輕輕一妻卡滋卡滋七期烤漆其全球開啟而其而其啐剛剛及全球齊齊而且其而其取其而全球&去咳嗽思考中國國情逾期看似球員咳咳咳咳YY前去球員f族群看看Y自取其余去瞧瞧其餘前去瞧瞧其餘全球Y與全球U愉快前四強賽及運送捷運局隨即於拒絕角色捷運局預期Y結果感覺察覺全國格格結局其餘親情與球員其餘時間和國際局局局長麴取決於去球員Y麴去6取決於其餘全球之開口之前月召開之麴去其二Y麴去全球與m之請求而且Y自取其自信而Y前妻求去要求Y其6全球最曲子親自去Y開二兒子親自去自取其自信而族群Y去Y親兒子去兒子去Y卡滋卡滋去吃孩子控制看出去Y開著開著開Y去而且而且兒子去試一試遊戲有時是要醫師諮詢而成孩子會吃虧而且

**Comment by afarber** [comment]
Alright, I've fixed my problem (QR-encoding String to a Bitmap in Android) by looking at the android/src/com/google/zxing/client/android/encode/QRCodeEncoder.java:

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);
            ImageView imageView = (ImageView) findViewById(R.id.qrCode);
            try {
                Bitmap bitmap = encodeAsBitmap(STR);
                imageView.setImageBitmap(bitmap);
            } catch (WriterException e) {
                e.printStackTrace();
            }
        }

        Bitmap encodeAsBitmap(String str) throws WriterException {
            BitMatrix result;
            try {
                result = new MultiFormatWriter().encode(str, 
                    BarcodeFormat.QR_CODE, WIDTH, WIDTH, null);
            } catch (IllegalArgumentException iae) {
                // Unsupported format
                return null;
            }
            int w = result.getWidth();
            int h = result.getHeight();
            int[] pixels = new int[w * h];
            for (int y = 0; y < h; y++) {
                int offset = y * w;
                for (int x = 0; x < w; x++) {
                    pixels[offset + x] = result.get(x, y) ? BLACK : WHITE;
                }
            }
            Bitmap bitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
            bitmap.setPixels(pixels, 0, width, 0, 0, w, h);
            return bitmap;
        }

The resulting screenshot and more details can be seen in [my Stackoverflow question](http://stackoverflow.com/questions/30515584/qr-encode-a-string-to-image-in-android-project-using-zxing).
