### ISSUE TITLE
meCode wrongly encodes telephone number

### ISSUE THREAD

**Issue by dsp76** [zxing/zxing#399]
For an international number - like +4935100000000 - the meCard doesn't include the required "+". The number will be encoded without and can't be dialed. Using vCard ist working fine.

**Comment by srowen** [comment]
You haven't specified how you are encoding this value or what the result is.

**Comment by dsp76** [comment]
@srowen I used the webbased encoding at https://zxing.appspot.com/generator, selected "contact information" encoded as "meCard". I put "+4935100000000" into the phone number field. 

The result is lacking the "+" sign for international prefix: 

MECARD:N:meCard;TEL:4935100000000;;

http://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=MECARD%3AN%3AmeCard%3BTEL%3A4935100000000%3B%3B

If I encode as vCard, its working fine:

BEGIN:VCARD
VERSION:3.0
N:meCard
TEL:+4935100000000
END:VCARD 

http://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=BEGIN%3AVCARD%0AVERSION%3A3.0%0AN%3AmeCard%0ATEL%3A%2B4935100000000%0AEND%3AVCARD

**Comment by srowen** [comment]
MECARD format says this field is digits-only. You need to write + as 00. https://www.nttdocomo.co.jp/english/service/developer/make/content/barcode/function/application/addressbook/index.html

**Comment by dsp76** [comment]
"00" is only correct for some countries. Only "+" qualifies as international prefix. If you save your number with "00" as international number, you won't be able to dial it many countries in the world. Have a look here:
http://en.wikipedia.org/wiki/List_of_international_call_prefixes

So meCard standard has a blind spot here. However almost all soft phones and smart phones are capable of handling the "+" sign.

**Comment by srowen** [comment]
Yeah that may be, but that's a MECARD issue if anything. It was originally created in the 90s for i-mode in Japan so may not be entirely internationalized. You can use vCard instead.

**Comment by dsp76** [comment]
Technically that is absolutely the correct answer.
If MECARD "standard" is not maintained anymore, maybe a not so strict implementation might be helpful?

**Comment by srowen** [comment]
Yeah, I think that's not unreasonable. Do you want to make a patch that would allow this character?

**Comment by dsp76** [comment]
If I could, but I'm not a programmer :(

Gruß Dirk
Tel.: +49 176 3030 4050

2015-06-08 21:42 GMT+02:00 Sean Owen <notifications@github.com>:

**Comment by M13Kd** [comment]
Love it
