### ISSUE TITLE
Invisible Mode

### ISSUE THREAD

**Issue by saenzramiro** [zxing/zxing#401]
Hello,

I'm using this amazing library with official PhoneGap plugin (https://github.com/phonegap/phonegap-plugin-barcodescanner).

I want to make an scan without showing any frame (silent-invisible) and in portrait mode. So when I start my app, start scanning when I still seeing my webview with an HTML page.

Can anyone help me with this?

**Comment by srowen** [comment]
I think that is more a phonegap question, but no there is nothing like this in this project and I wouldn't accept a PR for this at this stage.
