### ISSUE TITLE
CODE_93 generation possible?

### ISSUE THREAD

**Issue by codewell4** [zxing/zxing#403]
I was trying to generate CODE_93 from text but it always says that it can't encode it. So my question is, if generation of this type of code is supported?

Below is code sample with text from Wikipedia, but I tried also with valid Code_93 and while the barcode scanner recognizes it, it can't generate it.
```java
    Intent intent = new Intent("com.google.zxing.client.android.ENCODE");
    intent.putExtra("ENCODE_TYPE", "TEXT_TYPE" );
    //Should generate : https://en.wikipedia.org/wiki/Code_93
    intent.putExtra("ENCODE_DATA", "WIKIPEDIA" );
    intent.putExtra("ENCODE_FORMAT", "CODE_93");
    intent.putExtra("ENCODE_SHOW_CONTENTS", false );
    startActivity(intent);
```
Hopefully this is not a stupid question :P

**Comment by srowen** [comment]
(Use https://groups.google.com/forum/#!forum/zxing for questions)
No Code 93 encoding is not supported, unless I'm crazy and forgetting it.

**Comment by codewell4** [comment]
Another question. If I make the writer (Code93Writer) myself would you be able to put it into the core?
Maybe the code will not be nice as I'm not experienced.
