### ISSUE TITLE
The function ensureCapacity:() in ZXBitArray.m resizes a block of allocated memory on line 77.

### ISSUE THREAD

**Issue by Antonio-strickland** [zxing/zxing#408]
Details:"The function ensureCapacity:() in ZXBitArray.m resizes a block of allocated memory on line 77.

Pods/ZXingObjC/ZXingObjC/common/ZXBitArray.m:(Line 77)"

Impact:Do not use realloc() to resize buffers that store sensitive information.  The function might leave a copy of the sensitive information stranded in memory where it cannot be overwritten.

Fix:If sensitive information is stored in memory and there is a risk of an attacker having access to a memory dump, replace realloc() with explicit calls to malloc(), memcpy(), and free(). This approach gives you the opportunity to safely scrub the contents of the original buffer before it is freed.

**Comment by srowen** [comment]
This code isn't in this project now.
