### ISSUE TITLE
Launch QR code scanner inside HTML page

### ISSUE THREAD

**Issue by nvarshney** [zxing/zxing#411]
Anybody suggest me how can I launch the QR scanner inside the html form (for iOS and android phonegap app)?

**Comment by RobertMcC86** [comment]
Sent by Outlook for Android



From: nvarshney

Sent: Thursday, July 2, 6:28 AM

Subject: [zxing] Launch QR code scanner inside HTML page (#411)

To: zxing/zxing



Anybody suggest me how can I launch the QR scanner inside the html form?

**Comment by nvarshney** [comment]
Anybody please reply.

**Comment by Vigi0303** [comment]
in android, intent filter in manifest.xml meight help you
