### ISSUE TITLE
OkapiBarcode plug

### ISSUE THREAD

**Issue by woo-j** [zxing/zxing#417]
Hi,

Sorry this isn't really an issue so much as something I wanted to let you know about, and I'm afraid I wasn't sure where/how else to do so...

I'm the main developer behind the Zint library which you link to in your README.md file. Firstly, can I let you know that I'm no longer developing or supporting Zint, so I think that link should be removed. But also that I am developing a Java-based replacement called OkapiBarcode which is right here on GitHub which includes most of the functionality from Zint including numerous bugfixes, and which, IMHO, has already surpassed Barcode4J in usefulness! It's still a moving target at the moment, but I thought it might be useful to ZXing users.

Thanks,

Robin.

**Comment by srowen** [comment]
OK, do you have a link to the successor project? I'm happy to link to it in addition to removing the old link.

**Comment by woo-j** [comment]
Here's the URL:
https://github.com/woo-j/OkapiBarcode

Thanks.
