### ISSUE TITLE
PDF_417 lineThickness

### ISSUE THREAD

**Issue by awenger** [zxing/zxing#418]
Is there a reason to start the PDF_417 generation with a lineThickness of 2 [1] if the barcode is later scalled [2]. This excludes the generation of barcodes with lineThickness of 3 for example.

[1] https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/pdf417/PDF417Writer.java#L100
[2] https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/pdf417/PDF417Writer.java#L121

**Comment by srowen** [comment]
I dont' think I get the question (didn't write this code either) but if you can show and explain a change in a PR I can look at it.

**Comment by awenger** [comment]
The current generation starts with lineThickness 2 and scales the barcode later to fit into the available space. This prevents for example the generation of a barcode with scale factor 1,3,5 etc.
