### ISSUE TITLE
provide methods for content correctness check

### ISSUE THREAD

**Issue by Zavael** [zxing/zxing#420]
I was not able to check if the contents i want to encode are correct according to BarcodeFormat.
For example before doing
```
new MultiFormatWriter().encode(qrCodeData, BarcodeFormat.QR_CODE, codeWidth, codeHeight, map);
```
I would like to check
```
new MultiFormatWriter().encodable(qrCodeData, BarcodeFormat.QR_CODE);
```
which could either return true/false or throw Exceptions like the encode method.
In Ean13Writer are the validity checks provided at the start of encode(contents) method, so it should not be hard to extract them into separate public method and reuse, if the pattern is similar in all writers (did not check).
I am doing the generation asynchronous to the creation of db entry, but I need to know if the data are valid before the encoding proces.

**Comment by srowen** [comment]
You can simply catch for exceptions. There is a well-defined exception hierarchy for this. It doesn't require an API change, works for all the encoders, and is the intended way to check this.

**Comment by Zavael** [comment]
I think it is not really effective to call encode only for the information that the contents are invalid. See pseudocode of your suggestion:
```
for(multipleIterations) {
    object = createSomeObject(params);
    try {
        writer.encode(object.content, object.format);
        // this - instead of simple checking - is time and resource 
        // consuming (slower) as it will generate the bitmatrix even if 
        // the caller only wants to know if contents are valid (and fail fast if not)
        saveObject(object); //without generated image
    } catch {
        // inform user or continue or break or 
        // create list of wrong contents...        
    }
    scheduleObjectToProcess(object);
}
someProcessingThread.startIfNotRunning(); // includes writer.encode(object.content, object.format) again and updating object with generated image
```

Example case described: Scheduling of object to queue contains its id, code and format. Processing of object means encoding the contents **again**, creating a image and upload to amazon s3 for example. In the moment of processing the exception cannot be proceeded to the user.
Sending Bitmatrix instead of code and format would be inefective - its bigger and the bitmatrix is not needed yet.
Besides that, it would separate the knowledge of *contents validity* from the *bitmatrix creation* itself and enhance the code quality.
I still think this is a valid request for enhancement.

**Comment by srowen** [comment]
Why do you have to process it twice? It either succeeds or fails in one pass.

I suppose my point is the act of deciding whether it's encodable often means executing some or most of the encoding process anyway; there's not much to save. Creating an 'encodable' API is mostly recreating the whole encoding process anyway, to be really sure. The encoding process is also generally very fast, so I think it's not worth worrying about.

**Comment by Zavael** [comment]
Thanks for you responses.
Because if it suceeds I send the object id, code and codeformat to processing queue. Only there I create the image and only there I need BitMatrix, no reason to create it before, I dont need the bitmatrix in case I only want to validate context.  
For example in `QRCodeWriter` I am only interested in these lines - and they could be extracted as separate method and call that method... you would just provide a separate way to check, the encode method would still check that too.
```
...
if (contents.isEmpty()) {
  throw new IllegalArgumentException("Found empty contents");
}

if (format != BarcodeFormat.QR_CODE) {
  throw new IllegalArgumentException("Can only encode QR_CODE, but got " + format);
}

if (width < 0 || height < 0) {
  throw new IllegalArgumentException("Requested dimensions are too small: " + width + 'x' +
      height);
}
...
```
I could provide myself the validity check in our code. But in `EAN13Writer` I am interested in these lines:
```
...
if (contents.length() != 13) {
  throw new IllegalArgumentException(
      "Requested contents should be 13 digits long, but got " + contents.length());
}
try {
  if (!UPCEANReader.checkStandardUPCEANChecksum(contents)) {
    throw new IllegalArgumentException("Contents do not pass checksum");
  }
} catch (FormatException ignored) {
  throw new IllegalArgumentException("Illegal contents");
}
...
```
but I can not call UPCEANReader.checkStandardUPCEANChecksum(contents) from my code - its non-public.  
After this parts, the contents should be encodable, or am I wrong?

**Comment by srowen** [comment]
Yeah, I mean, that's an artifact of how your system works though; in general you can invoke the method once and either get a result or know it could not encode. Honestly it is not worrying about optimizing this by exposing this logic. Having to call the method twice is so cheap. This stuff was written to be efficient on _phones_ even as of 8 years ago. Server-class machines would do this in microseconds.

**Comment by Zavael** [comment]
ok thank you, for now we will call it twice
