### ISSUE TITLE
PDF417 Scanning

### ISSUE THREAD

**Issue by StevenDStanton** [zxing/zxing#422]
When Scanning PDF417 it seems that the barcode to be the perfect distance (about 1 inch) from the camera and cannot move at all.

When moving it 6 inches away the camera keeps auto focusing and will never scan it

I have tested with Manatee and PDF417.mobi and both of those scanners are able too scan the barcodes instantly. 

I have left the PDF417 barcode in the same position that the other two scanners were able to scan it instantly in and ZXing sat there for over an hour focusing and refocusing on the barcode and never scanning it,

Below is a log of the apps output trying to scan the ID. I do have my app set to look for PDF417 barcodes only

**Comment by StevenDStanton** [comment]
[SurfaceView] updateWindow -- OnPreDrawListener, mHaveFrame = true, this = md5e1d4744ef128cd013cac92521f1a8e76.ZXingSurfaceView{4246fe00 V.E..... ........ 0,0-1920,1128}
[Camera-JNI] Allocating callback buffer
[CameraFramework] handleMessage: 16
[Camera-JNI] setHasPreviewCallback: installed:1, manualBuffer:0
[SurfaceView] updateWindow -- OnPreDrawListener, mHaveFrame = true, this = md5e1d4744ef128cd013cac92521f1a8e76.ZXingSurfaceView{4246fe00 V.E..... ........ 0,0-1920,1128}
[Camera-JNI] Allocating callback buffer
[CameraFramework] handleMessage: 16
[Camera-JNI] setHasPreviewCallback: installed:1, manualBuffer:0
[SurfaceView] updateWindow -- OnPreDrawListener, mHaveFrame = true, this = md5e1d4744ef128cd013cac92521f1a8e76.ZXingSurfaceView{4246fe00 V.E..... ........ 0,0-1920,1128}
[Camera-JNI] Allocating callback buffer
[CameraFramework] handleMessage: 16
[Camera-JNI] setHasPreviewCallback: installed:1, manualBuffer:0
[SurfaceView] updateWindow -- OnPreDrawListener, mHaveFrame = true, this = md5e1d4744ef128cd013cac92521f1a8e76.ZXingSurfaceView{4246fe00 V.E..... ........ 0,0-1920,1128}
[Camera-JNI] Allocating callback buffer
[CameraFramework] handleMessage: 16
[Camera-JNI] setHasPreviewCallback: installed:1, manualBuffer:0
[SurfaceView] updateWindow -- OnPreDrawListener, mHaveFrame = true, this = md5e1d4744ef128cd013cac92521f1a8e76.ZXingSurfaceView{4246fe00 V.E..... ........ 0,0-1920,1128}
[Camera-JNI] Allocating callback buffer
[CameraFramework] handleMessage: 16
[Camera-JNI] setHasPreviewCallback: installed:1, manualBuffer:0
[CameraFramework] Camera framework getParameters =3dnr-mode=on;3dnr-mode-values=on,off;afeng-max-focus-step=1023;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz,auto;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;brightness=middle;brightness-values=low,middle,high;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,autorama,mav,asd,motiontrack;capfname=/sdcard/DCIM/cap00;contrast=middle;contrast-values=low,middle,high;cshot-indicator=true;cshot-indicator-supported=true;dynamic-frame-rate=true;dynamic-frame-rate-supported=true;edge=middle;edge-values=low,middle,high;effect=none;effect-values=none,mono,negative,sepia,aqua,whiteboard,blackboard,posterize,nashville,hefe,valencia,xproll,lofi,sierra,walden;eng-mfll-e=false;eng-mfll-s=true;eng-s-shad-t=0;eng-shad-t=0;exposure-compensation=0;exposure-compensation-step=1.0;face-beauty=false;face-beauty-supported=true;fb-enlarge-eye=0;fb-enlarge-eye-max=4;fb-enlarge-eye-min=-4;fb-extreme-beauty=true;fb-extreme-beauty-supported=false;fb-face-pos=-2000:-2000;fb-sharp=0;fb-sharp-max=4;fb-sharp-min=-4;fb-skin-color=0;fb-skin-color-max=4;fb-skin-color-min=-4;fb-slim-face=0;fb-slim-face-max=4;fb-slim-face-min=-4;fb-smooth-level=0;fb-smooth-level-max=4;fb-smooth-level-min=-4;fb-touch-pos=-2000:-2000;feature-max-fps=24@VFB+EIS;flash-duty-max=1;flash-duty-min=0;flash-duty-value=-1;flash-step-max=0;flash-step-min=0;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-fs-fi=0;focus-fs-fi-max=65535;focus-fs-fi-min=0;focus-mode=auto;focus-mode-values=auto,macro,infinity,continuous-picture,continuous-video,manual,fullscan;horizontal-view-angle=63;hsvr-prv-fps=30;hsvr-prv-fps-values=0,30,0,0;hsvr-prv-size=1280x720;hsvr-prv-size-values=0x0,1280x720,0x0,0x0;hue=middle;hue-values=low,middle,high;iso-speed=auto;iso-speed-values=auto,100,200,400,800,1600;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,320x240;jpeg-thumbnail-width=160;m-sr-g=0;m-ss=0;max-exposure-compensation=3;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=1;max-num-metering-areas=9;max-num-ot=1;max-zoom=10;mfb=off;mfb-values=off,mfll,ais;min-exposure-compensation=-3;mnr-e=0;mnr-s=true;mtk-123-shad-s=true;mtk-awb-s=true;mtk-cam-mode=0;mtk-shad-s=true;picture-format=jpeg;picture-format-values=jpeg;picture-size=3264x2448;picture-size-values=320x240,640x480,1024x768,1280x768,1280x960,1600x960,1600x1200,2048x1536,2560x1920,2880x1728,3264x2448,3600x2160;pip-fps-zsd-off=30;pip-fps-zsd-on=24;preferred-preview-size-for-video=1920x1080;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,60000;preview-fps-range-values=(5000,60000);preview-frame-rate=30;preview-frame-rate-values=20,15,24,30,60,120;preview-size=640x480;preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,1280x720,1280x768,1280x960,1440x1080,1600x960,1600x1200,1920x1080,1920x1088;rotation=0;saturation=middle;saturation-values=low,middle,high;scene-mode=auto;scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr;sen-mode-s=0;sensor-type=252;smooth-zoom-supported=true;sr-awb-s=true;sr-shad-s=true;stereo-depth-af=off;stereo-depth-af-values=on,off;stereo-distance-measurement=off;stereo-distance-measurement-values=on,off;stereo-image-refocus=off;stereo-image-refocus-values=on,off;sv1-s=3;sv2-s=3;vdr-cc2m-s=false;vdr-r=0;vdr-r2m-s=true;vdr-r4k2k-s=false;vertical-view-angle=49;vhdr-s=0;video-frame-format=yuv420p;video-hdr=off;video-hdr-values=off,on;video-size=640x480;video-size-values=176x144,480x320,640x480,864x480,1280x720,1920x1080,3840x2160;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true;vrd-mfr-e=true;vrd-mfr-high=30;vrd-mfr-low=15;vrd-mfr-max=30;vrd-mfr-min=15;vrd-mfr-s=true;whitebalance=auto;whitebalance-values=auto,inca
[SurfaceView] updateWindow -- OnPreDrawListener, mHaveFrame = true, this = md5e1d4744ef128cd013cac92521f1a8e76.ZXingSurfaceView{4246fe00 V.E..... ........ 0,0-1920,1128}

**Comment by srowen** [comment]
I probably couldn't say anymore, not having your barcodes. It will either scan in milliseconds or not at all. It's either unscannable due to a problem with the code, your camera hardware, or just a limit of the software. You can propose a PR if you have a change to make but otherwise there's not really an action here -- YMMV.

**Comment by StevenDStanton** [comment]
The Barcodes are from the back of drivers licenses.

It can't be a problem with the Barcodes because both Manatee and PDF417.Mobi scan them

Each scan has been done with the same hardware, at the same distance. 

It really can't be a software limitation as other companies have developed closed source software which can scan the codes in a few miliseconds. 

From what I am seeing with the differences in the code the other solutions get a clear image of the barcode, then freeze there and use that image

XZing seems to get a clear image of the barcode and then does a focus and tries again and again instead of using the clear image when it is in focus

**Comment by srowen** [comment]
I'm not saying it can't be done; I'm saying the software here might not get it done, and there is no further development work here, unless you are yourself proposing a code change. Please use other software if it works better for you in this case.
