### ISSUE TITLE
Switch display mode in help menu

### ISSUE THREAD

**Issue by IlianP** [zxing/zxing#423]
When switch from landscape mode into portrait mode and vice versa in the help menu on my LG G2 (Android 4.4.2) the content becomes a white screen.

**Comment by srowen** [comment]
There is not such a feature in this app

**Comment by IlianP** [comment]
I was talking about switching the orientation from landscape to portrait
and vice versa. I would do a screencast but you don't seem to appreciate
feedback...
Am 18.07.2015 12:35 schrieb "Sean Owen" <notifications@github.com>:

**Comment by IlianP** [comment]
I don't remember talking about any feature
Am 18.07.2015 13:07 schrieb <ilianos1@gmail.com>:

**Comment by srowen** [comment]
The app is landscape only which makes me think you are talking about another app.

**Comment by IlianP** [comment]
So you're not talking about the famous barcode scanner for Android?

Take an LG G2 with Android 4.4.2 >> press the 3 dots >> press help [from
here, rotation IS possible!] >> switch rotation and see what happens...

2015-07-18 14:02 GMT+02:00 Sean Owen <notifications@github.com>:

**Comment by srowen** [comment]
You are not talking about the app related to this project. Three dots >> Help leads to no information about rotation. You are talking about another app, which may be a copy of the open source code provided by this app.
