### ISSUE TITLE
Text of large codes overlaps heading

### ISSUE THREAD

**Issue by IlianP** [zxing/zxing#424]
See screenshot: https://www.dropbox.com/s/bujt1h890dwuv4f/2015-05-06-15-10-34.png?dl=0

**Comment by srowen** [comment]
I think you may be looking at an old version or an app clone. The text box should scroll

**Comment by IlianP** [comment]
It scrolls, but the text is displayed on top of the heading, as you can
obviously see in the screenshot...
Am 18.07.2015 12:36 schrieb "Sean Owen" <notifications@github.com>:
