### ISSUE TITLE
In zxing.org, where is send the form with the attached image?

### ISSUE THREAD

**Issue by doritos07** [zxing/zxing#426]
I'm trying to set my own zxing.org server in localhost to make tests. Doing that, i found that the page decode.jspx has an html form with action="decode". I'm just not understanding where is sent that form when i press the button send. As you can see, I'm really noob with jsp, but someone could point me in the good direction from where is sent that form/where is the script that receive them/where is the redirection i'm missing?

**Comment by srowen** [comment]
Ask questions on the mailing list please: https://groups.google.com/forum/#!forum/zxing
It goes to DecodeServlet in the web app. Yes, you probably want to read up on how JavaEE web apps are configured.
