### ISSUE TITLE
PDF417 not decoding

### ISSUE THREAD

**Issue by proCoderDude** [zxing/zxing#427]
Hi,

I am trying to decode the image attached. It gives a checksum error. I did some digging and found out that it only decoded the first and the last rows only.

Any ideas what the problem might be?

![clean07](https://cloud.githubusercontent.com/assets/13418629/8777198/c7c7c1c0-2ef6-11e5-80ad-1fb6a1cfd3f0.png)

**Comment by srowen** [comment]
There are a few possibilities: 1) bug in the code of course, 2) this is not being detected properly -- use PURE_BARCODE mode, 3) the barcode is actually corrupt or not supported. I think you'd have to run the debugger to dig more into why

**Comment by proCoderDude** [comment]
Thanks. I will continue digging. 
But I know for sure the barcode is not corrupted as I have tested in on andriod app, online decoders and barcode scanner. All gave me results.

**Comment by graug** [comment]
Hi proCoderDude,

as far as I can tell, the barcode is flipped vertically, i.e. it starts with row 33 and ends with row 0. The decoder assumes that the barcode correctly starts with row 0. I flipped the image and managed to decode it, although the content doesn't seem to be readable text.

![pdf417-flipped](https://cloud.githubusercontent.com/assets/4060134/8786268/690d66da-2f2d-11e5-9cfa-0db532c4230b.png)

Best regards,

  Guenther

**Comment by proCoderDude** [comment]
Hi Guenthler,

Thank you very much. That was the problem. It works on my side as well after flipping. Thanks a million times.


Kind Regards
proCodeDude
