### ISSUE TITLE
Incorrect Code 93 decoding

### ISSUE THREAD

**Issue by gredler** [zxing/zxing#428]
I wanted to use the zxing readers to check the encoding of barcodes in [Okapi](https://github.com/woo-j/OkapiBarcode/).

However, I think I may have found a bug in zxing -- the following image, which encodes "()\*,{}~" using Code 93, decodes as "()\*,EGH" in zxing. My physical barcode scanner reads "()\*,{}~", as does Okapi.

![special-characters-with-ctrl-3](https://cloud.githubusercontent.com/assets/178883/8790571/34f50d54-2f1d-11e5-9f45-1fc13ac2e41c.png)

**Comment by srowen** [comment]
Yeah that's just a bug. I don't know why this escape sequence was never handled correctly. Fix coming shortly ...

**Comment by Danielvmccall79** [comment]
Daniel

**Comment by Danielvmccall79** [comment]
Daniel
On Jul 21, 2015 6:00 AM, "Sean Owen" <notifications@github.com> wrote:
>
> Yeah that's just a bug. I don't know why this escape sequence was never
handled correctly. Fix coming shortly ...
