### ISSUE TITLE
Null Dereference Potential

### ISSUE THREAD

**Issue by spacecoder** [zxing/zxing#430]
Hello,
Our security team has identified potential security issues:

ZXAztecReader.m:(Line 71)
ZXAztecReader.m:(Line 65)

Impact:
Most null pointer issues result in general software reliability problems, but if an attacker can intentionally trigger a null pointer dereference, the attacker might be able to use the resulting exception to bypass security logic or to cause the application to reveal debugging information that will be valuable in planning subsequent attacks.

Recommendation:
Implement careful checks before dereferencing objects that might be null. When possible, abstract null checks into wrappers around code that manipulates resources to ensure that they are applied in all cases and to minimize the places where mistakes can occur.

**Comment by srowen** [comment]
Also not in this project
