### ISSUE TITLE
Missing checks against null

### ISSUE THREAD

**Issue by spacecoder** [zxing/zxing#431]
Hello,
Our security team has identified potential security concerns where null checks are not being performed:

/common/reedsolomon/ZXGenericGF.m:(Line 41)
common/reedsolomon/ZXGenericGF.m:(Line 40)
common/ZXHybridBinarizer.m:(Line 59)
common/ZXHybridBinarizer.m:(Line 150)
common/ZXHybridBinarizer.m:(Line 152)
pdf417/decoder/ec/ZXModulusGF.m:(Line 46)
pdf417/decoder/ec/ZXModulusGF.m:(Line 47)
core/ZXPlanarYUVLuminanceSource.m:(Line 114)

Impact:
This may lead to a memory crash enabling attackers to gain access
Recommendation:

If a function can return an error code or any other evidence of its success or failure, always check for the error condition, even if there is no obvious way for it to occur. In addition to preventing security errors, many initially mysterious bugs have eventually led back to a failed system call with an ignored return value.

**Comment by srowen** [comment]
This code is not from this project
