### ISSUE TITLE
Is there a JavaScript port planned?

### ISSUE THREAD

**Issue by SunboX** [zxing/zxing#433]
With pure HTML phones becoming more popular, I searched for a JavaScript port of ZXing. I could find this one here https://github.com/wojciechszela/zxingjs but it seems abandoned.

Is there a official port to JavaScript planned?

**Comment by srowen** [comment]
No, nothing is planned in fact. There's no new development in this project, just a little maintenance. I wouldn't be surprised if someone out there tried a port.

**Comment by SunboX** [comment]
Thanks for the quick info! That's sad, ZXing is really great and there's no real open source alternitive to it.
Maybe it's time for me to look into the abandoned one. Thanks! :)

**Comment by jbialobr** [comment]
I compiled ZXing to JavaScript using GWT compiler and exposed a minimal api to be able to scan qr codes.
Here is the project https://github.com/jbialobr/JsQRScanner
