### ISSUE TITLE
QR code not recognized

### ISSUE THREAD

**Issue by MeWiz** [zxing/zxing#435]
http://zxing.org does not detect any barcode in the attached image. Correctly read by other libraries such as the one used at http://online-barcode-reader.inliteresearch.com/default.aspx

![epqr](https://cloud.githubusercontent.com/assets/13549330/8949757/7c4e1376-3585-11e5-8f5f-d61ad1f40c94.png)

**Comment by srowen** [comment]
I suspect it's because of the corruption in the printing. Unless you have a PR though, I'd close this
