### ISSUE TITLE
Phone low-CPU optimisation

### ISSUE THREAD

**Issue by Dogm** [zxing/zxing#437]
Hi, 

It allow use ZXing on low cost phones (low cpu) with 8..12+ Mpx camera..

Problem:
Preview picture in phones with good camera is too large for fast cpu decode... 
Decoding barcode in this phones not work correctly (cpu too slow for decode large preview).

Optimisation:
File: .\src\com\google\zxing\client\android\camera\CameraConfigurationUtils.java
Change set:
--- source line: 348 ---
      Camera.Size largestPreview = supportedPreviewSizes.get(0);
--- optimized line: 348 ---
      Camera.Size largestPreview = supportedPreviewSizes.get(supportedPreviewSizes.size()-1);
--- end ---

This can be done with config in preferences or activity option...
without this - decoding is not work on Huawei/Siemens/Htc/.. mobile devices (Android 4.4+)...

Can you do this low-cpu optimization?

**Comment by srowen** [comment]
This isn't an appropriate change to make in general, no. The preview size is chosen to balance accuracy and speed. However, you can make your own build with whatever changes you like.

**Comment by Dogm** [comment]
8) You mean no matter about do not work decoding on huge amount of devices?

**Comment by srowen** [comment]
I think you're referring to some very limited phones? the app works fine on any mainstream Android phone from the last ~5 years, even low-end phones. So, "no"?

**Comment by Dogm** [comment]
On my work it is necessary to face cheap phones with the good camera...

I already use own build with this optimisation. Just think about nessesary to implement this for support more phones for mobile decoding barcode ...

p/s i use this logic in mobile application of one transport company for courier tracking and processing delivery...
