### ISSUE TITLE
NoClassDefFoundError: com.google.zxing.ResultMetadataType

### ISSUE THREAD

**Issue by kienntk** [zxing/zxing#438]
Firstly, Thank you very much for a great support application.
I am developing an application to scan barcode using ZXing on Android with core-2.2.jar but I got the error:

NoClassDefFoundError at:
08-06 14:23:49.084: E/AndroidRuntime(31626): FATAL EXCEPTION: main
08-06 14:23:49.084: E/AndroidRuntime(31626): Process: com.foxconn.cnsbg.it.barcodescanner, PID: 31626
08-06 14:23:49.084: E/AndroidRuntime(31626): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/zxing/ResultMetadataType;
08-06 14:23:49.084: E/AndroidRuntime(31626): 	at com.google.zxing.client.android.CaptureActivity.<clinit>(CaptureActivity.java:93)

I don't know why this error occur. ResultMetadataType had found :(

**Comment by srowen** [comment]
You didn't put the jar in your project. This is a basic Android question and not suitable here.

**Comment by kienntk** [comment]
I had put the jar file into libs folder but it not work. Then I added jar file as external library but still not working.
