### ISSUE TITLE
why integrator.initiateScan(); causing the current activity to go landscape

### ISSUE THREAD

**Issue by k0shk0sh** [zxing/zxing#440]
hello there, i'm having an issue with the library,  by calling this intent 
``
 IntentIntegrator integrator = new IntentIntegrator(Barcode.this);
            integrator.setPrompt("Scan a barcode");
            integrator.setResultDisplayDuration(0);
            integrator.initiateScan();
``
it changes my current activity to landscape which causing me this issue as mentioned in this thread at stackoverflow http://stackoverflow.com/questions/31884809/gridlayoutmanager-spansizelookup-bug 
could you please have a look and suggest me some solution? as workaround i did is, i created an activity that handles the intent and retrieve it back, this activity has a delay of one second to trigger the intent as if i didn't do that, i will get the exception as mentioned in the thread.  this only happens with this library i'm having my own custom camera which goes landscape and my current activity doesn't throw the exception that it threw whenever i open your default intent.

**Comment by srowen** [comment]
This isn't an issue report; you can ask on the mailing list. The app is always landscape -- is that what you're asking?

**Comment by k0shk0sh** [comment]
it is an issue if you had ask me, my question wasn't ( if the app is always landscape ) my question why does calling `initiateScan` changes the current activity orientation ?
