### ISSUE TITLE
GS1 DataBar Limited

### ISSUE THREAD

**Issue by chatakun** [zxing/zxing#442]
Dear Sir, 

I am who are developing an individual.

This time, it has decided to create a drug management software in the event of a disaster in the smartphone.

Bar code of Japan of medicine GS1-128 and GS1 DataBar Limited (CC-A) has been mainly used.

I am who are developing an individual.

This time, it has decided to create a drug management software in the event of a disaster in the smartphone.

Bar code of Japan of medicine GS1-128 and GS1 DataBar Limited (CC-A) has been mainly used.

GS1-128 in zxing, and I was able to read the GS1 DataBar standards, but it was not possible to read the Limited.

This request is for the extent of the cost to purchase a paid library in the trial version does not come out, is very grateful, if possible implementation in zxing.
By all means Could you consider the correspondence of Limited?

Very truly yours,

**Comment by srowen** [comment]
There is no commercial version of this library, and no further development is occurring here.

**Comment by chatakun** [comment]
ご返答ありがとうございます。

残念ですが、何とか道を探してみます。

ありがとうございました。
