### ISSUE TITLE
attribute name maxWidth with android 

### ISSUE THREAD

**Issue by k0shk0sh** [zxing/zxing#445]
could you please modify the attribute name for the maxWidth because it conflict with the new android support libraries ```com.android.support:preference-(v7,v14):23.0.0``` we can't use them unless if this attr is modified in zxing.

**Comment by srowen** [comment]
Not sure what this is referring to.

**Comment by k0shk0sh** [comment]
```
K:\workspace\newSalesMobility\app\build\intermediates\exploded-aar\com.journeyapps\zxing-android-legacy\2.3.0\res\values\values.xml
Error:(2) Attribute "maxWidth" has already been defined
Error:Execution failed for task ':app:processSalesMobilityTestDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'K:\android-sdk\build-tools\23.0.0\aapt.exe'' finished with non-zero exit value 1
```

**Comment by srowen** [comment]
This is an error from your app, not this project

**Comment by k0shk0sh** [comment]
in fact there is not such thing in my attrs having the same name, i have investigated more in the zxing source and found out that it does not have any attr at all, i guess its android bug after all. sorry for inconvenience .
