### ISSUE TITLE
Odd barcode layout...Unable to locate UPC in lower left corner. 

### ISSUE THREAD

**Issue by PokerPro123** [zxing/zxing#447]
![sample2](https://cloud.githubusercontent.com/assets/13951130/9451133/c2ff9952-4a7a-11e5-86b1-2d8403352f3a.jpg)

See image.
Any idea how I would calculate the bar code area (x, y, width, and height) for the barcode in the lower right corner?

**Comment by srowen** [comment]
Not sure what this is asking ... detecting the tiny barcode will fail because of the large barcode, so you want to crop the image if you already know where the tiny barcode is.
