### ISSUE TITLE
QR Decoder Not always working. When it does, it crashes with ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by candyss9185** [zxing/zxing#448]
Hi, I am working on a project where I need to stream the preview of the camera of Moverio glasses while being able to detect QR codes. I am using libstreaming to take care of the streaming and trying to decode the preview frames using zxing. However, I am running into 2 problems:
1. The QR code is sometimes recognized and sometimes not
2. When it does recognize the code, the application crashes with an ArrayIndexOutOfBounds when trying to extract the pure bits
java.lang.ArrayIndexOutOfBoundsException: length=9600; index=9600
            at com.google.zxing.common.BitMatrix.get(BitMatrix.java:131)
            at com.google.zxing.qrcode.QRCodeReader.extractPureBits(QRCodeReader.java:187)
            at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:73)
            at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
            at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:69)
            at net.majorkernelpanic.streaming.video.VideoStream.decode(VideoStream.java:1043)
            at net.majorkernelpanic.streaming.video.VideoStream.access$000(VideoStream.java:80)
            at net.majorkernelpanic.streaming.video.VideoStream$2.onPreviewFrame(VideoStream.java:449)

I am using a frame size of width 640 and height 480 and the following code in onPreviewFrame:
private void decode(byte[] data) {
        Result rawResult = null;

        int subtendedWidth = previewWidth / ZOOM;
        int subtendedHeight = previewHeight / ZOOM;
        int excessWidth = previewWidth - subtendedWidth;
        int excessHeight = previewHeight - subtendedHeight;

        PlanarYUVLuminanceSource source =
                new PlanarYUVLuminanceSource(data,
                        previewWidth, previewHeight,
                        excessWidth / 2, excessHeight / 2,
                        subtendedWidth, subtendedHeight,
                        false);
        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
        try {
            rawResult = new MultiFormatReader().decode(bitmap, hints);
        } catch (ReaderException re) {
            // continue
        }
    }

Do you know the recognition work doesn't everytime and what could be causing the exception?

**Comment by srowen** [comment]
Many frames will not decode; this is normal. The point is that one will, quickly. You haven't provided any images, so I don't think it's possible to say more about why one image does or doesn't decode.

I'm not sure what you mean that it succeeds in decoding, but throws an exception. The best thing would be to provide an image that causes the exception using code in `master` now. However it seems from this setup that it could be your app code. The AIOOBE at 9600 is not consistent with a 640x480 image. It sounds like the image size you are passing doesn't match the data size underneath?

If you can provide a reproduction using the project code we can reopen this.

**Comment by candyss9185** [comment]
Hi! Thanks for your feedback. 
The QR code I am using is this one (printed out on paper): https://upload.wikimedia.org/wikipedia/commons/9/9b/Wikipedia_mobile_en.svg

What I meant by success is that the QR code is actually recognized but it is not being decoded properly. I will check the size of the image being passed and get back to you if I need more help. Thanks.

**Comment by srowen** [comment]
The barcode image decodes fine for me. It says "http://en.m.wikipedia.org" and does so every time. (Note you may have to convert it from SVG to something Java libs can read, like PNG)

**Comment by candyss9185** [comment]
Hi! After hours of trial, I realized that the problem was with the frame. Since it is a frame returned while the streaming is going on, it is encoded in H264 and I guess that the library cannot process it. Is there a way to extract the QR code from a H.264 frame?

**Comment by srowen** [comment]
Do you mean that the bytes you're passing as an image are actually H.264 encodings of a frame? yeah that wouldn't work. It's intended to be Planar YUV -- really, that means that the first height x width pixels need to be luminance values. The rest of the array is ignored (U, V chroma planes)

**Comment by candyss9185** [comment]
Thanks for your help!
