### ISSUE TITLE
PDF417 decode error

### ISSUE THREAD

**Issue by gredler** [zxing/zxing#449]
The following PDF417 bar code, which was generated using [Okapi](https://github.com/woo-j/OkapiBarcode/) and encodes the text *"This is just a test."* cannot be decoded by ZXing:

![normal-basic-6-rows-6-columns](https://cloud.githubusercontent.com/assets/178883/9533715/ef3d587e-4ce1-11e5-94bb-98def8edb995.png)

It decodes without any issues with a hardware bar code scanner.

I would attach a stack trace, but it throws a `FormatException` without a stack trace (at `DetectionResultRowIndicatorColumn#125`, in the `getRowHeights()` method).

**Comment by graug** [comment]
The metadata cointained in the generated barcode does not match the actual barcode. According to the barcode metadata, the barcode is supposed to consist of 4 rows, but it actually consists of 6 rows. The last two rows of the barcode contain garbage. If I ignore the last two rows, the code decodes properly as "This is just a test.". I suggest you report this problem to Okapi.
If you cannot fix Okapi right away, you can apply the following patch to xing, which will cause it to ignore the additional garbage rows.

diff --git a/core/src/main/java/com/google/zxing/pdf417/decoder/DetectionResultRowIndicatorColumn.java b/core/src/main/java/com/google/zxing/pdf417/decoder/DetectionResultRowIndicatorColumn.java
index b9484c0..750aeac 100644
--- a/core/src/main/java/com/google/zxing/pdf417/decoder/DetectionResultRowIndicatorColumn.java
+++ b/core/src/main/java/com/google/zxing/pdf417/decoder/DetectionResultRowIndicatorColumn.java
@@ -122,7 +122,8 @@
       if (codeword != null) {
         int rowNumber = codeword.getRowNumber();
         if (rowNumber >= result.length) {
-          throw FormatException.getFormatInstance();
+        	continue;
+          //throw FormatException.getFormatInstance();
         }
         result[rowNumber]++;
       } // else throw exception?
diff --git a/core/src/main/java/com/google/zxing/pdf417/decoder/PDF417ScanningDecoder.java b/core/src/main/java/com/google/zxing/pdf417/decoder/PDF417ScanningDecoder.java
index 56ead37..50c78c1 100644
--- a/core/src/main/java/com/google/zxing/pdf417/decoder/PDF417ScanningDecoder.java
+++ b/core/src/main/java/com/google/zxing/pdf417/decoder/PDF417ScanningDecoder.java
@@ -343,7 +343,8 @@
             int rowNumber = codeword.getRowNumber();
             if (rowNumber >= 0) {
               if (rowNumber >= barcodeMatrix.length) {
-                throw FormatException.getFormatInstance();
+            	  continue;
+//                throw FormatException.getFormatInstance();
               }
               barcodeMatrix[rowNumber][column].setValue(codeword.getValue());
             }

**Comment by srowen** [comment]
Nice analysis, thanks @graug . If it's a problem in the generator, then yes that's the place to take it up, unless someone can argue that the decoder is supposed to handle this situation. In the meantime yes that's a decent hack you could apply.

**Comment by graug** [comment]
Thx @srowen . In this case the problem is the generator, but it could potentially happen (though very unlikely) that the zxing decoder erroneously detects additional rows after the actual barcode rows. I don't have a PDF417 spec, so I don't know how the decoder is supposed to handle this case. If we abide by the general rules for communication, we should be very strict in what we generate, but lenient in what we accept. So I guess we should probably accept the presented barcode and decode it, despite the garbage at the end. I've created a pull request.
