### ISSUE TITLE
Invalid X cord result points

### ISSUE THREAD

**Issue by PokerPro123** [zxing/zxing#450]
I've attached the image and a screenshot of the property values of the ResultPoints class. 

Why do I have result points which extend way beyond the actual width of this UPC bar code? 

![invalidresultpoints](https://cloud.githubusercontent.com/assets/13951130/9582919/37f1c81a-4fd6-11e5-8d10-391f7470c598.jpg)
![10000148-b](https://cloud.githubusercontent.com/assets/13951130/9582923/3c1b2c74-4fd6-11e5-8b15-8c93fed678b7.jpg)

**Comment by srowen** [comment]
This isn't Java code right? I think you're looking at a port that is not part of this project.

**Comment by PokerPro123** [comment]
You are correct sir.
