### ISSUE TITLE
Support scanning QR codes from photo

### ISSUE THREAD

**Issue by jas4711** [zxing/zxing#452]
I have some QR codes in photos that I would like to scan.  What do you think about a feature to select an image from the gallery to scan from?

**Comment by srowen** [comment]
Yes, it exists in https://play.google.com/store/apps/details?id=com.srowen.bs.android and I'd take a look at a pull request, but there is no more work being done on this project otherwise.

**Comment by maverick74** [comment]
@srowen  Would like this as well. 
Any chance to have this feature in the near future?

**Comment by garywill** [comment]
+1

and please add one more feature: using share button in gallery to send a gallery photo to scanner

**Comment by Bang631** [comment]
tai sao 1 dia chi bitcoin QR duoc long ghep do hoa cung ma hoa,vay tai sao no lai khong xac nhan thanh toan.sao chung ta khong  de cho no barcodes de xac nhan voi nhau va giao dich cung nhanh hon

**Comment by chungyau97** [comment]
@garywill @srowen is this added??
