### ISSUE TITLE
VCARD QR-Code can't hand over addresses to android contacts app properly

### ISSUE THREAD

**Issue by ToM-MaS** [zxing/zxing#464]
What is the reason that Barcode Scanner/+ (PLUS) can't hand over VCARD QR-Code addresses to the android contacts app properly?
The street field always contains all of address data (street, city, state,postal code and country seperated by line breaks).  The respective field for city, country etc. remain empty. 

Direct import of a vcard file by the contacts app works properly as expected.

**Comment by srowen** [comment]
IIRC it is because the intent API doesn't support these fields individually, or did not. This is already mentioned in another open issue. There is no development on this project now but I can look at PRs.
