### ISSUE TITLE
VCARD QR-Code can't hand over UTF-8 and QUOTED-PRINTABLE encoded addresses to android contacts app properly

### ISSUE THREAD

**Issue by ToM-MaS** [zxing/zxing#465]
Barcode Scanner/+ (PLUS) can't hand over UTF-8 and QUOTED-PRINTABLE encoded VCARD QR-Code addresses to the android contacts app properly.

Barcode Scanner/+ (PLUS) recognizes the address data correctly (The preview of the contact shows the correct decoded data.)

But the address fields of the android contacts app remain empty if I try to import it.

Here an example:

ADR;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;;=4B=6F=6D=6D=75=6E=69=6B=61=74=69=6F=6E=73=77=65=67=20=35=0A=4E=6F=72=
=64=68=61=75=73=65=6E=2C=20=54=68=C3=BC=72=69=6E=67=65=6E=20=39=39=37=
=33=34=0A=44=65=75=74=73=63=68=6C=61=6E=64;;;;

**Comment by srowen** [comment]
Is this just the same issue you already opened - that the address fields aren't populated ? I dont see a problem with quoted printable or don't understand what problem there is.

**Comment by ToM-MaS** [comment]
OK, you are right. Barcode Scanner/+ is not able to hand over multiple addresses for WORK and/or HOME - that seems to be the problem. It recognizes them in the preview, but can't hand them over to the contacts app. 

UTF-8 and QUOTED-PRINTABLE encoded addresses are working fine. (In my test example there was a second address which was encoded - the first wasn't encoded. And just the first - not encoded address seemed to work, but this is a general problem with multiple addresses.)

**Comment by srowen** [comment]
As I say, I think it's because the Intent supported by the Contacts app doesn't support it. At least, this was true in the past. This is covered by https://github.com/zxing/zxing/issues/25
