### ISSUE TITLE
datamatrix raise checksum error even when no errors are found

### ISSUE THREAD

**Issue by eppesuig** [zxing/zxing#470]
Hello,
I am facing a problem when zxing decode for datamatrix gives exception ChecksumException based on a failure of method ReedSolomonDecoder.findErrorLocations() that fails with exception ReedSolomonException.
The problem is that findErrorLocations() does not find any error since its error counter (the "e" variable) is kept at zero because errorLocator.evaluateAt(i) is never zero. This is of course strange since numErrors is not zero, and I don't know what is the meaning of this case.

I would like to know if the ReedSolomonException should *not* be thrown when e==0.

Thanks,
Giuseppe

**Comment by srowen** [comment]
Entirely possible there's a problem in there, though the tests cover it pretty well. Can you break out a test for this case somehow -- yes it should not be possible to find no zeroes for a non-zero polynomial. I'm wondering exactly what the locator poly was here.

**Comment by eppesuig** [comment]
I do have a PDF with a datamatrix version 6 that expose the problem. When I read it using the android app the text is correctly read, but if I read it via a java class that directly calls com.google.zxing.datamatrix.DataMatrixReader it fails as said before.

I tried to upload the file via github issue window, but it fails to accept it, so I've put it here: http://centrum.lixper.it/~giuseppe/zxing/zxing-datamatrix-dim6-zeroerrors.pdf .

**Comment by srowen** [comment]
I tried this one and the problem is that it is read almost correctly but not quite. The result is that it begins parsing but fails for 'too many errors'. That much is normally and actually I think the error polynomial isn't going to have all expected roots when there is too much corruption. 

Obviously reading everything is better but the RS logic here seems working as intended.

**Comment by eppesuig** [comment]
I understand the problem might be there, so I have a different question: why the android app correctly read it? Does it act internally different?

**Comment by srowen** [comment]
Because the Android app is reading a different image -- an image of the image. The barcode itself decodes just fine. the particular pixels in the image in the PDF fail to decode, just barely.
