### ISSUE TITLE
Use front camera to scan

### ISSUE THREAD

**Issue by wb9vxy** [zxing/zxing#473]
It would be nice if the scanner could be set to use the front camera rather than the back.

Tnx,

T3

**Comment by srowen** [comment]
It already does if that is the only camera. Using the front camera is a poor experience, so isn't otherwise available. The BS+ app lets you change it if you really want.

**Comment by wb9vxy** [comment]
Tnx
T3


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------
