### ISSUE TITLE
Scanning only when phone is 12 inches or farther away

### ISSUE THREAD

**Issue by Garguy** [zxing/zxing#474]
With my Note 4 and S6 Edge+ I can only get the scanner to scan a barcode at 12 inches or farther away. With a hold htc I still have I can do it at a normal distance. I am not sure why I have to scan from so far away with newer phones. Is there something in this library that sets the resolution or could it be a camera focus thing within the library?

**Comment by srowen** [comment]
Questions should go to ... https://groups.google.com/forum/#!forum/zxing

It's probably because your camera won't focus when it's too close.
