### ISSUE TITLE
How to recognize a leading Databar FNC1-character? 

### ISSUE THREAD

**Issue by saqada** [zxing/zxing#475]
Helllo,

The specification says that a leading FNC1-character is used to identify GS1 barcodes, and should be decoded as "]d2" (GS1 DataMatrix), "]C1" (GS1-128), "]e0" (GS1 DataBar Omnidirectional) or "]Q3" (GS1 QR Code). Any other occurrences of FNC1-characters should be decoded as ASCII GS-characters (byte value 29).  I managed to get FNC1-characters for DataMatrix, QR Code and GS1-128, but cannot do the same for DataBar because I don't have idea where to look at. 
Please, help me to understand how I can manage to get this leading FNC1-character "]e0"  for DataBar. Thanks.

Regards,
Ayaz

**Comment by srowen** [comment]
What format is "DataBar"? as I understand it's a label on top of other formats. Could you ask questions at https://groups.google.com/forum/#!forum/zxing instead?
