### ISSUE TITLE
Support for extended ISSN barcodes

### ISSUE THREAD

**Issue by wzol** [zxing/zxing#478]
Hello, I'm not sure if this is an issue on my side, or a feature request.

Would it be possible for you to support extended ISSN barcodes? It is an EAN-13 code with extra digits used for added information like issue number: https://en.wikipedia.org/wiki/International_Standard_Serial_Number.

Example http://www.free-barcode-generator.net/issn/ - and try example 9772434561006:12001. As I tried the extended characters aren't recognized only the main EAN-13 part. 

Is it an issue on my side?

Thank you in advance.

**Comment by srowen** [comment]
It already reads both the EAN 13 and the extension. It appears to be the same encoding as the "+2" or "+5" extension for UPC/EAN used elsewhere. Note that the extension is not considered part of the barcode and is returned separately as metadata. It's also not going to fail the decode if it sees the EAN but can't read the extension.
