### ISSUE TITLE
Framing image is wider than real objects

### ISSUE THREAD

**Issue by cybuch** [zxing/zxing#483]
Using Nexus 7 (it's fine for other devices) the image drawn by Barcode Scanner ('android' project) are significantly wider than real objects.

**Comment by srowen** [comment]
What does this mean? more importantly do you have a change to propose?

**Comment by cybuch** [comment]
Here you got link [0] to two pictures - first using barcode scanner and second using built-in camera app. Second image is correct, that glass is at it is. However in barcode scanner it's much wider than it should be. Honestly I've tried to look for solution, but couldn't find it. If you'll look on camera app - it's cropped to some resolution, so probably that's why it's not widening the image, I guess we shall do the same, but where and on what conditions?

[0] http://imgur.com/a/aEwUY

**Comment by srowen** [comment]
That's normal in that the app will choose a suitable preview size that best matches the aspect ratio of the screen. But, devices don't always provide a lot of choices. In this case it looks like the preview size with sufficient resolution doesn't match the aspect ratio so it renders as stretched. It's just a cosmetic effect. You can see the logic for picking the preview size in the project here. I'm open to suggestions about changing it, but it's generally robust across devices at this stage.

**Comment by cybuch** [comment]
Some debug information [0].  According to SO answer [1] it would be the best to get information about screen aspect ratio and add some margins? Like in the built-in camera app. I'm new to android and won't stay here too long, but I try to decode aztec codes using your library, however as you know getting the aztec a little wider makes it more difficult to decode.

[0] http://pastebin.com/bkGmeQMW
[1] http://stackoverflow.com/questions/21668394/camera-in-android-how-to-get-best-size-preview-size-picture-size-view-size

**Comment by srowen** [comment]
It already queries the aspect ratio and preview sizes that are available. Ideally devices provide a preview size that matches the screen size; almost all do. I don't want to make a special UI for those that don't. As I say, the stretching has no effect on scanning. It is purely cosmetic. Of course, what the camera sees is not stretched.

**Comment by cybuch** [comment]
How to get it then? I'm trying to decode aztec via preprocessing the image in decode() method of DecodeHandler. I get the picture from "activity.getCameraManager().buildLuminanceSource(data, width, height);" of the decode method and I pass it to my preprocessor which then returns preprocessed aztec (at least it should return it) and then again to your decoder. However it is stretched as well. How shall I get correct image to preprocess before decoding then?

**Comment by srowen** [comment]
The preview frame comes from the camera callback. It is not stretched. Android also flings it onto the preview surface but that's separate, and not something the app does. I'm not sure how your app works since it sounds like you're modifying the open source app, but the OSS app does as I say. For example, if you're reading off the preview surface, that's wrong (and unnecessary)

**Comment by cybuch** [comment]
Here's exactly what I do:
from the decode method of: https://github.com/zxing/zxing/blob/master/android/src/com/google/zxing/client/android/DecodeHandler.java I pass the source to my preprocessor and return back to the decoder (reader). Howver image got from variable 'source' (78th line) is stretched.
