### ISSUE TITLE
Camera image flipped on both axis

### ISSUE THREAD

**Issue by prenetic** [zxing/zxing#488]
Phone: Nexus 5X
OS: Android 6.0 - Marshmallow (stock build)
Behavior: Camera image is flipped on both axis within the app.
Repro: Installed from play store, opened app to scan code.
Attempted workaround: Cleared data/cache from app, the issue persisted.

**Comment by thederputy** [comment]
+1 for repro, same steps

**Comment by srowen** [comment]
Duplicate, have a look at existing closed issues. the 5x is weird.
