### ISSUE TITLE
Version 4.7.4 breaks ability to select camera

### ISSUE THREAD

**Issue by slepmog** [zxing/zxing#489]
The ability to select camera when calling ZXing via intent: https://github.com/zxing/zxing/pull/135
Version 4.7.4 brakes that.

Now when you request a non-default camera in the intent (e.g. camera 1), the scanning intent opens and immediately shows an error dialog:

> **Barcode Scanner**  
> Sorry, the Android camera encountered a problem. You may need to restart the device.
> **OK**

The following appears in the logcat:

<pre>D/SecCameraHardware( 1937): LSIHAL int android::HAL_getCameraInfo(int, camera_info*)

W/com.google.zxing.client.android.camera.open.OpenCameraInterface(23318): Requested camera does not exist: 1

W/CaptureActivity(23318): java.io.IOException: Camera.open() failed to return object from driver
W/CaptureActivity(23318): 	at com.google.zxing.client.android.camera.CameraManager.openDriver(CameraManager.java:82)
W/CaptureActivity(23318): 	at com.google.zxing.client.android.CaptureActivity.initCamera(CaptureActivity.java:723)
W/CaptureActivity(23318): 	at com.google.zxing.client.android.CaptureActivity.surfaceCreated(CaptureActivity.java:423)
W/CaptureActivity(23318): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:610)
W/CaptureActivity(23318): 	at android.view.SurfaceView.access$000(SurfaceView.java:93)
W/CaptureActivity(23318): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:182)
W/CaptureActivity(23318): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:864)
W/CaptureActivity(23318): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2142)
W/CaptureActivity(23318): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
W/CaptureActivity(23318): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
W/CaptureActivity(23318): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
W/CaptureActivity(23318): 	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
W/CaptureActivity(23318): 	at android.view.Choreographer.doFrame(Choreographer.java:561)
W/CaptureActivity(23318): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
W/CaptureActivity(23318): 	at android.os.Handler.handleCallback(Handler.java:730)
W/CaptureActivity(23318): 	at android.os.Handler.dispatchMessage(Handler.java:92)
W/CaptureActivity(23318): 	at android.os.Looper.loop(Looper.java:176)
W/CaptureActivity(23318): 	at android.app.ActivityThread.main(ActivityThread.java:5419)
W/CaptureActivity(23318): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/CaptureActivity(23318): 	at java.lang.reflect.Method.invoke(Method.java:525)
W/CaptureActivity(23318): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
W/CaptureActivity(23318): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
W/CaptureActivity(23318): 	at dalvik.system.NativeStart.main(Native Method)</pre>

Works fine with v4.7.3.

**Comment by srowen** [comment]
Hm, yeah this logic changed since it now accommodates requests for a specific camera as well as just a front/back camera. I think the problem is that it will require a rear-facing camera even when one is explicitly requested, and that one is front-facing. Really it should only prefer rear-facing if none was specified. Camera 1 is front-facing right?

**Comment by slepmog** [comment]
Yes, camera 1 is front-facing.

We're happy to make changes in our app if now it's a matter of asking for "a front camera" as opposed to "camera 1."

**Comment by srowen** [comment]
That's not exposed at the moment; this is really from splicing in code that supports this from another app. Try the latest commit I just pushed if you can to see if it addresses this.

**Comment by slepmog** [comment]
We don't do Java development, so we don't have the tools at the moment.  
I will see if we can quickly set up a Maven installation to compile it.

**Comment by slepmog** [comment]
Yes, seems to work fine with compiled android-4.7.4-aligned.apk.

**Comment by srowen** [comment]
Nice one. Let me wait a short while to see if any other issues come in before making 4.7.5
