### ISSUE TITLE
Launch from Lock Screen

### ISSUE THREAD

**Issue by christantoan** [zxing/zxing#491]
When launched from lock screen, the app starts in portrait mode and the resulting scans screenshot looks weird (stretched or something)

**Comment by srowen** [comment]
The app is landscape-only. If Android treats it as portrait, it's an Android error or else something that isn't supported.

**Comment by christantoan** [comment]
But it didn't happen before last update. It never launched as portrait before

**Comment by srowen** [comment]
It can handle landscape and reverse-landscape rotation better, but Android should never put it into portrait as it declares that it does not support portrait. If it is, it's an Android problem.
