### ISSUE TITLE
some code39 barcodes with check digit don't work

### ISSUE THREAD

**Issue by Spitfire90** [zxing/zxing#496]
The library is not able to scan some code39 barcodes with check digit.
I did the test with different barcodes.
- when the barcode ends with - or . checkdigit, it works
- when the barcode ends with $, %, + checkdigit, it doesn't work.

I think the problem is related to the calculation of the check digit (total variable) where we use the ALPHABET_STRING tab which contains the * (star) character whereas the specification doesn't include this star character as part of the possible check digit (https://en.wikipedia.org/wiki/Code_39)

**Comment by srowen** [comment]
Agree, good catch. PR coming ...

**Comment by Spitfire90** [comment]
Do you already know when the 3.2.2 milestone will be released ?
I'm new on GitHub, not familiar with the process...

**Comment by srowen** [comment]
@Spitfire90 there's no plan to release 3.2.2... I usually wait for a handful of bugs that need a fix, or ~6 months.
