### ISSUE TITLE
Barcodescanner scans different format and number

### ISSUE THREAD

**Issue by Matevos** [zxing/zxing#497]
Scanning in Zxing sometimes I have different format and number. It happens when I am not moving my camera away from barcode it scans multiples time and then I got different result. What's the problem here?

**Comment by srowen** [comment]
No problem, it's just a false positive read. You can disable formats you don't want to scan for to help this.

**Comment by Matevos** [comment]
Thanks for your help I only enabled EAN-13 and same result. Why this is happening?

**Comment by srowen** [comment]
I don't know. What result do you see? You don't describe the problem

**Comment by Matevos** [comment]
![img_20151112_104011](https://cloud.githubusercontent.com/assets/5268958/11112187/a32b4abe-8921-11e5-826d-1aaff3ae5438.jpg)

I scanned this barcode 10 times and sometimes I see wrong result i.e (981409130867) but original is 8991389730867. I only enabled EAN-13 for the test.

**Comment by srowen** [comment]
It scans as 8991389730867 --  http://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F5268958%2F11112187%2Fa32b4abe-8921-11e5-826d-1aaff3ae5438.jpg  It's possible, though rare, that you can get a misread for EAN.
