### ISSUE TITLE
Unable to decode the following PDF417 Barcode Reader

### ISSUE THREAD

**Issue by vrvmadan** [zxing/zxing#501]
I tried to decode the below PDF417 barcode Image, But I am unable to decode it. I know the quality of the Image is not good, is there any work around to decode the Image. How can i Improve the
 Hybrid binarizer logic to detect the low quality  Barcode Images also. could you please suggest me the way to detect the low quality barcode images also.
![img_20151027_172949914](https://cloud.githubusercontent.com/assets/6228468/11267885/e0646192-8ed3-11e5-928c-7b442e5271aa.jpg)

**Comment by srowen** [comment]
Unless you've got a change to propose, I'll have to close this. THere's no general magic; better quality, different image might scan.
