### ISSUE TITLE
False error alert when generating QRCode on Android device without GooglePlayServices.

### ISSUE THREAD

**Issue by JimVanG** [zxing/zxing#502]
Pretty much all in the title, but..

When generating a QRCode on an Android device without GooglePlayServices an error alert pops up for a split second and then goes away. The error alert says "This app won't run without Google Play services, Which are missing from your phone." Though the app runs fine and the QRCode is successfully generated.

I understand why this may happen when attempting to scan a QRCode. Because, to my understanding (as I've only implemented generation, not scanning), it relies on Intents and the Google Play Store to open up a scanner app. But I don't see why this false alert pops up when generating a QRCode, because generation doesn't rely on any Google Play services, but maybe I'm overlooking something.

This isn't a huge bug, as most of the Android users have Google Play services on their device, and the QRCode appears to be successfully generated. Also, the alert is only on the screen for a split second. But it would be good if we could stop the false error alert from popping up all together.

Here's the error alert:
<img width="283" alt="screen shot 2015-11-18 at 11 52 30 am" src="https://cloud.githubusercontent.com/assets/3766002/11277121/b7f9575e-8eaa-11e5-9214-1f55d05ab214.png">

Here's the Log output:
`11-19 16:27:41.144 1189-1189/com.myApp.qrGeneration W/GooglePlayServicesUtil: Google Play Store is missing.`
`11-19 16:27:41.148 1189-1189/com.myApp.qrGeneration I/qrGenerationActivity: [ main ] No valid Google Play Services APK found.`

**Comment by srowen** [comment]
This app does not rely on Play to function. Android has a new built-in barcode service that does. However it is unrelated to this app.
