### ISSUE TITLE
Potential vulnerability to SQL injection

### ISSUE THREAD

**Issue by schferbe** [zxing/zxing#503]
I have this http://forum.xda-developers.com/xperia-j-e/development/rom-cyanogenmod-10-dual-sim-t2518451 version of cyanogenmod installed. I am using the up-to-date version of Barcode Scanner from f-droid which is probably 4.7.5.
I generated a QR code using wolframalpha (http://www.wolframalpha.com/input/?i=qr+code+for+%27%29%3B+DROP+TABLE+user%3B+--) with the text '); DROP TABLE user; --

I think the I set the error correction level to Q but I'm not sure. 

When I scanned the QR code everything was displayed as usual and nothing strange happened. When I tried to open a different app using the camera a message came up, that the camera could not be opened.

Then I tried to close the Barcode scanner but the view of the running apps kept disappearing. Then cm crashed and after reboot none of the SIMs were recognized. Some things still worked. Others didn't. Even after flashing cm again I can't charge my phone.

I'm not sure if this is caused by an SQL injection. ATM I'm not able or willing to try to reproduce.

**Comment by srowen** [comment]
Eh, but that's an example of an attempt to attack `wolframalpha.com`, not the QR code app. No app would interpret this content; there's no DB in the app to attack. Everything else you describe sounds like a CM problem. Right?

**Comment by schferbe** [comment]
I also think it's probably because of cm. Sadly that version doesn't seem to be maintained. 

Maybe it'd be a good idea to test the impact on normal Android or other versions of cm.
