### ISSUE TITLE
Help screen goes blank on screen orientation change 

### ISSUE THREAD

**Issue by vanillajonathan** [zxing/zxing#504]

**Comment by srowen** [comment]
I've seen that but never bothered to figure it out since its not important. I'd be open to a PR if you have the fix, but otherwise nothing will happen

**Comment by vanillajonathan** [comment]
Might have something to do with that `screenOrientation` is set, but I don't know.

https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml#L151

**Comment by srowen** [comment]
That should be fine, in the sense that there's no big reason to not let the help page be in landscape mode. Maybe it makes sense to always match the landscape implementation? I'd take a PR for that if there is support.

**Comment by Grzesik** [comment]
Hi, I have the same problem on Android.

**Comment by srowen** [comment]
@Grzesik do you have a suggestion? other than forcing this to landscape.
