### ISSUE TITLE
Barcode Scanner: Decoding of multiple iCal/ics whole-day VEVENTs fails for second and further events

### ISSUE THREAD

**Issue by Wikinaut** [zxing/zxing#513]
Hello, I generated a QR code from the following whole-data-events in ics format.
#### Bug
- The current Zxing Barcode Scanner on Android detects only the first event (20151012)
- but **fails to detect/decode the further events**.

```
BEGIN:VCALENDAR
PRODID:Leave Planner Version 201512041000
COMMENT:5 day/s exported on 20151204
VERSION:2.0
BEGIN:VEVENT
SUMMARY:XLEAVE
DTSTART;VALUE=DATE:20151012
END:VEVENT
BEGIN:VEVENT
SUMMARY:XLEAVE
DTSTART;VALUE=DATE:20151013
END:VEVENT
BEGIN:VEVENT
SUMMARY:XLEAVE
DTSTART;VALUE=DATE:20151014
END:VEVENT
BEGIN:VEVENT
SUMMARY:XLEAVE
DTSTART;VALUE=DATE:20151015
END:VEVENT
BEGIN:VEVENT
SUMMARY:XLEAVE
DTSTART;VALUE=DATE:20151016
END:VEVENT
END:VCALENDAR
```

here's the code to generate with your online web side:

https://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=BEGIN%3AVCALENDAR%0APRODID%3ALeave+Planner+Version+201512041000%0ACOMMENT%3A5+day%2Fs+exported+on+20151204%0AVERSION%3A2.0%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151012%0AEND%3AVEVENT%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151013%0AEND%3AVEVENT%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151014%0AEND%3AVEVENT%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151015%0AEND%3AVEVENT%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151016%0AEND%3AVEVENT%0AEND%3AVCALENDAR%0A

**Comment by srowen** [comment]
I don't know that this is a bug. Generally you'd put one event in a QR code. I don't know how a device would act on several at once. Still, could be reasonable to support parsing multiple events. I am not working on the project anymore but can look at a pull request

**Comment by Wikinaut** [comment]
@srowen so it's at least the correct place to notify about (alleged) bugs of the Zxing Barcode Scanner App, isn't it? I'll will try to build that, too, and perhaps I can find a way to add more than one event.

At least the syntax (of the ics file) is correct. So it should be possible to add more than one event. This may indeed be difficult with respect to the "receiving" app like calendar. Perhaps you can help...

thanks.

**Comment by srowen** [comment]
Yes, the right place. I'm sure it's syntactically correct and therefore makes some sense to parse it. After all it's not just phones that use the decoding logic. But I don't think it's possible to send multiple events in an Intent in Android, so would always have to use the first one.

**Comment by YMosheL** [comment]
can you please help me with [this](http://stackoverflow.com/q/36001673/4352178)

**Comment by Medusa500** [comment]
![Screenshot_20201111-134628](https://user-images.githubusercontent.com/73814541/98857473-b50eca00-2424-11eb-80cf-b82ccdd35ec0.png)

**Comment by Marley4665** [comment]
> Hello, I generated a QR code from the following whole-data-events in ics format.
> 
> #### Bug
> * The current Zxing Barcode Scanner on Android detects only the first event (20151012)
> * but **fails to detect/decode the further events**.
> 
> ```
> BEGIN:VCALENDAR
> PRODID:Leave Planner Version 201512041000
> COMMENT:5 day/s exported on 20151204
> VERSION:2.0
> BEGIN:VEVENT
> SUMMARY:XLEAVE
> DTSTART;VALUE=DATE:20151012
> END:VEVENT
> BEGIN:VEVENT
> SUMMARY:XLEAVE
> DTSTART;VALUE=DATE:20151013
> END:VEVENT
> BEGIN:VEVENT
> SUMMARY:XLEAVE
> DTSTART;VALUE=DATE:20151014
> END:VEVENT
> BEGIN:VEVENT
> SUMMARY:XLEAVE
> DTSTART;VALUE=DATE:20151015
> END:VEVENT
> BEGIN:VEVENT
> SUMMARY:XLEAVE
> DTSTART;VALUE=DATE:20151016
> END:VEVENT
> END:VCALENDAR
> ```
> 
> here's the code to generate with your online web side:
> 
> https://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=BEGIN%3AVCALENDAR%0APRODID%3ALeave+Planner+Version+201512041000%0ACOMMENT%3A5+day%2Fs+exported+on+20151204%0AVERSION%3A2.0%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151012%0AEND%3AVEVENT%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151013%0AEND%3AVEVENT%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151014%0AEND%3AVEVENT%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151015%0AEND%3AVEVENT%0ABEGIN%3AVEVENT%0ASUMMARY%3AXLEAVE%0ADTSTART%3BVALUE%3DDATE%3A20151016%0AEND%3AVEVENT%0AEND%3AVCALENDAR%0A

Delete
