### ISSUE TITLE
Scanning hidden Wifi network QRCode does not connect the device to the Wifi

### ISSUE THREAD

**Issue by sebma** [zxing/zxing#515]
Hi,

When I scan the QRCode containing the following string : 

WIFI:S:MyNetWork;T:WPA2;P:fsdofjddsfjlgmfdgds;H:true;

It does not connect the device to that wifi network.

Can you please fix this ?

Seb.

**Comment by srowen** [comment]
This really isn't enough info to go on, as I don't even know what your wi-fi network is like. If you have a pull request, reopen.

**Comment by sebma** [comment]
I'm using an old android 2.2 device using "Barcode Scanner" v4.3.2

What other info would you like to have ?
