### ISSUE TITLE
Cannot connect to hidden wifi network using qrcode scanned with "Barcode Scanner"

### ISSUE THREAD

**Issue by sebma** [zxing/zxing#516]
Hi,

I'm using an old android 2.2 device using "Barcode Scanner" v4.3.2 to connect to my hidden WPA2 wifi network.

When I scan the QRCode containing the following string (containing my network info.) :

WIFI:S:MyNetWork;T:WPA2;P:fsdofjddsfjlgmfdgds;H:true;

It does not connect my device to that network.

Do you need some other information ?

Seb.

**Comment by sebma** [comment]
Hi, 

It does not work either using  an Android 4.2.2 device using "Barcode Scanner" v4.7.3.

Seb.

**Comment by srowen** [comment]
@sebma do _not_ just open the same issue. As I say, this works in general. Unless you have detail, probably at the level of a pull request, no I can't do anything.

**Comment by sebma** [comment]
What information do you need precisely ?

**Comment by srowen** [comment]
You need to suggest a change to the code or at least identify the issue in it. WPA2 works fine in general as far as I know. There's no way to debug it from this info.

**Comment by sebma** [comment]
How can I get debug info from your application ?

**Comment by sebma** [comment]
Is there any log file produced by your application on the phone or or the SD card filesystem ?

**Comment by sebma** [comment]
Finally figured out why it didn't work:

I had forgotten another semicolon at the end of the wifi string to encode so my QRcode was wrong.

I am sorry to have wasted your precious time.

Your app is a great app, keep up the good work :)

Sebastien.
