### ISSUE TITLE
Email address with unsupported extension

### ISSUE THREAD

**Issue by Stefanp44** [zxing/zxing#517]
Hi,

While wanting to generate a QR Code using your tool (which is great by the way), I stumbled upon a problem : it said that my e-mail address was not valid since it uses an unsual extension (@perspectives.marketing) : is there any way to go around that ?

Thank you for your answer

**Comment by srowen** [comment]
You're right. For now you can work around this by encoding "Text" with content `mailto:you@perspectives.marketing`. That's all it does anyway.

If you're interested in fixing it, take a look at the regex in `Validators.java`, which is simplistic. I will look at it later anyway as it should be a simple clear fix.

**Comment by Stefanp44** [comment]
Thank you Sean for your prompt answer (that was actually really fast !). I'll use the workaround since I'm not proficient in java.
