### ISSUE TITLE
Bulk Mode Scan

### ISSUE THREAD

**Issue by FlyingPikachu** [zxing/zxing#519]
Would anyone consider revisiting #39 so that we can utilize continuous scanning (bulk mode) in our apps? I've spent days searching for a snippet or hack, but to no avail. Repeatedly initiating scans is not an efficient solution.

(FYI I did adhere to the contributing guidelines by asking on the mailing list first: https://groups.google.com/forum/#!topic/zxing/Z_gYNKRhmpA)

**Comment by srowen** [comment]
I don't think so. I think the change would be fairly big since you'd have to define some new way to say the scanning is done and return the results. Right now this app is almost entirely in maintenance mode.
