### ISSUE TITLE
Barcodes with different color than b/w

### ISSUE THREAD

**Issue by sadedil** [zxing/zxing#521]
Hi;

I have a rare problem.
Our company have Code 39 barcodes, with black bars on the red background. ZXing barcode scanner can't read properly this barcodes, somtimes it takes 20 seconds, but reading OK for standart b/w barcodes, it reads in 1-2 second(s).

Is there any way to solve/hack this problem? Any configuration, suggestion or similar thing?

PS: I've also asked this question on ZXing.Net.Mobile project Issue page.

**Comment by srowen** [comment]
I think you just want to map your images to black-and-white first. If you know color = white, then you can easily write a transformation from YUV space that boosts "Y" (brightness) to the extent that U differs from V (U = V means no color).

I would do this in the library, except that in some cases, people have a color-on-white barcodes for example and so the opposite is desirable. Hm, if you have good success in developing this transform, maybe we could add them both as helper functions for `BufferedImage`s?
