### ISSUE TITLE
Camera locked after scanning

### ISSUE THREAD

**Issue by Fanalys** [zxing/zxing#522]
Hi ! 

Here my structure : 
MainActivity -> ScannerActivity -> ScannerFragment -> ResultFragment (after a scan)

I use ZXingScannerView on my ScannerFragment. When I scan a QR Code, the camera (ScannerView) got locked and I launch my ResultFragment but it doesn't appear on my screen, I always have my ScannerView enabled. How can I do to display my ResultFragment over the ScannerFragment without delete the ScannerFragment (I want to be back on the ScannerView after a back pressed on ResultFragment in order to scan a new QR Code).

Thanks for the help!

**Comment by srowen** [comment]
I think this is a question you'd have to answer elsewhere, as this app has no fragments. It's to do with your application design.
