### ISSUE TITLE
Zxing Barcode scanner android Camara not working

### ISSUE THREAD

**Issue by kpurohit** [zxing/zxing#525]
I am using zxing Barcode scanner with my android app. it was working properly. but from last few days when i am calling the app, app is called but camera is not geting open. but when i am clicking on help or setting button and comming back to first screen camara is open and i am able to scan the barcode.

I want to know the problem is with my app or zxing barcode scanner app. is there is any probleem with android permission or some thing else

**Comment by kpurohit** [comment]
how can you closed without give any solution

**Comment by srowen** [comment]
You provided no detail and appear to be asking about your app.

**Comment by kpurohit** [comment]
when i am calling the app is opens the app but some times app is not calling camera BUT WHEN I am clicking on help or setting and going back to home screen of the barcode app camera is getting open
