### ISSUE TITLE
Camera view scrambled

### ISSUE THREAD

**Issue by sniperle** [zxing/zxing#526]
Since a few weeks the camera picture is scrambled up (Barcode Scanner 4.7.5). I'm not sure but I think think this is happening since I updated to CM13. See the first picture please. A logcat is also attached.
At first I thought Barcode Scanner stooped working but then i mentioned that it still scans barcodes well. See the second picture please.
So why is my display screwed up and what can we do ?

![20151227-zxing1](https://cloud.githubusercontent.com/assets/3104188/12011231/b18180d4-acc5-11e5-89f2-c0e577770cea.png)

Logcat up to that point: 
12-27 12:05:36.012 I/ActivityManager(873): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.zxing.client.android/.CaptureActivity (has extras)} from uid 10009 on display 0
12-27 12:05:36.166 I/com.google.zxing.client.android.camera.open.OpenCameraInterface(9196): Opening camera #0
12-27 12:05:36.166 I/CameraService(261): CameraService::connect call (PID 9196 "com.google.zxing.client.android", camera ID 0) for HAL version default and Camera API version 1
12-27 12:05:36.347 I/DecodeThread(9196): Hints: {POSSIBLE_FORMATS=[AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E], NEED_RESULT_POINT_CALLBACK=com.google.zxing.client.android.ViewfinderResultPointCallback@288907e}
12-27 12:05:36.807 I/ActivityManager(873): Displayed com.google.zxing.client.android/.CaptureActivity: +781ms
12-27 12:05:36.841 I/WindowManager(873): Screen frozen for +814ms due to Window{cdf5e1 u0 Starting com.google.zxing.client.android}

![20151227-zxing2](https://cloud.githubusercontent.com/assets/3104188/12011242/07338932-acc6-11e5-8dad-f8ffebb47d59.png)

**Comment by srowen** [comment]
This virtually always means the camera says it supports preview data of one size, and when selected, sends a different preview size. It's going to be a device problem of some form.

**Comment by soenkegissel** [comment]
Hi there, 
I have the exactly same problem. The devices camera (com.google.camera) reports strange FPS rates. Did update to CM13 too and hope it's a problem with my device online.

Can someone with da Nexus device and official 6.0 confirm the issue or is it running smooth?!
