### ISSUE TITLE
How do I set the preview size?

### ISSUE THREAD

**Issue by enlob** [zxing/zxing#527]
I'm using zxing on android via intent. I have followed the instructions of JourneyApps to include zxing in Android Studio. This means I simple call the initiate method of IntentIntegrator to start the scan. But when it starts it goes in 640x360 resolution. I need to change it to 640x480. I think I found the config file where this information is defined: it should be CameraConfigurationUtils.java and I should edit the MIN_PREVIEW_SIZE. But I have no idea how to integrate zxing in my project so that I can edit that file. I also would need to set the zxing activity to fullscreen and to do so I need get inside the activity, as I'm not able to achieve it via intent now. Thanks for help.

**Comment by srowen** [comment]
(This is for reporting bugs and suggesting changes, rather than questions.) The best supported resolution is automatically selected. You can't control it. You do not integrate the code directly with intents.
