### ISSUE TITLE
Amazon app store

### ISSUE THREAD

**Issue by Starwind0** [zxing/zxing#532]
Hello

I know its known that you all do not release to the amazon app store. However, I would like to request that you all to please release it to the amazon app store. 

Bluntly, my work has to work on all the variants, including amazon. As this seems to have some relation to google, I understand why there is semi aggressive talk of "third part app stores" and the like. Google vs amazon.. but the reality is we developers need this tool on both amazon and play. We don't get to just make it for one of the android platforms. If the tool doesn't work on all platforms then its a pretty poor tool. No major venture could hope to use this library. The fix would be a simple official release from you all to the app store, and 2 lines of code to direct it to the correct store.

Wouldn't be a major issue, if the library is easily turned into a jar and thus would be free of "what store" the user has access to. I've been poking at this with that in mind. Easy is not how I would describe it. I have seen several contributors saying that its desired I don't do exactly that. 

Anyways thats just my 2 cents. I'll obviously have a solution before theres a reply, let alone a real fix.

**Comment by srowen** [comment]
I've had bad experiences working with Amazon, and they require you to assign additional rights to Amazon, like being able to modify the app. I won't do this, especially given the huge reach of Play and tht this is in maintenance mode. It's already a library.

**Comment by Starwind0** [comment]
Fair enough. I will try to figure out how to add the library again..

**Comment by eakratsada** [comment]
F
