### ISSUE TITLE
zxing scan site error

### ISSUE THREAD

**Issue by dlchase** [zxing/zxing#533]
I am attempting to do a barcode scan using URL zxing://scan/?ret=....
and I am getting back message below:

The webpage at http://scan/ might be temporarily down or it may have moved permanently to a new web address.
I have tried both the zxing://scan/ URL and the http://zxing.appspot.com/scan URL and both do the same.

**Comment by srowen** [comment]
It's something wrong with whatever is invoking that URL. It's trying to open it as a web page, but it isn't one.
