### ISSUE TITLE
{CODE} not getting replaced in return URL

### ISSUE THREAD

**Issue by DArrigoni** [zxing/zxing#536]
I'm probably doing something wrong but I have a link like this: 

    <a href="zxing://scan/?ret=http%3A%2F%2Ffoobar.foobaz.dev%2Flisting%2Fsearch%2F%7BCODE%7D" id="header_top_nav_scan">
      <i class="fa fa-barcode"></i>
      Scan
    </a>

And I keep getting {CODE} back instead of what was scanned. Am I doing something wrong or is there an issue?

**Comment by DArrigoni** [comment]
On a whim, I tried running it unencoded: 

    <a href="zxing://scan/?ret=http://crateandbarrel.cloudtags.dev/listing/search/{CODE}" id="header_top_nav_scan">
      <i class="fa fa-barcode"></i>
      Scan
    </a>

And now it works. I'm using Chrome from an Android. Is Chrome doing something to double escape the URL?

**Comment by srowen** [comment]
The latter looks right to me. I would expect both forms to work, but I'm not sure why the latter does only. Yes, in any event it should be something to do with Android or Chrome instead

**Comment by DArrigoni** [comment]
Well, my immediate problem is solved. Unless this warrants more investigation, I'll close this issue.
