### ISSUE TITLE
Camera preview is black on second time.

### ISSUE THREAD

**Issue by devmaheshrb458** [zxing/zxing#543]
I am writing an application to scan QR code. Where I am having two activities first one call second and in second one I am using the me.dm7.barcodescanner.zxing.ZXingScannerView to scan the QR code. 
1. First time when I go to second activity for scanning it is working fine 
2. When I go back by pressing the device back button and again going to second button the Camera preview is black. 

Currently I am using the following setting :
        zXingScannerView.setResultHandler(this);
        zXingScannerView.setKeepScreenOn(true);
        zXingScannerView.setFlash(flash);
        zXingScannerView.setAutoFocus(autoFocus);
        zXingScannerView.setFormats(ZXingScannerView.ALL_FORMATS);
        zXingScannerView.setFormats((List<BarcodeFormat>) zXingScannerView.getFormats());
        zXingScannerView.setWillNotDraw(true);   

Need your suggestion on urgent basis.  

![screenshot_2016-01-21-03-16-44](https://cloud.githubusercontent.com/assets/7732524/12479048/a3dc3d14-c05e-11e5-8933-5d7a6a7d67ed.png)

**Comment by srowen** [comment]
You need to ask whoever created `me.dm7`

**Comment by devmaheshrb458** [comment]
Ohk.

Regards,


*Mahesh Bhatkande*
