### ISSUE TITLE
(zxing.appspot.com) support for email+subject+content format inqr code generator [Feature Request]

### ISSUE THREAD

**Issue by gwpl** [zxing/zxing#547]
Some Sites support generator of QR Code with prefilled email with address,subject,content.

I find it working perfectly with QR Code reader!
I can snap QR Code with prefilled email on Android and send it via GMail app without any hassle.

However for generation, I need to go to other places than zxing.appspot.com generator.

I've found such articles describing format:
http://www.labnol.org/internet/email-with-qr-code/19610/
http://www.labnol.org/internet/email/learn-mailto-syntax/6748/
I am sure there are much more.
Here is example of other sites that generate such codes working well with ZXing reader: http://www.qr-code-generator.com/ , and example generated QR Code with prefilled email: https://goo.gl/Jh1xKU .

Best regards,
Grzegorz Wierzowiecki

**Comment by srowen** [comment]
You can make the change in the source code and I'll review it, but I don't otherwise make changes by request.

**Comment by gwpl** [comment]
Let me try to work on it.

**Comment by Carringguns** [comment]
The interesting thing is your aware of this. I caught it i time without software. But its intentions here  clear opening up Google authentication w/bar scaner and admin app. WOW. thats a good one. Then does what they do.. very creative. I saved the  overstack flow and didnt report it myself and save the program used to employ you code if you wish to view for adaption.
    Thank you for addressing this.
