### ISSUE TITLE
Issue with landsacape navigation

### ISSUE THREAD

**Issue by woj-tek** [zxing/zxing#548]
I've been using ZXing for a long time and it works great except one thing - exiting it is a pain as it always forces landscape mode but with a twist - all navigation buttons seems to be stacked in the middle of the navbar making them completely unusable. 
The only way to get around that is to either scan proper code and then with it go to another app or go to settings/help and then use the navbar to go to the home screen...

**Comment by srowen** [comment]
Are you talking about your own app? or the Barcode Scanner app? what nav buttons? I am not sure what you're referring to

**Comment by woj-tek** [comment]
Barcode Scanner app (from f-droid, `com.google.zxing.client.android`)

_Picture speaks more than a thousand words_ so here's screenshot:
https://www.dropbox.com/s/mcmcq9s3uyl4t4f/2016-01-28_08_57_182.png?dl

**Comment by srowen** [comment]
I'm not sure, that looks normal. It's full-screen -- possibly still showing the Android navigation. You can see the app is a simple full screen landscape app so I don't think it's anything to do with the app. If you have a change to propose in the code open a PR.

**Comment by woj-tek** [comment]
Well, this is the only app that manifests this behaviour.

Unfortunately I'm not and android developer so (for now) I don't have any PR.

**Comment by Forage** [comment]
I've got the same issue. No on-screen buttons are shown when the app is in landscape mode, neither do I have a way to prevent landscape mode. So I'm basically never able to exit the app normally.
The only way possible is to open the app settings through the menu and jump right to the home screen from there.
