### ISSUE TITLE
False positive EAN_8 barcode extracted in addition to correct UPC-A and QR-CODE barcodes

### ISSUE THREAD

**Issue by lucaswiman** [zxing/zxing#553]
I noticed the following when doing some testing of the zxing library. The image below contains a UPC-A barcode and a QR code, but when the `CommandLineRunner` is run with `--multi --try_harder`, it finds a spurious EAN 8 barcode. I'm guessing this is because part of the barcode is creased and UPC-A and EAN-8 use the same encoding. It presumably picks up the creased UPC-A barcode "part way through", finding something like an EAN-8 encoding.

Please free to close this issue as "won't fix". The issue isn't likely to cause many problems in practice, and `--try_harder` is a mode which I presume is prone to false positives. My hope was that you might be interested in a tricky false positive example to add to your collection of test cases if a fix is possible.

Thanks for all your work on this excellent library!

## How to reproduce
Note that only the QR code is found without `--try_harder`.

```
cd /tmp
git clone https://github.com/zxing/zxing.git
cd zxing
git checkout 1eaa66dbfac104c145aaf12f80383dd8e5a26bce
mvn package -DskipTests
cd javase
mvn -DskipTests package assembly:single
curl https://cloud.githubusercontent.com/assets/123110/12871393/de032b9e-cd2c-11e5-890a-bafca3285256.jpg > battery-package.jpg
java -jar target/javase-3.2.2-SNAPSHOT-jar-with-dependencies.jar battery-package.jpg --multi --try_harder
```

## Output
```
/tmp/zxing/javase $ java -jar target/javase-3.2.2-SNAPSHOT-jar-with-dependencies.jar battery-package.jpg --multi --try_harder
file:///private/tmp/zxing/javase/battery-package.jpg (format: QR_CODE, type: URI):
Raw result:
http://2d-scan.us/53655710
Parsed result:
http://2d-scan.us/53655710
Found 4 result points.
  Point 0: (1022.0,314.0)
  Point 1: (850.0,316.5)
  Point 2: (848.0,146.0)
  Point 3: (991.5,172.0)
file:///private/tmp/zxing/javase/battery-package.jpg (format: UPC_A, type: PRODUCT):
Raw result:
039800099099
Parsed result:
039800099099
Found 2 result points.
  Point 0: (1326.0,546.0)
  Point 1: (1326.0,99.5)
file:///private/tmp/zxing/javase/battery-package.jpg (format: EAN_8, type: PRODUCT):
Raw result:
77772114
Parsed result:
77772114
Found 2 result points.
  Point 0: (1163.0,1022.5)
  Point 1: (1163.0,743.5)
```

## Expected output
Same as above, but without the EAN_8 barcode.

## System information
OS X El Capitan 10.11.2.
```
$ java -version
java version "1.7.0_65"
Java(TM) SE Runtime Environment (build 1.7.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
```

## Image
![batteries](https://cloud.githubusercontent.com/assets/123110/12871393/de032b9e-cd2c-11e5-890a-bafca3285256.jpg)

**Comment by srowen** [comment]
Yeah, a false positive is always possible. Given enough pixels, something will look 'close enough' to a barcode. Indeed the whole library is a heuristic. How much like a barcode does every stretch of pixels look like? there's always threshold and rules to balance finding a real barcode vs not finding phantoms.

I am sure you can find images that consistently reproduce a false positive since decoding is deterministic. You could add this to the test suite, add changes or tunings that make it succeed, and then see how many other test images fail or succeed. If you find a setting that's net positive, I'd be happy to commit that. Otherwise, yeah this is just how it is.

**Comment by lucaswiman** [comment]
Alright. If I get a better understanding of the code working with the library further, I'll look in to submitting a patch with this as a test case.

Thanks again for your work on this library!
