### ISSUE TITLE
Getting result from "Scan from web page"

### ISSUE THREAD

**Issue by jraklovits** [zxing/zxing#554]
I know I can call a scan from a webpage and send the result to that scan to a custom URL.  I would like to capture the result of the scan, and insert it into a text box on the same webpage.  Is there a way to capture the result of the scan and save it as a variable?

**Comment by srowen** [comment]
No, there's no way for the app to address a field on a web page. It can open a URL that does whatever you want but it's a new page. I've remember something along these lines may be possible with some clever javascript in some situations -- dig through the mail archives.

**Comment by jraklovits** [comment]
Thanks!  I'll keep digging.
