### ISSUE TITLE
Android SDK API Level 23 Support, Issue with Browser.BookmarkColumns Class

### ISSUE THREAD

**Issue by jitendra7020** [zxing/zxing#557]
Hi ZXing Team,
I am trying to build ZXing android source code in Android Studio IDE, where i am using **compileSdkVersion 23** and **buildToolsVersion "23.0.2"** in **build.gradle** file.

I want to compile source code with Android SDK API 23 to support runtime permission, but IDE shows compile time error for API Level 23 because Android OS remove the **Browser.BookmarkColumns** class from API Level 23.

Please suggest solution for this problem ?

**Comment by srowen** [comment]
How about opening a pull request to just replace those references with the string value of those constants? that's OK by me.

**Comment by jitendra7020** [comment]
Actually i merge code manually in Android Studio, No direct pull request. Also i don't want to make any change on existing code for better code merging  in future. So can you provide any solution accordingly.

**Comment by srowen** [comment]
I'm not sure what you mean. I'm asking you to open the change against this project.

**Comment by laurre** [comment]
android.provider.Browser.BOOKMARKS_URI has also been removed but is still used in BookmarkPickerActivity.

**Comment by goldhair** [comment]
從我的 HTC 寄出

----- Reply message -----
寄件者： "laurre" <notifications@github.com>
收件者： "zxing/zxing" <zxing@noreply.github.com>
主旨： [zxing] Android SDK API Level 23 Support, Issue with Browser.BookmarkColumns Class (#557)
日期： 週三, 3月 9 日, 2016 年 19:01


android.provider.Browser.BOOKMARKS_URI has also been removed but is still used in BookmarkPickerActivity.

---

**Comment by laurre** [comment]
From the Android 6.0 Release Notes: 
"If your app targets Android 6.0 (API level 23) or higher, don't access bookmarks from the global provider or use the bookmark permissions. Instead, your app should store bookmarks data internally."

Maybe should we reconsider using bookmarks as it is now not recommended ?

**Comment by srowen** [comment]
Good point, I'll make that change too. The app does not target 23+, but supports 15+ actually. I don't want to remove this function for older Android versions. However the button is disabled in Android 6.
