### ISSUE TITLE
[UWP] Error: "The stream number provided was invalid." while screen rotation

### ISSUE THREAD

**Issue by bsautermeister** [zxing/zxing#559]
While checking out the UWP example app on my Windows 10 Mobile device got reproducable crashes when I rotate the screen while the scanner is active.

> "The stream number provided was invalid.\r\nPreviewState"

I tried to narrow down the problem and figured that the following code was causing the problem in ZXingScannerControl:

```
async void displayInformation_OrientationChanged(DisplayInformation sender, object args)
{
        displayOrientation = sender.CurrentOrientation;
        await SetPreviewRotationAsync();
 }
```

Commenting out this OrientationChanged event handler fixed the issue. Sure, the downside of this was that after rotating the phone, the camera behaved weired, due to the skipped call of SetPreviewRotationAsync().

**My suggestion for quick-fixing the issue:**
When navigating to the ScanPage, lock the screen orientation to the current rotation:
```
// LOCK screen rotation
var currentOrientation = Windows.Graphics.Display.DisplayInformation.GetForCurrentView().CurrentOrientation;
Windows.Graphics.Display.DisplayInformation.AutoRotationPreferences = currentOrientation;
```
Afterwards, unlock it:
```
// UNLOCK screen rotation
Windows.Graphics.Display.DisplayInformation.AutoRotationPreferences = Windows.Graphics.Display.DisplayOrientations.None;
```

In my opinion, not being able to rotate the screen while scanning is much better than having a crash :)

**Comment by srowen** [comment]
Wrong project
