### ISSUE TITLE
Read from file

### ISSUE THREAD

**Issue by homersimpsons** [zxing/zxing#566]
Can you add an option to read code from an image (jpg, png ...)

**Comment by srowen** [comment]
You can already read from a file. Look in the `javase` module.

**Comment by Selaron** [comment]
Is this also possible in android module? (App "Barcode Scanner").

One possible use case is crypto key verification of the app conversations.im which relies on 2D Code scanning via Barcode Scanner app without alternative.
It would help work around e.g. this issue: https://github.com/siacs/Conversations/issues/2175

If many people want to reliably trust my key, I'd screenshot my 2D-Code, provide it thru a secure channel to my contacts (e.g. trusted https download) and they can trigger Barcode Scanner, choose the received image file and proceed even if their device does not have a functional camera.
