### ISSUE TITLE
Making appspot proper multi-step GUI, where you can edit each step

### ISSUE THREAD

**Issue by stelt** [zxing/zxing#568]
Now you fill in a form ==> see all results
I propose putting things in the right order: form, text, URL, image and next to editing the form, also allow editing text  and URL.
Superbonus would be inverse steps, when data allows

**Comment by srowen** [comment]
I'm not sure what you mean. You fill in the form (input), and see the QR code and its encoded text (output). What can be different, and how or why could it be inverted?

**Comment by stelt** [comment]
For example I've seen Calendar events including a URL encoded in QR, but the form here doesn't support that.
With my suggestions implemented my workflow would be: easily use the form, than manually edit the generated text to make the custom changes. With a LOT of variations in QR support and no time/space for forms for all those combinations this is a nice generic way outside the few 'rather standard' QRencodings.

The superbonus of inverse steps where data validity allows, would make it into a QRscanner and debugger too, next to a generator. Which would make it the one-stop ultimate QR-powertool

**Comment by srowen** [comment]
You can already enter free text as a type of input if you need to -- see Text. I think this is simpler than having the output text also be input, for the rare use case where you want to customize it.

Adding a URL to the calendar form is probably pretty easy in contrast, and I'd look at a PR for that. 

I still don't see what the inverse would do -- decode a QR code? but there are already apps and online services for that, including one from this project

**Comment by stelt** [comment]
- Thanks for explanation.
- PR, probably simple enough for me in this case, will look into it
- will find the QRdecoder from this project
