### ISSUE TITLE
camera support for http://zxing.org/w/decode.jspx

### ISSUE THREAD

**Issue by stelt** [zxing/zxing#569]
no more
make photo, switch to decoder, select file where photo is saved into, decode
but
scan (and to be fair at least once: ALLOW camera use)

**Comment by srowen** [comment]
I don't understand this. Please read `CONTRIBUTING.md` and don't open feature requests

**Comment by stelt** [comment]
See http://serratus.github.io/quaggaJS/examples/live_w_locator.html to see what I mean.
There it uses the webcam to scan barcodes immediately
