### ISSUE TITLE
sometimes return random number

### ISSUE THREAD

**Issue by vagrant1991** [zxing/zxing#574]
call decodeWithState method in MultiFormatReader class, get the result from the Result.getText() method， sometimes it is a random number. here is a example QR code:

![image](https://cloud.githubusercontent.com/assets/7079919/14201185/c3140d14-f822-11e5-8921-9b4fe466ad69.png)

#https://github.com/dm77/barcodescanner/issues/188

**Comment by vagrant1991** [comment]
[https://github.com/dm77/barcodescanner/issues/188](url)

**Comment by vagrant1991** [comment]
#https://github.com/dm77/barcodescanner/issues/188

**Comment by srowen** [comment]
It is probably just a false positive read, which is common with a non-photo image. You don't want to search for all formats, just QR codes.

**Comment by vagrant1991** [comment]
@srowen so, if i want to scan  UPC_E UPC_A QR_CODE format at the same time, how can i do that?  it seems zxing decode the qr code as a barcode, so it return a random number, what do you mean a  non-photo image?  can you explain that..... i am sorry for my bad english.

**Comment by srowen** [comment]
You can reject the false reads by looking at the resulting format. If you know it's a synthetic image like this and not a photo of a barcode, always use the PURE_BARCODE mode to avoid this. In no case is a "random number" returned.

**Comment by sidgorey** [comment]
How to use the PURE_BARCODE mode?
