### ISSUE TITLE
ArrayIndexOutOfBoundsException in HybridBinarizer

### ISSUE THREAD

**Issue by akwizgran** [zxing/zxing#578]
My app caught the following exception while scanning a barcode with zxing-core 3.2.1:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=460800; index=460800
at com.google.zxing.common.HybridBinarizer.calculateBlackPoints(HybridBinarizer.java:184)
at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:79)
at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
```

**Comment by srowen** [comment]
Do you have a reproduction for this? I get reports like this already but never have an image to reproduce. Usually I assume it's a bad driver sending back the wrong size image. If it _never_ works for you, then that's probably it. If it _sometimes_ fails for you, it's almost certainly some corner case in the app.

**Comment by akwizgran** [comment]
This is the first time I've seen this crash in hundreds of scans on half a dozen devices. Is there some check I can perform on the preview frame before constructing the binarizer to check whether the data's valid?

**Comment by tanelihuuskonen** [comment]
I copied the loop code from HybridBinarizer and changed the array reference into a simple check for the index being less than height * width.  It worked for all sizes where 8 <= height < 1000 and 8 <= width < 1000.  I suspect the bug is a corner case in the driver.

**Comment by akwizgran** [comment]
@tanelihuuskonen thanks for checking this out! I agree that a corner case in the driver is likely as I've never run into this exception before or since. What checks should I perform on the preview frame received from the camera to validate it before passing it into the QRCodeReader? Or would it be better to make no assumptions about the preview frame and just catch the exception in the rare case that the frame is invalid?

**Comment by srowen** [comment]
Yeah, I mean obviously the problem is that the expected size of the image doesn't match the actual size of the data from the driver. I'm sure that's the proximate cause already, but the question is why. I have seen this happen in the past when the driver fails to init: you ask for preview size X x Y and it fails to take that config, and you get some default (much smaller) size back.

That is, I think it would fail never or always. It's not something intermittent -- I think. I'd be super surprised.

**Comment by akwizgran** [comment]
The app calls camera.getParameters().getPreviewSize() in the onPreviewFrame() callback, and uses the resulting width and height to create the decoder, but I guess the parameters may change between the time the preview frame is generated and the time it's delivered to the PreviewCallback, so the data may correspond to a different preview size.

**Comment by srowen** [comment]
I don't (yet) see how it changes though. It should be set correctly once at the outset.

**Comment by tanelihuuskonen** [comment]
@akwizgran To avoid the index out of bounds exception, you should make sure the length of the data array is at least the height times the width of the image before calling the constructor of a luminance source.  I'm afraid I don't know enough about camera drivers to suggest a proper fix for the underlying problem.
