### ISSUE TITLE
ZXing issue in iOS...

### ISSUE THREAD

**Issue by ambujshukla** [zxing/zxing#580]
I'm working in an app which uses ZXing and I need to scan 1D Barcode like Code - 128...But after a lot of search in google, didn't found any result...So please help me out so that both 1D Barcode and QRCode can be scanned at a time...

This is what I have done:-

     MultiFormatOneDReader *multiReader = [[MultiFormatOneDReader alloc] init];
        QRCodeReader *qrcodeReader = [[QRCodeReader alloc] init];
        readers = [[NSSet alloc ] initWithObjects:qrcodeReader,multiReader,nil];

  Decoder *decoder= [[Decoder alloc] init];
    decoder.readers= readers;
    decoder.delegate= self;

And some where I have read that barcode scanning is not supported by it, only it supports QRCode...But not found in their documentation...

**Comment by srowen** [comment]
This code isn't in the project anymore.

**Comment by ambujshukla** [comment]
Thanks.
So do you have any idea when it was supported how they perform this task...Please help...

**Comment by ambujshukla** [comment]
Means they have fully discard the support for iOS.
