### ISSUE TITLE
Scan from web page removes query string keys

### ISSUE THREAD

**Issue by bdewater** [zxing/zxing#581]
For a web app I'm working on I am experimenting with adding support for scanning bar codes with the [scan from web](https://github.com/zxing/zxing/wiki/Scanning-From-Web-Pages) option using the zxing URI scheme. Depending on where in the web app the user decides to create a new item, a link like https://example.com/items/new?stuff_id=123 is generated so that certain fields can be prepopulated with 'stuff' data.

In order to not lose the prepopulated data, I included the query string in the return URL like this `zxing://scan/?ret=https://example.com/items/new?barcode=%7BCODE%7D&stuff_id=123` but after scanning I'm redirected to `https://example.com/items/new?barcode=9988776655` - the prepopulated 'stuff' fields are now empty.

Changing the order of the key/value pairs doesn't work either: `zxing://scan/?ret=https://example.com/items/new?stuff_id=123&barcode=%7BCODE%7D` bring me to `https://example.com/items/new?stuff_id=123` after scanning, so the barcode field is not populated.

I am using Barcode Scanner version 4.7.5 on an Xperia Z3 Compact running Android 5.1.1.

**Comment by srowen** [comment]
You need to URL encode the `&`. Right now it's interpreted as a parameter to the original URL only, where it doesn't do anything.

**Comment by bdewater** [comment]
That was very obvious in hindsight. Thanks!
