### ISSUE TITLE
How to generate  galois field for block size  65536 bytes

### ISSUE THREAD

**Issue by mushahidh** [zxing/zxing#585]
While working on your amazing library i got stuck at the point when i need to enlarge the RS coding block size more than `public static final GenericGF AZTEC_DATA_12 ` . I am trying use RS coding block size equal to 2^16 and i am initializing it like this
```
public static final GenericGF AZTEC_PARAM = new GenericGF(0x00010001, 65536, 1);
```
But it is very much slow and i guess it is due to the first parameter i am using against x^16+1. How can i make it efficient? And it would be great if you initialize  GenericGF for all combinations till x^16.
Thanks

**Comment by srowen** [comment]
Questions should go to https://groups.google.com/forum/#!forum/zxing
I don't think a moderate field size would slow anything down, since operations' time doesn't depend on the field size. You'd have to profile your app to see where the slowdown is.
