### ISSUE TITLE
Android bug

### ISSUE THREAD

**Issue by ehaahe** [zxing/zxing#586]
the next is the error log:
java.lang.IllegalArgumentException
Crop rectangle does not fit within image data.
com.haibao.zxing.camera.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:45)
com.haibao.zxing.camera.CameraManager.buildLuminanceSource(CameraManager.java:327)
com.haibao.zxing.decoding.DecodeHandler.decode(DecodeHandler.java:85)
com.haibao.zxing.decoding.DecodeHandler.handleMessage(DecodeHandler.java:55)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:136)
com.haibao.zxing.decoding.DecodeThread.run(DecodeThread.java:83)

what can i resove this issue?

**Comment by ehaahe** [comment]
Screen resolution of the phone is 1080*1800

**Comment by srowen** [comment]
This means you fed image data that was smaller than what the app was expecting. I'm closing this since it is not a question about this project's code, but your modification.
