### ISSUE TITLE
Support for erasure correction

### ISSUE THREAD

**Issue by mushahidh** [zxing/zxing#587]
When dealing with Ethernet/IP network we deal with erasures instead of errors. We know which packets are missing so RS error correcting capability is increased by giving its position. Therefore, 1 parity symbol can recover from one erasure instead of 2 symbols for one error. I have an idea you must know all these details. Just wondering why there isn't any thing in the docs regarding passing error position to rs decoder so that its error correcting capability can be increased. Ior is there a way to tackle with erasures instead of errors in zxing?

**Comment by srowen** [comment]
The error correction routines do support erasures and errors. You'd have to read the implementation to see how it works though. This isn't an issue report, so I'm closing it.

**Comment by mushahidh** [comment]
@srowen  its better to update docs for newbies .
Thanks
