### ISSUE TITLE
UWP camera use

### ISSUE THREAD

**Issue by romanryba** [zxing/zxing#588]
I am using Xamarin Forms and UWP.
If you use scanner 
`ZXingScannerPage scanPage = new ZXingScannerPage();`
               ` scanPage.OnScanResult += async (result) =>`
                `{
                       ...
                 }`

than CameraCaptureUI is not working or any cammera usage after using the scanner and not killing the app. Only exception is the ZXingScannerPage  that works after closing and opening the page.
I dont know if it is feature of UWP or actual bug...

**Comment by srowen** [comment]
This code is not in this project.
