### ISSUE TITLE
Kindle / Amazon store support

### ISSUE THREAD

**Issue by Rockvole** [zxing/zxing#592]
Excellent work on this library Sean.

I would prefer to use your library over the Google barcode api since this would allow me to support barcode reading on kindles with the same codebase.
Unfortunately, when I try to install your app from mine via Intent it cannot find your app on the Amazon store. (I tried installing your apk on my Kindle and it worked great).

Is there a way to install via Intent on Kindle devices ?
Thanks.

**Comment by srowen** [comment]
Questions should go to https://groups.google.com/a/cloudera.org/forum/#!forum/zxing
I'm not quite sure what you mean, but the version on Amazon is unofficial and not related to the project, published by Amazon itself. I can't help you with it.
