### ISSUE TITLE
Code 128 and FNC1 error in autoswitching mode

### ISSUE THREAD

**Issue by mrprunen** [zxing/zxing#593]
### Bug Reports
i try to encode ucc ean128 whit **not** force_codset_b ( space requirements)
if i encode string      Chr(241) & "100958" & Chr(241) & "17160526"   work
if i encode string      Chr(241) & "10958" & Chr(241) & "17160526"   doesn't work 

class return **System.FormatException**

i guess error returned from 
https://zxingnet.svn.codeplex.com/svn/trunk/Source/lib/oned/Code128Writer.cs
in instruction 
`patternIndex = Int32.Parse(contents.Substring(position, 2));` 

I guess the problem is related to the attempt to change the SUBSET automatically.
When the FNC1 is even , it is interpreted as a number and then goes into error.

**Comment by srowen** [comment]
This is not code from this project.

**Comment by tanelihuuskonen** [comment]
Actually, the same bug occurs here.  I tested.  I'll see if I can fix it.

**Comment by tanelihuuskonen** [comment]
I have a fix that at least doesn't throw an exception on the cases you mention.  I'm working on some further tests before submitting a pull request.
