### ISSUE TITLE
Scanning in Portrait mode QR code not scanning when fit to scan area

### ISSUE THREAD

**Issue by naveen7593** [zxing/zxing#598]
Hi,

In Native zxing-BS-4.7.5, when scanning qr code fit to scan area in portrait mode it hadn't scan.
But it did scan when the distance between Scan Surface and mobile increase. The same issue hasn't happening in landscape. Please find the Screen Shots for this issue. 
Advance thanks for any suggestion

![not_scanning_on_fit_scan_area](https://cloud.githubusercontent.com/assets/19486269/15420573/21c17f20-1e8b-11e6-95e3-a3cc60b11583.png)
![scanning_with_some_distance](https://cloud.githubusercontent.com/assets/19486269/15420574/21e350e6-1e8b-11e6-8d4f-1e085aa6cb72.png)

.

**Comment by srowen** [comment]
I'm not sure what you're reporting, but it sounds like an issue in your app. There is no portrait mode in the app here.

**Comment by naveen7593** [comment]
Hi Sean Owen,

Thanks for the response.

I have downloaded the source code of Zxing from "
https://github.com/zxing/zxing/releases". I have modified the code, in
android manifest orientation of CaptureActivity from "sensorLandscape" to
"sensorPortrait".

when scanning qr code fit to scan area in portrait mode it hadn't scan.
But it did scan when the distance between Scan Surface and mobile increase.

It happening in zxing.


Thanks,
Naveen R.
Software Engineer.


On Fri, May 20, 2016 at 4:01 PM, Sean Owen <notifications@github.com> wrote:

> I'm not sure what you're reporting, but it sounds like an issue in your
> app. There is no portrait mode in the app here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zxing/zxing/issues/598#issuecomment-220572062>
>

-- 

------------------------------

This email message, including attachments, may contain confidential and/or 
privileged information and/or material.  If you receive this message in 
error, please notify the sender and delete it from your mailbox and system 
immediately.  Any review, retransmission, dissemination or other use of, or 
taking any action in reliance upon, this message, by anyone other than the 
intended recipient, is not authorized.  The sender disclaims all liability 
from unauthorized use.  Skava is a private company incorporated in 
California as Kallidus, Inc.  This communication may come from Skava or one 
of its affiliates.

**Comment by naveen7593** [comment]
If you want the apk or the code i have tried of zxing please let me know.
