### ISSUE TITLE
Android front camera inverted upside down

### ISSUE THREAD

**Issue by abelgs1987** [zxing/zxing#599]
I'm facing with a really weird issue.

ZXing in my android mobile with front camera is inverted and thus i don't get the barcode to work. Instead, in iOS works perfectly.

I'm wondering if this is a possible bug with this component in Android version.

I would appreciate any advice.
Many thanks

**Comment by srowen** [comment]
I'm not sure what you built or what you're running. To get the camera orientation right you need to query the sensor, but the app already does that. Maybe your app is not.

**Comment by linfeng008** [comment]
I`m so sorry, I don`t know how to help you .

At 2016-05-20 15:42:19, "abelgs1987" <notifications@github.com> wrote:


I'm facing with a really weird issue.

ZXing in my android mobile with front camera is inverted and thus i don't get the barcode to work. Instead, in iOS works perfectly.

I'm wondering if this is a possible bug with this component in Android version.

I would appreciate any advice.
Many thanks
