### ISSUE TITLE
Zxing camera becomes slow when calling StartScanning second time after calling PauseAnalysis()

### ISSUE THREAD

**Issue by bwwilliam** [zxing/zxing#600]
I have three tabs in my app.
The first time swipe from tab1 to Scan tab where the scan window is located, it works perfectly fine. However, if I swipe to another tab then swipe back to Scan tab again. It takes about 8 seconds for the ScanFragment to come back. I'm using Xamarin for Android. I tried to use PauseAnalysis when swipe to a tab other than Scan tab that is when it becomes slow. I tried to use StopScanning when swipe away from Scan tab, but the problem is when swipe back to Scan tab, the camera does not really focus.

please see this link
http://stackoverflow.com/questions/37295838/zxing-camera-becomes-slow-when-calling-startscanning-second-time-in-xamarin

**Comment by bwwilliam** [comment]
please let me know if sample code need to be supplied.

**Comment by srowen** [comment]
I don't think any of this is related to this project's library. It's something to do with your app.

**Comment by bwwilliam** [comment]
thanks for your quick response. any chance you can take a look at this issue for me if I supply you my source code?
