### ISSUE TITLE
I am getting this error while on scan preview activity

### ISSUE THREAD

**Issue by mayurchudasama** [zxing/zxing#604]
05-25 18:20:42.373: E/AndroidRuntime(10772): FATAL EXCEPTION: main
	      05-25 18:20:42.373: E/AndroidRuntime(10772): java.lang.RuntimeException: autoFocus failed
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.hardware.Camera.native_autoFocus(Native Method)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.hardware.Camera.autoFocus(Camera.java:936)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at jim.h.common.android.zxinglib.camera.CameraManager.requestAutoFocus(CameraManager.java:220)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at jim.h.common.android.zxinglib.CaptureActivityHandler.restartPreviewAndDecode(CaptureActivityHandler.java:130)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at jim.h.common.android.zxinglib.CaptureActivityHandler.<init>(CaptureActivityHandler.java:64)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at jim.h.common.android.zxinglib.CaptureActivity.initCamera(CaptureActivity.java:200)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at jim.h.common.android.zxinglib.CaptureActivity.surfaceCreated(CaptureActivity.java:116)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:571)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.SurfaceView.access$000(SurfaceView.java:86)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:175)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:833)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1860)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.Choreographer.doFrame(Choreographer.java:532)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.os.Handler.handleCallback(Handler.java:730)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.os.Handler.dispatchMessage(Handler.java:92)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.os.Looper.loop(Looper.java:137)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at java.lang.reflect.Method.invokeNative(Native Method)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at java.lang.reflect.Method.invoke(Method.java:525)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	      05-25 18:20:42.373: E/AndroidRuntime(10772): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by srowen** [comment]
This is an Android platform error

**Comment by mayurchudasama** [comment]
Do you have solution for this error ?

**Comment by THEONE10211024** [comment]
I have the same problem toooooooooooooo!!!!!!
