### ISSUE TITLE
Encoding Problem in Unity3D

### ISSUE THREAD

**Issue by KevinCollmer** [zxing/zxing#605]
Hey,

I've ran into the following problem using zxing for unity3d.
`        var bw = new BarcodeWriter();
        var encOptions = new ZXing.Common.EncodingOptions() { Width = 300, Height = 300, Margin = 0 };
        bw.Options = encOptions;
        bw.Format = BarcodeFormat.QR_CODE;
        Color32[] result = bw.Write("test");
        texture2DBarcode = new Texture2D(300, 300);
        texture2DBarcode.SetPixels32(result);
        texture2DBarcode.Apply();`

The output is:

[https://i.gyazo.com/a6aa5bbecd922f9ef4d2a37a473d6d59.png](url)

**Comment by srowen** [comment]
This is about code from another project.
