### ISSUE TITLE
Dialog Disappears on Device Rotation

### ISSUE THREAD

**Issue by reverse-unina** [zxing/zxing#611]
When I perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1.  Click on History
2.  Click on Delete
3. Orientation Change

Sequence 2:
1.  Click on More..
2.  Click on Settings
3.  Click on CustomSearchURLValidator
4.  Enter Text Example
5.  Click on OK
6. Orientation Change

**Comment by srowen** [comment]
These are intentional, or at least, not something I'd identify as a problem. Usually you stay in landscape orientation in the app, but, changing orientation reasonably cancels a modal dialog
