### ISSUE TITLE
Using Swagger with Zxing.org to make a barcode reading API

### ISSUE THREAD

**Issue by trifwnas** [zxing/zxing#617]
**My Swagger**

```yaml
{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "BarcodeScanner",
        "description": "A BarcodeScanner API"
    },
    "host": "zxing.org",
    "schemes": [
        "http"
    ],
    "basePath": "/w",
    "paths": {
        "/decode": {
            "post": {
                "tags": [
                    "decode"
                ],
                "operationId": "barcode_post",
                "consumes": [
                  "multipart/form-data"
                  ],
                "produces": [
                    "application/json",
                    "text/json",
                    "application/xml",
                    "multipart/form-data",
                    "text/html"
                ],
                "parameters":[
    					{
    						"name":"f",
    						"in":"formData",
    						"description":"file with barcode to upload",
    						"required":true,
    						"type":"file"
    				},
                    ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string",
                            "items": {
                                "$ref":"#/definitions/barcode"
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
    },
    "definitions": {
        "barcode": {
            "type": "object",
            "properties": {
                "Id": {
                    "format": "int32",
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "BarcodeNumber": {
                    "type": "string"
                }
            }
        }
    }
}
```
**Issue**
http://stackoverflow.com/questions/37955006/using-swagger-with-zxing-org-to-make-a-barcode-reading-api

Hi,
I am trying to use the online swagger editor (editor.swagger.io) in order to create a post request to the Zxing barcode reader web app (zxing.org/w/decode.jspx) and get back the decoded barcode data. In Postman I use the parameter "f" and the setup below and it works. Please help me fix my swagger file! Thank you in advance! :)

FYI, the web app uses the below form:
`<form enctype="multipart/form-data" method="post" action="decode"><tr><td style="text-align:right">Or upload a file (&lt;10MB, &lt;10MP):</td>
<td> <input name="f" type="file"/></td><td><input type="submit"/></td></tr></form>`

![1nmzo](https://cloud.githubusercontent.com/assets/6863495/16260284/031c9a64-3867-11e6-88a0-d1d2c5fd8c30.png)

**Comment by srowen** [comment]
I'm not sure what swagger is, and you haven't stated a problem. I don't think this is the place for swagger help. Although I don't mind if you send low traffic to zxing.org, if it's significant, you'll want to run your own copy of it.

**Comment by trifwnas** [comment]
Hi @srowen ,

Thank you for your reply and for the great work with the Zxing project.

I am running my own copy of zxing.org but I do not keep it up when I am not using it so I couldn ask for support on a dead server. My final implementation will work only with my copy.

The problem I am facing is probably with the requests that zxing.org accepts. Does it accept XHR calls? How can I apply this fix [(link)](https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md) on my copy ?

Thank you in advance.

**Comment by srowen** [comment]
I'm not sure what XHR is, but it accepts HTTP POSTs. You can see the source code for the web app in this project.

**Comment by trifwnas** [comment]
Hi @srowen ,

XHR is basically AJAX.

I am writing to let you know that I have figured out how to communicate with my own copy of zxing.org and it seems that probably the one which is hosted in zxing.org does not accept CORS (Cross-Origin Resource Sharing) or maybe it allows specific urls but not the one I was trying from.

Thank you for your help anyways.

**Comment by srowen** [comment]
I'm not sure what you're referring to, but if you're proposing a change to the code, describe it in a pull request.
