### ISSUE TITLE
Empty screen displayed with Android 6

### ISSUE THREAD

**Issue by selmanon** [zxing/zxing#618]
Hi,
Some users report that they get an empty screen when they test the qr code feature in Android 6 (Samsung devices).

**Comment by srowen** [comment]
I have an Android 6 device and it works fine. It sounds like you may be referring to your own app. Without any more info in any event I don't think this is actionable.

**Comment by selmanon** [comment]
I will give more information about the problem ASAP but I just wana to share this : http://stackoverflow.com/questions/9028735/getting-camera-error-in-zxing-barcode-application/36857090#36857090 It's not the description of my case by the way
