### ISSUE TITLE
Bug: calling one instance of barcode from different return links does not work

### ISSUE THREAD

**Issue by neff78** [zxing/zxing#619]
Running android device
- have web page with call for barcode scanner (payed) with return URL string 1, and with return URL string 2 (both pointing to same page, but different GET variables - imagine it as i want to scann to 2 different stacks and process them later.)

Problem is, when i call BS with return string 1, barcode opens, and returns correctly all data to URL string 1. It stays open in "last open apps". Then if i want to call it again with string 2, it reopens, but returns data on previous address - from string 1. 

If i close the BS, and then run it via string 2, it works. It seems as it remembers the return address it was opened 1st time, and it does not rewrite it on second call.

any thoughts?

**Comment by srowen** [comment]
I am unable to reproduce this. I tried trigger the app with two different links with different return URLs, and in both cases the app redirected to the correct distinct URLs.
