### ISSUE TITLE
White screen displayed after qr code scan - Samsung Galaxy S6 Android 6.0.1

### ISSUE THREAD

**Issue by selmanon** [zxing/zxing#620]
Hi,

The normal UC is when I scan a valide qrcode I display a screen that show the user is login
When I install the app and after the first qr code scan I get white screen randomly.

Samsung Galaxy S6 
OS : Android 6.0.1

Regrads,

**Comment by VincentHink** [comment]
Hi Selmanon, did you find out what was causing this? We are encountering the same problem.

**Comment by albertml** [comment]
Hi, we are encountering also the same, any help would be our pleasure thanks.
