### ISSUE TITLE
Illegal Character Exception

### ISSUE THREAD

**Issue by bomski** [zxing/zxing#624]
Hi everyone,

i always get a illegal character exception if i try to create a DataMatrix with following code

```
HashMap<EncodeHintType, Object> options = new HashMap<>();
options.put(EncodeHintType.DATA_MATRIX_SHAPE, SymbolShapeHint.FORCE_SQUARE);

int width = 128;
int height = 128;
String content = "test TE>240 2 I.E ST>300";

BitMatrix bitMatrix = new DataMatrixWriter().encode(content, BarcodeFormat.DATA_MATRIX, width, height, options)
```

**Stacktrace**

```
java.lang.IllegalArgumentException: Illegal character: . (0x002e)
    at com.google.zxing.datamatrix.encoder.HighLevelEncoder.illegalCharacter(HighLevelEncoder.java:445)
    at com.google.zxing.datamatrix.encoder.X12Encoder.encodeChar(X12Encoder.java:65)
    at com.google.zxing.datamatrix.encoder.X12Encoder.encode(X12Encoder.java:34)
    at com.google.zxing.datamatrix.encoder.HighLevelEncoder.encodeHighLevel(HighLevelEncoder.java:182)
    at com.google.zxing.datamatrix.DataMatrixWriter.encode(DataMatrixWriter.java:84)
    at com.google.zxing.Writer$encode.call(Unknown Source)
```

Is this a bug or i'm missing something?

**Comment by tanelihuuskonen** [comment]
As far as I can tell, it's a bug.

**Comment by srowen** [comment]
Agree, it looks like a problem with `HighLevelEncoder.lookAheadTest`. It switches to X12 encodation when it can't encode ".". I debugged it for a bit but am not familiar with this part of the code. It does look like the part of the code labelled "Step R" does not follow the Data Matrix spec, quite. I hacked a quick fix for that, but it caused other test failures.

```
        if (minCount == 1 && mins[EDIFACT_ENCODATION] > 0) {
          return EDIFACT_ENCODATION;
        }
        if (minCount == 1 && mins[TEXT_ENCODATION] > 0) {
          return TEXT_ENCODATION;
        }
        if (minCount == 1 && mins[X12_ENCODATION] > 0) {
          return X12_ENCODATION;
        }
```
should be
```
        if (intCharCounts[EDIFACT_ENCODATION] + 1 < intCharCounts[BASE256_ENCODATION]
            && intCharCounts[EDIFACT_ENCODATION] + 1 < intCharCounts[C40_ENCODATION]
            && intCharCounts[EDIFACT_ENCODATION] + 1 < intCharCounts[TEXT_ENCODATION]
            && intCharCounts[EDIFACT_ENCODATION] + 1 < intCharCounts[X12_ENCODATION]
            && intCharCounts[EDIFACT_ENCODATION] + 1 < intCharCounts[ASCII_ENCODATION]) {
          return EDIFACT_ENCODATION;
        }
        if (intCharCounts[TEXT_ENCODATION] + 1 < intCharCounts[BASE256_ENCODATION]
            && intCharCounts[TEXT_ENCODATION] + 1 < intCharCounts[C40_ENCODATION]
            && intCharCounts[TEXT_ENCODATION] + 1 < intCharCounts[EDIFACT_ENCODATION]
            && intCharCounts[TEXT_ENCODATION] + 1 < intCharCounts[X12_ENCODATION]
            && intCharCounts[TEXT_ENCODATION] + 1 < intCharCounts[ASCII_ENCODATION]) {
          return TEXT_ENCODATION;
        }
        if (intCharCounts[X12_ENCODATION] + 1 < intCharCounts[BASE256_ENCODATION]
            && intCharCounts[X12_ENCODATION] + 1 < intCharCounts[C40_ENCODATION]
            && intCharCounts[X12_ENCODATION] + 1 < intCharCounts[EDIFACT_ENCODATION]
            && intCharCounts[X12_ENCODATION] + 1 < intCharCounts[TEXT_ENCODATION]
            && intCharCounts[X12_ENCODATION] + 1 < intCharCounts[ASCII_ENCODATION]) {
          return X12_ENCODATION;
        }
```
I'm a little hesitant to commit it, even though it does seem to solve this particular bug. I'd be interested in any more informed views about it.

**Comment by ShreyashPromact** [comment]
it seems like there is some correction required.

**Comment by ashishchauhan99** [comment]
I tried the patch from srowen, but this does not fix the issue properly. 
I got following problems:
1. it causes three tests to fail:

`[ERROR] Failures: 
[ERROR]   HighLevelEncodeTestCase.testEDIFACTEncodation:210->Assert.assertEquals:144->Assert.assertEquals:115 expected:<... 27 131 198 236 238 [98 230 31]> but was:<... 27 131 198 236 238 [124 89 47 89 129]>
[ERROR]   HighLevelEncodeTestCase.testHelloWorld:304->Assert.assertEquals:144->Assert.assertEquals:115 expected:<... 130 175 123 148 64 [158 233 254] 34> but was:<... 130 175 123 148 64 [254 109 101] 34>
[ERROR]   HighLevelEncodeTestCase.testTextEncodation:160->Assert.assertEquals:144->Assert.assertEquals:115 expected:<239 91 11 91 11 [87 218 110]> but was:<239 91 11 91 11 [254 98 74 110 129]>`

2 When you read the barcode **4 i.E.;** is strangly converted to **4!).E.**; . So in my understaning it converted the whitespace to **!)**

**Comment by srowen** [comment]
Yes, as I say, that isn't the fix. I don't know how to fix this one.

**Comment by oehhar** [comment]
Dear Axel,
thank you for your contact by E-Mail, this is appreciated. I will follow-up the issue on the ISO/IEC level. The timing is great, as ISO/IEC 16022 is in revision currently.

Thank you,
Harald
