### ISSUE TITLE
Getting bool(false) as result

### ISSUE THREAD

**Issue by Jayad** [zxing/zxing#626]
using same code as mentioned.
<?php

include_once('./lib/QrReader.php');
$qrcode = new QrReader('JayaAADHAR.jpg');
var_dump($qrcode);
$text = $qrcode->text(); //return decoded text from QR Code
var_dump($text);
?>
returning bool(false)

private $dataWidth =>
int(1021)
private $dataHeight =>
int(2459)
private $left =>
int(0)
private $top =>
int(0)
private $image =>
class Imagick#42 (0) {
}
private $width =>
int(1021)
private $height =>
int(2459)
}
class QrReader#41 (1) {
public $result =>
bool(false)
}
bool(false)

Any help on what is going wrong?
This is happening only when I am uploading a fullzise image with a QRcode section present.
The online decoder https://zxing.org/w/decode.jspx gives perfect output even when we upload a fullsize image.

**Comment by srowen** [comment]
Not even clear what this means.

**Comment by Jayad** [comment]
HI Srowen,

When I am trying to extract details from an QR code which is part of an Image, the same is not working, where as when I only use the QR code, its returning result.

**Comment by Jayad** [comment]
When the full Image (with QR code and other details like text and images, logo etc) are used for the online decoder https://zxing.org/w/decode.jspx, it is able to extract properly.

My question was why the php wrapper was not behaving exact same as the URL.

**Comment by crodrigor** [comment]
This library has a blind spot, depending on the position x qrcode she does not read
