### ISSUE TITLE
Red and blue colors swapped on glass preview image

### ISSUE THREAD

**Issue by scorpeeon** [zxing/zxing#632]
I'm using the latest XE22 firmware on Glass and the latest zxing scanner release I could find for glass: BarcodeScannerGlass-0.2.1.apk from https://github.com/zxing/zxing/releases

I noticed the preview image looked a bit weird, and found out, that it looks like the red and blue colors are swapped, it looks something like an RGB vs BGR issue (are you using OpenCV underneath maybe?). The strange thing is that it looks OK for a moment when starting or exiting from the app.

Scanning QR codes still work fine (as they don't need to be in a specific color), so otherwise I think it causes no major problems.

**Comment by srowen** [comment]
Could be. I no longer have Google Glass to test. But you can look at the code; it does nothing at all with the preview mode. You can suggest a change if you know of one, but I don't think this would be updated otherwise. I was going to remove the `glass` module as unmaintained later anyway.
