### ISSUE TITLE
Camera freeze in andriod and Window phone UWP 

### ISSUE THREAD

**Issue by AryanVerma** [zxing/zxing#635]
Hi,

I am pawan and using this library for Xamarin shared project. It's working in UWP but the issues is regarding camera is freeze while press on window button and after longpress of back button relaunch the app. In this case zxing is not reinit to camera for scanning.

**Comment by srowen** [comment]
This sounds like an error with your app, so it's not an issue with this project. If you mean the iOS code when you talk about Xamarin, that's not even part of this project.
