### ISSUE TITLE
plain pbm image format not working if whitespace in raster is omitted

### ISSUE THREAD

**Issue by markusobi** [zxing/zxing#638]
[foobar.zip](https://github.com/zxing/zxing/files/380393/foobar.zip)
Hello,

I don't know whether the following issue is due to your website image reader or due to your zxing library.
There is no impressum and no contact on your [website](https://zxing.org/w/decode.jspx) so I put the issue here.

When uploading a **plain PBM** image and there's no whitespace in the pbm's raster section, the website will prompt:

> **No Barcode Found**
> No barcode was found in this image. Either it did not contain a barcode, or did not contain one in a supported format, or the software was simply unable to find it. Go "Back" in your browser and try another image.

The [plain PBM specification](http://netpbm.sourceforge.net/doc/pbm.html) states:

- Each pixel in the raster is represented by a byte containing ASCII '1' or '0', representing black and white respectively.

- White space in the raster section is ignored.

In example gimp omits the spaces between the entries when an image is exported as pbm(ascii).
In the zip archive only file foobar2.pbm (with spaces inbetween) works and produces "foobar".

[foobar.zip](https://github.com/zxing/zxing/files/380395/foobar.zip)

**Comment by srowen** [comment]
It is just using Java's ImageIO to read images, so whatever that library supports is what it reads. I have not heard of PBM; it looks like some kind of an _ASCII_ format for encoding monochrome images? I'm not sure that's worth supporting.
