### ISSUE TITLE
No decode the qr-code when loading from a file

### ISSUE THREAD

**Issue by Aazamandius** [zxing/zxing#640]
I have attached the file. Library can not recognize the code shown on it on any device when loading from storage. 

![38e9fe88-5037-11e6-83fc-f416d0601076](https://cloud.githubusercontent.com/assets/4215125/17135409/564ec234-5338-11e6-8c04-bcbc95b74f2b.jpg)

Important condition - the presence of text in the image

Forwarded from https://github.com/journeyapps/zxing-android-embedded/issues/190

**Comment by srowen** [comment]
This scans on my phone and in the online decoder:
http://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F4215125%2F17135409%2F564ec234-5338-11e6-8c04-bcbc95b74f2b.jpg
