### ISSUE TITLE
Core: DecoderResult's rawBytes comes without bit length indication, ambiguity arises

### ISSUE THREAD

**Issue by fgrieu** [zxing/zxing#644]
The [DecoderResult class](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/common/DecoderResult.java#L28) has a getRawBytes() method returning a byte array with the raw code's content. Problem is, there's no way to know exactly how many bits are in there: up to 7 bits in the last byte can be unused (in which case they are zeroes, and indistinguishable from actual bits at zero). This can be a cause of ambiguity, to the point that codes with different contents can have the same RawBytes, defeating its use as an inspection tool.

For examples, these two Aztec codes both have RawBytes<br>`f5 55 55 75 6b 5a d6 b5 ad 6b 5a d6 b5 ad 6b 5a d6 b5 ad 6b 5a d6 b0`<br>but the left one one contains<br>`88888TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT`<br>while the right one contains<br>`88888TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTO`<br>
![t](https://cloud.githubusercontent.com/assets/7809433/17342852/69115698-58fb-11e6-8e4d-846751baa59a.png) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ![to](https://cloud.githubusercontent.com/assets/7809433/17340857/46a7eada-58f2-11e6-8711-e7c5f4fed16b.png)
Both are plain vanilla Aztec codes generated with [bwip-js](http://bwip-js.metafloor.com/demo/demo.html) using `format=full eclevel=31` and their respective content. At the end of the rawBytes, the `b0` byte actually contains the bits `1001` in the left code and `10010000` in the right code, and that changes the decoded content.

The issue is one of design of the DecoderResult class. I see two ways to fix this:
1. Extend the DecoderResult class (in package com.google.zxing.common) with a getRawBytesBitSize() method returning an int telling how many bits there are in what getRawBytes() returns. This will leave any existing code working (including zxing's own test code), and requires no change in existing decoders when they never leave unused bits in RawBytes, or when that somewhat does not matter.
2. Fill any unused bits of the last byte in RawBytes with bits at one rather than zero in package com.google.zxing.aztec.decoder. That makes it possible to unambiguously decode RawBytes into content of the Aztec code for any standard-conforming Aztec code, because extra one bits can only produce content if the length of an earlier byte shift sequence was followed by less than 8 times that number of bits (something ISO/IEC 24778:2008 does not condone).

Method 1 is certain to cause no compatibility issue, but makes the full interface of the DecoderResult class more complex,

Method 2 might not be extensible to all symbologies (if any other turns out to be affected by the limitation of the design of the DecoderResult class), often modifies the last byte in RawBytes returned for a given Aztec code (which in turn will require simple changes to zxing's test code specific to the Aztec decoder), and could conceivably silently break some existing application code. On the other hand this method
- is likely to fix existing application code decoding RawBytes according to ISO/IEC 24778:2008;
- ensures that when rebuilding a code from its RawBytes alone, even when the image is different (which can still happen), the content is the same (with aforementioned exceptions involving non-conforming original; also, attempted rebuilding could still fail if the few extra bits cause the maximum capacity to become exceeded);
- makes the existing [ZXing Decoder Online](https://zxing.org/w/decode.jspx) and similar tools more useful as a debugging aid if left without modification to show what the hypothetical new getRawBytesBitSize() gives;
- causes the less code bloat.

Any thoughts on what's the way to go?

**Comment by srowen** [comment]
Yes, the meaning of 'raw bytes' varies a bit from barcode format to format. In any format there may be 0, 1 or more intermediate stages that might be regarded as the 'raw' payload and might be represented as bytes. For QR codes it's obviously the codewords and those are bytes. 

For Aztec is it not possible to know from the bytes where it ends? it sounds like it is not, that additional 0 bits make it still a perfectly valid result bit set.

I think the best solution is returning the number of bits that are valid, indeed, and have some logic to default it to the number of bytes times 8 of course. Then the change is pretty minimal.

**Comment by fgrieu** [comment]
For Aztec codes, filling unused bits with 1 rather than 0 happens to avoid most ambiguities as to the content (in fact, any ambiguity in a valid symbol); that's the basis of my solution 2. I can't tell for other codes.
