### ISSUE TITLE
Core: Aztec decoding fails for large symbols unless pixel-perfect

### ISSUE THREAD

**Issue by fgrieu** [zxing/zxing#646]
Scanning any Aztec code larger than approximately 67x67 with a mobile phone running BarcodeScanner-4.7.5.apk is very difficult in my experience, becoming entirely infeasible at 91x91 (or more); when NeoReader on the same mobile phone (Galaxy S6) scans these with great ease, 

The problem lies in ZXing core. It is repeatable on test images of excellent visual quality. At size 91x91, ZXing (e.g. as of [here](https://zxing.org/w/decode.jspx)) fails to detect Aztec codes in images that are even so slightly imperfect. For example the following detailed but slightly blurred image of a 91x91 code
![blurred91](https://cloud.githubusercontent.com/assets/7809433/17367222/74d267c6-598f-11e6-89ee-6ad673583228.png)

The above image was obtained by digitally stretching the pixel-perfect image below, which is detectable by ZXing when processing the file directly
![pass91](https://cloud.githubusercontent.com/assets/7809433/17367350/eb7b0e6e-598f-11e6-954a-cecf5dcb0a01.png)

There's the same problem with this 0.1 degree rotation of the pixel-perfect image
![rotated](https://cloud.githubusercontent.com/assets/7809433/17390313/486cd478-5a0c-11e6-9118-7bf002ac8e00.png)

I conclude improvement is much needed in com.google.zxing.aztec.detector (or what it uses), but have not any clue about what, or how to make progress. Any idea?

**Comment by srowen** [comment]
Yeah this is probably true. I am not actually familiar with how that works (didn't write it) but wouldn't be surprised if it's the limiting factor for detection.  I'd welcome changes that improve performance and don't make it much more complex.

**Comment by fgrieu** [comment]
Is this bug closed because it was fixed, or from some other reason?
Right, now, the online decoder [online decoder](https://zxing.org/w/decode.jspx) is still unable to decode either of these two test images: [even-so-slightly-blurred](https://cloud.githubusercontent.com/assets/7809433/17367222/74d267c6-598f-11e6-89ee-6ad673583228.png) [(pixel-perfect-with-0.1-degree-rotation)](https://cloud.githubusercontent.com/assets/7809433/17390313/486cd478-5a0c-11e6-9118-7bf002ac8e00.png).
