### ISSUE TITLE
Error to encode to non printable character with Code 128

### ISSUE THREAD

**Issue by Flattron** [zxing/zxing#649]
Bugs Report:
When we encode the ASCII for no printable character with Code128, it throw the exception for unsupported character . but the Code 128 support full ASCII character . We test the ASCII , now only support from SPACE（Hex20，Dec32）. The character from 0 to hex(1F) are not support . 
Code Sample like following :
BitMatrix matrix = new MultiFormatWriter().encode((char)2 + "XXX" + (char)3, BarcodeFormat.CODE_128, 1000, 400);

Please fix this bug .

**Comment by srowen** [comment]
Yeah I believe you're correct. I don't know much about Code 128 myself, but the format info seems to say ASCII 0 is encodable but the code rejects it. I wouldn't be able to work on it, but feel free to explore fixing it and submit a PR if you make good progress.

**Comment by Flattron** [comment]
Thanks,Srowen. We are company to develope barcode scanner and we have many setting barcode have no printable barcode to set the scan engine to different function .  we want to make these setting barcode as on-screen barcode to let the scan engine to read them to achieve some different function . We have encode QRCode for these no-printable character , that all OK．This moment ,we need 1D setting barcode for no printable character .

**Comment by srowen** [comment]
@Flattron yes I'm suggesting you prepare a fix if you are interested in resolving this.

**Comment by 8804645769** [comment]
Remove error please

**Comment by 8804645769** [comment]
Thanks

**Comment by jabiragd** [comment]
unable to read 1000 character 2d barcodes , please any one help me
