### ISSUE TITLE
Not recognized QR code

### ISSUE THREAD

**Issue by piotrwendykier** [zxing/zxing#656]
The QR code in the attached file is not recognized by ZXing Decoder Online.
![barcode](https://cloud.githubusercontent.com/assets/21197899/17932105/c3d1eb96-6a0e-11e6-8437-1d7bfd473608.png)

**Comment by srowen** [comment]
I tried other libraries and they also don't decode it. zxing says it fails the error correction routine, so maybe the encoding is wrong?

**Comment by janleeyu** [comment]
I tried scanner this with the QR reader I downloaded and it gave me this text value : 

> QPVeg

**Comment by tengfangjiang** [comment]
The result ：
`QPVeg`

**Comment by srowen** [comment]
Hm, is this a QR code from the old pre 2005 spec? it doesn't seem to have the right alternating bit pattern that the modern spec mandates around the top-right pattern.
