### ISSUE TITLE
Interleaved 2 of 5 - getting incorrect reads

### ISSUE THREAD

**Issue by undsoft** [zxing/zxing#658]
Hi,

I'm experimenting with ITF codes, however the scanner is not always accurate.
For example, I have use barcode-generator.org to generate code for 10101010.
When I scan it though, sometimes it scans as 76767676 and sometimes as 13131313.
It may scan incorrectly once in 10 scans. Samsung Galaxy s5, default example project.

How can I improve the accuracy of scanning?

**Comment by srowen** [comment]
ITF has no checksum IIRC, so it's easy to get false reads. This is why the possible lengths it will return is limited, and you can ask it to ignore anything but a read of a certain length if you know it ahead of time to avoid this. It's not really a bug, in the sense that it's always possible to see a phantom barcode, and this format is particularly prone to it.
