### ISSUE TITLE
 java.util.zip.ZipException: duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class

### ISSUE THREAD

**Issue by yasaman93** [zxing/zxing#662]
I got this error when I want to build signed apk!

Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'. > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class

**Comment by srowen** [comment]
This sounds like an error from your own build, since it doesn't happen for this project's. The error pretty much means what it says, as you somehow included a library twice.

**Comment by chaozaiai** [comment]
@srowen 
there  are two library, which named library1 and library2.  library1 contain the  compile 'com.google.zxing:core:3.2.1'  library2 contain compile 'me.dm7.barcodescanner:zxing:1.9'. 
but the library which name is 'me.dm7.barcodescanner:zxing:1.9' contain the com.google.zxing  too.
project use library1 and library2 ,when i gradle assembleRelease the project, log the follow error:
   * What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException                                  : duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class

do you have some method to fix this problem?

**Comment by awlodarczyk** [comment]
fix Your gradle file like below:

 `compile ('me.dm7.barcodescanner:zxing:1.9'){ `
 `        exclude group: 'com.google.zxing', module: 'core' `
  `   }`

**Comment by rizkitroy** [comment]
how to fix that problem?? i can't fix that problem

_duplicate entries com/google/zxing/aztec/Aztec DetectorResult.class_

**Comment by chaozaiai** [comment]
@rizkitroy  
there are duplicate AztecDetectorResult.class  in at least two libraries, find them.
then you should use these code below  if you use android studio.

compile(contain com.google.zxing library) {
        exclude group: 'com.google.zxing'
  }

**Comment by JamesBuretta** [comment]
@chaozaiai 

Thanks alot for the solution , it worked very well.

  compile ('com.journeyapps:zxing-android-embedded:3.4.0'){
        exclude group: 'com.google.zxing'
    }

**Comment by geomensione** [comment]
@chaozaiai 
 I've a similar problem, the output is:

Error:Execution failed for task ':transformClassesWithJarMergingForArmv7Debug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/BarcodeFormat.class

How can I find duplicate class? And where I have to put the suggested code?
I'm using Android Studio,

Regards,
Michele

**Comment by zayn1991** [comment]
@chaozaiai @yasaman93 
i had

```
compile files('libs/zxing_core.jar')
compile 'me.dm7.barcodescanner:zxing:1.9.8'
```

but i solved this by

```
compile files('libs/zxing_core.jar')
 compile ('me.dm7.barcodescanner:zxing:1.9.8'){
        exclude group: 'com.google.zxing'
}
```

**Comment by mksantoki** [comment]
I getting same error

`Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class`

I solved this issue by

` compile ('com.facebook.android:facebook-android-sdk:4.+'){
        exclude group: 'com.google.zxing'
    }`

I hope this helps you.

**Comment by ipehimanshu** [comment]
we are using phonegap build site to create build 

Here is our config 

`<preference name="phonegap-version" value="cli-7.0.1" />`

and we use below plugins 

`<plugin name="cordova-plugin-facebook4" spec="^1.9.1" source="npm">
        <variable name="APP_ID" value="xxxxxxxxxxxxxx" />
        <variable name="APP_NAME" value="xxxxxxxxxx" />
    </plugin>`

	`<plugin name="cordova-android-support-gradle-release" spec="0.0.2" source="npm">
        <variable name="ANDROID_SUPPORT_VERSION" value="25.+" />
    </plugin>`

	`<plugin name="phonegap-plugin-barcodescanner" spec="6.0.8" source="npm">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="To scan barcodes." />
    </plugin>`

	`<plugin spec="https://github.com/NazarKozak/cordova-plugin-multidex.git" source="git" />`


We get this type error 

from phonegap build url 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class


So any one please help me to resolve this issue ?

**Comment by damorus85** [comment]
@mksantoki I have the same error as you, but with BarcodeFormat.class instead of the AztecDetectorResult.class. 

In my gradle I have this line:

`compile "com.facebook.android:facebook-android-sdk:4.+"`

Changed as you said to this:

`compile ('com.facebook.android:facebook-android-sdk:4.+'){ exclude group: 'com.google.zxing' }`

As I tried building it again I got the same error and the code in my gradle or reverted BACK to:

`compile "com.facebook.android:facebook-android-sdk:4.+"`

Do you or anyone know why that happens?

**Comment by srowen** [comment]
All: this has nothing to do with this project. It's a discussion for another forum.

**Comment by mksantoki** [comment]
@damorus85 Hi
-I think issue is in your project have same library two time  with different version. So first you require to find which library conflict.
-Can you please post your error log here so understand is easy and find solution for you.

**Comment by hAz4rd0uS** [comment]
Hi,

Where am I supposed to put the code please ? 
I'm on cordova and I have cordova-plugin-facebook4 and cordova-plugin-barcodescanner.

Please help, it blocks me from building API 21- compatible android apps !
