### ISSUE TITLE
Android can not scan simple QR Code

### ISSUE THREAD

**Issue by leoaran** [zxing/zxing#663]
### Bug Reports

hi, my QR Code is quite simple and when I use zxing to scan it, it is always failed or needs a long time to  be recognized,  Is it an internal problem of zxing or could you tell me how to improve it, thks.
following is my test qrcode, it contains a lot of numbers:
https://cloud.githubusercontent.com/assets/3714307/18113338/8193c6d4-6f61-11e6-9c73-44a88a136dbb.png

![qrcode](https://cloud.githubusercontent.com/assets/3714307/18113338/8193c6d4-6f61-11e6-9c73-44a88a136dbb.png)

**Comment by leoaran** [comment]
![Uploading image.png…]()

**Comment by srowen** [comment]
This is an invalid QR code. Look at the trimmed edges. It may eventually be scanned, but that's the problem.

**Comment by leoaran** [comment]
hi, srowen, but other tools do recognize it

**Comment by leoaran** [comment]
thank you,Owen!But is there some possibility to improve it? I have tried some other apps, they do recognize my QR code From lily
            在2016年08月31日 20:49，Sean Owen 写道:This is an invalid QR code. Look at the trimmed edges. It may eventually be scanned, but that's the problem.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zxing/zxing","title":"zxing/zxing","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zxing/zxing"}},"updates":{"snippets":[{"icon":"PERSON","message":"@srowen in #663: This is an invalid QR code. Look at the trimmed edges. It may eventually be scanned, but that's the problem."}],"action":{"name":"View Issue","url":"https://github.com/zxing/zxing/issues/663#issuecomment-243752945"}}}

**Comment by laiying** [comment]
> ### Bug Reports
> hi, my QR Code is quite simple and when I use zxing to scan it, it is always failed or needs a long time to be recognized, Is it an internal problem of zxing or could you tell me how to improve it, thks.
> following is my test qrcode, it contains a lot of numbers:
> https://cloud.githubusercontent.com/assets/3714307/18113338/8193c6d4-6f61-11e6-9c73-44a88a136dbb.png
> 
> ![qrcode](https://cloud.githubusercontent.com/assets/3714307/18113338/8193c6d4-6f61-11e6-9c73-44a88a136dbb.png)

Your QRCode scan result:01110303800000010，This has happened to me， my solutions in version zxing-core 3.3.0：
At class FinderPatternFinder.java,find foundPatternCross() method,
edit:
protected static boolean foundPatternCross(int[] stateCount) {
    int totalModuleSize = 0;
    for (int i = 0; i < 5; i++) {
      int count = stateCount[i];
      if (count == 0) {
        return false;
      }
      totalModuleSize += count;
    }
    if (totalModuleSize < 7) {
      return false;
    }
    float moduleSize = totalModuleSize / 7.0f;
    float maxVariance = moduleSize / 2.0f;
    // Allow less than 50% variance from 1-1-3-1-1 proportions
    return Math.abs(moduleSize - stateCount[1]) < maxVariance &&
            Math.abs(3.0f * moduleSize - stateCount[2]) < 3 * maxVariance &&
            Math.abs(moduleSize - stateCount[3]) < maxVariance;
    /*return
        Math.abs(moduleSize - stateCount[0]) < maxVariance &&
        Math.abs(moduleSize - stateCount[1]) < maxVariance &&
        Math.abs(3.0f * moduleSize - stateCount[2]) < 3 * maxVariance &&
        Math.abs(moduleSize - stateCount[3]) < maxVariance &&
        Math.abs(moduleSize - stateCount[4]) < maxVariance;*/
  }
finally, the reason was QRCode image location box defected,The source recognize by 1:1:3:1:1,We changed it to 1:3:1

**Comment by srowen** [comment]
Yes, that QR code is not quite valid. Looks like it's missing some of the module width around the edge. I think you instead need to fix the QR codes if you can.
