### ISSUE TITLE
4x4 and 6x6 Data Matrix

### ISSUE THREAD

**Issue by MrBlockenpfeffer** [zxing/zxing#667]
It seems the _MultiFormatReader_ is not able to decode a square 4x4 or 6x6 DataMatrix. The function _decodeInternal(BinaryBitmap image)_ will return a _NotFoundException_ while using the attached DataMatrix Code. 

As I have debugged it it seems that the Dimensions of "code dots" are correct (80x80) and the detection of the code just works fine. So I think there is a problem with the class _DataMatrixReader_ at the function _public Result _decode(BinaryBitmap image, Map<DecodeHintType,?> hints)_. The overhanded _hints_ are _null_.

I have tried decoding it with Android App and the J2se Client with the same Result.

![test4x4](https://cloud.githubusercontent.com/assets/22150591/18505019/7c93baea-7a65-11e6-8d57-8d54195d4a83.png)

**Comment by srowen** [comment]
Yeah it doesn't like part of the encoding. It decodes fine up until a bit that starts "Acetylsalicyls"; is the word "Acetylsalicylsäure"? There's an upper shift followed by change to Shift 3, and then the codeword "2".

I read the spec, and it's kind of confusing about what's supposed to happen. Clearly the barcode is trying to encode the code point '132' which is 'ä' in extended ASCII. The spec refers to "extended ASCII" repeatedly, but says that code points > 127 are interpreted "as in ISO 8859 1". The code point of 'ä' in ISO 8859 1 is 228 though. In addition, I would expect code point 132 to be encoded as 3, not 2, given what I can understand of the rules.

I know that the existing tests do _not_ cover this decoder path, so it's possible it doesn't implement the spec correctly. 

Can you confirm the contents, and, how sure are you about the encoding?

**Comment by MrBlockenpfeffer** [comment]
Thanks for reapeating so fast. I have mixed up the encoding and did not notice that the value of ä was wrong. It works now as expected.

**Comment by srowen** [comment]
OK, I should say I'm not clear the decoder is correct here; I don't know for sure. If you're pretty sure the encoding was wrong, OK.

**Comment by mboeddeker** [comment]
Please check Ü ü Ö ö also
