### ISSUE TITLE
suggestions for building aar library

### ISSUE THREAD

**Issue by lawrence200801** [zxing/zxing#669]
EncodeActivity.java: OnOptionItemSelected
CaptureActivity.java: OnOptionItemSelected
EncodeHandler.java: handleMessage
CaptureActivityHandler.java: handleMessage

'switch' statement should be replaced by 'if else' statement when build aar library. The resource ID in aar library is dynamically generated.

**Comment by srowen** [comment]
It's not a library though, it's an app.
