### ISSUE TITLE
bug: TRANSLATED_HELP_ASSET_LANGUAGES

### ISSUE THREAD

**Issue by lawrence200801** [zxing/zxing#670]
### Bug Reports
com/google/zxing/client/android/LocaleManager.java:
Line 107,108

Must be written like this:

private static final Collection<String> TRANSLATED_HELP_ASSET_LANGUAGES =
      Arrays.asList("de", "en", "es", "fr", "it", "ja", "ko", "nl", "pt", "ru", "uk", "zh-CN", "zh-TW", "zh-HK");

**Comment by srowen** [comment]
@lawrence200801 I can't tell what change you're suggesting, or why. The code is fine. You've removed the generic type, which is not correct.
