### ISSUE TITLE
Cant add own parameters in WEB app

### ISSUE THREAD

**Issue by iiilja** [zxing/zxing#672]
Tryinng to add myParam to ret link.
'zxing://scan/?ret=' + location + '?code={CODE}&myParam=' + myParam+ 'SCAN_FORMATS=UPC_A,EAN_13,CODE_93,ITF,CODE_128,CODE_39,EAN_8'
Result is location + '?code={CODE}
If I put myParam first, code will not be present.
Using android app ver. 4.7.6

**Comment by srowen** [comment]
Not clear what you mean, but you seem to be reporting a problem in how you construct your URL.

**Comment by iiilja** [comment]
Maybe You could help me then. 
URL is 'zxing://scan/?ret=www.mywebapp.com?code={CODE}&myParam=12345&SCAN_FORMATS=UPC_A,EAN_13,CODE_93,ITF,CODE_128,CODE_39,EAN_8'
After code scanning application returns me to 
www.mywebapp.com?code=code
but it should return me to
www.mywebapp.com?code=code&myParam=12345
How can I achieve that result ?
