### ISSUE TITLE
Camera2 API Integration In Android Sample Project

### ISSUE THREAD

**Issue by dibakarece** [zxing/zxing#675]
Hi Srowen,
Thanks :) for your awesome 'zxing core lib' and 'android sample app'. As you know that new Camera2 API is updated instate of Camera. So, in your sample app the camera object showing deprecated in 24 API level. I'm trying to integrate Camera API 2 in your sample android app code, but unfortunately failed each time.Can you give me a hint or may you create a new sample app using Camera2 API .

**Comment by srowen** [comment]
The app supports Android 4, so can't use Camera2. This isn't a sample app that you're intended to use, but the real live Barcode Scanner app. It's your app and I'm afraid you have to investigate Camera2 if you want to use it. This isn't the place to ask.

**Comment by dibakarece** [comment]
Hi Srowen, 
I'm really sorry for my comment. I want some flavor from you that is it possible to change the old camera API to the new camera API. I know that you already mentioned that it support android 4 so we can't use Camera2. If we build for above to lollipop then what will be the requirement.
