### ISSUE TITLE
Various small encoding improvements

### ISSUE THREAD

**Issue by srowen** [zxing/zxing#679]
A couple related improvements from https://groups.google.com/forum/#!topic/zxing/iCODr5bZKHk

- UPC-E, EAN-13 and EAN-8 writers should add check digit if not present, like UPC-A does.
- They should all check the check digit if provided and reject the barcode if it fails
- The default margin for UPC/EAN barcodes should never result in a margin less than the mandated 9 modules
- Experiment with less tolerance of small quiet zones

**Comment by YurySk** [comment]
Sean, I took a (very) quick look at your changes. It may very well be that I am not seeing things right, but I just wanted to make sure.

UPC-E checksum is not the same as an application of UPC-A algorithm over a shorter string of data, but rather requires non-intuitive UPC-E->UPC-A conversion (see the table at https://en.wikipedia.org/wiki/Universal_Product_Code#UPC-E) and then an application of a UPC-A calculation over it. To achieve that, I would imagine a code similar to com.google.zxing.oned.UPCEReader.convertUPCEtoUPCA should appear somewhere in the picture. I am not sure I caught that anywhere, but again, I am not super-familiar with zxing code.

**Comment by srowen** [comment]
I think you're right, although it may weirdly be true that it works out the same. I will push a fix that more explicitly makes the UPC-E into UPC-A and then gets the check digit. (I should also enforce the first digit being 0 or 1.) EAN-8 does have a check digit computed directly in the same way as EAN-13 but that's not quite the same.

**Comment by YurySk** [comment]
Great stuff, thanks!

**Comment by YurySk** [comment]
There's a similar issue with DATA_MATRIX, it needs a quiet zone of one X-dimension to be readable...
