### ISSUE TITLE
When 'No automatic rotation' is on, camera stops working

### ISSUE THREAD

**Issue by BS987** [zxing/zxing#682]
When 'No automatic rotation' is on or off, screen not rotated when we change the orientation. In short, there is no effect whether it is on or off. Second thing, when 'No automatic rotation' is on while screen is in landscape mode, lock the device, then change to portrait and unlock your device. The screen is rotated to portrait but there is no preview and whole screen is converted to black. After you change rotation to any mode then there is no any effect or change in orientation. So what is the exact use of 'No automatic rotation' ? I think it is not working.

**Comment by srowen** [comment]
I can't reproduce any of that on my phone. It could be a device problem. I also don't in general have any crash reports from the app recently.

**Comment by BS987** [comment]
@srowen, Actually it happens less frequently, if you test for so many time, then you can face this issue. If you again send app to background and again bring it to front then it again works.

Anyways, what is the use of that setting option ? I don't find any difference whether it is on or off ?

**Comment by srowen** [comment]
If set, then the display won't rotate if you turn the camera 180 degrees over. That might be desirable if you're moving the device around a lot to scan.
