### ISSUE TITLE
QR decode result is null in nexus(android 7.0)

### ISSUE THREAD

**Issue by guoGavin** [zxing/zxing#685]
In the same code, some device is sucess, however, in nexux(7.0) device, result is null. why?
By debug, MultiFormatReader.decodeWithState(...) result is null.
What should I do?

**Comment by guoGavin** [comment]
Core code：
-----------------------------------------------------------------------------------------------------------------

protected String doInBackground(Void... params) {
        Camera.Parameters parameters = mCamera.getParameters();
        Camera.Size size = parameters.getPreviewSize();
        int width = size.width;
        int height = size.height;
        byte[] rotatedData = new byte[mData.length];
        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                rotatedData[x * height + height - y - 1] = mData[x + y * width];
            }
        }
        int tmp = width;
        width = height;
        height = tmp;
        try {
            if (mDelegate == null) {
                return null;
            }
            return mDelegate.processData(rotatedData, width, height);
        } catch (Exception e) {
            return null;
        }
    }

------------------------------------------------------------------------------------------------------------

    public String processData(byte[] data, int width, int height) {
        String result = null;
        Result rawResult = null;
        try {
            PlanarYUVLuminanceSource source = null;
            Rect rect = mScanBoxView.getScanBoxAreaRect(height);
            if (rect != null) {
                source = new PlanarYUVLuminanceSource(data, width, height, rect.left, rect.top, rect.width(), rect.height(), false);
            } else {
                source = new PlanarYUVLuminanceSource(data, width, height, 0, 0, width, height, false);
            }
            rawResult = mMultiFormatReader.decodeWithState(new BinaryBitmap(new HybridBinarizer(source)));
        } catch (Exception e) {
        } finally {
            mMultiFormatReader.reset();
        }
        if (rawResult != null) {
            result = rawResult.getText();
        }
        return result;
    }

**Comment by srowen** [comment]
I have a Nexus 6P with Android 7 and have no problem. You're really asking about your own code, and you'd have to debug that.
