### ISSUE TITLE
Unable to scan barcode unknown / unsupported format

### ISSUE THREAD

**Issue by mikeloeven** [zxing/zxing#686]
For some reason the app will not register this barcode format

![20161018_024757](https://cloud.githubusercontent.com/assets/2266606/19467180/c7944f36-94dd-11e6-86c0-044bcb92b0ac.jpg)

**Comment by mikeloeven** [comment]
![20161018_024735](https://cloud.githubusercontent.com/assets/2266606/19467212/f33f8286-94dd-11e6-94c9-7721bb7a10cb.jpg)

**Comment by srowen** [comment]
It seems like Code 128 which is supported. However it can be hard to scan off the screen especially when the bars are quite thin. I think that may just be the issue; I don't know if there's any step that someone would action here in the project.

**Comment by mikeloeven** [comment]
After seeing your reply I printed out the barcode and tried scanning it again it still did not register
