### ISSUE TITLE
ZXing not recognise Barcode

### ISSUE THREAD

**Issue by amaiaespinosa** [zxing/zxing#687]
Hi,

I am trying to use Zxing with an static photo. I want to read some barcode in 128 and ITF in Unity. I capture the region of the image in which the barcode is in, and the zxing doesn't work.

I am using the library with QR and it works so good. If i use my barcodes in a real time video, sometimes zxing works, but the process is so low.

Could you tell me why this happend? Is someway of selected the type of code? because i know the type of the barcode.

Please could you help me?

**Comment by srowen** [comment]
Impossible to say without any detail.

**Comment by amaiaespinosa** [comment]
![image](https://cloud.githubusercontent.com/assets/17545339/19478824/4eac08cc-9544-11e6-9586-ae440941cbf4.png)

This is the barcode i am trying to read. But zxing reads nothing.
