### ISSUE TITLE
128 code not read

### ISSUE THREAD

**Issue by amaiaespinosa** [zxing/zxing#688]
Hi,

I am trying to use Zxing with an static photo. I want to read some barcode in 128 and ITF in Unity. I capture the region of the image in which the barcode is in.
With the barcodes i need to read, this doesn't work.

![codbarras](https://cloud.githubusercontent.com/assets/17545339/19511466/9cbe1d54-95e7-11e6-8dd3-d432b31b40a6.png)

If i try to read another barcodes like this;

![cod1](https://cloud.githubusercontent.com/assets/17545339/19511486/b65e9130-95e7-11e6-9328-f77f52acabd1.jpg)

Works so good.

I am using the library with QR and it works so good. If i use my barcodes in a real time video, sometimes zxing works, but the process is so low.

Could you tell me why this happend? Is someway of selected the type of code? because i know the type of the barcode. The barcode is in code 128.

Please could you help me?

**Comment by srowen** [comment]
Try a little bit of blur / low pass filter to smooth out the noise. Otherwise it's not really a library problem. There will always be things that don't scan.
