### ISSUE TITLE
launch failed on api 23 but ok on 4.4

### ISSUE THREAD

**Issue by Lihengju1990** [zxing/zxing#690]
Hi
I have a problem.
I copy all the class files and resource files in android&core package(include permission).but when i launch the app,it takes some mistakes.

E/Camera-JNI: android_hardware_Camera_native_setup Error: -1 
E/Camera: Camera new cameraInitNormal:-1 
it launch on huawei MLA-AL00(android 6.0 api 23), on xiaomi 5(android 6.0.1 api 23),it takes other mistake.

E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/MediaPlayer: error (1, -2147483648)

but on another phone(android 4.4),it's ok.

**Comment by srowen** [comment]
I am able to run the app fine on Android up to 7.1. You seem to be asking about your app.
