### ISSUE TITLE
Unable to decode multiple QRCode in a single page 

### ISSUE THREAD

**Issue by tarun14691** [zxing/zxing#694]
I am trying to decode multiple QR codes in a single page. Where 2 QR codes exists. But i am getting only one result "BARCODE_XBES5FCPBE". 
this is my image:

![image barcode4](https://cloud.githubusercontent.com/assets/3948440/19674427/c0bf6e34-9aa5-11e6-823c-517c3e869b13.jpg)

and my code : 

```
List<String> resultList = new ArrayList<>();
        try {
            LuminanceSource source = new BufferedImageLuminanceSource(bufferedImage);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
            Hashtable<DecodeHintType, Object> hints = new Hashtable<DecodeHintType, Object>();
            hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
            hints.put(DecodeHintType.PURE_BARCODE, Boolean.FALSE);
            QRCodeMultiReader reader = new QRCodeMultiReader();
            Result[] results = reader.decodeMultiple(bitmap);
            for (int i = 0; i < results.length; i++) {
                resultList.add(results[i].getText());
            }
        } catch (NotFoundException nf){
            //Do nothing. It is just to avoid exception while
            // parsing multiple images maybe without barcodes
        } catch (Exception ex) {
            throw ex;
        } finally {
            return resultList;
        }
```

Both the barcodes are of different size.
Final result should be : 
1. BARCODE_XBES5FCPBE
2. BARCODE_ALKYSOTIQ8

**Comment by srowen** [comment]
You will definitely have to remove PURE_BARCODE mode. Does it work then?

**Comment by tarun14691** [comment]
Nope. I have removed PURE_BARCODE mode.

**Comment by srowen** [comment]
Not sure, it's not guaranteed to work given its heuristic. You could investigate what it finds with a debugger and perhaps devise a better strategy.

**Comment by srowen** [comment]
Oh I also noticed that the second barcode doesn't really have enough margin, but, I don't know if that's the problem. Reopen if you want to open a pull request that can get this case right and get all the tests currently in the project right too.

**Comment by xzessmedia** [comment]
same here...
why did you close this, 1 month after the guy asked the question?
thanks for open source but you are closing far to fast which is not very serious!

**Comment by srowen** [comment]
@xzessmedia please take any look at this projects site. It has not been active for years.
