### ISSUE TITLE
zxing.appspot.com/scan contains mixed content

### ISSUE THREAD

**Issue by rezxv** [zxing/zxing#705]
When I clicked on the "or enter code manually" link, I got no response (i.e., not prompted, not redirected). When I looked at the browser's console, it says that there are blocked contents because they are served with http (instead of https). The contents are Jquery and the Droid Sans font. I'm using Mozilla Firefox 49.0.2. It seems that Firefox is, by default, blocking active contents served through http pulled from https page.

**Comment by srowen** [comment]
What are you referring to? I don't believe anything in the web app uses jquery or a custom font.
