### ISSUE TITLE
scan not saved to clipboard in bulk scanning mode

### ISSUE THREAD

**Issue by fluffymcdeath** [zxing/zxing#707]
When save to clipboard is selected in settings it is ignored in bulk scanning mode.

While it might seem that saving to clipboard is silly during bulk scanning, if the user has requested it in the settings it should be honoured. I have a genuine need of this and expected it to work.

**Comment by fluffymcdeath** [comment]
Looks like this patch is all that's required:

index e4d9cb1..4e23c72 100755
--- a/android/src/com/google/zxing/client/android/CaptureActivity.java
+++ b/android/src/com/google/zxing/client/android/CaptureActivity.java
@@ -449,6 +449,9 @@ public final class CaptureActivity extends Activity implements SurfaceHolder.Cal
     boolean fromLiveScan = barcode != null;
     if (fromLiveScan) {
       historyManager.addHistoryItem(rawResult, resultHandler);
+      if (copyToClipboard && !resultHandler.areContentsSecure()) {
+        ClipboardInterface.setText(displayContents, this);
+      }
       // Then not from history, so beep/vibrate and we have an image to draw on
       beepManager.playBeepSoundAndVibrate();
       drawResultPoints(barcode, scaleFactor, rawResult);

**Comment by srowen** [comment]
Yes you're right, and I agree it should not behave differently in this path. I'll push a slightly different change to achieve a similar result.
