### ISSUE TITLE
Problem with ZXing on iOS 10.1 (Xamarin)

### ISSUE THREAD

**Issue by Cyber1000** [zxing/zxing#709]
Hi,

We are having some troubles with ZXIng on IOs 10.1. 
On scanning we are getting this (we are using xamarin) while it crashes:

Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

Here is a fix (at the end of the thread - in code of zxing - ZXingscannerview.cs), but I don't understand why this could fix the problem. Do you have a better fix?
https://forums.xamarin.com/discussion/77721/zxingscannerview-does-not-work-anymore-in-ios-10?

Thanks,
Cyber1000

**Comment by srowen** [comment]
This code is long since not in the project.
