### ISSUE TITLE
Scanning from web page - invalid or local URL

### ISSUE THREAD

**Issue by joshilewis** [zxing/zxing#71]
HI, Thanks for a brilliant product!
I've noticed in my development and testing, that certain return URLs don't work when scanning from a web page. Also, there's no indication that the URL is invalid, all that happens is that the barcode app never returns to the web browser. 

If I use the complete URL, of either my full site (http://foo.com/add/{CODE}) or my dev machine (http://192.168.2.5/add/{CODE{), it works fine. However, if I use a 'partial' URL, like '/add/{CODE}' or '~/add/{CODE}, the app scans fine, but never returns to the web browser.

**Comment by erumhannan** [comment]
@joshilewis  can u tell me how u resolved this issue ? i have resolved the full url isue but failed to scan from url ?

**Comment by marmar44** [comment]
On 5 Feb 2015 15:12, "erumhannan" <notifications@github.com> wrote:
>
> @joshilewis can u tell me how u resolved this issue ? i have resolved the
full url isue but failed to scan from url ?

**Comment by erumhannan** [comment]
@marmar44  can u tell me how u scanned from url i m just facing issue in this ?
