### ISSUE TITLE
Bad links in about page

### ISSUE THREAD

**Issue by Snipx** [zxing/zxing#711]
On this About page: https://zxing.github.io/zxing/ every link under the Project Modules title I click lead to 404 page.

You might want to fix that.
Regards,
Alexey

**Comment by srowen** [comment]
Here? https://zxing.github.io/zxing/index.html
Yeah there is no submodule documentation generated; there's nothing to see there anyway.
I am not sure this can be disabled in the mvn site plugin though. I just tried removing the 'index' module and it still generates "About". It's not great but I don't know how to turn it off; let me know if you do.
