### ISSUE TITLE
DataMatrix decoder is horizontal position sensitive

### ISSUE THREAD

**Issue by ecolner** [zxing/zxing#714]
We have two samples here. The first is the original image that fails. The second image is nudged 10px to the left along the x-axis with no other modifications and it passes. Can somebody on the team explain whether this is expected behavior or a bug and how to deal with this?

These samples were tested using the ZXing Decoder Online tool
https://zxing.org/w/decode.jspx

original image **FAIL**
![chip_1_1479511257810](https://cloud.githubusercontent.com/assets/1624780/20540464/2b1a203a-b0ae-11e6-97e0-bf058bd7fba1.png)

10px nudged left **PASS**
![chip_1_1479511257810 10px left](https://cloud.githubusercontent.com/assets/1624780/20540526/50ec85fa-b0ae-11e6-882b-34568c3dad02.png)

**Comment by srowen** [comment]
Yeah, it's just one of those cases where the heuristics get it wrong. It doesn't find the corner correctly in the first image because of how it happens to search. The idea is that in the context of a phone this won't matter because the next frame probably decodes. If you have a suggestion that improves the heuristic without causing more failures than it saves, open a PR, otherwise I'd close this.

**Comment by ecolner** [comment]
My approach so far has been to crop the image sent to the decoder around the center of the barcode rather than sweeping it across the entire width (which I'm actively trying to avoid). I use a 20px all-white border which seems to help the detector along.

**Comment by ecolner** [comment]
I think I see what's going on with this barcode. The WhiteRectangleDetector finds the segment in the center and gives up because it is surrounded by white... My fix would be to check if all the bits are set within the located segment and if so continue searching for the corners.

pointA = {ResultPoint@2105} "(307.0,215.0)"
pointB = {ResultPoint@2108} "(308.0,271.0)"
pointC = {ResultPoint@2107} "(329.0,214.0)"
pointD = {ResultPoint@2109} "(332.0,271.0)"

**Comment by srowen** [comment]
Aha, yeah, it happens to find this region when searching outwards from the center. The region no longer contains the image center though when shifted a bit. You could imagine non-continuous regions in the middle that cause the same problem. It's hard to know when it's a false positive.
