### ISSUE TITLE
QR code detection failed

### ISSUE THREAD

**Issue by Vort** [zxing/zxing#715]
Hello.

I was trying to get data from QR code, which was photographed from pack of sugar.
But the website at https://zxing.org/w/decode.jspx was failed to recognize it ("No Barcode Found").

The data was extracted with another services, but maybe this photo can help to improve this software:

![qr](https://cloud.githubusercontent.com/assets/1242858/20599824/0dcdcb74-b259-11e6-907c-359f2ef8b24d.png)

**Comment by srowen** [comment]
Yeah, not every image is going to decode. This one has a little trouble because the white areas are kind of dark, and there is some bleed at the edge of the blue areas. You may find that small variations on this image work fine.

**Comment by Vort** [comment]
Next attempt was with scanner.
Distortions and contrast problems was eliminated.
So looks like the color bleed is the main problem.

Here is another source and its 1 bpp conversion.
The converted picture is decoded fine.
Thanks.

*(It would be great if at some point software will be able to revert most popular distortions and decode everything that can be decoded by human brain)*

![qr2](https://cloud.githubusercontent.com/assets/1242858/20602514/3ca48b7e-b266-11e6-8cdf-af7bb5789ad8.png)
![qr2_bw](https://cloud.githubusercontent.com/assets/1242858/20602528/59a60b62-b266-11e6-9f7a-0606d8bffca8.png)
