### ISSUE TITLE
CODE_128 throws IllegalArgumentException when encoding control characters

### ISSUE THREAD

**Issue by dmyersturnbull** [zxing/zxing#716]
[CODE 128](https://en.wikipedia.org/wiki/Code_128) encodes all characters in ASCII between Unicode code points 0 and 127, inclusive.
However, this fails for all characters u0000 to u0019, inclusive:

```java
MultiFormatWriter().encode('\u0000', BarcodeFormat.CODE_128, width, height, null)
```

**Comment by srowen** [comment]
Looks like the same as https://github.com/zxing/zxing/issues/649 -- same story, you'd have to suggest a fix

**Comment by dmyersturnbull** [comment]
Got it! Sorry I missed the duplicate.
