### ISSUE TITLE
everything with dots read as urls

### ISSUE THREAD

**Issue by kilroythe5th** [zxing/zxing#721]
could someone please make this app not think everything with a period in it is a url? It's not quite a bug, but if it's going to interpret it as such, there really is no reason to slap an "http://" to the front of it, because browserd do a perfectly good job of that themselves.

**Comment by srowen** [comment]
It's really a function of Android linkifying the text. It's too generally useful to disable. Otherwise scanning "google.com" results in something you can't just tap.
