### ISSUE TITLE
How to scan invert qr code?

### ISSUE THREAD

**Issue by davidjonker** [zxing/zxing#724]
I'm using this great library to scan QR codes and it works perfect.
Btw when I want to scan color invert QR codes, it doesn't work.
Here's a link to QR code image.
http://prnt.sc/dijmc8

Here's my code.
        mScannerView = new ZXingScannerView(this);   // Programmatically initialize the scanner view
        setContentView(mScannerView);

        mScannerView.setResultHandler(this); // Register ourselves as a handler for scan results.
        mScannerView.startCamera();         // Start camera

Am I doing something wrong or Do I have to add additional codes on your library?
I'm looking for any help.

Thanks.

**Comment by srowen** [comment]
You have to invert the image to scan it. You can do it in your application and you can see how the app in this project does it.
