### ISSUE TITLE
Can't decode..

### ISSUE THREAD

**Issue by atypicalprogrammer** [zxing/zxing#726]
The image below can't be decoded by zxing, but can by other decoders. Can anyone tell me what the problem is? It is a simple "hello" message.

![hello-qr](https://cloud.githubusercontent.com/assets/20187287/21364032/60fcf4c8-c6ef-11e6-9071-e5f78cb3920d.png)

**Comment by srowen** [comment]
It's lacking a light/white margin so it's invalid
