### ISSUE TITLE
Text decoded as barcode

### ISSUE THREAD

**Issue by andobrol** [zxing/zxing#730]
Barcode text description decoded as barcode.

For example attached image decoded as EAN-8 with content "21017773".
![000 111_cr](https://cloud.githubusercontent.com/assets/6030277/21456013/de62c526-c935-11e6-8412-1f1829407c3c.png)

**Comment by srowen** [comment]
Not sure what this means

**Comment by andobrol** [comment]
I mean that text on image wrongly determined as barcode.
Attached image is a part of large image with normal barcodes.
