### ISSUE TITLE
can not find symbol "getStartTimestamp()" or "getEndTimestamp()". 

### ISSUE THREAD

**Issue by liucc07** [zxing/zxing#735]
when try to build the android project, I meet the error: in the \app\src\main\java\com\google\zxing\client\android\result\CalendarResultHandler.java
can not find symbol "getStartTimestamp()" or "getEndTimestamp()". 

Why? Any way to fix?

**Comment by srowen** [comment]
Not sure, the project builds fine right now: https://travis-ci.org/zxing/zxing
It's something specific to your app or modifications.

**Comment by LJX1024** [comment]
did you solve this problem? I have encountered the same problem.

**Comment by ImTosS** [comment]
Same problem here!

**Comment by srowen** [comment]
You're mixing different versions of the project, old and new code, somehow. It's a problem in your build, not the project. Again, see link above.

**Comment by Goldennn** [comment]
then how to solve this error.
