### ISSUE TITLE
I found barcode encoding bug

### ISSUE THREAD

**Issue by yuchulho** [zxing/zxing#736]
bug report.

when I tried to encode some numbers, but actually zxing library generates wrong barcode in (zxing 3.3)
i.g) type : UPC_E, number : 12345670
codes ) BitMatrix result = new MultiFormatWriter().encode("12345670", BarcodeFormat.UPC_E, ??, ??, ??);
kindly check this case.
thank you

**Comment by srowen** [comment]
There is no info on what you think is wrong.
