### ISSUE TITLE
encoding bug

### ISSUE THREAD

**Issue by yuchulho** [zxing/zxing#737]
bug report.

when I tried to encode some numbers, but actually zxing library generates wrong barcode in (zxing 3.3)

MultiFormatWriter makes invalid barcodes with below combination.
i.g) type : UPC_E, number : 12345670
codes ) BitMatrix result = new MultiFormatWriter().encode("12345670", BarcodeFormat.UPC_E, ??, ??, ??);
kindly check this case.
thank you

**Comment by srowen** [comment]
No info on what you think the problem is. Output looks correct.
