### ISSUE TITLE
wrong barcode generated ( image updated )

### ISSUE THREAD

**Issue by yuchulho** [zxing/zxing#738]
bug report.

when I tried to encode some numbers, but actually zxing library generates wrong barcode in (zxing 3.3)

MultiFormatWriter makes invalid barcodes with below combination.
i.g) type : UPC_E, number : 12345670
codes ) BitMatrix result = new MultiFormatWriter().encode("12345670", BarcodeFormat.UPC_E, ??, ??, ??);
kindly check this case.

 - correct barcode
![correct_12345670_upc-e](https://cloud.githubusercontent.com/assets/9362305/21675661/f283eb3a-d375-11e6-9eb4-28bbb8968dba.jpg)

 - generated by zxing library
![image](https://cloud.githubusercontent.com/assets/9362305/21675776/591a3930-d376-11e6-8b9a-b95a6d0cc8ca.png)

 - captured screen
![captured_12345670_upc-e](https://cloud.githubusercontent.com/assets/9362305/21675694/0b513780-d376-11e6-99a0-0ad2e861aa78.png)

thank you

**Comment by srowen** [comment]
Ah, that's much better. The problem is that the UPC-E writer doesn't take into account the number system (first digit) and effectively assumes a 0. That should be an easy fix.
