### ISSUE TITLE
Recommend QR version bug

### ISSUE THREAD

**Issue by liu-ning** [zxing/zxing#740]
First sorry for my Chinglish.

I define a Class to creat qrcode here:  [QRUtil](https://gist.github.com/liu-ning/9debcae8b0bdb81fca7cfb215f63271f)

Example:  

String content = "https://itunes.apple.com/cn/app/id1180510476";

I set `MARGIN ` to 0, but, the result QRCode image's margin is not 0. The QRCodeWriter did not choose the right QR VERSION.

`recommendVersion` function return "qr version 5", but the "qr version 6" should be the right choose.

qrcode_version_5( auto choose version)
![qrcode_version_5](https://cloud.githubusercontent.com/assets/4246362/21712688/117160ac-d431-11e6-8f18-bd00c2c7373b.jpg)

qrcode_version_6( user set version)
![qrcode_version_6](https://cloud.githubusercontent.com/assets/4246362/21712689/11e04b3e-d431-11e6-89df-313bd9a15c5a.jpg)

**Comment by srowen** [comment]
You didn't say why you think version 6 is correct. If version 5 correctly encodes the content, then 5 is correct.

**Comment by liu-ning** [comment]
Yes, version 5 correctly encodes the content, but result qrcode (qrcode_version_5) image's  "info matrix" doesn't fill up it's background(white pic), "info matrix" has a few distance to background border .  So, I think my code `put(EncodeHintType.MARGIN, 0)` doesn't work. 

If I add code `put(EncodeHintType.QR_VERSION, 6)`  to tell `zxing`  to use QR version 6, the result image(qrcode_version_6) is what i think is right.   I think my code `put(EncodeHintType.MARGIN, 0)` is work. 

`Hashtable hints = new Hashtable<EncodeHintType, Object>() 
{{
            put(EncodeHintType.MARGIN, 0);
            //put(EncodeHintType.QR_VERSION, 6);
            
            put(EncodeHintType.CHARACTER_SET, CHARSET);
            put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
 }};
BitMatrix bitMatrix = new MultiFormatWriter().encode(content, BarcodeFormat.QR_CODE, QRCODE_SIZE, QRCODE_SIZE, hints);
`
