### ISSUE TITLE
Not able to scan "EAN 13", "CODE 93" and "CODABAR" format correctly

### ISSUE THREAD

**Issue by shwetasingh2117** [zxing/zxing#743]
As per the document provided it should support the "EAN 13", "CODE 93" and "CODABAR" format, but from my app I am not able to scan it properly.I am using Zxing 3.3.0 and also tested with demo app. Attaching Image for reference.

EAN 13:
![barcode ean 13](https://cloud.githubusercontent.com/assets/15977592/21809695/d59153c6-d76e-11e6-927a-79f4c156a065.png)

CODE 93

![code 93](https://cloud.githubusercontent.com/assets/15977592/21809702/dfb281cc-d76e-11e6-8b4d-77d2d4c472c8.png)

CODEBAR

![codebar](https://cloud.githubusercontent.com/assets/15977592/21809711/e686d804-d76e-11e6-8757-7d76b29f40c2.png)

**Comment by srowen** [comment]
The first one works fine.

http://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F15977592%2F21809695%2Fd59153c6-d76e-11e6-927a-79f4c156a065.png

The code 93 barcode isn't valid. You can probably  make out that it starts with a black bar and then a double-width white bar. This can't be correct as the start char begins with black-white-black single-module bars.

Likewise the Codabar should have only narrow and wide bars, but there are several different widths for narrow and wide bars. I think these have been distorted in generation.
