### ISSUE TITLE
This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by Gemori** [zxing/zxing#747]
I'm trying to recreate the qr web app. I'm looking to use it's function in my upcoming project that needs to read qr codes with a phone's camera to retrieve product codes.

I've uploaded the files to my site and when accessing:
http://mysite.com/zxing-zxing-3.3.0/zxingorg/src/main/webapp/w/decode.jspx

I get the following message:
"This XML file does not appear to have any style information associated with it. The document tree is shown below."

And it just shows the sourcecode of the file. When I remove the first line in the .jspx file:
"?xml version="1.0" encoding="UTF-8"?"

It then shows the web app just fine, but does not function correctly. Can I get some guidance on installing the web app correctly? I'm new to using jspx files. I just want the decode function to work properly so I can move on to developing my app.

**Comment by srowen** [comment]
As you can see, the web app does work correctly: http://zxing.org/w/decode.jspx

It looks like you haven't deployed the web app. You literally uploaded its code to a webserver.

**Comment by Gemori** [comment]
May I ask how I go about doing a deployment of this app? I just want to see it working on my webserver.
