### ISSUE TITLE
Random com.google.zxing.NotFoundException during the reading valid QRCode

### ISSUE THREAD

**Issue by acidroed** [zxing/zxing#748]
Here is my QRCodeRead class:

```java
import com.google.zxing.*;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.qrcode.QRCodeReader;

import javax.imageio.ImageIO;
import javax.xml.bind.DatatypeConverter;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.Base64;

public class QRCodeRead {

    public static String readQRCodeBase64(String srcString) {

        String base64String =
                srcString.split("data:image/png;base64,")[1];

        BinaryBitmap binaryBitmap = null;
        BufferedImage image = null;

        try {
            image = ImageIO.read(new ByteArrayInputStream(DatatypeConverter.parseBase64Binary(base64String)));
//            image = ImageIO.read(new ByteArrayInputStream(Base64.getDecoder().decode(base64String)));
            binaryBitmap = new BinaryBitmap(new HybridBinarizer(
                    new BufferedImageLuminanceSource(image)));

        } catch (IOException e) {
            e.printStackTrace();
        }


        //just to check if base64String was converted correctly
        try {
            ImageIO.write(image, "png", new File("qrCode.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        Result qrCodeResult = null;
        try {
            qrCodeResult = new QRCodeReader().decode(binaryBitmap);
        } catch (NotFoundException | FormatException | ChecksumException e) {
            e.printStackTrace();
        }

        return qrCodeResult.getText();

    }

}
```

On site which I test there is src attribute for QRCode image in Base64 format. So when I execute 
    `QRCodeRead.readQRCodeBase64(srcString)`
rarely, but sometimes I catch com.google.zxing.NotFoundException. 

At the same time I am trying to scan this QRCode with my android device and it works fine.

Here below is example of such failed reading.

Screenshot of QRCode:
![qrcode](https://cloud.githubusercontent.com/assets/13766722/22298320/c3d947fe-e328-11e6-84a4-d34dc23343bb.png)

String in the Base64 format:
_data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAM8AAADPCAIAAADd4xIIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAABkxSURBVHhe7dLBiizJlUXR/v+fVsNmkZNTmFxhnokEsYb73LDnVeT//evr6698/9q+/s73r+3r73z/2r7+zvev7evvfP/avv7O96/t6+98/9q+/s73r+3r73z/2r7+zvev7evvfP/avv7O96/t6+98/9q+/s73r+3r73z/2r7+zvev7evvfP/avv7O96/t6+98/9q+/s73r+3r79z+tf3fL/B0pCOnR06PnEaKFCnSMEeKFCnSkdPH/OxVnr5w+4QPeZWnIx05PXJ65DRSpEiRhjlSpEiRjpw+5mev8vSF2yd8yKs8HenI6ZHTI6eRIkWKNMyRIkWKdOT0MT97lacv3D7hQ17l6UhHTo+cHjmNFClSpGGOFClSpCOnj/nZqzx94fYJHxLpI56IFCnSMEd6zM+GOdIwR4oUKVKkSJEiDXOkYY70EU9EunD7hA+J9BFPRIoUaZgjPeZnwxxpmCNFihQpUqRIkYY50jBH+ognIl24fcKHRPqIJyJFijTMkR7zs2GONMyRIkWKFClSpEjDHGmYI33EE5Eu3D7hQyJ9xBORIkUa5kiP+dkwRxrmSJEiRYoUKVKkYY40zJE+4olIF26f8CGRIh05jRQp0pHTSMM8zEdOhzlSpGGOdM1zwxwp0pHTSJEu3D7hQyJFOnIaKVKkI6eRhnmYj5wOc6RIwxzpmueGOVKkI6eRIl24fcKHRIp05DRSpEhHTiMN8zAfOR3mSJGGOdI1zw1zpEhHTiNFunD7hA+JFOnIaaRIkY6cRhrmYT5yOsyRIg1zpGueG+ZIkY6cRop04fYJHxIp0pHTSJEiRTpyGinSkdNIw3zNc8McaZiPnEaKdOQ0UqQLt0/4kEiRjpxGihQp0pHTSJGOnEYa5mueG+ZIw3zkNFKkI6eRIl24fcKHRIp05DRSpEiRjpxGinTkNNIwX/PcMEca5iOnkSIdOY0U6cLtEz4kUqQjp5EiRYp05DRSpCOnkYb5mueGOdIwHzmNFOnIaaRIF26f8CGRIh05jRTpI56IFCnSkdNIR06HOdIwR4o0zJGGOVKkI6eRIl24fcKHRIp05DRSpI94IlKkSEdOIx05HeZIwxwp0jBHGuZIkY6cRop04fYJHxIp0pHTSJE+4olIkSIdOY105HSYIw1zpEjDHGmYI0U6chop0oXbJ3xIpEhHTiNF+ognIkWKdOQ00pHTYY40zJEiDXOkYY4U6chppEgXbp/wIZE+4olIkSINc6RXeXqYI0Ua5kjDHGmYIw1zpI94ItKF2yd8SKSPeCJSpEjDHOlVnh7mSJGGOdIwRxrmSMMc6SOeiHTh9gkfEukjnogUKdIwR3qVp4c5UqRhjjTMkYY50jBH+ognIl24fcKHRPqIJyJFijTMkV7l6WGOFGmYIw1zpGGONMyRPuKJSBdun/Ahr/J0pEiRIkWKFClSpEiRIkWKFClSpEiRIkWKFClSpEiRXuXpC7dP+JBXeTpSpEiRIkWKFClSpEiRIkWKFClSpEiRIkWKFClSpEiv8vSF2yd8yKs8HSlSpEiRIkWKFClSpEiRIkWKFClSpEiRIkWKFClSpFd5+sLtEz7kVZ6OFClSpEiRIkWKFClSpEiRIkWKFClSpEiRIkWKFCnSqzx94YUn/qv4HxMpUqRhPnIaKVKkYX7MzyINc6T/Yv8Dn/gf8T8+UqRIw3zkNFKkSMP8mJ9FGuZI/8X+Bz7xP+J/fKRIkYb5yGmkSJGG+TE/izTMkf6L/Q984n/E//hIkSIN85HTSJEiDfNjfhZpmCP9F7v9RP+hwzzMR06PnA7zkdNIkY6cRhrmSJGGOdKR00hHTiNFeszPLtw+4UOGeZiPnB45HeYjp5EiHTmNNMyRIg1zpCOnkY6cRor0mJ9duH3ChwzzMB85PXI6zEdOI0U6chppmCNFGuZIR04jHTmNFOkxP7tw+4QPGeZhPnJ65HSYj5xGinTkNNIwR4o0zJGOnEY6chop0mN+duH2CR9y5DTSMEeKFCnSMH/EE0dOIw1zpEgf8cSR02ue+wW3T/vAI6eRhjlSpEiRhvkjnjhyGmmYI0X6iCeOnF7z3C+4fdoHHjmNNMyRIkWKNMwf8cSR00jDHCnSRzxx5PSa537B7dM+8MhppGGOFClSpGH+iCeOnEYa5kiRPuKJI6fXPPcLbp/2gR/xRKRIwzzMkSIN85HTYY4UaZgjHTl9zM8iRYoUKdKR00gXbp/wIR/xRKRIwzzMkSIN85HTYY4UaZgjHTl9zM8iRYoUKdKR00gXbp/wIR/xRKRIwzzMkSIN85HTYY4UaZgjHTl9zM8iRYoUKdKR00gXbp/wIR/xRKRIwzzMkSIN85HTYY4UaZgjHTl9zM8iRYoUKdKR00gXbp/wIZEiRfqIJyINc6RhjjTMwzzMw/wRTwzzMB85jTTMkYb5wu0TPiRSpEgf8USkYY40zJGGeZiHeZg/4olhHuYjp5GGOdIwX7h9wodEihTpI56INMyRhjnSMA/zMA/zRzwxzMN85DTSMEca5gu3T/iQSJEifcQTkYY50jBHGuZhHuZh/ognhnmYj5xGGuZIw3zh9gkfEilSpGEe5iOnkSI95meRIkWKFCnSkdNIH/FEpEiRIkWKFClSpJfcPuejIkWKNMzDfOQ0UqTH/CxSpEiRIkU6chrpI56IFClSpEiRIkWK9JLb53xUpEiRhnmYj5xGivSYn0WKFClSpEhHTiN9xBORIkWKFClSpEiRXnL7nI+KFCnSMA/zkdNIkR7zs0iRIkWKFOnIaaSPeCJSpEiRIkWKFCnSS26f81FHToc5UqRhvua5YY4UaZiPnA5zpEhHTiNFOnIaaZiH+cLtEz7kyOkwR4o0zNc8N8yRIg3zkdNhjhTpyGmkSEdOIw3zMF+4fcKHHDkd5kiRhvma54Y5UqRhPnI6zJEiHTmNFOnIaaRhHuYLt0/4kCOnwxwp0jBf89wwR4o0zEdOhzlSpCOnkSIdOY00zMN84fYJHxIpUqRIr/L0kdNhjjTMkYY50jAPc6RhjhQpUqRhjhRpmCNduH3Ch0SKFCnSqzx95HSYIw1zpGGONMzDHGmYI0WKFGmYI0Ua5kgXbp/wIZEiRYr0Kk8fOR3mSMMcaZgjDfMwRxrmSJEiRRrmSJGGOdKF2yd8SKRIkSK9ytNHToc50jBHGuZIwzzMkYY5UqRIkYY5UqRhjnThhSd++KhIkSJFinTkNNIwR4oUaZgjRTpy+piffcQTkY6cDnOkSMN84YUnfvioSJEiRYp05DTSMEeKFGmYI0U6cvqYn33EE5GOnA5zpEjDfOGFJ374qEiRIkWKdOQ00jBHihRpmCNFOnL6mJ99xBORjpwOc6RIw3zhhSd++KhIkSJFinTkNNIwR4oUaZgjRTpy+piffcQTkY6cDnOkSMN84YUn/pEPjBQpUqRIkSJFGuZhHuZIwzzMwxwp0pHTYY505PQxPxvml7z83A8fGylSpEiRIkWKNMzDPMyRhnmYhzlSpCOnwxzpyOljfjbML3n5uR8+NlKkSJEiRYoUaZiHeZgjDfMwD3OkSEdOhznSkdPH/GyYX/Lycz98bKRIkSJFihQp0jAP8zBHGuZhHuZIkY6cDnOkI6eP+dkwv+T2OR81zJGGeZgjRYoUKdKR00iRIg3zMEeKFOma546cRor0EU9cuH3ChwxzpGEe5kiRIkWKdOQ0UqRIwzzMkSJFuua5I6eRIn3EExdun/AhwxxpmIc5UqRIkSIdOY0UKdIwD3OkSJGuee7IaaRIH/HEhdsnfMgwRxrmYY4UKVKkSEdOI0WKNMzDHClSpGueO3IaKdJHPHHhhSf+Iz78yGmkSJFe5elIkSINc6RhjjTMkSJd89wwRxrmC6/9Zzzkw4+cRooU6VWejhQp0jBHGuZIwxwp0jXPDXOkYb7w2n/GQz78yGmkSJFe5elIkSINc6RhjjTMkSJd89wwRxrmC6/9Zzzkw4+cRooU6VWejhQp0jBHGuZIwxwp0jXPDXOkYb5w+4QPiTTMwzzMkSJFinTkNFKkSJEiRYoUKVKkYX7Mz4Y5UqRIkYZ5mCNduH3Ch0Qa5mEe5kiRIkU6chopUqRIkSJFihQp0jA/5mfDHClSpEjDPMyRLtw+4UMiDfMwD3OkSJEiHTmNFClSpEiRIkWKFGmYH/OzYY4UKVKkYR7mSBdun/AhkYZ5mIc5UqRIkY6cRooUKVKkSJEiRYo0zI/52TBHihQp0jAPc6QLLzzxw0dFGuZIkY6cRoo0zJEiRYoUKdJjfjbMkSJFOnIaKVKkSMM8zMN84YUnfvioSMMcKdKR00iRhjlSpEiRIkV6zM+GOVKkSEdOI0WKFGmYh3mYL7zwxA8fFWmYI0U6chop0jBHihQpUqRIj/nZMEeKFOnIaaRIkSIN8zAP84UXnvjhoyINc6RIR04jRRrmSJEiRYoU6TE/G+ZIkSIdOY0UKVKkYR7mYb7wwhP/lo+NdOR0mI+cRop05DRSpCOnwzzMkSIdOY0UaZivee7CC0/8Wz420pHTYT5yGinSkdNIkY6cDvMwR4p05DRSpGG+5rkLLzzxb/nYSEdOh/nIaaRIR04jRTpyOszDHCnSkdNIkYb5mucuvPDEv+VjIx05HeYjp5EiHTmNFOnI6TAPc6RIR04jRRrma5678MITP3xUpEiRhjlSpF/jn4kUaZgjDfNHPDHMkR7zsyOnwxzpwgtP/PBRkSJFGuZIkX6NfyZSpGGONMwf8cQwR3rMz46cDnOkCy888cNHRYoUaZgjRfo1/plIkYY50jB/xBPDHOkxPztyOsyRLrzwxA8fFSlSpGGOFOnX+GciRRrmSMP8EU8Mc6TH/OzI6TBHuvDCEz98VKQjp5EiRTpyGmmYH/OzSI/52ZHTSJGOnEaKNMyRIkX6ZW/+Mz480pHTSJEiHTmNNMyP+Vmkx/zsyGmkSEdOI0Ua5kiRIv2yN/8ZHx7pyGmkSJGOnEYa5sf8LNJjfnbkNFKkI6eRIg1zpEiRftmb/4wPj3TkNFKkSEdOIw3zY34W6TE/O3IaKdKR00iRhjlSpEi/7M1/xodf89yR00iRIg1zpEiRjpwOc6RIj/lZpEiRIkU6cvqYn1144YkfPuqa546cRooUaZgjRYp05HSYI0V6zM8iRYoUKdKR08f87MILT/zwUdc8d+Q0UqRIwxwpUqQjp8McKdJjfhYpUqRIkY6cPuZnF1544oePuua5I6eRIkUa5kiRIh05HeZIkR7zs0iRIkWKdOT0MT+7cPuEDxnmYY505HSYI0WKFCnSY34WKdIwRxrmI6eP+dkwR4oUKdIvuH3aBw7zMEc6cjrMkSJFihTpMT+LFGmYIw3zkdPH/GyYI0WKFOkX3D7tA4d5mCMdOR3mSJEiRYr0mJ9FijTMkYb5yOljfjbMkSJFivQLbp/2gcM8zJGOnA5zpEiRIkV6zM8iRRrmSMN85PQxPxvmSJEiRfoFt0/7wEhHTq95LlKkI6eRIkUa5mGOFOnI6TBHihRpmCMdOR3mSBdun/AhkY6cXvNcpEhHTiNFijTMwxwp0pHTYY4UKdIwRzpyOsyRLtw+4UMiHTm95rlIkY6cRooUaZiHOVKkI6fDHClSpGGOdOR0mCNduH3Ch0Q6cnrNc5EiHTmNFCnSMA9zpEhHToc5UqRIwxzpyOkwR7rwwhM/fNRjfnbkNNJHPPERT0Q6chopUqRIwxwp0pHTSEdOhznShRee+OGjHvOzI6eRPuKJj3gi0pHTSJEiRRrmSJGOnEY6cjrMkS688MQPH/WYnx05jfQRT3zEE5GOnEaKFCnSMEeKdOQ00pHTYY504YUnfviox/zsyGmkj3jiI56IdOQ0UqRIkYY5UqQjp5GOnA5zpAsvPPHDRx05jTTMkYZ5mB/zs0iRIkWKdOR0mI+cPuZnkSIN8zAP84UXnvjho46cRhrmSMM8zI/5WaRIkSJFOnI6zEdOH/OzSJGGeZiH+cILT/zwUUdOIw1zpGEe5sf8LFKkSJEiHTkd5iOnj/lZpEjDPMzDfOGFJ374qCOnkYY50jAP82N+FilSpEiRjpwO85HTx/wsUqRhHuZhvnD7hA+JdOQ00mN+FunIaaRIwzzMkY6cRnrMzyJFGuYjp4/5WaRIF26f8CGRjpxGeszPIh05jRRpmIc50pHTSI/5WaRIw3zk9DE/ixTpwu0TPiTSkdNIj/lZpCOnkSIN8zBHOnIa6TE/ixRpmI+cPuZnkSJduH3Ch0Q6chrpMT+LdOQ0UqRhHuZIR04jPeZnkSIN85HTx/wsUqQLLzzxj3xgpCOnR04jRRrmSJEe87Nh/jX+mY94IlKkYR7mSBdeeOIf+cBIR06PnEaKNMyRIj3mZ8P8a/wzH/FEpEjDPMyRLrzwxD/ygZGOnB45jRRpmCNFeszPhvnX+Gc+4olIkYZ5mCNdeOGJf+QDIx05PXIaKdIwR4r0mJ8N86/xz3zEE5EiDfMwR7rwwhP/yAdGihTpyOkwD3OkSMMcaZgjDXOkSB/xRKRIkSIN8zBHGuZIF1544h/5wEiRIh05HeZhjhRpmCMNc6RhjhTpI56IFClSpGEe5kjDHOnCC0/8Ix8YKVKkI6fDPMyRIg1zpGGONMyRIn3EE5EiRYo0zMMcaZgjXXjhiX/kAyNFinTkdJiHOVKkYY40zJGGOVKkj3giUqRIkYZ5mCMNc6QLt0/4kGEe5iOnR06H+SOeiBQpUqRIkYY50jBHijTMH/FEpCOnF26f8CHDPMxHTo+cDvNHPBEpUqRIkSINc6RhjhRpmD/iiUhHTi/cPuFDhnmYj5weOR3mj3giUqRIkSJFGuZIwxwp0jB/xBORjpxeuH3ChwzzMB85PXI6zB/xRKRIkSJFijTMkYY5UqRh/ognIh05vfDCE7/Kf+hjfjbMR04jRYoUKdIwR4oU6ZrnjpxGinTk9MILT/wq/6GP+dkwHzmNFClSpEjDHClSpGueO3IaKdKR0wsvPPGr/Ic+5mfDfOQ0UqRIkSINc6RIka557shppEhHTi+88MSv8h/6mJ8N85HTSJEiRYo0zJEiRbrmuSOnkSIdOb1w+4QPeZWnH/Ozj3jiI56IFOnIaaRIkR7zs0iRIkUa5mG+cPuED3mVpx/zs4944iOeiBTpyGmkSJEe87NIkSJFGuZhvnD7hA95lacf87OPeOIjnogU6chppEiRHvOzSJEiRRrmYb5w+4QPeZWnH/Ozj3jiI56IFOnIaaRIkR7zs0iRIkUa5mG+cPuED4n0EU9EihQpUqRhjhTpMT8b5kiRhjnSRzwRKdKR02GONMwXbp/wIZE+4olIkSJFijTMkSI95mfDHCnSMEf6iCciRTpyOsyRhvnC7RM+JNJHPBEpUqRIkYY5UqTH/GyYI0Ua5kgf8USkSEdOhznSMF+4fcKHRPqIJyJFihQp0jBHivSYnw1zpEjDHOkjnogU6cjpMEca5gu3T/iQSJGOnEaKFClSpEjDHGmYh/nI6TBHihQp0mN+9ipPR4r0ktvnfFSkSEdOI0WKFClSpGGONMzDfOR0mCNFihTpMT97lacjRXrJ7XM+KlKkI6eRIkWKFCnSMEca5mE+cjrMkSJFivSYn73K05EiveT2OR8VKdKR00iRIkWKFGmYIw3zMB85HeZIkSJFeszPXuXpSJFecvucj4oU6chppEjDPMyRXuXpI6fDPMyRIkWK9JifRYoU6TE/u3D7hA+JFOnIaaRIwzzMkV7l6SOnwzzMkSJFivSYn0WKFOkxP7tw+4QPiRTpyGmkSMM8zJFe5ekjp8M8zJEiRYr0mJ9FihTpMT+7cPuED4kU6chppEjDPMyRXuXpI6fDPMyRIkWK9JifRYoU6TE/u3D7hA+JFOnIaaRIj/nZMEca5kjDHOkxP4sUKdIwR4r0mJ9FeszPIl24fcKHRIp05DRSpMf8bJgjDXOkYY70mJ9FihRpmCNFeszPIj3mZ5Eu3D7hQyJFOnIaKdJjfjbMkYY50jBHeszPIkWKNMyRIj3mZ5Ee87NIF26f8CGRIh05jRTpMT8b5kjDHGmYIz3mZ5EiRRrmSJEe87NIj/lZpAu3T/iQSB/xRKRIj/nZMF/zXKRIwxzpMT8b5sf8LFKkSJGG+cLtEz4k0kc8ESnSY342zNc8FynSMEd6zM+G+TE/ixQpUqRhvnD7hA+J9BFPRIr0mJ8N8zXPRYo0zJEe87NhfszPIkWKFGmYL9w+4UMifcQTkSI95mfDfM1zkSINc6TH/GyYH/OzSJEiRRrmC7dP+JBXeTrSkdNIkR7zs0iRIkWKNMyRhjlSpEjDHOkjnhjml9w+56Ne5elIR04jRXrMzyJFihQp0jBHGuZIkSINc6SPeGKYX3L7nI96lacjHTmNFOkxP4sUKVKkSMMcaZgjRYo0zJE+4olhfsntcz7qVZ6OdOQ0UqTH/CxSpEiRIg1zpGGOFCnSMEf6iCeG+SUvP/f1dfD9a/v6O9+/tq+/8/1r+/o737+2r7/z/Wv7+jvfv7avv/P9a/v6O9+/tq+/8/1r+/o737+2r7/z/Wv7+jvfv7avv/P9a/v6O9+/tq+/8/1r+/o737+2r7/z/Wv7+jvfv7avv/P9a/v6O9+/tq+/8/1r+/or//rX/wPTVVM8BeND6wAAAABJRU5ErkJggg==_

**Comment by srowen** [comment]
I'm not quite sure what you mean, because the QR code actually encodes 

```
otpauth://totp/test_organisation:enablemfa958806%40email.com?secret=CTSCVI4MF3I4M6DUA2BC7AOG6SRJHFRI&issuer=test_organisation
```

See

http://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F13766722%2F22298320%2Fc3d947fe-e328-11e6-84a4-d34dc23343bb.png

This image always decodes correctly. If you're decoding an image of the image, it's always possible it's not detected correctly in some frames.
