### ISSUE TITLE
Could not decode image

### ISSUE THREAD

**Issue by b-t-o** [zxing/zxing#749]
Hi!

I already tried the option harder or uses the online decoder.
But this image (it is from a telefax) could not decoded - but another app could find the qrcode.

Is there a change to get this with zxing?

Best wishes

Marc
![qr-test](https://cloud.githubusercontent.com/assets/11349949/22353006/bc0d4f06-e41e-11e6-9646-6525fa04fca0.png)

**Comment by srowen** [comment]
The actual image is corrupted, so I'm not surprised it doesn't scan. I think you'd find it would work, oddly, if you scanned it off the screen with a phone. This is the use case it's optimized for. You could therefore experiment with trying scanning a lightly blurred image to smooth over telefax artifacts.

**Comment by b-t-o** [comment]
It is a software which can decode it - called ClearImage.
They have different methods to try it.

But I don't know exactly, what the do to reconstruct the image. But should zxing be abled to scan those images too?
