### ISSUE TITLE
Android vCard parse: type default / type order

### ISSUE THREAD

**Issue by qrcoder** [zxing/zxing#751]
Barcode scanner seems to be using different type defaults for `ADR` and `TEL` than suggested in the specification (at least for vCard 2.1). For me it defaults to 'private' but it should to 'work'. From looking at the code it seems that there is no default internally. This can also result in wrong order of types, e.g. this vCard data will swap the types of the second and third number.  

```
BEGIN:VCARD
N:;John;;;
TEL;WORK:10
TEL:2
TEL;CELL:30
END:VCARD  
```

IMHO a good solution for both issues would be to default to the type 'WORK' for phone numbers and addresses at parse time. This should be close enough to the specification. Maybe also for eMails.  

I guess this could be implemented by adding a `defaultType` Parameter to the function `matchVCardPrefixedField` in VCardResultParser.java?

**Comment by srowen** [comment]
I skimmed the code again and it seems like it defaults to nothing at all when there's no type metadata. "private" is perhaps an Android default. I don't know if this app should do something different.

What's the scenario where the types are wrong though? That does sound like a problem. The 'types' and values arrays should be of equal length. Are you on the trail of a fix already? if you have a PR to look at, I'll review. Maybe this as a test case plus some extra arg checking would reveal the issue.

**Comment by qrcoder** [comment]
Yes, it seems "private" is the Android default. I think it would be best for ZXing to itself insert a default of "work" as that is the recommended default in the vCard spec.  
  
The vCard data above ( [QR Code from it in ZXing Generator](https://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=BEGIN%3AVCARD%0AN%3A%3BJohn%3B%3B%3B%0ATEL%3BWORK%3A10%0ATEL%3A2%0ATEL%3BCELL%3A30%0AEND%3AVCARD++) ) results in a wrong type for "2" and "30". The reason for this seems to be that the 'types' and 'values' arrays are NOT of equal length as "2" in the example does not get a type. Would it get a default type ("work") everything should work as expected.  
  
Unfortunately I am not fluent in Java but I *think* a fix for both issues could look like this:  
* add ´defaultType´ parameter to the function ´matchVCardPrefixedField´.
* in ´AddressBookParsedResult´ append default values ´work´ to the fields ´ADR´, ´TEL´ and ´EMAIL´

**Comment by srowen** [comment]
Yeah I have a fix for the actual bug, that part was simple. Do you have a ref for the vCard default? I intend the output of parsing the vCard as a POJO to reflect the source. If it always says 'WORK' when nothing is specified that's kind of changing what the data says. Unless vCard mandates that all contact info has a type and defaults to work I'd hesitate to apply that change.

**Comment by qrcoder** [comment]
Taking a closer look, the defaults are not so clear after all.  
  
vCard 2.1: https://www.imc.org/pdi/vcard-21.rtf   searching for `Delivery Address Type` there is a table. It says the default includes several odd types but I think ´WORK´ is most relevant, at least for Android  
vCard 3.0: https://tools.ietf.org/html/rfc2426#page-20 same defaults as 2.1 for ´ADR´
vCard 4.0: https://tools.ietf.org/html/rfc6350#page-20 defaults to none for ´ADR´ (which is impossible on Android I guess).  
  
For ´TEL´ the default is "VOICE" for all three versions and for ´EMAIL´ the default is "INTERNET" for v2.1 and v3.0 and nothing for v 4.0.  

As long as Android enforces a default it seems to to be impossible to get a result according to the spec. And the moral of the story is that types always need to be included. Still, it might be better to use "WORK" instead of an Android enforced "PRIVATE" as default as probably 99% of vCards are business vCards.

**Comment by srowen** [comment]
Yeah that is a reasonable argument for enforcing a default, even if there isn't one, really. I end up neutral on it and would prefer to leave that behavior as-is, if neutral.
