### ISSUE TITLE
Problem using  zxing 3.3.0 with ant's artifact:dependencies

### ISSUE THREAD

**Issue by kasdega** [zxing/zxing#752]
I changed a pom.xml entry to zxing to 3.3.0 
```

		<dependency>
			<groupId>com.google.zxing</groupId>
			<artifactId>core</artifactId>
			<version>3.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.zxing</groupId>
			<artifactId>javase</artifactId>
			<version>3.3.0</version>
		</dependency>
		<dependency>
		  <groupId>com.google.zxing</groupId>
		  <artifactId>zxing-parent</artifactId>
		  <version>3.3.0</version>
		  <type>pom</type>
		</dependency>
```

and now I'm getting this:

```
    [artifact:dependencies] Unable to resolve artifact: Unable to get dependency information: Unable to read the metadata file for artifact 'com.github.jai-imageio:jai-imageio-core:jar': Invalid JDK version in profile 'java8-and-higher': Unbounded range: [1.8, for project com.github.jai-imageio:jai-imageio-core
    [artifact:dependencies]   com.github.jai-imageio:jai-imageio-core:jar:1.3.1

```

From what I can find this indicates that something is wrong with the pom file for zxing related to the required versions of java (which I'm using java 8)?

The code compiles fine using Maven and Eclipse, but this error occurs when attempting to run a separate ant process.

	<artifact:dependencies filesetId="dependency.fileset">
		<artifact:pom file="${basedir}/pom.xml"/>
	</artifact:dependencies>

The ant task works just fine if I use zxing 2.2 in the pom but then of course my code does not.
Is this a bug in zwing 3.3.0 or am I missing something?

**Comment by srowen** [comment]
That's odd, I have never seen that error. However, the pom file for this artifact does look like it has an error:

http://search.maven.org/#artifactdetails%7Ccom.github.jai-imageio%7Cjai-imageio-core%7C1.3.1%7Cbundle

There's a range specified as `[1.8,` which isn't valid. However I don't see why anything would active the profile. You're not building that artifact. You just need to consume it.

It's not a problem with this project but may be a real problem.

**Comment by kasdega** [comment]
I think when the artifact:dependencies its thing it is attempting to consume the entire pom file.  So even though I may not activate the profile ant is choking on it.  When it does that it errors on the invalid range and stops so my ant target doesn't run any more.  Seems like a simple fix to throw a ')' at the end unless I'm missing something.  Is there anything I can do about this until its changed and released?
