### ISSUE TITLE
PDF417 error samples

### ISSUE THREAD

**Issue by benquan** [zxing/zxing#753]
I have 3 PDF417 samples. They all come from the same type of document. I am able to decode 1 of them but the other two refuse to decode.  I tested other online samples that manage to decode all 3.

OK sample:
![dui3](https://cloud.githubusercontent.com/assets/3030645/22851584/4b8bcf26-efec-11e6-9a93-6862ffc8c287.jpg)

Error samples:
![dui1](https://cloud.githubusercontent.com/assets/3030645/22851586/5645bda0-efec-11e6-9534-8ce29ce2b92f.jpg)
![dui2](https://cloud.githubusercontent.com/assets/3030645/22851587/590b03a6-efec-11e6-94ec-5d8ee16ef25c.jpg)

Any help appreciated!

**Comment by srowen** [comment]
It's generally true that not all images will decode. These latter two look excessively corrupted. Unless you're suggesting a targeted code change, this won't lead to anything.

**Comment by benquan** [comment]
Studying the zxing code I found a commented section that totally fixed the problem:
This is in PDF417ScanningDecoder:

```
            // TODO implement check for width and correction of black and white bars
            // use start (and maybe stop pattern) to determine if blackbars are wider than white bars. If so, adjust.
            // should probably done only for codewords with a lot more than 17 bits. 
            // The following fixes 10-1.png, which has wide black bars and small white bars

            for (int i = 0; i < moduleBitCount.Length; i++)
            {
                if (i % 2 == 0)
                {
                    moduleBitCount[i]--;
                }
                else
                {
                    moduleBitCount[i]++;
                }
            }
```
