### ISSUE TITLE
Improve Datamatrix Scan Performance

### ISSUE THREAD

**Issue by olieidel** [zxing/zxing#759]
Thanks for maintaining zxing, it's probably the best open source library for barcodes out there.

Currently, I am trying to scan datamatrix codes, however, scan performance is not very good (see attachment), especially with larger (6x6) datamatrix codes. Scanning from my screen while the codes are enlarged is doable, but It's nearly impossible to scan the attached codes from printed pages.

I am aware that this project is in maintenance mode and this is more or less a feature request. However, if you could point me in the direction of some other library (or just the necessary optimizations) which offer/s better datamatrix scan performance, I would be happy integrate the code into zxing and file a pull request.

Attached file:
[Testfälle_bmp023.pdf](https://github.com/zxing/zxing/files/799996/Testfalle_bmp023.pdf)

Further information and background:
Germany has decided to standardize medication plans (see examples in attachment pdf). They chose to use datamatrix instead of qr codes (hm). The first smartphone apps in the app stores seem to be licensing proprietary scan technology.

So at the moment our options are:
- Everyone licenses proprietary scanners
- Change the standard from datamatrix to qr codes (better scanning performance)

If we don't find an open-source library which delivers satisfactory datamatrix scanning performance, we're in for a fun ride..

Any answer is greatly appreciated. Thanks!

**Comment by srowen** [comment]
I don't have any suggestions for you, and wouldn't dump another library into this one. If you have a more targeted PR to suggest, you can open one.
