### ISSUE TITLE
Unable to recognize this Interleaved 2 of 5 barcodes

### ISSUE THREAD

**Issue by vmerkel** [zxing/zxing#770]
ZXing in version 4.7.6 is unable to recognize the attached  Interleaved 2 of 5 barcodes.

![i2o5](https://cloud.githubusercontent.com/assets/8568433/23995291/2e5b67fa-0a49-11e7-82cf-95d490479bc1.png)

**Comment by srowen** [comment]
I think the lines are too fat, so it ends up being out of spec. It is likely not really a problem with the code therefore, but if you have a change to suggest that doesn't harm performance elsewhere I can look at it.
