### ISSUE TITLE
Warning when using Java 1.8

### ISSUE THREAD

**Issue by Omcsesz** [zxing/zxing#771]
When I try to build my Android project, I get a warning with the following text:
AGPBI: {"kind":"warning","text":"The field Intent.FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET is deprecated","sources":[{"file":"C:\\Users\\OMCSESZ\\AndroidStudioProjects\\VIPCardApp\\app\\src\\main\\java\\hu\\example\\omcsesz\\vipcardapp\\IntentIntegrator.java","position":{"startLine":322,"startColumn":35}}]}

Java version: 1.8.0_121
Android Studio version: 2.3
Gradle version: 3.4.1

**Comment by srowen** [comment]
Not a problem and not related to Java.  This constant is deprecated in newer Android but is used for backward compatibility
