### ISSUE TITLE
colored qrcode can't decode

### ISSUE THREAD

**Issue by vickyleu** [zxing/zxing#773]
sorry i'm poor in english

![alt text](http://img.blog.csdn.net/20150630112039097?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvYW9jaHVhbmd1eWluZw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center "title")

**Comment by srowen** [comment]
It does decode:

https://zxing.org/w/decode?u=https%3A%2F%2Fcamo.githubusercontent.com%2F681d8ccfe1b30ec5a85f2b982aa0c542e24000ec%2F687474703a2f2f696d672e626c6f672e6373646e2e6e65742f32303135303633303131323033393039373f77617465726d61726b2f322f746578742f6148523063446f764c324a736232637559334e6b626935755a5851765957396a61485668626d643165576c755a773d3d2f666f6e742f3561364c354c32542f666f6e7473697a652f3430302f66696c6c2f49304a42516b46434d413d3d2f646973736f6c76652f37302f677261766974792f43656e746572

**Comment by vickyleu** [comment]
Barcode Scanner 4.7.6 demo application identification too slow

**Comment by vickyleu** [comment]
is  reappear on Dual camera phone (huawei p8 ,android 7.0)or nubia  NX512J (arm64-v8a Android 5.1.1,level 22),any other phones is work smoothly

**Comment by evandrix** [comment]
![https://i.ibb.co/8cVXb3B/HV18-Ball-Day1-color.png](https://i.ibb.co/8cVXb3B/HV18-Ball-Day1-color.png)
