### ISSUE TITLE
Is there a mapping from ZXing version to JDK version?

### ISSUE THREAD

**Issue by tinkokuhei** [zxing/zxing#774]
Is there a mapping from ZXing version to JDK version?
I'm trying to decide if I need to explicitly set the JDK version that I used for my build in the manifest file.
example: 
zxing 2.2  -->jdk 1.6 above
zxing 2.3  -->jdk 1.7 above
Waiting for your help , your reply will be appreciate!

**Comment by srowen** [comment]
Questions should go to the mailing list, but you can also find that release 3.0.0 requires Java 7+ from the Releases tab. Before that, I believe 2.x required Java 6, and before that it was Java 4+.

**Comment by tinkokuhei** [comment]
Thanks for your answer. I search the realse tab. I find the description of the java version .
But I find that the earliest version of ZXing is 2.3.0. Where can I find the old version source file and description  of zxing .Example: ZXing 2.2.0,etc.
Waiting for your help , your reply will be appreciate!
