### ISSUE TITLE
Gallery qr image not able to decode To get QR string

### ISSUE THREAD

**Issue by ashuw20001** [zxing/zxing#778]
Hi , This is Ashish Ramtekkar an Mobile Application developer.
I am integrating this module in one of my application , but gallery image (Image which is capture through mobile camera from Laptop screen) is not able to decode to return the proper result object.(getting null result object when passing bitmap).

Below is my Code Snippet.
  String contents = null;

    int[] intArray = new int[bMap.getWidth()*bMap.getHeight()];
    //copy pixel data from the Bitmap into the 'intArray' array
    bMap.getPixels(intArray, 0, bMap.getWidth(), 0, 0, bMap.getWidth(), bMap.getHeight());

    LuminanceSource source = new RGBLuminanceSource(bMap.getWidth(), bMap.getHeight(), intArray);
    BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

    Reader reader = new MultiFormatReader();
    try {
        Result result = reader.decode(bitmap);
        contents = result.getText();
    }
    catch (Exception e) {
        Log.e("QrTest", "Error decoding barcode", e);
    }
 An humble request please give any suggestion as soon as possible.

Thanks ,
Ashish Ramtekkar,
http://ashish-ramtekkar.banded.me.
ramtekkar42@gmail.com.

**Comment by srowen** [comment]
You have not provided detail like a barcode that reproduces or the result of your debugging

**Comment by ashuw20001** [comment]
![img_20170328_130455](https://cloud.githubusercontent.com/assets/5238143/24397449/e853e12c-13c3-11e7-85b1-155f63ed0504.jpg)
Srowen, Please find the sample image that i used to decode.
I downloaded QR image working good but not an capture one from laptop.

Please suggest for the same.
Thanks ,
Ashish Ramtekkar,
http://ashish-ramtekkar.banded.me.
ramtekkar42@gmail.com.

**Comment by ashuw20001** [comment]
Please provide any update .


Thanks
