### ISSUE TITLE
Barcode code39 not working even with sample app uploaded on Playstore..

### ISSUE THREAD

**Issue by khalid-mahmood** [zxing/zxing#781]
![image uploaded from ios](https://cloud.githubusercontent.com/assets/6528169/24653845/efeabfae-1950-11e7-9680-8d97a3a3ef5b.jpg)

**Comment by srowen** [comment]
Decodes fine: https://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F6528169%2F24653845%2Fefeabfae-1950-11e7-9680-8d97a3a3ef5b.jpg

**Comment by khalid-mahmood** [comment]
@srowen i am using playstore app.. but it can't scan..

**Comment by khalid-mahmood** [comment]
@srowen Using Lenovo Yoga Tab 8 but no luck...
working fine with Huewei honor 3C
