### ISSUE TITLE
PDF 417 Barcode Encoding Error

### ISSUE THREAD

**Issue by apoorvakatta** [zxing/zxing#784]
### Bug Reports
Source: https://mvnrepository.com/artifact/com.google.zxing/core
Version: 3.3.0

```
public String getPDF417Barcode()
{
    LinkedHashMap<EncodeHintType,Object> encodingFormat = new 
    LinkedHashMap<EncodeHintType,Object>();
    encodingFormat.put(EncodeHintType.CHARACTER_SET, "UTF-8");
    encodingFormat.put(EncodeHintType.MARGIN, 0);

    BitMatrix bm = w.encode("My message", BarcodeFormat.PDF_417, 800, 200, encodingFormat);

    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    MatrixToImageWriter.writeToStream(bm, "png", baos);
    return "data:image/png;base64,"+Base64.getEncoder().encodeToString(baos.toByteArray());
}
```

The pdf417 barcode data does not match input.
Input: "My message"
Output: "A My message"

**Comment by srowen** [comment]
I can't reproduce this. The encode image is as below, and it decodes to "My message". I think maybe you have another problem in your code or test?

![download](https://cloud.githubusercontent.com/assets/822522/24755943/ecb919f0-1ad3-11e7-92ac-d11226b019c3.png)

**Comment by apoorvakatta** [comment]
PDF417 barcode for UTF-8 text should be this one
![image](https://cloud.githubusercontent.com/assets/20812836/24761451/f42b7e54-1b1d-11e7-8719-307657e5d741.png)

**Comment by snailycy** [comment]
it has a superfluous prefix "\000026"
