### ISSUE TITLE
it can not detect my QRCode image

### ISSUE THREAD

**Issue by RockyF** [zxing/zxing#790]
### Bug Reports

my QRCode image is a stardard jpeg image with a logo inside like this:
![qrcode](https://cloud.githubusercontent.com/assets/1643017/25032740/67c3f030-2109-11e7-9ad0-e99b3f91931b.jpeg)

QRCodeReader threw an exception named com.google.zxing.NotFoundException.
my image can be detected by other tools.

**Comment by srowen** [comment]
Works fine: https://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F1643017%2F25032740%2F67c3f030-2109-11e7-9ad0-e99b3f91931b.jpeg

**Comment by RockyF** [comment]
Sorry, I called decode with an empty pixels.
Now it works, thanks!
