### ISSUE TITLE
Only two finder patterns were found when decoding qrcode

### ISSUE THREAD

**Issue by zxkane** [zxing/zxing#792]
I am using `zxing` to decode a qrcode image. Both the [online decoder](https://zxing.org/w/decode.jspx) and directly using `zxing J2SE` API failed to decode the specific image. After debugging the `QrcodeDecoder`, I found it only found two finder patterns from the image.

![zxing](https://cloud.githubusercontent.com/assets/843303/25226785/bc6e13ce-25f8-11e7-9c1e-d30d1e05bbaa.jpg)

However the image can be decoded properly by other qrcode services, such as [this one](http://www.onlinebarcodereader.com/).

**Comment by srowen** [comment]
Yes, that just happens sometimes. It's not a bug.

**Comment by zxkane** [comment]
The scan always fails on this image, not intermittently. Do you think it's caused by the quality of image? Any suggestion to preprocessing the image to improve the scan rate?
