### ISSUE TITLE
Enable fdroid builds again

### ISSUE THREAD

**Issue by fungs** [zxing/zxing#797]
For anyone who has some time to spend on optimizing the build system: it would be nice to have automatic builds on fdroid, again. Until then, the bugfixes in the latest minor release will not reach most people who get the apk via fdroid.

https://f-droid.org/wiki/page/com.google.zxing.client.android

**Comment by srowen** [comment]
Not sure what this is about. Fdroid isn't related to this project and the official release is available on Play. The build here is fine. What are you asking for?

**Comment by fungs** [comment]
Many people use fdroid automated builds and not Google Play. Fdroid establishes a one-to-one relation between the source code and the binaries. The automatic build by fdroid stopped working after version 4.7.3 with comments "4.7.5: We can't build this version: The build for this version was manually disabled. Reason: requires recent maven, seemingly no way around it", "4.7.4: We can't build this version: The build for this version was manually disabled. Reason: fails". Since these are minor version bugfix releases, I wonder if one could make the build working again (apparently the fdroid maintainer wasn't able to do this). I don't have further information.

**Comment by srowen** [comment]
It requires a Maven that was released about 2.5 years ago, so I am not sure what the comment is referring to. Travis has it as a standard, for instance. This is an F-droid problem

**Comment by fungs** [comment]
Just trying to fix this issue on either side. Note by the fdroid maintainer: "Enable AUM again once they switch to a sane build system, possibly gradle."

**Comment by srowen** [comment]
No idea what that comment means. Maven is the most widely used build system, and `mvn package` builds the app correctly and always has. F-droid has a problem

**Comment by fungs** [comment]
Maybe.
