### ISSUE TITLE
zxing stops working after upgrade android build tool to version 25

### ISSUE THREAD

**Issue by winstonquock** [zxing/zxing#798]
I have extracted ZXing into a library similar to what SimpleZXing. It works fine until I upgrade the Android SDK tool to version 25. Then it still works in Android 6 but stop working in Android 5 or lower. The capture screen can start and display normally but it fails to capture QR code.

**Comment by diorlitao** [comment]
Thank you for the invitation！
I am a big data development engineer，Little is known about android，I can
understand from your description，I guess the software version is not
compatible，Some features are available in high versions of software，Better
to upgrade the software version，

2017-05-09 13:36 GMT+08:00 winstonquock <notifications@github.com>:

**Comment by srowen** [comment]
There is no info here about what isn't working and sounds like you are talking about your own project.

**Comment by winstonquock** [comment]
I tried the simplezxing version, the same problem, it can't detect a clear QR code which the iOS app can detect in no time. After a lot of experimenting, it seems the problem is that it becomes extremely sensitive to runtime speed after moving to SDK platform 25.  When it is running in the debugger, if I have a breakpoint set somewhere, the scan would not work and no yellow indictor is flashing, even though the breakpoint is never hit as it would only be hit in the caller's ```onActivityResult()```; after I remove all the break points, it works but more sluggish than before, typically taking 10 or more seconds for a scan. While it was never as fast as iOS, it took only a few seconds before. So I feel it may be a performance issue when moving to the new platform version.
