### ISSUE TITLE
Validate code128 barcode type

### ISSUE THREAD

**Issue by vidyajejurkar** [zxing/zxing#799]
I want to validate scanned barcode by zxing to check whether it is of type code 128 type or not.
How  i scan specify range for code 128.
I also tried to validate it like below code but I get negative ans always for it like scanned barcod eis not type of code128.
I need help.anyone help me in it.
 public void onActivityResult(int requestCode, int resultCode, Intent intent) {
        //retrieve scan result
        IntentResult scanningResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, intent);
        if (scanningResult != null) {
            if (scanningResult.getContents() != null) {
                //we have a result
                codeContent = scanningResult.getContents();
                // display it on screen
                contentTxt.setText("CONTENT: " + codeContent);
                //Insert Data into database
                System.out.println("Database Contents True or False:" + db.insertNewBarcode(codeContent));
                System.out.println("Database Content is" + db);

                //To delete all records from Database

               /* db.deleteallvalues();
                System.out.println("Database Deleted");*/
                // Database Record Count
                int profile_counts = db.getProfilesCount();
                db.close();
                System.out.println("DB Count" + profile_counts);

            } else if (requestCode == 0 || resultCode == 0) {
                aletErrorDialog();

            }
        }
        if(scanningResult.equals(BarcodeFormat.CODE_128))
        {
            Toast.makeText(getApplicationContext(),"Code 128 Barcode",Toast.LENGTH_LONG).show();
            System.out.println("code 128 barcode");
        }
        else
        {
            //throw new RuntimeException ("Format Not supported.");
            Toast.makeText(getApplicationContext(),"it is not Code 128 Barcode",Toast.LENGTH_LONG).show();

        }

    }

**Comment by srowen** [comment]
This isn't a forum to ask about your code. If you use Code128Reader, it will only scan for code 128.
