### ISSUE TITLE
Browser not opens file:\\ url

### ISSUE THREAD

**Issue by Grony** [zxing/zxing#805]
Hello,
I'm using zxing to capture QR-Code from Browser and than to switch to another page. Other than the standard http-url return handler value (the argument of 'ret' var), I need a file-url (file://....). The Browser not opens the new page of file. I Think, that zxing ignores uri that starts with file:// or the browser do that?
Has anyone an Idea why http:\\ works and file:\\ not?

Thanks

**Comment by srowen** [comment]
The mailing list is a better place for questions.
The platform (browser, Android) actually opens links.
It wouldn't surprise me if file URIs are restricted for security reasons, but, this isn't an app issue.
