### ISSUE TITLE
ZXing creates wrong barcode (for text with leading asterisk?)

### ISSUE THREAD

**Issue by CharlyNapf** [zxing/zxing#806]
Hi,

in our project we create data matrix barcodes using ZXing (core-3.3.0.jar and javase-3.3.0.jar) in this way:
```java
        final DataMatrixWriter barcode = new DataMatrixWriter();
        final BitMatrix bitMatrix = barcode.encode(text, BarcodeFormat.DATA_MATRIX, 0, 0);
```
We create an image (```java.awt.Image```) using the bit matrix and scan this barcode image afterwards (form screen or paper). In 99% percent of all cases the text of the scanned barcode image is identical to the the encoded text.

But in some cases we get another text. Examples:
* original text -> converted to barcode
* `*MEMANT-1F-MESTECH` -> `*MEMANQ90E5079ROO70` 
* `*MEMANT-1F-M-2estech` -> `*MEMANQ90E5089q{estech` 
* `*MEMANT-1F-M-2e-stech` -> `*MEMANQ90E5089q{e-stech` 
* `*MEMANT-1F-M6ABCDEF` -> `*MEMANQ90E5091` 

I suppose the leading asterisk causes the problems.

**Comment by srowen** [comment]
It's hard to help without an example of the barcode?

**Comment by CharlyNapf** [comment]
Sorry. In the attached PDF file [TestBarcodeGeneration_with Patch-DevEnvironment.pdf](https://github.com/zxing/zxing/files/1038189/TestBarcodeGeneration_with.Patch-DevEnvironment.pdf) you find some examples (good and bad) with
- entered text (heading)
- screen shot with generated barcode (form on left side) and 
- result of the scanned barcode (text editor on the right side)

Here is an *overview*:

Nr | Barcode text  | With iText.jar  | With zxing 
-- | ------------- | --------------- | -------------
 1 | *MEMANT-1F-M5          | :x: *MEMANT-1F-M83 | :white_check_mark:
 2 | *MEMANT-1F-M6          | :x: *MEMANT-1F-M87 | :white_check_mark:
 3 | *MEMANT-1F-M7          | :x: *MEMANT-1F-M91 | :white_check_mark: 
 4 | *MEMANT-1F-M8          | :x: *MEMANT-1F-M95 | :white_check_mark:
 5 | *MEMANT-1F-M9          | :x: *MEMANT-1F-M99 | :white_check_mark:
 6 | *MEMANT-1F-M10         | :white_check_mark: | :white_check_mark:
 7 | *MEMANT-1F-M25         | :white_check_mark: | :white_check_mark:
 8 | *MEMANT-1F-MESTECH     | :white_check_mark: | :x: *MEMANQ90E5079ROO70 
 9 | *MEMANT-1F-M-2estech   | :white_check_mark: | :x: *MEMANQ90E5089q{estech 
10 | *MEMANT-1F-M-2e-stech  | :white_check_mark: | :x: *MEMANQ90E5089q{e-stech 
11 | *MEMANT-1F-M6ABCDEF    | :white_check_mark: | :x: *MEMANQ90E5091

**Comment by srowen** [comment]
If anything, the encoding is the issue, because other readers seems to read it the same way. However I don't know what the issue may be. You'd have to debug and see if you can determine the problem and a solution. See https://github.com/zxing/zxing/issues/624

**Comment by CharlyNapf** [comment]
Sorry, but the code it too complicated for me.
We decided to switch back to 'iText.jar'

**Comment by micjahn** [comment]
I think I know what happens. I testet it with "*MEMANT-1F-MESTECH". The encoder selects X12 as encoding mode for the first part "*MEMAN". After that it switches to EDIFACT but it doesn't add the codeword 240 to signal the change of the encoding mode. I added it manually and the barcodes are correctly generated. I think I can provide a patch.

**Comment by micjahn** [comment]
[issue_806.patch.txt](https://github.com/zxing/zxing/files/1039708/issue_806.patch.txt)

(next time I will create a PR...)

**Comment by srowen** [comment]
I don't think you can ignore `newMode` here? that doesn't seem to be the issue

**Comment by CharlyNapf** [comment]
Michael,  I tried your solution and it works all in my test cases.

Sean, please let me know, if you agree with Michael's solution or if you want to veto.

**Comment by srowen** [comment]
This doesn't seem like a correct solution but a hack. It ignores mode selection.

**Comment by micjahn** [comment]
No, it isn't a hack. It is the smallest possible fix. It uses the same approach which is already used in the EdifactEncoder class.
But on the other side you are right. There are better solutions but they need a new issue title like "avoid double calls to HighLevelEncoder.lookAheadTest".

**Comment by srowen** [comment]
Hm, it passes tests, which makes me a lot less worried this breaks encoding elsewhere.

Ah, so is the point that only ASCII mode correctly looks ahead for a new mode, and sets the mode switch char? the others don't, but Edifact actually just hands off to ASCII if it thinks mode should change, and ASCII encodation checks again. It's not actually going to use ASCII encodation, which would be wrong.

OK, now that makes sense to me. Yes I'd merge this, perhaps ideally with a comment about the logic. Slightly better would be to factor out the logic for switching modes and apply it everywhere, rather than check twice.

**Comment by srowen** [comment]
I tried refactoring, and it's actually pretty tricky because you can't latch to the new mode without finishing the current mode and its unlatching. I think your patch is best, I get it now.

**Comment by CharlyNapf** [comment]
Thanks a lot for you work.
