### ISSUE TITLE
I only want to scan EAN_13 barcode with EAN-2 Addon / EAN-5 Addon.

### ISSUE THREAD

**Issue by tribitinfotech** [zxing/zxing#808]
I only want to scan EAN_13 barcode with EAN-2 Addon / EAN-5 Addon.

I have used this code on barcode scan click button

new IntentIntegrator(MainActivity.this).initiateScan();
and in on activity result getting this

@override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
if (result != null) {
if (result.getContents() == null) {
Toast.makeText(this, "Cancelled", Toast.LENGTH_LONG).show();
} else {
Log.e("123", "code::" + result.getContents());
Log.e("123", "result::" + result.toString());
}
} else {
super.onActivityResult(requestCode, resultCode, data);
}
}
But getting only 13 character barcode not getting addon with it like EAN-2 Addon / EAN-5 Addon

Provide me proper guidance for getting this EAN-2 Addon / EAN-5 Addon along with barcode

My barcode is like below
![capture1](https://cloud.githubusercontent.com/assets/20172434/26589802/99cc9262-4576-11e7-885f-8932dc937f57.PNG)

Getting only this number 4190136702803 
I couldn't found any addon ofter this
I also want to get this 10018 Addon after scanning barcode @srowen 

Sir, Looking forward to your reply @srowen

**Comment by srowen** [comment]
This isn't a place to ask questions and now you're spamming

**Comment by tribitinfotech** [comment]
Sir, I really need answer for this. I am very sorry to you @srowen If I bother you. Please if possible provide me answer so It would be help to me lots off.

Thanks in advance
