### ISSUE TITLE
QR Code NotFoundException on text containing "=="

### ISSUE THREAD

**Issue by dsnezhkov** [zxing/zxing#809]
![screenshot_1460](https://cloud.githubusercontent.com/assets/210750/26608440/31939d4a-4561-11e7-96e1-67a08483c024.png)
Hello,

I am trying to read a chunk of Base64 encoded data with `QRCodeReader().decode(binaryBitmap, hintMap);`

 Everything works until the QRCode has `==` double equals characters (Base64 padding). 

Example: `ZG9kb2RvCg==`

If the offending characters are encountered I get `NotFoundException`.  I have tried various combinations of CHARACTER_SET in hints but so far no success.
```
hintMap.put(DecodeHintType.CHARACTER_SET, CharacterSetECI.UTF8);
hintMap.put(DecodeHintType.TRY_HARDER, true);
```

Screenshot of the QRCode is attached. Any solution or workaround is appreciated.

**Comment by srowen** [comment]
I'm not sure what you mean. This QR code encodes `ZG9kb2RvCg==` and successfully decodes as that text. There is nothing related to Base64 in the QR code spec.

**Comment by dsnezhkov** [comment]
Sean,

Thank you for the resonse. I should have made it clear. The QRcode is
generated from the below string elsewhere (producer), by a different
library. When I am reading the QRcode (the one attached), the decoder
apparently does not like the QRcode generated from this string. I have
zeroed in on the doble equals. A QRcode with a single equal gets decoded
just fine fro some reason.

I have access to the source for the producer, and I have verified that the
QRcode is properly generated. As a workaround, I am now replacing '==' with
another set of characters on the producer side, after zxing successfully
 decodes the QRcode with an alternative characters, I replace them back to
'=='.

 Was just wondering why this might be happening, and why '==' sequence is
special to zxing. Nothing else changes.

Thank you.

On May 30, 2017 6:29 PM, "Sean Owen" <notifications@github.com> wrote:

I'm not sure what you mean. This QR code encodes ZG9kb2RvCg== and
successfully decodes as that text. There is nothing related to Base64 in
the QR code spec.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zxing/zxing/issues/809#issuecomment-305037817>, or mute
the thread

**Comment by srowen** [comment]
I am saying you can plug this QR code into the online decoder at zxing.org and it decodes fine, so I think you are mistaken.
