### ISSUE TITLE
Barcode scanner does not scan when iOS is in portrait mode

### ISSUE THREAD

**Issue by LSMadsen** [zxing/zxing#810]
When trying to scan a barcode on my iPhone, it does not get recognized when the iPhone is in portrait mode.

I have tested with this code:

    new MobileBarcodeScanner
    {
       BottomText = "Tap to focus",
       CameraUnsupportedMessage = "This camera is not supported",
       CancelButtonText = Strings.Cancel,
       FlashButtonText = "Flash"
    }.Scan(new MobileBarcodeScanningOptions
       {
          AutoRotate = true,
          UseNativeScanning = true,
    });

And by doing this

    var scanPage = new ZXingScannerPage(new MobileBarcodeScanningOptions
       {
          AutoRotate = true,
          UseNativeScanning = true,
    });

    try
    {
       await PushModalAsync(scanPage);

       ZXingScannerPage.ScanResultDelegate onScanResult = null;
       onScanResult = async (result) =>
       {
          scanPage.OnScanResult -= onScanResult;

          try
          {
             scanPage.IsScanning = false;
             if (scanPage.IsTorchOn)
                scanPage.ToggleTorch();

             await PopModalAsync();
          }
          catch (Exception e) { }
       };

       scanPage.OnScanResult += onScanResult;
    }

But in neither ways the barcode is recognized 

I am using ZXing.Net.Mobile and ZXing.Net.Mobile.Forms version 2.2.9

And I do not get any Exceptions. The camera is just kept open.

**Comment by srowen** [comment]
This code has not been part of the project for a long time
