### ISSUE TITLE
screen resolution not exactly match with supported screen size 

### ISSUE THREAD

**Issue by gao746700783** [zxing/zxing#812]
screen resolution not exactly match with supported screen size 

### details

android zxing here.
my phone   480*854 ,while Supported preview sizes: 1920x1080 1280x960 1280x720 864x480 800x480 720x480 768x432 640x480 576x432 480x360 384x288 352x288 320x240 240x160 176x144 144x176 160x120 
can't find the exact screen size to match my situtation,

may be generate a 400*864 for my phone ??  how to do it

**Comment by srowen** [comment]
The app can't make your phone support new preview sizes.

**Comment by gao746700783** [comment]
i don't think this is the solution,and i have found more problems on this one;
