### ISSUE TITLE
How can i change scannig area size?

### ISSUE THREAD

**Issue by tlgbltcn** [zxing/zxing#815]
Hi,

I searched but I could not find a solution. I can't change in zxing class. How can i change scanning area size. I need more area.

Thank you.

**Comment by praveenshharma** [comment]
just replace getFramingRect() fn in CameraManager class to make the scanning area of Square shape..

public synchronized Rect getFramingRect() {
        if (framingRect == null) {
            if (camera == null) {
                return null;
            }
            Point screenResolution = configManager.getScreenResolution();
            if (screenResolution == null) {
                // Called early, before init even finished
                return null;
            }

            int width = findDesiredDimensionInRange(screenResolution.x, MIN_FRAME_WIDTH, MAX_FRAME_WIDTH);
            int height = findDesiredDimensionInRange(screenResolution.y, MIN_FRAME_HEIGHT, MAX_FRAME_HEIGHT);

            if (width > height) {
                height = width;
            }
            if (height > width) {
                width = height;
            }

            int leftOffset = (screenResolution.x - width) / 2;
            int topOffset = (screenResolution.y - height) / 2;
            framingRect = new Rect(leftOffset, topOffset, leftOffset + width, topOffset + height);
            Log.d(TAG, "Calculated framing rect: " + framingRect);
        }
        return framingRect;
    }

Hope this will work for you..

**Comment by tlgbltcn** [comment]
@praveenshharma  Thank you. i want to ask you something. CameraManager is locked class. How can edit this class. I think i need to add the whole Project.

**Comment by srowen** [comment]
@tlgbltcn you shouldn't be importing this code anyway; it's an app. You do not add this project to your project. You can however write your own app, and reuse parts of the source. (This is not a project question.)
