### ISSUE TITLE
Camera Focus Lost on Alert Dialog ?

### ISSUE THREAD

**Issue by praveenshharma** [zxing/zxing#818]
@srowen Why the camera lost its focus on Alert Dialog ? I don't know how, but if I get my scanning result on Alert Dialog rather than on ResultView then after dismissing the dialog, Scanning stopped working. After pressing back button, its working fine...??

**Comment by srowen** [comment]
I am not sure what you're referring to, but seems like your own code/app. This app doesn't present an alert dialog during scanning.

**Comment by praveenshharma** [comment]
@srowen Can you suggest me about this ? Suppose if i have to get your barcode result on alert dialog rather than on another view ? How can we resume the scanning after dismissing the dialog ?
Thanks if you can help.
