### ISSUE TITLE
dotCode

### ISSUE THREAD

**Issue by johan-schoeman** [zxing/zxing#819]
Sean, It would be great if you could incorporate the scanning of DotCodes.

**Comment by srowen** [comment]
Not sure what it is, and there is no code here. I'd have to close any request like this

**Comment by johan-schoeman** [comment]
Something like the DotCodes that you can see on this page

https://www.google.co.za/search?q=Dot+Code+image+barcode&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi2mZWmj8XUAhWIOsAKHbStAwMQ_AUIBigB&biw=1600&bih=754#imgrc=_&spf=1497710745573

**Comment by johan-schoeman** [comment]
For eg the image at the top left of the link in the above post.

It reads 
http://www.tec-it.com

When scanned with Manatee Works

https://manateeworks.com/dotcode

**Comment by chwzr** [comment]
Please reopen this. A dotcode can be generated with this lib: `http://bwip-js.metafloor.com/demo/demo.html`  Dot Code reading would be so super great, since there are only two closed source implementations of readers.

**Comment by NF117** [comment]
I'm also interested in a open source java implementation.
The Symbology is standardized by AIM-Association for Automatic Identification & Mobility.
Public review download is for free:
https://aimglobal.site-ym.com/store/ViewProduct.aspx?id=9039375
I found a helpful c implementation from zint
https://sourceforge.net/p/zint/code/ci/dotcode/tree/backend/dotcode.c

**Comment by Skalaw** [comment]
Is the chance to implementation dotcode in future ?

**Comment by sofronas** [comment]
I don't see any implementation of dotcode reader.
Is there any possibility to read dotcode codes in future?

**Comment by sofronas** [comment]
Thanks for your answer.
