### ISSUE TITLE
Unable to encode aztec codes correctly

### ISSUE THREAD

**Issue by OmkarAmberkar** [zxing/zxing#820]
I am trying to create an aztec code with the payload below for android app with the help of zxing. However, after feeding this into the aztec generator, I am unable to read this payload correctly after scanning the barcode. The reader linked to zxing decodes a completely different barcode payload.

Has anyone else seen this issue? Or am I generating the Aztec code incorrectly?

Thanks for the help

barcode_payload

```i¼\u0000\u0003\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000)X“}ôZv\u0002ô\u0000\u0000˜\u0012\u0012äNMGX†Ô\u0000\u0001Zv\u0002ô05\u0002\u0018T 64\u0011k\u0007m[\u000fç“‰¿RÙƒ¨<úýá‹M\u0002\u0019\u0000 É¼ÏØ\u0010Ë¢\u0003d·ã Í\u000bÚæ? Ÿ#+\u0017˜\u0000```

Code:

```
public static Bitmap createAztec(String str, int mQrWidth, int mQrHeight, String timestampStr) { 
        String aztecStr; 
        if (!TextUtils.isEmpty(timestampStr)) { 
            aztecStr = str + "|" + timestampStr; 
        } else { 
            aztecStr = str; 
        } 
        AztecCode aztecCode = com.google.zxing.aztec.encoder.Encoder.encode(aztecStr.getBytes()); 
        BitMatrix matrix = aztecCode.getMatrix(); 
        if (matrix != null) { 
            int width = matrix.getWidth(); 
            int height = matrix.getHeight(); 
            int[] pixels = new int[width * height]; 
            for (int y = 0; y < height; y++) { 
                int offset = y * width; 
                for (int x = 0; x < width; x++) { 
                    pixels[offset + x] = matrix.get(x, y) ? Color.BLACK : Color.WHITE; 
                } 
            } 
            Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888); 
            bitmap.setPixels(pixels, 0, width, 0, 0, width, height); 
            return Bitmap.createScaledBitmap(bitmap, mQrWidth, mQrHeight, false); 
        } 
        return null; 
    }
```

**Comment by srowen** [comment]
Not sure, you haven't included a barcode here. What happens when you encode, decode with something else for comparison?

**Comment by OmkarAmberkar** [comment]
![screenshot_20170617-123556](https://user-images.githubusercontent.com/11454450/27254618-d53b5b30-5359-11e7-802c-09e7d3c1d22b.jpg)

![image uploaded from ios](https://user-images.githubusercontent.com/11454450/27254692-dc398c98-535b-11e7-86ce-5eeb1c18e286.jpg)


Attached above is the barcode and the decoded value with zxing android barcode scanner. For other values it works perfect.

**Comment by srowen** [comment]
It contains binary data, apparently, not text. The barcode decodes fine, but the payload isn't what you're suggesting: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F11454450%2F27254618-d53b5b30-5359-11e7-802c-09e7d3c1d22b.jpg

I think there's maybe an issue with the translation from your source string to byte encoding? did you choose the encoding you intended?

**Comment by OmkarAmberkar** [comment]
@srowen Thank you for pointing that out. The problem was with incorrect byte encoding, I had to use "ISO-8859-1" charset.
