### ISSUE TITLE
The library is not able to detect barcode on the jpg attached

### ISSUE THREAD

**Issue by manmisra** [zxing/zxing#824]
![randombarcode1](https://user-images.githubusercontent.com/29576753/27339654-f4ffa95a-55f5-11e7-983a-61312b342b1c.jpg)

**Comment by manmisra** [comment]
Hi Sean,
May I know the reason why this issue has been closed ? Is this an expected behavior?

**Comment by srowen** [comment]
There's no image here, and "this doesn't scan" isn't a bug, and I am only accepting pull requests.

**Comment by manmisra** [comment]
![randombarcode1](https://user-images.githubusercontent.com/29576753/27380754-0c8e8eb2-569e-11e7-9c12-61e0f0f6720d.jpg)

**Comment by manmisra** [comment]
I am trying to upload an .jpg image here . It does show up as uploaded but its not accessible . Is there any other way I could send you the image for review. I am not sure why this behavior ( the library is unable to detect barcodes on image) is not termed as a bug .
