### ISSUE TITLE
Is it possible to get a copyright notice for this project?

### ISSUE THREAD

**Issue by jpgtama** [zxing/zxing#825]
Can you provide one?

**Comment by srowen** [comment]
Eh, https://github.com/zxing/zxing/blob/master/LICENSE ?

**Comment by jpgtama** [comment]
Can you provide a notice with format list this?  Copyright [yyyy] [name of copyright owner]

**Comment by srowen** [comment]
These statements are in the source files. Did you look? they are not attributed to one person because hundreds of people own individual copyright in contributions. Year is not relevant.

**Comment by jpgtama** [comment]
Thank you. My fault. I got that.
