### ISSUE TITLE
Can you add a method? Add a logo picture to the center of the QR code.

### ISSUE THREAD

**Issue by b1234569856** [zxing/zxing#828]
Can you add a method? Add a logo picture to the center of the QR code.

**Comment by hardikm9850** [comment]
This is a reasonable requirement, why was it closed @srowen ?

**Comment by srowen** [comment]
This is a barcode generator and logos are not part of barcodes. I actually think this is obviously not something that belongs in the library. There are image manipulation tools and libs that can do this.

**Comment by hardikm9850** [comment]
Agreed.
