### ISSUE TITLE
javaweb  read QRCode   NotFoundException

### ISSUE THREAD

**Issue by 15991711351** [zxing/zxing#830]
![default](https://user-images.githubusercontent.com/10155058/27766919-0239e0f4-5f15-11e7-93c4-3568effd7efc.jpg)

`public static void decode(String filePath) {  
		 
		 MultiFormatReader formatReader = new MultiFormatReader();
			 
		 File file = new File(filePath);
		 BufferedImage image = null;
		try {
			image = ImageIO.read(file);
		} catch (IOException e1) {
			// TODO 自动生成的 catch 块
			e1.printStackTrace();
		};
		 LuminanceSource source = new BufferedImageLuminanceSource(image);
		 Binarizer  binarizer = new HybridBinarizer(source);
		 BinaryBitmap binaryBitmap = new BinaryBitmap(binarizer);
		 Map hints = new HashMap();
		 hints.put(DecodeHintType.CHARACTER_SET, "UTF8");
		 hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
		 Result result = null;
		try {
			result = formatReader.decode(binaryBitmap,hints);
			 System.out.println("result = "+ result.toString());
			 System.out.println("resultFormat = "+ result.getBarcodeFormat());
			 System.out.println("resultText = "+ result.getText());
		} catch (NotFoundException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}
		 
	}  `
![222](https://user-images.githubusercontent.com/10155058/27766924-1533bb12-5f15-11e7-9c3e-1a7acf6c8d87.jpg)

![1111](https://user-images.githubusercontent.com/10155058/27766923-11e291d6-5f15-11e7-9815-9747217257a7.jpg)

**Comment by 15991711351** [comment]
why?

**Comment by srowen** [comment]
The library reads it fine: `http://weixin.qq.com/r/M6JSSu7EKLNXraop9-ch` 
You're asking for help debugging your code and that's not on-topic here.

**Comment by 15991711351** [comment]
No Barcode Found
https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F10155058%2F27766919-0239e0f4-5f15-11e7-93c4-3568effd7efc.jpg
