### ISSUE TITLE
iOS - scanning from web pages

### ISSUE THREAD

**Issue by emdewu** [zxing/zxing#831]
Have a question regarding BarcodeScanner - An iOS application that captures video from the camera, scans for barcodes and displays results on screen - https://github.com/TheLevelUp/ZXingObjC Is there any possibility to use this application in the middle of the flow of my webApp.  It means, I would like to invoke scaner successfully from my webpage, scans the barcode and sends the code back to same(current) web-page.
Please for any suggestions for this solution.

There is also information on https://github.com/zxing/zxing/wiki/Scanning-From-Web-Pages that:
"Note that this functionality will be available on the iPhone app Barcodes. iOS works differently, and so the URL pattern must instead use the zxing://scan/ URL"
Problem is, that I can't find the Barcodes application in App Store.

Thank you in advance for your help

**Comment by srowen** [comment]
Oops, I should remove those references from the wiki. The iOS / objective C code was removed a while ago from this project. I think you're asking about a different project now.
