### ISSUE TITLE
Using in Web page

### ISSUE THREAD

**Issue by LedurFelipe** [zxing/zxing#832]
I'm sorry for my English, I'm brazilian.

I'm developing a web page that when I click on the input, opens the Barcode Scanner (application) and performs the reading and reloads the previous page and GET is inserted into the input, but in the last week, when I do the process,  it says To scan code with your mobile camera you need to install free Barcode Scanner -app. But it's installed on your smartphone
![19749539_1339358262849352_237059752_o](https://user-images.githubusercontent.com/17623076/27795706-7bce119c-5fdd-11e7-8b3f-39ed1fd19dcb.png)

**Comment by ADENHAM** [comment]
JESUS IS LORD
