### ISSUE TITLE
Cropping an image reads differently

### ISSUE THREAD

**Issue by bobjase** [zxing/zxing#837]
When reading a CODE-128 barcode from an image, ZX cannot read it properly (it will sometimes add random chars in between).

However, if I crop the image to remove whitespace from the edges, ZX can successfully read the barcode. 

Here is a video explaining the issue:  https://www.screencast.com/t/BnjtDyLB

[Images.zip](https://github.com/zxing/zxing/files/1140042/Images.zip)

**Comment by srowen** [comment]
It doesn't add random chars, but might be seeing a different barcode. Make sure you are only scanning for Code-128. Yes, cropping is helpful if you know where the barcode is. None of this is a bug.

**Comment by bobjase** [comment]
We specifically told it to look for only code128.

Why would cropping it make it read differently?

**Comment by srowen** [comment]
Cropping could affect a number of things indirectly, but primarily, how it turns the image into black/white. It's based on samples of regions of the image and overall image.
