### ISSUE TITLE
Failed to detect and decode DataMatrix

### ISSUE THREAD

**Issue by andresmrm** [zxing/zxing#841]
Hello! I tried to decode de following image using `Barcode Scanner` app and https://zxing.org website. Both say they can't find a barcode in the image.

But I was able to decode the image using this website https://online-barcode-reader.inliteresearch.com/. It says the content is `rebrand.ly/trans5af1` and displays this extra metadata: Length: 20, Rotation: left, Module: 10.8pix, Rectangle: {X=92,Y=202,Width=219,Height=218}

[![tmp_7479-_IMG_20170730_1009531919415075.jpg](https://s3.postimg.org/8xqrfl2v7/tmp_7479-_IMG_20170730_1009531919415075.jpg)](https://postimg.org/image/ovzh5px33/)

**Comment by srowen** [comment]
It's not valid without a quiet zone around it.

**Comment by andresmrm** [comment]
Thanks for the reply!
I know almost nothing about DataMatrixes, but being this an inverted DM, shouldn't the dark space around it be considered the quiet zone? It does has the L and dotted border (finder pattern), and seems similar to all the other DM I've found in the web...

**Comment by srowen** [comment]
Oh I see, it's inverted. That's an optional mode, so it's not scanned for by default. You can invert the image and scan it and it will detect it. This says `rebrand.ly/trans5af1`

**Comment by andresmrm** [comment]
Didn't see that option in the app config menu. After checking it the image was decoded.
Thanks! =)

**Comment by xzessmedia** [comment]
thanks to not share thee answer and making anything here useless
