### ISSUE TITLE
sharing screen of android contacts with e164 numbers is showing the wrong number

### ISSUE THREAD

**Issue by Trolldemorted** [zxing/zxing#842]
Steps to reproduce:

- have a contact with a phone number in the e164 format
- share the contact with the barcode scanner

![1845297871461598955_2](https://user-images.githubusercontent.com/10261186/28911439-cd6b6656-7830-11e7-88dd-ead3dab5c2e6.png)

As you can see, the barcode scanner is displaying the country prefix (+49 since it is a german phone number), but it somehow cut off the `+` character.

The data encoded in the qrcode is correct, though.

**Comment by srowen** [comment]
Hm, it is just showing whatever Android returns when it asks for the contact info. It doesn't add or strip anything. Do you see anything in the code that does otherwise?

**Comment by Trolldemorted** [comment]
No, i didn't have a look yet.

The vcard (or whatever it is) "inside" the qrcode is correct though:
![432364321742048573](https://user-images.githubusercontent.com/10261186/28911875-4d9e57c4-7832-11e7-97ba-e21081de1cf2.png)

Are you also experiencing this issue? This could be os/rom related, for all we know. I am running Android 7.1.2, lineageos 14.1, a build from july.

**Comment by srowen** [comment]
Can you send me the QR code offline so I can try to reproduce it? Or post a reproduction here that doesn't contain any sensitive info

**Comment by Trolldemorted** [comment]
are the reproduction steps in the first post not working for you?

**Comment by srowen** [comment]
I'm not sure what e164 format is and the detail is redacted above. To avoid doubt I'm asking for a concrete reproduction

**Comment by Trolldemorted** [comment]
e164 is a standard for formatting international [telephone numbers](https://en.wikipedia.org/wiki/E.164).

Such a number consists of
- the `+` sign (to indicate that a country prefix is appended)
- the country code (e.g. `1`, for the united states and canada, `49` for germany, [full lists are available](https://countrycode.org/)
- the rest of the phone number

To convert a localized number (i.e. numbers from contacts from your country which start with a `0`, you
- remove all whitespaces
- replace the `0` with `+COUNTRYPREFIX`

**Comment by srowen** [comment]
OK, if that's all it is, yes I understand. I also see that the "+" disappears though it's correct in the barcode. It must be a cosmetic issue. According to the logs it reads the phone number correctly:

```
Sending bundle for encoding: Bundle[{... secondary_phone=+44..., phone_type=2, ...}]
```

Digging further I remembered from the code that MECARD seems to require that the field only contains digits, but that's just based on:

https://web.archive.org/web/20160304025131/https://www.nttdocomo.co.jp/english/service/developer/make/content/barcode/function/application/addressbook/index.html

(Try switching to vCard encoding with the a>z button at the top right and the + appears)

So I don't know if the right thing is to actually allow +, or convert to 00. I'm inclined to allow +. Many other examples show `TEL:+1...`. I suppose the app could also default to vCard.

**Comment by Trolldemorted** [comment]
allowing `+` sounds reasonable, since it matches the content of the qrcode and is a valid part of a phone number.

Thanks for fixing this! Can you estimate when this change will arrive in the playstore version?

**Comment by srowen** [comment]
I was planning to release a '10th anniversary' release in a couple months
