### ISSUE TITLE
Sometimes wrong,  gives 8 digit Number

### ISSUE THREAD

**Issue by ouyangzn** [zxing/zxing#848]
### Bug Reports
user zxing3.0.0, but sometimes get wrong result with 8 digit Number.
version : zxing 3.0.0
mobile : Google pixel and honor 6

[relative issue](https://github.com/dm77/barcodescanner/issues/344#event-1203515743)

**Comment by ouyangzn** [comment]
Hi, @srowen , I don't know why close the issue.
My fault , the version is zxing 3.3.0. And the image is here:
![qrcode1](https://user-images.githubusercontent.com/8808376/29305960-d80530d2-81cd-11e7-9c3b-4596cea9ad05.jpg)

**Comment by srowen** [comment]
https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F8808376%2F29305960-d80530d2-81cd-11e7-9c3b-4596cea9ad05.jpg

**Comment by ouyangzn** [comment]
@srowen 
Your result is correct, but sometimes it's wrong, here is the result i got:
![](https://user-images.githubusercontent.com/8808376/29068443-73cce18c-7c69-11e7-9cb1-5c4d15b026e6.png)

**Comment by srowen** [comment]
It's always possible to misread a different format. You should only scan for QR codes

**Comment by ouyangzn** [comment]
Ok, thanks.
