### ISSUE TITLE
Unable to scan the QR code

### ISSUE THREAD

**Issue by tianshaokai** [zxing/zxing#852]
![1502872278](https://user-images.githubusercontent.com/6706496/29356691-a046fe98-82a7-11e7-894a-3ee20990b7ae.png)
![1502874059](https://user-images.githubusercontent.com/6706496/29355684-8d31e51e-82a4-11e7-864a-97524d301ad9.png)

**Comment by tianshaokai** [comment]
Why close it？

**Comment by srowen** [comment]
It's not a bug. The QR codes aren't standard, and might not be read. You didn't offer any proposed change.

**Comment by tianshaokai** [comment]
The first picture can not, the second picture is ok.
