### ISSUE TITLE
Decoding Chinese Character Error

### ISSUE THREAD

**Issue by elaine1234** [zxing/zxing#857]
I’m using zxing to decode a QRcode which contains Chinese Character like "二维码解码". The code can be decoded using apps such as wechat, but when I used zxing to decode this, I got nothing.
I've tried to set the hints like this
```
hints.put(DecodeHintType.CHARACTER_SET, "gbk");
hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
hints.put(DecodeHintType.POSSIBLE_FORMATS, BarcodeFormat.QR_CODE);
```
Can any one help?

**Comment by shengye102** [comment]
Is your problem solved? I also encountered the same problem
