### ISSUE TITLE
Cannot scan a specific code 93 type barcode

### ISSUE THREAD

**Issue by saravanakumarv86** [zxing/zxing#859]
Hi, i am new to this topic and using Zxing library android for scanning QR code and Bar code. I have a barcode(Code 93) which is scanned and decoded in Zbar library but not in Zxing. Can someone please help me on this.
![barcode-code93](https://user-images.githubusercontent.com/2579754/29602981-f69c75d6-87ff-11e7-9b7c-dd8f9d6c9ccb.jpg)

**Comment by srowen** [comment]
I think it's a combination of light printing (bars are too think) and overexposure, but, not a bug
