### ISSUE TITLE
Scanning BLUE & Black QR Code instead of WHITE & BLACK

### ISSUE THREAD

**Issue by prakash8083** [zxing/zxing#860]
I want to read custom QR which has Blue & Black combination instead of White & Black.

I changed BitMatrix to accept blue but its not reading.
Let me know if it can be acheived by inverted scan but with blue & black or any other color except white & black. 

![custom scan](https://user-images.githubusercontent.com/5716108/29739690-84a05a60-8a61-11e7-93ed-6ef83949a803.png)

**Comment by srowen** [comment]
This isn't valid, as it's effectively dark-on-dark.

**Comment by prakash8083** [comment]
Can i use any other color combinations keeping balck ? eg. gray & Black and so on.

 I want to prevent other QR codes to read it (If we can achieve it by minor changes)
