### ISSUE TITLE
vCard TEL URIs are not parsed correctly.

### ISSUE THREAD

**Issue by dseomn** [zxing/zxing#863]
I have a QR code of a version 4.0 vCard with `TEL;VALUE=uri;TYPE=cell:tel:+1-[redacted]`. When I scan the barcode and tap "Dial number", the dialer pops up with `8351[redacted]` instead of `1[redacted]`. Since "tel" maps to 835 on the numeric keypad, it seems that zxing is parsing the field as plain text instead of a URI.

**Comment by srowen** [comment]
You're right, VALUE=uri is not handled. Although I'm kind of uneasy about having it actually dereference URIs in general, it seems reasonable to use the scheme-specific part of the URI as the value in this case. It'll work here.

**Comment by srowen** [comment]
Should be addressed in https://github.com/zxing/zxing/commit/4ddc8c9e490fd6a9ef6897d9862dd4043916f837
