### ISSUE TITLE
Where can i find a good document to customize the viewfinder ? 

### ISSUE THREAD

**Issue by ahmedeltaher** [zxing/zxing#864]
I did search to understand what is the difference between
```  compile 'com.google.zxing:android-core:3.3.0' ```
```    compile 'com.google.zxing:core:3.3.0'  ```
```    compile 'com.google.zxing:android-integration:3.3.0'```
and which one should I use ! 
it is really hard to find how to embedded the Zxing scanner in my app with gradle without documentation . 
and I would like to customize the viewfinder , but there is no documentation for that  . 
could you provide a documentation ` how to customize the viewfinder`

**Comment by srowen** [comment]
None of the above. There is no library you're intended to use as an app, hence no docs. You're encouraged to build your own app using core and android-core.
