### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by feb07** [zxing/zxing#867]
java.lang.ArrayIndexOutOfBoundsException
src.length=1382400 srcPos=1416960 dst.length=1920 dstPos=0 length=1920
com.google.zxing.h.a(SourceFile:73)
1 java.lang.System.arraycopy(Native Method)
--
2 com.google.zxing.h.a(SourceFile:73)
3 com.google.zxing.common.g.a(SourceFile:62)
4 com.google.zxing.b.a(SourceFile:66)
5 com.google.zxing.oned.q.b(SourceFile:132)
6 com.google.zxing.oned.q.a(SourceFile:54)
7 com.google.zxing.e.b(SourceFile:171)
8 com.google.zxing.e.a(SourceFile:85)
9 com.google.zxing.client.android.g.a(SourceFile:89)
10 com.google.zxing.client.android.g.handleMessage(SourceFile:58)
11 android.os.Handler.dispatchMessage(Handler.java:102)
12 android.os.Looper.loop(Looper.java:150)
13 com.google.zxing.client.android.i.run(SourceFile:110)

**Comment by srowen** [comment]
This looks like a stack trace from an old obfuscated build or else your own app. There is no reproduction

**Comment by feb07** [comment]
It is in com.google.zxing.client.android.DecodeHandler.handleMessage(SourceFile:58) : decode((byte[]) message.obj, message.arg1, message.arg2);

**Comment by srowen** [comment]
Obviously, question is what input or device causes it.
