### ISSUE TITLE
Problems with Russian symbols.

### ISSUE THREAD

**Issue by VladoCC** [zxing/zxing#868]
Hello, I'm generating QR codes on Android with this code:
`MultiFormatWriter writer = new MultiFormatWriter();
                try {
                    BitMatrix bitMatrix = writer.encode(codeText, BarcodeFormat.QR_CODE, 500, 500);
                    int w = bitMatrix.getWidth();
                    int h = bitMatrix.getHeight();
                    code = Bitmap.createBitmap(500, 500, Bitmap.Config.ARGB_8888);
                    for (int y = 0; y < h; y++) {
                        int offset = y * w;
                        for (int x = 0; x < w; x++) {
                            code.setPixel(x, y, bitMatrix.get(x, y) ? 0xff000000 : 0xffffffff);
                        }
                    }
                    codeImage.setImageBitmap(code);`

This is working perfectly for English, but when I am trying to create code with Russian symbols, then this symbols in output text generated by QR code reader shows as "?".
What I need to do to fix this issue?

**Comment by VladoCC** [comment]
I gave you my encoder code.
Can you check it and say what's wrong?
Decoder work fine for codes generated with other encoder then zxing. And two decoders can't decode QR code generated in zxing.

**Comment by srowen** [comment]
You haven't set the text encoding, for example, to UTF-8. 
You haven't ruled out a display problem on the decoder. ? means you're missing a font which is nothing to do with the app.
You haven't presented any QR code you can't decode.

**Comment by VladoCC** [comment]
I check decoder using QR code with same text generated [here](http://ru.qr-code-generator.com/) and it worked fine.

How can I set text encoding?

![image](https://user-images.githubusercontent.com/15711952/30247509-d9d8b050-9659-11e7-8ed1-5bbccda4f4e4.png)
This code created from string "http://тест.рф|@|0" and all decoders decode it as "http://????.??|@|0"

**Comment by VladoCC** [comment]
![image](https://user-images.githubusercontent.com/15711952/30247606-a92e654c-965b-11e7-9b5a-b157fc0aeaed.png)
This code created from string "http://тест.рф|@|0" and all decoders decode it as "http://тест.рф|@|0". 
This code generated [here](http://ru.qr-code-generator.com/) and this is not the same code as zxings'

**Comment by srowen** [comment]
Both of these decode correctly as you have given. 
https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F15711952%2F30247606-a92e654c-965b-11e7-9b5a-b157fc0aeaed.png

The first one does really encode "????.??". I think you have not set the encoding correctly or there is an error in the string you feed in. As you can see from the second one, the decoder works fine.

**Comment by VladoCC** [comment]
Okey. How I need to set encoding? You can see code of my encoder.
`codeText` is an ordinary String created as: `codeText = links[which] + "|@|" + types[which];`. Links is a String[] and types is int[].

**Comment by srowen** [comment]
Try adding the hint `EncodeHintType.CHARACTER_SET` set to "UTF-8"

**Comment by VladoCC** [comment]
I am only need to add `EncodeHintType.CHARACTER_SET` or do anything else?

**Comment by srowen** [comment]
It needs to map to "UTF-8", yes.

**Comment by VladoCC** [comment]
Now this issue is really closed. Thanks!
