### ISSUE TITLE
Last release lacks APK attachment

### ISSUE THREAD

**Issue by IzzySoft** [zxing/zxing#869]
The [Latest release](https://github.com/zxing/zxing/releases/latest) lacks the `.apk` file. Could you please attach that (and continue attaching it for future versions)? Thanks!

**Comment by zhengshanwang** [comment]
what ?

**Comment by srowen** [comment]
(Questions should go to the mailing list.)
The actual app is versioned and released separately and you can find its APKs in separate releases.
https://github.com/zxing/zxing/releases/tag/BS-4.7.6

**Comment by IzzySoft** [comment]
The last APK file was attached for v4.7.6 (BarcodeScanner-4.7.6.apk). There's a release tagged 3.3.0, but it has no APK attachment. Maybe I'm mistaken and that's not the app but just the library? Are you mixing two different things within one repo, one being the library and the other the app? In that case, to avoid confusion, wouldn't it be preferable to use different repos?

**Comment by srowen** [comment]
The overall project version is 3.3.0 and you can see releases of its non-app artifacts in Maven. There used to be several apps, and it didn't make sense to release them all in lock-step. Now there's really just one. Yes if I started the project today it'd be a separate repo, but it started 10 years ago in SVN / Google Code where that wasn't simple. I wouldn't move it now, especially as it's just the one app, and so many people are used to it being where it is.

**Comment by IzzySoft** [comment]
Understood, thanks again. No prob, was just a little confusing. With the background in mind it's pretty clear. And there are other projects with a similar setup, where the "last release" not always contains all "flavors" (e.g. changes to the desktop component being released without changes to the Android app of course have no APK attached either). By the tag names used it should be easy enough to tell; I was just told to "please include the latest version with [your repo](https://apt.izzysoft.de/fdroid/)" :wink:

Speaking of which: As your app isn't on F-Droid, would you oppose if I'd include it with my repo, just picking up the always latest APK from here?

**Comment by srowen** [comment]
You can redistribute the binaries as they're just Apache License 2.0 - licensed. If it's the exact same binary you can represent it as the same as the official release, though wouldn't represent an F-Droid distribution as an official distribution channel. It's just Github and Play, officially.

**Comment by IzzySoft** [comment]
Sure – that's what I've meant. I don't want to put an additional burden unto you, so I'd pick exactly the `.apk` you provide – expecting it to be the very same you already support anyway. My repo isn't that "official" either (F-Droid knows about it and gives me "thumbs up" for filling a gap, but that's all).

So thanks, I'll then pick it ASAP :wink:
