### ISSUE TITLE
Image with circle logo decode failed

### ISSUE THREAD

**Issue by leo108** [zxing/zxing#874]
![2](https://user-images.githubusercontent.com/1551716/30465259-a0ab51cc-9a08-11e7-86da-84e4bc8acbb8.jpg)

https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F1551716%2F30465259-a0ab51cc-9a08-11e7-86da-84e4bc8acbb8.jpg results in `No Barcode Found`

**Comment by srowen** [comment]
This QR code looks invalid. It has dimension 42, but should be 41 if it intend to be version 6. It is either an old version of the QR code format that's no longer supported, or the encoder is wrong.

**Comment by leo108** [comment]
@srowen But some online tools can decode this image, e.g.

https://online-barcode-reader.inliteresearch.com/

http://www.onlinebarcodereader.com/

**Comment by srowen** [comment]
I think it could be an old pre 2005 format? But a code of dimension 42 is not valid from the 2005 spec, and that's why this fails. Try rendering the same QR at zxing.appspot.com
