### ISSUE TITLE
got one kind of EAN13 barcode can never not be recognized

### ISSUE THREAD

**Issue by lchad** [zxing/zxing#879]
![image](https://user-images.githubusercontent.com/6659831/30678217-4515920e-9ec3-11e7-8cda-e885b41ebbe0.png)

**I'm using Zxing 3.3 in Android, the barcode upon can never be recognized,I guess this barcode is not so standard(the right white blank is too short, and not very clear).so I create the other new Image by this one.**

![image](https://user-images.githubusercontent.com/6659831/30678286-beeeb114-9ec3-11e7-941e-d30c08be5f2a.png)

**the new bar code can be recognize easily.so what can I do to recognize the first EAN 13 barcode?
thank you!**

**Comment by srowen** [comment]
This isn't a bug. It's missing required quiet zone on the right, yes.

**Comment by lchad** [comment]
@srowen is there any solution, such as how to add the missing required quiet zone in the OneDReader or HybridBinarizer?
