### ISSUE TITLE
QR codes scan return error（扫描联系人二维码返回错误）

### ISSUE THREAD

**Issue by huannan** [zxing/zxing#882]
I had a problem with Android development: when I was using zxing to scan complex contact QR codes, the scan results in occasional commodity and text.

According to my analysis, the reason of the problems is that the image frame inside the scanning of the local features with the bar code, so it is identified as the recognition algorithm of bar code, but the code is of no practical significance, therefore through the network query, and can query to the bar code corresponding to the product, so there are the phenomenon described in bug. Excuse me, is there a solution?

Chinese：
我在Android开发中遇到一个问题：我在使用zxing扫描比较复杂的联系人二维码的时候，扫描结果偶尔会出现商品、文本。

根据我的分析，该问题出现的原因是，扫描的图像帧里面，局部区域特征符合了条形码，因此被识别算法识别为条形码，但该条形码是没有实际意义的，因此通过联网查询时，并不能查询到该条形码对应的商品，所以出现了bug中所描述的现象。请问一下这是否有解决办法？

Contact Me：1435378192@qq.com

**Comment by srowen** [comment]
I have no idea what this means

**Comment by huannan** [comment]
sorry，I translate it better now：

I have a problem in the process of Android developing: when I scan some complex QR code of contacts by zxing, the results occasionally are "PRODUCT" or "TEXT".

My analysis is as follow: part of the scanned picture is consistent with the bar code, then that part was recognized as bar code. But the recognized “bar code” is not existing, making the internet inquiry failed, namely no commodities’ information. Thus leading to the results described in the bug. Is there any way to solve this problem?

Contact Me：1435378192@qq.com

**Comment by srowen** [comment]
If you mean it is a false positive, yes it is possible. You should restrict the scan to only QR codes

**Comment by huannan** [comment]
Thanks. But I'm developing a system called APP (Camera). Both QR codes and bar codes should be scanned because it requires a universal function. I can do nothing about it, either

**Comment by huannan** [comment]
system APP
