### ISSUE TITLE
Scan part only around red line

### ISSUE THREAD

**Issue by JKorsten** [zxing/zxing#883]
Hey,

I was wondering if it is possible to have a scan only around the red line.
What I have now is the preview screen, which is the entire screen of my phone and in the middle there is a red line.

Now it is possible I have multiple barcodes in my screen and I put one underneath my red line. But it's never certain which barcode will be scanned.
Is it possible to have a full screen camera view, but a scan part which is only around the red line?

I hope my question is clear.

Thanks,

JKorsten

**Comment by srowen** [comment]
It scans the whole area of the reticle. Of course, some barcodes aren't 1D and so you can't just on and by the line.
