### ISSUE TITLE
Bug: Cannot read the barcode

### ISSUE THREAD

**Issue by bimusiek** [zxing/zxing#889]
Hey, maybe someone can give me some hint how to fix it or what to do. 

This barcode is not read by Zxing:
<img width="368" alt="wrong_barcode" src="https://user-images.githubusercontent.com/1025588/31506377-88f45d4c-af77-11e7-9604-9d8035a56654.png">

And the same one but directly extracted from PDF:
![tmp8y3m9dcl](https://user-images.githubusercontent.com/1025588/31507358-b5875514-af7a-11e7-8ba4-95746aae1d4a.png)

But when using some online tool, it is properly decoded. 

Any ideas what is wrong with it? I downloaded it directly from SAS Boarding Pass.

**Comment by srowen** [comment]
I ran it through the debugger and it says that it has way too many errors. This leads me to believe the encoding is somehow not quite normal PDF 417 or something. I don't think it's a library problem.

**Comment by bimusiek** [comment]
@srowen It is decoded correctly [here](http://online-barcode-reader.inliteresearch.com) + this is taken directly from SAS airline boarding pass. Which means it is correctly scanned by all airports scanners. 

I am not sure why SAS generated it like this, but in my opinion, the issue should not get closed.

**Comment by srowen** [comment]
I'm not sure then. This doesn't pass the standard PDF417 EC routine as far as I can tell, but I don't know the format well enough to say whether there's some other mode or variant here. I don't work on this project anymore, but will look at pull requests. This won't be implemented otherwise
