### ISSUE TITLE
Zxing unable to read code-128 barcode

### ISSUE THREAD

**Issue by enyedelacruz** [zxing/zxing#893]
Hi devs! Good day, I am currently working on project using zxing, I have this barcode that can't be read by zxing. I have attached the barcode sample, hoping for adjustment through this it will be huge help. Thank you! 
![img_6557](https://user-images.githubusercontent.com/28749486/31858054-58568d24-b6ff-11e7-8005-4421d59704f6.JPG)

**Comment by srowen** [comment]
I think it's just a matter of the dark and slightly blurred image being hard to read.

**Comment by enyedelacruz** [comment]
Hello Srowen, the attachment I sent you is printed on the card already which is really cant read by the zxing, if it looks dark and slightly blurred image maybe it's by the shot but really when it is being tested on card it is not readable, maybe by configuration of height or width? Please try, please. Thank you!

**Comment by srowen** [comment]
Maybe, but I don't work on this project now. Unless you're proposing a code change, I'd close anything like this.
