### ISSUE TITLE
Professionnal inquiry - Support Needed on Zxing for mobile APP

### ISSUE THREAD

**Issue by WillWellDone** [zxing/zxing#895]
Hello,

We are big retail company that is making Mobile APP and plan to use Zxing for scanning features.

The library has been installed but we still have some "issue" on 3 points

- Scanning very "small" barcodes printed on products
- issue on portrait and landscape scanning 
- Delay on "focus" and response time

Anyway I need to know if this is the right place and if this community is able to accompany our team on those topics.

This is my first post and hope it fits the requirement. Our developpers would be able to add details to our needs.

Thanks

Guillaume

**Comment by srowen** [comment]
There's no support available -- this project is not actively maintained. Patches for bug fixes are still accepted.

**Comment by WillWellDone** [comment]
OK ! thanks for the feedback.
