### ISSUE TITLE
How get correct  QR code

### ISSUE THREAD

**Issue by ZeroCrack** [zxing/zxing#896]
i  scan  a QRcode, after handleDecodeInternally(Result rawResult, Bitmap barcode) method.   i get a byte[] from  rawResult.getRawBytes() method.     rawResult.getRawBytes() this method what is it return means？
now  if i  hava  this byte[]   how to generate QRcode。 
i use  BarcodeFormat.AZTEC  to generate QRcode but not correct  .

**Comment by srowen** [comment]
It's the raw codewords in the QR code. Aztec is not QR code. Please ask questions on the mailing list.

**Comment by ZeroCrack** [comment]
if i have byte[]  codewords , can i generate QRcode ?
