### ISSUE TITLE
Finding false QR Code centers

### ISSUE THREAD

**Issue by herman1vdb** [zxing/zxing#897]
Problematic QR Code:
![image](https://user-images.githubusercontent.com/8955362/32093202-cb1d737c-bafb-11e7-899e-98686c6d4b55.png)

Finding (also changing the angle of the QR code to 45° scans successfully):
![image](https://user-images.githubusercontent.com/8955362/32093249-f5e1f402-bafb-11e7-84c1-daaf8513821a.png)

After further investigation it seems the vertical and horizontal pattern is accepted at the above incorrect center, for this particular QR Code.
Which lead me to come across these concerns:

It seems at [FinderPatternFinder.java:78](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java#L78)
`pureBarcode = hints != null && hints.containsKey(DecodeHintType.PURE_BARCODE);`
the default for `pureBarcode` is false (I'd rather assume most QR Codes are pure monochrome?)
eg. `pureBarcode = hints == null || hints.containsKey(DecodeHintType.PURE_BARCODE);`

In any case at [FinderPatternFinder.java:496](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java#L496) it seems that the diagonal check is ignored when it is not monochrome (`!pureBarcode || crossCheckDiagonal(...`). This seems strange can someone please explain the reasoning behind this, I don't understand it. According to me it should still do the check regardless if it is a `pureBarcode` or not.

I'll submit a pull request if required.

**meaning of Pure Barcode:**
```
  /**
   * Image is a pure monochrome image of a barcode. Doesn't matter what it maps to;
   * use {@link Boolean#TRUE}.
   */
  PURE_BARCODE(Void.class),
```
_DecodeHintType.java_

**Comment by srowen** [comment]
Yes, exactly, the heuristic will accept those because they look like finder patterns if you only look above and to the sides. It's optimizing for images of barcodes, where this false positive essentially doesn't happen.

"Pure barcode" mode was made for these cases, because frequently people want to decode a barcode image like these, not a picture, and should be trivial to find the corners just by looking at where the black pixels start. It is not the default, no. It is not a mode for black-and-white in general. It is a mode for non-photos.

This works with PURE_BARCODE on, right? does for me.

The diagonal check would be too strict for photos. I think it was there to avoid false positives like this in the image above. But, is your point that pureBarcode is always false if it ever tries to find finder patterns? in PURE_BARCODE mode it doesn't even try.

That is a good point and I think this is actually dead code from ages ago. I tried removing crossCheckDiagonal and it was fine; it's not actually called.

**Comment by herman1vdb** [comment]
Thanks I understand the prupose of PURE_BARCODE better now.
Yes, when PURE_BARCODE is on it works as it runs through the diagonal check.
I'm not sure how it would be too strict for photos? I mean it still executes the same way?

> But, is your point that pureBarcode is always false if it ever tries to find finder patterns? in PURE_BARCODE mode it doesn't even try.

Not sure what you mean by this. I'm not 100% familiar with this project, actually don't even work with Java. (I'm a C# developer, currently having to do a mobile app as well)
**Some background:**
I've created an Ionic app that uses the corodva plugin [phonegap-plugin-barcodescanner](https://github.com/phonegap/phonegap-plugin-barcodescanner) which inturn uses a compiled .aar file from zxing by means of [barcodescanner-lib-aar](https://github.com/EddyVerbruggen/barcodescanner-lib-aar). So I'm not sure how all this works together. (However, assume it's sends through a photo bitmap)

Regardless:
It seems that the `hints` never gets set and therefore causes the `pureBarcode` to be `false`.
When I run the app with diagonalChecking executing ( `pureBarcode` hardcoded as `true`) it doesn't seem to suffer from performance issues (It still gives result before my eyes can even recognise a QRcode.)

I actually would like the diagonalCheck to always run, regardless of pureBarcode, hardware are ever increasing in performance and I don't see it being such a huge performance hit at all. I mean it is still pretty much instant.

**Comment by srowen** [comment]
Maybe it wasn't your point, but I just realized that the check in the line you cite is superfluous. pureBarcode will never be true there. The whole diagonal check method is never called. I'll remove it.

The diagonal check wasn't supposed to be enabled at all for non-pure barcodes. Does it even pass the tests? It's not CPU cycles issue. It may reject finder patterns that are correct too readily.

If you're building an app, the image above is not what you're scanning anyway.

**Comment by srowen** [comment]
Actually, enabling this check in all cases doesn't change the test result much. A few more pass, a few more fail. I'm a little wary of changing the scanning significantly at this point, but it does seem like a wash. Anyone have better evidence either way?

**Comment by srowen** [comment]
For the moment I removed the dead code. We can revisit it later if there's evidence it actually helps.

**Comment by herman1vdb** [comment]
@srowen  I see what you meant with it is too strict. After looking at it, I agree it would have been bad to add it.
I'll create a pull request for a more lenient check that allows this QR code and the rest to succeed.

I'm not sure how to add this image as part of the tests:
![53](https://user-images.githubusercontent.com/8955362/32486715-263e6984-c3b0-11e7-9f7d-b1d99f8ce885.png)
