### ISSUE TITLE
APKs using deprecated MD5 signature

### ISSUE THREAD

**Issue by IzzySoft** [zxing/zxing#900]
Just a note: your APKs are still signed using MD5, which is deprecated.

    ERROR: JAR signer ZXING.RSA: Failed to verify JAR signature META-INF/ZXING.RSA against META-INF/ZXING.SF: java.security.SignatureException: Algorithm constraints check failed on disabled algorithm: MD5.

As you know, deprecated soon might mean unsupported – so you might wish to act on this :wink:

**Comment by srowen** [comment]
It's just using the standard Android tool chain to build and sign. Where do you see that this is deprecated for Android, and what's the change that would change the behavior? also where do you see this error?

**Comment by srowen** [comment]
OK I get it. The manifest files actually show the SHA-1 hash, not MD5 hash, but, the signing key is ...

- Signed by "CN=Daniel Switkin, OU=ZXing Team, O=Google, L=New York, ST=New York, C=US"
    Digest algorithm: SHA1
    Signature algorithm: MD5withRSA (weak), 1024-bit key

I see similar warnings from jarsigner. This is the same key that's signed the app for 10 years, so not surprised if it's out of date. That said I don't know, can it be changed? I thought the app store pretty much depended on using the same key.

Then I see https://guardianproject.info/2015/12/29/how-to-migrate-your-android-apps-signing-key/ which says there's basically no way, and only weak keys were supported before Android 4.3.

I know there's a new app signing mechanism in the store now, which I've been reluctant to deal with, but, might be time, especially if it offers any kind of migration path.

**Comment by IzzySoft** [comment]
You've found it already, I see – but for clarification:

    $ apksigner verify com.google.zxing.client.android.apk
    DOES NOT VERIFY
    ERROR: JAR signer ZXING.RSA: Failed to verify JAR signature META-INF/ZXING.RSA against META-INF/ZXING.SF: java.security.SignatureException: Algorithm constraints check failed on disabled algorithm: MD5.

I'm no Android dev, so I have no idea how to fix that. As you mention looking towards v2 signing: keep in mind that's AFAIK only supported from Android 7 onwards – so if you app shall run on versions before that, you'd need to "dual sign" (ie. signing v2 and v1 additionally). That way Android < 7 will ignore the v2 signature, and 7+ will stick to the v2 signature.

As indicated: MD5 is not ***yet*** a deal-breaker. But it might become at some point – so this was just a pointer to "be aware and prepared for that day".

BTW: Thanks for the details on the culprit! I've notified a couple of other projects of the same issue – so if they ask me, I can at least give that information.

**Comment by IzzySoft** [comment]
@srowen look what I just found: [How to Migrate Your Android App's Signing Key](https://guardianproject.info/2015/12/29/how-to-migrate-your-android-apps-signing-key/) (Guardian Project).

But that procedure means "migrating your app" (new package name), so not really what we were hoping for. So I took a look at a different approach: [How to sign an APK with more than one certificate?](https://stackoverflow.com/q/2881904/2533433) Idea is to generate a new signing key, sign the next couple of versions with both keys, then drop the old one and continue with the new one. Not sure if that really works.

**Comment by srowen** [comment]
I don't think it will work in that it is the not-signing with old key that causes Android to consider it a new app.

**Comment by IzzySoft** [comment]
Not sure that that's the showstopper. But according to one of the posts, Playstore doesn't accept dual-signed APKs (at least they didn't in 2013). Might be worth a try in Emulator, or using some dummy project, to see if Android itself would accept that path. I cannot validate, not having a proper build environment plus not being an Android dev. Just thought to leave those pointers I've found.

Would be a shame if there wasn't some way to "upgrade" a key without losing the package. Technology moves on, and algorithms up-to-date today are due to be replaced at one point in the future. I've seen a bunch of packages with that MD5 issue (according to a study I've read about recently, that should be up to 40%). If all those package names need change, that'd be very bad UX. Same if updates would be rejected because of that.

**Comment by IzzySoft** [comment]
@srowen another question in this context: currently the app is in both the official F-Droid repo and mine. As F-Droid uses its own key, above issue isn't present there. On the other hand, it usually takes them up to 2 weeks (sometimes more) to fetch updates. Shall I "unlist" the app from mine for now, to avoid confusion? If need arises, it can easily be put back.

**Comment by srowen** [comment]
The Play store is the only place I publish the app. People can re-publish where they like, though should make clear it's not being distributed by the project itself.

**Comment by IzzySoft** [comment]
Sounds familiar (guess you've said this already once in the past). Just thought it fair to mention. As my repo requires to be used with the F-Droid app anyway, I'd say it's sufficient having your app in the official repo then. And as mentioned (plus agreed by you), I can add it back anytime should the need arise.

Thanks again!

**Comment by IzzySoft** [comment]
@srowen The AdGuard team managed to solve the MD5 issue (see [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/1575#issuecomment-350717523). Their solution might apply to Zxing as well. Quoting:

> The solution was clearly one of the:

>* Transition from Maven to Gradle build system.
>* Update of Android SDK and build tools.

> But no change in certificates and keys was made.

**Comment by srowen** [comment]
I don't think that's the issue. It's clear how to use the new signatures, just that it won't be accepted by Play as the same app. This says the keys didn't change. The issue seems to indicate a signature was removed, not updated?

**Comment by IzzySoft** [comment]
As their code isn't open source, we cannot check the commit history. And me not being an Android dev, it's hard to see things clearly (I know the concepts, but not in-depth). You could contact them directly for details. From what was said, I'd deduce no removed signature ("no change in certificates and keys was made") – though from the files in `META-INF`, they've got different names now. But that might be due to Maven handling things differently than Gradle (here comes my guessing do to lack of in-depth knowledge & experience).

**Comment by IzzySoft** [comment]
Just to inform you: Shadowsocks solved this issue as well [by switching to gradle](https://github.com/shadowsocks/shadowsocks-android/issues/1433#issuecomment-350828188). Not sure if that went along with an "update of Android SDK and build tools".

**Comment by srowen** [comment]
Gradle's just a build tool, so I don't see what it can have to do with it. It's easy enough to provide only the new sigs, but that's back to square 1 -- will be considered a new app. It's easy to provide both, but that doesn't make Play reject apps signed with the old signature, which was the security issue. That is, from skimming this, I don't think they're actually solving the issue fully, though all of these variants 'work' depending on what you require and what you tolerate.

**Comment by IzzySoft** [comment]
Well, I've checked the resulting APKs, and the issue was gone. But of course it might be different in your case. Just thought it polite to inform you, as I've raised the issue here, so you know about *possible* solutions. Can't give any guarantees, that's right :wink:

**Comment by IzzySoft** [comment]
Just got another hint. Do you use Xamarin? If so, there's an article on the root cause of the issue which might help: [Visual Studio - build - jarsigner algorithm](https://forums.xamarin.com/discussion/101114/visual-studio-build-jarsigner-algorithm).

**Comment by srowen** [comment]
No nothing to do with Xamarin. Signing is no problem or mystery. Problem is that Android won't recognize the app as the same if we stop signing with the key that the tool is complaining about. I don't see any solution to that.
