### ISSUE TITLE
Q: Can we scan Frame QR

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [zxing/zxing#901]
Hi,
I would like to know whether this plugin supports Frame QR or not.

I tried passing all PossibleFormats in options but still it could not detect.
Loading ZXingScannerPage with following options
```
var options = new MobileBarcodeScanningOptions
            {
                TryInverted = true,
                TryHarder = true,
                DelayBetweenContinuousScans = 1000,
                DelayBetweenAnalyzingFrames = 500,
            };

```

Also tried to pass EAN_8,EAN_13 and it detected frame QR after long time(many unsuccessful attempts)but it is wrong and showing different result everytime. 

Here is the [link](http://qrcode.meetheed.com/qrcode_examples.php) where I scanned for frame QR and others.

Only micro QR and frame QR are not scanned

**Comment by srowen** [comment]
There is no plugin here so you may be asking in the wrong place. I have not heard of a frame QR code, and micro is not supported.

**Comment by avinashramireddy-rapidd** [comment]
I was actually working in Xamarin Forms ...May be wrong place...Sorry
