### ISSUE TITLE
EAN-13 BUG

### ISSUE THREAD

**Issue by MartinPrusa** [zxing/zxing#902]
### Bug Reports
I found, that type of EAN-13, that I've attached to this issue, is not supported in Zxing. Is it possible to add support for this type of EAN-13?

I double checked with https://zxing.org/w/decode.jspx and it was unable to decode it.

Regards,
-Martin

<img width="944" alt="screen shot 2017-11-02 at 23 31 44" src="https://user-images.githubusercontent.com/1409050/32354295-693df784-c029-11e7-8159-b510dcd30f4b.png">

**Comment by srowen** [comment]
It's readable, you're just missing the quiet zone on the right side.
