### ISSUE TITLE
Unable to write code 39 extended barcode using ZXING C#

### ISSUE THREAD

**Issue by Sathunter** [zxing/zxing#905]
I have been using ZXING to decode barcodes found in a webcam stream and then write the clean barcode in the correct format. This works perfectly except for extended code 39 when I use lowercase characters the writer fails with an exception. I have downloaded and run the ZXing.Net-master windows form client and this seems to encode perfectly. Having spent over a day trying to figure this out, I decided to see if anyone has come across the same issue or if the is a simple example of how to ensure the writer is configured correctly.

Kind Regards
Mark

**Comment by srowen** [comment]
That's a different project.

**Comment by Sathunter** [comment]
Apologies Sean

have raised againts the correct project.


Kind Regards

Mark


________________________________
