### ISSUE TITLE
Code 39 cannot be recognized when wrapped with box

### ISSUE THREAD

**Issue by youyix** [zxing/zxing#907]
The zxing library has trouble with recognizing barcodes (Code 39) when the barcodes are wrapped in a box.  

For example, the following barcode (code 39) can be recognized quickly. 
![code39_no_box](https://user-images.githubusercontent.com/3282634/32619678-c2b4f11c-c57b-11e7-9990-d606302e5649.png)

The following barcode (code 39) can not be recognized. However, as soon as the box's left border got hidden (by a piece of white paper). The barcode can be immediately recognized.
![code39_box](https://user-images.githubusercontent.com/3282634/32619672-bf58735e-c57b-11e7-9bac-b6ee98c33b08.png)

I tested with official BarcodeScanner, zxing.org and my customized app built on top of zxing. 
I also tested with Code 128 and there is no problem for recognizing it.

**Comment by srowen** [comment]
The problem is lack of minimum quiet zone on the left, yes
