### ISSUE TITLE
DataMatrix encoder broken for certain short EDIFACT messages

### ISSUE THREAD

**Issue by axxel** [zxing/zxing#908]
I'm helping out at a new C++ port of this code base (https://github.com/nu-book/zxing-cpp). I stumbled on an issue with messages encoded with EDIFACT that need 2 code words padding. During debugging and research I found out that this issue has been discovered "upstream" over 5 years ago: https://sourceforge.net/p/barcode4j/bugs/38/.

Steps to reproduce: create a DataMatrix with the message `<ABCDEFG><ABCDEFGK>` -> the resulting image contains an invalid code.

I don't have a pull request but the fix is just one line, see [here](https://github.com/nu-book/zxing-cpp/pull/24/commits/06cbdadecf05c4360ba8e5ee502e17e7f4be8b30).

**Comment by srowen** [comment]
Sounds good, fixed.
