### ISSUE TITLE
ITFReader improvement suggestion

### ISSUE THREAD

**Issue by axxel** [zxing/zxing#909]
I implemented a relatively simple improvement of the ITFReader in the mentioned c++ port. It makes the decoder detect all of the 14 (instead of 9) `itf-1` sample images.

For details see the following 2 commits:

https://github.com/nu-book/zxing-cpp/commit/0c7c389db039b204f959d4a4d93b2ce4e8275781#diff-ebc4247141d1f9af94ed35508c219ffe

https://github.com/nu-book/zxing-cpp/commit/ca81ca2403a56cee585612c38c6ac33cf90267e5#diff-ebc4247141d1f9af94ed35508c219ffe

In case you might be interested to backport this.

**Comment by srowen** [comment]
Interesting, I tried to back port this but it didn't work. I'm not sure how to make use of the PATTERNS change.

The first commit by itself is fine but didn't seem to affect test results.

**Comment by axxel** [comment]
I had a look at the ITFReader.java and it seems every changed line has a direct correspondence to the JAVA version. Can you be more specific as to what did not work? Or post your local diff, maybe I see something missing.

**Comment by srowen** [comment]
[909.txt](https://github.com/zxing/zxing/files/1472950/909.txt)
Here's my interpretation in a patch. It seems to fail the writer test cases.

**Comment by axxel** [comment]
I had a look at your diff and it seems to me quite right. By writer test cases you mean [this](https://github.com/zxing/zxing/blob/master/core/src/test/java/com/google/zxing/oned/ITFWriterTestCase.java)? That, I would not understand, since it does not seem to be calling the modified decoder code at all? Did you notice any improvements with the blackbox tests?

**Comment by srowen** [comment]
Oh, it's because the writer uses `ITFReader.PATTERNS` and that has changed of course. Is there another parallel change in the port that's required? I can guess what the change is, just wondering if there's something to mimic to stay in sync.

**Comment by axxel** [comment]
I see. I have not spent much time with the writers (except the DataMatrix one). It turns out that the ported Writer code has a copy of that PATTERNS array, hence, no change required there. And not: there is nothing (that I know of) that would be related to that particular improvement, except the two mentioned changesets.

**Comment by srowen** [comment]
OK done, I copied the array here too.
