### ISSUE TITLE
Autofocus not working

### ISSUE THREAD

**Issue by MichaMoll** [zxing/zxing#910]
I tried the last Version (2.3.2) on Android with VS2017.
If I use the Standard Overlay, the Auto Focus worked very well. But if I use a CustomOverlay the Auto Focus only works one time (when the view is started). After that, I can call AutoFocus(), but it has no effect. 
I tried this only on Samsung Mobile Phone (S5, S7, S7 edge).

Here is the my Code snippet:

var scanner = new ZXing.Mobile.MobileBarcodeScanner();
                ZXing.Mobile.MobileBarcodeScanningOptions options = new ZXing.Mobile.MobileBarcodeScanningOptions()
                {
                    TryHarder = true,
                    AutoRotate = true,
                };
                ZXing.Result result = null;
                if (!Settings.UseOldBCScanner)
                {
                    scanner.UseCustomOverlay = true;
                    ScanView myCustomOverlay = new ScanView(context, scanner, Caption);
                    scanner.CustomOverlay = myCustomOverlay;

                    new Thread(new ThreadStart(delegate
                    {
                        while (result == null && scanner != null)
                        {
                            scanner.AutoFocus();
                            Thread.Sleep(3000);

                        }
                    })).Start();
                }
                scanner.TopText = Caption;
                result = await scanner.Scan(options);
                scanner = null;
                if (result != null)
                    return result.Text;
                else
                    return "";

Is this a bug? Or doing I something wrong?

Kind regards

Michael Moll

**Comment by srowen** [comment]
Not part of this project.
