### ISSUE TITLE
Another EDIFACT related bug in the DataMatrix encoder

### ISSUE THREAD

**Issue by axxel** [zxing/zxing#912]
I believe [this](https://github.com/nu-book/zxing-cpp/pull/25/commits/ec2e5c6feb81c7b5d26be59d65a6ff43394cffd7) issue is also existing in this JAVA code base.

**Comment by axxel** [comment]
I think there simply are no full-cycle encode+decode tests for the DM stuff in your project. I added some for the c++ project to find exactly those issues reported here.

**Comment by srowen** [comment]
Done, pushed the fix.
