### ISSUE TITLE
Suggestion to backport an improved datamatrix detector

### ISSUE THREAD

**Issue by axxel** [zxing/zxing#913]
I needed a c++ library for datamatrix detection+decoding and found [this new c++ port](https://github.com/nu-book/zxing-cpp) of the ZXing library. [Like](https://stackoverflow.com/questions/22381421/zxing-library-cant-decode-datamatrix-barcode) [other](https://stackoverflow.com/questions/12721077/issue-to-read-multiple-barcodes-using-zxing-library) [people](https://github.com/glassechidna/zxing-cpp/issues/33#issuecomment-338646683), too, I quickly found out that the datamatrix detector is quite limited in capabilities.

The single biggest issue turned out to be the dependence on the `WhiteRectDetector` to look for a white bounding box parallel to the image borders that contains the datamatrix code and nothing else. So with many real world situations where you have some text near the code and the code is not perfectly aligned with the image border, like [here](http://www.neuhausag.ch/assets/uploads/images/produkte/Etiketten/Produkte_Etiketten_Barcodeetiketten_2DCode.jpg), [here](https://www.deutsche-apotheker-zeitung.de/_Resources/Persistent/55c53726b5bbcc918ec7800229cf2e9d27794c21/k4_931_258080_258181-800x343-660x283-482x271.jpg) or [here](https://i.stack.imgur.com/Tvxeo.jpg), you have no chance. It also may lead to [this](https://github.com/glassechidna/zxing-cpp/issues/42) peculiar problem.

This led me to implement the detector from scratch with the main focus on two things:
 1. try to detect the code with as little quite zone as possible (1 module) and
 1. do that in an image with as low a resolution as possible.

What I came up with can be found [here](https://github.com/nu-book/zxing-cpp/blob/2ceda95cba943b3b2ab30af3c90150c97e84d416/core/src/datamatrix/DMDetector.cpp#L442-L1072). It is currently capable of detecting all the samples from the blackbox tests and a lot more challenging ones, like the mentioned examples above.

This would require a couple hours worth of JAVA coding, so it is probably not going to happen. But maybe it would make sens to keep this issue open so someone who also needs a better datamatrix detector and is willing to spend that effort might find the info I assembled here.

**Comment by srowen** [comment]
I'd look at targeted improvements in pull requests, but generally no large-scale backports. Nobody would work on this otherwise.

**Comment by axxel** [comment]
Since I am not sure what you meant to say, allow me to ask the following question: If I someone would provide a PR that improved the DM detector as described, you would not look at it because it would be to large a change?

(If yes -> I see why you closed this bug, if no -> why hide the proved background info?)

**Comment by srowen** [comment]
Targeted improvements are fine. Big changes might be too much work to review or change behavior (although, if all tests keep passing, that's pretty OK). I'm not able to do the work myself.

If this was a request for someone to do the back-port, no that won't happen. If you want to open a pull request, go ahead and do that separately.
