### ISSUE TITLE
Nearly Ideal Barcodes Cannot Be Decoded

### ISSUE THREAD

**Issue by Beiri22** [zxing/zxing#914]
Hi, I created some QR-Codes with the iText library (pdf), rendered the pages as png and tried to read the codes via zxing (java library v. 3.3.1, terminal application and your online decoder). I did not work; I can't figure out why, because the images are perfect. The zxing mobile app works... so why is the library failing?
![test1](https://user-images.githubusercontent.com/8210233/33014147-9bdb0b8a-cde6-11e7-89d0-3a58076798f2.png)
![test4](https://user-images.githubusercontent.com/8210233/33014148-9c03ecc6-cde6-11e7-9639-cb2bc7bf2c38.png)

**Comment by srowen** [comment]
This works fine in pure barcode mode if you only upload the image:

```
����root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/usr/bin/nologin
daemon:x:2:2:daemon:/:/usr/bin/nologin
mail:x:8:12:mail:/var/spool/mail:/usr/bin/nologin
ftp:x:14:11:ftp:/srv/ftp:/usr/bin/nologin
http:x:33:33:http:/srv/http:/usr/bin/nologin
nobody:x:99:99:nobody:/:/usr/bin/nologin
systemd-journal-gateway:x:191:191:systemd-journal-gateway:/:
```

**Comment by Beiri22** [comment]
I have inspected the code and notices the following:

In QrCodeReader -> FinderPatternFinder there is a constant "MAX_MODULES = 57", whereas
in QrCodeMultiReader -> MultiFinderPatternFinder it is 180.


Without the Pure_Mode QRCodeReader cannot read the Image, but QrCodeMultiReader can. Why is that? Shouldn't both reader classes be able to recognize the code (without the pure option)?

**Comment by srowen** [comment]
I just decoded this successfully with the current project code, but almost certainly due to the pure barcode mode.

The '57' is mostly a heuristic, but I also think it's fine to increase it at this point, given more processing power and better cameras on phones. I can up that to version 20 / 97.

Both already work on the phone though.
