### ISSUE TITLE
Raised Digits lead to wrongly detected EAN-13

### ISSUE THREAD

**Issue by robertseifert** [zxing/zxing#920]
Scanning EAN-13 codes formatted in a certain way leads to wrongly detected EANs. It happens when the leading (human readable) digit is raised to the level of the bars and the bars have a relatively low height.

I assume that due to the low height of the overall code, some bounding box detection decides, that the raised digit may be part of the actual code, since removing the leading (human readable) digit results in a correct detection.

The behaviour can be easily reproduced with the described EAN-13 code layout. I attached a minimalistic code sample as well as two images which lead to an erroneous detection. However, trying to detect such kind of codes with different Applications that claim to use zxing leads to similar results.

[zxing_test.zip](https://github.com/zxing/zxing/files/1535996/zxing_test.zip)

![4017100131004](https://user-images.githubusercontent.com/34313625/33673768-079c826c-daae-11e7-939a-a98fb62e66f4.png)

![4017100131004_1](https://user-images.githubusercontent.com/34313625/33673769-07b7a92a-daae-11e7-8c26-07d192b475a8.png)

**Comment by srowen** [comment]
Yes, the digit is interrupting the quite zone leading the barcode. That digit shouldn't be there. There's still a region at the top that will scan, but it may become harder. This isn't a bug.
