### ISSUE TITLE
FAQ: permissions explanations miss INTERNET

### ISSUE THREAD

**Issue by IzzySoft** [zxing/zxing#921]
Please include with your [FAQ](https://github.com/zxing/zxing/wiki/Frequently-Asked-Questions)

> Why does Barcode Scanner request permission to access ...

* … the Internet?

You've explained `ACCESS_WIFI_STATE` and `CHANGE_WIFI_STATE` (implicitly, though not differentiating which is which) but omitted `INTERNET`; tin-foils like me get suspicious about such omissions. Alternatively (and even better) if you could drop that permission? I can't see why a Barcode-Scanner would need it :wink:

**Comment by srowen** [comment]
Sure, you can look at the source if you're curious. It uses the internet to get info about scan results. It will resolve redirects, get the title of the target page, get product and book info. I can update.

**Comment by IzzySoft** [comment]
Thanks a lot for the detailled description, Sean – and that fast! Very much appreciated!

And indeed, that sounds useful (hadn't thought of those when writing "I can't see why a Barcode-Scanner would need it". Privacy wise, the combination of accessing personal data (here: contacts, bookmarks) *and* `INTERNET` always raises concerns (which is why e.g. [Gadgetbridge](https://github.com/Freeyourgadget/Gadgetbridge) decided to do without it, or *Locus Maps* kept contact access as a separate addon). Not sure if you would consider something similar (no distrust meant, don't get me wrong). Of course the draw-back of an addon would be the user needing 2 packages; an alternative of course could be a second variant of the APK without that permission (and the corresponding functionality simply disabled); as from the behaviour that should be equivalent to e.g. being in airplane mode (network check fails), that might be even reasonably easy to achieve.

Again: just a thought, just a suggestion to think about – please don't feel pressed or nagged :wink: Unfortunately, the `INTERNET` permission cannot be requested "on demand": it's either given on install or not at all. Most users don't think about it at all – but a few always have a queasy feeling … (of course, some of the latter use a firewall app or have LOS's *privacy guard* to deal with such things)

**Comment by srowen** [comment]
In the beginning (Android 0.9 - 5.x I think) you could only ask for permissions at install time, which was a problem for the reason you give. I can't tell you the number of nasty emails and reviews that came in about stealing personal information. Now you can request permission at runtime, which would help, but, this app is not in development anymore.

The 'plus' app had a variant with minimal permissions just like you say:
https://play.google.com/store/apps/details?id=com.srowen.bs.android.simple

I am still ambivalent about this as its existence somehow validated the idea that you needed to give up functionality for privacy, when in fact there's nothing about it that abuses data.

**Comment by IzzySoft** [comment]
Oh, I can imagine those mails. Guess why I'm so insisting on *not* accusing you of anything! And yes, up to 5.x is correct. Unfortunately, 6+ only changed that for a few selected permissions. `INTERNET` is not one of those (you wouldn't dare robbing Google of their ad revenue!) – with lame excuses.

> The 'plus' app had a variant with minimal permissions just like you say:

Nah, wrong way around. I asked you to drop `INTERNET` but keep everything else. That 'plus' app drops everything else but kept `INTERNET` :stuck_out_tongue_winking_eye:

> I am still ambivalent about this as its existence somehow validated the idea that you needed to give up functionality for privacy, when in fact there's nothing about it that abuses data.

Same can be said about *Gadgetbridge*. Thing is, it's hard to accuse you for something technically impossible (no network permission, no data sent). So if someone doesn't trust you (enough (yet)), that someone could simply use the restricted version. If someone accuses you, the same applies. Sure you could (and in fact, did) say "you can look at the source if you're curious". But honestly, which laymen can read it? Even I wouldn't dare saying "that code looks safe", as I'm no developer (though I dare saying "this app looks safe, as I detected neither malware nor malicious libraries nor ad modules nor trackers inside it").
