### ISSUE TITLE
[Feature Request] stitch file together (minus header) across multiple QR codes

### ISSUE THREAD

**Issue by nasaWelder** [zxing/zxing#924]
Cryptocurrency users dislike connecting their cold wallets to internet connected computer, however there is need to transfer files back and forth.
I have a project that can split a Monero signed_tx file into approximately 21 QR codes that play in a loop.
[https://github.com/nasaWelder/sandbox/tree/master/monero/coldqr](https://github.com/nasaWelder/sandbox/tree/master/monero/coldqr)

The format is:
srcfilebasename,srcfilecrc32,1/21:bunchofasciiencodedtedtxt12345
srcfilebasename,srcfilecrc32,2/21:bunchofasciiencodedtedtxt12345
...
...
srcfilebasename,srcfilecrc32,21/21:bunchofasciiencodedtedtxt12345

I'd want the bulk scanning to be able to know when it has scanned the total number of files derived from within the QR code, show status bar, and self exit.
Then prompt user to save (default name srcfilebasename), or email file.

**Comment by srowen** [comment]
There is a mechanism in the QR code spec itself for this called "Structured Append". It's an odd complex feature, optional, and isn't supported here.

This sounds like a very app-specific type of functionality which you could build into your own separate app. I can't see making a UI for this in the app itself.
