### ISSUE TITLE
The generated qr code cannot be identified

### ISSUE THREAD

**Issue by chen732117819** [zxing/zxing#925]
When the content url contains the word 'invite', it is not recognized. 
For example:
    String content= Config.url + "/servlet/invite.go?id=1";
    BitMatrix encode = qrCodeWriter.encode(content, BarcodeFormat.QR_CODE, width, height, hints);

The content has the word with 'invite', it is not recognized. 

But:
String content= Config.url + "/servlet/invite_code.go?id=1";
It can recognized.

**Comment by srowen** [comment]
There's certainly nothing magic about the string 'invite'. Something else is at work. Your URL definitely works: https://zxing.org/w/decode?u=https%3A%2F%2Fzxing.org%2Fw%2Fchart%3Fcht%3Dqr%26chs%3D350x350%26chld%3DL%26choe%3DUTF-8%26chl%3Dhttp%253A%252F%252Fexample.com%252Fservlet%252Finvite.go%253Fid%253D1
