### ISSUE TITLE
"Search in Web" in app non-functional

### ISSUE THREAD

**Issue by katzenpapst** [zxing/zxing#928]
"Barcode Scanner" from FDroid links here, so I assume this bugtracker is for the app as well.

After I scan a code and press "Web Search", it says something like: "Application cannot be started, Barcode might be invalid"
Or similar. The actual error message appears in german for me:
"Die gewünschte Applikation kann nicht geöffnet werden. Der Barcode könnte ungültig sein".

Samsung Galaxy 5, Android 6.0.1.
I did the usual stuff like clearing data and reinstalling.

**Comment by srowen** [comment]
Works fine for me. I think you have a problem with whatever app you have chosen to handle web links; it's not a browser or something. You might have chosen to "Always" open links of this type with the other app

**Comment by katzenpapst** [comment]
No. Restored the stock browser to default, still same thing. Oh well, *uninstalls*

**Comment by srowen** [comment]
OK, but that wouldn't solve the problem I'm positing. If web links were being handled with some other app, the browser's settings and installation wouldn't matter. As I say, works for me and have not heard any other report like this, so it's highly likely it's specific to your phone.

**Comment by katzenpapst** [comment]
Er, I meant, I restored the stock browser as the default web link handler.
