### ISSUE TITLE
jai-imageio-core-1.3.1 not JDK 9 compatible

### ISSUE THREAD

**Issue by eakerma** [zxing/zxing#931]
See https://github.com/jai-imageio/jai-imageio-core/issues/26

**Comment by srowen** [comment]
Sure, but what can be done here? does not look like there is a new release.

**Comment by eakerma** [comment]
Agreed.  It's a placemarker so 1) users are aware of the issue and 2) for once it's released

**Comment by srowen** [comment]
Sounds good, I committed an update to use 1.4.0.

**Comment by gexclaude** [comment]
great thank you a lot! looking forward to 3.3.3 release.
