### ISSUE TITLE
Feature: Process images of barcodes and QR codes stored locally

### ISSUE THREAD

**Issue by Wolfram-Wolf** [zxing/zxing#932]
Sometimes I get images of barcodes and QR codes from websites and messages which I want to process. Adding an option to process local images would be great.

**Comment by srowen** [comment]
This exists in the 'plus' app which is also open source now. https://play.google.com/store/apps/details?id=com.srowen.bs.android I didn't plan to do any more backports from it. If someone cleanly backports that function here though I'll look at a PR.
