### ISSUE TITLE
SCAN_RESULT_BYTES

### ISSUE THREAD

**Issue by goldenluk** [zxing/zxing#934]
Hi, i can`t understand what is it result bytes.
I have this qr-code, it is in cp1251 encoding. it contains cyrillic symbols.
![1251 guessed like 3 cp](https://user-images.githubusercontent.com/25905825/34374263-cf410814-eb12-11e7-8d9d-7e86d8c7bbfc.png)

In scan result string i have non-readable symbols.
Can you explain what is in scan result bytes.
If i try variants like this:
`new String(resultBytes, "cp1251")` or this `new String(resultBytes, "utf8")` i get non-readable string.
How convert result bytes to String?
p.s. i cant using qr codes in utf-8
Thanks

**Comment by srowen** [comment]
Questions should go to the mailing list. It's the byte representation of any byte segments in the QR code. To interpret as a string you would have to apply the right encoding
