### ISSUE TITLE
trouble compiling ZXing into new project.

### ISSUE THREAD

**Issue by SynGreis** [zxing/zxing#936]
I am learning how this package works but having issues just getting it to build.

I grabbed ZXing reader from here ==> https://github.com/zxing/zxing

I also went to this site for a guide ==> https://www.callicoder.com/qr-code-reader-scanner-in-java-using-zxing/

So i opened up the pom.xml and i get all the modules .github, .idea, android, android-core, android-integration, core, docs, javase, src, zxing.appspot.com and zxingorg.

I then go to zxingorg/src/main/java/com.google.zxing.web and same for core module pasted qrcodereader in there and tried running it and i get this error.

"Error:Android Pre Dex: [android] Android SDK is not specified"

Now i do get an error saying android sdk needed api level 22 but....im not even developing for android. I was just planning on working just for pc/raspberry pi applications. Not android.

I was under the presumption that the ZXing library was usable for desktop applications and the like??

I am trying to be able to do a simple generate and decode.

I am using IntelliJ.

**Comment by srowen** [comment]
Questions should go to the mailing list. I'm not sure how you're trying to build, but you should be using the provided Maven build. It won't build anything with Android unless you specify and Android SDK home.
