### ISSUE TITLE
ZXing.BarcodeReader or ZXing.QrCode.QRCodeReader not decode

### ISSUE THREAD

**Issue by maxpower80** [zxing/zxing#939]
Hello everyone, I have tried to use zxing (version 0.16.2.0 for .net 3.5) and I can not decode this QR image, I have searched for other similar errors and I have tried solutions such as setting TRY_HARDER or PURE_BARCODE parameters but the result is the same: decode function returns null. I have tried in the online application https://zxing.org/w/decode.jspx to attach the image and there if decoding is achieved. Please, could you tell me what may be happening? Thank you very much and greetings.
![a](https://user-images.githubusercontent.com/35295921/34770742-47940d62-f602-11e7-8f4b-2d078cbf2049.jpg)

**Comment by srowen** [comment]
This decodes fine: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F35295921%2F34770742-47940d62-f602-11e7-8f4b-2d078cbf2049.jpg

It also sounds like you're talking about another project, not this one.
