### ISSUE TITLE
java: constant expression required

### ISSUE THREAD

**Issue by jinntrance** [zxing/zxing#94]
when compiling android/src/com/google/zxing/client/android/DecodeHandler.java
javac reports "Resource IDs cannot be used in a switch statement in Android library modules" in line 57

**Comment by f839903061** [comment]
针对：Resource IDs cannot be used in a switch statement in Android library modules

I found a solution ,you can use
 'if...else' 
instead of 
'switch'
,it‘s work for me ,

You do not need to do any other operations
我找到一种解决办法，仅仅只需要将switch格式修改为if....else就可以了，代码段照抄，其他不用做任何修改
