### ISSUE TITLE
env.ANDROID_HOME compile error with spring boot

### ISSUE THREAD

**Issue by FlowerWrong** [zxing/zxing#941]
## compile error with javase version

I just want to use zxing on my web server to work with spring boot. but this library seens force me to install android development.

build.gradle
```
compile group: 'com.google.zxing', name: 'javase', version: '3.3.1'
```

error log
```
> Task :model:compileJava
Errors occurred while build effective model from /Users/kingyang/.gradle/caches/modules-2/files-2.1/com.google.zxing/javase/3.3.1/357121cdf3f89f63ddfaad18170612dcad0db947/javase-3.3.1.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is ${env.ANDROID_HOME}/platforms/android-22/android.jar in com.google.zxing:javase:3.3.1
Errors occurred while build effective model from /Users/kingyang/.gradle/caches/modules-2/files-2.1/com.google.zxing/core/3.3.1/d1e7c4667f9dcdda30d09f3df7d1b44f65c44336/core-3.3.1.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is ${env.ANDROID_HOME}/platforms/android-22/android.jar in com.google.zxing:core:3.3.1

> Task :compileJava
Errors occurred while build effective model from /Users/kingyang/.gradle/caches/modules-2/files-2.1/com.google.zxing/javase/3.3.1/357121cdf3f89f63ddfaad18170612dcad0db947/javase-3.3.1.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is ${env.ANDROID_HOME}/platforms/android-22/android.jar in com.google.zxing:javase:3.3.1
Errors occurred while build effective model from /Users/kingyang/.gradle/caches/modules-2/files-2.1/com.google.zxing/core/3.3.1/d1e7c4667f9dcdda30d09f3df7d1b44f65c44336/core-3.3.1.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is ${env.ANDROID_HOME}/platforms/android-22/android.jar in com.google.zxing:core:3.3.1
注: /Users/kingyang/dev/java/lipu/api/src/main/java/com/lipuwater/service/PushService.java
```

**Comment by srowen** [comment]
You need to set ANDROID_HOME or disable the Android modules. I think your build tool isn't reading the Maven profiles that do this automatically.

**Comment by rohanliston** [comment]
I've got the same issue. How do I go about disabling the Android modules?

**Comment by srowen** [comment]
In Maven, it's done automatically based on whether `ANDROID_HOME` is set, though you can override that. In another build tool, not sure, you'd have to consult that build tool. This project uses Maven and tools that understand POM files.

**Comment by rohanliston** [comment]
I think I've got the same issue as #904, as I'm using Spring Boot with Gradle. I'll try your suggestion at the bottom of that issue.

**Comment by qianggetaba** [comment]
I've got same issue, and solved by following steps, hope this helps.
1. create empty file named android.jar
2. replace systempath with above file absolute path in .gradle\caches\modules-2\files-2.1\com.google.zxing\zxing-parent\3.3.2\4ad323c509da2eff69fe7f02ef0f4e5910509206\zxing-parent-3.3.2.pom, content: <systemPath>/path/to/android.jar</systemPath>

ENV:
windows 10
Intellij IDEA (only java)
gradle, springboot, zxing3.3.2

**Comment by srowen** [comment]
This is all unnecessary. Just use Maven, or remove references to the android modules manually in the parent pom.xml file.

**Comment by FreeLoopC** [comment]
update gradle version to 6.5
it work for me

**Comment by raduhrihoreanu99** [comment]
> I've got same issue, and solved by following steps, hope this helps.
> 
> 1. create empty file named android.jar
> 2. replace systempath with above file absolute path in .gradle\caches\modules-2\files-2.1\com.google.zxing\zxing-parent\3.3.2\4ad323c509da2eff69fe7f02ef0f4e5910509206\zxing-parent-3.3.2.pom, content: /path/to/android.jar
> 
> ENV:
> windows 10
> Intellij IDEA (only java)
> gradle, springboot, zxing3.3.2

I've solved the problem like qianggetaba said, except that I've replaced the systempath with  the absolute path of the android.jar file from Android SDK. If you go to the file that qianggetaba specified and look for the systemPath tag, you'll see a comment there that says: "ANDROID_HOME must be absolute, but redundant leading / may help Gradle Spring Boot plugin". So I've replaced the old path, that in my case used {env.ANDROID_HOME}, with:

![image](https://user-images.githubusercontent.com/46050082/123249592-cc04b700-d4f1-11eb-9fc3-28c44a9503a3.png)

Then the error disappeared.

**Comment by johnou** [comment]
If you're developing a Java project with Gradle and don't need android libraries you can unset the property causing the activation (in my case it is set because I do Android development in another project) by adding this to the top of your build.gradle.

```
// unset ANDROID_HOME to avoid problems with zxing
System.setProperty("env.ANDROID_HOME", "")
```
