### ISSUE TITLE
why zxing can not decode this qrcode image?

### ISSUE THREAD

**Issue by renfufei** [zxing/zxing#947]
The Qrcode is generate  by wechat,  but the other Utils can parse it.

JavaSE: Exception is "com.google.zxing.NotFoundException"。

The generate URL is <https://open.weixin.qq.com/connect/qrconnect?appid=wxa12dbe0ddc354603&redirect_uri=http%3A%2F%2Fapi.baomitu.com%2Fuser%2Findex%2Fsignin%3Frdurl%3Dhttp%253A%252F%252Fzcfy.cc%252Fwelcome%252F_%253Ftype%253Dweixin%2526state%253D1204120670142.8474%26type%3Dweixin&response_type=code&scope=snsapi_login&state=178bed19297db5cb6f5c83537f0abb27>。

What format is it?

Can any one help me?
![default](https://user-images.githubusercontent.com/5195188/35219194-9dd35774-ffac-11e7-8f44-00a7576739ef.jpg)

**Comment by renfufei** [comment]
My `ZXingUtil.java` Source code is there: <https://github.com/cncounter/cncounter-web/blob/master/src/main/java/com/cncounter/util/zxing/ZXingUtil.java#L165>

**Comment by srowen** [comment]
This decodes fine: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F5195188%2F35219194-9dd35774-ffac-11e7-8f44-00a7576739ef.jpg

**Comment by renfufei** [comment]
The <http://zxing.org> decoder is Great!

But may be it is  javase edition's bug.

The version is 3.3.1:

```
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>3.3.1</version>
        </dependency>
```

and the java code is there.

```
	public static String parseQrCode(BufferedImage image ) {
		String code = "";
		if (null == image || image.getHeight() < 10 || image.getWidth() < 10) {
			return code;
		}
		LuminanceSource source = new BufferedImageLuminanceSource(image);
		BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
		try {
			Result rawResult = new MultiFormatReader().decode(bitmap);
			code = rawResult.getText();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return code;
	}
```

When I decode the image <https://user-images.githubusercontent.com/5195188/35219194-9dd35774-ffac-11e7-8f44-00a7576739ef.jpg> file,

The Exception info is : 

```
com.google.zxing.NotFoundException
```

There is not anything other displayed...

**Comment by renfufei** [comment]
The Problem is resolved!
Reference code is <https://github.com/zxing/zxing/blob/master/zxingorg/src/main/java/com/google/zxing/web/DecodeServlet.java#L108>。

The Image is pure qr_code。Format is `BarcodeFormat.QR_CODE` and hint is `DecodeHintType.PURE_BARCODE, Boolean.TRUE`。

The  following is the config code:

```
        Map<DecodeHintType,Object>  HINTS = new EnumMap<DecodeHintType,Object>(DecodeHintType.class);
        HINTS.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
        HINTS.put(DecodeHintType.POSSIBLE_FORMATS, EnumSet.allOf(BarcodeFormat.class));
        Map<DecodeHintType,Object> HINTS_PURE = new EnumMap<DecodeHintType,Object>(HINTS);
        HINTS_PURE.put(DecodeHintType.PURE_BARCODE, Boolean.TRUE); // this effective
```

**Comment by 18908636885** [comment]
发自我的 iPhone

**Comment by shalomboss21-cell** [comment]
Shalom
