### ISSUE TITLE
ISBN - Scan partly not possible with 4.7.7

### ISSUE THREAD

**Issue by natrius** [zxing/zxing#948]
Unfortunately i cannot contribute :(

**Used Android Version:**
Android 7.1.2
**Used App Version:** 
4.7.7
**Problem:** 
It is not possible to scan ISBN - Codes from books, any QR-Code is perfectly fine. 
**What is expected:**
Open Barcode-Scanner, hove over the picture, it will focus and its done. 
**What happens instead:**
Nothing. One yellow dot somewhere on the barcode and thats it.
**What have you tried already:**
Uninstalled the app, new installed, deleted cache.
Setting: Deactivate every "Device Bug Workarounds", try it again, activate one by one while trying again.
With 4.7.3 it works, but the picture is rotated by 90° and somewhat weird streched. Hard to scan like that, but it would be possible.
**LogCat:**
As there is no error-message, i did not include one. If needed, i can deliver. Is pastebin fine?

Greets

**Comment by srowen** [comment]
The ISBN tests pass and I'm able to scan them. Maybe it isn't ISBN or it's slightly corrupted? There is no info to go on here I'm afraid.

**Comment by natrius** [comment]
I tried various books, also with the QR Scanner - it works flawless with that app :/

Still, thanks fornthe answer.
