### ISSUE TITLE
Trailing and leading whitespace on GS1-128 when using FNC1 character

### ISSUE THREAD

**Issue by annando** [zxing/zxing#949]
I'm having a strange issue with the GS1-128 barcode.

When sending the barcode ```003425023080025013461003012018``` the barcode looks this way:
![ean128](https://user-images.githubusercontent.com/844208/35389325-908a6b5c-01d7-11e8-873d-5b1894e5a6f3.jpg)

When sending the same barcode with the same parameters - but with the FNC1 character in it ```ñ00342502308002501346ñ1003012018``` - the barcode looks this way:
![gs1-128](https://user-images.githubusercontent.com/844208/35389345-ab76bc54-01d7-11e8-8e3f-f4b3749264a6.jpg)

The system generates massive whitespace before and after the barcode.

Is this a bug or a feature? Can it be disabled?

**Comment by srowen** [comment]
I think it's because the first barcode barely fits in the dimension you specify, but the second doesn't, and has to drop down a module size in pixels to fit, producing a smaller barcode.

**Comment by annando** [comment]
Yeah, you are right. When simply increasing the generated pixels proportionally by 5 it fits.

Thanks for this ultra fast help!
