### ISSUE TITLE
Barcode Scanner 4.7.7 not built using intellij

### ISSUE THREAD

**Issue by yingdi11** [zxing/zxing#950]
If using build tool before 26 will get below exception:

Error:Android Pre Dex: [android.jar] trouble processing "java/awt/font/NumericShaper.class":
Error:Android Pre Dex: [android.jar] Ill-advised or mistaken usage of a core class (java.* or javax.*)
Error:Android Pre Dex: [android.jar] when not building a core library.
Error:Android Pre Dex: [android.jar] This is often due to inadvertently including a core library file
Error:Android Pre Dex: [android.jar] in your application's project, when using an IDE (such as
Error:Android Pre Dex: [android.jar] Eclipse). If you are sure you're not intentionally defining a
Error:Android Pre Dex: [android.jar] core class, then this is the most likely explanation of what's
Error:Android Pre Dex: [android.jar] going on.
Error:Android Pre Dex: [android.jar] However, you might actually be trying to define a class in a core
Error:Android Pre Dex: [android.jar] namespace, the source of which you may have taken, for example,
Error:Android Pre Dex: [android.jar] from a non-Android virtual machine project. This will most
Error:Android Pre Dex: [android.jar] assuredly not work. At a minimum, it jeopardizes the
Error:Android Pre Dex: [android.jar] compatibility of your app with future versions of the platform.
Error:Android Pre Dex: [android.jar] It is also often of questionable legality.
Error:Android Pre Dex: [android.jar] If you really intend to build a core library -- which is only
Error:Android Pre Dex: [android.jar] appropriate as part of creating a full virtual machine
Error:Android Pre Dex: [android.jar] distribution, as opposed to compiling an application -- then use
Error:Android Pre Dex: [android.jar] the "--core-library" option to suppress this error message.
Error:Android Pre Dex: [android.jar] If you go ahead and use "--core-library" but are in fact
Error:Android Pre Dex: [android.jar] building an application, then be forewarned that your application
Error:Android Pre Dex: [android.jar] will still fail to build or run, at some point. Please be
Error:Android Pre Dex: [android.jar] prepared for angry customers who find, for example, that your
Error:Android Pre Dex: [android.jar] application ceases to function once they upgrade their operating
Error:Android Pre Dex: [android.jar] system. You will be to blame for this problem.
Error:Android Pre Dex: [android.jar] If you are legitimately using some code that happens to be in a
Error:Android Pre Dex: [android.jar] core package, then the easiest safe alternative you have is to
Error:Android Pre Dex: [android.jar] repackage that code. That is, move the classes in question into
Error:Android Pre Dex: [android.jar] your own package namespace. This means that they will never be in
Error:Android Pre Dex: [android.jar] conflict with core system classes. JarJar is a tool that may help
Error:Android Pre Dex: [android.jar] you in this endeavor. If you find that you cannot do this, then
Error:Android Pre Dex: [android.jar] that is an indication that the path you are on will ultimately
Error:Android Pre Dex: [android.jar] lead to pain, suffering, grief, and lamentation.
Error:Android Pre Dex: [android.jar] 1 error; aborting

if using build tool upper or equal than 26.0.0 , will get below:
Error:Android Pre Dex: [android.jar] Failed to load dx.jar
Error:Android Pre Dex: [android.jar] java.lang.ClassNotFoundException: com.android.dx.command.DxConsole
Error:Android Pre Dex: [android.jar] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Error:Android Pre Dex: [android.jar] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Error:Android Pre Dex: [android.jar] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Error:Android Pre Dex: [android.jar] at org.jetbrains.android.compiler.tools.AndroidDxRunner.loadDex(AndroidDxRunner.java:80)
Error:Android Pre Dex: [android.jar] at org.jetbrains.android.compiler.tools.AndroidDxRunner.runDex(AndroidDxRunner.java:136)
Error:Android Pre Dex: [android.jar] at org.jetbrains.android.compiler.tools.AndroidDxRunner.main(AndroidDxRunner.java:336)
Error:Android Pre Dex: [android.jar] Exception in thread "main" java.lang.NullPointerException
Error:Android Pre Dex: [android.jar] at org.jetbrains.android.compiler.tools.AndroidDxRunner.runDex(AndroidDxRunner.java:139)

**Comment by srowen** [comment]
It builds fine for me with IntelliJ. However the build is a Maven build. You should start by making sure even that works. These are not errors from the project, even.
