### ISSUE TITLE
Scanner returns to Mainactivity regardless which activity calls it.

### ISSUE THREAD

**Issue by gamengamenut** [zxing/zxing#954]
When i run the scan intent from the MainActivity, it works fine, no problems does what it does. Issue is now, when i run the scanning intent from AfterMainActivity, it does not call the OnActivityResult function in AfterMainActivity but rather just recreates MainActivity and runs from there, disregarding all code after the ScanningIntent is run in AfterMainActivity. Is there anything i'm doing wrong in calling the scanning intent?

Codes:

    IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setCaptureLayout(R.layout.activity_scan);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt(" ");
        integrator.addExtra("CONTINEUOUS_SCAN", true);
        integrator.setWide();  // Wide scanning rectangle
        integrator.setCameraId(0);  // Use a specific camera of the device
        integrator.initiateScan();

**Comment by srowen** [comment]
You are asking about your code, not this project.
