### ISSUE TITLE
Why ngx-zxing does not scan barcodes

### ISSUE THREAD

**Issue by AridonAvdullahu** [zxing/zxing#955]
I have a project which is built on Typescript and Angluar ,and I needed to have a scanner for all scan codes like barcodes or qrcode, and when I installed from npm modules https://www.npmjs.com/package/ngx-zxing I get only qrcode function.
So why the ngx-zxing does not scan barcodes, and scan only QrCodes

Thanks in advance
Aridon

**Comment by srowen** [comment]
Not sure -- you should ask that project.
