### ISSUE TITLE
Adding zxing as local module to android project

### ISSUE THREAD

**Issue by yoola** [zxing/zxing#962]
I wanted to integrate the zxing barcode scanner as local module in my android project, so I can change java files accordingly.

A good explanation how to do this could I find here https://saurjk.xyz/posts/2017/embed-zxing-barcode-scanner-in-an-android-app/.

**Comment by srowen** [comment]
Not sure what the action is here, but the app provides an Android app, not a library to be used in that way. It does break out some utility code into a reusable module, `android-core`.
