### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by m-saifuddin** [zxing/zxing#963]
Good Day,

I am trying to integrate scanner functionality in Android using IBM MobileFirst.

Its working when application is zxing app installed in mobile but running without app giving me the below error. 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abc/com.google.zxing.client.android.CaptureActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
03-01 20:37:40.161: E/AndroidRuntime(25256): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)

```

Any help would be appreciated.

**Comment by srowen** [comment]
This would be an error from your app or another framework, and not this project.
