### ISSUE TITLE
Reading a sample QR

### ISSUE THREAD

**Issue by Gudilbert** [zxing/zxing#964]
Hi there, correction to my previous post, I find a QR code that I can't read. Attached is the picture. Could you please make this app capable of scanning it?
Regards!
![qr sample](https://user-images.githubusercontent.com/1020656/36857790-0d5feef4-1d3f-11e8-8943-04bae3e3d89a.png)

**Comment by srowen** [comment]
Hm, it is detected correctly, but looks like there is an error to do with the format information in the barcode. It keeps rejecting the contents of it. Are you sure it's encoded correctly?

**Comment by Gudilbert** [comment]
Hi srowen, I can scan it with imagers of different scanners, not with the camera, so I suppose it is decoded correctly.

**Comment by Gudilbert** [comment]
Hello anybody knows about this? I've found many QRs like this one. It just can't be scanned with any app I download.

**Comment by srowen** [comment]
I thought it might be mirror-imaged, but I don't think that's it. It's possible it's an old-style QR code (pre 2005 spec) that isn't actually used much at all anymore. I can't quite tell by looking but the outer border at the bottom right does kind of make it look that way.

**Comment by Gudilbert** [comment]
Hi srowen, then, is there a parameter needed to be activated so the application can scan that kind of QR codes from 2005?

**Comment by srowen** [comment]
No, these are ancient, and shouldn't be used anymore. (I don't know if that's the case here but it's a reasonable hypothesis.)

**Comment by Darshi2520** [comment]
Fine

**Comment by axxel** [comment]
It is (most likely) a Model 1 symbol (see [here](https://www.qrcode.com/en/codes/model12.html)). You may want to check out https://github.com/zxing-cpp/zxing-cpp. It reads those QRCodes just fine.

**Comment by Brendasuebob** [comment]
How do I return a Barbie backpack? My granddaughter does not like please it’s expensive.

**Comment by benjablackice008** [comment]
Hello
