### ISSUE TITLE
Best preview size for Google Glass

### ISSUE THREAD

**Issue by yoola** [zxing/zxing#965]
I'm trying to make zxing working on Google Glass. But when I start the QR Code Scanner I get a distorted preview screen. How can I fix this?

**Comment by srowen** [comment]
I don't recall, but you can look at the source code for the glass app right before it was removed to see what I had working. It's for the original Google Glass device. https://github.com/zxing/zxing/tree/7fdc869d02b27e6819214b3a5c2f7412fa1e8749/glass
