### ISSUE TITLE
Not recognizing QR codes with not all 3 corners all blacked out

### ISSUE THREAD

**Issue by bslefevre** [zxing/zxing#966]
It isn't recognizing valid QR codes wich can have 1 corner not all blacked out.
Example: (value: 1559)
![20180303191933-velox](https://user-images.githubusercontent.com/5653833/36937819-45941fee-1f19-11e8-8c34-c5d61eeb002c.jpg)

Is there something to do to fix this?

**Comment by srowen** [comment]
That's not a valid QR code at that point, so no
