### ISSUE TITLE
Can't generate Aztec code when set EncodeHintType.ERROR_CORRECTION

### ISSUE THREAD

**Issue by phamxuanlu** [zxing/zxing#971]
Hi,
I try to generate Aztec code and use EncodeHintType.ERROR_CORRECTION but it throws NumberFormatException.

I found that in the source code of AztecWriter try to parse the error correction value to an integer.
`if (hints.containsKey(EncodeHintType.ERROR_CORRECTION)) {
        eccPercent = Integer.parseInt(hints.get(EncodeHintType.ERROR_CORRECTION).toString());
 }`
The value is string "L", "M", "Q", "H" and can't parse to integer. So it stop there.
I guess PDF417Writer face this issue too.

**Comment by srowen** [comment]
L, M, Q, H are for QR codes. As you can see this is expecting an "ECC percent".
