### ISSUE TITLE
Issue is scanning QRCode

### ISSUE THREAD

**Issue by sajidap** [zxing/zxing#975]
We are trying to read a Version 25 QR Code using the zxing library on Android(without using the zxing scanner app). We are only able to read it 1/10 times and even that is taking too long to read. The QR code generated has also been generated using the Zxing library. Could you please help us out with a solution for the same?

 

Library used : com.journeyapps:zxing-android-embedded:3.4.0

**Comment by srowen** [comment]
You don't have any specifics here and say you're using another code base. Large QR codes are simply hard to read; I'd not go above version 10
