### ISSUE TITLE
App crash when decline Camera access permission - Android

### ISSUE THREAD

**Issue by michaelmontero** [zxing/zxing#976]
When i decline the camera permission on Android the app crash and close in phisical device.

Device : SAMSUNG-MG-M910A
Device API Version : 23
Android Version: 60

ZXing 2.3.2

**Comment by srowen** [comment]
Of course you do, because it needs the camera to do anything.

**Comment by michaelmontero** [comment]
But the app does not have to present the ADR message and close.

**Comment by srowen** [comment]
If you manually take away permissions the app requires and that have to be granted at download time, I think this is expected. Especially one that logically must be enabled. there's no point in handling the case that someone took away the camera from an app built around the camera.
