### ISSUE TITLE
Add F-Droid badge to Readme

### ISSUE THREAD

**Issue by rugk** [zxing/zxing#978]
Currently you only have the Google Play download badge in your Readme. It would be nice to also add the F-Droid one, linking to the [F-Droid download](https://f-droid.org/packages/com.google.zxing.client.android/).

**Comment by srowen** [comment]
I'd say no because this isn't where the app is distributed. Third parties do that. I wouldn't want to suggest otherwise.

**Comment by rugk** [comment]
Hu? Google Play is also a third-party, which distributes your app. F-Droid is the same.
Users should just have an easy way to notice the app is on F-Droid when reading the Readme. Where they download it from is their choice.

**Comment by srowen** [comment]
I distribute the app on Play, and Github, and those are the only two places. I don't know what's on F-Droid or who puts it there, but it's not me -- a third party does it. Because I can't vouch for it, I'm not going to say I do by putting an icon on this project site. Clear enough?

**Comment by rugk** [comment]
For clarification: F-Droid takes the source automatically and compiles it.
