### ISSUE TITLE
Use zxing scan local QRcode will throw ChecksumException

### ISSUE THREAD

**Issue by caihuihuang** [zxing/zxing#979]
(Please remove this text once you've read and understood it.)

## Contributing

The project is in maintenance mode, meaning, changes are driven by contributed patches.
There is otherwise no active development or roadmap for this project. It is "DIY".

Only proposed changes in the form of a pull request are likely to be acted on, but,
these will be acted on promptly.

### Questions

Questions should be asked on the mailing list:
https://groups.google.com/forum/#!forum/zxing

### Feature Requests

Feature requests are not accepted and will generally be closed.
Feature requests with a pull request may be accepted. When in doubt, discuss on the
mailing list first.

### Bug Reports
I use zxing to scan local QRcode ,it will throw ChecksumException when decode the bitmap ,but use camera it's ok, then i use      
 another app wetchat can scan the QRcode successful. The attach files is the QRcode i used .
![3633a43238ade14efb43c8cb55e01984](https://user-images.githubusercontent.com/20508702/38013299-426a78f4-3297-11e8-9d7a-f29656e798b7.jpg)

**Comment by caihuihuang** [comment]
It's my code .
private Result DistinguishQR(String imgPath) {
		/*if (TextUtils.isEmpty(imgPath)) {
			return null;
		}
		// DecodeHintType 和EncodeHintType
		Hashtable<DecodeHintType, Object> hints = new Hashtable<DecodeHintType, Object>();
		hints.put(DecodeHintType.CHARACTER_SET, "utf-8"); // 设置二维码内容的编码
		*//*hints.put(DecodeHintType.PURE_BARCODE, Boolean.TRUE);
		hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);*//*
		BitmapFactory.Options options = new BitmapFactory.Options();
		options.inJustDecodeBounds = true; // 先获取原大小
		scanBitmap = BitmapFactory.decodeFile(imgPath, options);
		options.inJustDecodeBounds = false; // 获取新的大小

		int sampleSize = (int) (options.outHeight / (float) 200);

		if (sampleSize <= 0)
			sampleSize = 1;
		options.inSampleSize = sampleSize;
		scanBitmap = BitmapFactory.decodeFile(imgPath, options);

		RGBLuminanceSource source = new RGBLuminanceSource(scanBitmap);
		BinaryBitmap bitmap1 = new BinaryBitmap(new HybridBinarizer(source));
		QRCodeReader reader = new QRCodeReader();
		try {
			return reader.decode(bitmap1, hints);
		} catch (NotFoundException e) {
			e.printStackTrace();
		} catch (ChecksumException e) {
			e.printStackTrace();
		} catch (com.google.zxing.FormatException e) {
			e.printStackTrace();
		}
}

**Comment by srowen** [comment]
This decodes fine: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F20508702%2F38013299-426a78f4-3297-11e8-9d7a-f29656e798b7.jpg

It's a problem in your code or the choice of binarizer, etc. Some settings will work for this image.

**Comment by caihuihuang** [comment]
Sorry,I'm confused. What's setting i should change?

**Comment by Tougee** [comment]
@caihuihuang  you can try [this](https://github.com/zxing/zxing/issues/995)
