### ISSUE TITLE
Scan EAN-13 with wrong results.

### ISSUE THREAD

**Issue by Kaming** [zxing/zxing#980]
Barcode Scanner version is 4.7.7,the test device is nexus7.
This situation also occurred in my application.

![img_20180328_152737](https://user-images.githubusercontent.com/9999264/38015582-ca046ed0-329e-11e8-8378-3de815404f24.jpg)

**Comment by srowen** [comment]
I think it's just a rare misread. This image decodes correctly when I send it to the online decoder. Just try again.
