### ISSUE TITLE
Create QR with Standard ISO/IEC-18004

### ISSUE THREAD

**Issue by FeMexico** [zxing/zxing#984]
I’m trying to create a project in java for Create a QR but whit ISO/IEC-18004
I don’t have a lot of experience and I’m using:  https://github.com/zxing/zxing/tree/master/core/src/main/java/com/google/zxing/qrcode

In the Encoder.java, the next method say: cannot find GS_FORMAT
boolean hasGS1FormatHint = hints != null && hints.containsKey(EncodeHintType.GS1_FORMAT);
if (hasGS1FormatHint && Boolean.valueOf(hints.get(EncodeHintType.GS1_FORMAT).toString())) {
          GS1 formatted codes are prefixed with a FNC1 in first position mode header
            appendModeInfo(Mode.FNC1_FIRST_POSITION, headerBits);
}

And in the:
Version version;
if (hints != null && hints.containsKey(EncodeHintType.QR_VERSION)) {
    int versionNumber = Integer.parseInt(hints.get(EncodeHintType.QR_VERSION).toString());
    version = Version.getVersionForNumber(versionNumber);
    int bitsNeeded = calculateBitsNeeded(mode, headerBits, dataBits, version);
    if (!willFit(bitsNeeded, version, ecLevel)) {
        throw new WriterException("Data too big for requested version");
    }
} else {
    version = recommendVersion(ecLevel, mode, headerBits, dataBits);
}
Say: cannot find QR_VERSION
I have core.3.2.1

By other hand i can’t create the QR´s File with the next java:
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

public class BarcodeGeneratorUtil {   
    private static final int qr_image_width = 300;
    private static final int qr_image_height = 300;

    public void createBarCode(String location, String barcodeName, String content) throws     WriterException{
        QRCode code = new QRCode();
        Encoder enCode = new Encoder();
        code = enCode.encode(content, ErrorCorrectionLevel.M);
        QRCodeWriter qrCodeWritter = new QRCodeWriter();        
        BitMatrix biteMatrix = qrCodeWritter.encode(content, BarcodeFormat.QR_CODE, qr_image_width, qr_image_height);
BufferedImage image = new BufferedImage(biteMatrix.getWidth(), biteMatrix.getWidth(), BufferedImage.TYPE_INT_RGB);
        image.createGraphics();
        
        Graphics2D graphics = (Graphics2D) image.getGraphics();
        graphics.setColor(Color.BLACK);
        graphics.fillRect(0, 0, biteMatrix.getRowSize(), biteMatrix.getRowSize());
        for (int i=0; i<biteMatrix.getWidth(); i++) {
            for (int j=0; j<biteMatrix.getWidth(); j++) {
                if (byteMatrix.get(i, j) { // here is a problem but byteMatrix.get(x, y);
                    graphics.fillRect(i, j, 1, 1);
                }
            }            
        }
try {  
barcode.setData("Anything to write here is for create a QR with Standard ISO/IEC-18004”);
} catch (Exception e) {
e.printStackTrace();
}

I ask you your help and thanks for your attention
Or is there a better way to create a QR code having the standart: “ISO/IEC-18004” using  the libraries zxing.?

Ricardo Curiel
femexico1@gmail.com

**Comment by srowen** [comment]
I can't figure out what you are asking. Sounds like you have a software project that hasn't expressed dependencies correctly. Nothing to do with this project.
