### ISSUE TITLE
Wrong datamatrix barcode using asterisks

### ISSUE THREAD

**Issue by DevHammer2016** [zxing/zxing#986]
When using asterisks a wrong datamatrix barcode is rendered.

Using ZXing 3.3.2 and Java 8.

Example:
`com.google.zxing.client.j2se.MatrixToImageWriter.toBufferedImage(new com.google.zxing.MultiFormatWriter().encode("**10074938*Q6000*P85005-FLT003*RA*0*K110775*VKAR99AL*1T100749381**",com.google.zxing.BarcodeFormat.DATA_MATRIX,200,200))`

Input string:
`**10074938*Q6000*P85005-FLT003*RA*0*K110775*VKAR99AL*1T100749381**`

Rendered output string:
`**10074938*Q6000*P85005-FLT003*RA*0*K110775*VKAR99AL*1T1GX VSE2W6GMRRPG`

**Comment by DevHammer2016** [comment]
[Issue-986.pdf](https://github.com/zxing/zxing/files/1880700/Issue-986.pdf)

**Comment by srowen** [comment]
What does rendered output stream mean here? an example barcode would help. Do you believe the encode or decode is incorrect? You would also need to submit a pull request with the proposed fix.

**Comment by DevHammer2016** [comment]
The rendered output stream means the resulting text when scanning/reading the datamatrix barcode.
Unfortunately it deffers from the input string.
You can find example barcodes in the attached Issue-986.pdf.

**Comment by srowen** [comment]
The barcode does appear to encode "**10074938*Q6000*P85005-FLT003*RA*0*K110775*VKAR99AL*1T1GX VSE2W6GMRRPG" correctly; I tried https://online-barcode-reader.inliteresearch.com/ for example as well.

But I also generated a barcode with this library with the same input, and it's not the same as your barcode. It decodes correctly to the input text. I think you are using a different library or and old version to encode/decode.

![out](https://user-images.githubusercontent.com/822522/38427717-9d7d59c0-397f-11e8-99f3-3d3f9d192f87.png)

**Comment by DevHammer2016** [comment]
The text you encoded the barcode with is not the correct one which I used.
I generated the barcode with:
**10074938*Q6000*P85005-FLT003*RA*0*K110775*VKAR99AL*1T100749381**
and the resulting datamatrix is wrong.
I'm using the latest version 3.3.2 and Java 8.
Running with Java 7 the barcode is correct.
So this is definitely a bug.
Or maybe a problem with other libraries integrated in JasperReports Server.

**Comment by srowen** [comment]
No, I'm saying that the barcode does encode text ending with "RRPG", so it's not a decode issue. But, I also can't reproduce this on the latest code. Try running the `CommandLineEncoder` in `master` to encode your string ending in `381**`. The result decodes as that same string. It might have been fixed by https://github.com/zxing/zxing/commit/a3bbebccba25273c5229d0904478a31eb9eecac9 so try master

**Comment by DevHammer2016** [comment]
I've just built the master jars and ran with v3.3.3.
Even with this latest source the string is wrong encoded to data matrix barcode.
Please see newly attached pdf for details.
[Issue-986-2.pdf](https://github.com/zxing/zxing/files/1888718/Issue-986-2.pdf)

**Comment by DevHammer2016** [comment]
[Result-in-iReport.pdf](https://github.com/zxing/zxing/files/1888771/Result-in-iReport.pdf)
[Result-in-JasperReportsServer.pdf](https://github.com/zxing/zxing/files/1888772/Result-in-JasperReportsServer.pdf)

**Comment by DevHammer2016** [comment]
Result with CommandLineEncoder ist correct!

![out](https://user-images.githubusercontent.com/21060712/38484963-89922372-3bd8-11e8-90d4-004456a0ffcb.png)

**Comment by DevHammer2016** [comment]
CommandLineEncoder Test ran with Java 8u51 (bundled with JasperReports Server) AND Java 8u161.

**Comment by DevHammer2016** [comment]
Maybe it's a correlation with other libraries integrated in JasperReports Server.
Attaching a list of all JasperReports Server Libraries.
[JasperReportsServerLibs.txt](https://github.com/zxing/zxing/files/1888872/JasperReportsServerLibs.txt)

**Comment by DevHammer2016** [comment]
Maybe I've found the correlation.
JasperReports Server already bundles ZXing 2.3.0 (core-2.3.0.jar).
I'm just trying to eliminate that ...

**Comment by DevHammer2016** [comment]
Ok, that's it! :)
Removing the older zxing version already bundled with JRS fixed this issue.
