### ISSUE TITLE
Can't Read EAN Barcode

### ISSUE THREAD

**Issue by noman404** [zxing/zxing#988]
I can't read this [type of barcode](https://ibb.co/gEr6Wc), though it's also an EAN type. Tried on an Android device with your sample app on google play.  What do you suggest? implement new library and then try or is there any limitation of this library for that type of barcode.

**Comment by srowen** [comment]
https://zxing.org/w/decode?u=https%3A%2F%2Fimage.ibb.co%2FiQ1Ujx%2Fisbn_with_price.png

This decodes fine, including with the app.

**Comment by noman404** [comment]
Please have a look at your decode data it could not read the add-on part with 5 digits.

**Comment by srowen** [comment]
That part is optional. It can be read, but might not be read in every image.

**Comment by noman404** [comment]
Understood thanks !!! @srowen
