### ISSUE TITLE
WebView disappear after pressing home button and re-enter the app

### ISSUE THREAD

**Issue by calbee633810** [zxing/zxing#989]
### Bug Reports
Steps to reproduce:
1. Click Help in menu
2. Press home button and re-enter the app

WebView disappear but it should persist there.

![screen shot 2018-04-12 at 11 04 32 pm](https://user-images.githubusercontent.com/38213896/38686013-e7c01178-3ea5-11e8-849e-57b7f0355581.png)
Screenshot before pressing home button and re-enter app

![screen shot 2018-04-12 at 11 04 41 pm](https://user-images.githubusercontent.com/38213896/38686029-f155377c-3ea5-11e8-91ec-073cfa43d108.png)
Screenshot after pressing home button and re-enter app

Tested on Android 23 with Nexus 4 emulator

**Comment by srowen** [comment]
The behavior is on purpose. I assume that people want to scan whenever they reenter the app, and presenting a screen they were on potentially a long time ago could be confusing.
