### ISSUE TITLE
Unlicensed use of ZXing

### ISSUE THREAD

**Issue by Ranguvar** [zxing/zxing#992]
Hello ZXing team,

I just wanted to make you aware that the Waltonchain project (https://www.waltonchain.org/) is using your library without attribution.

The software 'WTCSetup1.17.exe" hosted here: https://github.com/WaltonChain/WaltonWallet_Win_x64

has been downloaded tens or hundreds of thousands of times, it is their node software and wallet.

While looking at the installed software, I became aware that they are using the code of no less than four separate software projects without obeying terms of licensing, even attribution.

Please let me know if I can assist in any way further.

**Comment by srowen** [comment]
Thanks for that. I'm not able to evaluate this myself, but take your word for it for the sake of argument. Yeah there are so many pieces of software out there that don't quite get licensing right. It's impossible to police, but still worth calling out where it's seen. In my experience 99% of cases are oversights of course.

I will send a message to the email address on their site, and anyone is welcome to do the same kind of thing if they spot issues like this in the wild.

**Comment by codebude** [comment]
Hi @srowen - did you get any answer? I'm still waiting, but saw that you closed your issue.

**Comment by srowen** [comment]
Not yet, I'll follow up. But I think that's the only action that falls out of this issue.

**Comment by codebude** [comment]
Hm sound like a lie. I downloaded the official client from their website and it's containing our libs. If it would be only their Github repository I could understand it. But the client, released on their website, isn't markes as alpha, etc. ...

**Comment by Ranguvar** [comment]
Right, they call this their public release and it is being used by 3620 nodes active right now according to http://waltonchain.net/#/main

I also contacted AForge .NET Framework to make them aware, as well as https://github.com/karalabe at  the Ethereum Foundation, whose go-ethereum which is the primary piece in their software.
