### ISSUE TITLE
Android: stored QR Code can´t be read but scanned - MultiFormatReader.decode(bitmap) returns null

### ISSUE THREAD

**Issue by omdespers** [zxing/zxing#995]
**Description of the problem:**

Some qr-codes can´t be decoded via MultiFormatReader or QRCodeReader with the method decode(bitmap). But the same qr-codes are scannable via IntentIntegrator(). The reader.decode(bitmap) method returns a null Result. This happens on both Android and Java application, scannable but not decodable. I tried to exclude some chars, but that´s not the problem. Wether chars, nor the length ist the problem. It seems it is the combination. Used the same chars in another order in hundreds of tries and it worked, only a few barcodes have the problem.

**Wich library you are using**
com.journeyapps:zxing-android-embedded:3.5.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
Android 5.0)**
Xiaomi Mi Mix 2
MIUI 9.3
Android 8.0.0

**Does the same happen on other devices or an emulator?**
Yes, build a Java application, same problem here

**Can you reproduce the issue in the sample project included with the library? If not, can you
provide your own sample project or sample code that produces this error?**

    public static String readQRImage(File file) {

    BitmapFactory.Options options = new BitmapFactory.Options();
    options.inPreferredConfig = Bitmap.Config.ARGB_8888;
    Bitmap bMap = BitmapFactory.decodeFile(file.getAbsolutePath(), options);

    String contents = null;

    int[] intArray = new int[bMap.getWidth() * bMap.getHeight()];

    bMap.getPixels(intArray, 0, bMap.getWidth(), 0, 0, bMap.getWidth(), bMap.getHeight());

    LuminanceSource source = new RGBLuminanceSource(bMap.getWidth(), bMap.getHeight(), intArray);
    BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
    Log.d("TEST", "ARRAY:" + intArray.length + " source:" + bitmap.getWidth());

    Reader reader = new MultiFormatReader();
    Reader reader2 = new QRCodeReader();
    try {

        Result result = reader.decode(bitmap);
        contents = result.getText();
    } catch (Exception e) {
        Log.e("QrTest", "Error decoding barcode", e);
    }
    return contents;
   }
It failes at reader.decode(bitmap); The BinaryBitmap is not null, it has height and width.

**In the case of an error do you have a stack trace or adb logs?
04-20 07:56:42.067 16049-16049/omdandroid.com.syc W/System.err: **

com.google.zxing.NotFoundException

reader.decode(bitmap) returns a Result which is null. The issue is also added to android ZXing lib here:

https://github.com/journeyapps/zxing-android-embedded/issues/388

Barcode which is scannable but not decodable attached.
![bbbb](https://user-images.githubusercontent.com/35189194/39036765-d4908d2e-447e-11e8-879f-86db2f5e6d82.png)

**Comment by srowen** [comment]
This decodes fine: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F35189194%2F39036765-d4908d2e-447e-11e8-879f-86db2f5e6d82.png

It may be that you need to use 'pure barcode' mode to scan it.

**Comment by omdespers** [comment]
Exactly, thanks. Example (in case for same problems for others)

    public static String readQRImage(File file) {

        
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inPreferredConfig = Bitmap.Config.ARGB_8888;
        Bitmap bMap = BitmapFactory.decodeFile(file.getAbsolutePath(), options);


        String contents = null;

        int[] intArray = new int[bMap.getWidth() * bMap.getHeight()];

        bMap.getPixels(intArray, 0, bMap.getWidth(), 0, 0, bMap.getWidth(), bMap.getHeight());

        LuminanceSource source = new RGBLuminanceSource(bMap.getWidth(), bMap.getHeight(), intArray);
        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

        Reader reader = new MultiFormatReader();
        Reader reader2 = new QRCodeReader();
        try {

            Map<DecodeHintType,Object> tmpHintsMap = new EnumMap<DecodeHintType, Object>(DecodeHintType.class);
            tmpHintsMap.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
            tmpHintsMap.put(DecodeHintType.POSSIBLE_FORMATS, EnumSet.allOf(BarcodeFormat.class));
            tmpHintsMap.put(DecodeHintType.PURE_BARCODE, Boolean.FALSE);

            Result result = reader.decode(bitmap, tmpHintsMap);
            contents = result.getText();
        } catch (Exception e) {
            Log.e("QrTest", "Error decoding barcode", e);
            e.printStackTrace();
        }
        return contents;
    }

**Comment by Tougee** [comment]
I fixed this by only add 
```kotlin
tmpHintsMap[DecodeHintType.TRY_HARDER] = true
```
and using QRCodeReader is faster than MultiFormatReader

**Comment by steelbytes** [comment]
I just wanna say: Thank you so much :-) 

this does make me think that zxing should set tryHarder to true by default … this must trip up a lot of other devs

**Comment by srowen** [comment]
Yeah wouldn't be a bad idea. It improves decoding a little. When phones were like 100x slower 11 years ago it didn't make sense; fail fast on one frame and try the next. Now with lots of CPU might make sense.
