### ISSUE TITLE
Oreo icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [zxing/zxing#996]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by srowen** [comment]
If you're able to design and submit a new icon scheme in a PR, I'll take a look, but otherwise not going to happen.

**Comment by c-e-p-x-u-o** [comment]
Really it's not a design but just a shape of the icon's background.

**Comment by c-e-p-x-u-o** [comment]
But I'll try to help, as you ask.

**Comment by srowen** [comment]
Yeah, though I figure just chopping a circle from the icon wouldn't look great. Maybe surround it with a circle but then it gets small. It's for better or worse such a well known icon that I'm reluctant to change it, but, if it's a pretty good and recognizable take on the existing icon, could be fine.

**Comment by c-e-p-x-u-o** [comment]
ok, I'll try to make a concept

**Comment by marescamichael2** [comment]
Thanks
