### ISSUE TITLE
Some decoding is very slow like the following QR code

### ISSUE THREAD

**Issue by MrBoudar** [zxing/zxing#999]
![qq 20180417160604](https://user-images.githubusercontent.com/17286695/39236102-54ec8304-48aa-11e8-8747-9559faa9f782.png)

**Comment by MrBoudar** [comment]
Fortunately for others, this scan is slow

**Comment by srowen** [comment]
It's the color gradient. This isn't standard and too far from dark in parts

**Comment by MrBoudar** [comment]
well,it's ok
